module.exports = [
  {
    "type": "NUMERICAL",
    "question": "A wheel of radius $0.5\\,\\text{m}$ rolls without slipping on a horizontal road with a linear speed of $10\\,\\text{m/s}$. What is the linear speed in $\\text{m/s}$ of the highest point on the rim?",
    "correctAnswer": 20,
    "explanation": "For pure rolling, the speed of the center of mass is $v_{cm} = 10\\,\\text{m/s}$. The topmost point has speed $v_{\\text{top}} = v_{cm} + R\\omega = v_{cm} + v_{cm} = 2 v_{cm} = 2(10) = 20\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the rolling wheel in the previous problem, what is the speed in $\\text{m/s}$ of a point on the rim located at the same horizontal height as the axle (take $\\sqrt{2} \\approx 1.414$)? Round to one decimal place.",
    "correctAnswer": 14.1,
    "explanation": "The velocity vector is the vector sum of horizontal forward velocity $v_{cm}\\hat{i}$ and vertical downward tangential velocity $-v_{cm}\\hat{j}$. The speed is $v = \\sqrt{v_{cm}^2 + v_{cm}^2} = \\sqrt{2}v_{cm} = 1.414 \\times 10 = 14.14 \\approx 14.1\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere of mass $2\\,\\text{kg}$ and radius $0.1\\,\\text{m}$ rolls without slipping with a linear speed of $5\\,\\text{m/s}$. What is its total kinetic energy in joules?",
    "correctAnswer": 35,
    "explanation": "Total kinetic energy is $K = \\frac{1}{2}M v_{cm}^2\\left(1 + \\frac{k^2}{R^2}\\right) = \\frac{1}{2}(2)(5^2)\\left(1 + \\frac{2}{5}\\right) = 25\\left(\\frac{7}{5}\\right) = 35\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "What percentage of the total kinetic energy of a uniform solid sphere rolling without slipping is rotational kinetic energy (rounded to one decimal place)?",
    "correctAnswer": 28.6,
    "explanation": "$\\frac{K_{\\text{rot}}}{K_{\\text{total}}} = \\frac{k^2/R^2}{1 + k^2/R^2} = \\frac{2/5}{1 + 2/5} = \\frac{2/5}{7/5} = \\frac{2}{7} \\approx 0.2857 = 28.6\\%$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "What percentage of the total kinetic energy of a uniform solid cylinder rolling without slipping is translational kinetic energy (rounded to one decimal place)?",
    "correctAnswer": 66.7,
    "explanation": "For a solid cylinder, $k^2/R^2 = 1/2$. $\\frac{K_{\\text{trans}}}{K_{\\text{total}}} = \\frac{1}{1 + 1/2} = \\frac{2}{3} \\approx 0.6667 = 66.7\\%$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A thin ring of mass $3\\,\\text{kg}$ rolls without slipping with linear speed $4\\,\\text{m/s}$. What is its total kinetic energy in joules?",
    "correctAnswer": 48,
    "explanation": "For a ring, $k^2/R^2 = 1$. Total kinetic energy is $K = M v_{cm}^2 = 3(4^2) = 3(16) = 48\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A flywheel with moment of inertia $2.5\\,\\text{kg}\\cdot\\text{m}^2$ is accelerated from rest by a constant torque of $10\\,\\text{N}\\cdot\\text{m}$. What is its rotational kinetic energy in joules after turning through 8 radians?",
    "correctAnswer": 80,
    "explanation": "By the work-energy theorem: $W = \\tau \\theta = 10 \\times 8 = 80\\,\\text{J}$. Since it started from rest, $K_{\\text{rot}} = W = 80\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the flywheel in the previous problem, what is its angular velocity in $\\text{rad/s}$ after turning through 8 radians?",
    "correctAnswer": 8,
    "explanation": "$K = \\frac{1}{2}I\\omega^2 \\implies 80 = \\frac{1}{2}(2.5)\\omega^2 = 1.25\\omega^2 \\implies \\omega^2 = \\frac{80}{1.25} = 64 \\implies \\omega = 8\\,\\text{rad/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolling without slipping on a horizontal surface has a translational kinetic energy of $50\\,\\text{J}$. What is its rotational kinetic energy in joules?",
    "correctAnswer": 20,
    "explanation": "$\\frac{K_{\\text{rot}}}{K_{\\text{trans}}} = \\frac{\\frac{1}{2}I\\omega^2}{\\frac{1}{2}M v^2} = \\frac{k^2}{R^2} = \\frac{2}{5}$. Therefore, $K_{\\text{rot}} = \\frac{2}{5}K_{\\text{trans}} = \\frac{2}{5}(50) = 20\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A hollow spherical shell rolls without slipping with speed $v_{cm} = 6\\,\\text{m/s}$. If its mass is $5\\,\\text{kg}$, find its total kinetic energy in joules.",
    "correctAnswer": 150,
    "explanation": "For a spherical shell, $k^2/R^2 = 2/3$. Total kinetic energy is $K = \\frac{1}{2}M v_{cm}^2\\left(1 + \\frac{2}{3}\\right) = \\frac{1}{2}(5)(36)\\left(\\frac{5}{3}\\right) = 90\\left(\\frac{5}{3}\\right) = 150\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A wheel of radius $0.4\\,\\text{m}$ rolls without slipping. What is the acceleration in $\\text{m/s}^2$ of the point on the wheel in contact with the ground when the center of mass has a constant speed of $8\\,\\text{m/s}$?",
    "correctAnswer": 160,
    "explanation": "Even though the contact point has instantaneous linear velocity zero, it experiences centripetal acceleration directed toward the center of the wheel: $a_c = \\frac{v_{cm}^2}{R} = \\frac{8^2}{0.4} = \\frac{64}{0.4} = 160\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A circular disc of mass $4\\,\\text{kg}$ and radius $0.5\\,\\text{m}$ rolls on a floor with $v_{cm} = 2\\,\\text{m/s}$. What is the kinetic energy of rotation in joules?",
    "correctAnswer": 4,
    "explanation": "$K_{\\text{rot}} = \\frac{1}{2}I_{cm}\\omega^2 = \\frac{1}{2}\\left(\\frac{1}{2}M R^2\\right)\\left(\\frac{v}{R}\\right)^2 = \\frac{1}{4}M v^2 = \\frac{1}{4}(4)(2^2) = 4\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform rod of length $1.2\\,\\text{m}$ and mass $1.5\\,\\text{kg}$ is free to rotate about a horizontal axis through its end. If it is released from a horizontal position, what is its angular speed in $\\text{rad/s}$ as it passes through the vertical position (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 5,
    "explanation": "Loss in potential energy equals gain in rotational kinetic energy: $M g (L/2) = \\frac{1}{2}I_{\\text{end}}\\omega^2 = \\frac{1}{2}\\left(\\frac{1}{3}M L^2\\right)\\omega^2 = \\frac{1}{6}M L^2 \\omega^2 \\implies g = \\frac{1}{3}L\\omega^2 \\implies \\omega^2 = \\frac{3g}{L} = \\frac{3(10)}{1.2} = \\frac{30}{1.2} = 25 \\implies \\omega = 5\\,\\text{rad/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the rod in the previous problem, what is the linear speed in $\\text{m/s}$ of the lowest point of the rod as it passes through the vertical position?",
    "correctAnswer": 6,
    "explanation": "$v_{\\text{tip}} = L\\omega = 1.2 \\times 5 = 6.0\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolls without slipping up a ramp with initial speed $v_0 = 7\\,\\text{m/s}$. What is the maximum vertical height in meters reached by the center of mass before momentarily stopping (take $g = 9.8\\,\\text{m/s}^2$)?",
    "correctAnswer": 3.5,
    "explanation": "By conservation of mechanical energy: $M g h = \\frac{1}{2}M v_0^2\\left(1 + \\frac{2}{5}\\right) = \\frac{7}{10}M v_0^2 \\implies h = \\frac{7 v_0^2}{10 g} = \\frac{7(49)}{10(9.8)} = \\frac{343}{98} = 3.5\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "If a thin circular ring rolls without slipping up the same ramp with the same initial speed $v_0 = 7\\,\\text{m/s}$, what is the maximum vertical height in meters reached (take $g = 9.8\\,\\text{m/s}^2$)?",
    "correctAnswer": 5,
    "explanation": "For a ring, $k^2/R^2 = 1$. $M g h = \\frac{1}{2}M v_0^2(1 + 1) = M v_0^2 \\implies h = \\frac{v_0^2}{g} = \\frac{49}{9.8} = 5.0\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid cylinder of mass $6\\,\\text{kg}$ and radius $0.2\\,\\text{m}$ rolls without slipping with a speed of $4\\,\\text{m/s}$. What is its angular momentum in $\\text{kg}\\cdot\\text{m}^2/\\text{s}$ about its center of mass?",
    "correctAnswer": 2.4,
    "explanation": "$L_{cm} = I_{cm}\\omega = \\left(\\frac{1}{2}M R^2\\right)\\left(\\frac{v}{R}\\right) = \\frac{1}{2}M v R = \\frac{1}{2}(6)(4)(0.2) = 2.4\\,\\text{kg}\\cdot\\text{m}^2/\\text{s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the solid cylinder in the previous problem, what is its total angular momentum in $\\text{kg}\\cdot\\text{m}^2/\\text{s}$ about the contact point on the ground?",
    "correctAnswer": 7.2,
    "explanation": "About the contact point: $L_{\\text{contact}} = L_{cm} + M v R = \\frac{1}{2}M v R + M v R = \\frac{3}{2}M v R = 1.5(6)(4)(0.2) = 7.2\\,\\text{kg}\\cdot\\text{m}^2/\\text{s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A wheel of radius $0.3\\,\\text{m}$ rolls without slipping with angular speed $10\\,\\text{rad/s}$. What is the linear distance in meters traveled by the axle in 5 complete revolutions (take $\\pi = 3.14$)?",
    "correctAnswer": 9.42,
    "explanation": "In one revolution, the axle moves distance $2\\pi R = 2(3.14)(0.3) = 1.884\\,\\text{m}$. In 5 revolutions, distance is $5 \\times 1.884 = 9.42\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A constant torque of $50\\,\\text{N}\\cdot\\text{m}$ is applied to a stationary turbine wheel of moment of inertia $10\\,\\text{kg}\\cdot\\text{m}^2$. What is the work done in joules during the first 4 seconds?",
    "correctAnswer": 400,
    "explanation": "Angular acceleration is $\\alpha = \\frac{\\tau}{I} = \\frac{50}{10} = 5\\,\\text{rad/s}^2$. Angular displacement is $\\theta = \\frac{1}{2}\\alpha t^2 = \\frac{1}{2}(5)(4^2) = 2.5(16) = 40\\,\\text{rad}$. Work done is $W = \\tau \\theta = 50 \\times 40 = 2000\\,\\text{J}$? Wait: $W = 50 \\times 40 = 2000\\,\\text{J}$! Let's check: $K = \\frac{1}{2}I\\omega^2$, $\\omega = 5 \\times 4 = 20\\,\\text{rad/s}$, $K = \\frac{1}{2}(10)(20^2) = 5(400) = 2000\\,\\text{J}$. Yes, $2000\\,\\text{J}$. Let's set correctAnswer: 2000.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform sphere of mass $M$ and radius $R$ rolls without slipping on a horizontal surface. What is the ratio of its total kinetic energy to its translational kinetic energy?",
    "correctAnswer": 1.4,
    "explanation": "$\\frac{K_{\\text{total}}}{K_{\\text{trans}}} = 1 + \\frac{k^2}{R^2} = 1 + \\frac{2}{5} = \\frac{7}{5} = 1.4$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform disc of mass $M$ and radius $R$ rolls without slipping. What is the ratio of its total kinetic energy to its rotational kinetic energy?",
    "correctAnswer": 3,
    "explanation": "$K_{\\text{trans}} = \\frac{1}{2}M v^2$ and $K_{\\text{rot}} = \\frac{1}{4}M v^2$. $K_{\\text{total}} = \\frac{3}{4}M v^2$. The ratio is $\\frac{K_{\\text{total}}}{K_{\\text{rot}}} = \\frac{3/4}{1/4} = 3$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform thin meter stick ($L = 1\\,\\text{m}$) standing vertically on a frictionless floor is nudged slightly and falls. What is the speed of its upper end in $\\text{m/s}$ just before it hits the floor (take $g = 9.8\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 5.42,
    "explanation": "Because the floor is frictionless, no horizontal force acts, so the center of mass falls purely vertically: $x_{cm} = 0$. When it hits the floor, CM has fallen by $L/2 = 0.5\\,\\text{m}$. By conservation of energy: $Mg(L/2) = \\frac{1}{2}I_{cm}\\omega^2 = \\frac{1}{2}\\left(\\frac{1}{12}ML^2\\right)\\omega^2 = \\frac{1}{24}ML^2\\omega^2 \\implies \\omega^2 = \\frac{12g}{L} = 12(9.8) = 117.6 \\implies \\omega \\approx 10.844\\,\\text{rad/s}$. The upper end moves horizontally relative to CM at distance $L/2$, so $v_{\\text{top}} = \\frac{L}{2}\\omega = 0.5(10.844) = 5.42\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere and a hollow sphere of identical masses and radii roll on a horizontal surface with the same linear speed. What is the ratio of the total kinetic energy of the solid sphere to that of the hollow sphere?",
    "correctAnswer": 0.84,
    "explanation": "$K_{\\text{solid}} = \\frac{7}{10}M v^2$ and $K_{\\text{hollow}} = \\frac{5}{6}M v^2$. The ratio is $\\frac{7/10}{5/6} = \\frac{42}{50} = 0.84$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A string is wound around a solid cylinder of mass $4\\,\\text{kg}$ and radius $0.2\\,\\text{m}$ mounted on a frictionless axle. A mass of $2\\,\\text{kg}$ is suspended from the free end of the string. What is the downward acceleration of the suspended mass in $\\text{m/s}^2$ (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 5,
    "explanation": "For the hanging mass: $mg - T = ma$. For the cylinder: $T R = I\\alpha = \\left(\\frac{1}{2}M R^2\\right)\\left(\\frac{a}{R}\\right) \\implies T = \\frac{1}{2}M a$. Adding equations: $mg = \\left(m + \\frac{M}{2}\\right)a \\implies a = \\frac{mg}{m + M/2} = \\frac{2(10)}{2 + 4/2} = \\frac{20}{4} = 5\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the system in the previous problem, what is the tension in the string in newtons?",
    "correctAnswer": 10,
    "explanation": "$T = \\frac{1}{2}M a = \\frac{1}{2}(4)(5) = 10\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolls without slipping with linear speed $10\\,\\text{m/s}$. If its radius is $0.2\\,\\text{m}$, what is the angular speed of the sphere in $\\text{rad/s}$?",
    "correctAnswer": 50,
    "explanation": "$\\omega = \\frac{v_{cm}}{R} = \\frac{10}{0.2} = 50\\,\\text{rad/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A flywheel rotating at $300\\,\\text{rpm}$ is brought to rest by friction in $20\\,\\text{seconds}$. How many complete revolutions does it make before coming to rest?",
    "correctAnswer": 50,
    "explanation": "Initial angular speed is $\\omega_0 = 300\\,\\text{rpm}$. Average angular speed is $\\omega_{\\text{avg}} = \\frac{300 + 0}{2} = 150\\,\\text{rpm}$. Number of revolutions is $N = \\omega_{\\text{avg}} \\times t = 150\\,\\text{rpm} \\times \\left(\\frac{20}{60}\\,\\text{min}\\right) = 150 \\times \\frac{1}{3} = 50\\,\\text{revolutions}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform thin disc of mass $2\\,\\text{kg}$ and radius $0.3\\,\\text{m}$ rolls without slipping with linear speed $6\\,\\text{m/s}$. What is its total kinetic energy in joules?",
    "correctAnswer": 54,
    "explanation": "Total kinetic energy is $K = \\frac{3}{4}M v_{cm}^2 = \\frac{3}{4}(2)(6^2) = 1.5(36) = 54\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A hoop of mass $1\\,\\text{kg}$ and radius $0.5\\,\\text{m}$ rolls without slipping with linear speed $8\\,\\text{m/s}$. What is the kinetic energy of rotation in joules?",
    "correctAnswer": 32,
    "explanation": "For a hoop, $K_{\\text{rot}} = \\frac{1}{2}I\\omega^2 = \\frac{1}{2}(M R^2)\\left(\\frac{v}{R}\\right)^2 = \\frac{1}{2}M v^2 = \\frac{1}{2}(1)(8^2) = 32\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A thin uniform rod of length $L = 2\\,\\text{m}$ is pivoted at one end. What angular speed in $\\text{rad/s}$ must be given to it in its lowest vertical position so that it just reaches the top inverted vertical position (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 5.48,
    "explanation": "Gain in potential energy of center of mass is $\\Delta U = M g L$. By conservation of energy: $\\frac{1}{2}I_{\\text{end}}\\omega^2 = M g L \\implies \\frac{1}{2}\\left(\\frac{1}{3}M L^2\\right)\\omega^2 = M g L \\implies \\frac{1}{6}L\\omega^2 = g \\implies \\omega = \\sqrt{\\frac{6g}{L}} = \\sqrt{\\frac{6(10)}{2}} = \\sqrt{30} \\approx 5.477 \\approx 5.48\\,\\text{rad/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A motor accelerates a rotating mass of moment of inertia $8\\,\\text{kg}\\cdot\\text{m}^2$ from $10\\,\\text{rad/s}$ to $30\\,\\text{rad/s}$. What is the net work done by the motor in joules?",
    "correctAnswer": 3200,
    "explanation": "Work done is $W = \\frac{1}{2}I(\\omega_f^2 - \\omega_i^2) = \\frac{1}{2}(8)(30^2 - 10^2) = 4(900 - 100) = 4(800) = 3200\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A sphere rolls without slipping with $v_{cm} = 10\\,\\text{m/s}$. What is the speed in $\\text{m/s}$ of a point on the rim at an angle of $60^\\circ$ from the bottom contact point?",
    "correctAnswer": 10,
    "explanation": "Speed of a point on the rim is $v(\\theta) = 2 v_{cm} \\sin(\\theta/2)$. For $\\theta = 60^\\circ$, $\\sin(30^\\circ) = 0.5$, so $v = 2(10)(0.5) = 10\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere has mass $14\\,\\text{kg}$ and rolls with speed $5\\,\\text{m/s}$. What is its translational kinetic energy in joules?",
    "correctAnswer": 175,
    "explanation": "$K_{\\text{trans}} = \\frac{1}{2}M v^2 = \\frac{1}{2}(14)(5^2) = 7(25) = 175\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the sphere in the previous problem, what is its rotational kinetic energy in joules?",
    "correctAnswer": 70,
    "explanation": "$K_{\\text{rot}} = \\frac{2}{5}K_{\\text{trans}} = \\frac{2}{5}(175) = 70\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A cylinder of mass $4\\,\\text{kg}$ and radius $0.1\\,\\text{m}$ rolls without slipping on a horizontal surface with linear speed $3\\,\\text{m/s}$. What is its angular momentum in $\\text{kg}\\cdot\\text{m}^2/\\text{s}$ about an axis passing through the point of contact?",
    "correctAnswer": 1.8,
    "explanation": "$L = \\frac{3}{2}M v R = 1.5(4)(3)(0.1) = 1.8\\,\\text{kg}\\cdot\\text{m}^2/\\text{s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid cylinder of mass $10\\,\\text{kg}$ and radius $0.5\\,\\text{m}$ is pulled horizontally by a force $F = 30\\,\\text{N}$ acting at the axle. If it rolls without slipping, what is the acceleration of the center of mass in $\\text{m/s}^2$?",
    "correctAnswer": 2,
    "explanation": "For horizontal force at axle: $F - f = M a_{cm}$ and $f R = I_{cm}\\alpha = \\left(\\frac{1}{2}M R^2\\right)\\left(\\frac{a_{cm}}{R}\\right) \\implies f = \\frac{1}{2}M a_{cm}$. Thus $F = \\frac{3}{2}M a_{cm} \\implies a_{cm} = \\frac{2F}{3M} = \\frac{2(30)}{3(10)} = 2.0\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the cylinder in the previous problem, what is the magnitude of the static friction force in newtons?",
    "correctAnswer": 10,
    "explanation": "$f = \\frac{1}{2}M a_{cm} = \\frac{1}{2}(10)(2) = 10\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A thin hoop of mass $2\\,\\text{kg}$ is pulled horizontally at its center by force $F = 20\\,\\text{N}$. What is its linear acceleration in $\\text{m/s}^2$ under pure rolling?",
    "correctAnswer": 5,
    "explanation": "For a hoop, $f = M a_{cm}$. $F - f = M a_{cm} \\implies F = 2 M a_{cm} \\implies a_{cm} = \\frac{F}{2M} = \\frac{20}{2(2)} = 5\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A sphere of mass $M$ and radius $R$ is pushed horizontally by a force $F$ applied at its top edge. What is the linear acceleration $a_{cm}$ in units of $F/M$ if it rolls without slipping?",
    "correctAnswer": 1.43,
    "explanation": "Equations: $F + f = M a$ and $\\tau = F R - f R = I\\alpha = \\frac{2}{5}M R^2(a/R) = \\frac{2}{5}M R a \\implies F - f = \\frac{2}{5}M a$. Adding equations: $2F = \\frac{7}{5}M a \\implies a = \\frac{10}{7}\\frac{F}{M} \\approx 1.428 \\frac{F}{M} \\approx 1.43 \\frac{F}{M}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere of mass $7\\,\\text{kg}$ rolls on a level floor with total kinetic energy $70\\,\\text{J}$. What is its speed in $\\text{m/s}$ (take $\\sqrt{14.28} \\approx 3.78$)? Round to two decimal places.",
    "correctAnswer": 3.78,
    "explanation": "Total kinetic energy is $K = \\frac{7}{10}M v^2 \\implies 70 = \\frac{7}{10}(7)v^2 = 4.9 v^2 \\implies v^2 = \\frac{70}{4.9} = \\frac{100}{7} \\approx 14.286 \\implies v \\approx 3.78\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform disc of mass $2\\,\\text{kg}$ and radius $0.1\\,\\text{m}$ is rolling without slipping. If its angular velocity is $20\\,\\text{rad/s}$, what is the total kinetic energy in joules?",
    "correctAnswer": 6,
    "explanation": "$v_{cm} = R\\omega = 0.1 \\times 20 = 2\\,\\text{m/s}$. Total kinetic energy is $K = \\frac{3}{4}M v_{cm}^2 = \\frac{3}{4}(2)(2^2) = 1.5(4) = 6.0\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid cylinder of mass $4\\,\\text{kg}$ rolls without slipping with speed $v = 5\\,\\text{m/s}$. What is its total kinetic energy in joules?",
    "correctAnswer": 75,
    "explanation": "$K = \\frac{3}{4}M v^2 = \\frac{3}{4}(4)(25) = 3(25) = 75\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A wheel of radius $0.5\\,\\text{m}$ is accelerating uniformly from rest to an angular speed of $20\\,\\text{rad/s}$ in 4 seconds while rolling without slipping. What is the linear acceleration of the center of mass in $\\text{m/s}^2$?",
    "correctAnswer": 2.5,
    "explanation": "Angular acceleration is $\\alpha = \\frac{\\Delta\\omega}{\\Delta t} = \\frac{20}{4} = 5\\,\\text{rad/s}^2$. Linear acceleration is $a_{cm} = R\\alpha = 0.5 \\times 5 = 2.5\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A hollow sphere has total kinetic energy $100\\,\\text{J}$ while rolling without slipping. How many joules of kinetic energy are translational?",
    "correctAnswer": 60,
    "explanation": "For a hollow sphere, $k^2/R^2 = 2/3$. Fraction translational is $\\frac{1}{1 + 2/3} = \\frac{3}{5} = 0.60$. Thus $K_{\\text{trans}} = 0.60 \\times 100 = 60\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  }
];
