module.exports = [
  {
    "question": "A simple pendulum of length $1\\,\\text{m}$ oscillates on Earth. What is its time period in seconds (take $g = 9.87\\,\\text{m/s}^2$)?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "Time period is $T = 2\\pi\\sqrt{\\frac{L}{g}}$. Since $g = \\pi^2 \\approx 9.87$, $T = 2\\pi\\sqrt{\\frac{1}{\\pi^2}} = 2\\pi\\left(\\frac{1}{\\pi}\\right) = 2.0\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with amplitude $A$. At what displacement in terms of $A$ are its kinetic energy and potential energy equal?",
    "options": [],
    "correctAnswer": 0.71,
    "numericalAnswer": 0.71,
    "explanation": "$K = U \\implies \\frac{1}{2}m\\omega^2(A^2 - x^2) = \\frac{1}{2}m\\omega^2 x^2 \\implies A^2 - x^2 = x^2 \\implies 2x^2 = A^2 \\implies x = \\frac{A}{\\sqrt{2}} \\approx 0.707 A \\approx 0.71 A$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executing SHM has total mechanical energy $E = 100\\,\\text{J}$. What is its kinetic energy in joules when its displacement is $x = A/2$?",
    "options": [],
    "correctAnswer": 75,
    "numericalAnswer": 75,
    "explanation": "Potential energy at $x = A/2$ is $U = \\frac{1}{2}k(A/2)^2 = \\frac{1}{4}\\left(\\frac{1}{2}k A^2\\right) = \\frac{E}{4} = 25\\,\\text{J}$. By conservation of energy, $K = E - U = 100 - 25 = 75\\,\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "What percentage of the total energy of a particle executing SHM is potential energy at displacement $x = A/2$?",
    "options": [],
    "correctAnswer": 25,
    "numericalAnswer": 25,
    "explanation": "$\\frac{U}{E} = \\frac{\\frac{1}{2}k(A/2)^2}{\\frac{1}{2}k A^2} = \\frac{1}{4} = 25\\%$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum has time period $T = 2.0\\,\\text{s}$ on the surface of the Earth. What would be its time period in seconds on the Moon where acceleration due to gravity is $g/6$ (take $\\sqrt{6} \\approx 2.45$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 4.9,
    "numericalAnswer": 4.9,
    "explanation": "Time period is $T \\propto \\frac{1}{\\sqrt{g}}$. On the Moon: $T_{\\text{moon}} = T_{\\text{earth}} \\sqrt{\\frac{g}{g/6}} = 2.0 \\times \\sqrt{6} \\approx 2.0 \\times 2.449 = 4.898 \\approx 4.90\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of length $L$ is inside an elevator accelerating upwards with an acceleration $a = g/3$. What is the ratio of its new time period to its original time period?",
    "options": [],
    "correctAnswer": 0.87,
    "numericalAnswer": 0.87,
    "explanation": "Effective gravity is $g_{\\text{eff}} = g + a = g + g/3 = \\frac{4}{3}g$. The new period is $T' = 2\\pi\\sqrt{\\frac{L}{4g/3}} = \\sqrt{\\frac{3}{4}} T = \\frac{\\sqrt{3}}{2} T \\approx 0.866 T \\approx 0.87 T$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "If the elevator in the previous problem is accelerating downwards with $a = g/2$, what is the ratio of the new time period to the original time period (take $\\sqrt{2} \\approx 1.41$)?",
    "options": [],
    "correctAnswer": 1.41,
    "numericalAnswer": 1.41,
    "explanation": "Effective gravity is $g_{\\text{eff}} = g - a = g - g/2 = g/2$. The new period is $T' = 2\\pi\\sqrt{\\frac{L}{g/2}} = \\sqrt{2} T \\approx 1.41 T$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum suspended from the ceiling of a car has period $T$. When the car accelerates horizontally with acceleration $a = g$, the new time period is $k T$. What is the value of $k$ (take $2^{-1/4} \\approx 0.84$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 0.84,
    "numericalAnswer": 0.84,
    "explanation": "Effective gravity is $g_{\\text{eff}} = \\sqrt{g^2 + a^2} = \\sqrt{g^2 + g^2} = \\sqrt{2} g$. The new period is $T' = 2\\pi\\sqrt{\\frac{L}{\\sqrt{2}g}} = \\frac{T}{(2)^{1/4}} = 2^{-1/4} T \\approx 0.84 T$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum bob has mass $m$ and positive charge $q$. If a uniform electric field $E$ directed vertically downwards is switched on, the time period becomes $T'$. If $qE = 3mg$, find the ratio $T / T'$.",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "The effective acceleration is $g_{\\text{eff}} = g + \\frac{qE}{m} = g + 3g = 4g$. Thus $T' = 2\\pi\\sqrt{\\frac{L}{4g}} = \\frac{1}{2}\\left(2\\pi\\sqrt{\\frac{L}{g}}\\right) = \\frac{T}{2} \\implies \\frac{T}{T'} = 2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A pendulum clock has a brass rod of linear expansion coefficient $\\alpha = 2 \\times 10^{-5}\\,^\\circ\\text{C}^{-1}$. If temperature increases by $10^\\circ\\text{C}$, how many seconds does the clock lose per day?",
    "options": [],
    "correctAnswer": 8.64,
    "numericalAnswer": 8.64,
    "explanation": "Fractional change in period is $\\frac{\\Delta T}{T} = \\frac{1}{2}\\alpha \\Delta \\theta = \\frac{1}{2}(2 \\times 10^{-5})(10) = 10^{-4}$. Time lost per day is $\\Delta t = \\frac{\\Delta T}{T} \\times 86400\\,\\text{s} = 10^{-4} \\times 86400 = 8.64\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The bob of a simple pendulum of density $\\rho = 8000\\,\\text{kg/m}^3$ oscillates with period $T = 2.0\\,\\text{s}$ in air. When completely immersed in water (density $1000\\,\\text{kg/m}^3$), what is its new time period in seconds (neglecting viscosity, take $\\sqrt{8/7} \\approx 1.07$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 2.14,
    "numericalAnswer": 2.14,
    "explanation": "Effective gravity in water is $g_{\\text{eff}} = g\\left(1 - \\frac{\\rho_{\\text{water}}}{\\rho_{\\text{bob}}}\\right) = g\\left(1 - \\frac{1000}{8000}\\right) = \\frac{7}{8}g$. New period is $T' = T\\sqrt{\\frac{g}{g_{\\text{eff}}}} = 2.0\\sqrt{\\frac{8}{7}} \\approx 2.0(1.069) \\approx 2.14\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum has length $L = 0.993\\,\\text{m}$ and executes oscillations on Earth where $g = 9.8\\,\\text{m/s}^2$. What is its period in seconds (take $\\pi = 3.14$)? Round to nearest integer.",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "This is a seconds pendulum: $T = 2\\pi\\sqrt{\\frac{0.993}{9.8}} = 2(3.14)\\sqrt{0.1013} = 6.28(0.318) \\approx 2.0\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "If the length of a simple pendulum is increased by $44\\%$, find the percentage increase in its time period.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$T \\propto \\sqrt{L}$. When $L' = 1.44 L$, $T' = \\sqrt{1.44} T = 1.20 T$. The percentage increase is $(1.20 - 1) \\times 100 = 20\\%$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "If the acceleration due to gravity decreases by $4\\%$, what is the percentage increase in the time period of a simple pendulum?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "For small variations, $\\frac{\\Delta T}{T} \\approx -\\frac{1}{2}\\frac{\\Delta g}{g} = -\\frac{1}{2}(-4\\%) = +2\\%$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two simple pendulums of lengths $100\\,\\text{cm}$ and $121\\,\\text{cm}$ start oscillating simultaneously in the same phase. After how many oscillations of the shorter pendulum will they again be in phase at the starting point?",
    "options": [],
    "correctAnswer": 11,
    "numericalAnswer": 11,
    "explanation": "Ratio of periods is $\\frac{T_1}{T_2} = \\sqrt{\\frac{L_1}{L_2}} = \\sqrt{\\frac{100}{121}} = \\frac{10}{11}$. They will be in phase when $n T_1 = (n - 1) T_2 \\implies \\frac{n}{n - 1} = \\frac{T_2}{T_1} = \\frac{11}{10} \\implies 10n = 11n - 11 \\implies n = 11$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with total energy $E$. What is the ratio of its kinetic energy to potential energy at displacement $x = A/3$?",
    "options": [],
    "correctAnswer": 8,
    "numericalAnswer": 8,
    "explanation": "At $x = A/3$, $U = \\frac{1}{2}k (A/3)^2 = \\frac{E}{9}$. Kinetic energy is $K = E - U = \\frac{8}{9}E$. The ratio is $\\frac{K}{U} = \\frac{8/9}{1/9} = 8$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body of mass $100\\,\\text{g}$ executes SHM with amplitude $10\\,\\text{cm}$ and period $0.2\\,\\text{s}$. What is its total mechanical energy in joules (take $\\pi^2 = 9.87$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 0.49,
    "numericalAnswer": 0.49,
    "explanation": "Angular frequency is $\\omega = \\frac{2\\pi}{0.2} = 10\\pi\\,\\text{rad/s}$. Amplitude is $A = 0.10\\,\\text{m}$, mass $m = 0.1\\,\\text{kg}$. Total energy is $E = \\frac{1}{2}m\\omega^2 A^2 = \\frac{1}{2}(0.1)(100\\pi^2)(0.01) = 0.05\\pi^2 = 0.05(9.87) = 0.4935 \\approx 0.49\\,\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum has time period $T$. When suspended in an artificial satellite in circular orbit around the Earth, what is its time period (in seconds, enter 0 for infinite)?",
    "options": [],
    "correctAnswer": 0,
    "numericalAnswer": 0,
    "explanation": "Inside an orbiting satellite, the satellite and pendulum are in state of free fall, so effective gravity is $g_{\\text{eff}} = 0$. Thus $T = 2\\pi\\sqrt{\\frac{L}{0}} \\to \\infty$ (it does not oscillate, period is infinite). Entering 0 as designated.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "At what displacement in centimeters from the mean position is the kinetic energy of a simple harmonic oscillator equal to 3 times its potential energy, given amplitude $A = 8\\,\\text{cm}$?",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$K = 3U \\implies E - U = 3U \\implies 4U = E \\implies 4\\left(\\frac{1}{2}k x^2\\right) = \\frac{1}{2}k A^2 \\implies 4x^2 = A^2 \\implies x = A/2 = 8/2 = 4\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of length $L$ oscillates with an angular amplitude of $\\theta_0 = 60^\\circ$. What is the tension in the string in terms of $mg$ when the bob passes through the lowest mean position?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "By conservation of energy: $m g L (1 - \\cos 60^\\circ) = \\frac{1}{2}m v^2 \\implies v^2 = 2gL(1 - 0.5) = gL$. At the lowest point, tension provides centripetal acceleration: $T - mg = \\frac{mv^2}{L} = \\frac{m(gL)}{L} = mg \\implies T = 2mg$. The factor is 2.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with amplitude $A$. What is its average potential energy over one complete cycle in terms of total energy $E$?",
    "options": [],
    "correctAnswer": 0.5,
    "numericalAnswer": 0.5,
    "explanation": "The time average of potential energy over one full cycle is $\\langle U \\rangle_t = \\frac{1}{4}k A^2 = \\frac{1}{2}E = 0.5 E$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "What is the average kinetic energy of a particle in SHM over position (space average from $x = -A$ to $+A$) in terms of total energy $E$ (as a decimal rounded to two decimal places)?",
    "options": [],
    "correctAnswer": 0.67,
    "numericalAnswer": 0.67,
    "explanation": "Position average is $\\langle K \\rangle_x = \\frac{1}{2A}\\int_{-A}^A \\frac{1}{2}k(A^2 - x^2)dx = \\frac{k}{4A}\\left[A^2(2A) - \\frac{2A^3}{3}\\right] = \\frac{k}{4A}\\left(\\frac{4A^3}{3}\\right) = \\frac{1}{3}k A^2 = \\frac{2}{3}\\left(\\frac{1}{2}k A^2\\right) = \\frac{2}{3}E \\approx 0.67 E$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum has time period $T_1$ on the Earth's surface and $T_2$ at an altitude equal to the radius of the Earth $R_E$. What is the ratio $T_2 / T_1$?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "At height $h = R_E$, $g' = g\\left(\\frac{R_E}{R_E + h}\\right)^2 = g\\left(\\frac{R_E}{2R_E}\\right)^2 = \\frac{g}{4}$. Therefore $T_2 = 2\\pi\\sqrt{\\frac{L}{g/4}} = 2\\left(2\\pi\\sqrt{\\frac{L}{g}}\\right) = 2 T_1 \\implies \\frac{T_2}{T_1} = 2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The length of a simple pendulum is $16\\,\\text{cm}$. What is its period in seconds (take $g = \\pi^2\\,\\text{m/s}^2$)?",
    "options": [],
    "correctAnswer": 0.8,
    "numericalAnswer": 0.8,
    "explanation": "$L = 0.16\\,\\text{m}$. $T = 2\\pi\\sqrt{\\frac{0.16}{\\pi^2}} = 2\\pi\\left(\\frac{0.4}{\\pi}\\right) = 0.8\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with an energy of $0.05\\,\\text{J}$ and maximum force $10\\,\\text{N}$. What is the amplitude of oscillation in centimeters?",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "We know $E = \\frac{1}{2}k A^2$ and $F_{\\max} = k A$. Dividing gives $\\frac{E}{F_{\\max}} = \\frac{A}{2} \\implies A = \\frac{2E}{F_{\\max}} = \\frac{2(0.05)}{10} = \\frac{0.10}{10} = 0.01\\,\\text{m} = 1\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum oscillates with an amplitude of $4^\\circ$. If its amplitude is increased to $8^\\circ$, by what factor does its total mechanical energy increase?",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "Energy of a simple pendulum is $E = mgL(1 - \\cos\\theta_0) \\approx \\frac{1}{2}mgL \\theta_0^2 \\propto \\theta_0^2$. Doubling the angular amplitude increases the total energy by a factor of $2^2 = 4$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of length $L$ has time period $T$. What should be the length of another simple pendulum in terms of $L$ so that its frequency is doubled?",
    "options": [],
    "correctAnswer": 0.25,
    "numericalAnswer": 0.25,
    "explanation": "$f = \\frac{1}{2\\pi}\\sqrt{\\frac{g}{L}}$. For $f' = 2f$, we need $\\sqrt{\\frac{L}{L'}} = 2 \\implies \\frac{L}{L'} = 4 \\implies L' = \\frac{L}{4} = 0.25 L$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with amplitude $12\\,\\text{cm}$. At what displacement from the mean position in centimeters is its potential energy equal to $\\frac{1}{9}$ of its total mechanical energy?",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$U = \\frac{1}{2}k x^2 = \\frac{1}{9}\\left(\\frac{1}{2}k A^2\\right) \\implies x^2 = \\frac{A^2}{9} \\implies x = \\frac{A}{3} = \\frac{12}{3} = 4\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The time period of a simple pendulum is measured to be $2.00\\,\\text{s}$ with an uncertainty of $0.02\\,\\text{s}$. If the length is measured to be $100.0\\,\\text{cm}$ with an uncertainty of $0.1\\,\\text{cm}$, find the percentage error in the determined value of $g$ (rounded to one decimal place).",
    "options": [],
    "correctAnswer": 2.1,
    "numericalAnswer": 2.1,
    "explanation": "Since $g = 4\\pi^2 \\frac{L}{T^2}$, the maximum relative error is $\\frac{\\Delta g}{g} = \\frac{\\Delta L}{L} + 2\\frac{\\Delta T}{T} = \\frac{0.1}{100.0} + 2\\left(\\frac{0.02}{2.00}\\right) = 0.001 + 2(0.010) = 0.001 + 0.020 = 0.021 = 2.1\\%$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle in SHM passes through the mean position with velocity $v_0 = 10\\,\\text{m/s}$. What is its speed in $\\text{m/s}$ when its potential energy is equal to its kinetic energy (take $\\sqrt{2} \\approx 1.414$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 7.07,
    "numericalAnswer": 7.07,
    "explanation": "Total energy is $E = \\frac{1}{2}m v_0^2$. When $K = U$, $K = E/2 \\implies \\frac{1}{2}m v^2 = \\frac{1}{2}\\left(\\frac{1}{2}m v_0^2\\right) \\implies v = \\frac{v_0}{\\sqrt{2}} = \\frac{10}{1.414} \\approx 7.07\\,\\text{m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of length $2.5\\,\\text{m}$ has a bob of mass $0.5\\,\\text{kg}$. What is the time period in seconds (take $g = 10\\,\\text{m/s}^2$ and $\\pi = 3.14$)?",
    "options": [],
    "correctAnswer": 3.14,
    "numericalAnswer": 3.14,
    "explanation": "$T = 2\\pi\\sqrt{\\frac{L}{g}} = 2(3.14)\\sqrt{\\frac{2.5}{10}} = 6.28\\sqrt{0.25} = 6.28(0.5) = 3.14\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum has time period $T$. If the mass of the bob is increased by $100\\%$, what is the new time period in terms of $T$?",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "The time period of a simple pendulum is $T = 2\\pi\\sqrt{L/g}$, which is independent of the mass of the bob. Hence the period remains $1 T$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A hollow sphere filled with water is used as the bob of a simple pendulum. A small hole at the bottom allows water to drain slowly. How does the time period initially change as water starts draining (enter 1 if it increases, 2 if it decreases, 3 if it remains constant)?",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "As water drains, the center of mass of the bob shifts downwards, increasing the effective length $L$ of the pendulum. Since $T \\propto \\sqrt{L}$, the period initially increases (enter 1). (Once the sphere becomes completely empty, center of mass returns to center and period returns to original).",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with amplitude $10\\,\\text{cm}$ and total energy $8\\,\\text{J}$. At what displacement in centimeters is its kinetic energy equal to $6\\,\\text{J}$?",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "Potential energy is $U = E - K = 8 - 6 = 2\\,\\text{J}$. Thus $\\frac{U}{E} = \\frac{2}{8} = \\frac{1}{4}$. Since $U/E = x^2/A^2$, we have $x^2/A^2 = 1/4 \\implies x = A/2 = 10/2 = 5\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of length $L$ has period $T$. When suspended in a liquid of density one-fourth that of the bob, its period becomes $k T$. What is the value of $k$ (take $\\sqrt{4/3} \\approx 1.15$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 1.15,
    "numericalAnswer": 1.15,
    "explanation": "Effective gravity is $g_{\\text{eff}} = g(1 - \\rho_L / \\rho_b) = g(1 - 1/4) = \\frac{3}{4}g$. Thus $T' = 2\\pi\\sqrt{\\frac{L}{3g/4}} = \\sqrt{\\frac{4}{3}} T \\approx 1.15 T$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $0.2\\,\\text{kg}$ oscillates in SHM with angular frequency $10\\,\\text{rad/s}$ and amplitude $0.1\\,\\text{m}$. Find the maximum kinetic energy in joules.",
    "options": [],
    "correctAnswer": 0.1,
    "numericalAnswer": 0.1,
    "explanation": "$K_{\\max} = \\frac{1}{2}m\\omega^2 A^2 = \\frac{1}{2}(0.2)(10^2)(0.1)^2 = 0.1(100)(0.01) = 0.1\\,\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two pendulums have lengths in the ratio $1:4$. What is the ratio of their frequencies of oscillation?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "$f \\propto \\frac{1}{\\sqrt{L}} \\implies \\frac{f_1}{f_2} = \\sqrt{\\frac{L_2}{L_1}} = \\sqrt{\\frac{4}{1}} = 2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In simple harmonic motion, at what fraction of amplitude ($x/A$) is the kinetic energy equal to 8 times the potential energy?",
    "options": [],
    "correctAnswer": 0.33,
    "numericalAnswer": 0.33,
    "explanation": "$K = 8U \\implies E - U = 8U \\implies 9U = E \\implies 9\\left(\\frac{1}{2}k x^2\\right) = \\frac{1}{2}k A^2 \\implies 9x^2 = A^2 \\implies x = A/3 \\approx 0.33 A$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum has period $T = 3\\,\\text{s}$. If its length is multiplied by 9, what is its new time period in seconds?",
    "options": [],
    "correctAnswer": 9,
    "numericalAnswer": 9,
    "explanation": "$T \\propto \\sqrt{L}$. When length is multiplied by 9, new period is $T' = \\sqrt{9} T = 3 \\times 3 = 9\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum has a time period of $2\\,\\text{s}$ on Earth. What is the length of the pendulum in meters (take $g = \\pi^2\\,\\text{m/s}^2$)?",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$T = 2\\pi\\sqrt{\\frac{L}{g}} \\implies 2 = 2\\pi\\sqrt{\\frac{L}{\\pi^2}} = 2\\sqrt{L} \\implies \\sqrt{L} = 1 \\implies L = 1\\,\\text{m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with total energy $16\\,\\text{J}$ and amplitude $4\\,\\text{cm}$. What is the potential energy in joules when displacement is $3\\,\\text{cm}$?",
    "options": [],
    "correctAnswer": 9,
    "numericalAnswer": 9,
    "explanation": "$U = E \\left(\\frac{x}{A}\\right)^2 = 16\\left(\\frac{3}{4}\\right)^2 = 16\\left(\\frac{9}{16}\\right) = 9\\,\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a simple pendulum, the maximum speed of the bob is $1.4\\,\\text{m/s}$. Find the maximum vertical height in centimeters to which the bob rises above its lowest position (take $g = 9.8\\,\\text{m/s}^2$).",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "By conservation of mechanical energy: $mgh = \\frac{1}{2}m v_{\\max}^2 \\implies h = \\frac{v_{\\max}^2}{2g} = \\frac{(1.4)^2}{2(9.8)} = \\frac{1.96}{19.6} = 0.10\\,\\text{m} = 10\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executing SHM has amplitude $20\\,\\text{cm}$. At what displacement from the mean position in centimeters is its kinetic energy equal to its potential energy (take $\\sqrt{2} \\approx 1.414$)? Round to one decimal place.",
    "options": [],
    "correctAnswer": 14.1,
    "numericalAnswer": 14.1,
    "explanation": "Displacement is $x = \\frac{A}{\\sqrt{2}} = \\frac{20}{1.414} \\approx 14.14 \\approx 14.1\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of length $L$ has period $T_0$. If its length is reduced to $L/16$, its new frequency is $k f_0$. What is the value of $k$?",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$f = \\frac{1}{2\\pi}\\sqrt{\\frac{g}{L}} \\propto \\frac{1}{\\sqrt{L}}$. Reducing length to $L/16$ multiplies frequency by $\\sqrt{16} = 4$. Hence $k = 4$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle in SHM has kinetic energy $K_0$ at the mean position. What is its potential energy when its speed is $\\frac{v_{\\max}}{2}$?",
    "options": [],
    "correctAnswer": 0.75,
    "numericalAnswer": 0.75,
    "explanation": "At this point, $K = \\frac{1}{2}m(v_{\\max}/2)^2 = \\frac{1}{4}K_0$. By conservation of energy, $U = K_0 - K = K_0 - 0.25 K_0 = 0.75 K_0$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
