module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The binding energy per nucleon ($BE/A$) is practically constant ($\\approx 8.5\\text{ MeV/nucleon}$) over a wide intermediate mass range ($30 < A < 170$).\\nReason (R): Nuclear forces have a short range and exhibit saturation, so each nucleon interacts only with its immediate neighbors.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Because the strong force has a range of $\\approx 1-2\\text{ fm}$, a nucleon is surrounded by a fixed maximum number of nearest neighbors regardless of total $A$. The binding energy thus increases linearly with $A$, keeping $BE/A$ nearly constant.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Energy is released when a very heavy nucleus undergoes nuclear fission into two intermediate-mass fragments.\\nReason (R): The binding energy per nucleon is higher for intermediate-mass fragments ($\\approx 8.5\\text{ MeV}$) than for the parent heavy nucleus ($\\approx 7.6\\text{ MeV}$).\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Because $BE/A$ of intermediate nuclei exceeds that of heavy nuclei by about $0.9\\text{ MeV/nucleon}$, splitting a heavy nucleus ($A \\sim 240$) results in more tightly bound daughter nuclei, releasing approximately $240 \\times 0.9 \\approx 200\\text{ MeV}$ of energy.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Energy is released when two light nuclei fuse together to form a heavier nucleus.\\nReason (R): The binding energy per nucleon of the fused heavier nucleus is significantly greater than that of the initial lighter nuclei.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "At the light end of the $BE/A$ curve ($A < 20$), $BE/A$ rises steeply. Fusing light nuclei (such as $^2\\text{H} + ^3\\text{H} \\to ^4\\text{He} + n$) moves the system up to the tightly bound $^4\\text{He}$ state ($7.07\\text{ MeV/nucleon}$), releasing substantial energy.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The nucleus $^{56}_{26}\\text{Fe}$ is one of the most stable nuclei in the universe.\\nReason (R): The binding energy per nucleon reaches its maximum value of approximately $8.75\\text{ MeV/nucleon}$ near mass number $A = 56$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "The $BE/A$ curve peaks near $A = 56-62$ ($^{56}\\text{Fe}$ and $^{62}\\text{Ni}$) at $\\approx 8.75-8.79\\text{ MeV/nucleon}$, representing the most tightly bound nuclear configurations in nature.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The binding energy per nucleon curve shows sharp local maxima for $^4_2\\text{He}, ^{12}_6\\text{C}$, and $^{16}_8\\text{O}$.\\nReason (R): These nuclei are composed of integral multiples of tightly bound $\\alpha$-particles ($2p + 2n$) and possess closed-shell configurations.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Even-even nuclei with $N = Z$ having completed nuclear shells (or sub-shells of $\\alpha$-clusters) possess unusually high stability, showing up as sharp spikes on the $BE/A$ curve compared to their immediate neighbors.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): For very heavy nuclei ($A > 170$), the binding energy per nucleon decreases as mass number increases.\\nReason (R): The cumulative long-range electrostatic Coulomb repulsive force between all protons increases faster than the saturated attractive nuclear force.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "While the attractive nuclear force is short-range and scales as $A$, the disruptive Coulomb repulsion acts between all $Z(Z-1)/2$ proton pairs and scales as $Z^2 / A^{1/3}$, reducing the net binding energy per nucleon for heavy nuclei.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Even-even nuclei (nuclei with an even number of protons and an even number of neutrons) are generally more stable than odd-odd nuclei.\\nReason (R): The pairing energy term in the semi-empirical mass formula contributes positively to the binding energy for even-even nuclei due to spin-pairing of nucleons.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Identical nucleons with opposite spins pair up in the same spatial state, maximizing their attractive overlap and providing extra stability ($+\\delta$ in the Weizsäcker formula). For odd-odd nuclei, the unpaired nucleons reduce binding energy.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The neutron separation energy $S_n$ is the energy required to remove a single neutron from a nucleus.\\nReason (R): The neutron separation energy is given by $S_n = [M(A-1, Z) + m_n - M(A, Z)] c^2$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Neutron separation energy is analogous to atomic ionization energy: it is the minimum energy required to detach one neutron to infinity, calculated directly from the mass difference between the daughter plus neutron and the parent nucleus.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The proton separation energy for a heavy nucleus is generally less than the neutron separation energy.\\nReason (R): Electrostatic Coulomb repulsion pushes the proton away from the nucleus, lowering the energy required to remove it.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "The Coulomb repulsion between the positively charged nucleus and the proton acts outward, assisting in its ejection and reducing the net work required to separate the proton compared to a neutral neutron.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): A nucleus having a binding energy per nucleon of $8.5\\text{ MeV}$ is more stable than a nucleus having a total binding energy of $1000\\text{ MeV}$ with $A = 200$.\\nReason (R): Nuclear stability is governed by the binding energy per nucleon ($BE/A$), not by the total binding energy.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "For the second nucleus, $BE/A = 1000 / 200 = 5.0\\text{ MeV/nucleon}$. A nucleus with $BE/A = 8.5\\text{ MeV/nucleon}$ requires more energy per constituent nucleon to disassemble, making it much more tightly bound and stable.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): In the liquid drop model of the nucleus, the surface energy term reduces the total binding energy.\\nReason (R): Nucleons situated on the surface of the nucleus have fewer neighboring nucleons to interact with than nucleons in the interior.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Just as surface molecules in a liquid drop experience an inward pull due to missing exterior neighbors, surface nucleons have fewer attractive bonds, creating a surface energy term $-a_s A^{2/3}$ that reduces the total binding energy.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Nuclear fusion produces more energy per unit mass than nuclear fission.\\nReason (R): The increase in binding energy per nucleon is larger in the fusion of light nuclei (such as deuterium and tritium) than in the fission of uranium.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "In fission of $^{235}\\text{U}$, $\\approx 200\\text{ MeV}$ is released for $235\\text{ u}$ (about $0.85\\text{ MeV/nucleon}$). In D-T fusion, $17.6\\text{ MeV}$ is released for $5\\text{ nucleons}$ (about $3.5\\text{ MeV/nucleon}$). Thus, per kilogram of fuel, fusion yields approximately 4 times more energy than fission.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The mass of a deuteron nucleus ($^2_1\\text{H}$) is $2.01355\\text{ u}$, which is less than $m_p + m_n = 2.01594\\text{ u}$.\\nReason (R): The difference in mass corresponds to the binding energy of the deuteron ($2.22\\text{ MeV}$) according to $E = \\Delta m \\cdot c^2$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "$\\Delta m = 2.01594 - 2.01355 = 0.00239\\text{ u}$. In energy units, $\\Delta m \\times 931.5\\text{ MeV} = 2.226\\text{ MeV}$, which is the known binding energy of the deuteron.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): A nucleus cannot spontaneously undergo a decay if the total mass of the products exceeds the rest mass of the parent nucleus.\\nReason (R): Such a process would require external energy input and violates conservation of energy for an isolated system.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Spontaneous radioactive decay is possible only if the reaction is exoergic ($Q = [M_{\\text{parent}} - \\sum M_{\\text{products}}] c^2 > 0$). If products are heavier, the reaction is endoergic and cannot occur spontaneously.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The binding energy of $^{4}_2\\text{He}$ is approximately $28.3\\text{ MeV}$.\\nReason (R): The binding energy per nucleon of $^{4}_2\\text{He}$ is about $7.07\\text{ MeV}$, so total binding energy is $4 \\times 7.07 \\approx 28.3\\text{ MeV}$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "The helium-4 nucleus has $A = 4$ and $BE/A \\approx 7.07\\text{ MeV/nucleon}$, yielding a total binding energy of $4 \\times 7.07 = 28.28 \\approx 28.3\\text{ MeV}$.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The volume energy term in Weizsäcker's semi-empirical mass formula is directly proportional to mass number $A$.\\nReason (R): Due to the saturation of nuclear forces, each nucleon contributes approximately a constant amount of binding energy from interactions with its nearest neighbors.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Saturation implies that each nucleon binds only with a fixed number of adjacent nucleons. Hence, the primary attractive volume term is $E_v = a_v A$.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The Coulomb energy term in the semi-empirical mass formula is proportional to $-\\frac{Z(Z - 1)}{A^{1/3}}$.\\nReason (R): The electrostatic potential energy of $Z$ protons uniformly distributed in a sphere of radius $R \\propto A^{1/3}$ is proportional to $\\frac{Z(Z - 1)}{R}$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "There are $Z(Z-1)/2$ interacting pairs of protons. Electrostatic self-energy of a uniformly charged sphere is $U_c = \\frac{3}{5}\\frac{1}{4\\pi\\varepsilon_0}\\frac{Z(Z-1)e^2}{R}$. Since $R = R_0 A^{1/3}$, the disruptive Coulomb energy term is $-a_c \\frac{Z(Z-1)}{A^{1/3}}$.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The asymmetry energy term in the semi-empirical mass formula is proportional to $-\\frac{(A - 2Z)^2}{A}$.\\nReason (R): Because of the Pauli exclusion principle, having unequal numbers of protons and neutrons ($N \\neq Z$) forces nucleons into higher nuclear energy states, reducing the binding energy.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Protons and neutrons each fill separate Fermi energy levels. Any excess of neutrons over protons ($N - Z = A - 2Z$) requires placing neutrons into higher available quantum states, penalizing the binding energy by an amount proportional to $(N-Z)^2 / A$.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): In an exothermic nuclear reaction, the total binding energy of the product nuclei is strictly greater than that of the reactant nuclei.\\nReason (R): The $Q$-value of a nuclear reaction is equal to the sum of the binding energies of the products minus the sum of the binding energies of the reactants ($Q = \\sum BE_{\\text{products}} - \\sum BE_{\\text{reactants}}$).\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Because $M c^2 = \\sum m_i c^2 - BE$, the $Q$-value $Q = (M_{\\text{react}} - M_{\\text{prod}}) c^2 = \\sum BE_{\\text{prod}} - \\sum BE_{\\text{react}}$. If $Q > 0$, the products are more tightly bound than the reactants.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): A nucleus with a lower binding energy per nucleon is more easily broken apart into its constituent nucleons.\\nReason (R): Binding energy per nucleon represents the average work required per nucleon to completely separate all nucleons to infinite distance.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "By definition, binding energy per nucleon $BE/A$ is the average work required to remove a nucleon from the nucleus. A smaller $BE/A$ means less energy is needed to disintegrate the nucleus.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Magic numbers ($2, 8, 20, 28, 50, 82, 126$) correspond to nuclei with exceptional binding energy and stability.\\nReason (R): Magic numbers represent completely filled quantum shells of protons or neutrons within the nuclear shell model, analogous to noble gas electron configurations.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "In the nuclear shell model (incorporating strong spin-orbit coupling), large energy gaps occur above nucleon counts $2, 8, 20, 28, 50, 82, 126$. Nuclei with these proton or neutron numbers have closed shells and elevated binding energies.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Doubly magic nuclei such as $^4_2\\text{He}, ^{16}_8\\text{O}, ^{40}_{20}\\text{Ca}$, and $^{208}_{82}\\text{Pb}$ have spherical shapes and abnormally high separation energies.\\nReason (R): Both their proton and neutron shells are completely filled, resulting in zero net orbital angular momentum and enhanced binding.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "When both $Z$ and $N$ are magic numbers, the nucleus benefits from two closed shells, producing a spherically symmetric charge distribution and unusually high resistance to nucleon removal.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The binding energy of a nucleus is always positive for a bound, stable nucleus.\\nReason (R): Work must be done by an external agent against attractive nuclear forces to pull the bound nucleons apart to infinite separation.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Because attractive nuclear forces dominate, energy must be supplied to dissociate the nucleus into free protons and neutrons. By convention, $BE = (\\sum m_{\\text{free}} - M_{\\text{bound}}) c^2 > 0$.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The binding energy per nucleon of a deuteron is $1.11\\text{ MeV/nucleon}$.\\nReason (R): The total binding energy of a deuteron is $2.22\\text{ MeV}$ and it contains $2$ nucleons, so $BE/A = 2.22 / 2 = 1.11\\text{ MeV/nucleon}$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "For a deuteron ($^2_1\\text{H}$), total $BE = 2.224\\text{ MeV}$. With $A = 2$, $BE/A = 2.224 / 2 = 1.112 \\approx 1.11\\text{ MeV/nucleon}$.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): When four protons fuse into a helium nucleus in the solar core, approximately $26.7\\text{ MeV}$ of energy is liberated.\\nReason (R): The mass defect between four free protons (plus two electrons) and a helium-4 nucleus corresponds to $\\approx 0.0287\\text{ u}$, releasing $26.7\\text{ MeV}$ via $E = \\Delta m c^2$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "The net reaction of the proton-proton chain is $4p + 2e^- \\to ^4\\text{He} + 2\\nu_e + 26.7\\text{ MeV}$. This energy release fuels the Sun and main-sequence stars.",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The packing fraction of $^{12}_6\\text{C}$ is zero.\\nReason (R): By definition, the atomic mass unit is based on $^{12}_6\\text{C}$ having an exact mass of $12.0000\\text{ u}$, so $M - A = 12 - 12 = 0$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Packing fraction is $f = \\frac{M - A}{A}$. In the unified atomic mass scale, the isotopic mass of $^{12}_6\\text{C}$ is defined as exactly $12\\text{ u}$, so $f = (12 - 12)/12 = 0$. Both statements are true and (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "A heavy nucleus $X$ with mass number $A = 240$ and binding energy per nucleon of $7.6\\text{ MeV}$ splits into two equal fragments $Y$ each of mass number $A = 120$ and binding energy per nucleon of $8.5\\text{ MeV}$. The total energy released in this fission process is:",
    "options": [
      "$216\\text{ MeV}$",
      "$108\\text{ MeV}$",
      "$0.9\\text{ MeV}$",
      "$432\\text{ MeV}$"
    ],
    "correctAnswer": "$216\\text{ MeV}$",
    "explanation": "Total initial binding energy: $BE_i = 240 \\times 7.6\\text{ MeV} = 1824\\text{ MeV}$.\\nTotal final binding energy: $BE_f = 2 \\times (120 \\times 8.5\\text{ MeV}) = 240 \\times 8.5\\text{ MeV} = 2040\\text{ MeV}$.\\nEnergy released: $Q = BE_f - BE_i = 2040 - 1824 = 216\\text{ MeV}$.",
    "type": "MCQ",
    "questionType": "MCQ",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "The binding energies per nucleon for a deuteron ($^2_1\\text{H}$) and a helium nucleus ($^4_2\\text{He}$) are $1.1\\text{ MeV}$ and $7.0\\text{ MeV}$ respectively. When two deuterons fuse to form one helium nucleus, the energy released is:",
    "options": [
      "$23.6\\text{ MeV}$",
      "$11.8\\text{ MeV}$",
      "$28.0\\text{ MeV}$",
      "$4.4\\text{ MeV}$"
    ],
    "correctAnswer": "$23.6\\text{ MeV}$",
    "explanation": "Initial binding energy: $BE_i = 2 \\times (2 \\times 1.1\\text{ MeV}) = 4.4\\text{ MeV}$.\\nFinal binding energy: $BE_f = 4 \\times 7.0\\text{ MeV} = 28.0\\text{ MeV}$.\\nEnergy released: $Q = BE_f - BE_i = 28.0 - 4.4 = 23.6\\text{ MeV}$.",
    "type": "MCQ",
    "questionType": "MCQ",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Which of the following nuclei has the highest binding energy per nucleon?",
    "options": [
      "$^{56}_{26}\\text{Fe}$",
      "$^{238}_{92}\\text{U}$",
      "$^4_2\\text{He}$",
      "$^2_1\\text{H}$"
    ],
    "correctAnswer": "$^{56}_{26}\\text{Fe}$",
    "explanation": "The binding energy per nucleon peaks near the iron-nickel region ($A \\approx 56$), where $^{56}\\text{Fe}$ has $BE/A \\approx 8.75\\text{ MeV/nucleon}$, the highest among the choices.",
    "type": "MCQ",
    "questionType": "MCQ",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "If the mass defect of a nucleus with mass number $A = 16$ is $0.137\\text{ u}$, the average binding energy per nucleon of the nucleus is approximately:",
    "options": [
      "$7.98\\text{ MeV}$",
      "$8.55\\text{ MeV}$",
      "$127.6\\text{ MeV}$",
      "$4.25\\text{ MeV}$"
    ],
    "correctAnswer": "$7.98\\text{ MeV}$",
    "explanation": "Total binding energy: $BE = 0.137 \\times 931.5\\text{ MeV} = 127.615\\text{ MeV}$.\\nBinding energy per nucleon: $BE / A = \\frac{127.615}{16} \\approx 7.98\\text{ MeV/nucleon}$.",
    "type": "MCQ",
    "questionType": "MCQ",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "The masses of neutron and proton are $1.0087\\text{ u}$ and $1.0073\\text{ u}$ respectively. If the mass of an $\\alpha$-particle is $4.0015\\text{ u}$, the binding energy of the $\\alpha$-particle is approximately:",
    "options": [
      "$28.4\\text{ MeV}$",
      "$7.1\\text{ MeV}$",
      "$14.2\\text{ MeV}$",
      "$56.8\\text{ MeV}$"
    ],
    "correctAnswer": "$28.4\\text{ MeV}$",
    "explanation": "Mass of constituent nucleons: $2 m_p + 2 m_n = 2(1.0073) + 2(1.0087) = 2.0146 + 2.0174 = 4.0320\\text{ u}$.\\nMass defect: $\\Delta m = 4.0320 - 4.0015 = 0.0305\\text{ u}$.\\n$BE = 0.0305 \\times 931.5\\text{ MeV} \\approx 28.41\\text{ MeV}$.",
    "type": "MCQ",
    "questionType": "MCQ",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "In the Weizsäcker semi-empirical mass formula, the term that accounts for the fact that nucleons on the surface have fewer interacting neighbors is called the:",
    "options": [
      "Surface energy term",
      "Volume energy term",
      "Coulomb energy term",
      "Asymmetry energy term"
    ],
    "correctAnswer": "Surface energy term",
    "explanation": "The surface energy term $-a_s A^{2/3}$ corrects for the reduction in binding of surface nucleons that have fewer attractive nearest-neighbor bonds than interior nucleons.",
    "type": "MCQ",
    "questionType": "MCQ",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "The binding energy per nucleon for $C^{12}$ is $7.68\\text{ MeV}$ and for $C^{13}$ is $7.47\\text{ MeV}$. The energy required to remove one neutron from $C^{13}$ is:",
    "options": [
      "$4.95\\text{ MeV}$",
      "$0.21\\text{ MeV}$",
      "$7.47\\text{ MeV}$",
      "$9.90\\text{ MeV}$"
    ],
    "correctAnswer": "$4.95\\text{ MeV}$",
    "explanation": "Total $BE(C^{12}) = 12 \\times 7.68 = 92.16\\text{ MeV}$.\\nTotal $BE(C^{13}) = 13 \\times 7.47 = 97.11\\text{ MeV}$.\\nNeutron separation energy: $S_n = BE(C^{13}) - BE(C^{12}) = 97.11 - 92.16 = 4.95\\text{ MeV}$.",
    "type": "MCQ",
    "questionType": "MCQ",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "A heavy nucleus of mass number $A = 240$ with binding energy per nucleon of $7.6\\text{ MeV}$ breaks into two equal fragments of $A = 120$ each with binding energy per nucleon of $8.5\\text{ MeV}$. The energy released in this reaction is ______ $\\text{MeV}$.",
    "correctAnswer": "216",
    "solution": "$Q = 240 \\times (8.5 - 7.6) = 240 \\times 0.9 = 216\\text{ MeV}$.",
    "explanation": "$Q = 240 \\times (8.5 - 7.6) = 240 \\times 0.9 = 216\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "Two deuterons ($^2_1\\text{H}$) each having binding energy per nucleon of $1.1\\text{ MeV}$ fuse to form a helium nucleus ($^4_2\\text{He}$) with binding energy per nucleon of $7.0\\text{ MeV}$. The energy released is ______ $\\text{MeV}$. (Round to nearest integer: $28.0 - 4.4 = 23.6 \\approx 24$)",
    "correctAnswer": "24",
    "solution": "$Q = 4 \\times 7.0 - 2 \\times (2 \\times 1.1) = 28.0 - 4.4 = 23.6\\text{ MeV} \\approx 24\\text{ MeV}$.",
    "explanation": "$Q = 4 \\times 7.0 - 2 \\times (2 \\times 1.1) = 28.0 - 4.4 = 23.6\\text{ MeV} \\approx 24\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The binding energy of a nucleus $X$ with mass number $A = 50$ is $400\\text{ MeV}$. The binding energy per nucleon is ______ $\\text{MeV/nucleon}$.",
    "correctAnswer": "8",
    "solution": "$BE / A = \\frac{400\\text{ MeV}}{50} = 8\\text{ MeV/nucleon}$.",
    "explanation": "$BE / A = \\frac{400\\text{ MeV}}{50} = 8\\text{ MeV/nucleon}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The mass defect of a carbon-12 nucleus is $0.10\\text{ u}$. The total binding energy of the carbon-12 nucleus is approximately ______ $\\text{MeV}$. (Take $1\\text{ u} = 931.5\\text{ MeV}$; round to nearest integer: $0.10 \\times 931.5 = 93.15 \\approx 93$)",
    "correctAnswer": "93",
    "solution": "$BE = 0.10 \\times 931.5 = 93.15\\text{ MeV} \\approx 93\\text{ MeV}$.",
    "explanation": "$BE = 0.10 \\times 931.5 = 93.15\\text{ MeV} \\approx 93\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The binding energy per nucleon of $^{14}_7\\text{N}$ is $7.5\\text{ MeV}$. The total binding energy of the $^{14}_7\\text{N}$ nucleus is ______ $\\text{MeV}$.",
    "correctAnswer": "105",
    "solution": "$BE = 14 \\times 7.5 = 105\\text{ MeV}$.",
    "explanation": "$BE = 14 \\times 7.5 = 105\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The binding energy per nucleon of $^{16}_8\\text{O}$ is $8.0\\text{ MeV}$. The total binding energy of the $^{16}_8\\text{O}$ nucleus is ______ $\\text{MeV}$.",
    "correctAnswer": "128",
    "solution": "$BE = 16 \\times 8.0 = 128\\text{ MeV}$.",
    "explanation": "$BE = 16 \\times 8.0 = 128\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The total binding energy of $^{56}_{26}\\text{Fe}$ is $492.8\\text{ MeV}$. The binding energy per nucleon of $^{56}\\text{Fe}$ is approximately ______ $\\text{MeV/nucleon}$. (Round to nearest integer: $492.8 / 56 = 8.8 \\approx 9$)",
    "correctAnswer": "9",
    "solution": "$BE / A = \\frac{492.8}{56} = 8.8\\text{ MeV/nucleon} \\approx 9\\text{ MeV/nucleon}$.",
    "explanation": "$BE / A = \\frac{492.8}{56} = 8.8\\text{ MeV/nucleon} \\approx 9\\text{ MeV/nucleon}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A heavy nucleus of mass number $A = 200$ with $BE/A = 7.5\\text{ MeV}$ splits into two fragments of $A_1 = 80$ and $A_2 = 120$, each having $BE/A = 8.5\\text{ MeV}$. The energy released in the fission is ______ $\\text{MeV}$.",
    "correctAnswer": "200",
    "solution": "$Q = [80(8.5) + 120(8.5)] - 200(7.5) = 200(8.5 - 7.5) = 200(1.0) = 200\\text{ MeV}$.",
    "explanation": "$Q = [80(8.5) + 120(8.5)] - 200(7.5) = 200(8.5 - 7.5) = 200(1.0) = 200\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The binding energy of a deuteron is $2.2\\text{ MeV}$. The energy required to break $3$ deuterons into $3$ free protons and $3$ free neutrons is ______ $\\text{MeV}$. (Round to nearest integer: $3 \\times 2.2 = 6.6 \\approx 7$)",
    "correctAnswer": "7",
    "solution": "$E = 3 \\times 2.2 = 6.6\\text{ MeV} \\approx 7\\text{ MeV}$.",
    "explanation": "$E = 3 \\times 2.2 = 6.6\\text{ MeV} \\approx 7\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The mass defect for the formation of an alpha particle is $0.030\\text{ u}$. The binding energy is approximately ______ $\\text{MeV}$. (Round to nearest integer: $0.030 \\times 931.5 = 27.95 \\approx 28$)",
    "correctAnswer": "28",
    "solution": "$BE = 0.030 \\times 931.5 = 27.945\\text{ MeV} \\approx 28\\text{ MeV}$.",
    "explanation": "$BE = 0.030 \\times 931.5 = 27.945\\text{ MeV} \\approx 28\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "In a nuclear reaction $A + B \\to C + D$, the binding energies of $A, B, C, D$ are $10\\text{ MeV}, 15\\text{ MeV}, 20\\text{ MeV}$, and $12\\text{ MeV}$ respectively. The $Q$-value of the reaction is ______ $\\text{MeV}$.",
    "correctAnswer": "7",
    "solution": "$Q = \\sum BE_{\\text{prod}} - \\sum BE_{\\text{react}} = (20 + 12) - (10 + 15) = 32 - 25 = 7\\text{ MeV}$.",
    "explanation": "$Q = \\sum BE_{\\text{prod}} - \\sum BE_{\\text{react}} = (20 + 12) - (10 + 15) = 32 - 25 = 7\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A nucleus with $A = 60$ has a binding energy per nucleon of $8.5\\text{ MeV}$. The total binding energy of the nucleus is ______ $\\text{MeV}$.",
    "correctAnswer": "510",
    "solution": "$BE = 60 \\times 8.5 = 510\\text{ MeV}$.",
    "explanation": "$BE = 60 \\times 8.5 = 510\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The binding energy of a nucleus is $720\\text{ MeV}$ and its mass number is $90$. The binding energy per nucleon is ______ $\\text{MeV/nucleon}$.",
    "correctAnswer": "8",
    "solution": "$BE / A = \\frac{720}{90} = 8\\text{ MeV/nucleon}$.",
    "explanation": "$BE / A = \\frac{720}{90} = 8\\text{ MeV/nucleon}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The energy required to remove a neutron from $^{13}_6\\text{C}$ is $5\\text{ MeV}$. If the binding energy of $^{12}_6\\text{C}$ is $92\\text{ MeV}$, the binding energy of $^{13}_6\\text{C}$ is ______ $\\text{MeV}$.",
    "correctAnswer": "97",
    "solution": "$BE(^{13}\\text{C}) = BE(^{12}\\text{C}) + S_n = 92 + 5 = 97\\text{ MeV}$.",
    "explanation": "$BE(^{13}\\text{C}) = BE(^{12}\\text{C}) + S_n = 92 + 5 = 97\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "The packing fraction of a nucleus with isotopic mass $M = 39.96\\text{ u}$ and mass number $A = 40$ is $-x \\times 10^{-4}$. The value of $x$ is ______ .",
    "correctAnswer": "10",
    "solution": "$f = \\frac{M - A}{A} = \\frac{39.96 - 40}{40} = -\\frac{0.04}{40} = -0.0010 = -10\\times 10^{-4} \\implies x = 10$.",
    "explanation": "$f = \\frac{M - A}{A} = \\frac{39.96 - 40}{40} = -\\frac{0.04}{40} = -0.0010 = -10\\times 10^{-4} \\implies x = 10$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "When three $\\alpha$-particles fuse to form a $^{12}_6\\text{C}$ nucleus, the energy released is approximately $7.3\\text{ MeV}$. (Take $BE(\\alpha) = 28.3\\text{ MeV}$ and $BE(^{12}\\text{C}) = 92.2\\text{ MeV}$). The energy released rounded to the nearest integer is ______ $\\text{MeV}$.",
    "correctAnswer": "7",
    "solution": "$Q = BE(^{12}\\text{C}) - 3 \\times BE(\\alpha) = 92.2 - 3(28.3) = 92.2 - 84.9 = 7.3\\text{ MeV} \\approx 7\\text{ MeV}$.",
    "explanation": "$Q = BE(^{12}\\text{C}) - 3 \\times BE(\\alpha) = 92.2 - 3(28.3) = 92.2 - 84.9 = 7.3\\text{ MeV} \\approx 7\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A nucleus of mass number $A = 100$ has $BE/A = 8.6\\text{ MeV}$. The total binding energy is ______ $\\text{MeV}$.",
    "correctAnswer": "860",
    "solution": "$BE = 100 \\times 8.6 = 860\\text{ MeV}$.",
    "explanation": "$BE = 100 \\times 8.6 = 860\\text{ MeV}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "If the binding energy per nucleon of a nucleus of mass number $A = 30$ is $8.0\\text{ MeV}$, the total mass defect of the nucleus is approximately $x / 100\\text{ u}$. Taking $1\\text{ u} \\approx 930\\text{ MeV}$, $BE = 240\\text{ MeV}$. The value of $\\Delta m$ is $240 / 930 \\approx 0.258\\text{ u} \\approx 26 / 100\\text{ u}$. The value of $x$ is ______ .",
    "correctAnswer": "26",
    "solution": "$\\Delta m = \\frac{240}{931.5} \\approx 0.2576\\text{ u} \\approx 0.26\\text{ u} = \\frac{26}{100}\\text{ u} \\implies x = 26$.",
    "explanation": "$\\Delta m = \\frac{240}{931.5} \\approx 0.2576\\text{ u} \\approx 0.26\\text{ u} = \\frac{26}{100}\\text{ u} \\implies x = 26$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "Two nuclei with $A = 1$ fuse to form a nucleus with $A = 2$, releasing $2.2\\text{ MeV}$. The energy released per nucleon in this fusion reaction is ______ $\\text{MeV/nucleon}$. (Round to nearest integer: $2.2 / 2 = 1.1 \\approx 1$)",
    "correctAnswer": "1",
    "solution": "$Q / A = 2.2 / 2 = 1.1\\text{ MeV/nucleon} \\approx 1\\text{ MeV/nucleon}$.",
    "explanation": "$Q / A = 2.2 / 2 = 1.1\\text{ MeV/nucleon} \\approx 1\\text{ MeV/nucleon}$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A heavy nucleus of mass number $A = 236$ undergoes fission releasing $200\\text{ MeV}$. The energy released per nucleon in this process is approximately $x / 100\\text{ MeV/nucleon}$. Taking $200 / 236 \\approx 0.85\\text{ MeV/nucleon} = 85 / 100$, the value of $x$ is ______ .",
    "correctAnswer": "85",
    "solution": "$\\frac{200}{236} \\approx 0.8475 \\approx 0.85 = \\frac{85}{100}\\text{ MeV/nucleon} \\implies x = 85$.",
    "explanation": "$\\frac{200}{236} \\approx 0.8475 \\approx 0.85 = \\frac{85}{100}\\text{ MeV/nucleon} \\implies x = 85$.",
    "type": "NUMERICAL",
    "questionType": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Atoms and Nuclei",
    "subtopic": "Binding energy",
    "subTopic": "Binding energy",
    "class": "Class 12",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  }
];
