module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The work done in moving an electric charge from one point to another on the same equipotential surface is identically zero.\nReason (R): The potential difference between any two points on an equipotential surface is zero: $\\Delta V = V_B - V_A = 0$, so $W = q\\Delta V = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By definition of an equipotential surface, all points have identical electrostatic potential ($V = \\text{constant}$), making work $W = q(V_B - V_A) = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electric field lines are everywhere perpendicular to equipotential surfaces.\nReason (R): Because the work done moving a charge along any displacement $d\\vec{r}$ on an equipotential surface is zero ($dW = -q\\vec{E}\\cdot d\\vec{r} = 0$), the electric field $\\vec{E}$ must be orthogonal to $d\\vec{r}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\vec{E}\\cdot d\\vec{r} = -dV = 0$ for any displacement on the surface, $\\vec{E}$ has zero tangential component and must be strictly normal to the equipotential surface. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two equipotential surfaces can never intersect each other.\nReason (R): If two equipotential surfaces with different potentials intersected, the line of intersection would have two different potential values at the same physical point, which is impossible.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Electrostatic potential is a single-valued scalar function of position; a point cannot possess two distinct potentials simultaneously. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Equipotential surfaces are closer together in regions of strong electric fields and farther apart in regions of weak electric fields.\nReason (R): The electric field is related to potential gradient by $E = -\\frac{dV}{dr}$, which implies that for a fixed potential step $\\Delta V$, the separation $\\Delta r = \\frac{|\\Delta V|}{E}$ is inversely proportional to $E$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "From $\\Delta r = \\frac{\\Delta V}{E}$, large electric field $E$ corresponds to small separation $\\Delta r$, meaning surfaces crowd together in regions of strong field. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The surface of a charged conductor in electrostatic equilibrium is always an equipotential surface.\nReason (R): Inside a conductor in electrostatic equilibrium, the electric field is zero everywhere, so the potential is constant throughout the entire volume and equal to the surface potential.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{E} = -\\vec{\\nabla}V = 0$ throughout the conductor, $V(x,y,z) = \\text{constant}$, making the entire conductor and its boundary an equipotential volume and surface. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): For an isolated point charge, the equipotential surfaces are a family of concentric spheres centered on the charge.\nReason (R): The potential due to a point charge $q$ is $V = \\frac{kq}{r}$, which is spherically symmetric and constant over any sphere of radius $r$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Surfaces of constant $r$ have constant potential $V = \\frac{kq}{r}$, producing concentric spherical equipotential shells. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In a uniform electric field, the equipotential surfaces are equidistant parallel planes perpendicular to the field direction.\nReason (R): For a uniform field $\\vec{E} = E_0\\hat{i}$, the potential is $V(x) = -E_0 x + C$, which is constant on planes of constant $x$ perpendicular to $\\vec{E}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Surfaces with constant $x$ are parallel planes orthogonal to the $\\hat{i}$ direction. Equal increments in $V$ correspond to equal steps $\\Delta x = \\Delta V / E_0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The equatorial plane of an electric dipole is an equipotential surface with potential $V = 0$.\nReason (R): Every point on the equatorial plane is equidistant from $+q$ and $-q$, so the positive and negative potential contributions cancel everywhere on this plane.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $r_+ = r_-$ for all points on the perpendicular bisector, $V = \\frac{kq}{r_+} - \\frac{kq}{r_-} = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): No electrical work is required to move a charge anywhere in the equatorial plane of an electric dipole.\nReason (R): The equatorial plane is an equipotential surface of constant potential $V = 0$, so the potential difference between any two points in this plane is zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$W = q(V_2 - V_1) = q(0 - 0) = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field always points in the direction of the steepest decrease in electrostatic potential.\nReason (R): The gradient operator $\\vec{\\nabla}V$ points in the direction of maximum rate of increase of potential, so $\\vec{E} = -\\vec{\\nabla}V$ points in the direction of maximum rate of decrease.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By vector calculus, the negative gradient $-\\vec{\\nabla}V$ defines the direction of steepest descent of the scalar field $V$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): For an infinitely long line charge with uniform linear charge density $\\lambda$, the equipotential surfaces are coaxial circular cylinders.\nReason (R): The potential of an infinite line charge depends solely on the perpendicular radial distance from the line: $V(r) = -\\frac{\\lambda}{2\\pi\\varepsilon_0}\\ln(r/r_0)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $V$ is a function of radial coordinate $r$ alone, surfaces of constant $r$ are circular cylinders coaxial with the charged wire. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A test charge released from rest in an electric field moves naturally from regions of higher potential to regions of lower potential.\nReason (R): The electrostatic force on a charge $q$ is $\\vec{F} = q\\vec{E} = -q\\vec{\\nabla}V$, which drives a positive charge in the direction of decreasing potential.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Positive charges accelerate towards lower potential to minimize potential energy ($U = qV$). Negative charges, conversely, accelerate towards higher potential. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If the potential is constant throughout a certain region of space, the electric field must be zero in that entire region.\nReason (R): The electric field is the spatial derivative of potential: $\\vec{E} = -\\vec{\\nabla}V$. The derivative of a constant is identically zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{\\nabla}(\\text{constant}) = 0$, a uniform potential region implies zero electric field everywhere inside it. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A metallic bird perched on a high-voltage bare transmission line does not get electrocuted.\nReason (R): The bird's two feet rest on the same conductor at essentially the same point, so the potential difference between the feet is virtually zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "No current flows through the bird because there is no potential difference ($\\Delta V \\approx 0$) across its body. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If the electric field is zero at a point, the electrostatic potential must necessarily be zero at that point.\nReason (R): Electric field and potential are related by $\\vec{E} = -\\vec{\\nabla}V$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: inside a charged metal sphere, $\\vec{E} = 0$ while $V = \\frac{kQ}{R} \\ne 0$. Reason is true: $\\vec{E} = -\\vec{\\nabla}V$ implies $V$ is flat (constant gradient), not necessarily zero.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Equipotential surfaces can be closed surfaces.\nReason (R): Concentric spherical equipotential surfaces surrounding a point charge are closed geometric surfaces.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Spherical and ellipsoidal equipotential surfaces are topologically closed manifolds in three dimensions. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric potential is a scalar quantity, but its spatial gradient is a vector quantity.\nReason (R): The gradient operation $\\vec{\\nabla}V = \\frac{\\partial V}{\\partial x}\\hat{i} + \\frac{\\partial V}{\\partial y}\\hat{j} + \\frac{\\partial V}{\\partial z}\\hat{k}$ transforms a scalar field into a vector field pointing along the maximum directional derivative.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Gradient takes scalar input $V$ and outputs vector $\\vec{\\nabla}V = -\\vec{E}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In a region where electric field lines are diverging, the spacing between consecutive equipotential surfaces increases in the direction of the field.\nReason (R): As field lines diverge, the electric field strength $E$ decreases, and since $\\Delta r = \\frac{\\Delta V}{E}$, the spacing $\\Delta r$ between equipotentials with equal potential steps increases.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Divergence causes $E$ to weaken with distance, requiring larger distance $\\Delta r$ to span the same potential drop $\\Delta V$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): An equipotential surface can be constructed through any point where the electric field is non-zero.\nReason (R): The normal to the equipotential surface at any point is uniquely aligned with the local electric field vector $\\vec{E}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{E} \\ne 0$ specifies a unique normal vector $\\hat{n} = \\frac{\\vec{E}}{|E|}$, a well-defined orthogonal surface can always be passed through that point. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic potential function $V(x, y, z) = 2x + 3y - 5z$ represents a uniform electric field.\nReason (R): Differentiating gives constant components: $E_x = -2, E_y = -3, E_z = +5$, so $\\vec{E} = -2\\hat{i} - 3\\hat{j} + 5\\hat{k}$ is independent of position coordinates.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because all partial derivatives are constant, $\\vec{E}$ is spatially uniform. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A hollow charged conductor shields its interior completely from external electrostatic fields, making the entire cavity an equipotential volume.\nReason (R): No electric field lines can cross the conducting shell because $E = 0$ inside the conducting material, keeping the cavity at the constant surface potential.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Electrostatic shielding creates a field-free cavity where potential is constant everywhere, equal to that of the shell. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Work done in moving a charge between two equipotential surfaces depends on the choice of path taken between them.\nReason (R): The electrostatic force is a conservative force.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: work done by conservative electrostatic force depends solely on initial and final potentials ($W = q(V_B - V_A)$) and is completely path-independent. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Equipotential surfaces for two equal and opposite charges (a dipole) are symmetrical about the equatorial plane.\nReason (R): The potential distribution of a dipole satisfies $V(x, y, -z) = -V(x, y, z)$ when the dipole is aligned along the $z$-axis.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The antisymmetry $V(-z) = -V(z)$ across the $z = 0$ equatorial plane gives symmetric equipotential contours with reversed signs. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): For two identical positive charges $+Q$ placed a distance apart, the equipotential surfaces near each charge are nearly spherical, but at large distances they merge into a single large spherical surface.\nReason (R): At large distances from the two charges ($r \\gg d$), the pair of charges acts effectively as a single combined point charge of magnitude $+2Q$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Monopole approximation: far away, the separation is negligible, so the potential approaches $V \\approx \\frac{k(2Q)}{r}$, whose equipotentials are large concentric spheres. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field inside a non-conducting uniformly charged solid sphere is non-zero, so the interior is NOT an equipotential region.\nReason (R): Inside a uniformly charged solid sphere of radius $R$, the electric field is $E(r) = \\frac{kQr}{R^3}$, which produces a variable potential $V(r) = \\frac{kQ}{2R^3}(3R^2 - r^2)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $V(r)$ varies with radius $r$, the interior is not equipotential. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Along an electric field line, the electrostatic potential always decreases in the direction of the field.\nReason (R): The electric field is defined as $\\vec{E} = -\\vec{\\nabla}V$, which implies that $dV = -\\vec{E}\\cdot d\\vec{r} < 0$ when moving in the direction of $\\vec{E}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Moving along $\\vec{E}$ implies $d\\vec{r} \\parallel \\vec{E}$, so $dV = -E\\, dr < 0$, meaning potential strictly decreases. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electrostatic potential in a region of space is given by $V(x, y, z) = 4x^2\\text{ Volts}$. The electric field at the point $(1\\text{ m}, 0, 2\\text{ m})$ is:",
    "options": [
      "$-8\\hat{i}\\text{ V/m}$",
      "$8\\hat{i}\\text{ V/m}$",
      "$-4\\hat{i}\\text{ V/m}$",
      "$-8\\hat{k}\\text{ V/m}$"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{E} = -\\left(\\frac{\\partial V}{\\partial x}\\hat{i} + \\frac{\\partial V}{\\partial y}\\hat{j} + \\frac{\\partial V}{\\partial z}\\hat{k}\\right) = -\\frac{\\partial(4x^2)}{\\partial x}\\hat{i} = -8x\\hat{i}$. At $x = 1\\text{ m}$, $\\vec{E} = -8\\hat{i}\\text{ V/m}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Equipotential surfaces at a great distance from a collection of charges whose total sum is non-zero are approximately:",
    "options": [
      "Spheres",
      "Planes",
      "Cylinders",
      "Ellipsoids"
    ],
    "correctAnswer": 0,
    "explanation": "At large distances, any finite charge distribution with net non-zero charge $Q_{net} \\ne 0$ behaves as a point charge, so its equipotential surfaces are approximately concentric spheres.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The work done in carrying an electron along an equipotential surface of potential $50\\text{ V}$ through a distance of $2\\text{ m}$ is:",
    "options": [
      "$0$",
      "$100\\text{ eV}$",
      "$50\\text{ eV}$",
      "$25\\text{ eV}$"
    ],
    "correctAnswer": 0,
    "explanation": "By definition, work done on an equipotential surface is zero because potential difference is zero: $W = q\\Delta V = q(0) = 0$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A uniform electric field of magnitude $E = 100\\text{ V/m}$ is directed along the $+x$-axis. If the potential at $x = 0$ is $V = 0$, the potential at $x = 2\\text{ m}$ is:",
    "options": [
      "$-200\\text{ V}$",
      "$200\\text{ V}$",
      "$-100\\text{ V}$",
      "$100\\text{ V}$"
    ],
    "correctAnswer": 0,
    "explanation": "$V(x) = V(0) - \\int_0^x E\\, dx = 0 - (100)(2) = -200\\text{ V}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electric potential is given by $V(x, y) = 6xy - y + 2y^2$. The electric field vector at $(1, 1)$ is:",
    "options": [
      "$-6\\hat{i} - 9\\hat{j}$",
      "$6\\hat{i} + 9\\hat{j}$",
      "$-6\\hat{i} - 5\\hat{j}$",
      "$-6\\hat{i} + 9\\hat{j}$"
    ],
    "correctAnswer": 0,
    "explanation": "$E_x = -\\frac{\\partial V}{\\partial x} = -6y = -6(1) = -6$. $E_y = -\\frac{\\partial V}{\\partial y} = -(6x - 1 + 4y) = -(6(1) - 1 + 4(1)) = -9$. Thus $\\vec{E} = -6\\hat{i} - 9\\hat{j}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The angle between an electric field line and an equipotential surface passing through the same point is:",
    "options": [
      "$90^\\circ$",
      "$0^\\circ$",
      "$45^\\circ$",
      "$180^\\circ$"
    ],
    "correctAnswer": 0,
    "explanation": "Electric field lines are always orthogonal to equipotential surfaces, so the angle is $90^\\circ$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a certain region of space, the electrostatic potential is constant. Which of the following statements about the electric field in this region is true?",
    "options": [
      "The electric field must be zero everywhere in this region.",
      "The electric field must be uniform and non-zero.",
      "The electric field must be directed towards the origin.",
      "The electric field varies linearly with position."
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\vec{E} = -\\vec{\\nabla}V$ and $V = \\text{constant}$, the gradient of a constant is zero, meaning $\\vec{E} = 0$ everywhere in the region.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An electric charge $q = 2\\mu\\text{C}$ is moved from an equipotential surface of potential $V_1 = 20\\text{ V}$ to another equipotential surface of potential $V_2 = 30\\text{ V}$. Calculate the work done (in $\\mu\\text{J}$) by the external agent.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$W = q(V_2 - V_1) = (2\\mu\\text{C})(30\\text{ V} - 20\\text{ V}) = (2)(10) = 20\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An electric charge $q = 4\\mu\\text{C}$ is moved from an equipotential surface of potential $V_1 = 20\\text{ V}$ to another equipotential surface of potential $V_2 = 40\\text{ V}$. Calculate the work done (in $\\mu\\text{J}$) by the external agent.",
    "options": [],
    "correctAnswer": 80,
    "numericalAnswer": 80,
    "explanation": "$W = q(V_2 - V_1) = (4\\mu\\text{C})(40\\text{ V} - 20\\text{ V}) = (4)(20) = 80\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An electric charge $q = 6\\mu\\text{C}$ is moved from an equipotential surface of potential $V_1 = 20\\text{ V}$ to another equipotential surface of potential $V_2 = 50\\text{ V}$. Calculate the work done (in $\\mu\\text{J}$) by the external agent.",
    "options": [],
    "correctAnswer": 180,
    "numericalAnswer": 180,
    "explanation": "$W = q(V_2 - V_1) = (6\\mu\\text{C})(50\\text{ V} - 20\\text{ V}) = (6)(30) = 180\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An electric charge $q = 8\\mu\\text{C}$ is moved from an equipotential surface of potential $V_1 = 20\\text{ V}$ to another equipotential surface of potential $V_2 = 60\\text{ V}$. Calculate the work done (in $\\mu\\text{J}$) by the external agent.",
    "options": [],
    "correctAnswer": 320,
    "numericalAnswer": 320,
    "explanation": "$W = q(V_2 - V_1) = (8\\mu\\text{C})(60\\text{ V} - 20\\text{ V}) = (8)(40) = 320\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An electric charge $q = 10\\mu\\text{C}$ is moved from an equipotential surface of potential $V_1 = 20\\text{ V}$ to another equipotential surface of potential $V_2 = 70\\text{ V}$. Calculate the work done (in $\\mu\\text{J}$) by the external agent.",
    "options": [],
    "correctAnswer": 500,
    "numericalAnswer": 500,
    "explanation": "$W = q(V_2 - V_1) = (10\\mu\\text{C})(70\\text{ V} - 20\\text{ V}) = (10)(50) = 500\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel planar equipotential surfaces are separated by a distance of $\\Delta x = 5\\text{ cm}$. If the potential difference between them is $\\Delta V = 20\\text{ V}$, find the magnitude of the uniform electric field $E$ (in $\\text{V/m}$) between the surfaces.",
    "options": [],
    "correctAnswer": 400,
    "numericalAnswer": 400,
    "explanation": "$E = \\frac{\\Delta V}{\\Delta x} = \\frac{20\\text{ V}}{0.05\\text{ m}} = 400\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel planar equipotential surfaces are separated by a distance of $\\Delta x = 5\\text{ cm}$. If the potential difference between them is $\\Delta V = 40\\text{ V}$, find the magnitude of the uniform electric field $E$ (in $\\text{V/m}$) between the surfaces.",
    "options": [],
    "correctAnswer": 800,
    "numericalAnswer": 800,
    "explanation": "$E = \\frac{\\Delta V}{\\Delta x} = \\frac{40\\text{ V}}{0.05\\text{ m}} = 800\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel planar equipotential surfaces are separated by a distance of $\\Delta x = 5\\text{ cm}$. If the potential difference between them is $\\Delta V = 60\\text{ V}$, find the magnitude of the uniform electric field $E$ (in $\\text{V/m}$) between the surfaces.",
    "options": [],
    "correctAnswer": 1200,
    "numericalAnswer": 1200,
    "explanation": "$E = \\frac{\\Delta V}{\\Delta x} = \\frac{60\\text{ V}}{0.05\\text{ m}} = 1200\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel planar equipotential surfaces are separated by a distance of $\\Delta x = 5\\text{ cm}$. If the potential difference between them is $\\Delta V = 80\\text{ V}$, find the magnitude of the uniform electric field $E$ (in $\\text{V/m}$) between the surfaces.",
    "options": [],
    "correctAnswer": 1600,
    "numericalAnswer": 1600,
    "explanation": "$E = \\frac{\\Delta V}{\\Delta x} = \\frac{80\\text{ V}}{0.05\\text{ m}} = 1600\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel planar equipotential surfaces are separated by a distance of $\\Delta x = 5\\text{ cm}$. If the potential difference between them is $\\Delta V = 100\\text{ V}$, find the magnitude of the uniform electric field $E$ (in $\\text{V/m}$) between the surfaces.",
    "options": [],
    "correctAnswer": 2000,
    "numericalAnswer": 2000,
    "explanation": "$E = \\frac{\\Delta V}{\\Delta x} = \\frac{100\\text{ V}}{0.05\\text{ m}} = 2000\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electric potential in a region is given by $V(x) = 5x^2\\text{ Volts}$. Find the magnitude of the electric field $E$ (in $\\text{V/m}$) at $x = 2\\text{ m}$.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$E = |-\\frac{dV}{dx}| = |-2(5)x| = 10(2) = 20\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electric potential in a region is given by $V(x) = 10x^2\\text{ Volts}$. Find the magnitude of the electric field $E$ (in $\\text{V/m}$) at $x = 2\\text{ m}$.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "$E = |-\\frac{dV}{dx}| = |-2(10)x| = 20(2) = 40\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electric potential in a region is given by $V(x) = 15x^2\\text{ Volts}$. Find the magnitude of the electric field $E$ (in $\\text{V/m}$) at $x = 2\\text{ m}$.",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$E = |-\\frac{dV}{dx}| = |-2(15)x| = 30(2) = 60\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electric potential in a region is given by $V(x) = 20x^2\\text{ Volts}$. Find the magnitude of the electric field $E$ (in $\\text{V/m}$) at $x = 2\\text{ m}$.",
    "options": [],
    "correctAnswer": 80,
    "numericalAnswer": 80,
    "explanation": "$E = |-\\frac{dV}{dx}| = |-2(20)x| = 40(2) = 80\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electric potential in a region is given by $V(x) = 25x^2\\text{ Volts}$. Find the magnitude of the electric field $E$ (in $\\text{V/m}$) at $x = 2\\text{ m}$.",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$E = |-\\frac{dV}{dx}| = |-2(25)x| = 50(2) = 100\\text{ V/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a uniform electric field of $E = 2\\text{ V/cm}$, equipotential surfaces are spaced apart by distance $\\Delta r$. If consecutive surfaces differ in potential by $\\Delta V = 10\\text{ V}$, find the separation $\\Delta r$ (in cm).",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "$\\Delta r = \\frac{\\Delta V}{E} = \\frac{10\\text{ V}}{2\\text{ V/cm}} = 5\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a uniform electric field of $E = 4\\text{ V/cm}$, equipotential surfaces are spaced apart by distance $\\Delta r$. If consecutive surfaces differ in potential by $\\Delta V = 10\\text{ V}$, find the separation $\\Delta r$ (in cm).",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "$\\Delta r = \\frac{\\Delta V}{E} = \\frac{10\\text{ V}}{4\\text{ V/cm}} = 3\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a uniform electric field of $E = 6\\text{ V/cm}$, equipotential surfaces are spaced apart by distance $\\Delta r$. If consecutive surfaces differ in potential by $\\Delta V = 10\\text{ V}$, find the separation $\\Delta r$ (in cm).",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "$\\Delta r = \\frac{\\Delta V}{E} = \\frac{10\\text{ V}}{6\\text{ V/cm}} = 2\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a uniform electric field of $E = 8\\text{ V/cm}$, equipotential surfaces are spaced apart by distance $\\Delta r$. If consecutive surfaces differ in potential by $\\Delta V = 10\\text{ V}$, find the separation $\\Delta r$ (in cm).",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$\\Delta r = \\frac{\\Delta V}{E} = \\frac{10\\text{ V}}{8\\text{ V/cm}} = 1\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a uniform electric field of $E = 10\\text{ V/cm}$, equipotential surfaces are spaced apart by distance $\\Delta r$. If consecutive surfaces differ in potential by $\\Delta V = 10\\text{ V}$, find the separation $\\Delta r$ (in cm).",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$\\Delta r = \\frac{\\Delta V}{E} = \\frac{10\\text{ V}}{10\\text{ V/cm}} = 1\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Equipotential surfaces",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
