module.exports = [
  {
    "question": "Assertion (A): Total internal reflection occurs only when light travels from an optically denser medium to an optically rarer medium.\nReason (R): When light travels from a denser medium to a rarer medium, the refracted ray bends away from the normal, allowing the angle of refraction to reach $90^\\circ$ at a critical angle of incidence.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "From Snell's law $\\mu_1 \\sin i = \\mu_2 \\sin r$. When $\\mu_1 > \\mu_2$, $r > i$. As $i$ increases, $r$ reaches $90^\\circ$ when $\\sin i_c = \\frac{\\mu_2}{\\mu_1}$. For $i > i_c$, no real refracted ray exists and the light is totally reflected. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The critical angle for a diamond-air interface is exceptionally small (about $24.4^\\circ$).\nReason (R): Diamond has a very high refractive index ($\\mu \\approx 2.42$), and the critical angle is inversely related to refractive index via $\\sin\\theta_c = \\frac{1}{\\mu}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\mu = 2.42$, $\\sin\\theta_c = \\frac{1}{2.42} \\approx 0.4132 \\implies \\theta_c \\approx 24.4^\\circ$. A small critical angle facilitates multiple internal reflections, causing sparkling brilliance. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an optical fibre, the refractive index of the core must be greater than that of the cladding.\nReason (R): Total internal reflection occurs at the core-cladding boundary only when light travels from a medium of higher refractive index to a medium of lower refractive index.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "To guide light along the fibre by successive total internal reflections, the core must be optically denser than the cladding ($\\mu_{core} > \\mu_{cladding}$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): At minimum deviation in a triangular prism, the refracted ray inside the prism travels parallel to the base for an equilateral prism.\nReason (R): At minimum deviation, the angle of incidence equals the angle of emergence ($i = e$), and the two interior angles of refraction are equal ($r_1 = r_2$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By symmetry, at minimum deviation $i = e$ and $r_1 = r_2 = \\frac{A}{2}$. For an isosceles or equilateral prism, this makes the refracted ray parallel to the base. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The refractive index of a prism material can be accurately determined using the angle of the prism $A$ and the angle of minimum deviation $\\delta_m$.\nReason (R): The prism formula relates refractive index to $A$ and $\\delta_m$ by $\\mu = \\frac{\\sin\\left(\\frac{A + \\delta_m}{2}\\right)}{\\sin(A/2)}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "At minimum deviation, $i = \\frac{A + \\delta_m}{2}$ and $r = \\frac{A}{2}$. By Snell's law, $\\mu = \\frac{\\sin i}{\\sin r} = \\frac{\\sin\\left(\\frac{A + \\delta_m}{2}\\right)}{\\sin(A/2)}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A mirage is an optical illusion observed in hot deserts due to total internal reflection.\nReason (R): On hot days, the air near the ground is hot and less dense, causing light rays from the sky to bend continuously upwards until they undergo total internal reflection into an observer's eye.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Temperature decreases with height above the hot desert surface, so refractive index increases upward. Light descending toward the ground bends away from the normal until $i > \\theta_c$, totally reflecting to create the illusion of a water puddle. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A ray of light cannot emerge from a prism if the prism angle $A$ is greater than twice the critical angle ($A > 2\\theta_c$).\nReason (R): For any angle of incidence, the second angle of refraction satisfies $r_2 = A - r_1 > \\theta_c$, so total internal reflection always occurs at the second face.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since maximum possible value of $r_1$ is $\\theta_c$, the minimum value of $r_2$ is $A - \\theta_c$. If $A > 2\\theta_c$, then $r_2 > \\theta_c$ for all possible incidence angles, resulting in total internal reflection at the second face. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The dispersive power of a prism depends only on the material of the prism and is independent of the refracting angle $A$.\nReason (R): Dispersive power is defined as $\\omega = \\frac{\\mu_V - \\mu_R}{\\mu_Y - 1}$, which depends solely on the refractive indices of the material for different wavelengths.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Dispersive power $\\omega = \\frac{\\delta_V - \\delta_R}{\\delta_Y} = \\frac{(\\mu_V - \\mu_R)A}{(\\mu_Y - 1)A} = \\frac{\\mu_V - \\mu_R}{\\mu_Y - 1}$. The angle $A$ cancels out. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): An air bubble inside water shines brightly like a silvery mirror when viewed from certain angles.\nReason (R): Light traveling through water undergoes total internal reflection at the water-air interface of the bubble when the incidence angle exceeds the critical angle.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Water is optically denser ($\\mu = 1.33$) than air ($\\mu = 1.0$). Rays hitting the bubble at $i > \\theta_c \\approx 48.6^\\circ$ are completely reflected, giving it a shining silvery appearance. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Right-angled isosceles prisms (Porro prisms) are widely used in binoculars rather than plane mirrors to invert images.\nReason (R): Total internal reflection in a Porro prism reflects 100% of incident light without silvering degradation or ghost reflections from multiple surfaces.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Plane mirrors absorb about 10-15% of light at each metallic reflection and suffer silver tarnishing over time. TIR prisms reflect 100% of energy with zero absorption loss. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A crown glass prism and a flint glass prism can be combined to produce dispersion without mean deviation.\nReason (R): By properly choosing the refracting angles such that $(\\mu_1 - 1)A_1 = (\\mu_2 - 1)A_2$, the mean deviations produced by the two prisms cancel out while angular dispersion remains non-zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Net mean deviation is $\\delta = (\\mu_1 - 1)A_1 - (\\mu_2 - 1)A_2 = 0$. Since $\\mu$ varies differently with wavelength for the two glasses, the net dispersion $(\\mu_{V1} - \\mu_{R1})A_1 - (\\mu_{V2} - \\mu_{R2})A_2 \\neq 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A crown glass prism and a flint glass prism can be combined to produce deviation without net dispersion (achromatic prism).\nReason (R): Achromatism is achieved by setting the angular dispersions equal and opposite: $(\\mu_{V1} - \\mu_{R1})A_1 = (\\mu_{V2} - \\mu_{R2})A_2$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Equating the angular dispersions gives zero net dispersion for the chosen two colours, while a net deviation $\\delta = (\\mu_{Y1} - 1)A_1 - (\\mu_{Y2} - 1)A_2 \\neq 0$ remains. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a prism is immersed in water, its angle of minimum deviation decreases compared to its value in air.\nReason (R): The relative refractive index of glass with respect to water is less than the refractive index of glass with respect to air.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Relative refractive index $\\mu_{rel} = \\frac{\\mu_g}{\\mu_w} = \\frac{1.5}{1.33} = 1.125 < 1.5$. Since deviation $\\delta_m$ decreases as relative refractive index decreases, $\\delta_m$ in water is smaller than in air. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Red light has a larger critical angle than violet light at a glass-air interface.\nReason (R): According to Cauchy's dispersion formula, the refractive index of glass is smaller for red light than for violet light, and $\\sin\\theta_c = \\frac{1}{\\mu}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\lambda_R > \\lambda_V$, $\\mu_R < \\mu_V$. Therefore $\\sin\\theta_{c,R} = \\frac{1}{\\mu_R} > \\frac{1}{\\mu_V} = \\sin\\theta_{c,V} \\implies \\theta_{c,R} > \\theta_{c,V}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When white light passes through a glass prism, violet light suffers the maximum deviation and red light suffers the minimum deviation.\nReason (R): The refractive index of glass is maximum for violet light and minimum for red light, and the angle of deviation is directly related to refractive index.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For a thin prism $\\delta = (\\mu - 1)A$. Since $\\mu_V > \\mu_R$, it follows that $\\delta_V > \\delta_R$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): An optical fibre can transmit light signals around tight curves with negligible transmission loss.\nReason (R): Light within the core undergoes repeated total internal reflection as long as the angle of incidence on the core-cladding boundary exceeds the critical angle.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Even when the fibre is bent, provided the radius of curvature is not too sharp, the angle of incidence remains above the critical angle, preserving TIR. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The acceptance angle $\\theta_a$ of an optical fibre represents the maximum angle of incidence at the core entrance for which light undergoes TIR inside the core.\nReason (R): The numerical aperture of an optical fibre is given by $NA = \\sin\\theta_a = \\sqrt{\\mu_1^2 - \\mu_2^2}$, where $\\mu_1$ is the core index and $\\mu_2$ is the cladding index.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Applying Snell's law at the entrance face and using the critical angle condition $\\sin\\phi_c = \\frac{\\mu_2}{\\mu_1}$ at the wall yields $\\sin\\theta_a = \\sqrt{\\mu_1^2 - \\mu_2^2}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A swimmer under water looking up at the flat water surface sees the outside world compressed into a circular cone of half-angle equal to the critical angle.\nReason (R): Rays of light entering water from air in all directions ($0$ to $90^\\circ$) are refracted into water within a cone of semi-vertical angle $\\theta_c = \\sin^{-1}(1/\\mu)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the maximum angle of refraction in water corresponding to $i = 90^\\circ$ is $r_{max} = \\theta_c = \\sin^{-1}(1/\\mu) \\approx 48.6^\\circ$, the entire $180^\\circ$ horizon is compressed into a circle of vision of half-angle $\\theta_c$ (Snell's window). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A ray incident normally on one face of an equilateral glass prism of refractive index $\\sqrt{2}$ undergoes total internal reflection at the second face.\nReason (R): The angle of incidence at the second face is $60^\\circ$, which is greater than the critical angle $\\theta_c = \\sin^{-1}(1/\\sqrt{2}) = 45^\\circ$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For normal incidence at face 1, $r_1 = 0$. Since $r_1 + r_2 = A = 60^\\circ$, $r_2 = 60^\\circ$. The critical angle is $\\theta_c = \\sin^{-1}(1/\\sqrt{2}) = 45^\\circ$. Because $r_2 = 60^\\circ > 45^\\circ$, total internal reflection occurs at the second face. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Total internal reflection is accompanied by a phase change between the reflected electric field components.\nReason (R): Beyond the critical angle, an evanescent wave penetrates into the rarer medium, decaying exponentially with distance from the interface.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In TIR, electromagnetic boundary conditions require an evanescent wave in the rarer medium, which causes a non-zero phase shift between $s$- and $p$-polarizations (Goos-Hänchen effect). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If the angle of a prism is equal to its angle of minimum deviation ($A = \\delta_m$), the refractive index of the prism is $\\mu = 2\\cos(A/2)$.\nReason (R): Substituting $\\delta_m = A$ into the prism formula gives $\\mu = \\frac{\\sin(A)}{\\sin(A/2)} = \\frac{2\\sin(A/2)\\cos(A/2)}{\\sin(A/2)} = 2\\cos(A/2)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Using the prism formula $\\mu = \\frac{\\sin\\left(\\frac{A + \\delta_m}{2}\\right)}{\\sin(A/2)}$ with $\\delta_m = A$ gives $\\mu = \\frac{\\sin A}{\\sin(A/2)} = 2\\cos(A/2)$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a ray of light is refracted through a prism at minimum deviation, the angle of deviation does not change if the direction of the ray is reversed.\nReason (R): The principle of reversibility of light states that the path of a light ray is strictly reversible.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By the principle of reversibility, reversing the emergent ray makes it follow the exact same path in reverse, maintaining the same angle of incidence and deviation. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A hollow prism filled with water produces less deviation than an identical solid glass prism in air.\nReason (R): The refractive index of water (1.33) is less than the refractive index of glass (1.5).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Deviation $\\delta \\approx (\\mu - 1)A$. Since $\\mu_{water} < \\mu_{glass}$, the deviation produced by a water prism is smaller than that of a glass prism. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Diamonds cut by expert lapidaries have multiple facets angled to maximize internal reflections.\nReason (R): Cutting the facets properly ensures that light entering the top face strikes inner facets at angles greater than the critical angle ($24.4^\\circ$), trapping light until it emerges with high brilliance from the crown.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By designing facets such that $i > 24.4^\\circ$, almost all light entering the diamond undergoes multiple TIRs and emerges through the top face, creating dazzling sparkle. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a prism, the deviation $\\delta$ is minimum for a unique angle of incidence.\nReason (R): The graph of deviation $\\delta$ versus angle of incidence $i$ is a parabolic-like curve that possesses a single minimum where $i = e$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The $\\delta-i$ curve has a unique minimum at $i = e$. For any other deviation $\\delta > \\delta_m$, there are two distinct angles of incidence corresponding to the same deviation. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Total internal reflection can occur when light travels from air into glass.\nReason (R): The speed of light in glass is less than the speed of light in air.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "(A) is false because TIR can only occur when light travels from an optically denser medium to an optically rarer medium (glass into air). (R) is true because $v = c/\\mu$, and $\\mu_{glass} > \\mu_{air}$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light is incident at an angle of $60^\\circ$ on one face of a prism of angle $30^\\circ$. The emergent ray makes an angle of $30^\\circ$ with the incident ray. The angle of emergence is:",
    "options": [
      "$0^\\circ$",
      "$30^\\circ$",
      "$45^\\circ$",
      "$60^\\circ$"
    ],
    "correctAnswer": 0,
    "explanation": "In a prism, $\\delta = i + e - A$. Given $i = 60^\\circ$, $A = 30^\\circ$, and $\\delta = 30^\\circ$. Thus $30^\\circ = 60^\\circ + e - 30^\\circ \\implies 30^\\circ = 30^\\circ + e \\implies e = 0^\\circ$ (the ray emerges perpendicularly to the second face).",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The angle of a prism is $A$ and its refractive index is $\\cot(A/2)$. The angle of minimum deviation $\\delta_m$ is:",
    "options": [
      "$180^\\circ - 2A$",
      "$90^\\circ - A$",
      "$180^\\circ - A$",
      "$2A$"
    ],
    "correctAnswer": 0,
    "explanation": "Using the prism formula: $\\mu = \\frac{\\sin\\left(\\frac{A + \\delta_m}{2}\\right)}{\\sin(A/2)}$. Given $\\mu = \\cot(A/2) = \\frac{\\cos(A/2)}{\\sin(A/2)}$. Therefore, $\\sin\\left(\\frac{A + \\delta_m}{2}\\right) = \\cos(A/2) = \\sin(90^\\circ - A/2)$. Equating arguments: $\\frac{A + \\delta_m}{2} = 90^\\circ - \\frac{A}{2} \\implies A + \\delta_m = 180^\\circ - A \\implies \\delta_m = 180^\\circ - 2A$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A light ray falls on a prism of angle $60^\\circ$ and refractive index $\\sqrt{2}$ at an angle of incidence $i$. If the ray suffers minimum deviation, the angle of incidence $i$ and minimum deviation $\\delta_m$ are:",
    "options": [
      "$i = 45^\\circ,\\ \\delta_m = 30^\\circ$",
      "$i = 60^\\circ,\\ \\delta_m = 60^\\circ$",
      "$i = 30^\\circ,\\ \\delta_m = 45^\\circ$",
      "$i = 45^\\circ,\\ \\delta_m = 45^\\circ$"
    ],
    "correctAnswer": 0,
    "explanation": "At minimum deviation, $r = \\frac{A}{2} = \\frac{60^\\circ}{2} = 30^\\circ$. By Snell's law: $\\sin i = \\mu \\sin r = \\sqrt{2} \\sin(30^\\circ) = \\frac{\\sqrt{2}}{2} = \\frac{1}{\\sqrt{2}} \\implies i = 45^\\circ$. Then $\\delta_m = 2i - A = 2(45^\\circ) - 60^\\circ = 30^\\circ$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An optical fibre has a core of refractive index $1.5$ and a cladding of refractive index $1.414$ ($\\sqrt{2}$). The numerical aperture (NA) of the fibre for light entering from air is:",
    "options": [
      "0.5",
      "0.707",
      "0.25",
      "0.866"
    ],
    "correctAnswer": 0,
    "explanation": "Numerical aperture $NA = \\sqrt{\\mu_{core}^2 - \\mu_{cladding}^2} = \\sqrt{1.5^2 - (\\sqrt{2})^2} = \\sqrt{2.25 - 2} = \\sqrt{0.25} = 0.5$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point source of light is placed at the bottom of a water tank of depth $h = \\sqrt{7}\\text{ m}$. The refractive index of water is $\\mu = \\frac{4}{3}$. The area of the surface of water through which light can emerge out is:",
    "options": [
      "$9\\pi\\text{ m}^2$",
      "$7\\pi\\text{ m}^2$",
      "$16\\pi\\text{ m}^2$",
      "$3\\pi\\text{ m}^2$"
    ],
    "correctAnswer": 0,
    "explanation": "Radius of the circular illuminated patch is $R = \\frac{h}{\\sqrt{\\mu^2 - 1}} = \\frac{\\sqrt{7}}{\\sqrt{(4/3)^2 - 1}} = \\frac{\\sqrt{7}}{\\sqrt{16/9 - 1}} = \\frac{\\sqrt{7}}{\\sqrt{7/9}} = \\frac{\\sqrt{7}}{\\sqrt{7}/3} = 3\\text{ m}$. Area $A = \\pi R^2 = \\pi (3)^2 = 9\\pi\\text{ m}^2$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The refractive index of the material of a prism for red, yellow, and violet colours are $1.61$, $1.63$, and $1.65$ respectively. The dispersive power of the prism material is:",
    "options": [
      "0.0635",
      "0.0400",
      "0.0245",
      "0.0812"
    ],
    "correctAnswer": 0,
    "explanation": "Dispersive power $\\omega = \\frac{\\mu_V - \\mu_R}{\\mu_Y - 1} = \\frac{1.65 - 1.61}{1.63 - 1} = \\frac{0.04}{0.63} \\approx 0.0635$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light is incident normally on one face of a right-angled isosceles prism of refractive index $\\mu$. If the ray is totally reflected at the hypotenuse face, the minimum value of $\\mu$ is:",
    "options": [
      "$\\sqrt{2}$",
      "1.5",
      "$\\frac{2}{\\sqrt{3}}$",
      "1.33"
    ],
    "correctAnswer": 0,
    "explanation": "For a right-angled isosceles prism, the angle of incidence at the hypotenuse face is $45^\\circ$. For total internal reflection to occur, $i \\ge \\theta_c \\implies \\sin(45^\\circ) \\ge \\frac{1}{\\mu} \\implies \\frac{1}{\\sqrt{2}} \\ge \\frac{1}{\\mu} \\implies \\mu \\ge \\sqrt{2}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light passes through an equilateral glass prism with minimum deviation of $30^\\circ$. The refractive index of the prism is $\\sqrt{x}$. The value of $10 x$ is:",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$A = 60^\\circ, \\delta_m = 30^\\circ$. $\\mu = \\frac{\\sin((60^\\circ+30^\\circ)/2)}{\\sin(60^\\circ/2)} = \\frac{\\sin(45^\\circ)}{\\sin(30^\\circ)} = \\frac{1/\\sqrt{2}}{1/2} = \\sqrt{2}$. Thus $x = 2$, and $10 x = 20$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The critical angle for a certain medium is $45^\\circ$. Taking $\\sqrt{2} = 1.414$, the refractive index of the medium (rounded to two decimal places) is:",
    "options": [],
    "correctAnswer": 1.41,
    "numericalAnswer": 1.41,
    "explanation": "$\\mu = \\frac{1}{\\sin\\theta_c} = \\frac{1}{\\sin 45^\\circ} = \\sqrt{2} \\approx 1.41$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A small bulb is placed at the bottom of a tank filled with water ($\\mu = \\frac{4}{3}$) to a depth of $70\\text{ cm}$. The radius of the circular surface on water through which light emerges in $\\text{cm}$ is (rounded to nearest integer, taking $\\sqrt{7} = 2.646$):",
    "options": [],
    "correctAnswer": 79,
    "numericalAnswer": 79,
    "explanation": "$R = \\frac{h}{\\sqrt{\\mu^2 - 1}} = \\frac{70}{\\sqrt{(16/9) - 1}} = \\frac{70}{\\sqrt{7}/3} = \\frac{210}{\\sqrt{7}} = 30\\sqrt{7} \\approx 30 \\times 2.646 \\approx 79.4 \\approx 79\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An optical fibre has a core of refractive index $1.5$ and cladding of refractive index $\\sqrt{2} \\approx 1.414$. The numerical aperture of the fibre is:",
    "options": [],
    "correctAnswer": 0.5,
    "numericalAnswer": 0.5,
    "explanation": "$NA = \\sqrt{\\mu_{core}^2 - \\mu_{cladding}^2} = \\sqrt{2.25 - 2} = \\sqrt{0.25} = 0.5$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The refracting angle of a thin prism is $6^\\circ$ and its refractive index is $1.5$. The angle of deviation produced by the prism in degrees is:",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "$\\delta = (\\mu - 1)A = (1.5 - 1) \\times 6^\\circ = 0.5 \\times 6^\\circ = 3^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A prism of angle $60^\\circ$ has a refractive index of $1.5$. If the angle of minimum deviation is $\\delta_m$, the value of $\\sin\\left(\\frac{60^\\circ + \\delta_m}{2}\\right)$ is:",
    "options": [],
    "correctAnswer": 0.75,
    "numericalAnswer": 0.75,
    "explanation": "$\\mu = \\frac{\\sin((A+\\delta_m)/2)}{\\sin(A/2)} \\implies 1.5 = \\frac{\\sin((60^\\circ+\\delta_m)/2)}{\\sin(30^\\circ)} \\implies \\sin((60^\\circ+\\delta_m)/2) = 1.5 \\times 0.5 = 0.75$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "For a prism with $A = 60^\\circ$ and $\\mu = \\sqrt{3}$, the angle of minimum deviation in degrees is:",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$\\mu = \\frac{\\sin((60^\\circ+\\delta_m)/2)}{\\sin(30^\\circ)} = \\sqrt{3} \\implies \\sin((60^\\circ+\\delta_m)/2) = \\frac{\\sqrt{3}}{2} \\implies \\frac{60^\\circ+\\delta_m}{2} = 60^\\circ \\implies \\delta_m = 60^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The critical angle of a glass prism for yellow light is $42^\\circ$. If a ray is incident at an angle of $45^\\circ$ inside the glass at the interface with air, the percentage of incident intensity that is transmitted into air is:",
    "options": [],
    "correctAnswer": 0,
    "numericalAnswer": 0,
    "explanation": "Since $i = 45^\\circ > 42^\\circ = \\theta_c$, total internal reflection occurs, and 100% of light is reflected. Zero percentage is transmitted into air.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray is incident on a prism of angle $A = 4^\\circ$ made of glass with $\\mu = 1.6$. The angle of deviation in degrees is:",
    "options": [],
    "correctAnswer": 2.4,
    "numericalAnswer": 2.4,
    "explanation": "$\\delta = (\\mu - 1)A = (1.6 - 1) \\times 4^\\circ = 0.6 \\times 4^\\circ = 2.4^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A thin prism having an angle of $8^\\circ$ has refractive indices $\\mu_V = 1.65$ and $\\mu_R = 1.60$. The angular dispersion between violet and red rays in degrees is:",
    "options": [],
    "correctAnswer": 0.4,
    "numericalAnswer": 0.4,
    "explanation": "$\\theta = (\\mu_V - \\mu_R)A = (1.65 - 1.60) \\times 8^\\circ = 0.05 \\times 8^\\circ = 0.4^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light traveling in water ($\\mu = 1.33$) is incident on a glass plate ($\\mu = 1.50$). The critical angle for total internal reflection between these two media exists only when light travels from glass to water. Its value in degrees (taking $\\sin(62.5^\\circ) = 0.887$) is (rounded to nearest integer):",
    "options": [],
    "correctAnswer": 63,
    "numericalAnswer": 63,
    "explanation": "$\\sin\\theta_c = \\frac{\\mu_w}{\\mu_g} = \\frac{1.333}{1.500} = \\frac{8}{9} \\approx 0.8889 \\implies \\theta_c \\approx 62.7^\\circ \\approx 63^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an equilateral prism ($A = 60^\\circ$), the angle of incidence is $48^\\circ$ and the angle of emergence is $48^\\circ$. The angle of deviation in degrees is:",
    "options": [],
    "correctAnswer": 36,
    "numericalAnswer": 36,
    "explanation": "$\\delta = i + e - A = 48^\\circ + 48^\\circ - 60^\\circ = 96^\\circ - 60^\\circ = 36^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The critical angle for a medium is $30^\\circ$. The speed of light in this medium in $\\text{km/s}$ is (taking $c = 3 \\times 10^5\\text{ km/s}$):",
    "options": [],
    "correctAnswer": 150000,
    "numericalAnswer": 150000,
    "explanation": "$\\mu = \\frac{1}{\\sin 30^\\circ} = 2$. Speed $v = \\frac{c}{\\mu} = \\frac{3 \\times 10^5}{2} = 1.5 \\times 10^5\\text{ km/s} = 150000\\text{ km/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A light pipe made of glass with refractive index $1.5$ is surrounded by air. The maximum angle of incidence $\\theta_a$ in air for total internal reflection along the pipe has $\\sin\\theta_a = 1.0$. What is the critical angle $\\theta_c$ inside the pipe in degrees (taking $\\sin(41.8^\\circ) = \\frac{1}{1.5}$)? (Round to one decimal place):",
    "options": [],
    "correctAnswer": 41.8,
    "numericalAnswer": 41.8,
    "explanation": "$\\sin\\theta_c = \\frac{1}{\\mu} = \\frac{1}{1.5} \\approx 0.6667 \\implies \\theta_c \\approx 41.8^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A prism of angle $60^\\circ$ produces an angle of minimum deviation of $40^\\circ$. The angle of incidence at minimum deviation in degrees is:",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "$i = \\frac{A + \\delta_m}{2} = \\frac{60^\\circ + 40^\\circ}{2} = 50^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The dispersive power of a prism is $0.05$. If the mean deviation is $40^\\circ$, the angular dispersion in degrees is:",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "$\\theta = \\omega \\delta_Y = 0.05 \\times 40^\\circ = 2^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A crown glass prism of angle $6^\\circ$ ($\\mu = 1.5$) is combined with a flint glass prism ($\\mu = 1.6$) to produce dispersion without mean deviation. The angle of the flint glass prism in degrees is:",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "$(\\mu_1 - 1)A_1 = (\\mu_2 - 1)A_2 \\implies (1.5 - 1)(6^\\circ) = (1.6 - 1)A_2 \\implies 0.5 \\times 6 = 0.6 A_2 \\implies A_2 = \\frac{3}{0.6} = 5^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray incident at $45^\\circ$ on an equilateral prism undergoes minimum deviation. The angle of refraction inside the prism in degrees is:",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "At minimum deviation, $r_1 = r_2 = \\frac{A}{2} = \\frac{60^\\circ}{2} = 30^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point source of light is at a depth of $3\\text{ m}$ in a liquid of refractive index $\\sqrt{2}$. The radius of the circular opening on the surface through which light emerges in meters is:",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "$R = \\frac{h}{\\sqrt{\\mu^2 - 1}} = \\frac{3}{\\sqrt{(\\sqrt{2})^2 - 1}} = \\frac{3}{\\sqrt{2 - 1}} = 3\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An optical fibre has a core index of $1.50$ and a cladding index of $1.414$. The numerical aperture of the fibre is $NA = 0.5$. The acceptance angle in degrees is:",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "$\\sin\\theta_a = NA = 0.5 \\implies \\theta_a = 30^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Total internal reflection and prisms",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
