module.exports = [
  {
    "type": "NUMERICAL",
    "question": "A uniform solid sphere of mass $M$ and radius $R$ rolls without slipping down an inclined plane of inclination $30^\\circ$. What is the linear acceleration of its center of mass in $\\text{m/s}^2$ (take $g = 9.8\\,\\text{m/s}^2$)?",
    "correctAnswer": 3.5,
    "explanation": "$a = \\frac{g\\sin\\theta}{1 + k^2/R^2} = \\frac{9.8\\sin(30^\\circ)}{1 + 2/5} = \\frac{9.8(0.5)}{7/5} = \\frac{4.9 \\times 5}{7} = 3.5\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform circular disc rolls down the same $30^\\circ$ incline without slipping. What is its linear acceleration in $\\text{m/s}^2$ (take $g = 9.8\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 3.27,
    "explanation": "For a disc, $k^2/R^2 = 1/2$. $a = \\frac{g\\sin(30^\\circ)}{1 + 1/2} = \\frac{4.9}{3/2} = \\frac{9.8}{3} \\approx 3.267 \\approx 3.27\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A thin hollow spherical shell rolls down the same $30^\\circ$ incline without slipping. What is its linear acceleration in $\\text{m/s}^2$ (take $g = 9.8\\,\\text{m/s}^2$)?",
    "correctAnswer": 2.94,
    "explanation": "For a spherical shell, $k^2/R^2 = 2/3$. $a = \\frac{g\\sin(30^\\circ)}{1 + 2/3} = \\frac{4.9}{5/3} = \\frac{4.9 \\times 3}{5} = \\frac{14.7}{5} = 2.94\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A thin circular ring rolls down the same $30^\\circ$ incline without slipping. What is its linear acceleration in $\\text{m/s}^2$ (take $g = 9.8\\,\\text{m/s}^2$)?",
    "correctAnswer": 2.45,
    "explanation": "For a ring, $k^2/R^2 = 1$. $a = \\frac{g\\sin(30^\\circ)}{1 + 1} = \\frac{4.9}{2} = 2.45\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid cylinder of mass $2\\,\\text{kg}$ rolls without slipping down an incline of angle $30^\\circ$. What is the magnitude of the static friction force in newtons acting on the cylinder (take $g = 10\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 3.33,
    "explanation": "Frictional force is $f = \\frac{mg\\sin\\theta}{1 + R^2/k^2}$. For a solid cylinder, $k^2/R^2 = 1/2 \\implies R^2/k^2 = 2$. Thus $f = \\frac{mg\\sin(30^\\circ)}{1 + 2} = \\frac{2(10)(0.5)}{3} = \\frac{10}{3} \\approx 3.33\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "What is the minimum coefficient of static friction $\\mu_s$ required for a uniform solid sphere to roll without slipping down an inclined plane of inclination $45^\\circ$ (round to two decimal places)?",
    "correctAnswer": 0.29,
    "explanation": "For a solid sphere, $\\mu_{\\min} = \\frac{\\tan\\theta}{1 + R^2/k^2} = \\frac{\\tan(45^\\circ)}{1 + 5/2} = \\frac{1}{7/2} = \\frac{2}{7} \\approx 0.2857 \\approx 0.29$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "What is the minimum coefficient of static friction $\\mu_s$ required for a uniform solid cylinder to roll without slipping down the same $45^\\circ$ incline (round to two decimal places)?",
    "correctAnswer": 0.33,
    "explanation": "For a solid cylinder, $\\mu_{\\min} = \\frac{\\tan(45^\\circ)}{1 + 2} = \\frac{1}{3} \\approx 0.33$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "What is the minimum coefficient of static friction $\\mu_s$ required for a thin circular ring to roll without slipping down a $45^\\circ$ incline?",
    "correctAnswer": 0.5,
    "explanation": "For a ring, $k^2/R^2 = 1 \\implies R^2/k^2 = 1$. $\\mu_{\\min} = \\frac{\\tan(45^\\circ)}{1 + 1} = \\frac{1}{2} = 0.50$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolls from rest down an incline of height $h = 7\\,\\text{m}$. What is its linear speed in $\\text{m/s}$ when it reaches the bottom (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 10,
    "explanation": "$v = \\sqrt{\\frac{2gh}{1 + k^2/R^2}} = \\sqrt{\\frac{2(10)(7)}{1 + 2/5}} = \\sqrt{\\frac{140}{7/5}} = \\sqrt{\\frac{140 \\times 5}{7}} = \\sqrt{20 \\times 5} = \\sqrt{100} = 10\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform disc rolls from rest down an incline of height $h = 6\\,\\text{m}$. What is its linear speed in $\\text{m/s}$ at the bottom (take $g = 10\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 8.9,
    "explanation": "$v = \\sqrt{\\frac{2gh}{1 + 1/2}} = \\sqrt{\\frac{2(10)(6)}{1.5}} = \\sqrt{\\frac{120}{1.5}} = \\sqrt{80} \\approx 8.94 \\approx 8.9\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "An Atwood machine consists of two blocks of masses $m_1 = 3\\,\\text{kg}$ and $m_2 = 2\\,\\text{kg}$ connected by a light string passing over a pulley of mass $M_p = 2\\,\\text{kg}$ and radius $R$ (modeled as a uniform disc). What is the linear acceleration of the blocks in $\\text{m/s}^2$ (take $g = 10\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 1.67,
    "explanation": "Equivalent mass of pulley disc is $M_p/2 = 2/2 = 1\\,\\text{kg}$. Acceleration is $a = \\frac{(m_1 - m_2)g}{m_1 + m_2 + M_p/2} = \\frac{(3 - 2)(10)}{3 + 2 + 1} = \\frac{10}{6} = \\frac{5}{3} \\approx 1.67\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the Atwood machine in the previous problem, what is the tension $T_1$ on the heavier $3\\,\\text{kg}$ mass side in newtons?",
    "correctAnswer": 25,
    "explanation": "For the descending mass: $m_1 g - T_1 = m_1 a \\implies T_1 = m_1(g - a) = 3(10 - 5/3) = 3(25/3) = 25\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the Atwood machine in the previous problem, what is the tension $T_2$ on the lighter $2\\,\\text{kg}$ mass side in newtons (rounded to one decimal place)?",
    "correctAnswer": 23.3,
    "explanation": "For the ascending mass: $T_2 - m_2 g = m_2 a \\implies T_2 = m_2(g + a) = 2(10 + 5/3) = 2(35/3) = \\frac{70}{3} \\approx 23.33 \\approx 23.3\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A block of mass $m = 4\\,\\text{kg}$ hangs from a string wrapped around a pulley of mass $M_p = 4\\,\\text{kg}$ and radius $R = 0.2\\,\\text{m}$ (solid disc). What is the angular acceleration of the pulley in $\\text{rad/s}^2$ (take $g = 9.8\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 32.7,
    "explanation": "Linear acceleration is $a = \\frac{mg}{m + M_p/2} = \\frac{4(9.8)}{4 + 2} = \\frac{39.2}{6} \\approx 6.533\\,\\text{m/s}^2$. Angular acceleration is $\\alpha = \\frac{a}{R} = \\frac{6.533}{0.2} = 32.667 \\approx 32.7\\,\\text{rad/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A ring and a solid sphere of the same mass and radius roll down an incline of length $s$ from rest without slipping. What is the ratio of the time taken by the ring to that by the solid sphere (take $\\sqrt{1.4} \\approx 1.18$)? Round to two decimal places.",
    "correctAnswer": 1.18,
    "explanation": "Time taken is $t = \\sqrt{\\frac{2s(1 + k^2/R^2)}{g\\sin\\theta}} \\propto \\sqrt{1 + k^2/R^2}$. For ring: $\\sqrt{1 + 1} = \\sqrt{2}$. For solid sphere: $\\sqrt{1 + 2/5} = \\sqrt{7/5}$. Ratio is $\\frac{t_{\\text{ring}}}{t_{\\text{sphere}}} = \\sqrt{\\frac{2}{7/5}} = \\sqrt{\\frac{10}{7}} = \\sqrt{1.4286} \\approx 1.195 \\approx 1.20$. Let's check $\\sqrt{10/7} = 1.1952 \\approx 1.20$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolls down an incline of angle $\\theta = 30^\\circ$. What fraction of the total force along the incline ($mg\\sin\\theta$) is the friction force?",
    "correctAnswer": 0.29,
    "explanation": "$f = \\frac{mg\\sin\\theta}{1 + R^2/k^2} = \\frac{mg\\sin\\theta}{1 + 5/2} = \\frac{2}{7}mg\\sin\\theta \\approx 0.2857 mg\\sin\\theta \\approx 0.29 mg\\sin\\theta$. Fraction is $0.29$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid cylinder rolls down an incline of angle $\\theta = 30^\\circ$. What fraction of $mg\\sin\\theta$ is the friction force (rounded to two decimal places)?",
    "correctAnswer": 0.33,
    "explanation": "$f = \\frac{mg\\sin\\theta}{1 + 2} = \\frac{1}{3}mg\\sin\\theta \\approx 0.33 mg\\sin\\theta$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A hollow sphere of mass $M$ rolls without slipping down an incline of angle $\\theta = 30^\\circ$. What fraction of $mg\\sin\\theta$ is the friction force?",
    "correctAnswer": 0.4,
    "explanation": "For a hollow sphere, $k^2/R^2 = 2/3 \\implies R^2/k^2 = 3/2$. Thus $f = \\frac{mg\\sin\\theta}{1 + 3/2} = \\frac{2}{5}mg\\sin\\theta = 0.40 mg\\sin\\theta$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A ring rolls without slipping down an incline of angle $\\theta = 30^\\circ$. What fraction of $mg\\sin\\theta$ is the friction force?",
    "correctAnswer": 0.5,
    "explanation": "For a ring, $R^2/k^2 = 1$. $f = \\frac{mg\\sin\\theta}{1 + 1} = 0.50 mg\\sin\\theta$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform disc of mass $2\\,\\text{kg}$ and radius $0.2\\,\\text{m}$ has a string wound around it. One end of the string is fixed to the ceiling and the disc is allowed to fall vertically unwinding the string (like a yoyo). What is the downward acceleration in $\\text{m/s}^2$ (take $g = 9.8\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 6.53,
    "explanation": "$a = \\frac{g}{1 + k^2/R^2} = \\frac{g}{1 + 1/2} = \\frac{2}{3}g = \\frac{2}{3}(9.8) = \\frac{19.6}{3} \\approx 6.53\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the falling disc in the previous problem, what is the tension in the string in newtons (rounded to one decimal place)?",
    "correctAnswer": 6.5,
    "explanation": "Equation of motion: $mg - T = ma \\implies T = m(g - a) = m(g - 2g/3) = \\frac{1}{3}mg = \\frac{1}{3}(2)(9.8) = \\frac{19.6}{3} \\approx 6.53 \\approx 6.5\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A cylinder of mass $M$ and radius $R$ rolls down an incline of height $h = 3\\,\\text{m}$. What is its translational speed in $\\text{m/s}$ at the bottom (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 6.32,
    "explanation": "$v = \\sqrt{\\frac{4gh}{3}} = \\sqrt{\\frac{4(10)(3)}{3}} = \\sqrt{40} \\approx 6.32\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "Four objects—a ring, a solid disc, a solid sphere, and a spherical shell—all of the same mass and radius, roll without slipping down the same incline. How many of them reach the bottom before the solid disc?",
    "correctAnswer": 1,
    "explanation": "The linear accelerations are: Solid sphere ($a = 5/7 g\\sin\\theta \\approx 0.714$), Solid disc ($a = 2/3 g\\sin\\theta \\approx 0.667$), Spherical shell ($a = 3/5 g\\sin\\theta = 0.600$), Ring ($a = 1/2 g\\sin\\theta = 0.500$). Only 1 object (the solid sphere) has a greater acceleration and reaches the bottom before the disc.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform solid cylinder of mass $6\\,\\text{kg}$ rolls down an incline of inclination $30^\\circ$. What is the linear acceleration of its center of mass in $\\text{m/s}^2$ (take $g = 10\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 3.33,
    "explanation": "$a = \\frac{g\\sin(30^\\circ)}{1 + 1/2} = \\frac{10(0.5)}{1.5} = \\frac{5}{1.5} = \\frac{10}{3} \\approx 3.33\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere is released from rest at the top of an incline of length $s = 14\\,\\text{m}$ and inclination $30^\\circ$. What is the time in seconds taken to reach the bottom (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 2.8,
    "explanation": "Acceleration is $a = \\frac{5}{7}g\\sin(30^\\circ) = \\frac{5}{7}(10)(0.5) = \\frac{25}{7} \\approx 3.571\\,\\text{m/s}^2$. Time taken is $t = \\sqrt{\\frac{2s}{a}} = \\sqrt{\\frac{2(14)}{25/7}} = \\sqrt{\\frac{28 \\times 7}{25}} = \\sqrt{\\frac{196}{25}} = \\frac{14}{5} = 2.8\\,\\text{s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform hoop rolls down an incline of angle $30^\\circ$. What is its acceleration in $\\text{m/s}^2$ (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 2.5,
    "explanation": "$a = \\frac{g\\sin(30^\\circ)}{1 + 1} = \\frac{5}{2} = 2.5\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere and a disc of equal mass and radius roll down an incline of height $h$. What is the ratio of their final speeds at the bottom, $v_{\\text{sphere}} / v_{\\text{disc}}$?",
    "correctAnswer": 1.03,
    "explanation": "$\\frac{v_{\\text{sphere}}}{v_{\\text{disc}}} = \\sqrt{\\frac{1 + 1/2}{1 + 2/5}} = \\sqrt{\\frac{3/2}{7/5}} = \\sqrt{\\frac{15}{14}} = \\sqrt{1.0714} \\approx 1.035 \\approx 1.03$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A massless rope is wrapped around a massive cylindrical pulley of mass $M = 8\\,\\text{kg}$ and radius $R = 0.5\\,\\text{m}$. A downward force of $40\\,\\text{N}$ is applied to the free end of the rope. What is the angular acceleration of the pulley in $\\text{rad/s}^2$?",
    "correctAnswer": 20,
    "explanation": "Moment of inertia is $I = \\frac{1}{2}M R^2 = \\frac{1}{2}(8)(0.25) = 1.0\\,\\text{kg}\\cdot\\text{m}^2$. Applied torque is $\\tau = F R = 40 \\times 0.5 = 20\\,\\text{N}\\cdot\\text{m}$. Angular acceleration is $\\alpha = \\frac{\\tau}{I} = \\frac{20}{1.0} = 20\\,\\text{rad/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A block of mass $m = 2\\,\\text{kg}$ rests on a frictionless horizontal table and is attached to a string passing over a pulley of mass $M_p = 2\\,\\text{kg}$ (disc) to a hanging mass of $3\\,\\text{kg}$. What is the linear acceleration of the system in $\\text{m/s}^2$ (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 5,
    "explanation": "Effective mass of pulley is $M_p/2 = 2/2 = 1\\,\\text{kg}$. Driving force is $m_{\\text{hang}} g = 3(10) = 30\\,\\text{N}$. Total effective mass is $m_{\\text{table}} + m_{\\text{hang}} + M_p/2 = 2 + 3 + 1 = 6\\,\\text{kg}$. Acceleration is $a = \\frac{30}{6} = 5\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the system in the previous problem, what is the tension in the string attached to the $2\\,\\text{kg}$ block on the table in newtons?",
    "correctAnswer": 10,
    "explanation": "$T_{\\text{table}} = m_{\\text{table}} a = 2 \\times 5 = 10\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the system in the previous problem, what is the tension in the string attached to the hanging $3\\,\\text{kg}$ mass in newtons?",
    "correctAnswer": 15,
    "explanation": "$m_{\\text{hang}} g - T_{\\text{hang}} = m_{\\text{hang}} a \\implies T_{\\text{hang}} = 3(10 - 5) = 15\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolls up an incline of angle $30^\\circ$ without slipping with initial velocity $v_0 = 10\\,\\text{m/s}$. What is the distance along the incline in meters traveled before stopping (take $g = 9.8\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 14.3,
    "explanation": "Deceleration along the incline is $a = \\frac{5}{7}g\\sin(30^\\circ) = \\frac{5}{7}(9.8)(0.5) = 3.5\\,\\text{m/s}^2$. Distance traveled is $s = \\frac{v_0^2}{2a} = \\frac{100}{2(3.5)} = \\frac{100}{7} \\approx 14.285 \\approx 14.3\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "If a disc rolls up the same $30^\\circ$ incline with initial velocity $v_0 = 10\\,\\text{m/s}$, what is the distance along the incline in meters traveled before stopping (take $g = 9.8\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 15.3,
    "explanation": "Deceleration of disc is $a = \\frac{2}{3}g\\sin(30^\\circ) = \\frac{2}{3}(9.8)(0.5) = \\frac{9.8}{3} \\approx 3.267\\,\\text{m/s}^2$. Distance is $s = \\frac{100}{2(9.8/3)} = \\frac{300}{19.6} \\approx 15.31 \\approx 15.3\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A hollow sphere rolls up the same $30^\\circ$ incline with $v_0 = 10\\,\\text{m/s}$. What is the distance along the incline in meters traveled before stopping (take $g = 9.8\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 17,
    "explanation": "$a = \\frac{3}{5}g\\sin(30^\\circ) = 0.3(9.8) = 2.94\\,\\text{m/s}^2$. $s = \\frac{100}{2(2.94)} = \\frac{100}{5.88} \\approx 17.0\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A ring rolls up the same $30^\\circ$ incline with $v_0 = 10\\,\\text{m/s}$. What is the distance along the incline in meters traveled before stopping (take $g = 9.8\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 20.4,
    "explanation": "$a = \\frac{1}{2}g\\sin(30^\\circ) = 0.25(9.8) = 2.45\\,\\text{m/s}^2$. $s = \\frac{100}{2(2.45)} = \\frac{100}{4.9} \\approx 20.41 \\approx 20.4\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolls down an incline of angle $37^\\circ$ without slipping (take $\\sin 37^\\circ = 0.6, \\cos 37^\\circ = 0.8$, $g = 10\\,\\text{m/s}^2$). What is its linear acceleration in $\\text{m/s}^2$ (round to two decimal places)?",
    "correctAnswer": 4.29,
    "explanation": "$a = \\frac{5}{7}g\\sin(37^\\circ) = \\frac{5}{7}(10)(0.6) = \\frac{30}{7} \\approx 4.2857 \\approx 4.29\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "For the sphere on the $37^\\circ$ incline in the previous problem, what is the minimum value of static friction coefficient $\\mu_s$ to prevent slipping (round to two decimal places)?",
    "correctAnswer": 0.21,
    "explanation": "$\\mu_{\\min} = \\frac{2}{7}\\tan(37^\\circ) = \\frac{2}{7}\\left(\\frac{0.6}{0.8}\\right) = \\frac{2}{7}\\left(\\frac{3}{4}\\right) = \\frac{3}{14} \\approx 0.214 \\approx 0.21$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform disc of mass $1\\,\\text{kg}$ rolls down an incline of angle $30^\\circ$. What is the linear acceleration in $\\text{m/s}^2$ (take $g = 9.81\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 3.27,
    "explanation": "$a = \\frac{2}{3}g\\sin(30^\\circ) = \\frac{1}{3}(9.81) = 3.27\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere rolls from rest down an incline of height $h = 2.8\\,\\text{m}$. What is its linear speed in $\\text{m/s}$ at the bottom (take $g = 9.8\\,\\text{m/s}^2$)?",
    "correctAnswer": 6.26,
    "explanation": "$v = \\sqrt{\\frac{10gh}{7}} = \\sqrt{\\frac{10(9.8)(2.8)}{7}} = \\sqrt{10(9.8)(0.4)} = \\sqrt{39.2} \\approx 6.26\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A cylinder of mass $m$ rolls down an incline of angle $\\theta$. What is the ratio of the friction force to the normal force if it rolls without slipping with $\\theta = 45^\\circ$?",
    "correctAnswer": 0.33,
    "explanation": "$\\frac{f}{N} = \\frac{\\frac{1}{3}mg\\sin(45^\\circ)}{mg\\cos(45^\\circ)} = \\frac{1}{3}\\tan(45^\\circ) = \\frac{1}{3} \\approx 0.33$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A disc of mass $3\\,\\text{kg}$ rolls down an incline of length $6\\,\\text{m}$ and inclination $30^\\circ$. What is the time in seconds taken to reach the bottom (take $g = 10\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 1.9,
    "explanation": "Acceleration is $a = \\frac{2}{3}(10)(0.5) = \\frac{10}{3} \\approx 3.333\\,\\text{m/s}^2$. Time is $t = \\sqrt{\\frac{2s}{a}} = \\sqrt{\\frac{2(6)}{10/3}} = \\sqrt{\\frac{36}{10}} = \\sqrt{3.6} \\approx 1.897 \\approx 1.9\\,\\text{s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A solid sphere of mass $2\\,\\text{kg}$ rolls on an incline of angle $30^\\circ$. What is the friction force in newtons (take $g = 9.8\\,\\text{m/s}^2$)? Round to two decimal places.",
    "correctAnswer": 2.8,
    "explanation": "$f = \\frac{2}{7}mg\\sin(30^\\circ) = \\frac{2}{7}(2)(9.8)(0.5) = \\frac{2(9.8)}{7} = 2(1.4) = 2.8\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "An Atwood machine has two hanging masses of $2\\,\\text{kg}$ each. When an extra mass of $1\\,\\text{kg}$ is added to one side, the system accelerates. The pulley has mass $M_p = 2\\,\\text{kg}$ (disc). What is the acceleration in $\\text{m/s}^2$ (take $g = 10\\,\\text{m/s}^2$)? Round to one decimal place.",
    "correctAnswer": 1.7,
    "explanation": "$a = \\frac{(3 - 2)(10)}{3 + 2 + 1} = \\frac{10}{6} \\approx 1.67 \\approx 1.7\\,\\text{m/s}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  },
  {
    "type": "NUMERICAL",
    "question": "A uniform spherical shell of mass $6\\,\\text{kg}$ rolls down an incline of angle $30^\\circ$. What is the friction force in newtons (take $g = 10\\,\\text{m/s}^2$)?",
    "correctAnswer": 12,
    "explanation": "$f = \\frac{2}{5}mg\\sin(30^\\circ) = \\frac{2}{5}(6)(10)(0.5) = \\frac{2}{5}(30) = 12\\,\\text{N}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Moment of inertia",
    "chapter": "Rotational Motion",
    "subject": "Physics",
    "options": []
  }
];
