module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The relative velocity of body $A$ with respect to body $B$ is given by $\\vec{v}_{AB} = \\vec{v}_A - \\vec{v}_B$.\nReason (R): The relative position of $A$ with respect to $B$ is $\\vec{r}_{AB} = \\vec{r}_A - \\vec{r}_B$, and differentiating with respect to time gives $\\frac{d\\vec{r}_{AB}}{dt} = \\frac{d\\vec{r}_A}{dt} - \\frac{d\\vec{r}_B}{dt}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By vector definition of position in a reference frame, $\\vec{r}_A = \\vec{r}_B + \\vec{r}_{AB} \\implies \\vec{r}_{AB} = \\vec{r}_A - \\vec{r}_B$. Differentiating with respect to time yields $\\vec{v}_{AB} = \\vec{v}_A - \\vec{v}_B$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): To cross a river in the shortest possible time, a swimmer must always head perpendicular to the river flow direction.\nReason (R): The component of velocity perpendicular to the river bank is maximum ($v_{swimmer}$) when the swimmer heads strictly across the current.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Time to cross is $t = \\frac{d}{v_{b/r}\\cos\\theta}$, where $\\theta$ is the angle with the normal to the banks. To minimize $t$, $\\cos\\theta$ must be maximum, which occurs at $\\theta = 0^\\circ$ (perpendicular to bank). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A boat can cross a river along the shortest path (zero drift) only if the boat's speed in still water is strictly greater than the river flow speed.\nReason (R): Zero drift requires the horizontal component of the boat's velocity to exactly cancel river velocity: $v_{boat}\\sin\\theta = v_{river}$, requiring $\\sin\\theta = \\frac{v_{river}}{v_{boat}} \\le 1$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\sin\\theta \\le 1$, the condition $\\sin\\theta = \\frac{v_{river}}{v_{boat}}$ can only be satisfied if $v_{boat} \\ge v_{river}$. If $v_{boat} < v_{river}$, zero drift is physically impossible. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If rain is falling vertically downwards, a man running horizontally must tilt his umbrella forward at an angle $\\theta = \\tan^{-1}\\left(\\frac{v_m}{v_r}\\right)$ with the vertical.\nReason (R): The relative velocity of rain with respect to the running man is $\\vec{v}_{rm} = \\vec{v}_r - \\vec{v}_m = -v_r\\hat{j} - v_m\\hat{i}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\vec{v}_{rm} = -v_m\\hat{i} - v_r\\hat{j}$, the rain appears to come from a forward-tilted direction making angle $\\tan\\theta = \\frac{v_m}{v_r}$ with the vertical. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two cars moving in the same direction on a straight road with speeds $v_1$ and $v_2$ ($v_1 > v_2$) have a relative speed equal to $v_1 - v_2$.\nReason (R): When two vectors are parallel and in the same direction, the magnitude of their vector difference is the difference of their magnitudes.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{v}_{12} = v_1\\hat{i} - v_2\\hat{i} = (v_1 - v_2)\\hat{i}$, so the relative speed is $|\\vec{v}_{12}| = v_1 - v_2$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two trains moving towards each other with speeds $u_1$ and $u_2$ collide after time $t = \\frac{d}{u_1 + u_2}$, where $d$ is their initial separation.\nReason (R): The relative speed of approach between two bodies moving directly towards each other is the sum of their individual speeds ($u_1 + u_2$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Relative velocity is $\\vec{v}_{rel} = u_1\\hat{i} - (-u_2\\hat{i}) = (u_1 + u_2)\\hat{i}$. The relative distance to cover is $d$, giving $t = \\frac{d}{u_1 + u_2}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The closest distance of approach between two particles moving with constant velocities $\\vec{v}_1$ and $\\vec{v}_2$ is zero if and only if they collide.\nReason (R): Collision occurs when the relative position vector and relative velocity vector are antiparallel, meaning the line of relative motion passes directly through the other particle.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "A distance of approach of zero implies identical positions at some instant, which is the definition of a collision. In relative coordinates, the relative velocity vector points directly along the line of initial separation. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In the frame of reference of a freely falling elevator, an object released from rest inside the elevator remains at rest relative to the elevator.\nReason (R): Both the elevator and the released object experience identical gravitational acceleration $g$ downwards, making their relative acceleration $\\vec{a}_{rel} = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{a}_{rel} = \\vec{g} - \\vec{g} = 0$. Since initial relative velocity is zero, the object experiences weightlessness and floats stationary relative to the elevator. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The relative acceleration of two projectiles launched simultaneously under gravity in the same region is always zero.\nReason (R): Both projectiles experience the exact same acceleration due to gravity, $\\vec{a}_1 = \\vec{g}$ and $\\vec{a}_2 = \\vec{g}$, so $\\vec{a}_{rel} = \\vec{a}_1 - \\vec{a}_2 = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{a}_{rel} = 0$, the motion of one projectile relative to the other is always a straight line with constant relative velocity $\\vec{v}_{rel} = \\vec{u}_1 - \\vec{u}_2$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The trajectory of one projectile as observed from another projectile launched at the same time is always a straight line.\nReason (R): The relative acceleration between any two freely flying projectiles under gravity is zero, so the relative velocity remains constant.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "With $\\vec{a}_{rel} = 0$, the relative position vector evolves as $\\vec{r}_{rel}(t) = \\vec{r}_{0,rel} + \\vec{v}_{rel}t$, which represents a straight line. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When a man walks at speed $v$ in vertically falling rain, the rain hits him at angle $\\theta_1$. If he doubles his speed to $2v$, the angle becomes $\\theta_2$ where $\\tan\\theta_2 = 2\\tan\\theta_1$.\nReason (R): The tangent of the angle with the vertical is given by $\\tan\\theta = \\frac{v_{man}}{v_{rain}}$, which is directly proportional to the man's speed.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\tan\\theta_1 = \\frac{v}{v_r}$ and $\\tan\\theta_2 = \\frac{2v}{v_r} = 2\\tan\\theta_1$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): An airplane flying against a headwind takes longer to complete a round trip between two cities than on a completely calm day.\nReason (R): The time for a round trip is $t = \\frac{d}{v - w} + \\frac{d}{v + w} = \\frac{2vd}{v^2 - w^2} = \\frac{2d/v}{1 - w^2/v^2}$, which is strictly greater than $\\frac{2d}{v}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the denominator $1 - w^2/v^2 < 1$, the time taken in the presence of wind is always greater than the calm-air round-trip time $\\frac{2d}{v}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If a boat's speed in still water $v_b$ is less than the river flow speed $v_r$, the boat cannot reach a point directly opposite on the other bank.\nReason (R): To achieve zero drift, the condition $\\sin\\theta = \\frac{v_r}{v_b}$ requires $|\\sin\\theta| \\le 1$, which is impossible when $v_b < v_r$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Zero drift requires $\\sin\\theta = v_r / v_b > 1$, which has no real solution. Thus the boat inevitably drifts downstream. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The minimum drift of a boat crossing a river when its speed in still water $v_b$ is less than river flow speed $v_r$ occurs when $\\sin\\theta = \\frac{v_b}{v_r}$.\nReason (R): Differentiating the drift expression $x = \\frac{d(v_r - v_b\\sin\\theta)}{v_b\\cos\\theta}$ with respect to $\\theta$ and setting the derivative to zero gives $\\sin\\theta = \\frac{v_b}{v_r}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Minimizing drift $x(\\theta)$ yields $\\frac{dx}{d\\theta} = 0 \\implies \\sin\\theta = \\frac{v_b}{v_r}$, where $\\theta$ is the angle upstream from the normal. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The relative velocity of two photons moving in opposite directions in vacuum is $2c$ in classical Newtonian kinematics.\nReason (R): In classical Galilean relativity, relative velocity for bodies moving opposite is $v_{rel} = v_1 - (-v_2) = v_1 + v_2$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In classical Newtonian kinematics, Galilean addition gives $v_{rel} = c + c = 2c$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A bird flying due north with speed $v$ in a wind blowing due east with speed $v$ has a ground velocity of $\\sqrt{2}v$ in the North-East direction.\nReason (R): The ground velocity is the vector sum of the bird's velocity relative to air and the wind velocity: $\\vec{v}_{ground} = v\\hat{j} + v\\hat{i}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{v}_{ground} = v\\hat{i} + v\\hat{j}$. Magnitude is $|\\vec{v}| = \\sqrt{v^2 + v^2} = \\sqrt{2}v$ and direction is $\\tan\\theta = 1 \\implies 45^\\circ$ East of North (North-East). (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If two bodies move with velocities $\\vec{v}_1$ and $\\vec{v}_2$ at an angle $\\theta$ to each other, their relative speed is $v_{rel} = \\sqrt{v_1^2 + v_2^2 - 2v_1 v_2\\cos\\theta}$.\nReason (R): The magnitude of the vector difference $\\vec{v}_{12} = \\vec{v}_1 - \\vec{v}_2$ is given by the law of cosines for vector subtraction.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By vector algebra, $|\\vec{v}_1 - \\vec{v}_2|^2 = v_1^2 + v_2^2 - 2v_1 v_2\\cos\\theta$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When a person runs faster in vertically falling rain, the rain appears to fall slower.\nReason (R): The magnitude of the relative velocity of rain is $|\\vec{v}_{rm}| = \\sqrt{v_r^2 + v_m^2}$, which increases as the man's speed $v_m$ increases.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: because $|\\vec{v}_{rm}| = \\sqrt{v_r^2 + v_m^2}$, running faster increases the relative speed of rain, making it hit faster and harder. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The relative velocity between two particles moving at speed $v$ in opposite directions along a straight line is zero.\nReason (R): Relative velocity between two objects moving in opposite directions is the sum of their individual speeds, $v - (-v) = 2v$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: the relative velocity is $2v$, not zero. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A passenger in a train moving at constant velocity throws a ball vertically upwards. The ball returns to the passenger's hand.\nReason (R): The ball retains the constant horizontal velocity of the train due to inertia, covering the same horizontal distance as the passenger during its flight.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Both the passenger and the ball maintain the same constant horizontal velocity $v_x$, so the relative horizontal displacement between them remains zero. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two particles moving with constant non-zero velocities in a plane always collide eventually.\nReason (R): Collision requires their relative velocity vector to be precisely collinear and opposite to their initial relative position vector.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: two particles will collide only under the very specific condition that the relative velocity points directly along their separation line. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): To catch a bus that has just started moving with constant acceleration, a person running at constant speed must have a speed greater than or equal to $\\sqrt{2as_0}$, where $s_0$ is the initial separation.\nReason (R): The quadratic equation for time of meeting $s_0 + \\frac{1}{2}at^2 = vt$ has real roots only if the discriminant $v^2 - 2as_0 \\ge 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Rewriting $\\frac{1}{2}at^2 - vt + s_0 = 0$, the condition for real time $t$ is $D = v^2 - 4(a/2)(s_0) = v^2 - 2as_0 \\ge 0 \\implies v \\ge \\sqrt{2as_0}$. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A swimmer crosses a river along the path of minimum drift in time $t$. If the river speed increases, the minimum drift increases.\nReason (R): Minimum drift when $v_b < v_r$ is $x_{min} = d\\sqrt{\\frac{v_r^2}{v_b^2} - 1}$, which increases monotonically with $v_r$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "As $v_r$ increases, the ratio $v_r/v_b$ increases, thereby increasing $x_{min} = d\\sqrt{(v_r/v_b)^2 - 1}$. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The time taken by a boat to travel a distance $d$ downstream and return upstream in a river is greater than the time taken to travel $2d$ in still water.\nReason (R): Downstream time is $\\frac{d}{v+u}$ and upstream time is $\\frac{d}{v-u}$, giving total time $\\frac{2vd}{v^2-u^2} = \\frac{2d/v}{1 - u^2/v^2} > \\frac{2d}{v}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the delay incurred while travelling upstream against the current exceeds the time saved while travelling downstream, the total time is always greater. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A person in an open elevator accelerating upwards with acceleration $a$ drops a coin. The acceleration of the coin relative to the elevator is $g + a$ downwards.\nReason (R): The acceleration of the coin relative to the elevator is $\\vec{a}_{coin} - \\vec{a}_{elevator} = (-g\\hat{j}) - (+a\\hat{j}) = -(g+a)\\hat{j}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Taking upward as positive, $a_{elevator} = +a$ and $a_{coin} = -g$. Relative acceleration is $a_{rel} = -g - a = -(g+a)$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): For two objects moving with constant velocities, the rate of change of distance between them is zero at the instant of closest approach.\nReason (R): At the moment of minimum distance, the relative velocity vector is perpendicular to the relative position vector: $\\vec{r}_{rel} \\cdot \\vec{v}_{rel} = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $r_{rel}^2 = \\vec{r}_{rel} \\cdot \\vec{r}_{rel}$, differentiating gives $2r\\frac{dr}{dt} = 2\\vec{r}_{rel} \\cdot \\vec{v}_{rel}$. When distance is minimum, $\\frac{dr}{dt} = 0$, so $\\vec{r}_{rel} \\cdot \\vec{v}_{rel} = 0$. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A train of length $200\\text{ m}$ is moving at $72\\text{ km/h}$. Another train of length $300\\text{ m}$ is moving at $36\\text{ km/h}$ in the same direction on a parallel track. The time taken by the first train to completely cross the second train is:",
    "options": [
      "$25\\text{ s}$",
      "$50\\text{ s}$",
      "$10\\text{ s}$",
      "$100\\text{ s}$"
    ],
    "correctAnswer": 1,
    "explanation": "Convert speeds: $v_1 = 72 \\times \\frac{5}{18} = 20\\text{ m/s}$, $v_2 = 36 \\times \\frac{5}{18} = 10\\text{ m/s}$. Relative speed is $v_{rel} = 20 - 10 = 10\\text{ m/s}$. Total distance to clear is $L_1 + L_2 = 200 + 300 = 500\\text{ m}$. Time taken is $t = \\frac{500}{10} = 50\\text{ s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Rain is falling vertically downwards with a speed of $4\\text{ m/s}$. A man walks horizontally at a speed of $3\\text{ m/s}$. The angle at which he should hold his umbrella with the vertical to protect himself from the rain is:",
    "options": [
      "$\\tan^{-1}(3/4)$ forward",
      "$\\tan^{-1}(4/3)$ forward",
      "$\\tan^{-1}(3/4)$ backward",
      "$\\tan^{-1}(4/3)$ backward"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{v}_r = -4\\hat{j}$, $\\vec{v}_m = 3\\hat{i}$. Relative velocity of rain is $\\vec{v}_{rm} = \\vec{v}_r - \\vec{v}_m = -3\\hat{i} - 4\\hat{j}$. The angle with the vertical is $\\tan\\theta = \\frac{|v_{rm,x}|}{|v_{rm,y}|} = \\frac{3}{4} \\implies \\theta = \\tan^{-1}(3/4)$ tilted forward in the direction of motion.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A river is flowing from west to east at a speed of $5\\text{ m/min}$. A man on the south bank of the river, capable of swimming at $10\\text{ m/min}$ in still water, wants to swim across the river in the shortest time. He should swim in a direction:",
    "options": [
      "Due North",
      "$30^\\circ$ East of North",
      "$30^\\circ$ West of North",
      "$60^\\circ$ East of North"
    ],
    "correctAnswer": 0,
    "explanation": "Shortest time across a river is achieved when the swimmer directs his velocity purely perpendicular to the bank, i.e., due North ($\\theta = 0^\\circ$ with normal). Time taken is $t_{min} = \\frac{d}{v_{b/r}}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A boat crosses a river of width $1\\text{ km}$ along the shortest path in $15\\text{ minutes}$. If the speed of the boat in still water is $5\\text{ km/h}$, the velocity of the river stream is:",
    "options": [
      "$3\\text{ km/h}$",
      "$4\\text{ km/h}$",
      "$2\\text{ km/h}$",
      "$2.5\\text{ km/h}$"
    ],
    "correctAnswer": 0,
    "explanation": "Along shortest path, drift is zero, so net velocity is perpendicular to the bank: $v_{net} = \\frac{d}{t} = \\frac{1\\text{ km}}{15/60\\text{ h}} = 4\\text{ km/h}$. Since $v_{net} = \\sqrt{v_b^2 - v_r^2}$, we have $4 = \\sqrt{5^2 - v_r^2} \\implies 16 = 25 - v_r^2 \\implies v_r^2 = 9 \\implies v_r = 3\\text{ km/h}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Ship $A$ is travelling due east at $10\\text{ km/h}$ and ship $B$ is heading due north at $10\\text{ km/h}$. What is the velocity of ship $A$ relative to ship $B$?",
    "options": [
      "$10\\sqrt{2}\\text{ km/h}$ towards South-East",
      "$10\\sqrt{2}\\text{ km/h}$ towards North-East",
      "$10\\sqrt{2}\\text{ km/h}$ towards South-West",
      "$10\\text{ km/h}$ towards South-East"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{v}_A = 10\\hat{i}$, $\\vec{v}_B = 10\\hat{j}$. Relative velocity $\\vec{v}_{AB} = \\vec{v}_A - \\vec{v}_B = 10\\hat{i} - 10\\hat{j}$. Magnitude is $|\\vec{v}_{AB}| = \\sqrt{10^2 + (-10)^2} = 10\\sqrt{2}\\text{ km/h}$. Direction is $+x$ (East) and $-y$ (South), which is South-East.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A man running at $6\\text{ km/h}$ feels rain falling vertically on him. When he increases his speed to $12\\text{ km/h}$, the rain appears to make an angle of $45^\\circ$ with the vertical. The true velocity of the rain is:",
    "options": [
      "$6\\sqrt{2}\\text{ km/h}$ at $45^\\circ$ with vertical",
      "$6\\text{ km/h}$ vertically downwards",
      "$12\\text{ km/h}$ vertically downwards",
      "$6\\sqrt{3}\\text{ km/h}$ at $30^\\circ$ with vertical"
    ],
    "correctAnswer": 0,
    "explanation": "Let $\\vec{v}_r = v_x\\hat{i} - v_y\\hat{j}$. When $\\vec{v}_m = 6\\hat{i}$, $\\vec{v}_{rm} = (v_x - 6)\\hat{i} - v_y\\hat{j}$ is vertical $\\implies v_x - 6 = 0 \\implies v_x = 6\\text{ km/h}$. When $\\vec{v}_m = 12\\hat{i}$, $\\vec{v}_{rm} = (6 - 12)\\hat{i} - v_y\\hat{j} = -6\\hat{i} - v_y\\hat{j}$. It makes $45^\\circ$ with vertical $\\implies \\tan 45^\\circ = \\frac{|-6|}{v_y} = 1 \\implies v_y = 6\\text{ km/h}$. Thus $\\vec{v}_r = 6\\hat{i} - 6\\hat{j}$, $|\\vec{v}_r| = \\sqrt{6^2 + 6^2} = 6\\sqrt{2}\\text{ km/h}$ at $45^\\circ$ with vertical.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two particles $A$ and $B$ are separated by $100\\text{ m}$. Particle $A$ moves towards $B$ at $10\\text{ m/s}$, while $B$ moves away perpendicular to the initial line connecting them at $10\\text{ m/s}$. The closest distance between them is:",
    "options": [
      "$50\\sqrt{2}\\text{ m}$",
      "$50\\text{ m}$",
      "$100\\text{ m}$",
      "$25\\sqrt{2}\\text{ m}$"
    ],
    "correctAnswer": 0,
    "explanation": "Let $A$ be at origin $(0,0)$ and $B$ at $(100, 0)$. $\\vec{v}_A = 10\\hat{i}$, $\\vec{v}_B = 10\\hat{j}$. Relative velocity $\\vec{v}_{BA} = \\vec{v}_B - \\vec{v}_A = -10\\hat{i} + 10\\hat{j}$. Relative speed is $10\\sqrt{2}\\text{ m/s}$. The angle made by $\\vec{v}_{BA}$ with the $x$-axis is $135^\\circ$. The perpendicular distance from origin to the relative trajectory line is $d_{min} = 100\\sin 45^\\circ = \\frac{100}{\\sqrt{2}} = 50\\sqrt{2}\\text{ m}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two trains of length $L_1 = 100\\text{ m}$ and $L_2 = 150\\text{ m}$ are travelling towards each other on parallel tracks at speeds of $15\\text{ m/s}$ and $10\\text{ m/s}$ respectively. Find the time $t$ (in seconds) taken by them to completely cross each other.",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "Relative speed is $v_{rel} = 15 + 10 = 25\\text{ m/s}$. Total distance is $L_1 + L_2 = 250\\text{ m}$. Time $t = \\frac{250}{25} = 10\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two trains of length $L_1 = 200\\text{ m}$ and $L_2 = 300\\text{ m}$ are travelling towards each other on parallel tracks at speeds of $15\\text{ m/s}$ and $10\\text{ m/s}$ respectively. Find the time $t$ (in seconds) taken by them to completely cross each other.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "Relative speed is $v_{rel} = 15 + 10 = 25\\text{ m/s}$. Total distance is $L_1 + L_2 = 500\\text{ m}$. Time $t = \\frac{500}{25} = 20\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two trains of length $L_1 = 300\\text{ m}$ and $L_2 = 450\\text{ m}$ are travelling towards each other on parallel tracks at speeds of $15\\text{ m/s}$ and $10\\text{ m/s}$ respectively. Find the time $t$ (in seconds) taken by them to completely cross each other.",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "Relative speed is $v_{rel} = 15 + 10 = 25\\text{ m/s}$. Total distance is $L_1 + L_2 = 750\\text{ m}$. Time $t = \\frac{750}{25} = 30\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two trains of length $L_1 = 400\\text{ m}$ and $L_2 = 600\\text{ m}$ are travelling towards each other on parallel tracks at speeds of $15\\text{ m/s}$ and $10\\text{ m/s}$ respectively. Find the time $t$ (in seconds) taken by them to completely cross each other.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "Relative speed is $v_{rel} = 15 + 10 = 25\\text{ m/s}$. Total distance is $L_1 + L_2 = 1000\\text{ m}$. Time $t = \\frac{1000}{25} = 40\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two trains of length $L_1 = 500\\text{ m}$ and $L_2 = 750\\text{ m}$ are travelling towards each other on parallel tracks at speeds of $15\\text{ m/s}$ and $10\\text{ m/s}$ respectively. Find the time $t$ (in seconds) taken by them to completely cross each other.",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "Relative speed is $v_{rel} = 15 + 10 = 25\\text{ m/s}$. Total distance is $L_1 + L_2 = 1250\\text{ m}$. Time $t = \\frac{1250}{25} = 50\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A swimmer can swim with a speed of $10\\text{ m/s}$ in still water. If the width of the river is $d = 200\\text{ m}$ and the river flows at $6\\text{ m/s}$, calculate the minimum time $t$ (in seconds) required for the swimmer to cross the river.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "To minimize crossing time, the swimmer heads perpendicular to the flow: $t_{min} = \\frac{d}{v_b} = \\frac{200}{10} = 20\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A swimmer can swim with a speed of $10\\text{ m/s}$ in still water. If the width of the river is $d = 400\\text{ m}$ and the river flows at $6\\text{ m/s}$, calculate the minimum time $t$ (in seconds) required for the swimmer to cross the river.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "To minimize crossing time, the swimmer heads perpendicular to the flow: $t_{min} = \\frac{d}{v_b} = \\frac{400}{10} = 40\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A swimmer can swim with a speed of $10\\text{ m/s}$ in still water. If the width of the river is $d = 600\\text{ m}$ and the river flows at $6\\text{ m/s}$, calculate the minimum time $t$ (in seconds) required for the swimmer to cross the river.",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "To minimize crossing time, the swimmer heads perpendicular to the flow: $t_{min} = \\frac{d}{v_b} = \\frac{600}{10} = 60\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A swimmer can swim with a speed of $10\\text{ m/s}$ in still water. If the width of the river is $d = 800\\text{ m}$ and the river flows at $6\\text{ m/s}$, calculate the minimum time $t$ (in seconds) required for the swimmer to cross the river.",
    "options": [],
    "correctAnswer": 80,
    "numericalAnswer": 80,
    "explanation": "To minimize crossing time, the swimmer heads perpendicular to the flow: $t_{min} = \\frac{d}{v_b} = \\frac{800}{10} = 80\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A swimmer can swim with a speed of $10\\text{ m/s}$ in still water. If the width of the river is $d = 1000\\text{ m}$ and the river flows at $6\\text{ m/s}$, calculate the minimum time $t$ (in seconds) required for the swimmer to cross the river.",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "To minimize crossing time, the swimmer heads perpendicular to the flow: $t_{min} = \\frac{d}{v_b} = \\frac{1000}{10} = 100\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A boat crosses a river of width $d = 100\\text{ m}$ in the shortest possible time. The speed of the boat in still water is $5\\text{ m/s}$ and the river flow velocity is $3\\text{ m/s}$. Find the downstream drift $x$ (in meters) of the boat when it reaches the opposite bank.",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "Time taken is $t = \\frac{d}{v_b} = \\frac{100}{5} = 20\\text{ s}$. Drift is $x = v_r t = 3 \\times 20 = 60\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A boat crosses a river of width $d = 200\\text{ m}$ in the shortest possible time. The speed of the boat in still water is $5\\text{ m/s}$ and the river flow velocity is $3\\text{ m/s}$. Find the downstream drift $x$ (in meters) of the boat when it reaches the opposite bank.",
    "options": [],
    "correctAnswer": 120,
    "numericalAnswer": 120,
    "explanation": "Time taken is $t = \\frac{d}{v_b} = \\frac{200}{5} = 40\\text{ s}$. Drift is $x = v_r t = 3 \\times 40 = 120\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A boat crosses a river of width $d = 300\\text{ m}$ in the shortest possible time. The speed of the boat in still water is $5\\text{ m/s}$ and the river flow velocity is $3\\text{ m/s}$. Find the downstream drift $x$ (in meters) of the boat when it reaches the opposite bank.",
    "options": [],
    "correctAnswer": 180,
    "numericalAnswer": 180,
    "explanation": "Time taken is $t = \\frac{d}{v_b} = \\frac{300}{5} = 60\\text{ s}$. Drift is $x = v_r t = 3 \\times 60 = 180\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A boat crosses a river of width $d = 400\\text{ m}$ in the shortest possible time. The speed of the boat in still water is $5\\text{ m/s}$ and the river flow velocity is $3\\text{ m/s}$. Find the downstream drift $x$ (in meters) of the boat when it reaches the opposite bank.",
    "options": [],
    "correctAnswer": 240,
    "numericalAnswer": 240,
    "explanation": "Time taken is $t = \\frac{d}{v_b} = \\frac{400}{5} = 80\\text{ s}$. Drift is $x = v_r t = 3 \\times 80 = 240\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A boat crosses a river of width $d = 500\\text{ m}$ in the shortest possible time. The speed of the boat in still water is $5\\text{ m/s}$ and the river flow velocity is $3\\text{ m/s}$. Find the downstream drift $x$ (in meters) of the boat when it reaches the opposite bank.",
    "options": [],
    "correctAnswer": 300,
    "numericalAnswer": 300,
    "explanation": "Time taken is $t = \\frac{d}{v_b} = \\frac{500}{5} = 100\\text{ s}$. Drift is $x = v_r t = 3 \\times 100 = 300\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two cars $A$ and $B$ are travelling in the same direction on a straight highway. Car $A$ moves at $25\\text{ m/s}$ and car $B$ moves at $15\\text{ m/s}$. If car $A$ is initially $d = 200\\text{ m}$ behind car $B$, find the time $t$ (in seconds) it takes for car $A$ to overtake car $B$.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "Relative velocity is $v_{rel} = 25 - 15 = 10\\text{ m/s}$. Time taken is $t = \\frac{d}{v_{rel}} = \\frac{200}{10} = 20\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two cars $A$ and $B$ are travelling in the same direction on a straight highway. Car $A$ moves at $25\\text{ m/s}$ and car $B$ moves at $15\\text{ m/s}$. If car $A$ is initially $d = 400\\text{ m}$ behind car $B$, find the time $t$ (in seconds) it takes for car $A$ to overtake car $B$.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "Relative velocity is $v_{rel} = 25 - 15 = 10\\text{ m/s}$. Time taken is $t = \\frac{d}{v_{rel}} = \\frac{400}{10} = 40\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two cars $A$ and $B$ are travelling in the same direction on a straight highway. Car $A$ moves at $25\\text{ m/s}$ and car $B$ moves at $15\\text{ m/s}$. If car $A$ is initially $d = 600\\text{ m}$ behind car $B$, find the time $t$ (in seconds) it takes for car $A$ to overtake car $B$.",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "Relative velocity is $v_{rel} = 25 - 15 = 10\\text{ m/s}$. Time taken is $t = \\frac{d}{v_{rel}} = \\frac{600}{10} = 60\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two cars $A$ and $B$ are travelling in the same direction on a straight highway. Car $A$ moves at $25\\text{ m/s}$ and car $B$ moves at $15\\text{ m/s}$. If car $A$ is initially $d = 800\\text{ m}$ behind car $B$, find the time $t$ (in seconds) it takes for car $A$ to overtake car $B$.",
    "options": [],
    "correctAnswer": 80,
    "numericalAnswer": 80,
    "explanation": "Relative velocity is $v_{rel} = 25 - 15 = 10\\text{ m/s}$. Time taken is $t = \\frac{d}{v_{rel}} = \\frac{800}{10} = 80\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two cars $A$ and $B$ are travelling in the same direction on a straight highway. Car $A$ moves at $25\\text{ m/s}$ and car $B$ moves at $15\\text{ m/s}$. If car $A$ is initially $d = 1000\\text{ m}$ behind car $B$, find the time $t$ (in seconds) it takes for car $A$ to overtake car $B$.",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "Relative velocity is $v_{rel} = 25 - 15 = 10\\text{ m/s}$. Time taken is $t = \\frac{d}{v_{rel}} = \\frac{1000}{10} = 100\\text{ s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Relative velocity",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
