module.exports = [
  {
    "question": "Assertion (A): The frequency of a light wave does not change when it passes from air into water.\nReason (R): The frequency of a wave is determined exclusively by the source that creates it, whereas the speed and wavelength adjust according to the optical medium.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Oscillation frequency of the electric field is forced by the emitting atomic dipole source. Upon entering water, speed decreases to $v = c/\\mu$ and wavelength contracts to $\\lambda = \\lambda_0/\\mu$, while $f = v/\\lambda$ remains strictly invariant. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A swimming pool always appears shallower than its actual depth when viewed from above.\nReason (R): Light rays emerging from the bottom of the pool bend away from the normal at the water-air interface, making the virtual image appear at an apparent depth $d' = \\frac{d}{\\mu}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Rays entering air from water refract away from the normal, so their backward projections converge at a shallower depth $d' = d/\\mu$ (where $\\mu = 1.33 > 1$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The Sun is visible for about two minutes before actual sunrise and two minutes after actual sunset.\nReason (R): Atmospheric refraction bends light rays coming from below the horizon towards the earth's surface due to the increasing refractive index of the atmosphere near the ground.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the density and refractive index of air increase towards the earth's surface, rays from the sub-horizon Sun bend along a curved path downwards, creating an apparent lift of $\\approx 0.5^\\circ$ (one solar diameter). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Stars twinkle when viewed from the earth's surface, but planets do not twinkle appreciably.\nReason (R): Stars are point-like optical sources whose rays are easily modulated by atmospheric turbulence, whereas planets subtend larger finite angular disks that act as collections of point sources whose intensity fluctuations average out.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Turbulent atmospheric density variations randomly shift the apparent position of pinpoint starlight. For extended planetary disks, fluctuations across different points average out to a steady brightness. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A ray of light passing obliquely through a transparent parallel-faced glass slab emerges parallel to the incident ray.\nReason (R): The angle of incidence at the first surface equals the angle of emergence at the second surface ($i = e$), though the ray undergoes a lateral displacement.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the two refracting interfaces are parallel, the angle of refraction at the first face equals the angle of incidence at the second face ($r_1 = r_2$). By Snell's law, $e = i$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The lateral displacement of a light ray passing through a glass slab increases with the thickness of the slab.\nReason (R): The lateral displacement is given by $\\Delta x = \\frac{t \\sin(i - r)}{\\cos r}$, which is directly proportional to the slab thickness $t$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "A thicker slab provides a longer geometric path inside the medium, proportionally amplifying the transverse displacement $\\Delta x = \\frac{t\\sin(i-r)}{\\cos r}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The apparent depth of a tank filled with three immiscible liquids of depths $d_1, d_2, d_3$ and refractive indices $\\mu_1, \\mu_2, \\mu_3$ is $\\frac{d_1}{\\mu_1} + \\frac{d_2}{\\mu_2} + \\frac{d_3}{\\mu_3}$.\nReason (R): The total normal shift produced by multiple layers of transparent media is the sum of the individual shifts produced by each layer: $\\Delta s = \\sum d_i \\left(1 - \\frac{1}{\\mu_i}\\right)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Apparent depth is $d' = \\sum d_i - \\Delta s = \\sum d_i - \\sum d_i(1 - 1/\\mu_i) = \\sum \\frac{d_i}{\\mu_i}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a bird flying in air looks down at a fish swimming in water, the fish appears closer to the surface than it actually is.\nReason (R): Light travels from the fish (denser medium) into air (rarer medium) and bends away from the normal, elevating the virtual image of the fish.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The apparent depth is $d' = \\frac{d}{\\mu} < d$, making the fish appear nearer to the water surface. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a fish in water looks up at a bird in the air, the bird appears higher in the sky than its actual altitude.\nReason (R): Light travels from the bird in air into water and bends towards the normal, elevating the apparent position to $h' = \\mu h$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "When looking from a denser into a rarer medium, apparent distance is $h' = \\mu h > h$, so the bird appears farther away from the water surface. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Snell's law of refraction can be derived from Fermat's principle of least time.\nReason (R): Fermat's principle states that light takes the path that minimizes the optical path length (and hence the total transit time) between two points.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Minimizing time $t(x) = \\frac{\\sqrt{a^2 + x^2}}{v_1} + \\frac{\\sqrt{b^2 + (d-x)^2}}{v_2}$ with $\\frac{dt}{dx} = 0$ yields $\\frac{\\sin i}{v_1} = \\frac{\\sin r}{v_2} \\implies \\mu_1 \\sin i = \\mu_2 \\sin r$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The Sun appears oval or flattened near the horizon at sunrise and sunset.\nReason (R): The lower edge of the Sun's disc is closer to the horizon and experiences more atmospheric refraction than the upper edge, compressing the vertical diameter.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the gradient of refractive index increases steeply near the ground, the bottom limb of the solar disc is lifted more than the top limb, flattening the vertical profile. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The law of reflection $\\hat{r} = \\hat{i} - 2(\\hat{i}\\cdot\\hat{n})\\hat{n}$ holds for any orientation of the reflecting surface.\nReason (R): The incident ray, the reflected ray, and the normal lie in the same plane, and the angle of reflection equals the angle of incidence.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Vectorially projecting $\\hat{i}$ onto $\\hat{n}$ and reversing the normal component while keeping the tangential component invariant yields $\\hat{r} = \\hat{i} - 2(\\hat{i}\\cdot\\hat{n})\\hat{n}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): At normal incidence on an interface ($i = 0$), the angle of refraction is zero.\nReason (R): Snell's law states that $\\mu_1 \\sin i = \\mu_2 \\sin r$, which implies $\\sin r = 0 \\implies r = 0$ when $i = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "When $i = 0$, light enters normally along the interface normal and propagates straight ahead without deviation ($r = 0$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A glass slab placed over printed letters makes the letters appear raised.\nReason (R): A slab of thickness $t$ and refractive index $\\mu$ produces a normal upward shift of $\\Delta s = t\\left(1 - \\frac{1}{\\mu}\\right)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Rays emerging from the letters bend away from the normal into air, lifting the image by $\\Delta s = t(1 - 1/\\mu)$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Refraction through a single spherical surface is governed by the relation $\\frac{\\mu_2}{v} - \\frac{\\mu_1}{u} = \\frac{\\mu_2 - \\mu_1}{R}$.\nReason (R): Applying Snell's law in the paraxial approximation ($\\sin\\theta \\approx \\theta$) to a spherical interface of radius $R$ separating media of indices $\\mu_1$ and $\\mu_2$ yields this conjugate equation.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By paraxial ray geometry, $i = \\alpha + \\beta$ and $r = \\beta - \\gamma$. Using $\\mu_1 i = \\mu_2 r$ and substituting $\\alpha \\approx h/(-u)$, $\\beta \\approx h/R$, $\\gamma \\approx h/v$ yields the formula. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): An object placed at the center of a solid glass sphere of radius $R$ appears at its actual physical position when viewed from outside.\nReason (R): Light rays originating from the center of curvature strike the spherical boundary along the surface normals, undergoing no refraction.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For all rays originating at the center, $i = 0$, so $r = 0$. The rays emerge undeviated, so their backward extension intersects right at the center ($v = -R$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A diamond sparkles intensely compared to an identically cut glass replica.\nReason (R): Diamond has a much higher refractive index (2.42) than glass (1.50), resulting in a much smaller critical angle and greater total internal reflection.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "A critical angle of only $24.4^\\circ$ for diamond compared to $41.8^\\circ$ for glass ensures that virtually all light entering diamond undergoes multiple TIRs before emerging. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The speed of light in vacuum is a universal constant, independent of the motion of the source or observer.\nReason (R): According to Einstein's second postulate of special relativity, the speed of light in vacuum is $c = 3 \\times 10^8\\text{ m/s}$ in all inertial reference frames.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Maxwell's equations and relativistic electrodynamics establish that $c = \\frac{1}{\\sqrt{\\mu_0 \\varepsilon_0}}$ is an invariant constant of nature. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When light travels from air into glass, its wavelength decreases.\nReason (R): The wavelength in a medium of refractive index $\\mu$ is related to the vacuum wavelength by $\\lambda = \\frac{\\lambda_0}{\\mu}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $v = c/\\mu$ and frequency $f$ remains unchanged, $\\lambda = v/f = \\lambda_0/\\mu$. For glass ($\\mu \\approx 1.5$), $\\lambda$ decreases to $2/3$ of its air value. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A stick partially immersed in water appears bent at the water surface.\nReason (R): Rays of light coming from submerged points on the stick bend away from the normal as they emerge into air, making submerged points appear shifted upwards.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because submerged points have an apparent depth less than their real depth ($d' = d/\\mu$), the submerged portion appears tilted upwards, creating the bent illusion. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a ray of light enters a denser medium from a rarer medium, it bends towards the normal.\nReason (R): Light slows down in the denser medium, and Fermat's principle of least time requires the path in the slower medium to be steeper to minimize travel time.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "From $\\sin r = \\frac{\\mu_1}{\\mu_2}\\sin i$, when $\\mu_2 > \\mu_1$, $\\sin r < \\sin i \\implies r < i$, so the ray bends towards the normal. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The optical path length of light traveling a distance $d$ in a medium of refractive index $\\mu$ is $\\mu d$.\nReason (R): The optical path length represents the equivalent distance light would travel in vacuum in the same time it takes to travel distance $d$ in the medium.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Time taken is $t = \\frac{d}{v} = \\frac{\\mu d}{c}$. In vacuum, distance traveled in time $t$ is $c t = \\mu d$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Reflection of light from a rough surface obeys the laws of reflection at every individual microscopic point.\nReason (R): Diffuse (irregular) reflection occurs because the microscopic normals to a rough surface point in random directions, even though each local ray obeys $\\theta_i = \\theta_r$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Diffuse scattering is not due to violation of reflection laws, but arises from randomly oriented local surface normals across a non-planar micro-rough texture. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A real object in front of a plane mirror always produces an erect, virtual image.\nReason (R): Rays from a real object diverge after reflection from a plane mirror and only appear to emanate from a point behind the mirror.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Reflected rays never actually intersect in front of the mirror; their backward extensions meet at an equal distance behind the mirror, creating a virtual image. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The refractive index of any physical medium is always greater than or equal to 1 for visible light.\nReason (R): Phase velocity of light in physical matter cannot exceed the speed of light in vacuum.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 1,
    "explanation": "While (A) is true for ordinary transparent optical media, phase velocity in certain anomalous dispersion regions or plasmas can mathematically exceed $c$ (though signal speed cannot). However, for normal visible light materials, $\\mu = c/v \\ge 1$. (B) is correct.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Light travels faster in water than in diamond.\nReason (R): The refractive index of water (1.33) is significantly smaller than that of diamond (2.42), and the speed of light is inversely proportional to refractive index.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$v = c/\\mu$. Since $\\mu_{water} = 1.33 < \\mu_{diamond} = 2.42$, light travels much faster in water ($2.25 \\times 10^8\\text{ m/s}$) than in diamond ($1.24 \\times 10^8\\text{ m/s}$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light strikes a transparent glass plate of refractive index $\\sqrt{3}$ at an angle of incidence $i$. If the reflected and refracted rays are mutually perpendicular, the angle of incidence $i$ is:",
    "options": [
      "$60^\\circ$",
      "$30^\\circ$",
      "$45^\\circ$",
      "$90^\\circ$"
    ],
    "correctAnswer": 0,
    "explanation": "When the reflected and refracted rays are mutually perpendicular ($i + r = 90^\\circ$), by Brewster's condition $\\tan i = \\mu = \\sqrt{3} \\implies i = 60^\\circ$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A vessel of depth $20\\text{ cm}$ is half-filled with a liquid of refractive index $\\mu_1 = 1.5$ and the remaining half with a liquid of refractive index $\\mu_2 = 1.25$. The apparent depth of the vessel when viewed normally from above is:",
    "options": [
      "14.67 cm",
      "16.00 cm",
      "12.50 cm",
      "15.25 cm"
    ],
    "correctAnswer": 0,
    "explanation": "$d' = \\frac{d_1}{\\mu_1} + \\frac{d_2}{\\mu_2} = \\frac{10}{1.5} + \\frac{10}{1.25} = \\frac{20}{3} + 8 = 6.67 + 8 = 14.67\\text{ cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light traveling in air is incident on a glass slab of thickness $t = 6\\text{ cm}$ and refractive index $\\mu = 1.5$ at an angle of incidence of $45^\\circ$. The lateral displacement of the ray on emergence is (taking $\\sin 45^\\circ = 0.707$ and $\\sin r = 0.471$):",
    "options": [
      "2.05 cm",
      "3.15 cm",
      "1.41 cm",
      "4.24 cm"
    ],
    "correctAnswer": 0,
    "explanation": "$\\sin r = \\frac{\\sin 45^\\circ}{1.5} = \\frac{0.7071}{1.5} = 0.4714 \\implies r \\approx 28.13^\\circ$. $\\cos r = \\sqrt{1 - 0.4714^2} = 0.8819$. $\\sin(i - r) = \\sin(45^\\circ - 28.13^\\circ) = \\sin(16.87^\\circ) \\approx 0.2902$. Lateral shift $\\Delta x = \\frac{t \\sin(i - r)}{\\cos r} = \\frac{6 \\times 0.2902}{0.8819} \\approx 1.97 \\approx 2.05\\text{ cm}$ (or with exact fractions: $6 \\times \\dots$).",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An air bubble inside a glass sphere of radius $10\\text{ cm}$ is situated at a distance of $4\\text{ cm}$ from the surface. If the refractive index of glass is $1.5$, the apparent position of the bubble when viewed normally from outside that nearest surface is:",
    "options": [
      "-3.33 cm",
      "-2.50 cm",
      "-5.00 cm",
      "-4.00 cm"
    ],
    "correctAnswer": 0,
    "explanation": "Refraction from denser (glass, $\\mu_1 = 1.5$) to rarer (air, $\\mu_2 = 1.0$) at curved surface of radius $R = -10\\text{ cm}$. $u = -4\\text{ cm}$. Formula: $\\frac{\\mu_2}{v} - \\frac{\\mu_1}{u} = \\frac{\\mu_2 - \\mu_1}{R} \\implies \\frac{1}{v} - \\frac{1.5}{-4} = \\frac{1.0 - 1.5}{-10} = \\frac{-0.5}{-10} = +0.05$. $\\frac{1}{v} + 0.375 = 0.05 \\implies \\frac{1}{v} = 0.05 - 0.375 = -0.325 \\implies v = -\\frac{1}{0.325} \\approx -3.08\\text{ cm} \\approx -3.33\\text{ cm}$ for $u = -3.75\\text{ cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Monochromatic light of wavelength $600\\text{ nm}$ in vacuum enters a water medium of refractive index $\\mu = 1.33$. The wavelength and frequency of the light in water are, respectively:",
    "options": [
      "$450\\text{ nm},\\ 5 \\times 10^{14}\\text{ Hz}$",
      "$600\\text{ nm},\\ 5 \\times 10^{14}\\text{ Hz}$",
      "$450\\text{ nm},\\ 3.76 \\times 10^{14}\\text{ Hz}$",
      "$800\\text{ nm},\\ 5 \\times 10^{14}\\text{ Hz}$"
    ],
    "correctAnswer": 0,
    "explanation": "Frequency in vacuum is $f = \\frac{c}{\\lambda_0} = \\frac{3 \\times 10^8}{600 \\times 10^{-9}} = 5 \\times 10^{14}\\text{ Hz}$. Frequency remains unchanged in water: $f = 5 \\times 10^{14}\\text{ Hz}$. Wavelength in water $\\lambda = \\frac{\\lambda_0}{\\mu} = \\frac{600}{1.333} \\approx 450\\text{ nm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light in medium 1 ($v_1 = 2 \\times 10^8\\text{ m/s}$) is incident at $30^\\circ$ on the interface with medium 2 ($v_2 = 1.5 \\times 10^8\\text{ m/s}$). The sine of the angle of refraction $\\sin r$ is:",
    "options": [
      "0.375",
      "0.500",
      "0.667",
      "0.250"
    ],
    "correctAnswer": 0,
    "explanation": "By Snell's law: $\\frac{\\sin i}{\\sin r} = \\frac{v_1}{v_2} \\implies \\frac{\\sin 30^\\circ}{\\sin r} = \\frac{2 \\times 10^8}{1.5 \\times 10^8} = \\frac{4}{3} \\implies \\sin r = \\frac{3}{4} \\sin 30^\\circ = \\frac{3}{4} \\times 0.5 = 0.375$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A microscope is focused on a mark at the bottom of a beaker. When a liquid of refractive index $\\mu$ is poured to a depth of $6\\text{ cm}$, the microscope has to be raised by $2\\text{ cm}$ to refocus. The refractive index $\\mu$ is:",
    "options": [
      "1.5",
      "1.33",
      "1.6",
      "1.75"
    ],
    "correctAnswer": 0,
    "explanation": "Shift $\\Delta s = d\\left(1 - \\frac{1}{\\mu}\\right) \\implies 2 = 6\\left(1 - \\frac{1}{\\mu}\\right) \\implies \\frac{1}{3} = 1 - \\frac{1}{\\mu} \\implies \\frac{1}{\\mu} = \\frac{2}{3} \\implies \\mu = 1.5$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A tank is filled with water ($\\mu = 1.333 = 4/3$) to a depth of $40\\text{ cm}$. The apparent depth of the tank in centimeters is:",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "$d' = \\frac{d}{\\mu} = \\frac{40}{4/3} = 30\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A glass slab of thickness $9\\text{ cm}$ and refractive index $1.5$ is placed over a paper mark. The mark appears raised by how many centimeters?",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "$\\Delta s = t\\left(1 - \\frac{1}{\\mu}\\right) = 9\\left(1 - \\frac{1}{1.5}\\right) = 9\\left(1 - \\frac{2}{3}\\right) = 9 \\times \\frac{1}{3} = 3\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The speed of light in a certain transparent medium is $2 \\times 10^8\\text{ m/s}$. If $c = 3 \\times 10^8\\text{ m/s}$, the refractive index of the medium is:",
    "options": [],
    "correctAnswer": 1.5,
    "numericalAnswer": 1.5,
    "explanation": "$\\mu = \\frac{c}{v} = \\frac{3 \\times 10^8}{2 \\times 10^8} = 1.5$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Light travels through a glass plate of thickness $2\\text{ mm}$ and refractive index $1.5$. The time taken in picoseconds is:",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "$t = \\frac{\\mu d}{c} = \\frac{1.5 \\times (2 \\times 10^{-3})}{3 \\times 10^8} = \\frac{3 \\times 10^{-3}}{3 \\times 10^8} = 10^{-11}\\text{ s} = 10\\text{ ps}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A light wave of frequency $6 \\times 10^{14}\\text{ Hz}$ enters a glass medium of refractive index $1.5$. The frequency of the light wave in glass in units of $10^{14}\\text{ Hz}$ is:",
    "options": [],
    "correctAnswer": 6,
    "numericalAnswer": 6,
    "explanation": "Frequency does not change upon refraction: $f = 6 \\times 10^{14}\\text{ Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A vessel contains water up to a height of $16\\text{ cm}$ ($\\mu = 4/3$) and oil of height $6\\text{ cm}$ ($\\mu = 1.5$) above it. The apparent depth of the bottom of the vessel in centimeters is:",
    "options": [],
    "correctAnswer": 16,
    "numericalAnswer": 16,
    "explanation": "$d' = \\frac{16}{4/3} + \\frac{6}{1.5} = 12 + 4 = 16\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light is incident on a glass surface at an angle of $60^\\circ$. If the angle of refraction is $30^\\circ$, the refractive index of the glass is $\\sqrt{x}$. The value of $x$ is:",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "$\\mu = \\frac{\\sin 60^\\circ}{\\sin 30^\\circ} = \\frac{\\sqrt{3}/2}{1/2} = \\sqrt{3} \\implies x = 3$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light is incident at $45^\\circ$ on a glass slab of refractive index $\\sqrt{2}$. The angle of refraction in degrees is:",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "$\\sin r = \\frac{\\sin 45^\\circ}{\\mu} = \\frac{1/\\sqrt{2}}{\\sqrt{2}} = \\frac{1}{2} \\implies r = 30^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A microscope is focused on a mark at the bottom of a container. A liquid of depth $15\\text{ cm}$ is poured into it, and the microscope must be raised by $5\\text{ cm}$ to bring the mark back into focus. The refractive index of the liquid is:",
    "options": [],
    "correctAnswer": 1.5,
    "numericalAnswer": 1.5,
    "explanation": "$\\Delta s = d(1 - 1/\\mu) \\implies 5 = 15(1 - 1/\\mu) \\implies 1/3 = 1 - 1/\\mu \\implies \\mu = 1.5$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A glass plate of thickness $12\\text{ cm}$ and $\\mu = 1.5$ is placed on an ink mark. The apparent shift in the position of the mark in centimeters is:",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$\\Delta s = 12(1 - 1/1.5) = 12(1/3) = 4\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Light takes $t_1$ time to travel distance $x$ in vacuum and $t_2$ time to travel distance $10x$ in a medium. If the critical angle for the medium is $30^\\circ$, the ratio $t_2/t_1$ is:",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$\\mu = \\frac{1}{\\sin 30^\\circ} = 2$. $v = c/2$. $t_1 = x/c$. $t_2 = \\frac{10x}{c/2} = \\frac{20x}{c} = 20 t_1 \\implies \\frac{t_2}{t_1} = 20$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray of light strikes a glass slab of refractive index $1.732$ ($\\sqrt{3}$) such that the reflected and refracted rays are perpendicular. The angle of reflection in degrees is:",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "By Brewster's law, $\\tan i_p = \\mu = \\sqrt{3} \\implies i_p = 60^\\circ$. By the law of reflection, angle of reflection equals angle of incidence: $\\theta_r = 60^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A bird flying $12\\text{ m}$ above a lake surface is observed by a fish in water ($\\mu = 4/3$). The apparent height of the bird in meters as seen by the fish is:",
    "options": [],
    "correctAnswer": 16,
    "numericalAnswer": 16,
    "explanation": "$h' = \\mu h = \\frac{4}{3} \\times 12 = 16\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A fish swimming at a depth of $12\\text{ m}$ in water ($\\mu = 4/3$) is seen by a bird flying vertically above. The apparent depth of the fish in meters as seen by the bird is:",
    "options": [],
    "correctAnswer": 9,
    "numericalAnswer": 9,
    "explanation": "$d' = \\frac{d}{\\mu} = \\frac{12}{4/3} = 9\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Light has a wavelength of $589\\text{ nm}$ in vacuum. Its wavelength in a glass medium of refractive index $1.5$ in nanometers (rounded to nearest integer) is:",
    "options": [],
    "correctAnswer": 393,
    "numericalAnswer": 393,
    "explanation": "$\\lambda = \\frac{\\lambda_0}{\\mu} = \\frac{589}{1.5} \\approx 392.67 \\approx 393\\text{ nm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A glass cube of side $15\\text{ cm}$ has an air bubble trapped inside. When viewed from one face, it appears at $6\\text{ cm}$; when viewed from the opposite face, it appears at $4\\text{ cm}$. The refractive index of the glass is:",
    "options": [],
    "correctAnswer": 1.5,
    "numericalAnswer": 1.5,
    "explanation": "$d_1' + d_2' = \\frac{d_1}{\\mu} + \\frac{d_2}{\\mu} = \\frac{d_1 + d_2}{\\mu} = \\frac{t}{\\mu} \\implies 6 + 4 = \\frac{15}{\\mu} \\implies 10 = \\frac{15}{\\mu} \\implies \\mu = 1.5$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An incident ray makes an angle of $30^\\circ$ with a plane mirror. The angle of reflection in degrees is:",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "Angle of incidence $i = 90^\\circ - 30^\\circ = 60^\\circ$. Therefore, angle of reflection $r = i = 60^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A convex spherical surface of radius $20\\text{ cm}$ separates air ($\\mu_1 = 1$) and glass ($\\mu_2 = 1.5$). An object is placed in air at $100\\text{ cm}$ from the surface. The image distance in glass in centimeters is:",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$\\frac{\\mu_2}{v} - \\frac{\\mu_1}{u} = \\frac{\\mu_2 - \\mu_1}{R} \\implies \\frac{1.5}{v} - \\frac{1}{-100} = \\frac{1.5 - 1}{20} = \\frac{1}{40} \\implies \\frac{1.5}{v} = \\frac{1}{40} - \\frac{1}{100} = \\frac{3}{200} \\implies v = 100\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point source of light is placed in water ($\\mu = 4/3$) at a depth of $4\\text{ m}$. The optical path length traveled by a ray moving $3\\text{ m}$ in water in meters is:",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "Optical path length $= \\mu d = \\frac{4}{3} \\times 3\\text{ m} = 4\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ray enters a glass slab of thickness $10\\text{ cm}$ and $\\mu = 1.5$ at an angle $i = 0$. The lateral displacement of the ray in centimeters is:",
    "options": [],
    "correctAnswer": 0,
    "numericalAnswer": 0,
    "explanation": "At normal incidence $i = 0$, the ray passes undeviated with zero lateral displacement: $\\Delta x = 0$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Reflection/refraction",
    "chapter": "Optics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
