// Subtopic 4: Distance between parallel lines (18 questions: 6 MCQ, 6 AR, 6 NUM)
module.exports = [
  // --- MCQ 1 to 6 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The distance between the parallel lines $\\vec{r} = (\\hat{i} + 2\\hat{j} - 4\\hat{k}) + \\lambda(2\\hat{i} + 3\\hat{j} + 6\\hat{k})$ and $\\vec{r} = (3\\hat{i} + 3\\hat{j} - 5\\hat{k}) + \\mu(2\\hat{i} + 3\\hat{j} + 6\\hat{k})$ is:",
    options: [
      "$\\frac{\\sqrt{293}}{7}$",
      "$\\frac{\\sqrt{17}}{7}$",
      "$\\frac{19}{7}$",
      "$\\frac{\\sqrt{125}}{7}$"
    ],
    correctAnswer: 0,
    explanation: "Let $\\vec{a}_1 = \\hat{i} + 2\\hat{j} - 4\\hat{k}$, $\\vec{a}_2 = 3\\hat{i} + 3\\hat{j} - 5\\hat{k}$, and common direction vector $\\vec{b} = 2\\hat{i} + 3\\hat{j} + 6\\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = 2\\hat{i} + \\hat{j} - \\hat{k}$. The cross product $(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}$ is: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 2 & 1 & -1 \\\\ 2 & 3 & 6 \\end{vmatrix} = \\hat{i}(6 - (-3)) - \\hat{j}(12 - (-2)) + \\hat{k}(6 - 2) = 9\\hat{i} - 14\\hat{j} + 4\\hat{k}$$. Magnitude: $|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}| = \\sqrt{9^2 + (-14)^2 + 4^2} = \\sqrt{81 + 196 + 16} = \\sqrt{293}$. Also, $|\\vec{b}| = \\sqrt{2^2 + 3^2 + 6^2} = \\sqrt{4 + 9 + 36} = \\sqrt{49} = 7$. Thus, the distance is $d = \\frac{|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}|}{|\\vec{b}|} = \\frac{\\sqrt{293}}{7}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The distance between the parallel lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-2}{4} = \\frac{y-4}{6} = \\frac{z-5}{8}$ is:",
    options: [
      "$\\sqrt{\\frac{6}{29}}$",
      "$\\sqrt{\\frac{3}{29}}$",
      "$\\sqrt{\\frac{11}{29}}$",
      "$\\sqrt{\\frac{14}{29}}$"
    ],
    correctAnswer: 0,
    explanation: "Line 1 passes through $A(1, 2, 3)$ with direction vector $\\vec{b} = 2\\hat{i} + 3\\hat{j} + 4\\hat{k}$. Line 2 passes through $B(2, 4, 5)$ with direction vector $4\\hat{i} + 6\\hat{j} + 8\\hat{k} = 2\\vec{b}$. Thus the lines are parallel. Vector $\\vec{AB} = (2-1)\\hat{i} + (4-2)\\hat{j} + (5-3)\\hat{k} = \\hat{i} + 2\\hat{j} + 2\\hat{k}$. Now compute $\\vec{AB} \\times \\vec{b}$: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 2 & 2 \\\\ 2 & 3 & 4 \\end{vmatrix} = \\hat{i}(8 - 6) - \\hat{j}(4 - 4) + \\hat{k}(3 - 4) = 2\\hat{i} - \\hat{k}$$. Magnitude $|\\vec{AB} \\times \\vec{b}| = \\sqrt{2^2 + 0^2 + (-1)^2} = \\sqrt{4 + 1} = \\sqrt{5}$. Wait, $2(4) - 3(2) = 8 - 6 = 2$, $1(4) - 2(2) = 0$, $1(3) - 2(2) = -1$. Magnitude is $\\sqrt{5}$. But option has $\\sqrt{6/29}$! What if $B(2, 3, 4)$? Then $\\vec{AB} = (1, 1, 1)$. Then $\\vec{AB} \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 1 & 1 \\\\ 2 & 3 & 4 \\end{vmatrix} = \\hat{i}(4-3) - \\hat{j}(4-2) + \\hat{k}(3-2) = \\hat{i} - 2\\hat{j} + \\hat{k}$. Magnitude is $\\sqrt{1^2 + (-2)^2 + 1^2} = \\sqrt{1+4+1} = \\sqrt{6}$! And $|\\vec{b}| = \\sqrt{4+9+16} = \\sqrt{29}$. Then distance is $\\frac{\\sqrt{6}}{\\sqrt{29}} = \\sqrt{\\frac{6}{29}}$! Let line 2 pass through $(2, 3, 4)$: $\\frac{x-2}{4} = \\frac{y-3}{6} = \\frac{z-4}{8}$.",
    question: "The distance between the parallel lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-2}{4} = \\frac{y-3}{6} = \\frac{z-4}{8}$ is:",
    options: [
      "$\\sqrt{\\frac{6}{29}}$",
      "$\\sqrt{\\frac{3}{29}}$",
      "$\\sqrt{\\frac{11}{29}}$",
      "$\\sqrt{\\frac{14}{29}}$"
    ],
    correctAnswer: 0,
    explanation: "Line 1 passes through $A(1, 2, 3)$ with direction vector $\\vec{b} = 2\\hat{i} + 3\\hat{j} + 4\\hat{k}$. Line 2 passes through $B(2, 3, 4)$ with direction vector $4\\hat{i} + 6\\hat{j} + 8\\hat{k} = 2\\vec{b}$. Since the direction vectors are proportional, the lines are parallel. Vector $\\vec{AB} = (2-1)\\hat{i} + (3-2)\\hat{j} + (4-3)\\hat{k} = \\hat{i} + \\hat{j} + \\hat{k}$. The cross product is: $$\\vec{AB} \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 1 & 1 \\\\ 2 & 3 & 4 \\end{vmatrix} = \\hat{i}(4 - 3) - \\hat{j}(4 - 2) + \\hat{k}(3 - 2) = \\hat{i} - 2\\hat{j} + \\hat{k}$$. Magnitude $|\\vec{AB} \\times \\vec{b}| = \\sqrt{1^2 + (-2)^2 + 1^2} = \\sqrt{6}$. Magnitude of $\\vec{b}$ is $|\\vec{b}| = \\sqrt{2^2 + 3^2 + 4^2} = \\sqrt{4 + 9 + 16} = \\sqrt{29}$. Thus, the distance is $d = \\frac{\\sqrt{6}}{\\sqrt{29}} = \\sqrt{\\frac{6}{29}}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The distance between the parallel lines $\\vec{r} = (\\hat{i} + \\hat{j}) + \\lambda(2\\hat{i} - \\hat{j} + \\hat{k})$ and $\\vec{r} = (2\\hat{i} + \\hat{j} - \\hat{k}) + \\mu(2\\hat{i} - \\hat{j} + \\hat{k})$ is:",
    options: [
      "$\\sqrt{\\frac{5}{6}}$",
      "$\\sqrt{\\frac{1}{6}}$",
      "$\\sqrt{\\frac{7}{6}}$",
      "$\\sqrt{\\frac{11}{6}}$"
    ],
    correctAnswer: 0,
    explanation: "Here $\\vec{a}_1 = \\hat{i} + \\hat{j}$, $\\vec{a}_2 = 2\\hat{i} + \\hat{j} - \\hat{k}$, and $\\vec{b} = 2\\hat{i} - \\hat{j} + \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} - \\hat{k}$. The cross product is: $$(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 0 & -1 \\\\ 2 & -1 & 1 \\end{vmatrix} = \\hat{i}(0 - 1) - \\hat{j}(1 - (-2)) + \\hat{k}(-1 - 0) = -\\hat{i} - 3\\hat{j} - \\hat{k}$$. Magnitude: $|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}| = \\sqrt{(-1)^2 + (-3)^2 + (-1)^2} = \\sqrt{1 + 9 + 1} = \\sqrt{11}$. Wait, with magnitude $\\sqrt{11}$, the distance is $\\sqrt{11/6}$! Let us check option D: $\\sqrt{11/6}$. Option D is $\\sqrt{11/6}$! Thus the distance is $\\sqrt{\\frac{11}{6}}$.",
    correctAnswer: 3,
    options: [
      "$\\sqrt{\\frac{5}{6}}$",
      "$\\sqrt{\\frac{1}{6}}$",
      "$\\sqrt{\\frac{7}{6}}$",
      "$\\sqrt{\\frac{11}{6}}$"
    ],
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Hard",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If the distance between the parallel lines $\\vec{r} = (\\hat{i} + 2\\hat{j} + 3\\hat{k}) + \\lambda(\\hat{i} - \\hat{j} + \\hat{k})$ and $\\vec{r} = (2\\hat{i} + \\alpha\\hat{j} + \\hat{k}) + \\mu(\\hat{i} - \\hat{j} + \\hat{k})$ is $\\sqrt{\\frac{14}{3}}$, and $\\alpha > 0$, then the value of $\\alpha$ is:",
    options: [
      "$4$",
      "$3$",
      "$2$",
      "$5$"
    ],
    correctAnswer: 0,
    explanation: "Let $\\vec{a}_1 = \\hat{i} + 2\\hat{j} + 3\\hat{k}$ and $\\vec{a}_2 = 2\\hat{i} + \\alpha\\hat{j} + \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} + (\\alpha - 2)\\hat{j} - 2\\hat{k}$. The common direction vector is $\\vec{b} = \\hat{i} - \\hat{j} + \\hat{k}$ with $|\\vec{b}| = \\sqrt{1+1+1} = \\sqrt{3}$. Computing $(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}$: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & \\alpha - 2 & -2 \\\\ 1 & -1 & 1 \\end{vmatrix} = \\hat{i}(\\alpha - 2 - 2) - \\hat{j}(1 - (-2)) + \\hat{k}(-1 - (\\alpha - 2)) = (\\alpha - 4)\\hat{i} - 3\\hat{j} + (1 - \\alpha)\\hat{k}$$. Magnitude squared: $|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}|^2 = (\\alpha - 4)^2 + 9 + (1 - \\alpha)^2 = (\\alpha^2 - 8\\alpha + 16) + 9 + (\\alpha^2 - 2\\alpha + 1) = 2\\alpha^2 - 10\\alpha + 26$. Distance squared: $d^2 = \\frac{2\\alpha^2 - 10\\alpha + 26}{3} = \\frac{14}{3} \\implies 2\\alpha^2 - 10\\alpha + 26 = 14 \\implies 2\\alpha^2 - 10\\alpha + 12 = 0 \\implies \\alpha^2 - 5\\alpha + 6 = 0 \\implies (\\alpha - 2)(\\alpha - 3) = 0$. So $\\alpha = 2$ or $\\alpha = 3$. If $\\alpha = 3$, it is option B! What if we make the distance such that $\\alpha = 4$? For $\\alpha = 4$: $2(16) - 10(4) + 26 = 32 - 40 + 26 = 18$. Distance squared would be $18/3 = 6$. For $d = \\sqrt{6}$: $2\\alpha^2 - 10\\alpha + 26 = 18 \\implies 2\\alpha^2 - 10\\alpha + 8 = 0 \\implies \\alpha^2 - 5\\alpha + 4 = 0 \\implies (\\alpha-4)(\\alpha-1)=0$. If $\\alpha > 1$, then $\\alpha = 4$! Let us set $d = \\sqrt{6}$.",
    question: "If the distance between the parallel lines $\\vec{r} = (\\hat{i} + 2\\hat{j} + 3\\hat{k}) + \\lambda(\\hat{i} - \\hat{j} + \\hat{k})$ and $\\vec{r} = (2\\hat{i} + \\alpha\\hat{j} + \\hat{k}) + \\mu(\\hat{i} - \\hat{j} + \\hat{k})$ is $\\sqrt{6}$, where $\\alpha > 1$, then $\\alpha$ is equal to:",
    options: [
      "$4$",
      "$3$",
      "$2$",
      "$5$"
    ],
    correctAnswer: 0,
    explanation: "Let $\\vec{a}_1 = \\hat{i} + 2\\hat{j} + 3\\hat{k}$ and $\\vec{a}_2 = 2\\hat{i} + \\alpha\\hat{j} + \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} + (\\alpha - 2)\\hat{j} - 2\\hat{k}$. The direction vector is $\\vec{b} = \\hat{i} - \\hat{j} + \\hat{k}$ with $|\\vec{b}| = \\sqrt{3}$. Computing the cross product: $$(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & \\alpha - 2 & -2 \\\\ 1 & -1 & 1 \\end{vmatrix} = (\\alpha - 4)\\hat{i} - 3\\hat{j} + (1 - \\alpha)\\hat{k}$$. The square of the magnitude is: $$|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}|^2 = (\\alpha - 4)^2 + 9 + (1 - \\alpha)^2 = 2\\alpha^2 - 10\\alpha + 26$$. Given $d = \\sqrt{6}$, so $d^2 = 6$: $$\\frac{2\\alpha^2 - 10\\alpha + 26}{3} = 6 \\implies 2\\alpha^2 - 10\\alpha + 26 = 18 \\implies 2\\alpha^2 - 10\\alpha + 8 = 0 \\implies \\alpha^2 - 5\\alpha + 4 = 0$$. Factoring gives $(\\alpha - 1)(\\alpha - 4) = 0$. Since $\\alpha > 1$, we get $\\alpha = 4$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The distance between the parallel lines $\\frac{x}{1} = \\frac{y}{1} = \\frac{z}{1}$ and $\\frac{x-1}{1} = \\frac{y-2}{1} = \\frac{z-3}{1}$ is:",
    options: [
      "$\\sqrt{2}$",
      "$\\sqrt{3}$",
      "$2$",
      "$\\sqrt{6}$"
    ],
    correctAnswer: 0,
    explanation: "Line 1 passes through $O(0, 0, 0)$ with direction vector $\\vec{b} = \\hat{i} + \\hat{j} + \\hat{k}$. Line 2 passes through $A(1, 2, 3)$. Then $\\vec{OA} = \\hat{i} + 2\\hat{j} + 3\\hat{k}$. The cross product $\\vec{OA} \\times \\vec{b}$ is: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 2 & 3 \\\\ 1 & 1 & 1 \\end{vmatrix} = \\hat{i}(2 - 3) - \\hat{j}(1 - 3) + \\hat{k}(1 - 2) = -\\hat{i} + 2\\hat{j} - \\hat{k}$$. Magnitude $|\\vec{OA} \\times \\vec{b}| = \\sqrt{(-1)^2 + 2^2 + (-1)^2} = \\sqrt{1 + 4 + 1} = \\sqrt{6}$. Also $|\\vec{b}| = \\sqrt{1^2 + 1^2 + 1^2} = \\sqrt{3}$. Thus, the distance is $d = \\frac{\\sqrt{6}}{\\sqrt{3}} = \\sqrt{2}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between two parallel lines $\\vec{r} = \\vec{a}_1 + \\lambda\\vec{b}$ and $\\vec{r} = \\vec{a}_2 + \\mu\\vec{b}$ is zero if and only if:",
    options: [
      "$(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b} = \\vec{0}$",
      "$(\\vec{a}_2 - \\vec{a}_1) \\cdot \\vec{b} = 0$",
      "$\\vec{a}_1 = \\vec{a}_2$",
      "$\\vec{a}_1 \\cdot \\vec{a}_2 = 0$"
    ],
    correctAnswer: 0,
    explanation: "The formula for distance between parallel lines is $d = \\frac{|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}|}{|\\vec{b}|}$. This distance is zero if and only if the numerator is zero, i.e., $(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b} = \\vec{0}$. This corresponds to the two parallel lines being coincident.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- ASSERTION_REASON 7 to 12 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The distance between the parallel lines $\\vec{r} = \\vec{a}_1 + \\lambda \\vec{b}$ and $\\vec{r} = \\vec{a}_2 + \\mu \\vec{b}$ is given by $\\frac{|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}|}{|\\vec{b}|}$.\nReason R: The area of the parallelogram formed by vectors $\\vec{a}_2 - \\vec{a}_1$ and $\\vec{b}$ divided by the base length $|\\vec{b}|$ equals the perpendicular height between the lines.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "The geometric derivation of the distance between parallel lines considers the parallelogram formed by $\\vec{a}_2 - \\vec{a}_1$ and $\\vec{b}$. Its area is $|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}| = |\\vec{b}| \\times h$, where $h$ is the perpendicular distance between the lines. Thus $h = \\frac{|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}|}{|\\vec{b}|}$. Both statements are true and Reason R provides the exact geometric proof.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The lines $\\frac{x-1}{2} = \\frac{y-2}{4} = \\frac{z-3}{6}$ and $\\frac{x-3}{1} = \\frac{y-4}{2} = \\frac{z-5}{3}$ are parallel lines.\nReason R: The direction ratios of the lines are $(2, 4, 6)$ and $(1, 2, 3)$, which satisfy $\\frac{2}{1} = \\frac{4}{2} = \\frac{6}{3} = 2$.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "Two lines are parallel if their direction ratios are proportional. Here $\\frac{2}{1} = \\frac{4}{2} = \\frac{6}{3} = 2$. Furthermore, substituting point $(3, 4, 5)$ into the first line gives $\\frac{3-1}{2} = 1, \\frac{4-2}{4} = 0.5$, which are unequal, so the lines are distinct and parallel. Both statements are true and Reason R correctly explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The distance between the parallel lines $\\vec{r} = \\lambda(\\hat{i} + \\hat{j} + \\hat{k})$ and $\\vec{r} = (\\hat{i} + \\hat{j} + \\hat{k}) + \\mu(\\hat{i} + \\hat{j} + \\hat{k})$ is zero.\nReason R: The point $(1, 1, 1)$ lies on the line $\\vec{r} = \\lambda(\\hat{i} + \\hat{j} + \\hat{k})$ for $\\lambda = 1$, making the two lines coincident.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "For $\\lambda = 1$, the first line passes through $\\hat{i} + \\hat{j} + \\hat{k}$. Since both lines share the point $(1, 1, 1)$ and have the same direction vector, they are coincident. The distance between coincident lines is $0$. Both statements are true and Reason R explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Hard",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The shortest distance formula for skew lines $d = \\frac{|(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2)|}{|\\vec{b}_1 \\times \\vec{b}_2|}$ can be directly applied to find the distance between parallel lines.\nReason R: For parallel lines, the direction vectors $\\vec{b}_1$ and $\\vec{b}_2$ are collinear, so $\\vec{b}_1 \\times \\vec{b}_2 = \\vec{0}$, making the denominator zero.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 3,
    explanation: "Assertion A is false: The skew lines formula cannot be used directly for parallel lines because $\\vec{b}_1 \\times \\vec{b}_2 = \\vec{0}$, which results in an indeterminate $\\frac{0}{0}$ expression. Reason R correctly states why this occurs. Therefore, Assertion A is false but Reason R is true.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The distance between two parallel lines is constant everywhere along the length of the lines.\nReason R: In Euclidean three-dimensional geometry, parallel lines remain equidistant from each other at all corresponding points.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "By Euclidean definition, parallel lines lie in the same plane and the perpendicular distance from any point on one line to the other line is constant. Both statements are true and Reason R correctly explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The distance between the parallel lines $\\frac{x}{2} = \\frac{y}{3} = \\frac{z}{4}$ and $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ is independent of the parameter chosen along the lines.\nReason R: The shortest distance between two parallel lines is a scalar invariant of the two lines.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "The shortest perpendicular distance between two lines is a geometric invariant that does not depend on parameterization or the specific points chosen on the lines. Both statements are true and Reason R correctly explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- NUMERICAL 13 to 18 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "The square of the distance between the parallel lines $\\frac{x}{1} = \\frac{y}{1} = \\frac{z}{1}$ and $\\frac{x-1}{1} = \\frac{y-2}{1} = \\frac{z-3}{1}$ is equal to:",
    options: [],
    correctAnswer: 2,
    explanation: "Line 1 passes through $O(0, 0, 0)$ with $\\vec{b} = \\hat{i} + \\hat{j} + \\hat{k}$. Line 2 passes through $A(1, 2, 3)$. Then $\\vec{OA} = \\hat{i} + 2\\hat{j} + 3\\hat{k}$. Vector $\\vec{OA} \\times \\vec{b} = -\\hat{i} + 2\\hat{j} - \\hat{k}$. Magnitude $|\\vec{OA} \\times \\vec{b}| = \\sqrt{(-1)^2 + 2^2 + (-1)^2} = \\sqrt{6}$. Also $|\\vec{b}| = \\sqrt{1^2 + 1^2 + 1^2} = \\sqrt{3}$. Thus $d = \\frac{\\sqrt{6}}{\\sqrt{3}} = \\sqrt{2}$, and $d^2 = 2$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the distance between the parallel lines $\\vec{r} = (\\hat{i} + 2\\hat{j} - \\hat{k}) + \\lambda(2\\hat{i} + 3\\hat{j} + 6\\hat{k})$ and $\\vec{r} = (3\\hat{i} + 3\\hat{j} + k\\hat{k}) + \\mu(2\\hat{i} + 3\\hat{j} + 6\\hat{k})$ is $\\frac{\\sqrt{117}}{7}$, then the non-negative integer value of $k$ is:",
    options: [],
    correctAnswer: 1,
    explanation: "Let $\\vec{a}_1 = \\hat{i} + 2\\hat{j} - \\hat{k}$ and $\\vec{a}_2 = 3\\hat{i} + 3\\hat{j} + k\\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = 2\\hat{i} + \\hat{j} + (k+1)\\hat{k}$. Cross product with $\\vec{b} = 2\\hat{i} + 3\\hat{j} + 6\\hat{k}$: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 2 & 1 & k+1 \\\\ 2 & 3 & 6 \\end{vmatrix} = \\hat{i}(6 - 3(k+1)) - \\hat{j}(12 - 2(k+1)) + \\hat{k}(6 - 2) = (3 - 3k)\\hat{i} + (2k - 10)\\hat{j} + 4\\hat{k}$$. For $k = 1$: $(3 - 3)\\hat{i} + (2 - 10)\\hat{j} + 4\\hat{k} = -8\\hat{j} + 4\\hat{k}$. Magnitude squared: $(-8)^2 + 4^2 = 64 + 16 = 80$. What if $k = 2$? $(3 - 6)\\hat{i} + (4 - 10)\\hat{j} + 4\\hat{k} = -3\\hat{i} - 6\\hat{j} + 4\\hat{k}$, magnitude squared: $9 + 36 + 16 = 61$. For $k = 0$: $3\\hat{i} - 10\\hat{j} + 4\\hat{k}$, magnitude squared: $9 + 100 + 16 = 125$. For $k = -1$: $6\\hat{i} - 12\\hat{j} + 4\\hat{k}$, magnitude squared: $36 + 144 + 16 = 196$, then distance is $\\sqrt{196}/7 = 14/7 = 2$! Excellent! If $k = -1$, the distance is an exact integer $2$!",
    question: "The distance between the parallel lines $\\vec{r} = (\\hat{i} + 2\\hat{j} - \\hat{k}) + \\lambda(2\\hat{i} + 3\\hat{j} + 6\\hat{k})$ and $\\vec{r} = (3\\hat{i} + 3\\hat{j} - \\hat{k}) + \\mu(2\\hat{i} + 3\\hat{j} + 6\\hat{k})$ is equal to:",
    correctAnswer: 2,
    explanation: "Let $\\vec{a}_1 = \\hat{i} + 2\\hat{j} - \\hat{k}$ and $\\vec{a}_2 = 3\\hat{i} + 3\\hat{j} - \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = 2\\hat{i} + \\hat{j} + 0\\hat{k} = 2\\hat{i} + \\hat{j}$. The cross product with $\\vec{b} = 2\\hat{i} + 3\\hat{j} + 6\\hat{k}$ is: $$(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 2 & 1 & 0 \\\\ 2 & 3 & 6 \\end{vmatrix} = \\hat{i}(6) - \\hat{j}(12) + \\hat{k}(6 - 2) = 6\\hat{i} - 12\\hat{j} + 4\\hat{k}$$. The magnitude is $|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}| = \\sqrt{6^2 + (-12)^2 + 4^2} = \\sqrt{36 + 144 + 16} = \\sqrt{196} = 14$. The magnitude of $\\vec{b}$ is $|\\vec{b}| = \\sqrt{2^2 + 3^2 + 6^2} = 7$. Thus, the distance is $d = \\frac{14}{7} = 2$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the distance between the parallel lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-2}{4} = \\frac{y-3}{6} = \\frac{z-4}{8}$ is $d$, then the value of $29d^2$ is:",
    options: [],
    correctAnswer: 6,
    explanation: "Line 1 passes through $A(1, 2, 3)$ with direction vector $\\vec{b} = 2\\hat{i} + 3\\hat{j} + 4\\hat{k}$. Line 2 passes through $B(2, 3, 4)$ with direction vector $2\\vec{b}$. Vector $\\vec{AB} = \\hat{i} + \\hat{j} + \\hat{k}$. The cross product is: $$\\vec{AB} \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 1 & 1 \\\\ 2 & 3 & 4 \\end{vmatrix} = \\hat{i}(4-3) - \\hat{j}(4-2) + \\hat{k}(3-2) = \\hat{i} - 2\\hat{j} + \\hat{k}$$. Magnitude squared is $|\\vec{AB} \\times \\vec{b}|^2 = 1^2 + (-2)^2 + 1^2 = 6$. Also $|\\vec{b}|^2 = 2^2 + 3^2 + 4^2 = 29$. Therefore, $d^2 = \\frac{6}{29} \\implies 29d^2 = 6$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "The distance between the parallel lines $\\vec{r} = \\lambda(2\\hat{i} + 2\\hat{j} + \\hat{k})$ and $\\vec{r} = (3\\hat{i} + 0\\hat{j} + 0\\hat{k}) + \\mu(2\\hat{i} + 2\\hat{j} + \\hat{k})$ is equal to:",
    options: [],
    correctAnswer: 2,
    explanation: "Let $\\vec{a}_1 = \\vec{0}$, $\\vec{a}_2 = 3\\hat{i}$, and $\\vec{b} = 2\\hat{i} + 2\\hat{j} + \\hat{k}$. Vector $\\vec{a}_2 - \\vec{a}_1 = 3\\hat{i}$. The cross product is: $$(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 3 & 0 & 0 \\\\ 2 & 2 & 1 \\end{vmatrix} = \\hat{i}(0) - \\hat{j}(3) + \\hat{k}(6) = -3\\hat{j} + 6\\hat{k}$$. Magnitude: $|(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b}| = \\sqrt{(-3)^2 + 6^2} = \\sqrt{9 + 36} = \\sqrt{45} = 3\\sqrt{5}$. Magnitude of $\\vec{b}$ is $|\\vec{b}| = \\sqrt{4 + 4 + 1} = 3$. Distance is $\\frac{3\\sqrt{5}}{3} = \\sqrt{5}$. So $d = \\sqrt{5}$, and $d^2 = 5$. Let us ask for $d^2$!",
    question: "The square of the distance between the parallel lines $\\vec{r} = \\lambda(2\\hat{i} + 2\\hat{j} + \\hat{k})$ and $\\vec{r} = (3\\hat{i}) + \\mu(2\\hat{i} + 2\\hat{j} + \\hat{k})$ is equal to:",
    correctAnswer: 5,
    explanation: "Let $\\vec{a}_1 = \\vec{0}$, $\\vec{a}_2 = 3\\hat{i}$, and $\\vec{b} = 2\\hat{i} + 2\\hat{j} + \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = 3\\hat{i}$. The cross product is: $$(\\vec{a}_2 - \\vec{a}_1) \\times \\vec{b} = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 3 & 0 & 0 \\\\ 2 & 2 & 1 \\end{vmatrix} = -3\\hat{j} + 6\\hat{k}$$. The magnitude is $\\sqrt{(-3)^2 + 6^2} = \\sqrt{45} = 3\\sqrt{5}$. The magnitude of $\\vec{b}$ is $\\sqrt{2^2 + 2^2 + 1^2} = 3$. Thus, the distance is $d = \\frac{3\\sqrt{5}}{3} = \\sqrt{5}$, which gives $d^2 = 5$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Hard",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the parallel lines $\\frac{x-1}{a} = \\frac{y-2}{b} = \\frac{z-3}{c}$ and $\\frac{x-2}{1} = \\frac{y-3}{2} = \\frac{z-4}{2}$ are separated by a distance $d = \\sqrt{\\frac{2}{9}}$, where $(a, b, c) = (1, 2, 2)$, then the value of $9d^2$ is:",
    options: [],
    correctAnswer: 2,
    explanation: "Given $d = \\sqrt{\\frac{2}{9}}$, we have $d^2 = \\frac{2}{9}$. Multiplying by $9$ yields $9d^2 = 9 \\times \\frac{2}{9} = 2$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Distance between parallel lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "The distance between the parallel lines $\\vec{r} = \\lambda\\hat{i}$ and $\\vec{r} = (3\\hat{j} + 4\\hat{k}) + \\mu\\hat{i}$ is equal to:",
    options: [],
    correctAnswer: 5,
    explanation: "Line 1 is along the $x$-axis ($\\{ (x, 0, 0) \\}$). Line 2 passes through $(0, 3, 4)$ and is also parallel to the $x$-axis ($\\{ (x, 3, 4) \\}$). The perpendicular distance between any point on Line 1 and Line 2 is simply the distance in the $yz$-plane: $d = \\sqrt{3^2 + 4^2} = \\sqrt{9 + 16} = \\sqrt{25} = 5$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  }
];
