module.exports = [
  {
    "question": "Assertion: Beats can be heard distinctly by the human ear only when the frequency difference between the two sounding bodies is less than or equal to $10\\,\\text{Hz}$.\\nReason: The persistence of hearing for the human ear is approximately $0.1\\,\\text{seconds}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Because of the persistence of hearing ($0.1\\,\\text{s}$), the human brain cannot resolve acoustic intensity fluctuations that occur faster than 10 times per second. If beat frequency $f_b > 10\\,\\text{Hz}$, the individual waxing and waning blend into a continuous harsh sound. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: When wax is loaded onto the prongs of a tuning fork, its natural frequency of vibration decreases.\\nReason: Loading wax increases the effective vibrating mass and inertia of the prongs without changing their elastic stiffness.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The frequency of a cantilevered tuning fork prong is given by $f \\propto \\sqrt{\\frac{k}{m}}$. Adding wax increases the vibrating mass $m$, which reduces the natural oscillation frequency $f$. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Filing the prongs of a tuning fork increases its vibrational frequency.\\nReason: Filing removes metal from the prongs, decreasing their mass and inertia.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Filing the prongs thins them out and reduces their mass $m$ without substantially diminishing their restoring elasticity, thereby increasing the natural frequency according to $f \\propto \\sqrt{k/m}$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The phenomenon of beats is a temporal interference effect, whereas normal fringe patterns are a spatial interference effect.\\nReason: Beats arise from the superposition of two waves of slightly different frequencies traveling in the same direction, resulting in periodic intensity variations at a fixed point in time.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "In spatial interference, two waves of identical frequency create a stationary pattern of maxima and minima across space. In beats, the frequency mismatch causes the relative phase at a fixed location to cycle through $0$ to $2\\pi$ periodically over time, producing temporal waxing and waning. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The time interval between a maximum sound intensity (waxing) and the immediately succeeding minimum sound intensity (waning) in beats is $\\frac{1}{2(f_1 - f_2)}$.\\nReason: One complete beat period $T_b = \\frac{1}{|f_1 - f_2|}$ corresponds to the time between two consecutive intensity maxima.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The full beat period from one maximum to the next is $T_b = \\frac{1}{f_b} = \\frac{1}{|f_1 - f_2|}$. The minimum occurs halfway through the cycle when the waves become $180^\\circ$ out of phase, at time $\\frac{T_b}{2} = \\frac{1}{2|f_1 - f_2|}$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Tuning fork $A$ of frequency $256\\,\\text{Hz}$ produces $4\\,\\text{beats/s}$ with fork $B$. When $B$ is loaded with wax, the beat frequency increases to $6\\,\\text{beats/s}$. Therefore, the original frequency of $B$ was $252\\,\\text{Hz}$.\\nReason: Loading with wax decreases the frequency of fork $B$, so if $f_B$ were already below $f_A$ ($252\\,\\text{Hz}$), decreasing it further would widen the gap $|f_A - f_B|$, increasing the beat frequency.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Initially $|f_A - f_B| = 4 \\implies f_B = 260\\,\\text{Hz}$ or $252\\,\\text{Hz}$. When $B$ is loaded with wax, $f_B$ decreases. If $f_B = 260\\,\\text{Hz}$, decreasing it would bring it closer to $256\\,\\text{Hz}$, reducing the beat frequency. If $f_B = 252\\,\\text{Hz}$, decreasing it moves it further from $256\\,\\text{Hz}$, increasing the beat frequency to $6\\,\\text{Hz}$. Thus $f_B$ must have been $252\\,\\text{Hz}$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Beats can be observed for transverse waves on strings as well as longitudinal sound waves in gases.\\nReason: The phenomenon of beats depends purely on the mathematical principle of superposition of two waves with slightly different frequencies.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Beat formation is not restricted to sound waves; any two waves (transverse on strings, electromagnetic, or acoustic) of slightly different frequencies superpose to modulate amplitude temporally according to the trigonometric identity for $\\sin(\\omega_1 t) + \\sin(\\omega_2 t)$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: If two tuning forks of frequencies $500\\,\\text{Hz}$ and $505\\,\\text{Hz}$ are sounded together, the listener hears 5 loud pulses per second.\\nReason: The beat frequency is equal to the absolute difference between the frequencies of the two interfering sources: $f_b = |f_1 - f_2| = |505 - 500| = 5\\,\\text{Hz}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The beat frequency is given by $f_b = |f_1 - f_2| = 505 - 500 = 5\\,\\text{Hz}$. The listener perceives 5 intensity maxima per second. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Musicians use the phenomenon of beats to tune their musical instruments to a standard pitch.\\nReason: When the frequency of the instrument matches the standard tuning fork exactly, the beat frequency drops to zero.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "As an instrument string is tightened or loosened toward the frequency of a standard tuning fork, the beat frequency $f_b = |f_{\\text{instrument}} - f_{\\text{fork}}|$ decreases continuously. When perfect unison is reached, $f_b = 0$ and the beats vanish completely. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The amplitude of the envelope wave in beats oscillates with frequency $\\frac{|f_1 - f_2|}{2}$, but the intensity oscillates with frequency $|f_1 - f_2|$.\\nReason: Acoustic intensity is proportional to the square of the envelope amplitude, and the square of a harmonic function completes two full cycles for every single cycle of the function.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The displacement is $y = 2A\\cos\\left(\\frac{\\omega_1 - \\omega_2}{2}t\\right)\\sin\\left(\\frac{\\omega_1 + \\omega_2}{2}t\\right)$. The envelope amplitude is $A_{\\text{env}}(t) = 2A\\cos\\left(2\\pi\\frac{f_1 - f_2}{2}t\\right)$, which has frequency $\\frac{f_1 - f_2}{2}$. Since intensity $I \\propto A_{\\text{env}}^2 \\propto \\cos^2(2\\pi \\frac{f_1 - f_2}{2}t) = \\frac{1 + \\cos(2\\pi(f_1 - f_2)t)}{2}$, the intensity beats with frequency $|f_1 - f_2|$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: When two organ pipes of slightly different lengths are blown simultaneously, beats are produced.\\nReason: The fundamental frequencies of the two pipes differ because fundamental frequency is inversely proportional to the length of the pipe ($f \\propto 1/L$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Because the pipe lengths differ, their natural fundamental frequencies $f_1 = \\frac{v}{2L_1}$ and $f_2 = \\frac{v}{2L_2}$ differ slightly. Sounding them together creates beats with frequency $f_b = \\frac{v}{2}\\left|\\frac{1}{L_1} - \\frac{1}{L_2}\\right|$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Two tuning forks producing $3\\,\\text{beats/s}$ are sounded. If the temperature of the room rises, the beat frequency remains unchanged if the forks are made of the same metal.\\nReason: Thermal expansion affects both identical tuning forks in the same proportion, keeping their frequency difference essentially invariant.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Tuning fork frequencies depend on material density, dimensions, and Young's modulus. Since both forks are at the same ambient temperature and constructed of identical alloy, temperature changes scale both frequencies proportionally: $\\frac{\\Delta f}{f} = \\text{constant}$. For a very small initial difference, $|f_1 - f_2|$ remains virtually constant. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Complete silence is heard at the minima of beats only when the two interfering waves have identical amplitudes.\\nReason: The minimum amplitude in beats is given by $|A_1 - A_2|$, which is zero if and only if $A_1 = A_2$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "If $A_1 \\neq A_2$, the opposing waves cannot cancel completely at the out-of-phase condition, leaving a residual amplitude $|A_1 - A_2| > 0$. Zero sound at minima requires $A_1 = A_2$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: A person hears beats when standing between two identical sound sources if he moves towards one of the sources.\\nReason: Due to the Doppler effect, the frequency of sound heard from the source approached increases, while that from the source receded from decreases.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "If the observer moves with speed $u$ between two stationary sources of frequency $f_0$, the apparent frequency from the source in front is $f_1 = f_0\\left(1 + \\frac{u}{v}\\right)$, and from behind is $f_2 = f_0\\left(1 - \\frac{u}{v}\\right)$. The frequency difference produces beats of frequency $f_b = f_1 - f_2 = \\frac{2u}{v}f_0$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: A tuning fork $A$ produces $5\\,\\text{beats/s}$ with a $250\\,\\text{Hz}$ fork. When $A$ is filed, the beat frequency becomes $2\\,\\text{beats/s}$. The original frequency of fork $A$ was $245\\,\\text{Hz}$.\\nReason: Filing a tuning fork increases its frequency, so if its original frequency was $245\\,\\text{Hz}$, increasing it brings it closer to $250\\,\\text{Hz}$, reducing the beat frequency.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Initially $|f_A - 250| = 5 \\implies f_A = 255$ or $245\\,\\text{Hz}$. Filing increases $f_A$. If $f_A$ were $255\\,\\text{Hz}$, filing would increase it to e.g. $258\\,\\text{Hz}$, raising beat frequency to $8\\,\\text{Hz}$. If $f_A = 245\\,\\text{Hz}$, filing raises it to e.g. $248\\,\\text{Hz}$, reducing beat frequency to $250 - 248 = 2\\,\\text{Hz}$. Thus the original frequency was $245\\,\\text{Hz}$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The number of beats heard per second when $n$ tuning forks are arranged in increasing order of frequency, such that each gives $x$ beats with the preceding one, between the first and last fork is $(n - 1)x$.\\nReason: The frequency of the $k$-th fork is $f_k = f_1 + (k - 1)x$, so $f_n - f_1 = (n - 1)x$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The frequencies form an arithmetic progression with common difference $x$. Thus $f_n = f_1 + (n - 1)x$. Sounding the first and $n$-th fork together yields a beat frequency $f_n - f_1 = (n - 1)x$. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Beats cannot be formed by waves that travel in opposite directions along a line.\\nReason: Two identical waves traveling in opposite directions superpose to form standing waves rather than beats.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 1,
    "explanation": "When two waves travel in opposite directions, even with slightly different frequencies, they form a non-stationary standing wave (with slowly drifting nodes) rather than pure temporal beats at a single spatial location. Both statements are true facts, but Reason describes identical frequency waves whereas beats involve frequency differences. Hence Reason is not the complete explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: If the intensities of two interfering sources in a beat experiment are $I$ and $9I$, the ratio of maximum to minimum intensity in the beat cycle is $4:1$.\\nReason: The maximum amplitude is $\\sqrt{9I} + \\sqrt{I} = 4\\sqrt{I}$ and minimum amplitude is $\\sqrt{9I} - \\sqrt{I} = 2\\sqrt{I}$, giving $\\frac{I_{\\max}}{I_{\\min}} = \\left(\\frac{4}{2}\\right)^2 = 4$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Amplitudes are $A_1 = 3A_0$ and $A_2 = A_0$. Maximum amplitude is $3A_0 + A_0 = 4A_0$, and minimum amplitude is $3A_0 - A_0 = 2A_0$. The ratio of maximum to minimum intensity is $\\left(\\frac{4A_0}{2A_0}\\right)^2 = 2^2 = 4$. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: A closed organ pipe and an open organ pipe can produce beats when sounded together.\\nReason: The lengths of the two pipes can be chosen such that their resonant frequencies are slightly different ($|f_1 - f_2| \\le 10\\,\\text{Hz}$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Any two sound generators emitting tones with a frequency difference within the audible beat range ($< 10\\,\\text{Hz}$) will generate audible beats upon superposition, regardless of whether they are open or closed pipes. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: In beats, the average intensity over one beat cycle is equal to the sum of the individual intensities of the two interfering waves ($I_1 + I_2$).\\nReason: The time average of $\\cos(2\\pi f_b t)$ over a full beat cycle is zero.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Instantaneous intensity is $I(t) = I_1 + I_2 + 2\\sqrt{I_1 I_2}\\cos(2\\pi f_b t)$. Since $\\frac{1}{T_b}\\int_0^{T_b} \\cos(2\\pi f_b t) dt = 0$, the time-averaged intensity over a beat cycle is $\\langle I \\rangle = I_1 + I_2$. Energy is conserved. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: If two tuning forks $A$ and $B$ produce $5\\,\\text{beats/s}$, and loading $A$ with wax decreases the beat frequency to $2\\,\\text{beats/s}$, the frequency of fork $A$ is greater than that of fork $B$.\\nReason: Loading $A$ with wax decreases $f_A$, and if $f_A > f_B$, decreasing $f_A$ brings it closer to $f_B$, reducing the beat frequency $|f_A - f_B|$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Beat frequency is $f_b = |f_A - f_B| = 5$. Since loading $A$ decreases $f_A$ and this results in a lower beat frequency ($2\\,\\text{Hz}$), $f_A$ must have been higher than $f_B$ initially ($f_A - f_B = 5$). Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Ultrasonic waves can also produce beats upon superposition.\\nReason: Ultrasonic waves are mechanical sound waves having frequencies above $20\\,\\text{kHz}$, and superposition of any two harmonic waves with slightly different frequencies yields beats.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Superposition of two ultrasonic waves with frequencies, say, $40000\\,\\text{Hz}$ and $40005\\,\\text{Hz}$ produces a beat frequency of $5\\,\\text{Hz}$. Although the carrier frequency is ultrasonic, the resulting $5\\,\\text{Hz}$ envelope modulation is in the infrasonic/audible intensity range and can be detected by sensors. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Heterodyne detection in radio receivers operates on the exact same mathematical principle as acoustic beats.\\nReason: Non-linear mixing of an incoming high-frequency radio signal with a local oscillator frequency produces sum and difference frequencies, where the difference frequency is an intermediate frequency (IF).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Superheterodyne radio receivers mix an incoming RF signal with a local oscillator to yield a difference (beat) frequency $f_{\\text{IF}} = |f_{\\text{RF}} - f_{\\text{LO}}|$, exactly mirroring the frequency subtraction in acoustic beats. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: A vibrating wire of length $L_1$ and another identical wire of length $L_2$ under the same tension produce beats.\\nReason: The fundamental frequency of a stretched wire is inversely proportional to its length ($f = \\frac{v}{2L}$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Because $f_1 = \\frac{v}{2L_1}$ and $f_2 = \\frac{v}{2L_2}$, if $L_1 \\approx L_2$, $f_1$ and $f_2$ differ slightly, resulting in audible beats when plucked simultaneously. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Beats can be heard when two tuning forks of frequencies $256\\,\\text{Hz}$ and $260\\,\\text{Hz}$ are sounded simultaneously.\\nReason: The beat frequency is $4\\,\\text{Hz}$, which is well within the human ear's temporal resolution limit of $10\\,\\text{Hz}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Beat frequency is $f_b = 260 - 256 = 4\\,\\text{Hz}$. Since $4\\,\\text{Hz} < 10\\,\\text{Hz}$, the ear comfortably resolves the periodic waxing and waning. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: When two sound waves $y_1 = A\\sin(2000\\pi t)$ and $y_2 = A\\sin(2008\\pi t)$ superpose, 4 beats are heard per second.\\nReason: The frequencies are $f_1 = \\frac{2000\\pi}{2\\pi} = 1000\\,\\text{Hz}$ and $f_2 = \\frac{2008\\pi}{2\\pi} = 1004\\,\\text{Hz}$, giving $f_b = |1004 - 1000| = 4\\,\\text{Hz}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Frequencies are $f_1 = 1000\\,\\text{Hz}$ and $f_2 = 1004\\,\\text{Hz}$. The beat frequency is $f_b = |1004 - 1000| = 4\\,\\text{Hz}$. Thus 4 beats are heard per second. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A tuning fork of known frequency $256\\,\\text{Hz}$ produces $4\\,\\text{beats/s}$ with another tuning fork $B$. When the prongs of fork $B$ are loaded with a small amount of wax, the beat frequency becomes $2\\,\\text{beats/s}$. What is the original frequency of tuning fork $B$?",
    "options": [
      "$260\\,\\text{Hz}$",
      "$252\\,\\text{Hz}$",
      "$258\\,\\text{Hz}$",
      "$254\\,\\text{Hz}$"
    ],
    "correctAnswer": 0,
    "explanation": "Initially, $|f_B - 256| = 4 \\implies f_B = 260\\,\\text{Hz}$ or $252\\,\\text{Hz}$. Loading $B$ with wax decreases $f_B$. If $f_B = 260\\,\\text{Hz}$, decreasing it brings it closer to $256\\,\\text{Hz}$, reducing the beat frequency to $2\\,\\text{beats/s}$ (e.g. $f_B' = 258\\,\\text{Hz}$). If $f_B = 252\\,\\text{Hz}$, decreasing it would increase the beat frequency. Hence the original frequency was $260\\,\\text{Hz}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two vibrating tuning forks produce progressive waves given by $y_1 = 4\\sin(500\\pi t)$ and $y_2 = 2\\sin(506\\pi t)$, where $t$ is in seconds. The number of beats heard per second and the ratio of maximum to minimum intensity in the beats are:",
    "options": [
      "$3\\,\\text{beats/s}$ and $9:1$",
      "$6\\,\\text{beats/s}$ and $9:1$",
      "$3\\,\\text{beats/s}$ and $4:1$",
      "$6\\,\\text{beats/s}$ and $3:1$"
    ],
    "correctAnswer": 0,
    "explanation": "The frequencies are $f_1 = \\frac{500\\pi}{2\\pi} = 250\\,\\text{Hz}$ and $f_2 = \\frac{506\\pi}{2\\pi} = 253\\,\\text{Hz}$. Beat frequency is $f_b = |253 - 250| = 3\\,\\text{beats/s}$. Maximum amplitude is $A_{\\max} = 4 + 2 = 6$, and minimum amplitude is $A_{\\min} = 4 - 2 = 2$. The intensity ratio is $\\frac{I_{\\max}}{I_{\\min}} = \\left(\\frac{6}{2}\\right)^2 = 3^2 = 9:1$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "16 tuning forks are arranged in increasing order of frequencies such that each tuning fork gives $4\\,\\text{beats/s}$ with the next one. If the frequency of the last tuning fork is twice that of the first, find the frequency of the first tuning fork:",
    "options": [
      "$60\\,\\text{Hz}$",
      "$120\\,\\text{Hz}$",
      "$64\\,\\text{Hz}$",
      "$56\\,\\text{Hz}$"
    ],
    "correctAnswer": 0,
    "explanation": "Let the frequency of the first fork be $f_1$. The $n$-th fork has frequency $f_{16} = f_1 + (16 - 1)(4) = f_1 + 60$. Given $f_{16} = 2f_1$, we have $2f_1 = f_1 + 60 \\implies f_1 = 60\\,\\text{Hz}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two sound waves of wavelengths $1.00\\,\\text{m}$ and $1.02\\,\\text{m}$ produce $16\\,\\text{beats}$ in $2.4\\,\\text{seconds}$ in a gas. What is the speed of sound in the gas?",
    "options": [
      "$340\\,\\text{m/s}$",
      "$330\\,\\text{m/s}$",
      "$320\\,\\text{m/s}$",
      "$350\\,\\text{m/s}$"
    ],
    "correctAnswer": 0,
    "explanation": "Beat frequency is $f_b = \\frac{16}{2.4} = \\frac{20}{3}\\,\\text{Hz}$. Using $f = v/\\lambda$: $f_b = v\\left(\\frac{1}{\\lambda_1} - \\frac{1}{\\lambda_2}\\right) = v\\left(\\frac{1}{1.00} - \\frac{1}{1.02}\\right) = v\\left(\\frac{0.02}{1.02}\\right) = \\frac{v}{51}$. Equating gives $\\frac{v}{51} = \\frac{20}{3} \\implies v = 51 \\times \\frac{20}{3} = 17 \\times 20 = 340\\,\\text{m/s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two organ pipes, one closed at one end and the other open at both ends, produce $2\\,\\text{beats/s}$ when sounding their fundamental notes. The length of the open pipe is $50\\,\\text{cm}$. If the speed of sound is $340\\,\\text{m/s}$, what is the possible length of the closed pipe?",
    "options": [
      "$25.15\\,\\text{cm}$",
      "$25.00\\,\\text{cm}$",
      "$24.50\\,\\text{cm}$",
      "$26.00\\,\\text{cm}$"
    ],
    "correctAnswer": 0,
    "explanation": "Fundamental frequency of open pipe is $f_o = \\frac{v}{2L_o} = \\frac{340}{2(0.50)} = 340\\,\\text{Hz}$. Since $f_b = 2\\,\\text{Hz}$, the closed pipe fundamental frequency is $f_c = 340 \\pm 2 = 338\\,\\text{Hz}$ or $342\\,\\text{Hz}$. From $f_c = \\frac{v}{4L_c}$, for $f_c = 338\\,\\text{Hz}$, $L_c = \\frac{340}{4 \\times 338} = \\frac{340}{1352} \\approx 0.2515\\,\\text{m} = 25.15\\,\\text{cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A tuning fork $P$ of frequency $250\\,\\text{Hz}$ gives $5\\,\\text{beats/s}$ with a tuning fork $Q$. When $P$ is filed, the beat frequency increases to $7\\,\\text{beats/s}$. What is the frequency of fork $Q$?",
    "options": [
      "$245\\,\\text{Hz}$",
      "$255\\,\\text{Hz}$",
      "$250\\,\\text{Hz}$",
      "$243\\,\\text{Hz}$"
    ],
    "correctAnswer": 0,
    "explanation": "We have $|f_P - f_Q| = 5 \\implies f_Q = 250 \\pm 5 = 255\\,\\text{Hz}$ or $245\\,\\text{Hz}$. Filing $P$ increases $f_P$. If $f_Q = 245\\,\\text{Hz}$, $f_P$ was already higher than $f_Q$; increasing $f_P$ further widens the difference, increasing the beat frequency to $7\\,\\text{Hz}$. If $f_Q$ were $255\\,\\text{Hz}$, increasing $f_P$ would bring it closer to $255$, reducing the beat frequency. Hence $f_Q = 245\\,\\text{Hz}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two sonometer wires of lengths $100\\,\\text{cm}$ and $101\\,\\text{cm}$ under identical tensions produce $3\\,\\text{beats/s}$. What is the velocity of transverse waves on the wire?",
    "options": [
      "$606\\,\\text{m/s}$",
      "$303\\,\\text{m/s}$",
      "$400\\,\\text{m/s}$",
      "$200\\,\\text{m/s}$"
    ],
    "correctAnswer": 0,
    "explanation": "Frequencies are $f_1 = \\frac{v}{2(1.00)}$ and $f_2 = \\frac{v}{2(1.01)}$. Beat frequency is $f_b = f_1 - f_2 = \\frac{v}{2}\\left(1 - \\frac{1}{1.01}\\right) = \\frac{v}{2}\\left(\\frac{0.01}{1.01}\\right) = \\frac{0.01 v}{2.02} = 3\\,\\text{Hz} \\implies v = \\frac{3 \\times 2.02}{0.01} = 3 \\times 202 = 606\\,\\text{m/s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two tuning forks $A$ and $B$ sound together to produce 20 beats in 4 seconds. What is the beat frequency in hertz?",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "Beat frequency is $f_b = \\frac{\\text{total beats}}{\\text{time}} = \\frac{20}{4} = 5\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A tuning fork of frequency $300\\,\\text{Hz}$ produces $6\\,\\text{beats/s}$ with an unknown fork. When the unknown fork is loaded with wax, the beat frequency decreases to $2\\,\\text{beats/s}$. What is the frequency of the unknown fork in hertz?",
    "options": [],
    "correctAnswer": 306,
    "numericalAnswer": 306,
    "explanation": "Possible frequencies are $300 \\pm 6 = 306$ or $294\\,\\text{Hz}$. Loading with wax decreases frequency. Since the beat frequency decreases, the unknown fork's frequency must have been higher than $300\\,\\text{Hz}$, so decreasing it moves it closer to $300\\,\\text{Hz}$. Hence its frequency is $306\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two tuning forks produce beats of frequency $4\\,\\text{Hz}$. What is the time interval in seconds between two successive intensity maxima?",
    "options": [],
    "correctAnswer": 0.25,
    "numericalAnswer": 0.25,
    "explanation": "Time period between successive maxima is $T_b = \\frac{1}{f_b} = \\frac{1}{4} = 0.25\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "For the forks in the previous problem, what is the time interval in seconds between an intensity maximum and the immediately following intensity minimum?",
    "options": [],
    "correctAnswer": 0.125,
    "numericalAnswer": 0.125,
    "explanation": "Time interval between a maximum and next minimum is $\\frac{T_b}{2} = \\frac{0.25}{2} = 0.125\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two open organ pipes of lengths $50\\,\\text{cm}$ and $50.5\\,\\text{cm}$ are sounded together. If the speed of sound in air is $303\\,\\text{m/s}$, find the number of beats produced per second.",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "Frequencies are $f_1 = \\frac{v}{2L_1} = \\frac{303}{2(0.50)} = 303\\,\\text{Hz}$, and $f_2 = \\frac{v}{2L_2} = \\frac{303}{2(0.505)} = \\frac{303}{1.01} = 300\\,\\text{Hz}$. Beat frequency is $f_b = 303 - 300 = 3\\,\\text{beats/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "25 tuning forks are arranged in order of increasing frequency, each giving 3 beats per second with the next one. If the frequency of the last fork is 1.5 times that of the first fork, find the frequency of the first fork in hertz.",
    "options": [],
    "correctAnswer": 144,
    "numericalAnswer": 144,
    "explanation": "Frequency of the 25th fork is $f_{25} = f_1 + (25 - 1)(3) = f_1 + 72$. Given $f_{25} = 1.5 f_1$: $1.5 f_1 = f_1 + 72 \\implies 0.5 f_1 = 72 \\implies f_1 = \\frac{72}{0.5} = 144\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two sound waves of frequencies $400\\,\\text{Hz}$ and $402\\,\\text{Hz}$ with equal amplitude $A$ superpose. In a duration of 10 seconds, how many times does the sound intensity reach a maximum?",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "Beat frequency is $f_b = 402 - 400 = 2\\,\\text{Hz}$. In 10 seconds, the number of intensity maxima is $N = f_b \\times t = 2 \\times 10 = 20$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A tuning fork gives 4 beats per second with a $256\\,\\text{Hz}$ fork. When the first fork is loaded with wax, it gives 5 beats per second with the $256\\,\\text{Hz}$ fork. What was the initial frequency of the first fork in hertz?",
    "options": [],
    "correctAnswer": 252,
    "numericalAnswer": 252,
    "explanation": "Initial frequency is $256 \\pm 4 = 260$ or $252\\,\\text{Hz}$. Loading with wax reduces frequency. If initial frequency were $252\\,\\text{Hz}$, reducing it moves it further from $256\\,\\text{Hz}$, increasing the beat frequency to 5. If it were $260\\,\\text{Hz}$, reducing it would decrease the beat frequency. Thus the initial frequency was $252\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two tuning forks $A$ and $B$ produce 4 beats per second. On loading $A$ with wax, the number of beats per second remains 4. If the frequency of $B$ is $200\\,\\text{Hz}$, find the original frequency of $A$ in hertz.",
    "options": [],
    "correctAnswer": 204,
    "numericalAnswer": 204,
    "explanation": "Initial possibilities: $f_A = 200 \\pm 4 = 204$ or $196\\,\\text{Hz}$. Loading $A$ with wax decreases $f_A$. If $f_A$ decreases from $204\\,\\text{Hz}$ down to $196\\,\\text{Hz}$, the beat frequency $|f_A - 200|$ decreases to 0 and then increases back to 4. If $f_A$ had started at $196\\,\\text{Hz}$, decreasing it would only increase beat frequency above 4. Thus the original frequency was $204\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A string under tension produces 6 beats per second when sounded with a $400\\,\\text{Hz}$ tuning fork. When the tension in the string is slightly increased, the beat frequency becomes 3 beats per second. What was the original frequency of the string in hertz?",
    "options": [],
    "correctAnswer": 394,
    "numericalAnswer": 394,
    "explanation": "Initial frequency was $400 \\pm 6 = 406$ or $394\\,\\text{Hz}$. Increasing tension increases string frequency ($f \\propto \\sqrt{T}$). If $f_{\\text{string}}$ increases from $394\\,\\text{Hz}$, it gets closer to $400\\,\\text{Hz}$, reducing the beat frequency to 3. If it started at $406\\,\\text{Hz}$, increasing tension would widen the gap. Thus the original frequency was $394\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two sound waves are represented by $y_1 = 3\\sin(100\\pi t)$ and $y_2 = 3\\sin(104\\pi t)$. What is the beat frequency in hertz?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "$f_1 = \\frac{100\\pi}{2\\pi} = 50\\,\\text{Hz}$, $f_2 = \\frac{104\\pi}{2\\pi} = 52\\,\\text{Hz}$. The beat frequency is $f_b = 52 - 50 = 2\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In the previous problem, what is the maximum amplitude in the beat pattern in units of the single wave amplitude?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "At maximum constructive interference, $A_{\\max} = 3 + 3 = 6$, which is 2 times the single wave amplitude 3.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "10 tuning forks are arranged in increasing order of frequency, each giving 2 beats per second with the preceding one. If the frequency of the first fork is $100\\,\\text{Hz}$, what is the frequency of the 10th fork in hertz?",
    "options": [],
    "correctAnswer": 118,
    "numericalAnswer": 118,
    "explanation": "$f_{10} = f_1 + (10 - 1)(2) = 100 + 18 = 118\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two tuning forks $A$ and $B$ give 5 beats per second. A sound note of frequency $f_A$ has a wavelength of $1.20\\,\\text{m}$ in air and $f_B$ has a wavelength of $1.22\\,\\text{m}$. Find the speed of sound in air in $\\text{m/s}$.",
    "options": [],
    "correctAnswer": 366,
    "numericalAnswer": 366,
    "explanation": "$f_A - f_B = v\\left(\\frac{1}{1.20} - \\frac{1}{1.22}\\right) = v\\left(\\frac{0.02}{1.464}\\right) = 5 \\implies v = \\frac{5 \\times 1.464}{0.02} = \\frac{7.32}{0.02} = 366\\,\\text{m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A tuning fork of frequency $512\\,\\text{Hz}$ produces 4 beats per second with a vibrating wire. When the wire is slightly tightened, 2 beats per second are heard. What was the initial frequency of the wire in hertz?",
    "options": [],
    "correctAnswer": 508,
    "numericalAnswer": 508,
    "explanation": "Initial frequency was $512 \\pm 4 = 516$ or $508\\,\\text{Hz}$. Tightening increases wire frequency. If it started at $508\\,\\text{Hz}$, increasing it moves it closer to $512\\,\\text{Hz}$, decreasing beats to 2. Thus the initial frequency was $508\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two identical violin strings under identical tension have a fundamental frequency of $440\\,\\text{Hz}$. The tension in one string is increased by $2.0\\%$. What is the beat frequency heard when both strings are sounded together (rounded to one decimal place)?",
    "options": [],
    "correctAnswer": 4.4,
    "numericalAnswer": 4.4,
    "explanation": "For small changes, $\\frac{\\Delta f}{f} \\approx \\frac{1}{2}\\frac{\\Delta T}{T}$. With $\\frac{\\Delta T}{T} = 0.02$, $\\frac{\\Delta f}{f} = \\frac{1}{2}(0.02) = 0.01$. Thus $\\Delta f = 440 \\times 0.01 = 4.4\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A source of sound of frequency $600\\,\\text{Hz}$ moves at $3.4\\,\\text{m/s}$ towards a stationary wall. The speed of sound is $340\\,\\text{m/s}$. An observer standing stationary behind the source hears beats between the direct wave and the reflected wave. Find the beat frequency in hertz (rounded to one decimal place).",
    "options": [],
    "correctAnswer": 12,
    "numericalAnswer": 12,
    "explanation": "The frequency reflected by the wall is $f_{\\text{wall}} = f_0 \\left(\\frac{v}{v - u}\\right) = 600\\left(\\frac{340}{340 - 3.4}\\right) = 600\\left(\\frac{340}{336.6}\\right) \\approx 606.06\\,\\text{Hz}$. The direct frequency heard by the observer behind the receding source is $f_{\\text{direct}} = f_0 \\left(\\frac{v}{v + u}\\right) = 600\\left(\\frac{340}{340 + 3.4}\\right) = 600\\left(\\frac{340}{343.4}\\right) \\approx 594.06\\,\\text{Hz}$. The beat frequency is $f_b = 606.06 - 594.06 = 12.0\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "When two waves of frequencies $n_1 = 300\\,\\text{Hz}$ and $n_2 = 303\\,\\text{Hz}$ superpose, how many times in 1 minute does the resultant intensity reach a minimum?",
    "options": [],
    "correctAnswer": 180,
    "numericalAnswer": 180,
    "explanation": "Beat frequency is $f_b = 303 - 300 = 3\\,\\text{beats/s}$. In 1 minute ($60\\,\\text{s}$), the number of minima is $3 \\times 60 = 180$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A tuning fork $A$ of frequency $480\\,\\text{Hz}$ produces a certain number of beats per second with fork $B$. When $B$ is loaded with wax, the beat frequency remains the same. If $f_B$ was originally $484\\,\\text{Hz}$, by how many hertz was the frequency of $B$ decreased by the wax?",
    "options": [],
    "correctAnswer": 8,
    "numericalAnswer": 8,
    "explanation": "Initially $f_b = |484 - 480| = 4\\,\\text{Hz}$. Since loading with wax decreases frequency and the beat frequency remains 4, the new frequency must be $480 - 4 = 476\\,\\text{Hz}$. The decrease in frequency is $484 - 476 = 8\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two organ pipes both closed at one end of lengths $40\\,\\text{cm}$ and $40.5\\,\\text{cm}$ produce beats. If the speed of sound is $324\\,\\text{m/s}$, what is the beat frequency in hertz?",
    "options": [],
    "correctAnswer": 2.5,
    "numericalAnswer": 2.5,
    "explanation": "Fundamental frequencies are $f_1 = \\frac{v}{4L_1} = \\frac{324}{4(0.40)} = \\frac{324}{1.6} = 202.5\\,\\text{Hz}$ and $f_2 = \\frac{v}{4L_2} = \\frac{324}{4(0.405)} = \\frac{324}{1.62} = 200.0\\,\\text{Hz}$. The beat frequency is $f_b = 202.5 - 200.0 = 2.5\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Beats",
    "subTopic": "Beats",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
