module.exports = [
  {
    "type": "NUMERICAL",
    "question": "A $100\\,\\text{W}$ sodium vapor lamp radiates light of wavelength $589\\,\\text{nm}$ uniformly in all directions. How many photons are emitted per second by the lamp in units of $10^{20}\\,\\text{photons/s}$ (take $hc = 1.989 \\times 10^{-25}\\,\\text{J}\\cdot\\text{m}$)? Round to two decimal places.",
    "correctAnswer": 2.96,
    "explanation": "Energy per photon is $E = \\frac{hc}{\\lambda} = \\frac{1.989 \\times 10^{-25}}{589 \\times 10^{-9}} \\approx 3.377 \\times 10^{-19}\\,\\text{J}$. Photon emission rate is $N = \\frac{P}{E} = \\frac{100}{3.377 \\times 10^{-19}} \\approx 2.961 \\times 10^{20}\\,\\text{photons/s} \\approx 2.96 \\times 10^{20}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "For the lamp in the previous problem, at what distance from the lamp in meters is the photon flux equal to $1.0 \\times 10^{18}\\,\\text{photons/(s}\\cdot\\text{m}^2)$ (take emission rate $N = 2.96 \\times 10^{20}\\,\\text{s}^{-1}$)? Round to two decimal places.",
    "correctAnswer": 4.85,
    "explanation": "Photon flux is $\\Phi = \\frac{N}{4\\pi r^2} \\implies r = \\sqrt{\\frac{N}{4\\pi \\Phi}} = \\sqrt{\\frac{2.96 \\times 10^{20}}{4\\pi \\times 10^{18}}} = \\sqrt{\\frac{296}{12.566}} = \\sqrt{23.555} \\approx 4.853 \\approx 4.85\\,\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A laser beam of wavelength $632.8\\,\\text{nm}$ has an output power of $5.0\\,\\text{mW}$. How many photons per second are emitted by the laser in units of $10^{16}\\,\\text{photons/s}$ (take $hc = 1.989 \\times 10^{-25}\\,\\text{J}\\cdot\\text{m}$)? Round to two decimal places.",
    "correctAnswer": 1.59,
    "explanation": "Energy per photon is $E = \\frac{1.989 \\times 10^{-25}}{632.8 \\times 10^{-9}} \\approx 3.143 \\times 10^{-19}\\,\\text{J}$. Photon emission rate is $N = \\frac{5.0 \\times 10^{-3}}{3.143 \\times 10^{-19}} \\approx 1.5908 \\times 10^{16}\\,\\text{s}^{-1} \\approx 1.59 \\times 10^{16}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A monochromatic light beam of power $20\\,\\text{W}$ and wavelength $300\\,\\text{nm}$ falls on a photocell. If the quantum efficiency is $2\\%$, what is the saturation photocurrent in milliamperes (mA) (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to one decimal place.",
    "correctAnswer": 96.8,
    "explanation": "Photon energy in eV is $E = \\frac{1240}{300} \\approx 4.133\\,\\text{eV} = 6.613 \\times 10^{-19}\\,\\text{J}$. Photons per second: $N_{\\text{ph}} = \\frac{20}{6.613 \\times 10^{-19}} \\approx 3.024 \\times 10^{19}\\,\\text{s}^{-1}$. Emitted electrons per second: $N_e = 0.02 \\times 3.024 \\times 10^{19} = 6.048 \\times 10^{17}\\,\\text{s}^{-1}$. Saturation current is $I = N_e e = (6.048 \\times 10^{17})(1.6 \\times 10^{-19}) \\approx 0.0968\\,\\text{A} = 96.8\\,\\text{mA}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A light source of intensity $I = 100\\,\\text{W/m}^2$ and wavelength $400\\,\\text{nm}$ illuminates a target area of $1.0\\,\\text{cm}^2$. How many photons strike the target per second in units of $10^{16}$ (take $hc = 2.0 \\times 10^{-25}\\,\\text{J}\\cdot\\text{m}$)?",
    "correctAnswer": 2,
    "explanation": "Power on target is $P = I \\times A = 100 \\times 10^{-4} = 10^{-2}\\,\\text{W}$. Photon energy is $E = \\frac{2.0 \\times 10^{-25}}{400 \\times 10^{-9}} = 5.0 \\times 10^{-19}\\,\\text{J}$. Photons per second: $N = \\frac{10^{-2}}{5.0 \\times 10^{-19}} = 2.0 \\times 10^{16}\\,\\text{s}^{-1}$. Value is $2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the photocurrent in a photocell is $4.8\\,\\mu\\text{A}$ and its quantum efficiency is $0.5\\%$, how many photons strike the photocell per second in units of $10^{15}$ (take $e = 1.6 \\times 10^{-19}\\,\\text{C}$)?",
    "correctAnswer": 6,
    "explanation": "Rate of electron emission is $N_e = \\frac{I}{e} = \\frac{4.8 \\times 10^{-6}}{1.6 \\times 10^{-19}} = 3.0 \\times 10^{13}\\,\\text{s}^{-1}$. Rate of incident photons is $N_{\\text{ph}} = \\frac{N_e}{\\eta} = \\frac{3.0 \\times 10^{13}}{0.005} = 6.0 \\times 10^{15}\\,\\text{s}^{-1}$. Value is $6$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A point source of light is placed at a distance of $0.5\\,\\text{m}$ from a photocell, producing a saturation current of $8\\,\\text{mA}$. What will be the saturation current in $\\text{mA}$ if the distance is increased to $2.0\\,\\text{m}$?",
    "correctAnswer": 0.5,
    "explanation": "Current varies inversely with the square of distance: $I \\propto 1/r^2$. Ratio of distances is $r_2 / r_1 = 2.0 / 0.5 = 4$. Current decreases by a factor of $4^2 = 16$. New current is $\\frac{8}{16} = 0.5\\,\\text{mA}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A $60\\,\\text{W}$ light bulb radiates visible light of mean wavelength $550\\,\\text{nm}$ with an efficiency of $5\\%$. How many photons of visible light are emitted per second in units of $10^{18}\\,\\text{photons/s}$ (take $hc = 1.989 \\times 10^{-25}\\,\\text{J}\\cdot\\text{m}$)? Round to two decimal places.",
    "correctAnswer": 8.3,
    "explanation": "Useful radiated power is $P = 0.05 \\times 60 = 3.0\\,\\text{W}$. Photon energy is $E = \\frac{1.989 \\times 10^{-25}}{550 \\times 10^{-9}} \\approx 3.616 \\times 10^{-19}\\,\\text{J}$. Photon emission rate is $N = \\frac{3.0}{3.616 \\times 10^{-19}} \\approx 8.296 \\times 10^{18}\\,\\text{s}^{-1} \\approx 8.30 \\times 10^{18}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photocell delivers a saturation current of $1.0\\,\\text{mA}$ when illuminated with a laser of wavelength $400\\,\\text{nm}$. If only $1$ out of every $1000$ incident photons ejects a photoelectron, what is the power of the laser beam in watts (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to one decimal place.",
    "correctAnswer": 3.1,
    "explanation": "$N_e = \\frac{I}{e} = \\frac{10^{-3}}{1.6 \\times 10^{-19}} = 6.25 \\times 10^{15}\\,\\text{s}^{-1}$. Total incident photons per second: $N_{\\text{ph}} = 1000 N_e = 6.25 \\times 10^{18}\\,\\text{s}^{-1}$. Photon energy is $E = \\frac{1240}{400} = 3.1\\,\\text{eV} = 4.96 \\times 10^{-19}\\,\\text{J}$. Incident power is $P = N_{\\text{ph}} E = (6.25 \\times 10^{18})(4.96 \\times 10^{-19}) = 3.1\\,\\text{W}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the distance between a point light source and a photosensitive plate is reduced to one-third of its initial value, by what factor does the saturation current increase?",
    "correctAnswer": 9,
    "explanation": "By the inverse square law, $I \\propto \\frac{1}{r^2}$. If distance becomes $r/3$, intensity and saturation current increase by a factor of $3^2 = 9$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A monochromatic source of light operating at $200\\,\\text{W}$ emits $4.0 \\times 10^{20}$ photons per second. What is the wavelength of the light in nanometers (take $hc = 1.989 \\times 10^{-25}\\,\\text{J}\\cdot\\text{m}$)? Round to one decimal place.",
    "correctAnswer": 397.8,
    "explanation": "Energy per photon is $E = \\frac{P}{N} = \\frac{200}{4.0 \\times 10^{20}} = 5.0 \\times 10^{-19}\\,\\text{J}$. Wavelength is $\\lambda = \\frac{hc}{E} = \\frac{1.989 \\times 10^{-25}}{5.0 \\times 10^{-19}} = 3.978 \\times 10^{-7}\\,\\text{m} = 397.8\\,\\text{nm}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A laser emits light of frequency $5.0 \\times 10^{14}\\,\\text{Hz}$ with power $3.315\\,\\text{mW}$. How many photons per second does it emit in units of $10^{16}\\,\\text{photons/s}$ (take $h = 6.63 \\times 10^{-34}\\,\\text{J}\\cdot\\text{s}$)?",
    "correctAnswer": 1,
    "explanation": "Photon energy is $E = h\\nu = (6.63 \\times 10^{-34})(5.0 \\times 10^{14}) = 3.315 \\times 10^{-19}\\,\\text{J}$. Emission rate is $N = \\frac{P}{E} = \\frac{3.315 \\times 10^{-3}}{3.315 \\times 10^{-19}} = 1.0 \\times 10^{16}\\,\\text{s}^{-1}$. Value is $1$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photoelectric cell has a saturation photocurrent of $6.4\\,\\mu\\text{A}$. How many electrons are emitted per minute (in units of $10^{15}$)?",
    "correctAnswer": 2.4,
    "explanation": "Electrons per second: $n = \\frac{I}{e} = \\frac{6.4 \\times 10^{-6}}{1.6 \\times 10^{-19}} = 4.0 \\times 10^{13}\\,\\text{s}^{-1}$. Electrons per minute ($60\\,\\text{s}$): $N = 4.0 \\times 10^{13} \\times 60 = 2.4 \\times 10^{15}$. Value is $2.4$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A metallic plate of area $2.0\\,\\text{cm}^2$ is illuminated by radiation of intensity $1.6\\,\\text{mW/cm}^2$. The photon energy is $4.0\\,\\text{eV}$. If the quantum efficiency is $0.25\\%$, what is the photocurrent in microamperes ($\\mu\\text{A}$)?",
    "correctAnswer": 2,
    "explanation": "Power incident on plate is $P = 1.6\\,\\text{mW/cm}^2 \\times 2.0\\,\\text{cm}^2 = 3.2\\,\\text{mW} = 3.2 \\times 10^{-3}\\,\\text{J/s}$. Photon energy is $E = 4.0\\,\\text{eV} = 6.4 \\times 10^{-19}\\,\\text{J}$. Photons per second: $N_{\\text{ph}} = \\frac{3.2 \\times 10^{-3}}{6.4 \\times 10^{-19}} = 5.0 \\times 10^{15}\\,\\text{s}^{-1}$. Electrons per second: $N_e = 0.0025 \\times 5.0 \\times 10^{15} = 1.25 \\times 10^{13}\\,\\text{s}^{-1}$. Photocurrent is $I = N_e e = 1.25 \\times 10^{13} \\times 1.6 \\times 10^{-19} = 2.0 \\times 10^{-6}\\,\\text{A} = 2.0\\,\\mu\\text{A}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A $10\\,\\text{W}$ point source of light emits light of wavelength $500\\,\\text{nm}$ isotropically. What is the photon flux in units of $10^{18}\\,\\text{photons/(s}\\cdot\\text{m}^2)$ at a distance of $1.0\\,\\text{m}$ (take $hc = 1.989 \\times 10^{-25}\\,\\text{J}\\cdot\\text{m}$)? Round to two decimal places.",
    "correctAnswer": 2,
    "explanation": "Energy per photon is $E = \\frac{1.989 \\times 10^{-25}}{500 \\times 10^{-9}} = 3.978 \\times 10^{-19}\\,\\text{J}$. Total photons per second: $N = \\frac{10}{3.978 \\times 10^{-19}} \\approx 2.5138 \\times 10^{19}\\,\\text{s}^{-1}$. Flux at $r = 1\\,\\text{m}$ is $\\Phi = \\frac{N}{4\\pi r^2} = \\frac{2.5138 \\times 10^{19}}{4\\pi (1)^2} \\approx 2.0004 \\times 10^{18} \\approx 2.00 \\times 10^{18}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photocell is illuminated by light from a source placed at distance $r$. If the source is moved such that the distance is tripled, by what percentage does the saturation current decrease?",
    "correctAnswer": 88.89,
    "explanation": "New current is $I' = \\frac{I}{3^2} = \\frac{I}{9}$. Percentage decrease is $\\frac{I - I/9}{I} \\times 100\\% = \\frac{8}{9} \\times 100\\% \\approx 88.888 \\approx 88.89\\%$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A beam of light having intensity $10\\,\\text{W/m}^2$ falls on a photosensitive area of $0.01\\,\\text{m}^2$. If the light has wavelength $600\\,\\text{nm}$ and $1$ out of every $10^4$ photons emits an electron, what is the photocurrent in microamperes ($\\mu\\text{A}$) (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 4.84,
    "explanation": "Incident power is $P = 10 \\times 0.01 = 0.1\\,\\text{W}$. Photon energy in eV is $E = \\frac{1240}{600} \\approx 2.0667\\,\\text{eV} = 3.3067 \\times 10^{-19}\\,\\text{J}$. Photons per second: $N_{\\text{ph}} = \\frac{0.1}{3.3067 \\times 10^{-19}} \\approx 3.024 \\times 10^{17}\\,\\text{s}^{-1}$. Electrons emitted per second: $N_e = 3.024 \\times 10^{13}\\,\\text{s}^{-1}$. Current is $I = N_e e = 3.024 \\times 10^{13} \\times 1.6 \\times 10^{-19} = 4.838 \\times 10^{-6}\\,\\text{A} \\approx 4.84\\,\\mu\\text{A}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In a photoelectric experiment, a light source of power $P$ produces a saturation current of $2.4\\,\\text{mA}$. If the power of the source is increased by $50\\%$, what is the new saturation current in $\\text{mA}$?",
    "correctAnswer": 3.6,
    "explanation": "Saturation current is directly proportional to light power. New current is $I' = 1.5 \\times 2.4 = 3.6\\,\\text{mA}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "How many photons of red light (wavelength $663\\,\\text{nm}$) have the same energy as one photon of ultraviolet radiation of wavelength $221\\,\\text{nm}$?",
    "correctAnswer": 3,
    "explanation": "Energy $E = \\frac{hc}{\\lambda} \\propto \\frac{1}{\\lambda}$. The ratio of energies is $\\frac{E_{\\text{UV}}}{E_{\\text{red}}} = \\frac{\\lambda_{\\text{red}}}{\\lambda_{\\text{UV}}} = \\frac{663}{221} = 3$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photocell receives $5.0 \\times 10^{16}$ photons per second. If the photocurrent produced is $0.8\\,\\text{mA}$, what is the quantum efficiency of the photocell in percent?",
    "correctAnswer": 10,
    "explanation": "Electrons per second: $N_e = \\frac{0.8 \\times 10^{-3}}{1.6 \\times 10^{-19}} = 5.0 \\times 10^{15}\\,\\text{s}^{-1}$. Quantum efficiency is $\\eta = \\frac{N_e}{N_{\\text{ph}}} \\times 100\\% = \\frac{5.0 \\times 10^{15}}{5.0 \\times 10^{16}} \\times 100\\% = 10\\%$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the distance between a light source and a photoelectric cathode is decreased from $60\\,\\text{cm}$ to $30\\,\\text{cm}$, the saturation current increases by a factor of:",
    "correctAnswer": 4,
    "explanation": "Distance is halved ($r' = r/2$), so intensity increases by a factor of $(2)^2 = 4$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A monochromatic source of frequency $6.0 \\times 10^{14}\\,\\text{Hz}$ produces $2.0\\,\\text{mW}$ of radiation. How many photons does it emit per second in units of $10^{15}\\,\\text{photons/s}$ (take $h = 6.63 \\times 10^{-34}\\,\\text{J}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 5.03,
    "explanation": "Photon energy is $E = (6.63 \\times 10^{-34})(6.0 \\times 10^{14}) = 3.978 \\times 10^{-19}\\,\\text{J}$. Emission rate is $N = \\frac{2.0 \\times 10^{-3}}{3.978 \\times 10^{-19}} \\approx 5.0276 \\times 10^{15}\\,\\text{s}^{-1} \\approx 5.03 \\times 10^{15}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A metal cathode is placed at a distance of $1.5\\,\\text{m}$ from a small light bulb. When moved to a distance of $0.5\\,\\text{m}$, the saturation photocurrent becomes $27\\,\\mu\\text{A}$. What was the initial photocurrent in $\\mu\\text{A}$?",
    "correctAnswer": 3,
    "explanation": "Distance ratio is $\\frac{1.5}{0.5} = 3$. At $1.5\\,\\text{m}$, the intensity is $\\frac{1}{3^2} = \\frac{1}{9}$ of that at $0.5\\,\\text{m}$. Initial current is $\\frac{27}{9} = 3\\,\\mu\\text{A}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "The work function of a metal is $2.0\\,\\text{eV}$. What is the energy in Joules of a photon at the threshold frequency in units of $10^{-19}\\,\\text{J}$?",
    "correctAnswer": 3.2,
    "explanation": "$E_0 = \\phi = 2.0 \\times 1.6 \\times 10^{-19}\\,\\text{J} = 3.2 \\times 10^{-19}\\,\\text{J}$. Value is $3.2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A laser of power $10\\,\\text{mW}$ and wavelength $600\\,\\text{nm}$ is used to liberate photoelectrons. If the quantum efficiency is $0.1\\%$, what is the saturation current in microamperes ($\\mu\\text{A}$) (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 4.84,
    "explanation": "Photon energy in eV is $E = \\frac{1240}{600} \\approx 2.0667\\,\\text{eV} = 3.3067 \\times 10^{-19}\\,\\text{J}$. Photons per second: $N_{\\text{ph}} = \\frac{10^{-2}}{3.3067 \\times 10^{-19}} \\approx 3.024 \\times 10^{16}\\,\\text{s}^{-1}$. Rate of electrons: $N_e = 0.001 \\times 3.024 \\times 10^{16} = 3.024 \\times 10^{13}\\,\\text{s}^{-1}$. Current is $I = 3.024 \\times 10^{13} \\times 1.6 \\times 10^{-19} \\approx 4.838 \\times 10^{-6}\\,\\text{A} \\approx 4.84\\,\\mu\\text{A}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the photon flux on a photosensitive plate of area $4.0\\,\\text{cm}^2$ is $2.5 \\times 10^{16}\\,\\text{photons/(s}\\cdot\\text{m}^2)$, how many photons strike the plate every second in units of $10^{12}$?",
    "correctAnswer": 10,
    "explanation": "Area in $\\text{m}^2$ is $4.0 \\times 10^{-4}\\,\\text{m}^2$. Photons per second: $N = \\Phi \\times A = (2.5 \\times 10^{16})(4.0 \\times 10^{-4}) = 1.0 \\times 10^{13} = 10 \\times 10^{12}$. Value is $10$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A point light source of power $40\\,\\text{W}$ emits radiation of wavelength $500\\,\\text{nm}$. How many photons are emitted per second in units of $10^{20}\\,\\text{photons/s}$ (take $hc = 2.0 \\times 10^{-25}\\,\\text{J}\\cdot\\text{m}$)?",
    "correctAnswer": 1,
    "explanation": "Photon energy is $E = \\frac{2.0 \\times 10^{-25}}{500 \\times 10^{-9}} = 4.0 \\times 10^{-19}\\,\\text{J}$. Photons per second: $N = \\frac{40}{4.0 \\times 10^{-19}} = 1.0 \\times 10^{20}$. Value is $1$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "For the point source in the previous problem, what is the intensity of radiation in $\\text{W/m}^2$ at a distance of $2.0\\,\\text{m}$ (take $\\pi = 3.1416$)? Round to two decimal places.",
    "correctAnswer": 0.8,
    "explanation": "$I = \\frac{P}{4\\pi r^2} = \\frac{40}{4\\pi (2.0)^2} = \\frac{40}{16\\pi} = \\frac{2.5}{\\pi} = \\frac{2.5}{3.1416} \\approx 0.7958 \\approx 0.80\\,\\text{W/m}^2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photodiode receives $1.25 \\times 10^{14}$ photons per second and produces a current of $4.0\\,\\mu\\text{A}$. What is its quantum efficiency in percent?",
    "correctAnswer": 20,
    "explanation": "Rate of electrons: $N_e = \\frac{4.0 \\times 10^{-6}}{1.6 \\times 10^{-19}} = 2.5 \\times 10^{13}\\,\\text{s}^{-1}$. Quantum efficiency: $\\eta = \\frac{2.5 \\times 10^{13}}{1.25 \\times 10^{14}} \\times 100\\% = 20\\%$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In a photoelectric cell, if the distance of the lamp from the cathode is increased from $40\\,\\text{cm}$ to $80\\,\\text{cm}$, the saturation current drops from $12\\,\\mu\\text{A}$ to what value in $\\mu\\text{A}$?",
    "correctAnswer": 3,
    "explanation": "Doubling the distance decreases intensity and current by a factor of 4. New current is $\\frac{12}{4} = 3\\,\\mu\\text{A}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A laser beam with a cross-sectional area of $2.0\\,\\text{mm}^2$ has an intensity of $1.0 \\times 10^4\\,\\text{W/m}^2$. What is the power of the beam in milliwatts (mW)?",
    "correctAnswer": 20,
    "explanation": "Area is $A = 2.0 \\times 10^{-6}\\,\\text{m}^2$. Power is $P = I \\times A = 1.0 \\times 10^4 \\times 2.0 \\times 10^{-6} = 0.02\\,\\text{W} = 20\\,\\text{mW}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A monochromatic light source of wavelength $400\\,\\text{nm}$ has an output power of $3.1\\,\\text{W}$. How many photons does it emit in $10$ seconds in units of $10^{19}$ (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)?",
    "correctAnswer": 6.25,
    "explanation": "Photon energy: $E = \\frac{1240}{400} = 3.1\\,\\text{eV} = 4.96 \\times 10^{-19}\\,\\text{J}$. Photons per second: $N = \\frac{3.1}{4.96 \\times 10^{-19}} = 6.25 \\times 10^{18}\\,\\text{s}^{-1}$. In 10 seconds: $6.25 \\times 10^{19}$. Value is $6.25$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the rate of electron emission from a metal surface is $1.0 \\times 10^{14}\\,\\text{electrons/s}$, what is the saturation photocurrent in microamperes ($\\mu\\text{A}$)?",
    "correctAnswer": 16,
    "explanation": "$I = N_e e = 10^{14} \\times 1.6 \\times 10^{-19} = 1.6 \\times 10^{-5}\\,\\text{A} = 16\\,\\mu\\text{A}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A monochromatic light source of power $100\\,\\text{W}$ emits light of frequency $6.0 \\times 10^{14}\\,\\text{Hz}$. What is the energy of one photon in units of $10^{-19}\\,\\text{J}$ (take $h = 6.63 \\times 10^{-34}\\,\\text{J}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 3.98,
    "explanation": "$E = h\\nu = 6.63 \\times 10^{-34} \\times 6.0 \\times 10^{14} = 3.978 \\times 10^{-19}\\,\\text{J} \\approx 3.98 \\times 10^{-19}\\,\\text{J}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In a photoelectric experiment, a light source of power $10\\,\\text{W}$ placed at distance $r$ produces saturation current $I$. If a source of power $40\\,\\text{W}$ is placed at distance $2r$, what is the new saturation current in terms of $I$?",
    "correctAnswer": 1,
    "explanation": "Current is proportional to $P/r^2$. For the second setup: $\\frac{40}{(2r)^2} = \\frac{40}{4r^2} = \\frac{10}{r^2}$. The ratio is $1$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If $10^{17}$ photons strike a photosensitive surface every second and the resulting photocurrent is $3.2\\,\\text{mA}$, what is the quantum efficiency in percent?",
    "correctAnswer": 20,
    "explanation": "Rate of electrons: $N_e = \\frac{3.2 \\times 10^{-3}}{1.6 \\times 10^{-19}} = 2.0 \\times 10^{16}\\,\\text{s}^{-1}$. Quantum efficiency: $\\frac{2.0 \\times 10^{16}}{10^{17}} \\times 100\\% = 20\\%$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A laser has power $1.5\\,\\text{mW}$ at wavelength $663\\,\\text{nm}$. How many photons are emitted per second in units of $10^{15}\\,\\text{photons/s}$ (take $h = 6.63 \\times 10^{-34}\\,\\text{J}\\cdot\\text{s}$)?",
    "correctAnswer": 5,
    "explanation": "Photon energy: $E = \\frac{hc}{\\lambda} = \\frac{(6.63 \\times 10^{-34})(3.0 \\times 10^8)}{663 \\times 10^{-9}} = 3.0 \\times 10^{-19}\\,\\text{J}$. Emission rate: $N = \\frac{1.5 \\times 10^{-3}}{3.0 \\times 10^{-19}} = 5.0 \\times 10^{15}\\,\\text{s}^{-1}$. Value is $5$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A light source emits $2.5 \\times 10^{18}$ photons per second. If the target area absorbs $10\\%$ of these photons and the quantum efficiency is $2\\%$, how many photoelectrons are emitted per second in units of $10^{15}$?",
    "correctAnswer": 5,
    "explanation": "Photons reaching target: $0.10 \\times 2.5 \\times 10^{18} = 2.5 \\times 10^{17}$. Electrons emitted: $0.02 \\times 2.5 \\times 10^{17} = 5.0 \\times 10^{15}$. Value is $5$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "What is the power in milliwatts (mW) of a light beam emitting $1.0 \\times 10^{16}$ photons per second of wavelength $310\\,\\text{nm}$ (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)?",
    "correctAnswer": 6.4,
    "explanation": "Photon energy: $E = \\frac{1240}{310} = 4.0\\,\\text{eV} = 6.4 \\times 10^{-19}\\,\\text{J}$. Power: $P = 10^{16} \\times 6.4 \\times 10^{-19} = 6.4 \\times 10^{-3}\\,\\text{W} = 6.4\\,\\text{mW}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the distance between a source and a detector is doubled while the source power is increased by a factor of 8, by what factor does the intensity at the detector change?",
    "correctAnswer": 2,
    "explanation": "Intensity $I \\propto \\frac{P}{r^2}$. With $P' = 8P$ and $r' = 2r$, $I' \\propto \\frac{8P}{(2r)^2} = \\frac{8P}{4r^2} = 2\\frac{P}{r^2}$. The factor is $2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A beam of light of wavelength $500\\,\\text{nm}$ carries power $6.0\\,\\text{W}$. What is the total momentum transferred per second to a completely absorbing surface in units of $10^{-8}\\,\\text{N}$ (take $c = 3.0 \\times 10^8\\,\\text{m/s}$)?",
    "correctAnswer": 2,
    "explanation": "Force exerted on absorbing surface is $F = \\frac{P}{c} = \\frac{6.0}{3.0 \\times 10^8} = 2.0 \\times 10^{-8}\\,\\text{N}$. Value is $2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photocell is placed at distance $r$ from a point source. When the source is moved to $3r$, the photocurrent changes by what factor?",
    "correctAnswer": 0.11,
    "explanation": "Current decreases by a factor of $3^2 = 9$. The new current is $\\frac{1}{9} \\approx 0.111 \\approx 0.11$ of the original.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  }
];
