// Subtopic 5: Sum of binomial coefficients and series (30 questions: 10 MCQ, 10 AR, 10 NUM)
module.exports = [
  // --- MCQ 1 to 10 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of the double sum $\\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j}$ is equal to:",
    options: [
      "$\\frac{1}{2} \\left(2^{2n} - \\binom{2n}{n}\\right)$",
      "$2^{2n} - \\binom{2n}{n}$",
      "$\\frac{1}{2} \\left(2^{2n} + \\binom{2n}{n}\\right)$",
      "$\\frac{1}{2} \\binom{2n}{n}$"
    ],
    correctAnswer: 0,
    explanation: "Consider the square of the sum of binomial coefficients: $$\\left(\\sum_{k=0}^n \\binom{n}{k}\\right)^2 = (2^n)^2 = 2^{2n}$$. Expanding the left-hand side: $$\\sum_{k=0}^n \\binom{n}{k}^2 + 2 \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} = 2^{2n}$$. Since $\\sum_{k=0}^n \\binom{n}{k}^2 = \\binom{2n}{n}$, we obtain: $$2 \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} = 2^{2n} - \\binom{2n}{n} \\implies \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} = \\frac{1}{2} \\left(2^{2n} - \\binom{2n}{n}\\right)$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Hard",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The sum $\\sum_{0 \\le i < j \\le n} \\left(\\binom{n}{i} + \\binom{n}{j}\\right)$ is equal to:",
    options: [
      "$n 2^n$",
      "$n 2^{n-1}$",
      "$(n-1) 2^n$",
      "$(n+1) 2^{n-1}$"
    ],
    correctAnswer: 0,
    explanation: "By symmetry, each binomial coefficient $\\binom{n}{k}$ appears in the sum for each pair $(i, j)$ where either $i = k$ or $j = k$. The number of values of $j > k$ is $n - k$, and the number of values of $i < k$ is $k$. Thus, $\\binom{n}{k}$ appears $(n - k) + k = n$ times in the entire sum. Therefore: $$\\sum_{0 \\le i < j \\le n} \\left(\\binom{n}{i} + \\binom{n}{j}\\right) = \\sum_{k=0}^n n \\binom{n}{k} = n \\sum_{k=0}^n \\binom{n}{k} = n 2^n$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of the sum $\\sum_{r=0}^{n} \\frac{\\binom{n}{r}}{(r+1)(r+2)}$ is equal to:",
    options: [
      "$\\frac{2^{n+2} - n - 3}{(n+1)(n+2)}$",
      "$\\frac{2^{n+1} - n - 2}{(n+1)(n+2)}$",
      "$\\frac{2^{n+2} - 1}{(n+1)(n+2)}$",
      "$\\frac{2^n - 1}{(n+1)(n+2)}$"
    ],
    correctAnswer: 0,
    explanation: "Notice that $\\frac{1}{(r+1)(r+2)} \\binom{n}{r} = \\frac{1}{(n+1)(n+2)} \\binom{n+2}{r+2}$. Therefore: $$\\sum_{r=0}^n \\frac{\\binom{n}{r}}{(r+1)(r+2)} = \\frac{1}{(n+1)(n+2)} \\sum_{r=0}^n \\binom{n+2}{r+2} = \\frac{1}{(n+1)(n+2)} \\sum_{k=2}^{n+2} \\binom{n+2}{k}$$. The sum of all coefficients from $k=0$ to $n+2$ is $2^{n+2}$. Subtracting the terms for $k=0$ and $k=1$: $$\\sum_{k=2}^{n+2} \\binom{n+2}{k} = 2^{n+2} - \\binom{n+2}{0} - \\binom{n+2}{1} = 2^{n+2} - 1 - (n+2) = 2^{n+2} - n - 3$$. Hence, the sum is $\\frac{2^{n+2} - n - 3}{(n+1)(n+2)}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\sum_{r=0}^{n} r(n-r) \\binom{n}{r}$ is equal to:",
    options: [
      "$n(n-1) 2^{n-2}$",
      "$n(n-1) 2^{n-1}$",
      "$n^2 2^{n-2}$",
      "$n(n+1) 2^{n-2}$"
    ],
    correctAnswer: 0,
    explanation: "Using the absorption identity: $$(n-r) \\binom{n}{r} = n \\binom{n-1}{r}$$. Then: $$r (n-r) \\binom{n}{r} = r n \\binom{n-1}{r} = n(n-1) \\binom{n-2}{r-1}$$. Summing over $r$ from $1$ to $n-1$: $$\\sum_{r=1}^{n-1} n(n-1) \\binom{n-2}{r-1} = n(n-1) \\sum_{k=0}^{n-2} \\binom{n-2}{k} = n(n-1) 2^{n-2}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The sum of the coefficients of all even powers of $x$ in the expansion of $\\left(1 + x + x^2\\right)^{10}$ is:",
    options: [
      "$\\frac{3^{10} + 1}{2}$",
      "$\\frac{3^{10} - 1}{2}$",
      "$3^9$",
      "$3^{10}$"
    ],
    correctAnswer: 0,
    explanation: "Let $P(x) = (1 + x + x^2)^{10}$. The sum of the coefficients of even powers of $x$ is given by: $$\\frac{P(1) + P(-1)}{2}$$. Evaluating: $P(1) = (1 + 1 + 1)^{10} = 3^{10}$, and $P(-1) = (1 - 1 + 1)^{10} = 1^{10} = 1$. Thus, the required sum is $\\frac{3^{10} + 1}{2}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The sum $\\sum_{r=0}^{n} (-1)^r \\binom{n}{r} \\left(\\frac{1}{2}\\right)^r$ is equal to:",
    options: [
      "$\\frac{1}{2^n}$",
      "$\\frac{1}{2^{n-1}}$",
      "$0$",
      "$\\left(\\frac{3}{2}\\right)^n$"
    ],
    correctAnswer: 0,
    explanation: "Consider the binomial expansion of $(1 - x)^n = \\sum_{r=0}^n \\binom{n}{r} (-1)^r x^r$. Setting $x = \\frac{1}{2}$: $$\\left(1 - \\frac{1}{2}\\right)^n = \\sum_{r=0}^n (-1)^r \\binom{n}{r} \\left(\\frac{1}{2}\\right)^r = \\left(\\frac{1}{2}\\right)^n = \\frac{1}{2^n}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Hard",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\sum_{r=0}^{n} (r+1)^2 \\binom{n}{r}$ is equal to:",
    options: [
      "$(n^2 + 5n + 4) 2^{n-2}$",
      "$(n^2 + 3n + 2) 2^{n-2}$",
      "$(n^2 + n + 1) 2^{n-1}$",
      "$(n^2 + 4n + 4) 2^{n-2}$"
    ],
    correctAnswer: 0,
    explanation: "Write $(r+1)^2 = r^2 + 2r + 1 = r(r-1) + 3r + 1$. Then: $$\\sum_{r=0}^n (r+1)^2 \\binom{n}{r} = \\sum_{r=2}^n r(r-1) \\binom{n}{r} + 3 \\sum_{r=1}^n r \\binom{n}{r} + \\sum_{r=0}^n \\binom{n}{r}$$. Using the standard formulas: $$= n(n-1) 2^{n-2} + 3 n 2^{n-1} + 2^n = 2^{n-2} [n(n-1) + 6n + 4] = 2^{n-2} [n^2 - n + 6n + 4] = (n^2 + 5n + 4) 2^{n-2}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If $(1+x)^n = C_0 + C_1 x + C_2 x^2 + \\dots + C_n x^n$, then the value of $C_0 - 2C_1 + 3C_2 - \\dots + (-1)^n (n+1)C_n$ for $n \\ge 2$ is:",
    options: [
      "$0$",
      "$1$",
      "$-1$",
      "$2^{n-1}$"
    ],
    correctAnswer: 0,
    explanation: "Consider the series $S = \\sum_{r=0}^n (-1)^r (r+1) C_r$. We know: $$\\sum_{r=0}^n C_r x^{r+1} = x (1+x)^n$$. Differentiating with respect to $x$: $$\\sum_{r=0}^n (r+1) C_r x^r = (1+x)^n + n x (1+x)^{n-1}$$. Substitute $x = -1$: For $n \\ge 2$, $(1-1)^n + n(-1)(1-1)^{n-1} = 0 + 0 = 0$. Hence, the sum is $0$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\sum_{k=1}^{n} \\frac{k \\binom{n}{k}}{\\binom{n}{k-1}}$ is equal to:",
    options: [
      "$\\frac{n(n+1)}{2}$",
      "$\\frac{n(n-1)}{2}$",
      "$n^2$",
      "$\\frac{(n+1)^2}{2}$"
    ],
    correctAnswer: 0,
    explanation: "Using the ratio of consecutive binomial coefficients: $$\\frac{\\binom{n}{k}}{\\binom{n}{k-1}} = \\frac{n-k+1}{k}$$. Therefore: $$k \\frac{\\binom{n}{k}}{\\binom{n}{k-1}} = k \\left(\\frac{n-k+1}{k}\\right) = n - k + 1$$. Summing from $k = 1$ to $n$: $$\\sum_{k=1}^n (n - k + 1) = n + (n-1) + \\dots + 1 = \\frac{n(n+1)}{2}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Hard",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If $S_n = \\sum_{r=0}^{n} \\frac{1}{\\binom{n}{r}}$ and $T_n = \\sum_{r=0}^{n} \\frac{r}{\\binom{n}{r}}$, then $\\frac{T_n}{S_n}$ is equal to:",
    options: [
      "$\\frac{n}{2}$",
      "$\\frac{n-1}{2}$",
      "$n$",
      "$\\frac{n+1}{2}$"
    ],
    correctAnswer: 0,
    explanation: "Write $T_n = \\sum_{r=0}^n \\frac{r}{\\binom{n}{r}}$. By substituting $r = n - r$ and using $\\binom{n}{n-r} = \\binom{n}{r}$: $$T_n = \\sum_{r=0}^n \\frac{n-r}{\\binom{n}{n-r}} = \\sum_{r=0}^n \\frac{n-r}{\\binom{n}{r}} = n \\sum_{r=0}^n \\frac{1}{\\binom{n}{r}} - \\sum_{r=0}^n \\frac{r}{\\binom{n}{r}} = n S_n - T_n$$. Thus: $$2 T_n = n S_n \\implies \\frac{T_n}{S_n} = \\frac{n}{2}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- AR 11 to 20 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The sum $\\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} = \\frac{1}{2} \\left(2^{2n} - \\binom{2n}{n}\\right)$.\nReason (R): $\\left(\\sum_{r=0}^n \\binom{n}{r}\\right)^2 = \\sum_{r=0}^n \\binom{n}{r}^2 + 2 \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j}$, and $\\sum_{r=0}^n \\binom{n}{r} = 2^n$ while $\\sum_{r=0}^n \\binom{n}{r}^2 = \\binom{2n}{n}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Expanding the square of the sum of binomial coefficients gives $\\left(2^n\\right)^2 = 2^{2n} = \\sum_{r=0}^n \\binom{n}{r}^2 + 2 \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j}$. Since $\\sum_{r=0}^n \\binom{n}{r}^2 = \\binom{2n}{n}$, subtracting and dividing by 2 gives the result in (A). Both (A) and (R) are true, and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): If $S_n = \\sum_{r=0}^n \\frac{1}{\\binom{n}{r}}$ and $T_n = \\sum_{r=0}^n \\frac{r}{\\binom{n}{r}}$, then $T_n = \\frac{n}{2} S_n$.\nReason (R): $\\binom{n}{r} = \\binom{n}{n-r}$, so reversing the order of summation gives $T_n = \\sum_{r=0}^n \\frac{n-r}{\\binom{n}{r}} = n S_n - T_n$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Reversing summation indices using $\\binom{n}{r} = \\binom{n}{n-r}$ gives $T_n = \\sum_{r=0}^n \\frac{n-r}{\\binom{n}{r}} = n \\sum \\frac{1}{\\binom{n}{r}} - T_n = n S_n - T_n$. Adding $T_n$ yields $2T_n = n S_n \\implies T_n = \\frac{n}{2} S_n$. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The sum of coefficients in the expansion of $(1 - 3x + 10x^2)^n$ is $8^n$.\nReason (R): The sum of the coefficients of a polynomial $P(x)$ is found by evaluating $P(1)$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Let $P(x) = (1 - 3x + 10x^2)^n$. To find the sum of all coefficients, set $x = 1$: $P(1) = (1 - 3(1) + 10(1)^2)^n = (1 - 3 + 10)^n = 8^n$. Reason (R) states the universal property for sum of coefficients of a polynomial. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): $\\sum_{r=0}^{n} \\frac{(-1)^r \\binom{n}{r}}{r+1} = \\frac{1}{n+1}$.\nReason (R): By integration, $\\int_0^1 (1-x)^n dx = \\sum_{r=0}^n (-1)^r \\binom{n}{r} \\int_0^1 x^r dx = \\sum_{r=0}^n \\frac{(-1)^r \\binom{n}{r}}{r+1}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Directly integrating $(1-x)^n$ from $0$ to $1$: $\\int_0^1 (1-x)^n dx = \\left[-\\frac{(1-x)^{n+1}}{n+1}\\right]_0^1 = 0 - \\left(-\\frac{1}{n+1}\\right) = \\frac{1}{n+1}$. Term by term integration gives the series in (A). Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): If $C_r = \\binom{n}{r}$, then $C_0 + 3C_1 + 5C_2 + \\dots + (2n+1)C_n = (n+1) 2^n$.\nReason (R): $\\sum_{r=0}^n (2r+1) C_r = 2 \\sum_{r=0}^n r C_r + \\sum_{r=0}^n C_r = 2(n 2^{n-1}) + 2^n = (n+1) 2^n$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "We expand: $$\\sum_{r=0}^n (2r+1) C_r = 2 \\sum_{r=1}^n r C_r + \\sum_{r=0}^n C_r = 2 (n 2^{n-1}) + 2^n = n 2^n + 2^n = (n+1) 2^n$$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The sum $\\sum_{r=1}^{n} (-1)^{r-1} r^2 \\binom{n}{r} = 0$ for all $n > 2$.\nReason (R): For $(1-x)^n$, differentiating twice with respect to $x$ and setting $x = 1$ gives $n(n-1)(1-1)^{n-2} = 0$ for $n > 2$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Consider $f(x) = (1-x)^n = \\sum_{r=0}^n (-1)^r \\binom{n}{r} x^r$. Then $x f'(x) = \\sum_{r=1}^n (-1)^r r \\binom{n}{r} x^r = -n x (1-x)^{n-1}$. Differentiating again and multiplying by $x$: $x \\frac{d}{dx}[x f'(x)] = \\sum_{r=1}^n (-1)^r r^2 \\binom{n}{r} x^r$. For $n > 2$, evaluating at $x = 1$ gives $0$. Hence, $\\sum_{r=1}^n (-1)^{r-1} r^2 \\binom{n}{r} = 0$. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The value of $\\sum_{r=0}^{n} \\frac{\\binom{n}{r}}{r+1} 2^{r+1} = \\frac{3^{n+1} - 1}{n+1}$.\nReason (R): $\\int_0^2 (1+x)^n dx = \\left[\\frac{(1+x)^{n+1}}{n+1}\\right]_0^2 = \\frac{3^{n+1} - 1}{n+1}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "We know $(1+x)^n = \\sum_{r=0}^n \\binom{n}{r} x^r$. Integrating from $0$ to $2$: $$\\int_0^2 (1+x)^n dx = \\sum_{r=0}^n \\binom{n}{r} \\left[\\frac{x^{r+1}}{r+1}\\right]_0^2 = \\sum_{r=0}^n \\frac{\\binom{n}{r}}{r+1} 2^{r+1}$$. The left side evaluates directly to $\\left[\\frac{(1+x)^{n+1}}{n+1}\\right]_0^2 = \\frac{3^{n+1} - 1}{n+1}$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The sum $\\binom{n}{1} + 2\\binom{n}{2} + 3\\binom{n}{3} + \\dots + n\\binom{n}{n} = n 2^{n-1}$.\nReason (R): Differentiating $(1+x)^n = \\sum_{r=0}^n \\binom{n}{r} x^r$ with respect to $x$ yields $n(1+x)^{n-1} = \\sum_{r=1}^n r \\binom{n}{r} x^{r-1}$, and substituting $x = 1$ gives the result.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Differentiating $(1+x)^n = \\sum_{r=0}^n \\binom{n}{r} x^r$ gives $n(1+x)^{n-1} = \\sum_{r=1}^n r \\binom{n}{r} x^{r-1}$. Setting $x = 1$ yields $n(2)^{n-1} = \\sum_{r=1}^n r \\binom{n}{r}$. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The sum $\\sum_{0 \\le i < j \\le n} (i+j) \\binom{n}{i} \\binom{n}{j} = n \\left[2^{2n-1} - \\frac{1}{2} \\binom{2n}{n}\\right]$.\nReason (R): By symmetry, $\\sum_{0 \\le i < j \\le n} (i+j) \\binom{n}{i} \\binom{n}{j} = n \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Let $S = \\sum_{0 \\le i < j \\le n} (i+j) \\binom{n}{i} \\binom{n}{j}$. Substituting $i = n - i'$ and $j = n - j'$ where $0 \\le j' < i' \\le n$: $$S = \\sum_{0 \\le j' < i' \\le n} (2n - i' - j') \\binom{n}{i'} \\binom{n}{j'} = 2n \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} - S$$. Thus: $$2S = 2n \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} \\implies S = n \\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} = n \\left[\\frac{1}{2}\\left(2^{2n} - \\binom{2n}{n}\\right)\\right] = n\\left[2^{2n-1} - \\frac{1}{2}\\binom{2n}{n}\\right]$$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): In the expansion of $(1+x)^n$, $\\binom{n}{0} + \\binom{n}{2} + \\binom{n}{4} + \\dots = 2^{n-1}$.\nReason (R): Adding $(1+1)^n = 2^n$ and $(1-1)^n = 0$ eliminates all odd-indexed binomial coefficients and gives twice the sum of even-indexed coefficients.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Adding the expansions: $$(1+1)^n + (1-1)^n = 2 \\left[\\binom{n}{0} + \\binom{n}{2} + \\binom{n}{4} + \\dots\\right]$$. Since $(1-1)^n = 0$ for $n \\ge 1$, we have: $$2^n = 2 \\left[\\binom{n}{0} + \\binom{n}{2} + \\dots\\right] \\implies \\binom{n}{0} + \\binom{n}{2} + \\dots = 2^{n-1}$$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- NUM 21 to 30 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=0}^{4} (2r+1) \\binom{4}{r} = K$, find the value of $K$.",
    options: [],
    correctAnswer: 80,
    explanation: "Using the formula $\\sum_{r=0}^n (2r+1) \\binom{n}{r} = (n+1) 2^n$: For $n = 4$: $$K = (4+1) 2^4 = 5 \\times 16 = 80$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Evaluate the sum of the coefficients in the expansion of $\\left(2 - 3x + x^2\\right)^{15}$.",
    options: [],
    correctAnswer: 0,
    explanation: "The sum of coefficients is obtained by setting $x = 1$: $$\\left(2 - 3(1) + (1)^2\\right)^{15} = (2 - 3 + 1)^{15} = 0^{15} = 0$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the value of $\\sum_{r=0}^{3} \\binom{6}{2r}$.",
    options: [],
    correctAnswer: 32,
    explanation: "We have $\\sum_{r=0}^3 \\binom{6}{2r} = \\binom{6}{0} + \\binom{6}{2} + \\binom{6}{4} + \\binom{6}{6}$. This is the sum of all even-indexed binomial coefficients for $n = 6$, which equals $2^{6-1} = 2^5 = 32$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=0}^{5} \\frac{\\binom{5}{r}}{r+1} = \\frac{p}{q}$ in lowest terms ($\\gcd(p, q) = 1$), find the value of $p - q$.",
    options: [],
    correctAnswer: 19,
    explanation: "Using the formula $\\sum_{r=0}^n \\frac{\\binom{n}{r}}{r+1} = \\frac{2^{n+1}-1}{n+1}$: For $n = 5$, the sum is $\\frac{2^6 - 1}{6} = \\frac{63}{6} = \\frac{21}{2}$. Thus, in lowest terms, $p = 21, q = 2$, and $p - q = 21 - 2 = 19$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=1}^{4} r(r+1) \\binom{4}{r} = N$, find the value of $N$.",
    options: [],
    correctAnswer: 112,
    explanation: "Using $\\sum_{r=1}^n r(r+1) \\binom{n}{r} = n(n+3) 2^{n-2}$: For $n = 4$: $$N = 4(4+3) 2^{4-2} = 4 \\times 7 \\times 2^2 = 28 \\times 4 = 112$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=1}^{n} r \\binom{n}{r} = 192$, find the value of $n$.",
    options: [],
    correctAnswer: 6,
    explanation: "We have the standard identity $\\sum_{r=1}^n r \\binom{n}{r} = n 2^{n-1}$. We are given $n 2^{n-1} = 192$. For $n = 6$: $6 \\times 2^{6-1} = 6 \\times 2^5 = 6 \\times 32 = 192$. Hence, $n = 6$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the sum of the coefficients of all odd powers of $x$ in the expansion of $(1+x)^{12}$.",
    options: [],
    correctAnswer: 2048,
    explanation: "The sum of coefficients of odd powers of $x$ in $(1+x)^n$ is $2^{n-1}$. For $n = 12$, this sum is $2^{12-1} = 2^{11} = 2048$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Evaluate the double sum $\\sum_{0 \\le i < j \\le 2} \\binom{2}{i} \\binom{2}{j}$.",
    options: [],
    correctAnswer: 5,
    explanation: "Using the formula $\\sum_{0 \\le i < j \\le n} \\binom{n}{i} \\binom{n}{j} = \\frac{1}{2} \\left(2^{2n} - \\binom{2n}{n}\\right)$ with $n = 2$: $$\\frac{1}{2} \\left(2^4 - \\binom{4}{2}\\right) = \\frac{1}{2} (16 - 6) = \\frac{1}{2} (10) = 5$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Evaluate the sum $\\sum_{r=0}^{3} (-1)^r \\binom{6}{r}^2$.",
    options: [],
    correctAnswer: -210,
    explanation: "We compute each term: $\\binom{6}{0} = 1$, $\\binom{6}{1} = 6$, $\\binom{6}{2} = 15$, $\\binom{6}{3} = 20$. Thus: $$\\sum_{r=0}^3 (-1)^r \\binom{6}{r}^2 = 1^2 - 6^2 + 15^2 - 20^2 = 1 - 36 + 225 - 400 = -210$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Sum of binomial coefficients and series",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $S = \\sum_{0 \\le i < j \\le 3} \\binom{3}{i} \\binom{3}{j}$, find the value of $S$.",
    options: [],
    correctAnswer: 22,
    explanation: "Using the formula $S = \\frac{1}{2} \\left(2^{2n} - \\binom{2n}{n}\\right)$ with $n = 3$: $$S = \\frac{1}{2} \\left(2^6 - \\binom{6}{3}\\right) = \\frac{1}{2} (64 - 20) = \\frac{1}{2} (44) = 22$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  }
];
