module.exports = [
  {
    "question": "Assertion (A): Total mechanical energy of an isolated system remains constant if all internal forces are conservative and external forces do no work.\nReason (R): The work done by conservative forces equals the negative of the change in potential energy ($W_{\\text{cons}} = -\\Delta U$), leading to $\\Delta K + \\Delta U = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "From the work-energy theorem, $W_{\\text{net}} = \\Delta K$. When only conservative forces do work, $W_{\\text{cons}} = -\\Delta U$, so $\\Delta K + \\Delta U = 0 \\implies \\Delta(K + U) = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a body falls freely under gravity in a vacuum, its mechanical energy is conserved at every point of its motion.\nReason (R): Gravitational force is a conservative force, and air resistance is absent in a vacuum.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because gravity is conservative and there are no dissipative forces, potential energy lost converts directly into kinetic energy gained ($mgh + \\frac{1}{2}mv^2 = \\text{constant}$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A mass attached to an ideal horizontal spring executing simple harmonic motion has constant total mechanical energy.\nReason (R): The restoring force $F = -kx$ is a conservative force.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For an ideal spring-mass system on a frictionless surface, the only horizontal force is the conservative spring force, so $E = \\frac{1}{2}mv^2 + \\frac{1}{2}kx^2$ is strictly conserved. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a mass $m$ is gently placed on a vertical spring of constant $k$, the maximum compression produced is $\\frac{2mg}{k}$.\nReason (R): At the point of maximum compression, the kinetic energy of the mass is zero, and the loss in gravitational potential energy equals the gain in spring potential energy.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By conservation of mechanical energy: $mg x_{\\text{max}} = \\frac{1}{2}k x_{\\text{max}}^2 \\implies x_{\\text{max}} = \\frac{2mg}{k}$. (Note that equilibrium compression is $\\frac{mg}{k}$, and the mass oscillates about it). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Mechanical energy is not conserved when a block slides down a rough inclined plane.\nReason (R): Friction is a non-conservative dissipative force that converts mechanical energy into thermal energy.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The presence of friction does negative work ($W_{\\text{friction}} < 0$), decreasing the total mechanical energy ($E_f - E_i = W_{\\text{nc}} < 0$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A particle moving in a potential well $U(x)$ cannot enter regions where $U(x) > E$, where $E$ is its total mechanical energy.\nReason (R): Kinetic energy $K = E - U(x)$ must be greater than or equal to zero for physical classical motion.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $K = \\frac{1}{2}mv^2 \\ge 0$, we have $E - U(x) \\ge 0 \\implies U(x) \\le E$. The points where $U(x) = E$ are turning points where $v = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a block slides down a smooth curved track of any shape from height $h$, its speed at the bottom depends only on $h$ and not on the profile of the track.\nReason (R): The normal force exerted by the frictionless track is always perpendicular to instantaneous displacement and does zero work.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{N} \\perp d\\vec{r}$, $W_N = 0$. Gravity is path-independent, so $\\Delta K = mgh \\implies v = \\sqrt{2gh}$ regardless of track geometry. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The mechanical energy of a simple pendulum swinging in air gradually decreases with time.\nReason (R): Air drag and viscous damping continuously do negative non-conservative work on the swinging pendulum bob.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Viscous resistive forces oppose the motion ($\\vec{F}_{\\text{drag}} \\cdot d\\vec{r} < 0$), dissipating mechanical energy into heat and dampening oscillations. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an Atwood machine with a frictionless massless pulley and light string, the total mechanical energy of the two-block system is conserved.\nReason (R): Tension in the connecting string does no net work on the two-block system as a whole.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Tension does $+T d$ work on the ascending mass and $-T d$ work on the descending mass, summing to zero net internal work ($W_{\\text{tension, net}} = 0$). Gravity is the only active work-doing force, so mechanical energy is conserved. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a bomb at rest explodes into several fragments, the total mechanical kinetic energy increases.\nReason (R): Internal chemical potential energy stored in explosive bonds is released and converted into kinetic energy of the fragments.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Total mechanical kinetic energy is not conserved because non-mechanical chemical potential energy is converted into kinetic energy. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In uniform circular motion on a horizontal surface, kinetic energy and potential energy both remain constant.\nReason (R): The speed of the particle is constant and its height above the ground is constant.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Uniform circular motion has constant speed $v \\implies K = \\text{constant}$, and horizontal plane implies uniform elevation $h \\implies U = \\text{constant}$. Total mechanical energy remains constant. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): For a body thrown vertically upwards, a plot of total mechanical energy versus height is a horizontal straight line.\nReason (R): In the absence of non-conservative forces, total mechanical energy is independent of position and time.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Total mechanical energy $E = K + U = \\text{constant}$ at all heights $h$, yielding a flat horizontal line in an $E$ vs $h$ graph. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): For a body in free fall, the plot of kinetic energy versus height is a straight line with a negative slope.\nReason (R): From conservation of mechanical energy, $K(h) = E_{\\text{total}} - mgh$, which is linear in $h$ with slope $-mg$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $K + mgh = E$, $K = E - mgh$, which is an equation of a straight line $y = c - mx$ with slope $-mg$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When an external non-conservative force acts on a system, the work done by it equals the change in total mechanical energy.\nReason (R): The generalized work-energy theorem states $W_{\\text{nc}} = \\Delta E_{\\text{mech}} = \\Delta K + \\Delta U$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "From $W_{\\text{total}} = W_{\\text{cons}} + W_{\\text{nc}} = \\Delta K$, using $W_{\\text{cons}} = -\\Delta U$ gives $W_{\\text{nc}} = \\Delta K + \\Delta U = \\Delta E$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A mass suspended from a vertical spring is pulled down by distance $A$ from its equilibrium position and released. Its speed is maximum at the equilibrium position.\nReason (R): At the equilibrium position, the net force on the mass is zero, so potential energy of the spring-gravity system is at a minimum.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The effective potential energy is $U_{\\text{eff}} = \\frac{1}{2}ky^2$ where $y$ is measured from the equilibrium point. At $y = 0$, $U_{\\text{eff}}$ is minimum, which maximizes kinetic energy and speed. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If internal forces are conservative, the total mechanical energy of an isolated system is conserved even if the bodies collide elastically.\nReason (R): In an elastic collision, deformation is fully reversible and governed by conservative elastic forces.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Elastic collision forces are conservative internal interactions; no mechanical energy is permanently converted into thermal energy. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A ball thrown at an angle $\\theta$ to the horizontal with speed $u$ reaches the ground with speed $u$ (neglecting air resistance).\nReason (R): The vertical displacement of the projectile between launch and landing is zero, so change in gravitational potential energy is zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By conservation of mechanical energy: $\\frac{1}{2}m v_f^2 = \\frac{1}{2}m u^2 - mg\\Delta y$. Since $\\Delta y = 0$, $v_f = u$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The kinetic energy of a planet orbiting the Sun is maximum at perihelion (closest approach).\nReason (R): Total mechanical energy of the planet-Sun system is conserved, and gravitational potential energy $U = -\\frac{GMm}{r}$ is at its most negative (minimum) at perihelion.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $E = K + U = \\text{constant}$, when $r$ is smallest, $U$ is most negative (minimum), so $K = E - U$ reaches its maximum value. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a block slides down a smooth wedge that is free to slide on a frictionless horizontal floor, the mechanical energy of the (block + wedge) system is conserved.\nReason (R): All contact forces are normal to the surfaces and internal to the system, with zero friction anywhere.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "No non-conservative forces act on the system; the normal force between block and wedge transfers mechanical energy between them without dissipation. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A mass released from rest from a height $h$ compresses a spring of stiffness $k$ by $x$. The value of $x$ does not depend on the mass of the spring.\nReason (R): An ideal spring is assumed to be massless, having no kinetic energy of its own.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In the standard idealization, springs are massless, so all kinetic energy resides entirely in the block. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Mechanical energy is conserved during the flow of an ideal non-viscous, incompressible fluid along a streamline.\nReason (R): Bernoulli's equation is a statement of the conservation of mechanical energy per unit volume for ideal fluid flow.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Bernoulli's theorem states $P + \\frac{1}{2}\\rho v^2 + \\rho g h = \\text{constant}$, which directly represents mechanical energy conservation in fluid dynamics. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If two bodies are connected by a taut inextensible string over a fixed pulley, the sum of their kinetic energies equals the net loss of potential energy of the system.\nReason (R): The work done by string tension on the connected system is identically zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the string is inextensible, one mass displaces by $+x$ while the other displaces by $-x$. Net work done by tension is $T x - T x = 0$, so $\\Delta K_{\\text{system}} = -\\Delta U_{\\text{system}}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The kinetic energy of a body can be greater than its total mechanical energy.\nReason (R): Potential energy can have negative values, allowing $K = E - U > E$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "If $U < 0$ (such as in an attractive gravitational or electrostatic potential well), $K = E - U = E + |U| > E$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A particle subjected to a force $\\vec{F} = (y\\hat{i} + x\\hat{j})$ has conserved mechanical energy.\nReason (R): The curl of the force field $\\vec{\\nabla} \\times \\vec{F}$ is zero, meaning the force is conservative.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Here $\\frac{\\partial F_y}{\\partial x} - \\frac{\\partial F_x}{\\partial y} = \\frac{\\partial(x)}{\\partial x} - \\frac{\\partial(y)}{\\partial y} = 1 - 1 = 0$. Hence the force is conservative ($U = -xy$), and mechanical energy is conserved. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Mechanical energy is conserved when a stone is dropped into water and reaches terminal velocity.\nReason (R): The viscous buoyant force does conservative work on the stone.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Viscous resistance is a non-conservative dissipative force that converts mechanical energy into heat in the fluid. Hence mechanical energy is NOT conserved. Assertion is false.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a block of mass $m$ is dropped onto a vertical spring from height $h$, maximum velocity of the block occurs when the spring compression is $x = \\frac{mg}{k}$.\nReason (R): Maximum velocity occurs when acceleration is zero ($a = 0$), which occurs at the equilibrium position where the upward spring force balances gravity.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Acceleration is $a = g - \\frac{kx}{m}$. Velocity increases as long as $a > 0$. At $kx = mg \\implies x = \\frac{mg}{k}$, acceleration is zero and velocity reaches its maximum value. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $m = 1\\text{ kg}$ is dropped from a height $h = 0.6\\text{ m}$ onto a vertical spring of stiffness $k = 400\\text{ N/m}$. Taking $g = 10\\text{ m/s}^2$, the maximum compression $x$ of the spring is:",
    "options": [
      "$0.1\\text{ m}$",
      "$0.2\\text{ m}$",
      "$0.3\\text{ m}$",
      "$0.4\\text{ m}$"
    ],
    "correctAnswer": 1,
    "explanation": "By conservation of mechanical energy: $mg(h + x) = \\frac{1}{2}kx^2$. Substituting values: $10(0.6 + x) = 200 x^2 \\implies 6 + 10x = 200x^2 \\implies 200x^2 - 10x - 6 = 0 \\implies 100x^2 - 5x - 3 = 0$. Factoring: $(20x - 3)(5x + 1) = 0 \\implies x = 0.15\\text{ m}$. Wait, let's recheck: if x = 0.2 m, 100(0.04) - 5(0.2) - 3 = 4 - 1 - 3 = 0! Yes! $(5x - 1)(20x + 3) = 100x^2 + 15x - 20x - 3 = 100x^2 - 5x - 3 = 0$. Thus $5x - 1 = 0 \\implies x = 0.2\\text{ m}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $m$ moves along the x-axis under a potential energy $U(x) = 20 + (x - 2)^2$ (in Joules). If the total mechanical energy of the particle is $E = 36\\text{ J}$, the maximum speed of the particle in terms of $m$ is:",
    "options": [
      "$\\sqrt{\\frac{16}{m}}$",
      "$\\sqrt{\\frac{32}{m}}$",
      "$\\sqrt{\\frac{48}{m}}$",
      "$\\sqrt{\\frac{64}{m}}$"
    ],
    "correctAnswer": 1,
    "explanation": "Minimum potential energy occurs at $x = 2\\text{ m}$, where $U_{\\text{min}} = 20\\text{ J}$. Maximum kinetic energy is $K_{\\text{max}} = E - U_{\\text{min}} = 36 - 20 = 16\\text{ J}$. Therefore $\\frac{1}{2}m v_{\\text{max}}^2 = 16 \\implies v_{\\text{max}} = \\sqrt{\\frac{32}{m}}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $m$ slides from rest down a frictionless track that ends in a horizontal spring of stiffness $k$. If the initial vertical height is $h$, the maximum compression $x$ of the spring is:",
    "options": [
      "$\\sqrt{\\frac{mgh}{k}}$",
      "$\\sqrt{\\frac{2mgh}{k}}$",
      "$\\frac{mgh}{k}$",
      "$\\frac{2mgh}{k}$"
    ],
    "correctAnswer": 1,
    "explanation": "Since the track and horizontal surface are frictionless, the initial gravitational potential energy is fully converted into elastic potential energy of the compressed spring: $mgh = \\frac{1}{2}kx^2 \\implies x = \\sqrt{\\frac{2mgh}{k}}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of bob mass $m$ and string length $L$ is displaced by an angle $\\theta_0$ from the vertical and released from rest. The kinetic energy of the bob at the lowest point is:",
    "options": [
      "$mgL\\sin\\theta_0$",
      "$mgL\\cos\\theta_0$",
      "$mgL(1 - \\cos\\theta_0)$",
      "$mgL(1 - \\sin\\theta_0)$"
    ],
    "correctAnswer": 2,
    "explanation": "The vertical distance descended by the bob is $h = L - L\\cos\\theta_0 = L(1 - \\cos\\theta_0)$. By conservation of mechanical energy, the kinetic energy at the bottom equals the loss in potential energy: $K = mgh = mgL(1 - \\cos\\theta_0)$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $2\\text{ kg}$ is pressed against a horizontal spring of force constant $k = 800\\text{ N/m}$, compressing it by $0.1\\text{ m}$. When released on a frictionless surface, the speed of the block as it separates from the spring is:",
    "options": [
      "$1\\text{ m/s}$",
      "$2\\text{ m/s}$",
      "$4\\text{ m/s}$",
      "$8\\text{ m/s}$"
    ],
    "correctAnswer": 1,
    "explanation": "Conservation of energy: $\\frac{1}{2}mv^2 = \\frac{1}{2}kx^2 \\implies v = x\\sqrt{\\frac{k}{m}} = 0.1\\sqrt{\\frac{800}{2}} = 0.1\\sqrt{400} = 0.1 \\times 20 = 2\\text{ m/s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A bullet of mass $m$ moving horizontally with velocity $v$ penetrates a wooden block of mass $M$ resting on a smooth surface and gets embedded. The fraction of initial mechanical energy lost is:",
    "options": [
      "$\\frac{m}{M+m}$",
      "$\\frac{M}{M+m}$",
      "$\\frac{M}{m}$",
      "$\\frac{m}{M}$"
    ],
    "correctAnswer": 1,
    "explanation": "Initial kinetic energy is $K_i = \\frac{1}{2}mv^2$. Final kinetic energy is $K_f = \\frac{1}{2}(M+m)V^2 = \\frac{1}{2}(M+m)\\left(\\frac{mv}{M+m}\\right)^2 = \\frac{m}{M+m}K_i$. Fraction lost is $\\frac{K_i - K_f}{K_i} = 1 - \\frac{m}{M+m} = \\frac{M}{M+m}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A bead of mass $m$ slides down a smooth vertical wire bent in the shape of a parabola $y = c x^2$ under gravity ($g$). If released from rest at height $y = H$, its speed at the origin $(0, 0)$ is:",
    "options": [
      "$\\sqrt{gH}$",
      "$\\sqrt{2gH}$",
      "$2\\sqrt{gH}$",
      "$\\sqrt{\\frac{gH}{c}}$"
    ],
    "correctAnswer": 1,
    "explanation": "Since the wire is frictionless, the constraint force does zero work. Mechanical energy is conserved: $mgH = \\frac{1}{2}mv^2 \\implies v = \\sqrt{2gH}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body of mass $2\\text{ kg}$ is dropped from a height of $45\\text{ m}$. Taking $g = 10\\text{ m/s}^2$ and neglecting air resistance, the speed of the body when it reaches the ground in $\\text{m/s}$ is:",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "$v = \\sqrt{2gh} = \\sqrt{2 \\times 10 \\times 45} = \\sqrt{900} = 30\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A spring of stiffness $k = 200\\text{ N/m}$ is compressed by $0.2\\text{ m}$. The kinetic energy acquired by a block of mass $1\\text{ kg}$ when released from this spring on a smooth horizontal table in Joules is:",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$K = \\frac{1}{2}kx^2 = \\frac{1}{2}(200)(0.2)^2 = 100 \\times 0.04 = 4\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A pendulum bob of mass $0.5\\text{ kg}$ is released from a height of $1.8\\text{ m}$ above its lowest point. Taking $g = 10\\text{ m/s}^2$, the speed of the bob at the lowest point in $\\text{m/s}$ is:",
    "options": [],
    "correctAnswer": 6,
    "numericalAnswer": 6,
    "explanation": "$v = \\sqrt{2gh} = \\sqrt{2 \\times 10 \\times 1.8} = \\sqrt{36} = 6\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $1\\text{ kg}$ moves under a conservative force with potential energy $U(x) = x^2 - 4x + 7$ (in Joules). If its total mechanical energy is $12\\text{ J}$, its maximum kinetic energy in Joules is:",
    "options": [],
    "correctAnswer": 9,
    "numericalAnswer": 9,
    "explanation": "Minimum potential energy is at $x = 2\\text{ m}$, where $U_{\\text{min}} = 2^2 - 4(2) + 7 = 4 - 8 + 7 = 3\\text{ J}$. Maximum kinetic energy is $K_{\\text{max}} = E - U_{\\text{min}} = 12 - 3 = 9\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $2\\text{ kg}$ moving at $4\\text{ m/s}$ on a smooth surface collides with an uncompressed horizontal spring of stiffness $k = 32\\text{ N/m}$. The maximum compression of the spring in meters is:",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$\\frac{1}{2}kx^2 = \\frac{1}{2}mv^2 \\implies x = v\\sqrt{\\frac{m}{k}} = 4\\sqrt{\\frac{2}{32}} = 4\\sqrt{\\frac{1}{16}} = 4 \\times \\frac{1}{4} = 1\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A ball of mass $0.1\\text{ kg}$ is projected upwards with velocity $20\\text{ m/s}$. Taking $g = 10\\text{ m/s}^2$, its potential energy in Joules at the maximum height (taking ground as zero reference) is:",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "At maximum height, all initial kinetic energy is converted into potential energy: $U = K_i = \\frac{1}{2}mv^2 = \\frac{1}{2}(0.1)(20^2) = 0.05 \\times 400 = 20\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $1\\text{ kg}$ is dropped from a height of $2\\text{ m}$ above the uncompressed top of a vertical spring of stiffness $k = 200\\text{ N/m}$. Taking $g = 10\\text{ m/s}^2$, the maximum compression of the spring in centimeters is:",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "By energy conservation: $mg(h + x) = \\frac{1}{2}kx^2 \\implies 10(2 + x) = 100x^2 \\implies 10x^2 - x - 2 = 0$. Factoring gives $(2x - 1)(5x + 2) = 0 \\implies x = 0.5\\text{ m} = 50\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in a force field where $U(x) = 4x^2 - 16x$ Joules. If the particle is released from rest at $x = 0$, the maximum position $x$ in meters reached by the particle is:",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "At $x = 0$, $E = U(0) = 0\\text{ J}$. At turning points, $K = 0 \\implies U(x) = E \\implies 4x^2 - 16x = 0 \\implies 4x(x - 4) = 0$. The particle moves between $x = 0$ and $x = 4\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body of mass $4\\text{ kg}$ is attached to a vertical spring. When released from rest from the uncompressed state, the maximum elongation of the spring is $0.2\\text{ m}$. Taking $g = 10\\text{ m/s}^2$, the force constant of the spring in $\\text{N/m}$ is:",
    "options": [],
    "correctAnswer": 400,
    "numericalAnswer": 400,
    "explanation": "Maximum elongation is $x_{\\text{max}} = \\frac{2mg}{k} \\implies 0.2 = \\frac{2 \\times 4 \\times 10}{k} = \\frac{80}{k} \\implies k = \\frac{80}{0.2} = 400\\text{ N/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A cart of mass $50\\text{ kg}$ moving at $10\\text{ m/s}$ along a smooth horizontal track enters an inclined ramp. Taking $g = 10\\text{ m/s}^2$, the maximum vertical height in meters reached by the cart before sliding back is:",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "By conservation of energy: $\\frac{1}{2}mv^2 = mgh \\implies h = \\frac{v^2}{2g} = \\frac{10^2}{2 \\times 10} = \\frac{100}{20} = 5\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A simple pendulum of length $1.25\\text{ m}$ has a bob of mass $0.2\\text{ kg}$. If given a horizontal velocity of $5\\text{ m/s}$ at the bottom, taking $g = 10\\text{ m/s}^2$, the height in meters to which the bob rises before momentarily stopping is:",
    "options": [],
    "correctAnswer": 1.25,
    "numericalAnswer": 1.25,
    "explanation": "$h = \\frac{v^2}{2g} = \\frac{5^2}{2 \\times 10} = \\frac{25}{20} = 1.25\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two blocks of masses $m_1 = 3\\text{ kg}$ and $m_2 = 1\\text{ kg}$ are connected by a light string passing over a frictionless pulley. If the system is released from rest, taking $g = 10\\text{ m/s}^2$, the total kinetic energy of the system in Joules after $m_1$ falls through a distance of $2\\text{ m}$ is:",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "When $m_1$ falls by $h = 2\\text{ m}$, $m_2$ rises by $h = 2\\text{ m}$. Loss in potential energy is $\\Delta U = m_1 gh - m_2 gh = (3 - 1)(10)(2) = 2 \\times 20 = 40\\text{ J}$. By energy conservation, total kinetic energy is $K = 40\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $1\\text{ kg}$ slides down a smooth curved incline from height $h = 5\\text{ m}$ and compresses a horizontal spring of stiffness $k = 100\\text{ N/m}$. Taking $g = 10\\text{ m/s}^2$, the maximum compression of the spring in meters is:",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$mgh = \\frac{1}{2}kx^2 \\implies 1 \\times 10 \\times 5 = \\frac{1}{2}(100)x^2 \\implies 50 = 50x^2 \\implies x = 1\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $2\\text{ kg}$ moves along the x-axis with potential energy $U(x) = 10x^2$ Joules. If its total mechanical energy is $40\\text{ J}$, the distance between its turning points in meters is:",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "Turning points occur where $U(x) = E \\implies 10x^2 = 40 \\implies x^2 = 4 \\implies x = \\pm 2\\text{ m}$. The distance between turning points is $2 - (-2) = 4\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A vertical spring of constant $k = 500\\text{ N/m}$ is compressed by $0.2\\text{ m}$. A ball of mass $0.5\\text{ kg}$ is placed on it and released. Taking $g = 10\\text{ m/s}^2$, the maximum height above the release point reached by the ball in meters is:",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "Initial spring energy is $E = \\frac{1}{2}kx^2 = \\frac{1}{2}(500)(0.2)^2 = 250 \\times 0.04 = 10\\text{ J}$. At maximum height, $mgh = 10 \\implies 0.5 \\times 10 \\times h = 10 \\implies 5h = 10 \\implies h = 2\\text{ m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $2\\text{ kg}$ is released from rest on a smooth inclined plane of angle $30^\\circ$. Taking $g = 10\\text{ m/s}^2$, its kinetic energy in Joules after sliding a distance of $4\\text{ m}$ along the plane is:",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "Vertical height fallen is $h = s\\sin 30^\\circ = 4 \\times 0.5 = 2\\text{ m}$. By conservation of energy, $K = mgh = 2 \\times 10 \\times 2 = 40\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $2\\text{ kg}$ is projected horizontally from the top of a tower of height $20\\text{ m}$ with speed $15\\text{ m/s}$. Taking $g = 10\\text{ m/s}^2$, its kinetic energy upon striking the ground in Joules is:",
    "options": [],
    "correctAnswer": 625,
    "numericalAnswer": 625,
    "explanation": "By conservation of mechanical energy: $K_f = K_i + mgh = \\frac{1}{2}(2)(15^2) + 2(10)(20) = 225 + 400 = 625\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body of mass $3\\text{ kg}$ attached to a spring of stiffness $k = 300\\text{ N/m}$ oscillates horizontally on a smooth floor. If its maximum speed is $2\\text{ m/s}$, the amplitude of oscillation in centimeters is:",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$\\frac{1}{2}kA^2 = \\frac{1}{2}mv_{\\text{max}}^2 \\implies A = v_{\\text{max}}\\sqrt{\\frac{m}{k}} = 2\\sqrt{\\frac{3}{300}} = 2\\sqrt{\\frac{1}{100}} = 0.2\\text{ m} = 20\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A block of mass $0.5\\text{ kg}$ is released from rest from a height of $8\\text{ m}$ on a frictionless curved track. Taking $g = 10\\text{ m/s}^2$, the speed of the block in $\\text{m/s}$ when it reaches a height of $3\\text{ m}$ is:",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "Vertical drop is $\\Delta h = 8 - 3 = 5\\text{ m}$. Speed is $v = \\sqrt{2g\\Delta h} = \\sqrt{2 \\times 10 \\times 5} = \\sqrt{100} = 10\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $1\\text{ kg}$ moves in a potential field $U(x) = 25 - x^2$ Joules for $|x| \\le 5\\text{ m}$, and $U(x) = 0$ for $|x| > 5\\text{ m}$. The minimum mechanical energy in Joules required for a particle starting from $x = 5\\text{ m}$ to pass over the potential barrier at the origin is:",
    "options": [],
    "correctAnswer": 25,
    "numericalAnswer": 25,
    "explanation": "The maximum of the potential barrier occurs at $x = 0$, where $U_{\\text{max}} = 25\\text{ J}$. To cross this barrier, the total mechanical energy must be at least $E_{\\text{min}} = U_{\\text{max}} = 25\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Conservation of mechanical energy",
    "chapter": "Work, Energy, and Power",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
