module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The total electric flux through any closed Gaussian surface depends solely on the net charge enclosed within that surface.\nReason (R): Gauss's law states that $\\oint \\vec{E}\\cdot d\\vec{A} = \\frac{Q_{enclosed}}{\\varepsilon_0}$, which is completely independent of charges situated outside the Gaussian surface.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By Gauss's law, any field line originating from an external charge that enters the closed surface must also exit it, contributing zero net flux. Only enclosed charges yield a non-zero net flux. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Although charges outside a closed Gaussian surface do not contribute to the total net electric flux, they do contribute to the electric field at individual points on the surface.\nReason (R): The electric field $\\vec{E}$ in the integral $\\oint \\vec{E}\\cdot d\\vec{A}$ represents the total resultant electric field produced by all charges present in the universe, both inside and outside the surface.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In $\\oint \\vec{E}\\cdot d\\vec{A} = \\frac{Q_{enc}}{\\varepsilon_0}$, the integrand $\\vec{E}$ is the net vector field due to all charges, while the integrated scalar flux over the whole boundary isolates $Q_{enc}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric flux through one face of a cube when a point charge $q$ is placed at its geometric center is $\\frac{q}{6\\varepsilon_0}$.\nReason (R): By cubic symmetry, the total flux $\\frac{q}{\\varepsilon_0}$ is distributed equally across all six identical square faces of the cube.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because all 6 faces are equidistant and symmetrically placed relative to the central charge, $\\Phi_{face} = \\frac{1}{6}\\Phi_{total} = \\frac{q}{6\\varepsilon_0}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When a point charge $q$ is placed at one corner of a cube, the total electric flux emerging through that cube is $\\frac{q}{8\\varepsilon_0}$.\nReason (R): Eight identical cubes sharing the common corner are required to completely enclose the charge $q$ symmetrically.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By constructing 8 identical adjacent cubes meeting at the corner, the charge is placed at the center of the composite larger cube of flux $\\frac{q}{\\varepsilon_0}$. Each small cube receives $\\frac{1}{8}\\frac{q}{\\varepsilon_0}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When a point charge $q$ is placed at the corner of a cube, the electric flux through each of the three adjacent faces meeting at that corner is zero.\nReason (R): For the three faces meeting at the corner, the electric field lines lie parallel to the plane of each face, making $\\vec{E} \\perp \\hat{n}$, so $\\vec{E}\\cdot d\\vec{A} = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Electric field vectors radiating from the corner graze across the adjacent surfaces without penetrating them, so $\\Phi = 0$ for all three adjoining faces. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field inside a uniformly charged thin spherical shell of radius $R$ is zero everywhere.\nReason (R): A concentric spherical Gaussian surface of radius $r < R$ inside the shell encloses zero net electric charge: $Q_{enc} = 0$, giving $\\oint \\vec{E}\\cdot d\\vec{A} = 0 \\implies E = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since all charge resides on the outer surface of the shell, any internal Gaussian sphere has $Q_{enc} = 0$, so $E(r) = 0$ for all $r < R$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field outside a uniformly charged spherical shell at distance $r > R$ is identical to that of a point charge of the same total charge placed at the center.\nReason (R): Applying Gauss's law to a sphere of radius $r > R$ gives $E(4\\pi r^2) = \\frac{Q}{\\varepsilon_0} \\implies E = \\frac{1}{4\\pi\\varepsilon_0}\\frac{Q}{r^2}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Spherical symmetry guarantees that the external field behaves as though all charge $Q$ were concentrated at the center: $E = \\frac{kQ}{r^2}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Inside a uniformly charged non-conducting solid sphere of radius $R$ and total charge $Q$, the electric field increases linearly with distance from the center: $E(r) \\propto r$.\nReason (R): A Gaussian sphere of radius $r < R$ encloses a charge $Q_{enc} = Q\\left(\\frac{r^3}{R^3}\\right)$, and Gauss's law yields $E(4\\pi r^2) = \\frac{Q r^3}{\\varepsilon_0 R^3} \\implies E(r) = \\frac{Q r}{4\\pi\\varepsilon_0 R^3}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The enclosed charge grows with volume as $r^3$, while surface area grows as $r^2$, resulting in $E(r) = \\frac{kQr}{R^3} \\propto r$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field inside a spherical cavity carved inside a uniformly charged solid sphere with charge density $\\rho$ is uniform.\nReason (R): The electric field at any point inside the cavity is the vector difference of the field due to the entire solid sphere $\\vec{E}_1 = \\frac{\\rho}{3\\varepsilon_0}\\vec{r}_1$ and the field due to the removed cavity sphere $\\vec{E}_2 = \\frac{\\rho}{3\\varepsilon_0}\\vec{r}_2$, yielding $\\vec{E}_{cavity} = \\frac{\\rho}{3\\varepsilon_0}(\\vec{r}_1 - \\vec{r}_2) = \\frac{\\rho}{3\\varepsilon_0}\\vec{a}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{r}_1 - \\vec{r}_2 = \\vec{a}$ (the constant vector connecting the center of the sphere to the center of the cavity), $\\vec{E} = \\frac{\\rho}{3\\varepsilon_0}\\vec{a}$ is constant in both magnitude and direction everywhere within the cavity. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Gauss's law is an immediate consequence of the inverse-square nature of Coulomb's law.\nReason (R): The solid angle subtended by any closed surface at an interior point is $4\\pi\\text{ steradians}$, which cancels the $r^2$ dependence in the denominator of Coulomb's law.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Flux element is $d\\Phi = \\frac{kq}{r^2} dA\\cos\\theta = kq\\, d\\Omega$. Integrating over the full sphere gives $\\Phi = kq(4\\pi) = \\frac{q}{4\\pi\\varepsilon_0}(4\\pi) = \\frac{q}{\\varepsilon_0}$. If Coulomb's law were not inverse-square, Gauss's law would fail. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If a closed Gaussian surface encloses zero net charge, the electric field must be zero everywhere on the surface.\nReason (R): Gauss's law states that $\\oint \\vec{E}\\cdot d\\vec{A} = \\frac{Q_{enclosed}}{\\varepsilon_0}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: when an external charge is placed near a closed surface, $Q_{enc} = 0$ so net flux is zero, but the electric field $\\vec{E}$ on the surface is definitely non-zero. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Gauss's law cannot be used to calculate the electric field of an electric dipole.\nReason (R): Gauss's law is always physically valid, but for low-symmetry charge distributions like a dipole, $\\vec{E}$ cannot be factored out of the surface integral $\\oint \\vec{E}\\cdot d\\vec{A}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Gauss's law remains true, but without spherical, cylindrical, or planar symmetry, it does not provide a practical algebraic shortcut to find $\\vec{E}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric flux through a hemispherical surface of radius $R$ with a point charge $q$ placed at its open circular base center is $\\frac{q}{2\\varepsilon_0}$.\nReason (R): A full sphere centered at the charge would enclose the charge completely with flux $\\frac{q}{\\varepsilon_0}$, and by symmetry the hemisphere intercepts exactly half of that flux.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the charge lies on the plane of the base, half of the radially outward field lines cross the upper curved hemisphere, giving $\\Phi = \\frac{q}{2\\varepsilon_0}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If the radius of a Gaussian sphere enclosing a point charge is doubled, the electric flux through the sphere remains unchanged.\nReason (R): The electric field decreases by a factor of 4 ($E \\propto 1/r^2$) while the surface area increases by a factor of 4 ($A = 4\\pi r^2$), leaving the product $EA$ invariant.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By Gauss's law, flux depends strictly on enclosed charge $\\Phi = Q_{enc}/\\varepsilon_0$, independent of the radius of the Gaussian surface. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field due to an infinite cylinder of uniform charge density $\\rho$ and radius $R$ at a point inside ($r < R$) is $E(r) = \\frac{\\rho r}{2\\varepsilon_0}$.\nReason (R): Applying Gauss's law to a coaxial cylinder of radius $r < R$ and length $L$ yields $E(2\\pi r L) = \\frac{\\rho (\\pi r^2 L)}{\\varepsilon_0} \\implies E = \\frac{\\rho r}{2\\varepsilon_0}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Gaussian cylindrical surface has curved area $2\\pi r L$ and enclosed charge $\\rho \\pi r^2 L$, directly yielding $E = \\frac{\\rho r}{2\\varepsilon_0}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A point charge $q$ is placed at distance $d$ directly above the center of a square plate of side $2d$. The electric flux through the square is $\\frac{q}{6\\varepsilon_0}$.\nReason (R): The square plate forms one of the six faces of a symmetric cube of side $2d$ centered at the charge.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Constructing a cube of side $2d$ with the charge at its center, the plate is exactly one face of the cube. Total flux through the cube is $\\frac{q}{\\varepsilon_0}$, so the flux through the plate is $\\frac{q}{6\\varepsilon_0}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The divergence of the electrostatic field $\\vec{\\nabla}\\cdot\\vec{E}$ at a point in vacuum free of charges is zero.\nReason (R): The differential form of Gauss's law is $\\vec{\\nabla}\\cdot\\vec{E} = \\frac{\\rho}{\\varepsilon_0}$, which evaluates to zero where volume charge density $\\rho = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In charge-free space, $\\rho = 0$, so Maxwell's first equation reduces to $\\vec{\\nabla}\\cdot\\vec{E} = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If a conductor carries an excess net charge $Q$, all the excess charge must reside exclusively on its outer surface in electrostatic equilibrium.\nReason (R): Inside the conducting material $\\vec{E} = 0$, so any Gaussian surface drawn entirely within the conducting material encloses zero net charge by Gauss's law.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{E} = 0$ everywhere inside the bulk of a conductor, $\\oint \\vec{E}\\cdot d\\vec{A} = 0 \\implies Q_{enc} = 0$. Hence no net charge can reside in the interior. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field just outside the surface of a charged conductor is twice as large as the electric field near an infinite non-conducting sheet carrying the same surface charge density $\\sigma$.\nReason (R): For a conducting surface, all field lines emerge outward on one side because the interior field is zero ($E = \\frac{\\sigma}{\\varepsilon_0}$), whereas for a thin non-conducting sheet, field lines emerge symmetrically from both sides ($E = \\frac{\\sigma}{2\\varepsilon_0}$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "A non-conducting sheet sends flux through two faces ($2EA = \\frac{\\sigma A}{\\varepsilon_0} \\implies E = \\frac{\\sigma}{2\\varepsilon_0}$), while a conductor has zero internal flux ($EA = \\frac{\\sigma A}{\\varepsilon_0} \\implies E = \\frac{\\sigma}{\\varepsilon_0}$). (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A spherical Gaussian surface encloses a point charge. If the charge is shifted away from the center to an eccentric point, the total electric flux through the surface changes.\nReason (R): Gauss's law states that total flux depends only on the magnitude of the enclosed charge, not on its position within the surface.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: as long as the charge remains inside the boundary, total flux $\\Phi = \\frac{q}{\\varepsilon_0}$ is invariant (though local field values on the surface change). Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electric flux through a closed surface can be negative.\nReason (R): If the net charge enclosed within the surface is negative ($Q_{enc} < 0$), more electric field lines enter the surface than leave it, making $\\oint \\vec{E}\\cdot d\\vec{A} < 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Field lines ending on negative interior charges point opposite to the outward surface normal, giving negative net flux. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field on the surface of a uniformly charged conducting sphere of radius $R$ and charge $Q$ is discontinuous.\nReason (R): The electric field drops abruptly from $E = \\frac{kQ}{R^2} = \\frac{\\sigma}{\\varepsilon_0}$ just outside the surface to $E = 0$ just inside the surface.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The presence of a surface charge density $\\sigma$ causes a step discontinuity in the normal component of the electric field: $\\Delta E_n = \\frac{\\sigma}{\\varepsilon_0}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric flux through a cube of side $a$ placed in a uniform electric field $\\vec{E} = E_0\\hat{i}$ is zero.\nReason (R): The electric field lines entering the left face of the cube emerge completely through the right face, and no charge is enclosed within the cube.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\Phi_{in} = -E_0 a^2$ and $\\Phi_{out} = +E_0 a^2$, giving net flux $\\Phi = 0$, consistent with $Q_{enc} = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In applying Gauss's law, the chosen Gaussian surface must be a physical boundary made of a real material.\nReason (R): A Gaussian surface is a purely hypothetical mathematical surface chosen for convenience to evaluate flux.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: a Gaussian surface is completely imaginary and need not correspond to any physical material boundary. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The total electric flux emerging from an isolated charge of $q = 8.854\\mu\\text{C}$ in vacuum is $10^6\\text{ N}\\cdot\\text{m}^2/\\text{C}$.\nReason (R): By Gauss's law, $\\Phi = \\frac{q}{\\varepsilon_0} = \\frac{8.854 \\times 10^{-6}\\text{ C}}{8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)} = 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Evaluating $\\frac{q}{\\varepsilon_0}$ yields exactly $10^6\\text{ V}\\cdot\\text{m}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Gauss's law cannot be applied to calculate the electric field inside a non-spherical charged body without high symmetry.\nReason (R): Gauss's law is valid for any closed surface regardless of shape or charge symmetry, but determining $\\vec{E}$ requires geometric symmetry where $E$ is constant over the integration surface.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Gauss's law is universally true, but without symmetry, $\\vec{E}$ cannot be isolated from the surface integral. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge $q$ is placed at the center of a cube of side $L$. The electric flux emerging through any one of the six faces of the cube is:",
    "options": [
      "$\\frac{q}{6\\varepsilon_0}$",
      "$\\frac{q}{\\varepsilon_0}$",
      "$\\frac{q}{24\\varepsilon_0}$",
      "$\\frac{q}{8\\varepsilon_0}$"
    ],
    "correctAnswer": 0,
    "explanation": "Total flux through the cube is $\\Phi = \\frac{q}{\\varepsilon_0}$. By cubic symmetry, all 6 faces receive identical flux, so $\\Phi_{face} = \\frac{q}{6\\varepsilon_0}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge $q$ is placed at one corner of a cube. What is the electric flux through each of the three faces that DO NOT touch this corner?",
    "options": [
      "$\\frac{q}{24\\varepsilon_0}$",
      "$\\frac{q}{8\\varepsilon_0}$",
      "$\\frac{q}{6\\varepsilon_0}$",
      "$\\frac{q}{12\\varepsilon_0}$"
    ],
    "correctAnswer": 0,
    "explanation": "Total flux through the cube is $\\frac{q}{8\\varepsilon_0}$. The 3 faces meeting at the corner have zero flux because field lines are parallel to them. The remaining flux $\\frac{q}{8\\varepsilon_0}$ is divided equally among the 3 opposite faces: $\\frac{1}{3}\\left(\\frac{q}{8\\varepsilon_0}\\right) = \\frac{q}{24\\varepsilon_0}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A charge $q$ is placed at the center of the open circular base of a hemisphere of radius $R$. The electric flux through the curved surface of the hemisphere is:",
    "options": [
      "$\\frac{q}{2\\varepsilon_0}$",
      "$\\frac{q}{\\varepsilon_0}$",
      "$\\frac{q}{4\\varepsilon_0}$",
      "Zero"
    ],
    "correctAnswer": 0,
    "explanation": "Completing the hemisphere to a full sphere gives total flux $\\frac{q}{\\varepsilon_0}$. By symmetry, half the field lines pass through the curved surface of the hemisphere, giving $\\Phi = \\frac{q}{2\\varepsilon_0}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A spherical shell of radius $R$ carries a uniform surface charge density $\\sigma$. The electric field at a radial distance $r < R$ inside the shell is:",
    "options": [
      "Zero",
      "$\\frac{\\sigma}{\\varepsilon_0}$",
      "$\\frac{\\sigma}{2\\varepsilon_0}$",
      "$\\frac{\\sigma r}{\\varepsilon_0 R}$"
    ],
    "correctAnswer": 0,
    "explanation": "A Gaussian surface inside the shell encloses zero net charge, so $E(4\\pi r^2) = 0 \\implies E = 0$ everywhere inside the shell.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A non-conducting solid sphere of radius $R$ has a uniform volume charge density $\\rho$. The electric field at a distance $r$ from the center (where $r < R$) is:",
    "options": [
      "$\\frac{\\rho r}{3\\varepsilon_0}$",
      "$\\frac{\\rho r}{\\varepsilon_0}$",
      "$\\frac{\\rho R^3}{3\\varepsilon_0 r^2}$",
      "$\\frac{\\rho r^2}{3\\varepsilon_0 R}$"
    ],
    "correctAnswer": 0,
    "explanation": "Enclosed charge is $Q_{enc} = \\rho\\left(\\frac{4}{3}\\pi r^3\\right)$. By Gauss's law: $E(4\\pi r^2) = \\frac{Q_{enc}}{\\varepsilon_0} = \\frac{4\\pi \\rho r^3}{3\\varepsilon_0} \\implies E = \\frac{\\rho r}{3\\varepsilon_0}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A cylinder of radius $R$ and length $L$ is placed in a uniform electric field $\\vec{E}$ parallel to the cylinder axis. The total electric flux through the entire surface of the cylinder is:",
    "options": [
      "Zero",
      "$2\\pi R^2 E$",
      "$\\pi R^2 E$",
      "$2\\pi R L E$"
    ],
    "correctAnswer": 0,
    "explanation": "Flux entering the left flat face is $-E(\\pi R^2)$. Flux exiting the right flat face is $+E(\\pi R^2)$. Flux through the curved surface is zero as $\\vec{E} \\parallel$ curved surface. Total flux is $-E\\pi R^2 + E\\pi R^2 = 0$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Inside a solid sphere of uniform charge density $\\rho$, a spherical cavity of radius $R'$ is excavated. The electric field inside the cavity is:",
    "options": [
      "Uniform and non-zero",
      "Zero everywhere",
      "Radial and proportional to distance from cavity center",
      "Inversely proportional to distance from cavity center"
    ],
    "correctAnswer": 0,
    "explanation": "By superposition, $\\vec{E} = \\vec{E}_{full} - \\vec{E}_{removed} = \\frac{\\rho}{3\\varepsilon_0}\\vec{r}_1 - \\frac{\\rho}{3\\varepsilon_0}\\vec{r}_2 = \\frac{\\rho}{3\\varepsilon_0}(\\vec{r}_1 - \\vec{r}_2) = \\frac{\\rho}{3\\varepsilon_0}\\vec{a}$, which is strictly uniform in both magnitude and direction.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge of $q = 53.12\\mu\\text{C}$ is placed at the center of a cube. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux $\\Phi$ through one face of the cube in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "$\\Phi = \\frac{q}{6\\varepsilon_0} = \\frac{53.12 \\times 10^{-6}}{6(8.854 \\times 10^{-12})} = 1 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 10 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge of $q = 106.25\\mu\\text{C}$ is placed at the center of a cube. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux $\\Phi$ through one face of the cube in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$\\Phi = \\frac{q}{6\\varepsilon_0} = \\frac{106.25 \\times 10^{-6}}{6(8.854 \\times 10^{-12})} = 2 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 20 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge of $q = 159.37\\mu\\text{C}$ is placed at the center of a cube. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux $\\Phi$ through one face of the cube in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "$\\Phi = \\frac{q}{6\\varepsilon_0} = \\frac{159.37 \\times 10^{-6}}{6(8.854 \\times 10^{-12})} = 3 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 30 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge of $q = 212.5\\mu\\text{C}$ is placed at the center of a cube. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux $\\Phi$ through one face of the cube in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "$\\Phi = \\frac{q}{6\\varepsilon_0} = \\frac{212.5 \\times 10^{-6}}{6(8.854 \\times 10^{-12})} = 4 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 40 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge of $q = 265.62\\mu\\text{C}$ is placed at the center of a cube. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux $\\Phi$ through one face of the cube in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "$\\Phi = \\frac{q}{6\\varepsilon_0} = \\frac{265.62 \\times 10^{-6}}{6(8.854 \\times 10^{-12})} = 5 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 50 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge $q = 17.71\\mu\\text{C}$ is located at the center of the circular base of a hemisphere. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux through the curved surface of the hemisphere in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "$\\Phi = \\frac{q}{2\\varepsilon_0} = \\frac{17.71 \\times 10^{-6}}{2(8.854 \\times 10^{-12})} = 1 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 10 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge $q = 35.42\\mu\\text{C}$ is located at the center of the circular base of a hemisphere. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux through the curved surface of the hemisphere in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$\\Phi = \\frac{q}{2\\varepsilon_0} = \\frac{35.42 \\times 10^{-6}}{2(8.854 \\times 10^{-12})} = 2 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 20 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge $q = 53.12\\mu\\text{C}$ is located at the center of the circular base of a hemisphere. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux through the curved surface of the hemisphere in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "$\\Phi = \\frac{q}{2\\varepsilon_0} = \\frac{53.12 \\times 10^{-6}}{2(8.854 \\times 10^{-12})} = 3 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 30 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge $q = 70.83\\mu\\text{C}$ is located at the center of the circular base of a hemisphere. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux through the curved surface of the hemisphere in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "$\\Phi = \\frac{q}{2\\varepsilon_0} = \\frac{70.83 \\times 10^{-6}}{2(8.854 \\times 10^{-12})} = 4 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 40 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A point charge $q = 88.54\\mu\\text{C}$ is located at the center of the circular base of a hemisphere. Taking $\\varepsilon_0 = 8.854 \\times 10^{-12}\\text{ C}^2/(\\text{N}\\cdot\\text{m}^2)$, find the electric flux through the curved surface of the hemisphere in units of $10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "$\\Phi = \\frac{q}{2\\varepsilon_0} = \\frac{88.54 \\times 10^{-6}}{2(8.854 \\times 10^{-12})} = 5 \\times 10^6\\text{ N}\\cdot\\text{m}^2/\\text{C} = 50 \\times 10^5\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A non-conducting solid sphere of radius $R = 1.0\\text{ m}$ carries a total charge of $Q = 2\\mu\\text{C}$ distributed uniformly throughout its volume. Calculate the electric field intensity $E$ (in $\\text{kV/m}$) at a radial distance $r = 0.5\\text{ m}$ from the center. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 9,
    "numericalAnswer": 9,
    "explanation": "$E = \\frac{k Q r}{R^3} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})(0.5)}{(1.0)^3} = 9000\\text{ V/m} = 9\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A non-conducting solid sphere of radius $R = 1.0\\text{ m}$ carries a total charge of $Q = 4\\mu\\text{C}$ distributed uniformly throughout its volume. Calculate the electric field intensity $E$ (in $\\text{kV/m}$) at a radial distance $r = 0.5\\text{ m}$ from the center. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 18,
    "numericalAnswer": 18,
    "explanation": "$E = \\frac{k Q r}{R^3} = \\frac{(9 \\times 10^9)(4 \\times 10^{-6})(0.5)}{(1.0)^3} = 18000\\text{ V/m} = 18\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A non-conducting solid sphere of radius $R = 1.0\\text{ m}$ carries a total charge of $Q = 6\\mu\\text{C}$ distributed uniformly throughout its volume. Calculate the electric field intensity $E$ (in $\\text{kV/m}$) at a radial distance $r = 0.5\\text{ m}$ from the center. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 27,
    "numericalAnswer": 27,
    "explanation": "$E = \\frac{k Q r}{R^3} = \\frac{(9 \\times 10^9)(6 \\times 10^{-6})(0.5)}{(1.0)^3} = 27000\\text{ V/m} = 27\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A non-conducting solid sphere of radius $R = 1.0\\text{ m}$ carries a total charge of $Q = 8\\mu\\text{C}$ distributed uniformly throughout its volume. Calculate the electric field intensity $E$ (in $\\text{kV/m}$) at a radial distance $r = 0.5\\text{ m}$ from the center. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 36,
    "numericalAnswer": 36,
    "explanation": "$E = \\frac{k Q r}{R^3} = \\frac{(9 \\times 10^9)(8 \\times 10^{-6})(0.5)}{(1.0)^3} = 36000\\text{ V/m} = 36\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A non-conducting solid sphere of radius $R = 1.0\\text{ m}$ carries a total charge of $Q = 10\\mu\\text{C}$ distributed uniformly throughout its volume. Calculate the electric field intensity $E$ (in $\\text{kV/m}$) at a radial distance $r = 0.5\\text{ m}$ from the center. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 45,
    "numericalAnswer": 45,
    "explanation": "$E = \\frac{k Q r}{R^3} = \\frac{(9 \\times 10^9)(10 \\times 10^{-6})(0.5)}{(1.0)^3} = 45000\\text{ V/m} = 45\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A conducting sphere of radius $0.1\\text{ m}$ carries a charge of $Q = 1\\mu\\text{C}$. Calculate the electric field $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from the center of the sphere. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "Outside the sphere ($r > R$), $E = \\frac{kQ}{r^2} = \\frac{(9 \\times 10^9)(1 \\times 10^{-6})}{(0.3)^2} = \\frac{9000}{0.09} = 100000\\text{ V/m} = 100\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A conducting sphere of radius $0.1\\text{ m}$ carries a charge of $Q = 2\\mu\\text{C}$. Calculate the electric field $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from the center of the sphere. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 200,
    "numericalAnswer": 200,
    "explanation": "Outside the sphere ($r > R$), $E = \\frac{kQ}{r^2} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})}{(0.3)^2} = \\frac{18000}{0.09} = 200000\\text{ V/m} = 200\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A conducting sphere of radius $0.1\\text{ m}$ carries a charge of $Q = 3\\mu\\text{C}$. Calculate the electric field $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from the center of the sphere. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 300,
    "numericalAnswer": 300,
    "explanation": "Outside the sphere ($r > R$), $E = \\frac{kQ}{r^2} = \\frac{(9 \\times 10^9)(3 \\times 10^{-6})}{(0.3)^2} = \\frac{27000}{0.09} = 300000\\text{ V/m} = 300\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A conducting sphere of radius $0.1\\text{ m}$ carries a charge of $Q = 4\\mu\\text{C}$. Calculate the electric field $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from the center of the sphere. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 400,
    "numericalAnswer": 400,
    "explanation": "Outside the sphere ($r > R$), $E = \\frac{kQ}{r^2} = \\frac{(9 \\times 10^9)(4 \\times 10^{-6})}{(0.3)^2} = \\frac{36000}{0.09} = 400000\\text{ V/m} = 400\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A conducting sphere of radius $0.1\\text{ m}$ carries a charge of $Q = 5\\mu\\text{C}$. Calculate the electric field $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from the center of the sphere. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 500,
    "numericalAnswer": 500,
    "explanation": "Outside the sphere ($r > R$), $E = \\frac{kQ}{r^2} = \\frac{(9 \\times 10^9)(5 \\times 10^{-6})}{(0.3)^2} = \\frac{45000}{0.09} = 500000\\text{ V/m} = 500\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Gauss's law",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
