// Subtopic 2: Middle term (30 questions: 10 MCQ, 10 AR, 10 NUM)
module.exports = [
  // --- MCQ 1 to 10 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The middle term in the expansion of $\\left(x - \\frac{1}{2x}\\right)^{10}$ is:",
    options: [
      "$-\\frac{63}{8}$",
      "$\\frac{63}{8}$",
      "$-\\frac{63}{4}$",
      "$\\frac{63}{4}$"
    ],
    correctAnswer: 0,
    explanation: "Since $n = 10$ is even, there is only one middle term, which is the $\\left(\\frac{10}{2} + 1\\right)^{\\text{th}} = 6^{\\text{th}}$ term ($r = 5$). $$T_6 = \\binom{10}{5} x^{10-5} \\left(-\\frac{1}{2x}\\right)^5 = 252 \\cdot x^5 \\cdot \\left(-\\frac{1}{32 x^5}\\right) = -\\frac{252}{32} = -\\frac{63}{8}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If $n$ is an even natural number, then the coefficient of the middle term in the expansion of $\\left(x + \\frac{1}{x}\\right)^{2n}$ is:",
    options: [
      "$\\frac{1 \\cdot 3 \\cdot 5 \\dots (2n-1)}{n!} 2^n$",
      "$\\frac{1 \\cdot 3 \\cdot 5 \\dots (2n-1)}{(n!)^2} 2^n$",
      "$\\frac{2n!}{n!}$",
      "$\\frac{1 \\cdot 3 \\cdot 5 \\dots (4n-1)}{(2n)!} 2^{2n}$"
    ],
    correctAnswer: 0,
    explanation: "The power is $2n$, which is even. The middle term is the $(n+1)^{\\text{th}}$ term. Its coefficient is $\\binom{2n}{n} = \\frac{(2n)!}{n! n!} = \\frac{1 \\cdot 2 \\cdot 3 \\dots (2n-1)(2n)}{(n!)^2} = \\frac{[1 \\cdot 3 \\cdot 5 \\dots (2n-1)] [2 \\cdot 4 \\dots 2n]}{(n!)^2} = \\frac{[1 \\cdot 3 \\cdot 5 \\dots (2n-1)] 2^n n!}{(n!)^2} = \\frac{1 \\cdot 3 \\cdot 5 \\dots (2n-1)}{n!} 2^n$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "In the expansion of $\\left(3x - \\frac{x^3}{6}\\right)^9$, the middle terms are:",
    options: [
      "$4^{\\text{th}}$ and $5^{\\text{th}}$ terms",
      "$5^{\\text{th}}$ and $6^{\\text{th}}$ terms",
      "$6^{\\text{th}}$ and $7^{\\text{th}}$ terms",
      "Only the $5^{\\text{th}}$ term"
    ],
    correctAnswer: 1,
    explanation: "The index is $n = 9$, which is odd. The total number of terms in the expansion is $9 + 1 = 10$. The middle terms are the $\\frac{9+1}{2} = 5^{\\text{th}}$ and $\\frac{9+3}{2} = 6^{\\text{th}}$ terms.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The middle term in the expansion of $\\left(1 - 3x + 3x^2 - x^3\\right)^{2n}$ is:",
    options: [
      "$\\binom{6n}{3n} (-1)^n x^{3n}$",
      "$\\binom{6n}{3n} (-1)^{3n} x^{3n}$",
      "$\\binom{2n}{n} (-x)^n$",
      "$\\binom{6n}{3n} x^{3n}$"
    ],
    correctAnswer: 1,
    explanation: "Notice that $1 - 3x + 3x^2 - x^3 = (1 - x)^3$. Therefore, the given expression is $\\left[(1 - x)^3\\right]^{2n} = (1 - x)^{6n}$. Since the index $6n$ is even, the middle term is the $(3n + 1)^{\\text{th}}$ term, corresponding to $r = 3n$. $$T_{3n+1} = \\binom{6n}{3n} (1)^{6n-3n} (-x)^{3n} = \\binom{6n}{3n} (-1)^{3n} x^{3n}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If the middle term in the expansion of $\\left(\\frac{x}{2} + 2\\right)^8$ is $1120$, then the real value of $x$ is:",
    options: [
      "$\\pm 2$",
      "$\\pm 1$",
      "$\\pm 4$",
      "$\\pm \\sqrt{2}$"
    ],
    correctAnswer: 0,
    explanation: "For $n = 8$, the middle term is the $5^{\\text{th}}$ term ($r = 4$). $$T_5 = \\binom{8}{4} \\left(\\frac{x}{2}\\right)^4 (2)^4 = 70 \\cdot \\frac{x^4}{16} \\cdot 16 = 70 x^4$$. We are given $T_5 = 1120$: $$70 x^4 = 1120 \\implies x^4 = 16 \\implies x^2 = 4 \\implies x = \\pm 2$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The greatest binomial coefficient in the expansion of $(1+x)^{14}$ is:",
    options: [
      "$\\binom{14}{6}$",
      "$\\binom{14}{7}$",
      "$\\binom{14}{8}$",
      "$\\binom{14}{5}$"
    ],
    correctAnswer: 1,
    explanation: "For any expansion $(1+x)^n$, the binomial coefficients $\\binom{n}{r}$ increase up to the middle term and then decrease. Since $n = 14$ is even, the maximum occurs at $r = n/2 = 7$, which is $\\binom{14}{7} = 3432$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "In the expansion of $\\left(\\frac{a}{x} + bx\\right)^{12}$, the middle term is independent of $x$ and equals:",
    options: [
      "$924 a^6 b^6$",
      "$462 a^6 b^6$",
      "$792 a^6 b^6$",
      "$1716 a^6 b^6$"
    ],
    correctAnswer: 0,
    explanation: "For $n = 12$, the middle term is the $7^{\\text{th}}$ term ($r = 6$). $$T_7 = \\binom{12}{6} \\left(\\frac{a}{x}\\right)^6 (bx)^6 = \\binom{12}{6} a^6 b^6 x^{6-6} = \\binom{12}{6} a^6 b^6$$. Calculating $\\binom{12}{6} = \\frac{12 \\times 11 \\times 10 \\times 9 \\times 8 \\times 7}{720} = 924$. Thus, the middle term is $924 a^6 b^6$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If the coefficients of the middle terms in the expansions of $(1+x)^{2n}$ and $(1+x)^{2n-1}$ are denoted by $\\alpha$ and $\\beta$ respectively, then $\\frac{\\alpha}{\\beta}$ is equal to:",
    options: [
      "$1$",
      "$2$",
      "$\\frac{1}{2}$",
      "$\\frac{2n}{2n-1}$"
    ],
    correctAnswer: 1,
    explanation: "In $(1+x)^{2n}$, the index $2n$ is even, so there is one middle term: $T_{n+1}$ with coefficient $\\alpha = \\binom{2n}{n}$. In $(1+x)^{2n-1}$, the index $2n-1$ is odd, so the middle terms are the $n^{\\text{th}}$ and $(n+1)^{\\text{th}}$ terms, each with coefficient $\\beta = \\binom{2n-1}{n-1} = \\binom{2n-1}{n}$. We have $\\binom{2n}{n} = \\frac{2n}{n} \\binom{2n-1}{n-1} = 2 \\binom{2n-1}{n-1} = 2\\beta$. Therefore, $\\frac{\\alpha}{\\beta} = 2$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The middle term in the expansion of $\\left(x^2 + \\frac{1}{x}\\right)^{2n}$ is:",
    options: [
      "$\\binom{2n}{n} x^n$",
      "$\\binom{2n}{n} x^{2n}$",
      "$\\binom{2n}{n} x^{3n}$",
      "$\\binom{2n}{n}$"
    ],
    correctAnswer: 0,
    explanation: "The index is $2n$, which is even. The middle term is the $(n+1)^{\\text{th}}$ term ($r = n$). $$T_{n+1} = \\binom{2n}{n} (x^2)^{2n-n} \\left(\\frac{1}{x}\\right)^n = \\binom{2n}{n} (x^2)^n x^{-n} = \\binom{2n}{n} x^{2n-n} = \\binom{2n}{n} x^n$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If the middle term in the expansion of $\\left(2x + \\frac{1}{3x}\\right)^{2m}$ contains $x^0$, then its value is:",
    options: [
      "$\\binom{2m}{m} \\left(\\frac{2}{3}\\right)^m$",
      "$\\binom{2m}{m} 2^m 3^m$",
      "$\\binom{2m}{m} \\left(\\frac{3}{2}\\right)^m$",
      "$\\binom{2m}{m}$"
    ],
    correctAnswer: 0,
    explanation: "The middle term corresponds to $r = m$: $$T_{m+1} = \\binom{2m}{m} (2x)^m \\left(\\frac{1}{3x}\\right)^m = \\binom{2m}{m} 2^m x^m \\cdot \\frac{1}{3^m x^m} = \\binom{2m}{m} \\left(\\frac{2}{3}\\right)^m$$. This term is independent of $x$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- AR 11 to 20 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The expansion of $(1+x)^{20}$ has exactly one middle term, which has the greatest binomial coefficient among all terms.\nReason (R): When $n$ is even, the number of terms in $(1+x)^n$ is $n+1$ (an odd number), which has a unique middle term at $r = n/2$, and $\\binom{n}{r}$ is maximized at $r = n/2$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Since $n = 20$ is even, the number of terms is $21$, so the unique middle term is the $11^{\\text{th}}$ term ($r = 10$). The coefficient $\\binom{20}{10}$ is the maximum binomial coefficient in $(1+x)^{20}$. Reason (R) states this general fact accurately, hence both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): In the expansion of $(1+x)^{15}$, there are two middle terms and their coefficients are equal.\nReason (R): When $n$ is odd, the middle terms are the $\\left(\\frac{n+1}{2}\\right)^{\\text{th}}$ and $\\left(\\frac{n+3}{2}\\right)^{\\text{th}}$ terms, with coefficients $\\binom{n}{\\frac{n-1}{2}}$ and $\\binom{n}{\\frac{n+1}{2}}$, which are equal because $\\binom{n}{r} = \\binom{n}{n-r}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "For $n = 15$ (odd), the number of terms is $16$ (even). The middle terms are the $8^{\\text{th}}$ and $9^{\\text{th}}$ terms ($r = 7$ and $r = 8$). Their coefficients are $\\binom{15}{7}$ and $\\binom{15}{8}$. Since $\\binom{15}{7} = \\binom{15}{15-7} = \\binom{15}{8}$, their coefficients are equal. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The coefficient of the middle term in the expansion of $(1+x)^{2n}$ is greater than the sum of the coefficients of the two middle terms in the expansion of $(1+x)^{2n-1}$.\nReason (R): For any natural number $n$, $\\binom{2n}{n} = \\binom{2n-1}{n-1} + \\binom{2n-1}{n}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 3,
    explanation: "In $(1+x)^{2n}$, the coefficient of the middle term is $\\binom{2n}{n}$. In $(1+x)^{2n-1}$, the coefficients of the two middle terms are $\\binom{2n-1}{n-1}$ and $\\binom{2n-1}{n}$. By Pascal's identity, $\\binom{2n}{n} = \\binom{2n-1}{n-1} + \\binom{2n-1}{n}$, which means the coefficient is exactly EQUAL to the sum, not strictly greater. Therefore, Assertion (A) is false, but Reason (R) is true.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The middle term in the expansion of $\\left(x - \\frac{1}{x}\\right)^{10}$ is $-252$.\nReason (R): In $\\left(x - \\frac{1}{x}\\right)^{2n}$, the middle term is $T_{n+1} = \\binom{2n}{n} x^n (-x^{-1})^n = (-1)^n \\binom{2n}{n}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Here $2n = 10 \\implies n = 5$. The middle term is $T_6 = (-1)^5 \\binom{10}{5} = -252$. Reason (R) gives the general formula for the middle term of $\\left(x - \\frac{1}{x}\\right)^{2n}$, which evaluates to $(-1)^n \\binom{2n}{n}$. For $n=5$, $(-1)^5 \\binom{10}{5} = -252$. Both (A) and (R) are true, and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): In the expansion of $\\left(x + \\frac{1}{x}\\right)^6$, the middle term has the highest value of coefficient, and is independent of $x$.\nReason (R): The middle term in $\\left(x + \\frac{1}{x}\\right)^{2n}$ is the $(n+1)^{\\text{th}}$ term, in which the powers of $x$ cancel out, leaving a constant term.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "For $n=6=2(3)$, the middle term is $T_4 = \\binom{6}{3} x^3 (1/x)^3 = 20$, which is constant and has the maximal binomial coefficient $\\binom{6}{3} = 20$. Reason (R) states this general property accurately. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The middle term of $\\left(1 + 2x\\right)^6$ at $x = 1$ is $160$.\nReason (R): The middle term of $(a+b)^6$ is $T_4 = \\binom{6}{3} a^3 b^3$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Here $a = 1, b = 2x, n = 6$. The middle term is $T_4 = \\binom{6}{3} (1)^3 (2x)^3 = 20 \\times 8x^3 = 160 x^3$. At $x = 1$, $T_4 = 160(1)^3 = 160$. Both (A) and (R) are true, and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The greatest coefficient in the expansion of $(1+x)^{2n+1}$ is $\\binom{2n+1}{n}$.\nReason (R): In the expansion of $(1+x)^m$, the binomial coefficients satisfy $\\binom{m}{0} < \\binom{m}{1} < \\dots < \\binom{m}{\\lfloor m/2 \\rfloor}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "For odd index $m = 2n+1$, the binomial coefficients increase strictly until $r = n$ and then decrease after $r = n+1$, with $\\binom{2n+1}{n} = \\binom{2n+1}{n+1}$ being the two equal maximum values. Thus, the greatest coefficient is indeed $\\binom{2n+1}{n}$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): If $n$ is an odd natural number, then the two middle terms in the expansion of $(a-b)^n$ have opposite signs if $a, b > 0$.\nReason (R): When $n$ is odd, the two middle terms correspond to $r = \\frac{n-1}{2}$ and $r = \\frac{n+1}{2}$, which have opposite parities.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "In the expansion of $(a-b)^n = [a + (-b)]^n$, the term has factor $(-1)^r$. The two middle terms have $r_1 = \\frac{n-1}{2}$ and $r_2 = \\frac{n+1}{2} = r_1 + 1$. Since $r_2 = r_1 + 1$, one of them is even and the other is odd. Hence, $(-1)^{r_1}$ and $(-1)^{r_2}$ have opposite signs. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The middle term in the expansion of $\\left(x^3 + \\frac{1}{x^3}\\right)^{10}$ contains $x^0$.\nReason (R): For $\\left(x^p + \\frac{1}{x^p}\\right)^{2k}$, the middle term is $T_{k+1} = \\binom{2k}{k} (x^p)^k (x^{-p})^k = \\binom{2k}{k}$, which is always independent of $x$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Here $p = 3, 2k = 10 \\implies k = 5$. The middle term is $T_6 = \\binom{10}{5} (x^3)^5 (x^{-3})^5 = \\binom{10}{5} = 252$, which has $x^0$. Reason (R) states this general principle correctly. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The ratio of the coefficient of the middle term of $(1+x)^{2n}$ to the coefficient of the middle term of $(1+x)^{2n-2}$ is $\\frac{2(2n-1)}{n}$.\nReason (R): The coefficient of the middle term of $(1+x)^{2m}$ is $\\binom{2m}{m}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "The coefficient for $(1+x)^{2n}$ is $\\binom{2n}{n}$ and for $(1+x)^{2n-2}$ is $\\binom{2n-2}{n-1}$. The ratio is: $$\\frac{\\binom{2n}{n}}{\\binom{2n-2}{n-1}} = \\frac{(2n)!}{n! n!} \\times \\frac{(n-1)! (n-1)!}{(2n-2)!} = \\frac{2n(2n-1)}{n^2} = \\frac{2(2n-1)}{n}$$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- NUM 21 to 30 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "The coefficient of the middle term in the expansion of $(1+x)^{10}$ is:",
    options: [],
    correctAnswer: 252,
    explanation: "For $n = 10$, the middle term is the $\\left(\\frac{10}{2} + 1\\right)^{\\text{th}} = 6^{\\text{th}}$ term ($r = 5$). Its coefficient is $\\binom{10}{5} = \\frac{10 \\times 9 \\times 8 \\times 7 \\times 6}{120} = 252$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the middle term in the expansion of $\\left(x^2 + \\frac{1}{x}\\right)^8$ is $T_k = c x^m$, then the value of $m$ is:",
    options: [],
    correctAnswer: 4,
    explanation: "Since $n = 8$, the middle term is the $5^{\\text{th}}$ term ($r = 4$). $$T_5 = \\binom{8}{4} (x^2)^{8-4} \\left(\\frac{1}{x}\\right)^4 = 70 (x^2)^4 x^{-4} = 70 x^8 x^{-4} = 70 x^4$$. Thus, $m = 4$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the ratio of the middle term in the expansion of $(1+x)^{2n}$ to that in the expansion of $(1+x)^{2n-1}$ is $2$, and the middle term coefficient of $(1+x)^{2n}$ is $70$, then the value of $n$ is:",
    options: [],
    correctAnswer: 4,
    explanation: "The middle term coefficient of $(1+x)^{2n}$ is $\\binom{2n}{n}$. We are given $\\binom{2n}{n} = 70$. Testing values of $n$: for $n=1$, $\\binom{2}{1}=2$; for $n=2$, $\\binom{4}{2}=6$; for $n=3$, $\\binom{6}{3}=20$; for $n=4$, $\\binom{8}{4} = \\frac{8 \\times 7 \\times 6 \\times 5}{24} = 70$. Thus, $n = 4$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the position $k$ of the middle term in the expansion of $\\left(\\frac{x}{3} + 9y\\right)^{12}$.",
    options: [],
    correctAnswer: 7,
    explanation: "For index $n = 12$, the number of terms is $12 + 1 = 13$. The middle term is at position $k = \\frac{12}{2} + 1 = 7$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "In the expansion of $\\left(x - \\frac{2}{x}\\right)^6$, the middle term is $k$. Find the value of $k$.",
    options: [],
    correctAnswer: -160,
    explanation: "Here $n = 6$. The middle term is the $4^{\\text{th}}$ term ($r = 3$). $$T_4 = \\binom{6}{3} x^{6-3} \\left(-\\frac{2}{x}\\right)^3 = 20 \\cdot x^3 \\cdot \\left(-\\frac{8}{x^3}\\right) = 20 \\times (-8) = -160$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the middle term in the expansion of $\\left(\\sqrt{x} + \\frac{1}{\\sqrt{x}}\\right)^{2n}$ is $924$, find the value of $n$.",
    options: [],
    correctAnswer: 6,
    explanation: "The middle term is $T_{n+1} = \\binom{2n}{n} (x^{1/2})^n (x^{-1/2})^n = \\binom{2n}{n}$. We are given $\\binom{2n}{n} = 924$. For $n=5$, $\\binom{10}{5} = 252$. For $n=6$, $\\binom{12}{6} = \\frac{12 \\times 11 \\times 10 \\times 9 \\times 8 \\times 7}{720} = 924$. Thus, $n = 6$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "The power of $x$ in the middle term of the expansion of $\\left(x^4 - \\frac{1}{x^2}\\right)^8$ is equal to:",
    options: [],
    correctAnswer: 8,
    explanation: "Since $n = 8$, the middle term is $T_5$ ($r = 4$). $$T_5 = \\binom{8}{4} (x^4)^{8-4} (-x^{-2})^4 = 70 (x^4)^4 x^{-8} = 70 x^{16} x^{-8} = 70 x^8$$. Therefore, the power of $x$ is $8$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the two middle terms in the expansion of $\\left(x^2 + \\frac{1}{x}\\right)^{11}$ have powers of $x$ given by $p$ and $q$, then $|p - q|$ is equal to:",
    options: [],
    correctAnswer: 3,
    explanation: "For $n = 11$, the middle terms are $T_6$ ($r = 5$) and $T_7$ ($r = 6$). For $T_6$: $(x^2)^{11-5} (x^{-1})^5 = (x^2)^6 x^{-5} = x^{12-5} = x^7$, so $p = 7$. For $T_7$: $(x^2)^{11-6} (x^{-1})^6 = (x^2)^5 x^{-6} = x^{10-6} = x^4$, so $q = 4$. Thus, $|p - q| = |7 - 4| = 3$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the coefficient of the middle term in the expansion of $\\left(1 + 3x\\right)^4$ at $x=1$ divided by $6$.",
    options: [],
    correctAnswer: 9,
    explanation: "For $n=4$, the middle term is $T_3$ ($r=2$). $$T_3 = \\binom{4}{2} (1)^2 (3x)^2 = 6 \\times 9 x^2 = 54 x^2$$. Its coefficient is $54$. Dividing by $6$, we get $\\frac{54}{6} = 9$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Middle term",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "In the expansion of $\\left(x - \\frac{1}{x}\\right)^{2n}$, if the middle term is $-20$, find the value of $n$.",
    options: [],
    correctAnswer: 3,
    explanation: "The middle term is $T_{n+1} = \\binom{2n}{n} x^n (-x^{-1})^n = (-1)^n \\binom{2n}{n}$. We are given $(-1)^n \\binom{2n}{n} = -20$. This requires $n$ to be odd and $\\binom{2n}{n} = 20$. For $n=3$, $\\binom{6}{3} = 20$, and $(-1)^3 (20) = -20$. Thus, $n = 3$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  }
];
