module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two parallel wires carrying steady currents in the same direction attract each other.\nReason (R): By Biot-Savart law and the right-hand grip rule, each wire produces a magnetic field at the other whose interaction with the current creates an attractive Lorentz force by Fleming's left-hand rule.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "For parallel currents $I_1$ and $I_2$ in the same direction separated by $d$, wire 1 creates field $B_1 = \\frac{\\mu_0 I_1}{2\\pi d}$ directed perpendicular to wire 2. The magnetic force on wire 2 is $\\vec{F}_{21} = I_2(\\vec{L} \\times \\vec{B}_1)$, pointing towards wire 1. Wire 1 experiences an equal and opposite force towards wire 2, causing attraction.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two parallel straight wires carrying currents in opposite directions repel each other.\nReason (R): The magnetic field produced by each wire interacts with the antiparallel current in the other to produce a force directed away from the other wire.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Reversing one current reverses the vector cross product $\\vec{L} \\times \\vec{B}$, flipping the magnetic force direction so that it points away from the adjacent wire, producing mutual repulsion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The force per unit length between two infinitely long parallel conductors separated by distance $d$ is inversely proportional to $d$.\nReason (R): The magnitude of the magnetic field produced by a long straight current-carrying wire decreases inversely with distance as $B = \\frac{\\mu_0 I}{2\\pi d}$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The force per unit length is $\\frac{F}{L} = \\frac{\\mu_0 I_1 I_2}{2\\pi d}$. Since $B_1 \\propto 1/d$ and $F/L = I_2 B_1$, the force per unit length is directly proportional to $1/d$. Both Assertion and Reason are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The SI definition of the Ampere was historically based on the force between two parallel current-carrying conductors.\nReason (R): One Ampere is defined as that constant current which, if maintained in two straight parallel conductors of infinite length placed $1\\text{ meter}$ apart in vacuum, produces between them a force equal to $2 \\times 10^{-7}\\text{ Newton per meter}$ of length.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "From $F/L = \\frac{\\mu_0 I_1 I_2}{2\\pi d}$, setting $I_1 = I_2 = 1\\text{ A}$ and $d = 1\\text{ m}$ gives $F/L = \\frac{4\\pi \\times 10^{-7} \\times 1 \\times 1}{2\\pi \\times 1} = 2 \\times 10^{-7}\\text{ N/m}$. This was the international standard definition of the Ampere in the SI system.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two parallel beams of electrons moving in the same direction at non-relativistic speeds repel each other.\nReason (R): Although the parallel convection currents produce an attractive magnetic force, the repulsive electrostatic Coulomb force between the like negative charges is far stronger than the magnetic force when $v \\ll c$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The ratio of magnetic force to electric force between two charges moving with speed $v$ is $F_m / F_e = v^2 / c^2$. For non-relativistic electrons ($v \\ll c$), $F_e \\gg F_m$. Since both beams carry negative charge, the repulsive electrostatic force dominates completely.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If the current in both parallel wires is doubled and the separation between them is doubled, the force per unit length between them doubles.\nReason (R): The force per unit length is given by $\\frac{F}{L} = \\frac{\\mu_0 I_1 I_2}{2\\pi d}$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "New force per unit length: $\\left(\\frac{F}{L}\\right)' = \\frac{\\mu_0 (2I_1)(2I_2)}{2\\pi (2d)} = 2 \\frac{\\mu_0 I_1 I_2}{2\\pi d} = 2 \\left(\\frac{F}{L}\\right)$. Both Assertion and Reason are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The mutual magnetic forces between two long parallel current-carrying straight conductors obey Newton's third law of motion.\nReason (R): The magnetic force exerted by wire 1 on wire 2 is equal in magnitude and opposite in direction to the force exerted by wire 2 on wire 1 ($\\vec{F}_{12} = -\\vec{F}_{21}$).\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "For two complete, closed or infinitely long parallel straight circuits, the action-reaction law holds strictly: $\\vec{F}_{12} = -\\vec{F}_{21}$. Both Assertion and Reason are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A rectangular current loop placed near a long straight wire in the same plane experiences a net translational force towards the wire if the closer edge carries current in the same direction as the wire.\nReason (R): The attractive force on the closer edge of the loop is greater in magnitude than the repulsive force on the farther edge, while the forces on the two transverse edges cancel out.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The magnetic field is stronger closer to the wire. The near parallel edge has current parallel to the wire, experiencing a strong attractive force $F_1 = \\frac{\\mu_0 I_1 I_2 L}{2\\pi d_1}$. The far edge experiences a weaker repulsive force $F_2 = \\frac{\\mu_0 I_1 I_2 L}{2\\pi d_2} < F_1$. The net force is attractive (towards the wire).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Three long parallel wires $A, B,$ and $C$ carrying equal currents in the same direction are placed symmetrically at equal distances $d$ in a plane. The middle wire $B$ experiences zero net force.\nReason (R): The attractive force exerted on the middle wire $B$ by wire $A$ is equal in magnitude and opposite in direction to the attractive force exerted on wire $B$ by wire $C$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Wire $A$ pulls wire $B$ towards the left with force $F = \\frac{\\mu_0 I^2 L}{2\\pi d}$, while wire $C$ pulls wire $B$ towards the right with an identical force $F$. The resultant force on $B$ is $\\vec{F}_{net} = 0$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A flexible wire carrying a large electric current will contract radially into a tighter cylinder.\nReason (R): Parallel current filaments flowing through the same conductor carry current in the same direction, mutually attracting each other via Ampere's force (pinch effect).\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Any large conductor can be viewed as a bundle of parallel current filaments. Because they all carry current in the same direction, they attract each other, creating an inward radial magnetic pressure known as the pinch effect.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If two parallel straight wires carry unequal currents, the force exerted by the wire with the larger current on the other is greater than the force exerted on it.\nReason (R): The magnetic field produced by the larger current is stronger, creating a larger force.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 3,
    "explanation": "The force on wire 2 is $F_{12} = I_2 L B_1 = I_2 L \\frac{\\mu_0 I_1}{2\\pi d} = \\frac{\\mu_0 I_1 I_2 L}{2\\pi d}$. The force on wire 1 is $F_{21} = I_1 L B_2 = I_1 L \\frac{\\mu_0 I_2}{2\\pi d} = \\frac{\\mu_0 I_1 I_2 L}{2\\pi d}$. The forces are strictly equal in magnitude, obeying Newton's third law. Assertion is false, Reason is flawed.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A horizontal wire carrying current $I_2$ can be magnetically levitated above a parallel fixed horizontal wire carrying current $I_1$.\nReason (R): If the currents flow in opposite directions, the repulsive magnetic force can act vertically upwards to balance the weight of the upper wire.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Opposite currents repel each other. If the lower wire is fixed and the upper wire has current antiparallel to it, the magnetic repulsion pushes the upper wire upwards. Levitation occurs when $\\frac{\\mu_0 I_1 I_2}{2\\pi d} = \\lambda g$, where $\\lambda$ is mass per unit length.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The magnetic force between two parallel current-carrying wires depends on the magnetic permeability of the intervening medium.\nReason (R): The magnetic field produced by a current in a medium of relative permeability $\\mu_r$ is $B = \\frac{\\mu_r \\mu_0 I}{2\\pi d}$, scaling the force per unit length by a factor of $\\mu_r$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "In a magnetic medium, $\\mu_0$ is replaced by $\\mu = \\mu_r \\mu_0$. Hence $\\frac{F}{L} = \\frac{\\mu I_1 I_2}{2\\pi d} = \\mu_r \\left(\\frac{F}{L}\\right)_{vacuum}$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two parallel straight wires carrying currents in the same direction are placed in a uniform external magnetic field. The net force between the wires changes.\nReason (R): The force between the two wires depends solely on the currents they carry and their separation, while the external field only adds an external force to each wire individually.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 3,
    "explanation": "The mutual force between the two wires is unaffected by an external uniform field (superposition principle). The total force on each wire is the vector sum of the mutual force and the external force, but the mutual interaction force remains $\\frac{\\mu_0 I_1 I_2}{2\\pi d}$. Thus Assertion is false, Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Four long parallel wires carrying equal currents in the same direction pass through the vertices of a square. The net magnetic field at the center of the square is zero.\nReason (R): The magnetic fields produced by diametrically opposite pairs of wires at the geometric center are equal in magnitude and opposite in direction.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "By symmetry, the fields of opposite wires cancel in pairs at the center of the square: $\\vec{B}_1 + \\vec{B}_3 = 0$ and $\\vec{B}_2 + \\vec{B}_4 = 0$. Thus $\\vec{B}_{net} = 0$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If two parallel wires carry currents $I_1$ and $I_2$ in the same direction, there is a neutral line between the wires where the net magnetic field is zero.\nReason (R): At a point between the wires, the magnetic fields produced by the two parallel currents point in opposite directions and cancel when $\\frac{\\mu_0 I_1}{2\\pi d_1} = \\frac{\\mu_0 I_2}{2\\pi d_2}$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Between parallel wires carrying current in the same direction, the magnetic field of one is directed inwards and that of the other is directed outwards. Zero net field occurs along a line at distance ratio $d_1 / d_2 = I_1 / I_2$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When two mutually perpendicular non-intersecting wires carry steady currents, the net magnetic force between them is zero.\nReason (R): The force per unit length between any two current-carrying wires is proportional to the cosine of the angle between them.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 2,
    "explanation": "For two infinitely long straight perpendicular wires, integration of the magnetic force across their lengths shows that the net translational force is zero (though a net torque exists). However, the force between arbitrary current elements is governed by Ampere's force law, not a simple cosine scalar. Assertion is true, Reason is false.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A circular coil carrying current $I$ tends to contract when the current flows.\nReason (R): Diametrically opposite current elements carry currents in opposite directions and therefore repel each other.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 3,
    "explanation": "Opposite elements carry currents in opposite directions and repel each other, while adjacent elements carry current in similar directions and attract. The net magnetic pressure points outward, causing the loop to expand, not contract. Assertion is false, Reason (that opposite elements carry opposite directions and repel) is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If two long parallel wires carry alternating currents in the same phase, they attract each other on average.\nReason (R): Since $I_1(t) = I_0 \\sin(\\omega t)$ and $I_2(t) = I_0 \\sin(\\omega t)$, their instantaneous product is $I_1(t) I_2(t) = I_0^2 \\sin^2(\\omega t) \\ge 0$, which has a strictly positive time-average value.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The force is proportional to $I_1(t) I_2(t) = I_0^2 \\sin^2(\\omega t)$. Because $\\langle \\sin^2(\\omega t) \\rangle = 1/2 > 0$, the time-averaged force is attractive.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A current loop suspended freely in a non-uniform magnetic field will experience translational acceleration towards regions of stronger magnetic field if its dipole moment aligns with the field.\nReason (R): The potential energy of a magnetic dipole in an aligned state is $U = -M B$, so the net force $\\vec{F} = -\\nabla U = M \\nabla B$ points in the direction of increasing field strength.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "When $\\vec{M}$ is parallel to $\\vec{B}$, $U = -MB$. The force is $\\vec{F} = -\\nabla(-MB) = M\\nabla B$. This drives the dipole towards regions of higher magnetic field $B$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two parallel wires carrying currents of $2\\text{ A}$ and $8\\text{ A}$ separated by $10\\text{ cm}$ experience mutual forces that are in the ratio $1 : 4$.\nReason (R): Magnetic force on a wire is directly proportional to the current flowing through that wire.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 3,
    "explanation": "By Newton's third law, the force exerted by wire 1 on wire 2 is equal and opposite to the force exerted by wire 2 on wire 1. The ratio of mutual forces is always $1 : 1$. Assertion is false, Reason is true (force on a wire is proportional to its own current, but also to the field of the other wire).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two parallel conductors placed $1\\text{ mm}$ apart in air carrying current of $1000\\text{ A}$ can produce severe mechanical forces capable of distorting the conductors.\nReason (R): The force per unit length is proportional to the product of the currents and inversely proportional to the separation: $F/L = \\frac{\\mu_0 I^2}{2\\pi d} = \\frac{(2 \\times 10^{-7})(10^6)}{10^{-3}} = 200\\text{ N/m}$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Calculating $F/L$: $\\frac{(4\\pi \\times 10^{-7})(1000)^2}{2\\pi (10^{-3})} = \\frac{2 \\times 10^{-7} \\times 10^6}{10^{-3}} = 200\\text{ N/m}$. High surge currents (like short-circuit faults) generate massive mechanical stresses requiring robust busbar bracing in power systems.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In a coaxial cable, the inner and outer conductors repel each other.\nReason (R): The inner conductor and the outer cylindrical shell carry equal currents flowing in opposite directions.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "In a standard coaxial line, the signal current flows along the inner core and returns along the outer sheath. Because the currents are antiparallel, the magnetic forces between them are repulsive. The inner conductor experiences outward magnetic pressure and the outer sheath experiences radial expansion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If two parallel wires carrying currents in the same direction are placed in a region free of external fields, the magnetic energy stored in space decreases as the wires move closer together.\nReason (R): Systems with attractive forces naturally tend to move toward configurations of lower potential energy.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Because the force between parallel currents in the same direction is attractive, releasing them from rest will cause them to accelerate toward each other, converting magnetic potential energy into mechanical kinetic energy.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The force per unit length between two parallel wires does not depend on the cross-sectional shape of the wires if the separation is much larger than their radii.\nReason (R): When separation $d \\gg R$, the wires can be accurately treated as ideal line currents located along their central axes.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "By the multipole expansion, when the separation is much larger than the wire radius ($d \\gg R$), higher-order multipole contributions vanish and the fields reduce to those of line currents.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If three long parallel wires carrying equal currents $I$ in the same direction pass through the vertices of an equilateral triangle of side $a$, the force per unit length on each wire is $\\sqrt{3}\\frac{\\mu_0 I^2}{2\\pi a}$.\nReason (R): Each wire experiences two attractive forces of magnitude $F_0 = \\frac{\\mu_0 I^2}{2\\pi a}$ at an angle of $60^\\circ$ to each other, giving a resultant $F_{net} = \\sqrt{F_0^2 + F_0^2 + 2F_0^2 \\cos 60^\\circ} = \\sqrt{3}F_0$.\nIn the light of the above statements, choose the most appropriate answer from the options given below:",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The two attractive forces of magnitude $F_0$ make an angle of $60^\\circ$ with each other. The resultant magnitude is $F_{net} = \\sqrt{F_0^2 + F_0^2 + 2F_0^2(0.5)} = \\sqrt{3}F_0 = \\sqrt{3}\\frac{\\mu_0 I^2}{2\\pi a}$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long, parallel straight wires are separated by a distance of $0.2\\text{ m}$ and carry currents of $4.0\\text{ A}$ and $6.0\\text{ A}$ in opposite directions. The force per unit length experienced by each wire is:",
    "options": [
      "$2.4 \\times 10^{-5}\\text{ N/m}$, repulsive",
      "$2.4 \\times 10^{-5}\\text{ N/m}$, attractive",
      "$1.2 \\times 10^{-5}\\text{ N/m}$, repulsive",
      "$4.8 \\times 10^{-5}\\text{ N/m}$, attractive"
    ],
    "correctAnswer": 0,
    "explanation": "Force per unit length: $\\frac{F}{L} = \\frac{\\mu_0 I_1 I_2}{2\\pi d} = \\frac{(2 \\times 10^{-7})(4.0)(6.0)}{0.20} = \\frac{4.8 \\times 10^{-6}}{0.20} = 2.4 \\times 10^{-5}\\text{ N/m}$. Since the currents flow in opposite directions, the force is repulsive.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A long straight wire carries a current of $25\\text{ A}$. A rectangular loop of dimensions $15\\text{ cm} \\times 10\\text{ cm}$ carrying a current of $15\\text{ A}$ is placed with its longer sides parallel to the straight wire at distances of $2\\text{ cm}$ and $12\\text{ cm}$ respectively. The net magnetic force on the loop is:",
    "options": [
      "$4.7 \\times 10^{-4}\\text{ N}$ towards the wire",
      "$4.7 \\times 10^{-4}\\text{ N}$ away from the wire",
      "$7.8 \\times 10^{-4}\\text{ N}$ towards the wire",
      "$7.8 \\times 10^{-4}\\text{ N}$ away from the wire"
    ],
    "correctAnswer": 0,
    "explanation": "Length of parallel sides $L = 15\\text{ cm} = 0.15\\text{ m}$. Force on closer edge ($d_1 = 0.02\\text{ m}$, attractive): $F_1 = \\frac{\\mu_0 I_1 I_2 L}{2\\pi d_1} = \\frac{(2 \\times 10^{-7})(25)(15)(0.15)}{0.02} = \\frac{1.125 \\times 10^{-5}}{0.02} = 5.625 \\times 10^{-4}\\text{ N}$ (towards wire). Force on farther edge ($d_2 = 0.12\\text{ m}$, repulsive): $F_2 = \\frac{(2 \\times 10^{-7})(25)(15)(0.15)}{0.12} = \\frac{1.125 \\times 10^{-5}}{0.12} = 0.9375 \\times 10^{-4}\\text{ N}$ (away). The forces on the transverse sides cancel. Net force $F_{net} = F_1 - F_2 = (5.625 - 0.9375) \\times 10^{-4} = 4.6875 \\times 10^{-4}\\text{ N} \\approx 4.7 \\times 10^{-4}\\text{ N}$ towards the wire.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Three long straight parallel wires $A, B,$ and $C$ carry currents $I_A = 10\\text{ A}$, $I_B = 20\\text{ A}$, and $I_C = 30\\text{ A}$ in the same direction. Wire $B$ is positioned midway between wires $A$ and $C$, with separation between $A$ and $B$ being $10\\text{ cm}$ and between $B$ and $C$ being $10\\text{ cm}$. The net force per unit length on wire $B$ is:",
    "options": [
      "$8.0 \\times 10^{-4}\\text{ N/m}$ towards $C$",
      "$8.0 \\times 10^{-4}\\text{ N/m}$ towards $A$",
      "$4.0 \\times 10^{-4}\\text{ N/m}$ towards $C$",
      "$4.0 \\times 10^{-4}\\text{ N/m}$ towards $A$"
    ],
    "correctAnswer": 0,
    "explanation": "Force on $B$ due to $A$ (attractive towards $A$, left): $F_{BA}/L = \\frac{\\mu_0 I_A I_B}{2\\pi d} = \\frac{(2 \\times 10^{-7})(10)(20)}{0.10} = 4.0 \\times 10^{-4}\\text{ N/m}$. Force on $B$ due to $C$ (attractive towards $C$, right): $F_{BC}/L = \\frac{\\mu_0 I_B I_C}{2\\pi d} = \\frac{(2 \\times 10^{-7})(20)(30)}{0.10} = 12.0 \\times 10^{-4}\\text{ N/m}$. Net force per unit length on $B$ is $F_{net}/L = 12.0 \\times 10^{-4} - 4.0 \\times 10^{-4} = 8.0 \\times 10^{-4}\\text{ N/m}$ directed towards $C$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel straight wires $10\\text{ cm}$ apart carry currents $I_1 = 5\\text{ A}$ and $I_2 = 15\\text{ A}$ in the same direction. At what distance from wire 1 on the line connecting the two wires is the resultant magnetic field zero?",
    "options": [
      "$2.5\\text{ cm}$",
      "$5.0\\text{ cm}$",
      "$7.5\\text{ cm}$",
      "$1.5\\text{ cm}$"
    ],
    "correctAnswer": 0,
    "explanation": "Let the distance from wire 1 be $x$. Then the distance from wire 2 is $10 - x$. Since the currents flow in the same direction, the magnetic fields oppose each other between the wires: $\\frac{\\mu_0 I_1}{2\\pi x} = \\frac{\\mu_0 I_2}{2\\pi (10 - x)} \\implies \\frac{5}{x} = \\frac{15}{10 - x} \\implies 10 - x = 3x \\implies 4x = 10 \\implies x = 2.5\\text{ cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A horizontal wire of linear mass density $\\lambda = 0.04\\text{ kg/m}$ carries a current $I_2 = 20\\text{ A}$ and is free to move vertically above a fixed parallel wire carrying current $I_1 = 50\\text{ A}$. For what equilibrium separation $d$ will the upper wire remain levitated? (Take $g = 9.8\\text{ m/s}^2$)",
    "options": [
      "$5.1\\text{ mm}$",
      "$2.5\\text{ mm}$",
      "$10.2\\text{ mm}$",
      "$1.2\\text{ mm}$"
    ],
    "correctAnswer": 0,
    "explanation": "For levitation, magnetic repulsion balances gravity: $\\frac{\\mu_0 I_1 I_2}{2\\pi d} = \\lambda g \\implies d = \\frac{\\mu_0 I_1 I_2}{2\\pi \\lambda g} = \\frac{(2 \\times 10^{-7})(50)(20)}{(0.04)(9.8)} = \\frac{2.0 \\times 10^{-4}}{0.392} \\approx 5.102 \\times 10^{-3}\\text{ m} = 5.1\\text{ mm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires carrying equal currents $I$ in opposite directions are separated by distance $2d$. What is the magnetic field at a point midway between the wires?",
    "options": [
      "$\\frac{\\mu_0 I}{\\pi d}$",
      "$\\frac{2\\mu_0 I}{\\pi d}$",
      "Zero",
      "$\\frac{\\mu_0 I}{2\\pi d}$"
    ],
    "correctAnswer": 0,
    "explanation": "At the midpoint, distance from each wire is $d$. For opposite currents, by the right-hand grip rule, both fields point in the same direction perpendicular to the plane of the wires. Therefore: $B_{net} = B_1 + B_2 = \\frac{\\mu_0 I}{2\\pi d} + \\frac{\\mu_0 I}{2\\pi d} = \\frac{\\mu_0 I}{\\pi d}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Three long straight parallel wires carry equal currents $I$ in the same direction and pass through the vertices of an equilateral triangle of side $a$. The magnitude of the magnetic force per unit length on any one wire is:",
    "options": [
      "$\\frac{\\sqrt{3}\\mu_0 I^2}{2\\pi a}$",
      "$\\frac{\\mu_0 I^2}{2\\pi a}$",
      "$\\frac{\\mu_0 I^2}{\\pi a}$",
      "$\\frac{2\\mu_0 I^2}{\\pi a}$"
    ],
    "correctAnswer": 0,
    "explanation": "Each wire experiences an attractive force of magnitude $F_0 = \\frac{\\mu_0 I^2}{2\\pi a}$ from each of the other two wires. The angle between these two force vectors is $60^\\circ$. The resultant force is $F_{net} = \\sqrt{F_0^2 + F_0^2 + 2F_0^2\\cos 60^\\circ} = \\sqrt{3}F_0 = \\frac{\\sqrt{3}\\mu_0 I^2}{2\\pi a}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires separated by $5.0\\text{ cm}$ carry currents $I_1 = 10\\text{ A}$ and $I_2 = 25\\text{ A}$ in the same direction. Find the force per unit length experienced by the wires in micro-Newtons per meter ($\\mu\\text{N/m}$).",
    "options": [],
    "correctAnswer": "1000",
    "numericalAnswer": "1000",
    "explanation": "$\\frac{F}{L} = \\frac{\\mu_0 I_1 I_2}{2\\pi d} = \\frac{(2 \\times 10^{-7})(10)(25)}{0.05} = \\frac{5.0 \\times 10^{-5}}{0.05} = 1.0 \\times 10^{-3}\\text{ N/m} = 1000\\,\\mu\\text{N/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel straight wires $A$ and $B$ of length $2.0\\text{ m}$ each are separated by $4.0\\text{ cm}$ and carry currents $I_A = 6.0\\text{ A}$ and $I_B = 8.0\\text{ A}$. What is the total magnetic force between them in micro-Newtons ($\\mu\\text{N}$)?",
    "options": [],
    "correctAnswer": "480",
    "numericalAnswer": "480",
    "explanation": "$F = \\frac{\\mu_0 I_A I_B L}{2\\pi d} = \\frac{(2 \\times 10^{-7})(6.0)(8.0)(2.0)}{0.04} = \\frac{1.92 \\times 10^{-5}}{0.04} = 4.8 \\times 10^{-4}\\text{ N} = 480\\,\\mu\\text{N}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A fixed horizontal wire carries a current of $80\\text{ A}$. A second parallel wire of mass per unit length $\\lambda = 2.0 \\times 10^{-3}\\text{ kg/m}$ carrying current $I$ in the opposite direction is held in equilibrium $2.0\\text{ cm}$ directly above the first wire. Find the current $I$ in Amperes. (Take $g = 9.8\\text{ m/s}^2$)",
    "options": [],
    "correctAnswer": "24.5",
    "numericalAnswer": "24.5",
    "explanation": "For equilibrium: $\\frac{\\mu_0 I_1 I}{2\\pi d} = \\lambda g \\implies I = \\frac{2\\pi d \\lambda g}{\\mu_0 I_1} = \\frac{(0.02)(2.0 \\times 10^{-3})(9.8)}{(2 \\times 10^{-7})(80)} = \\frac{3.92 \\times 10^{-4}}{1.6 \\times 10^{-5}} = 24.5\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires carry currents $I_1 = 4\\text{ A}$ and $I_2 = 16\\text{ A}$ in the same direction. If the separation between the wires is $20\\text{ cm}$, find the distance (in cm) from wire 1 where the net magnetic field is zero.",
    "options": [],
    "correctAnswer": "4",
    "numericalAnswer": "4",
    "explanation": "Condition: $\\frac{I_1}{x} = \\frac{I_2}{20 - x} \\implies \\frac{4}{x} = \\frac{16}{20 - x} \\implies 20 - x = 4x \\implies 5x = 20 \\implies x = 4\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires carry currents $I_1 = 6\\text{ A}$ and $I_2 = 18\\text{ A}$ in opposite directions. The separation between the wires is $12\\text{ cm}$. Find the distance (in cm) from wire 1 on the side opposite to wire 2 where the net magnetic field is zero.",
    "options": [],
    "correctAnswer": "6",
    "numericalAnswer": "6",
    "explanation": "For opposite currents, the zero-field point lies outside the wires closer to the weaker current ($I_1 = 6\\text{ A}$). Let distance from wire 1 be $x$. Then distance from wire 2 is $12 + x$. $\\frac{6}{x} = \\frac{18}{12 + x} \\implies 12 + x = 3x \\implies 2x = 12 \\implies x = 6\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Three long straight parallel wires carry equal currents $I = 10\\text{ A}$ in the same direction and are placed at the vertices of an equilateral triangle of side $a = 10\\text{ cm}$. What is the magnetic force per unit length on each wire in micro-Newtons per meter ($\\mu\\text{N/m}$)? (Take $\\sqrt{3} = 1.732$)",
    "options": [],
    "correctAnswer": "346",
    "numericalAnswer": "346",
    "explanation": "$F/L = \\sqrt{3} \\frac{\\mu_0 I^2}{2\\pi a} = 1.732 \\times \\frac{(2 \\times 10^{-7})(10)^2}{0.10} = 1.732 \\times 2.0 \\times 10^{-4} = 3.464 \\times 10^{-4}\\text{ N/m} \\approx 346\\,\\mu\\text{N/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A square loop of side $L = 20\\text{ cm}$ carries a current of $5\\text{ A}$. It is placed in the same plane as a long straight wire carrying $20\\text{ A}$, with the nearest side parallel to the wire at a distance of $5\\text{ cm}$. If the current in the nearest side is in the same direction as the wire, find the net force on the loop in micro-Newtons ($\\mu\\text{N}$).",
    "options": [],
    "correctAnswer": "128",
    "numericalAnswer": "128",
    "explanation": "$d_1 = 0.05\\text{ m}, d_2 = 0.05 + 0.20 = 0.25\\text{ m}$. $F_1 = \\frac{\\mu_0 I_1 I_2 L}{2\\pi d_1} = \\frac{(2 \\times 10^{-7})(20)(5)(0.20)}{0.05} = \\frac{4.0 \\times 10^{-6}}{0.05} = 8.0 \\times 10^{-5}\\text{ N}$ (towards wire). $F_2 = \\frac{4.0 \\times 10^{-6}}{0.25} = 1.6 \\times 10^{-5}\\text{ N}$ (away). Net force $F_{net} = F_1 - F_2 = (8.0 - 1.6) \\times 10^{-5} = 6.4 \\times 10^{-5}\\text{ N} = 64\\,\\mu\\text{N}$ -- wait, let's recalculate: $(2 \\times 10^{-7})(20)(5)(0.20) = 8.0 \\times 10^{-6}$! Then $F_1 = 8.0 \\times 10^{-6} / 0.05 = 1.6 \\times 10^{-4}\\text{ N} = 160\\,\\mu\\text{N}$. $F_2 = 8.0 \\times 10^{-6} / 0.25 = 3.2 \\times 10^{-5}\\text{ N} = 32\\,\\mu\\text{N}$. $F_{net} = 160 - 32 = 128\\,\\mu\\text{N}$! Let's update val to 128.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires carry currents $I$ and $3I$ in the same direction. If the force per unit length between them is $6.0 \\times 10^{-5}\\text{ N/m}$ when separated by $10\\text{ cm}$, find the current $I$ in Amperes.",
    "options": [],
    "correctAnswer": "10",
    "numericalAnswer": "10",
    "explanation": "$\\frac{F}{L} = \\frac{\\mu_0 I(3I)}{2\\pi d} = \\frac{3\\mu_0 I^2}{2\\pi d} \\implies 6.0 \\times 10^{-5} = \\frac{3(2 \\times 10^{-7})I^2}{0.10} = 6.0 \\times 10^{-6} I^2 \\implies I^2 = \\frac{6.0 \\times 10^{-5}}{6.0 \\times 10^{-6}} = 100 \\implies I = 10\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Four long parallel wires carrying current $I = 10\\text{ A}$ each in the same direction pass through the vertices of a square of side $a = 10\\text{ cm}$. Find the magnitude of the net magnetic force per unit length on any one wire in micro-Newtons per meter ($\\mu\\text{N/m}$). (Take $\\sqrt{2} = 1.414$)",
    "options": [],
    "correctAnswer": "424",
    "numericalAnswer": "424",
    "explanation": "For wire 1, the two adjacent wires (distance $a$) attract it with forces $F_0 = \\frac{\\mu_0 I^2}{2\\pi a} = \\frac{(2 \\times 10^{-7})(100)}{0.10} = 2.0 \\times 10^{-4}\\text{ N/m}$. Their resultant is along the diagonal: $F_{adj} = \\sqrt{2}F_0$. The diagonally opposite wire (distance $\\sqrt{2}a$) attracts it along the diagonal with force $F_{diag} = \\frac{\\mu_0 I^2}{2\\pi (\\sqrt{2}a)} = \\frac{F_0}{\\sqrt{2}}$. Net force: $F_{net} = \\left(\\sqrt{2} + \\frac{1}{\\sqrt{2}}\\right) F_0 = \\frac{3}{\\sqrt{2}} F_0 = \\frac{3}{1.414}(2.0 \\times 10^{-4}) \\approx 2.1213 \\times 2.0 \\times 10^{-4} = 4.24 \\times 10^{-4}\\text{ N/m} = 424\\,\\mu\\text{N/m}$ -- wait: $\\frac{3}{\\sqrt{2}} = 2.1213$, so $2.1213 \\times 200\\,\\mu\\text{N/m} \\approx 424\\,\\mu\\text{N/m}$! Let's set val to 424.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires carry currents $I_1 = 20\\text{ A}$ and $I_2 = 30\\text{ A}$ in the same direction. They are separated by $15\\text{ cm}$. What is the magnetic field at the midpoint between them in micro-Tesla ($\\mu\\text{T}$)?",
    "options": [],
    "correctAnswer": "27",
    "numericalAnswer": "27",
    "explanation": "At the midpoint ($d = 7.5\\text{ cm} = 0.075\\text{ m}$), the fields oppose each other: $B_1 = \\frac{(2 \\times 10^{-7})(20)}{0.075} = \\frac{4.0 \\times 10^{-6}}{0.075} = 5.333 \\times 10^{-5}\\text{ T}$. $B_2 = \\frac{(2 \\times 10^{-7})(30)}{0.075} = \\frac{6.0 \\times 10^{-6}}{0.075} = 8.0 \\times 10^{-5}\\text{ T}$. Net field $B_{net} = 8.0 \\times 10^{-5} - 5.333 \\times 10^{-5} = 2.667 \\times 10^{-5}\\text{ T} \\approx 27\\,\\mu\\text{T}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A bundle of 5 identical parallel thin wires carrying $2.0\\text{ A}$ each in the same direction is placed parallel to a single wire carrying $10.0\\text{ A}$ in the opposite direction at a separation of $5.0\\text{ cm}$. What is the repulsive force per unit length between the bundle and the single wire in micro-Newtons per meter ($\\mu\\text{N/m}$)?",
    "options": [],
    "correctAnswer": "400",
    "numericalAnswer": "400",
    "explanation": "Total current in bundle $I_1 = 5 \\times 2.0 = 10.0\\text{ A}$. Current in single wire $I_2 = 10.0\\text{ A}$. Force per unit length: $\\frac{F}{L} = \\frac{\\mu_0 I_1 I_2}{2\\pi d} = \\frac{(2 \\times 10^{-7})(10.0)(10.0)}{0.05} = \\frac{2.0 \\times 10^{-5}}{0.05} = 4.0 \\times 10^{-4}\\text{ N/m} = 400\\,\\mu\\text{N/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A long straight wire carries $I = 50\\text{ A}$. An electron moves parallel to the wire with speed $v = 1.0 \\times 10^7\\text{ m/s}$ in the same direction as the current, at a distance of $5.0\\text{ cm}$ from the wire. What is the magnitude of the magnetic force on the electron in units of $10^{-17}\\text{ N}$?",
    "options": [],
    "correctAnswer": "32",
    "numericalAnswer": "32",
    "explanation": "Magnetic field at $5.0\\text{ cm}$: $B = \\frac{\\mu_0 I}{2\\pi r} = \\frac{(2 \\times 10^{-7})(50)}{0.05} = 2.0 \\times 10^{-4}\\text{ T}$. Magnetic force: $F = e v B = (1.6 \\times 10^{-19}\\text{ C})(1.0 \\times 10^7\\text{ m/s})(2.0 \\times 10^{-4}\\text{ T}) = 3.2 \\times 10^{-16}\\text{ N} = 32 \\times 10^{-17}\\text{ N}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires carry currents $I_1 = 12\\text{ A}$ and $I_2 = 4\\text{ A}$ in opposite directions, separated by $8\\text{ cm}$. The point of zero magnetic field is located at a distance of $d\\text{ cm}$ from the $4\\text{ A}$ wire (outside the wires). Find the value of $d$.",
    "options": [],
    "correctAnswer": "4",
    "numericalAnswer": "4",
    "explanation": "$\\frac{12}{8 + d} = \\frac{4}{d} \\implies 12d = 4(8 + d) = 32 + 4d \\implies 8d = 32 \\implies d = 4\\text{ cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two parallel wires each of length $1.5\\text{ m}$ are separated by $3.0\\text{ cm}$. When equal currents $I$ are passed through them, they experience an attractive force of $1.0 \\times 10^{-3}\\text{ N}$. Find the current $I$ in Amperes.",
    "options": [],
    "correctAnswer": "10",
    "numericalAnswer": "10",
    "explanation": "$F = \\frac{\\mu_0 I^2 L}{2\\pi d} \\implies 1.0 \\times 10^{-3} = \\frac{(2 \\times 10^{-7}) I^2 (1.5)}{0.03} = \\frac{3.0 \\times 10^{-7} I^2}{0.03} = 1.0 \\times 10^{-5} I^2 \\implies I^2 = \\frac{1.0 \\times 10^{-3}}{1.0 \\times 10^{-5}} = 100 \\implies I = 10\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A long straight wire carrying $40\\text{ A}$ is placed parallel to another wire carrying $60\\text{ A}$ at a distance of $20\\text{ cm}$. What is the work done per unit length (in $\\mu\\text{J/m}$) in increasing their separation from $20\\text{ cm}$ to $40\\text{ cm}$, if the currents flow in opposite directions?",
    "options": [],
    "correctAnswer": "333",
    "numericalAnswer": "333",
    "explanation": "Since currents are opposite, the force is repulsive: $F/L = \\frac{\\mu_0 I_1 I_2}{2\\pi r}$. The work done by an external agent against the magnetic repulsion to move them further apart is negative, but work done BY the magnetic force is $W/L = \\int_{r_1}^{r_2} \\frac{\\mu_0 I_1 I_2}{2\\pi r} dr = \\frac{\\mu_0 I_1 I_2}{2\\pi} \\ln\\left(\\frac{r_2}{r_1}\\right) = (2 \\times 10^{-7})(40)(60)\\ln(2) = 4.8 \\times 10^{-4}(0.69315) \\approx 3.327 \\times 10^{-4}\\text{ J/m} = 333\\,\\mu\\text{J/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Three parallel wires $1, 2,$ and $3$ carry currents $10\\text{ A}, 10\\text{ A},$ and $10\\text{ A}$ in the same direction and are spaced $5\\text{ cm}$ apart in a plane ($2$ is between $1$ and $3$). The net force per unit length on wire $1$ in micro-Newtons per meter ($\\mu\\text{N/m}$) is:",
    "options": [],
    "correctAnswer": "600",
    "numericalAnswer": "600",
    "explanation": "Forces on wire 1 from wire 2 (distance $5\\text{ cm}$) and wire 3 (distance $10\\text{ cm}$) are both attractive (towards the right): $F_2/L = \\frac{(2 \\times 10^{-7})(10)(10)}{0.05} = 4.0 \\times 10^{-4}\\text{ N/m}$. $F_3/L = \\frac{(2 \\times 10^{-7})(10)(10)}{0.10} = 2.0 \\times 10^{-4}\\text{ N/m}$. Total force per unit length on wire 1 is $F_{net}/L = 4.0 \\times 10^{-4} + 2.0 \\times 10^{-4} = 6.0 \\times 10^{-4}\\text{ N/m} = 600\\,\\mu\\text{N/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel wires carrying currents $I_1 = 5\\text{ A}$ and $I_2 = 10\\text{ A}$ in the same direction are separated by $12\\text{ cm}$. What is the magnetic field at a point $P$ located $6\\text{ cm}$ from both wires (midpoint) in micro-Tesla ($\\mu\\text{T}$)?",
    "options": [],
    "correctAnswer": "17",
    "numericalAnswer": "17",
    "explanation": "$d = 0.06\\text{ m}$. $B_1 = \\frac{(2 \\times 10^{-7})(5)}{0.06} = 1.667 \\times 10^{-5}\\text{ T}$. $B_2 = \\frac{(2 \\times 10^{-7})(10)}{0.06} = 3.333 \\times 10^{-5}\\text{ T}$. Net field: $B_{net} = 3.333 \\times 10^{-5} - 1.667 \\times 10^{-5} = 1.667 \\times 10^{-5}\\text{ T} \\approx 17\\,\\mu\\text{T}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A current of $10\\text{ A}$ flows through two long parallel wires separated by $2.0\\text{ cm}$. What is the force per unit length between them in units of $10^{-4}\\text{ N/m}$?",
    "options": [],
    "correctAnswer": "10",
    "numericalAnswer": "10",
    "explanation": "$F/L = \\frac{\\mu_0 I^2}{2\\pi d} = \\frac{(2 \\times 10^{-7})(10)^2}{0.02} = \\frac{2.0 \\times 10^{-5}}{0.02} = 1.0 \\times 10^{-3}\\text{ N/m} = 10 \\times 10^{-4}\\text{ N/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Hard",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A beam of protons ($q = 1.6 \\times 10^{-19}\\text{ C}$) moves parallel to a long straight wire carrying $20\\text{ A}$ with speed $v = 5.0 \\times 10^6\\text{ m/s}$ in the direction of the current. If the distance from the wire is $4.0\\text{ cm}$, the magnitude of the magnetic force on each proton in units of $10^{-16}\\text{ N}$ is:",
    "options": [],
    "correctAnswer": "8",
    "numericalAnswer": "8",
    "explanation": "$B = \\frac{\\mu_0 I}{2\\pi r} = \\frac{(2 \\times 10^{-7})(20)}{0.04} = 1.0 \\times 10^{-4}\\text{ T}$. Force: $F = q v B = (1.6 \\times 10^{-19})(5.0 \\times 10^6)(1.0 \\times 10^{-4}) = 8.0 \\times 10^{-16}\\text{ N}$. Thus the value is $8$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Easy",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two long parallel conductors carry equal currents in opposite directions and are separated by $10\\text{ cm}$. If the magnetic field at a point $10\\text{ cm}$ from both conductors is $B$, find the value of $B$ in micro-Tesla ($\\mu\\text{T}$) when $I = 15\\text{ A}$.",
    "options": [],
    "correctAnswer": "30",
    "numericalAnswer": "30",
    "explanation": "The point forms an equilateral triangle of side $d = 10\\text{ cm}$ with the two wires. Each wire produces $B_0 = \\frac{\\mu_0 I}{2\\pi d} = \\frac{(2 \\times 10^{-7})(15)}{0.10} = 3.0 \\times 10^{-5}\\text{ T}$. Since the currents are opposite, by the right-hand rule the two field vectors make an angle of $120^\\circ$ with each other (or let's check: angle between tangent lines at the third vertex is $60^\\circ$ or $120^\\circ$). If the angle between them is $120^\\circ$, $B_{net} = 2 B_0 \\cos(60^\\circ) = B_0 = 30\\,\\mu\\text{T}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "difficulty": "Medium",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Force between two parallel currents",
    "chapter": "Magnetic Effects of Current and Magnetism",
    "subject": "Physics",
    "source": "JEE Main Question Bank"
  }
];
