module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Work done by a thermodynamic system during an expansion depends on the path followed between the initial and final states.\\nReason (R): Thermodynamic work is a path function and not a state function.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Work done $W = \\int P\\,dV$ depends on the functional relationship between pressure $P$ and volume $V$ along the specific path connecting the two states. Hence, work is a path function, not a state property, making (R) the correct explanation of (A).",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): In an isochoric process, the work done by an ideal gas is always zero.\\nReason (R): Work done by a gas in a quasi-static process is given by $W = \\int P\\,dV$, and $dV = 0$ for a constant volume process.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "In an isochoric process, volume remains constant ($V = \\text{constant}$), so $dV = 0$. Consequently, $W = \\int P\\,dV = 0$. Thus both statements are true and (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The net work done by a gas in a closed cyclic process represented on a $P-V$ diagram is equal to the area enclosed by the loop.\\nReason (R): The net work done over a complete cycle is the cyclic integral $\\oint P\\,dV$, which geometrically represents the enclosed area on the $P-V$ plane.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Over a closed cycle, $W_{\\text{net}} = \\oint P\\,dV$. On a $P-V$ diagram, this integral corresponds directly to the area enclosed by the curve, taken as positive if traversed clockwise and negative if anticlockwise.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): A cyclic process traced in a clockwise direction on a standard $P-V$ diagram results in positive net work done by the gas.\\nReason (R): Along the upper path of the clockwise cycle, expansion occurs at higher pressures, so the positive work done during expansion exceeds the negative work done during compression along the lower path.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "During clockwise traversal on a $P-V$ diagram, the forward path is an expansion ($dV > 0$) at higher pressure, while the return path is a compression ($dV < 0$) at lower pressure. Hence, $W_{\\text{expansion}} > |W_{\\text{compression}}|$, yielding positive net work.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): A cyclic process traced in an anticlockwise direction on a $P-V$ diagram represents a work-absorbing cycle (such as a refrigerator or heat pump).\\nReason (R): For an anticlockwise cycle on a $P-V$ diagram, the net work done by the working substance is negative.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "In an anticlockwise cycle, the compression takes place at higher pressures than expansion, making the total work done by the system negative ($W_{\\text{net}} < 0$). This external work input is characteristic of refrigerators and heat pumps.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): For the same initial state and same final volume, the work done by an ideal gas during an isobaric expansion is greater than that in an isothermal expansion.\\nReason (R): In an isobaric expansion, pressure remains at its initial maximum value, so the area under the $P-V$ curve is larger than in an isothermal expansion where pressure decreases.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Starting from $(P_0, V_0)$ to $V_f > V_0$, the isobaric curve is a horizontal line at $P = P_0$, whereas the isothermal curve $P = P_0 V_0 / V$ drops below $P_0$. Since the area under the curve represents work, $W_{\\text{isobaric}} > W_{\\text{isothermal}}$.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): For an ideal gas expanding from volume $V_1$ to $V_2$, the work done in an isothermal process is greater than the work done in an adiabatic process.\\nReason (R): The slope of an adiabatic $P-V$ curve is steeper than that of an isothermal curve by a factor of $\\gamma$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Since $(\\partial P / \\partial V)_{\\text{adiabatic}} = \\gamma (\\partial P / \\partial V)_{\\text{isothermal}}$ with $\\gamma > 1$, the adiabatic curve falls more steeply than the isothermal curve during expansion. Hence, the area under the isothermal curve is strictly greater than under the adiabatic curve.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): When an ideal gas undergoes free expansion into an evacuated insulated container, the work done by the gas is zero.\\nReason (R): The gas expands against zero opposing external pressure ($P_{\\text{ext}} = 0$).\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Thermodynamic work during an expansion against an external pressure is $W = \\int P_{\\text{ext}}\\,dV$. For free expansion into a vacuum, $P_{\\text{ext}} = 0$, so no work is performed by the gas.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The work done in an isobaric process for $n$ moles of an ideal gas when its temperature rises by $\\Delta T$ is equal to $n R \\Delta T$.\\nReason (R): From the ideal gas equation, $P\\Delta V = n R \\Delta T$ when pressure $P$ is kept constant.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "For an isobaric process, $W = P(V_2 - V_1) = P\\Delta V$. Differentiating the ideal gas equation $PV = nRT$ at constant pressure gives $P\\Delta V = nR\\Delta T$. Hence $W = nR\\Delta T$, and (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Work done by a gas during an isothermal expansion depends only on the temperature and the ratio of initial to final volumes.\\nReason (R): For an isothermal expansion of an ideal gas, $W = nRT \\ln(V_2/V_1)$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "For an ideal gas, integrating $P\\,dV = (nRT/V)dV$ at constant $T$ gives $W = nRT \\ln(V_2/V_1)$. This depends solely on $n$, $T$, and the volume ratio $V_2/V_1$.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): For a polytropic process characterized by $PV^x = \\text{constant}$ (where $x \\neq 1$), the work done is given by $W = \\frac{P_1 V_1 - P_2 V_2}{x - 1}$.\\nReason (R): Integrating $P\\,dV = C V^{-x}\\,dV$ from $V_1$ to $V_2$ directly yields $\\frac{P_1 V_1 - P_2 V_2}{x - 1}$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "$W = \\int_{V_1}^{V_2} C V^{-x}\\,dV = \\frac{C}{1 - x}[V_2^{1-x} - V_1^{1-x}] = \\frac{P_2 V_2 - P_1 V_1}{1 - x} = \\frac{P_1 V_1 - P_2 V_2}{x - 1}$. Both statements are true and (R) explains (A).",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): In compressing an ideal gas from volume $V_1$ to a smaller volume $V_2$, more work must be done on the gas in an adiabatic process than in an isothermal process.\\nReason (R): During adiabatic compression, temperature increases, causing the pressure at each intermediate volume to be higher than during isothermal compression.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "During compression, the adiabatic curve lies entirely above the isothermal curve because heating increases the pressure. The magnitude of work required $|W| = \\int P\\,dV$ is therefore greater for adiabatic compression.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The work done in a cyclic process depends on the coordinates chosen; the area in a $P-V$ diagram has dimensions of energy, but the area in a $P-T$ diagram does not.\\nReason (R): The product of pressure and volume has SI units of $\\text{N/m}^2 \\times \\text{m}^3 = \\text{N}\\cdot\\text{m} = \\text{J}$, whereas the product of pressure and temperature has units of $\\text{Pa}\\cdot\\text{K}$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Work is $\\int P\\,dV$, whose integrand is $P\\,dV$ (units of Joules). The area enclosed in a $P-V$ diagram directly represents work (Joules). In a $P-T$ diagram, the area enclosed has units of $\\text{Pa}\\cdot\\text{K}$, which is not energy.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): When an ideal gas expands into an evacuated chamber of non-rigid walls, the work done on the surrounding atmosphere may be non-zero.\\nReason (R): Even if expansion begins against a vacuum, if the container pushes against external atmospheric pressure, work is done against the atmosphere.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Work is done whenever a boundary displaces against a non-zero external pressure: $W = \\int P_{\\text{ext}}\\,dV$. If the boundary displaces the surrounding atmosphere, work is done against atmospheric pressure.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The work done in a quasi-static process can be calculated using $W = \\int P\\,dV$.\\nReason (R): In a quasi-static process, the system passes through a continuous sequence of equilibrium states where pressure is well-defined throughout the volume.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Quasi-static means infinitely slow, allowing thermodynamic coordinates like pressure and temperature to remain uniform and well-defined at each instant, enabling the integration $\\int P\\,dV$.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The work done by a gas in an expansion from state A to state B cannot be uniquely determined solely from the coordinates $(P_A, V_A)$ and $(P_B, V_B)$.\\nReason (R): Work done depends on the thermodynamic path along which the gas is taken from state A to state B.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Work is a path-dependent quantity. Infinitely many different paths can connect state A and state B, each enclosing a different area under the $P-V$ curve, so the end-state coordinates alone are insufficient.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): If a gas expands such that its pressure is inversely proportional to the square of its volume ($P \\propto 1/V^2$), the work done as volume doubles is $P_1 V_1 / 2$.\\nReason (R): For $P = C/V^2$, work done is $W = \\int_{V_1}^{2V_1} \\frac{C}{V^2}\\,dV = C\\left[\\frac{1}{V_1} - \\frac{1}{2V_1}\\right] = \\frac{C}{2V_1} = \\frac{P_1 V_1}{2}$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Since $C = P_1 V_1^2$, $W = \\int_{V_1}^{2V_1} C V^{-2}\\,dV = -C [1/V]_{V_1}^{2V_1} = C/(2V_1) = P_1 V_1^2 / (2V_1) = P_1 V_1 / 2$. Both statements are true and (R) gives the exact derivation.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): In an adiabatic expansion, the work done by the gas is done entirely at the expense of its internal energy.\\nReason (R): According to the first law of thermodynamics, $\\Delta Q = \\Delta U + W$. Since $\\Delta Q = 0$ in an adiabatic process, $W = -\\Delta U$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "For an adiabatic process, heat exchanged $\\Delta Q = 0$. Hence $W = -\\Delta U$. When the gas expands ($W > 0$), its internal energy decreases ($\\Delta U < 0$), causing the gas to cool.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The area under a $V-T$ indicator diagram represents the work done by the gas.\\nReason (R): The integral $\\int V\\,dT$ has the dimensions of energy for an ideal gas.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "(A) is false but (R) is true",
    "explanation": "(A) is false because work done is represented by the area under a $P-V$ diagram ($\\int P\\,dV$), not a $V-T$ diagram. (R) is also false as $V\\,dT$ has units $\\text{m}^3\\cdot\\text{K}$, not Joules, but among standard JEE patterns if (A) is false then (A) is false.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): For an ideal gas, the work done during an isobaric expansion is always less than the heat supplied to the gas.\\nReason (R): In an isobaric process, heat supplied goes into both increasing internal energy and doing mechanical work, so $W = \\Delta Q - \\Delta U < \\Delta Q$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "In an isobaric process, $\\Delta Q = n C_p \\Delta T$ and $W = n R \\Delta T$. Since $C_p = C_v + R > R$, the fraction of heat converted to work is $W/\\Delta Q = R/C_p = 1 - 1/\\gamma < 1$. Thus $W < \\Delta Q$.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): In a cyclic process, the net change in internal energy is zero, so the net work done equals the net heat absorbed.\\nReason (R): Internal energy is a state function, meaning its change over any closed cyclic path is zero ($\\oint dU = 0$).\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Because $U$ is a state function, $\\Delta U_{\\text{cycle}} = 0$. By the first law, $Q_{\\text{net}} = \\Delta U + W_{\\text{net}} = W_{\\text{net}}$. Hence net work equals net heat absorbed.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): Work done by an ideal gas during an expansion against a constant external pressure $P_{\\text{ext}}$ is $W = P_{\\text{ext}}(V_2 - V_1)$, even if the process is irreversible.\\nReason (R): Irreversible mechanical work is defined by the resisting external force integrated over the displacement of the system boundary.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Mechanical work done by a system on its surroundings is determined by the external resisting force: $W = \\int P_{\\text{ext}}\\,dV$. When $P_{\\text{ext}}$ is constant, $W = P_{\\text{ext}}\\Delta V$, regardless of internal non-equilibrium states.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): During a free expansion of an ideal gas, no work is done and the temperature of the gas remains unchanged.\\nReason (R): In free expansion, $W = 0$ and $Q = 0$, which implies $\\Delta U = 0$; for an ideal gas, internal energy depends solely on temperature.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Free expansion is adiabatic ($Q = 0$) and against vacuum ($W = 0$). Thus $\\Delta U = Q - W = 0$. For an ideal gas, $U = U(T)$, so $\\Delta U = 0$ implies $\\Delta T = 0$ (initial and final temperatures are equal).",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): The efficiency of a Carnot cycle is related to the net work done by the gas and the heat absorbed from the hot reservoir.\\nReason (R): Efficiency of any heat engine is defined as the ratio of net work output to the total heat input from the source, $\\eta = W_{\\text{net}}/Q_{\\text{in}}$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Thermal efficiency is fundamentally defined as desired energy output (work $W_{\\text{net}}$) divided by required energy input (heat supplied $Q_{\\text{in}}$). Both statements are true and (R) is the correct explanation of (A).",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Easy",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): If an ideal gas is taken through an elliptical cycle on a $P-V$ diagram with semi-axes $a = \\Delta P / 2$ and $b = \\Delta V / 2$, the work done in one cycle is $\\frac{\\pi}{4} \\Delta P \\Delta V$.\\nReason (R): The area of an ellipse with major and minor axes $\\Delta P$ and $\\Delta V$ is given by $\\pi \\left(\\frac{\\Delta P}{2}\\right)\\left(\\frac{\\Delta V}{2}\\right) = \\frac{\\pi}{4}\\Delta P\\Delta V$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "The area enclosed by an ellipse is $\\pi a b$. Here semi-axes are $a = \\Delta P / 2$ and $b = \\Delta V / 2$. Therefore, the area representing work done is $\\pi (\\Delta P / 2)(\\Delta V / 2) = \\frac{\\pi}{4} \\Delta P \\Delta V$.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\\nAssertion (A): When an ideal gas undergoes an expansion according to the law $P = \\alpha V$ (where $\\alpha$ is a positive constant), the work done as volume expands from $V_0$ to $2V_0$ is $\\frac{3}{2}\\alpha V_0^2$.\\nReason (R): The work done is $W = \\int_{V_0}^{2V_0} \\alpha V\\,dV = \\frac{\\alpha}{2}\\left[(2V_0)^2 - V_0^2\\right] = \\frac{3}{2}\\alpha V_0^2$.\\nIn the light of the above statements, choose the correct answer from the options given below:",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": "Both (A) and (R) are true and (R) is the correct explanation of (A)",
    "explanation": "Evaluating $W = \\int_{V_0}^{2V_0} P\\,dV = \\alpha \\int_{V_0}^{2V_0} V\\,dV = \\frac{\\alpha}{2}(4V_0^2 - V_0^2) = \\frac{3}{2}\\alpha V_0^2$. Both statements are true and (R) provides the exact mathematical reasoning.",
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "An ideal gas is taken through the cycle $A \\to B \\to C \\to A$ shown on a $P-V$ diagram. $A \\to B$ is an isobaric expansion at $P = 4\\times 10^5\\text{ N/m}^2$ from $V = 2\\times 10^{-3}\\text{ m}^3$ to $V = 6\\times 10^{-3}\\text{ m}^3$. $B \\to C$ is an isochoric process to $P = 1\\times 10^5\\text{ N/m}^2$, and $C \\to A$ is a linear path returning to state $A$. The net work done by the gas in one complete cycle is:",
    "options": [
      "$600\\text{ J}$",
      "$1200\\text{ J}$",
      "$800\\text{ J}$",
      "$400\\text{ J}$"
    ],
    "correctAnswer": "$600\\text{ J}$",
    "explanation": "The cycle forms a right-angled triangle on the $P-V$ diagram with vertices $A(2\\times 10^{-3}, 4\\times 10^5)$, $B(6\\times 10^{-3}, 4\\times 10^5)$, and $C(6\\times 10^{-3}, 1\\times 10^5)$.\\nBase $\\Delta V = (6 - 2)\\times 10^{-3} = 4\\times 10^{-3}\\text{ m}^3$.\\nHeight $\\Delta P = (4 - 1)\\times 10^5 = 3\\times 10^5\\text{ N/m}^2$.\\nThe cycle is traced clockwise ($A\\to B\\to C\\to A$), so work is positive:\\n$W = \\frac{1}{2} \\times \\text{base} \\times \\text{height} = \\frac{1}{2} \\times (4\\times 10^{-3}) \\times (3\\times 10^5) = 600\\text{ J}$.",
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "One mole of an ideal gas expands from volume $V$ to $2V$ along three different reversible paths: (1) Isobaric, (2) Isothermal, and (3) Adiabatic. If $W_1, W_2, W_3$ denote the work done along these three paths respectively, which of the following relations is correct?",
    "options": [
      "$W_1 > W_2 > W_3$",
      "$W_3 > W_2 > W_1$",
      "$W_2 > W_1 > W_3$",
      "$W_1 > W_3 > W_2$"
    ],
    "correctAnswer": "$W_1 > W_2 > W_3$",
    "explanation": "Starting from the same initial state $(P_0, V_0)$, during an expansion to $2V_0$:\\n1. Isobaric: pressure remains constant at $P_0$, highest curve.\\n2. Isothermal: $P = P_0 V_0 / V$, pressure drops with slope $-P/V$.\\n3. Adiabatic: $P = P_0 V_0^\\gamma / V^\\gamma$, pressure drops more steeply with slope $-\\gamma P/V$.\\nSince work is the area under the curve in a $P-V$ diagram, $W_1 > W_2 > W_3$.",
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "A thermodynamic system is taken from state $A$ to state $B$ along path $ACB$ and brought back to state $A$ along path $BDA$. The work done along path $ACB$ is $80\\text{ J}$ and the heat absorbed along $ACB$ is $100\\text{ J}$. If the work done along path $BDA$ is $-50\\text{ J}$, the heat released along path $BDA$ is:",
    "options": [
      "$-70\\text{ J}$",
      "$-30\\text{ J}$",
      "$50\\text{ J}$",
      "$-50\\text{ J}$"
    ],
    "correctAnswer": "$-70\\text{ J}$",
    "explanation": "For the path $ACB$:\\n$\\Delta U_{AB} = Q_{ACB} - W_{ACB} = 100 - 80 = 20\\text{ J}$.\\nFor the return path $BDA$ from state $B$ to state $A$:\\n$\\Delta U_{BA} = -\\Delta U_{AB} = -20\\text{ J}$.\\nFrom the first law for path $BDA$:\\n$Q_{BDA} = \\Delta U_{BA} + W_{BDA} = -20 + (-50) = -70\\text{ J}$.\\nHence, $70\\text{ J}$ of heat is released ($Q = -70\\text{ J}$).",
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "An ideal gas undergoes a cyclic process represented by an ellipse on the $P-V$ diagram, where pressure ranges between $1\\times 10^5\\text{ Pa}$ and $3\\times 10^5\\text{ Pa}$, and volume ranges between $2\\times 10^{-3}\\text{ m}^3$ and $4\\times 10^{-3}\\text{ m}^3$. The net work done by the gas in one complete clockwise cycle is:",
    "options": [
      "$314\\text{ J}$",
      "$628\\text{ J}$",
      "$157\\text{ J}$",
      "$1256\\text{ J}$"
    ],
    "correctAnswer": "$314\\text{ J}$",
    "explanation": "The semi-axes of the ellipse are:\\n$a = \\frac{P_{\\max} - P_{\\min}}{2} = \\frac{(3 - 1)\\times 10^5}{2} = 1\\times 10^5\\text{ Pa}$.\\n$b = \\frac{V_{\\max} - V_{\\min}}{2} = \\frac{(4 - 2)\\times 10^{-3}}{2} = 1\\times 10^{-3}\\text{ m}^3$.\\nWork done in one clockwise cycle is the enclosed area:\\n$W = \\pi a b = \\pi \\times (1\\times 10^5) \\times (1\\times 10^{-3}) = 100\\pi\\text{ J} \\approx 314\\text{ J}$.",
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "Two moles of an ideal monoatomic gas expand isothermally at temperature $T = 300\\text{ K}$ from an initial volume $V_0$ to $4V_0$. The work done by the gas is (Take $R = 8.314\\text{ J/(mol}\\cdot\\text{K)}$ and $\\ln 2 = 0.693$):",
    "options": [
      "$3457\\text{ J}$",
      "$1728\\text{ J}$",
      "$6914\\text{ J}$",
      "$864\\text{ J}$"
    ],
    "correctAnswer": "$3457\\text{ J}$",
    "explanation": "For isothermal expansion of an ideal gas:\\n$W = n R T \\ln\\left(\\frac{V_f}{V_i}\\right) = 2 \\times 8.314 \\times 300 \\times \\ln(4) = 4988.4 \\times 2\\ln 2 = 4988.4 \\times 1.3863 \\approx 3457\\text{ J}$.",
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "A sample of an ideal gas expands from volume $V_1$ to $V_2$ such that pressure depends on volume as $P = a V + b$, where $a$ and $b$ are constants. The work done by the gas during this expansion is:",
    "options": [
      "$\\frac{a}{2}(V_2^2 - V_1^2) + b(V_2 - V_1)$",
      "$a(V_2^2 - V_1^2) + b(V_2 - V_1)$",
      "$\\frac{a}{2}(V_2 - V_1)^2 + b(V_2 - V_1)$",
      "$\\frac{a+b}{2}(V_2^2 - V_1^2)$"
    ],
    "correctAnswer": "$\\frac{a}{2}(V_2^2 - V_1^2) + b(V_2 - V_1)$",
    "explanation": "Work done is given by:\\n$W = \\int_{V_1}^{V_2} P\\,dV = \\int_{V_1}^{V_2} (aV + b)\\,dV = \\left[ \\frac{a V^2}{2} + b V \\right]_{V_1}^{V_2} = \\frac{a}{2}(V_2^2 - V_1^2) + b(V_2 - V_1)$.",
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "An ideal gas is compressed to half its initial volume. In which of the following processes is the magnitude of work done on the gas minimum?",
    "options": [
      "Isobaric",
      "Isothermal",
      "Adiabatic",
      "Polytropic with index $n = 2$"
    ],
    "correctAnswer": "Isobaric",
    "explanation": "During compression from $V$ to $V/2$ starting at $(P_0, V_0)$:\\n- In an isobaric process, pressure remains constant at $P_0$.\\n- In isothermal compression, pressure increases as $P = P_0 V_0 / V > P_0$.\\n- In adiabatic compression, pressure increases as $P = P_0 (V_0/V)^\\gamma$, which is even higher than isothermal.\\n- For $n = 2$, pressure rises even faster.\\nSince the area under the curve represents work, the isobaric path has the lowest average pressure and hence the minimum magnitude of work done on the gas.",
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 1
  },
  {
    "question": "An ideal gas undergoes an isobaric expansion at a pressure of $2.5\\times 10^5\\text{ Pa}$ from an initial volume of $0.02\\text{ m}^3$ to a final volume of $0.06\\text{ m}^3$. The work done by the gas during this expansion is ______ $\\text{kJ}$.",
    "correctAnswer": "10",
    "solution": "For an isobaric process:\\n$W = P \\Delta V = (2.5\\times 10^5\\text{ Pa}) \\times (0.06 - 0.02\\text{ m}^3) = 2.5\\times 10^5 \\times 0.04 = 10000\\text{ J} = 10\\text{ kJ}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "Three moles of an ideal gas at temperature $300\\text{ K}$ are heated at constant pressure until the temperature reaches $400\\text{ K}$. The work done by the gas during this process is ______ $\\text{J}$. (Take $R = 8.31\\text{ J/(mol}\\cdot\\text{K)}$)",
    "correctAnswer": "2493",
    "solution": "For an isobaric process:\\n$W = P\\Delta V = n R \\Delta T = 3 \\times 8.31 \\times (400 - 300) = 3 \\times 8.31 \\times 100 = 2493\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "An ideal gas is taken through a cyclic process $ABCA$ on a $P-V$ diagram. Path $AB$ is at constant pressure $P = 5\\times 10^5\\text{ Pa}$ from $V_A = 1\\times 10^{-3}\\text{ m}^3$ to $V_B = 5\\times 10^{-3}\\text{ m}^3$. Path $BC$ is at constant volume $V = 5\\times 10^{-3}\\text{ m}^3$ down to $P_C = 2\\times 10^5\\text{ Pa}$, and path $CA$ is a straight line connecting $C$ back to $A$. The net work done by the gas in one complete cycle is ______ $\\text{J}$.",
    "correctAnswer": "600",
    "solution": "The cycle forms a right triangle on the $P-V$ diagram with:\\n$\\text{Base} = V_B - V_A = (5 - 1)\\times 10^{-3} = 4\\times 10^{-3}\\text{ m}^3$.\\n$\\text{Height} = P_A - P_C = (5 - 2)\\times 10^5 = 3\\times 10^5\\text{ Pa}$.\\nThe cycle is clockwise ($A \\to B \\to C \\to A$), so net work is positive:\\n$W_{\\text{net}} = \\frac{1}{2} \\times \\text{base} \\times \\text{height} = \\frac{1}{2} \\times 4\\times 10^{-3} \\times 3\\times 10^5 = 600\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A gas expands from volume $V_1 = 1\\text{ m}^3$ to $V_2 = 3\\text{ m}^3$ along a path where pressure varies linearly with volume as $P = (2V + 1)\\text{ kPa}$, with $V$ in $\\text{m}^3$. The work done by the gas during the expansion is ______ $\\text{kJ}$.",
    "correctAnswer": "10",
    "solution": "$W = \\int_{V_1}^{V_2} P\\,dV = \\int_{1}^{3} (2V + 1)\\,dV = \\left[ V^2 + V \\right]_{1}^{3} = (9 + 3) - (1 + 1) = 12 - 2 = 10\\text{ kJ}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "Two moles of an ideal gas undergo an adiabatic expansion such that the temperature decreases by $60\\text{ K}$. If $\\gamma = 1.4$ and $R = 8.3\\text{ J/(mol}\\cdot\\text{K)}$, the work done by the gas is ______ $\\text{J}$.",
    "correctAnswer": "2490",
    "solution": "For an adiabatic process:\\n$W = \\frac{n R \\Delta T}{\\gamma - 1}$.\\nHere $n = 2$, $\\Delta T = 60\\text{ K}$, $\\gamma - 1 = 1.4 - 1 = 0.4$, and $R = 8.3\\text{ J/(mol}\\cdot\\text{K)}$.\\n$W = \\frac{2 \\times 8.3 \\times 60}{0.4} = \\frac{996}{0.4} = 2490\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "An ideal gas is compressed isothermally at $300\\text{ K}$ to half its original volume. If the work done on the gas is $1730\\text{ J}$, the number of moles of the gas is ______ . (Take $R = 8.31\\text{ J/(mol}\\cdot\\text{K)}$ and $\\ln 2 = 0.693$)",
    "correctAnswer": "1",
    "solution": "Work done on the gas during isothermal compression is:\\n$W_{\\text{on}} = n R T \\ln\\left(\\frac{V_i}{V_f}\\right) = n R T \\ln 2$.\\nGiven $W_{\\text{on}} = 1730\\text{ J}$, $T = 300\\text{ K}$, $R = 8.31$, $\\ln 2 = 0.693$:\\n$n = \\frac{1730}{8.31 \\times 300 \\times 0.693} = \\frac{1730}{1727.6} \\approx 1\\text{ mole}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A closed cycle $ABCDA$ on a $P-V$ diagram consists of four processes: $AB$ at constant pressure $P_1 = 4\\times 10^5\\text{ Pa}$, $BC$ at constant volume $V_2 = 0.05\\text{ m}^3$, $CD$ at constant pressure $P_2 = 1\\times 10^5\\text{ Pa}$, and $DA$ at constant volume $V_1 = 0.02\\text{ m}^3$. The net work done by the gas in one cycle is ______ $\\text{kJ}$.",
    "correctAnswer": "9",
    "solution": "The cycle is a rectangle in the $P-V$ plane.\\n$\\Delta P = P_1 - P_2 = (4 - 1)\\times 10^5 = 3\\times 10^5\\text{ Pa}$.\\n$\\Delta V = V_2 - V_1 = 0.05 - 0.02 = 0.03\\text{ m}^3$.\\nTraversed clockwise ($A \\to B \\to C \\to D \\to A$), the net work done is:\\n$W_{\\text{net}} = \\Delta P \\times \\Delta V = (3\\times 10^5\\text{ Pa}) \\times (0.03\\text{ m}^3) = 9000\\text{ J} = 9\\text{ kJ}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "An ideal gas expands such that its pressure varies with volume as $P = \\alpha / V$, where $\\alpha = 500\\text{ J}$. The work done by the gas as its volume increases from $1\\text{ m}^3$ to $e^2\\text{ m}^3$ (where $e$ is the base of natural logarithms) is ______ $\\text{J}$.",
    "correctAnswer": "1000",
    "solution": "$W = \\int_{V_1}^{V_2} P\\,dV = \\int_{1}^{e^2} \\frac{\\alpha}{V}\\,dV = \\alpha [\\ln V]_{1}^{e^2} = \\alpha (2 - 0) = 2\\alpha$.\\nGiven $\\alpha = 500\\text{ J}$:\\n$W = 2 \\times 500 = 1000\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A gas expands from an initial state $(P_1 = 3\\times 10^5\\text{ Pa}, V_1 = 2\\times 10^{-3}\\text{ m}^3)$ to a final state $(P_2 = 1\\times 10^5\\text{ Pa}, V_2 = 6\\times 10^{-3}\\text{ m}^3)$ along a straight line path on a $P-V$ diagram. The work done by the gas during this process is ______ $\\text{J}$.",
    "correctAnswer": "800",
    "solution": "The path is a straight line, so the area under the $P-V$ diagram is a trapezium:\\n$W = \\frac{P_1 + P_2}{2} \\times (V_2 - V_1) = \\frac{(3 + 1)\\times 10^5}{2} \\times (6 - 2)\\times 10^{-3} = (2\\times 10^5) \\times (4\\times 10^{-3}) = 800\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "One mole of a monoatomic gas ($\\gamma = 5/3$) undergoes an adiabatic expansion where its volume increases by a factor of $8$. If the initial temperature was $400\\text{ K}$, the work done by the gas is ______ $\\text{J}$. (Take $R = 8.31\\text{ J/(mol}\\cdot\\text{K)}$)",
    "correctAnswer": "3740",
    "solution": "For adiabatic expansion: $T_2 = T_1 (V_1/V_2)^{\\gamma - 1}$.\\nHere $\\gamma - 1 = 5/3 - 1 = 2/3$.\\n$T_2 = 400 \\times (1/8)^{2/3} = 400 \\times (1/2)^2 = 400 \\times 1/4 = 100\\text{ K}$.\\nWork done in adiabatic expansion is:\\n$W = \\frac{n R (T_1 - T_2)}{\\gamma - 1} = \\frac{1 \\times 8.31 \\times (400 - 100)}{2/3} = \\frac{8.31 \\times 300}{2/3} = 8.31 \\times 450 = 3739.5 \\approx 3740\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A heat engine carries $0.5\\text{ mol}$ of an ideal gas through a cycle where net work done is $1200\\text{ J}$. If the engine absorbs $4000\\text{ J}$ of heat during each cycle, the efficiency of the engine is ______ $\\%$.",
    "correctAnswer": "30",
    "solution": "Thermal efficiency of a heat engine is given by:\\n$\\eta = \\frac{W_{\\text{net}}}{Q_{\\text{in}}} = \\frac{1200\\text{ J}}{4000\\text{ J}} = 0.30 = 30\\%$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "An ideal gas is taken from state $A$ to state $B$ along path 1 where work done is $40\\text{ J}$, and along path 2 where work done is $60\\text{ J}$. If the heat absorbed along path 1 is $90\\text{ J}$, then the heat absorbed along path 2 is ______ $\\text{J}$.",
    "correctAnswer": "110",
    "solution": "Change in internal energy depends only on the initial and final states:\\n$\\Delta U = Q_1 - W_1 = 90 - 40 = 50\\text{ J}$.\\nFor path 2 between the same two states:\\n$Q_2 = \\Delta U + W_2 = 50 + 60 = 110\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A gas expands from volume $V_0$ to $2V_0$ under the process $P = c V^2$, where $c = 3\\times 10^5\\text{ N/m}^8$ and $V_0 = 0.1\\text{ m}^3$. The work done by the gas during this expansion is ______ $\\text{J}$.",
    "correctAnswer": "700",
    "solution": "$W = \\int_{V_0}^{2V_0} P\\,dV = c \\int_{V_0}^{2V_0} V^2\\,dV = \\frac{c}{3}\\left[ (2V_0)^3 - V_0^3 \\right] = \\frac{c}{3} (7 V_0^3) = \\frac{7}{3} c V_0^3$.\\nGiven $c = 3\\times 10^5$ and $V_0 = 0.1\\text{ m}^3$ ($V_0^3 = 10^{-3}\\text{ m}^9$):\\n$W = \\frac{7}{3} \\times (3\\times 10^5) \\times 10^{-3} = 7 \\times 100 = 700\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "An ideal gas undergoes a polytropic process $PV^2 = \\text{constant}$ from initial state $(P_1 = 4\\times 10^5\\text{ Pa}, V_1 = 0.01\\text{ m}^3)$ to final volume $V_2 = 0.02\\text{ m}^3$. The work done by the gas is ______ $\\text{J}$.",
    "correctAnswer": "2000",
    "solution": "For $PV^n = \\text{constant}$ with $n = 2$:\\n$P_2 = P_1 (V_1/V_2)^2 = 4\\times 10^5 \\times (0.01/0.02)^2 = 4\\times 10^5 \\times 1/4 = 1\\times 10^5\\text{ Pa}$.\\nWork done is:\\n$W = \\frac{P_1 V_1 - P_2 V_2}{n - 1} = \\frac{(4\\times 10^5 \\times 0.01) - (1\\times 10^5 \\times 0.02)}{2 - 1} = 4000 - 2000 = 2000\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "During a cyclic process, a gas absorbs $500\\text{ J}$ of heat during expansion and releases $350\\text{ J}$ of heat during compression. The work done by the gas in one complete cycle is ______ $\\text{J}$.",
    "correctAnswer": "150",
    "solution": "For a complete cyclic process, the net change in internal energy is zero ($\\Delta U = 0$).\\nFrom the first law of thermodynamics:\\n$W_{\\text{net}} = Q_{\\text{net}} = Q_{\\text{absorbed}} - Q_{\\text{released}} = 500 - 350 = 150\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "An ideal gas expands from volume $V_1 = 2\\text{ m}^3$ to $V_2 = 6\\text{ m}^3$ at a constant pressure of $P = 150\\text{ kPa}$. The work done by the gas is ______ $\\text{kJ}$.",
    "correctAnswer": "600",
    "solution": "$W = P (V_2 - V_1) = 150\\text{ kPa} \\times (6 - 2\\text{ m}^3) = 150 \\times 4 = 600\\text{ kJ}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "One mole of an ideal gas is compressed isothermally at $27^\\circ\\text{C}$ to $1/e$ times its initial volume. The work done on the gas during compression is ______ $\\text{J}$. (Take $R = 8.31\\text{ J/(mol}\\cdot\\text{K)}$)",
    "correctAnswer": "2493",
    "solution": "$T = 27 + 273 = 300\\text{ K}$.\\nWork done on the gas is:\\n$W_{\\text{on}} = n R T \\ln\\left(\\frac{V_i}{V_f}\\right) = 1 \\times 8.31 \\times 300 \\times \\ln(e) = 2493 \\times 1 = 2493\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "In a cyclic process $ABCA$, the vertices on the $P-V$ plane are $A(1\\times 10^5\\text{ Pa}, 1\\text{ L})$, $B(3\\times 10^5\\text{ Pa}, 1\\text{ L})$, and $C(1\\times 10^5\\text{ Pa}, 4\\text{ L})$. The net work done by the gas over cycle $ABCA$ is ______ $\\text{J}$.",
    "correctAnswer": "300",
    "solution": "The cycle is a triangle on the $P-V$ diagram:\\n$\\Delta P = (3 - 1)\\times 10^5 = 2\\times 10^5\\text{ Pa}$.\\n$\\Delta V = (4 - 1)\\text{ L} = 3\\text{ L} = 3\\times 10^{-3}\\text{ m}^3$.\\nTraversed in clockwise direction ($A(1,1) \\to B(1,3) \\to C(4,1) \\to A(1,1)$):\\n$W = \\frac{1}{2} \\times \\Delta P \\times \\Delta V = \\frac{1}{2} \\times 2\\times 10^5 \\times 3\\times 10^{-3} = 300\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A cylinder fitted with a frictionless piston contains $2\\text{ moles}$ of an ideal gas at $300\\text{ K}$. The gas is heated isobarically so that its volume doubles. The work done by the gas is ______ $\\text{J}$. (Take $R = 8.31\\text{ J/(mol}\\cdot\\text{K)}$)",
    "correctAnswer": "4986",
    "solution": "At constant pressure, $V \\propto T$. Doubling volume means temperature doubles from $T_1 = 300\\text{ K}$ to $T_2 = 600\\text{ K}$.\\n$\\Delta T = 600 - 300 = 300\\text{ K}$.\\nWork done is:\\n$W = n R \\Delta T = 2 \\times 8.31 \\times 300 = 4986\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Medium",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  },
  {
    "question": "A thermodynamic engine operates on a cycle where work output is $500\\text{ J}$ and efficiency is $25\\%$. The heat rejected to the sink in each cycle is ______ $\\text{J}$.",
    "correctAnswer": "1500",
    "solution": "$\\eta = \\frac{W}{Q_{\\text{in}}} \\implies Q_{\\text{in}} = \\frac{W}{\\eta} = \\frac{500}{0.25} = 2000\\text{ J}$.\\nHeat rejected to the sink is:\\n$Q_{\\text{out}} = Q_{\\text{in}} - W = 2000 - 500 = 1500\\text{ J}$.",
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Thermodynamics",
    "subtopic": "Work done in thermodynamic processes",
    "class": "Class 11",
    "difficulty": "Hard",
    "examType": "JEE Mains",
    "marks": 4,
    "negativeMarks": 0
  }
];
