module.exports = [
  {
    "question": "Assertion (A): In an ideal LC circuit, electrical oscillations continue indefinitely without damping.\nReason (R): An ideal LC circuit contains zero ohmic resistance, so no electromagnetic energy is dissipated as Joule heat.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Total electromagnetic energy $U = \\frac{q^2}{2C} + \\frac{1}{2} L I^2$ is conserved because there is no resistance to convert energy into heat ($R = 0$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an LC circuit, the electric energy of the capacitor and magnetic energy of the inductor oscillate with twice the frequency of the current.\nReason (R): The charge varies as $q(t) = Q_0 \\cos(\\omega t)$, and the electric energy $U_E \\propto q^2 = Q_0^2 \\cos^2(\\omega t) = \\frac{Q_0^2}{2}[1 + \\cos(2\\omega t)]$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Squaring the sinusoidal term yields a cosine at frequency $2\\omega$. Thus both electric and magnetic energies oscillate with frequency $2f$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When the charge on the capacitor is $\\frac{Q_0}{\\sqrt{2}}$, the energy stored in the capacitor equals the energy stored in the inductor.\nReason (R): At this instant, the electrostatic energy is $U_E = \\frac{q^2}{2C} = \\frac{1}{2}\\left(\\frac{Q_0^2}{2C}\\right)$, which is exactly half of the total initial energy.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Total energy $U = \\frac{Q_0^2}{2C}$. When $q = \\frac{Q_0}{\\sqrt{2}}$, $U_E = \\frac{(Q_0/\\sqrt{2})^2}{2C} = \\frac{1}{2} U$. By conservation of energy, $U_B = U - U_E = \\frac{1}{2} U$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In the mechanical analogy of an LC circuit, inductance $L$ corresponds to mass $m$, and reciprocal of capacitance $\\frac{1}{C}$ corresponds to spring constant $k$.\nReason (R): The differential equation for an LC circuit is $L\\frac{d^2 q}{dt^2} + \\frac{1}{C}q = 0$, which is mathematically isomorphic to the harmonic oscillator equation $m\\frac{d^2 x}{dt^2} + kx = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Comparing $L\\ddot{q} + \\frac{1}{C}q = 0$ with $m\\ddot{x} + kx = 0$, charge $q \\leftrightarrow x$, current $I = \\dot{q} \\leftrightarrow v = \\dot{x}$, $L \\leftrightarrow m$, and $\\frac{1}{C} \\leftrightarrow k$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The maximum current in an LC circuit is $I_0 = \\frac{Q_0}{\\sqrt{LC}}$, where $Q_0$ is the initial maximum charge on the capacitor.\nReason (R): By conservation of energy, the maximum magnetic energy stored in the inductor equals the maximum electrostatic energy initially stored in the capacitor: $\\frac{1}{2} L I_0^2 = \\frac{Q_0^2}{2C}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Equating $\\frac{1}{2} L I_0^2 = \\frac{Q_0^2}{2C}$ yields $I_0^2 = \\frac{Q_0^2}{LC} \\implies I_0 = \\frac{Q_0}{\\sqrt{LC}} = \\omega Q_0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When the current in an LC oscillation is maximum, the charge on the capacitor is zero.\nReason (R): Current is the time rate of change of charge, $I = -\\frac{dq}{dt}$, and the derivative of a cosine function is maximum when the cosine itself is zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "With $q(t) = Q_0 \\cos(\\omega t)$, $I(t) = \\omega Q_0 \\sin(\\omega t)$. When $I$ is maximum ($\\sin(\\omega t) = 1$), $\\cos(\\omega t) = 0$, so $q = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The natural frequency of an LC oscillator decreases if a dielectric slab is inserted between the capacitor plates.\nReason (R): Inserting a dielectric slab increases the capacitance $C$ by a factor of dielectric constant $K$, and the frequency is inversely proportional to $\\sqrt{C}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Frequency $f = \\frac{1}{2\\pi\\sqrt{LC}}$. Since $C' = K C > C$, $f' = \\frac{f}{\\sqrt{K}} < f$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The natural frequency of an LC circuit decreases if a soft iron core is inserted into the inductor.\nReason (R): The self-inductance $L$ increases due to the high magnetic permeability of iron, and frequency is given by $f = \\frac{1}{2\\pi\\sqrt{LC}}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Inductance increases to $L' = \\mu_r L$. As $f \\propto \\frac{1}{\\sqrt{L}}$, increasing $L$ decreases the oscillation frequency. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Real LC circuits experience damped oscillations even if the wires have negligible electrical resistance.\nReason (R): Accelerating charges in the oscillating circuit continuously radiate electromagnetic waves into space, carrying away energy.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Even with $R = 0$, energy is lost via electromagnetic radiation at the oscillation frequency, causing eventual decay of the oscillations. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The phase difference between the voltage across the capacitor and the current in an LC circuit is $\\frac{\\pi}{2}$.\nReason (R): Charge on the capacitor is $q = Q_0 \\cos(\\omega t)$ and current is $I = -\\omega Q_0 \\sin(\\omega t) = \\omega Q_0 \\cos(\\omega t + \\pi/2)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The capacitor voltage is $V_C = \\frac{q}{C} = \\frac{Q_0}{C}\\cos(\\omega t)$, while current is $I = I_0 \\cos(\\omega t + \\pi/2)$, showing a phase lead of $\\pi/2$ for current over voltage. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): At time $t = \\frac{T}{8}$ after the start of oscillation from full charge, the magnetic energy equals the electrostatic energy.\nReason (R): At $t = \\frac{T}{8}$, the phase is $\\omega t = \\frac{2\\pi}{T} \\frac{T}{8} = \\frac{\\pi}{4}$, so $q = Q_0 \\cos(\\pi/4) = \\frac{Q_0}{\\sqrt{2}}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $q = \\frac{Q_0}{\\sqrt{2}}$, $U_E = \\frac{q^2}{2C} = \\frac{Q_0^2}{4C} = \\frac{1}{2} U_{total}$. Hence $U_B = U_{total} - U_E = U_E$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an LC oscillation, the rate of change of current $\\frac{dI}{dt}$ is maximum when the current itself is zero.\nReason (R): From Kirchhoff's loop rule, $-L\\frac{dI}{dt} - \\frac{q}{C} = 0$, so $\\left|\\frac{dI}{dt}\\right| = \\frac{q}{LC}$, which is maximum when charge $q = Q_0$ (at which instant $I = 0$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "When $I = 0$, charge is at its maximum $Q_0$. Therefore, $\\left|\\frac{dI}{dt}\\right| = \\frac{Q_0}{LC}$ is maximum. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The total energy in an LC circuit at any instant is independent of time.\nReason (R): The time-dependent terms in the electrostatic energy and magnetic energy satisfy the trigonometric identity $\\cos^2(\\omega t) + \\sin^2(\\omega t) = 1$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$U = U_E + U_B = \\frac{Q_0^2}{2C}\\cos^2(\\omega t) + \\frac{Q_0^2}{2C}\\sin^2(\\omega t) = \\frac{Q_0^2}{2C}[\\cos^2(\\omega t) + \\sin^2(\\omega t)] = \\frac{Q_0^2}{2C}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If both inductance $L$ and capacitance $C$ are doubled, the resonant frequency of the LC circuit is halved.\nReason (R): The frequency of an LC oscillator is inversely proportional to the product $\\sqrt{LC}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\omega = \\frac{1}{\\sqrt{LC}}$, replacing $L \\to 2L$ and $C \\to 2C$ yields $\\omega' = \\frac{1}{\\sqrt{2L \\times 2C}} = \\frac{1}{2\\sqrt{LC}} = \\frac{\\omega}{2}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): An LC circuit can act as a tank circuit for generating continuous high-frequency oscillations when coupled with a transistor.\nReason (R): The transistor provides positive feedback and supplies energy from a DC battery to compensate for resistive and radiative losses in the tank circuit.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "A tank circuit loses energy gradually due to resistance. An active element (transistor) with tuned positive feedback replenishes the lost energy every cycle to sustain undamped oscillations. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The current in an LC circuit leads the charge on the capacitor by a phase angle of $90^\\circ$.\nReason (R): Current is the time derivative of charge, which introduces a leading phase factor of $\\frac{\\pi}{2}$ radians.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$I = \\frac{dq}{dt} = \\frac{d}{dt}[Q_0 \\sin(\\omega t)] = \\omega Q_0 \\cos(\\omega t) = \\omega Q_0 \\sin(\\omega t + \\pi/2)$. Thus current leads charge by $90^\\circ$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If an inductor with non-zero internal resistance is used in an LC circuit, the amplitude of charge oscillations decays exponentially with time.\nReason (R): The resistance dissipates energy at the instantaneous rate of $I^2 R$, leading to a damped harmonic equation of the form $L\\frac{d^2 q}{dt^2} + R\\frac{dq}{dt} + \\frac{1}{C}q = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The presence of the damping term $R\\dot{q}$ produces solutions with an exponential decay envelope $e^{-\\gamma t}$, where $\\gamma = \\frac{R}{2L}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a critically damped LCR circuit, no electrical oscillations occur.\nReason (R): Critical damping occurs when $R = 2\\sqrt{\\frac{L}{C}}$, causing the system to return to equilibrium in the shortest possible time without crossing zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "When $R^2 = \\frac{4L}{C}$, the roots of the auxiliary equation are real and equal, resulting in non-oscillatory, aperiodic return to zero charge. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): At the instant when the magnetic energy is three times the electrostatic energy, the charge on the capacitor is $\\frac{Q_0}{2}$.\nReason (R): Total energy is $U = U_E + U_B = U_E + 3U_E = 4U_E$. Therefore, $U_E = \\frac{1}{4}U_{total} \\implies \\frac{q^2}{2C} = \\frac{1}{4}\\frac{Q_0^2}{2C} \\implies q = \\frac{Q_0}{2}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "With $U_B = 3U_E$, $U_{total} = 4U_E$, which gives $q^2 = \\frac{Q_0^2}{4} \\implies q = \\frac{Q_0}{2}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The angular frequency of oscillation in an LC circuit is independent of the initial charge given to the capacitor.\nReason (R): The natural frequency $\\omega = \\frac{1}{\\sqrt{LC}}$ is determined solely by the circuit parameters $L$ and $C$, not by the initial conditions.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The governing linear differential equation has natural frequency $\\omega_0 = \\frac{1}{\\sqrt{LC}}$, which is an intrinsic characteristic of the system regardless of initial amplitude. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): During LC oscillations, the magnetic field energy is maximum when the electric field inside the capacitor is zero.\nReason (R): Electric field in the capacitor is proportional to charge ($E = \\frac{q}{\\varepsilon_0 A}$), and when $q = 0$, all the energy resides in the magnetic field of the inductor ($I = I_0$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "When $q = 0$, electrostatic energy $U_E = 0$. By conservation of energy, $U_B = U_{total} = \\frac{1}{2} L I_0^2$ is maximum. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The dimension of $\\sqrt{LC}$ is the same as the dimension of time.\nReason (R): The product of inductive reactance and capacitive reactance is equal to the square of a resistance.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 1,
    "explanation": "Since $\\omega = \\frac{1}{\\sqrt{LC}}$ has dimensions $[T^{-1}]$, $\\sqrt{LC}$ has dimensions $[T]$. Also, $X_L X_C = (\\omega L)\\left(\\frac{1}{\\omega C}\\right) = \\frac{L}{C} = [\\Omega]^2$, which is also true, but (R) is not the explanation of why $\\sqrt{LC}$ has units of time. (B) is correct.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If the capacitance in an LC circuit is quadrupled, the time period of oscillation is doubled.\nReason (R): The time period of LC oscillation is directly proportional to the square root of capacitance: $T = 2\\pi\\sqrt{LC}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $T \\propto \\sqrt{C}$, replacing $C$ with $4C$ gives $T' = \\sqrt{4} T = 2T$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A charged capacitor is connected across an inductor at $t = 0$. The first instant at which the energy is equally divided between capacitor and inductor is $t = \\frac{T}{8}$.\nReason (R): The charge varies as $q = Q_0 \\cos\\left(\\frac{2\\pi t}{T}\\right)$, and $q = \\frac{Q_0}{\\sqrt{2}}$ when $\\frac{2\\pi t}{T} = \\frac{\\pi}{4} \\implies t = \\frac{T}{8}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Energy is equally shared when $U_E = \\frac{1}{2} U_{max}$, which requires $q^2 = \\frac{Q_0^2}{2} \\implies q = \\frac{Q_0}{\\sqrt{2}}$. For $q = Q_0 \\cos(\\omega t)$, $\\omega t = \\frac{\\pi}{4} \\implies t = \\frac{\\pi/4}{2\\pi/T} = \\frac{T}{8}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an underdamped LCR circuit, the frequency of oscillation is slightly lower than the undamped resonant frequency $\\omega_0 = \\frac{1}{\\sqrt{LC}}$.\nReason (R): The damped angular frequency is given by $\\omega' = \\sqrt{\\omega_0^2 - \\left(\\frac{R}{2L}\\right)^2} < \\omega_0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Resistance reduces the oscillation frequency according to $\\omega' = \\sqrt{\\frac{1}{LC} - \\frac{R^2}{4L^2}}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): An LC circuit can never oscillate at optical frequencies.\nReason (R): At extremely high frequencies, stray capacitances, lead inductances, and skin effect significantly alter the circuit behavior, and physical components cannot be made small enough.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Optical frequencies are around $10^{14}\\text{ Hz}$. At such frequencies, conventional lumped LC parameters are not physically realizable. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A capacitor of capacitance $25\\ \\mu\\text{F}$ is charged to $100\\text{ V}$ and then connected across an inductor of $10\\text{ mH}$. The maximum current in the circuit during oscillation is:",
    "options": [
      "5.0 A",
      "2.5 A",
      "10.0 A",
      "1.25 A"
    ],
    "correctAnswer": 0,
    "explanation": "Initial charge $Q_0 = C V_0 = 25 \\times 10^{-6} \\times 100 = 2.5 \\times 10^{-3}\\text{ C}$. Resonant frequency $\\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{10 \\times 10^{-3} \\times 25 \\times 10^{-6}}} = \\frac{1}{\\sqrt{25 \\times 10^{-8}}} = \\frac{10^4}{5} = 2000\\text{ rad/s}$. Peak current $I_0 = \\omega Q_0 = 2000 \\times 2.5 \\times 10^{-3} = 5.0\\text{ A}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an oscillating LC circuit, the maximum charge on the capacitor is $Q_0$. The charge on the capacitor when the energy is shared equally between the electric and magnetic fields is:",
    "options": [
      "$\\frac{Q_0}{\\sqrt{2}}$",
      "$\\frac{Q_0}{2}$",
      "$\\frac{Q_0}{\\sqrt{3}}$",
      "$\\frac{Q_0}{4}$"
    ],
    "correctAnswer": 0,
    "explanation": "Total energy $U = \\frac{Q_0^2}{2C}$. When energies are equal, $U_E = \\frac{1}{2}U = \\frac{Q_0^2}{4C}$. Also $U_E = \\frac{q^2}{2C}$. Equating the two gives $\\frac{q^2}{2C} = \\frac{Q_0^2}{4C} \\implies q^2 = \\frac{Q_0^2}{2} \\implies q = \\frac{Q_0}{\\sqrt{2}}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An LC circuit contains a $20\\text{ mH}$ inductor and a $50\\ \\mu\\text{F}$ capacitor with an initial charge of $10\\text{ mC}$. The resistance of the circuit is negligible. At what time $t$ will the energy stored be completely magnetic for the first time?",
    "options": [
      "$\\frac{\\pi}{2}\\text{ ms}$",
      "$\\pi\\text{ ms}$",
      "$2\\pi\\text{ ms}$",
      "$\\frac{\\pi}{4}\\text{ ms}$"
    ],
    "correctAnswer": 0,
    "explanation": "Angular frequency $\\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{20 \\times 10^{-3} \\times 50 \\times 10^{-6}}} = \\frac{1}{\\sqrt{10^{-6}}} = 1000\\text{ rad/s}$. Time period $T = \\frac{2\\pi}{\\omega} = 2\\pi \\times 10^{-3}\\text{ s} = 2\\pi\\text{ ms}$. Energy is completely magnetic when $q = 0$, which occurs at $t = \\frac{T}{4} = \\frac{2\\pi\\text{ ms}}{4} = \\frac{\\pi}{2}\\text{ ms}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC oscillation, the maximum potential difference across the capacitor is $V_0$. When the potential difference across the capacitor is $\\frac{V_0}{2}$, the current through the inductor is:",
    "options": [
      "$\\frac{\\sqrt{3}}{2} I_0$",
      "$\\frac{1}{2} I_0$",
      "$\\frac{1}{\\sqrt{2}} I_0$",
      "$\\frac{3}{4} I_0$"
    ],
    "correctAnswer": 0,
    "explanation": "Total energy is $U = \\frac{1}{2} C V_0^2 = \\frac{1}{2} L I_0^2$. When $V = \\frac{V_0}{2}$, $U_E = \\frac{1}{2} C \\left(\\frac{V_0}{2}\\right)^2 = \\frac{1}{4} U$. Magnetic energy is $U_B = U - U_E = \\frac{3}{4} U$. Thus $\\frac{1}{2} L I^2 = \\frac{3}{4}\\left(\\frac{1}{2} L I_0^2\\right) \\implies I = \\frac{\\sqrt{3}}{2} I_0$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The frequency of oscillation of an LC circuit is $f$. The frequency at which the electrostatic energy stored in the capacitor oscillates is:",
    "options": [
      "$2f$",
      "$f$",
      "$\\frac{f}{2}$",
      "$4f$"
    ],
    "correctAnswer": 0,
    "explanation": "Electrostatic energy is $U_E = \\frac{q^2}{2C} = \\frac{Q_0^2}{2C}\\cos^2(\\omega t) = \\frac{Q_0^2}{4C}[1 + \\cos(2\\omega t)]$. The angular frequency of energy oscillation is $2\\omega$, so its frequency is $2f$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An LC circuit oscillates with angular frequency $\\omega$. If the initial charge is $Q_0$, the current $I(t)$ at time $t$ (taking $q(0) = Q_0$) is given by:",
    "options": [
      "$-\\omega Q_0 \\sin(\\omega t)$",
      "$\\omega Q_0 \\cos(\\omega t)$",
      "$-\\frac{Q_0}{\\omega} \\sin(\\omega t)$",
      "$\\frac{Q_0}{\\omega} \\cos(\\omega t)$"
    ],
    "correctAnswer": 0,
    "explanation": "Since $q(t) = Q_0 \\cos(\\omega t)$, the current is $I(t) = \\frac{dq}{dt} = -\\omega Q_0 \\sin(\\omega t)$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC oscillation, the ratio of electrostatic energy to magnetic energy at an instant when the charge on the capacitor is $\\frac{\\sqrt{3}}{2} Q_0$ is:",
    "options": [
      "$3 : 1$",
      "$1 : 3$",
      "$1 : 1$",
      "$9 : 1$"
    ],
    "correctAnswer": 0,
    "explanation": "$U_E = \\frac{q^2}{2C} = \\frac{3}{4}\\left(\\frac{Q_0^2}{2C}\\right) = \\frac{3}{4} U_{total}$. By conservation of energy, $U_B = U_{total} - U_E = \\frac{1}{4} U_{total}$. Thus $\\frac{U_E}{U_B} = \\frac{3/4}{1/4} = 3 : 1$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A capacitor of $10\\ \\mu\\text{F}$ is charged to $50\\text{ V}$ and connected across a $0.1\\text{ H}$ inductor of zero resistance. The maximum current in the circuit in amperes is:",
    "options": [],
    "correctAnswer": 0.5,
    "numericalAnswer": 0.5,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{0.1 \\times 10^{-5}}} = 1000\\text{ rad/s}$. $Q_0 = C V = 10^{-5} \\times 50 = 5 \\times 10^{-4}\\text{ C}$. Peak current $I_0 = \\omega Q_0 = 1000 \\times 5 \\times 10^{-4} = 0.5\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An LC circuit contains an inductor $L = 25\\text{ mH}$ and a capacitor $C = 40\\ \\mu\\text{F}$. The natural angular frequency of oscillation in $\\text{rad/s}$ is:",
    "options": [],
    "correctAnswer": 1000,
    "numericalAnswer": 1000,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{25 \\times 10^{-3} \\times 40 \\times 10^{-6}}} = \\frac{1}{\\sqrt{10^{-6}}} = 1000\\text{ rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A $1\\ \\mu\\text{F}$ capacitor is charged to $100\\text{ V}$ and then connected across an inductor of $4\\text{ mH}$. The total energy stored in the circuit in millijoules is:",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "$U = \\frac{1}{2} C V_0^2 = \\frac{1}{2} \\times 10^{-6} \\times 10000 = 5 \\times 10^{-3}\\text{ J} = 5\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit, the initial maximum charge on the capacitor is $4\\ \\mu\\text{C}$. When the charge becomes $2\\ \\mu\\text{C}$, the percentage of total energy stored as magnetic energy in the inductor is:",
    "options": [],
    "correctAnswer": 75,
    "numericalAnswer": 75,
    "explanation": "$U_E = \\frac{q^2}{2C} = \\left(\\frac{2}{4}\\right)^2 U_{total} = \\frac{1}{4} U_{total} = 25\\%$. Therefore, $U_B = 100\\% - 25\\% = 75\\%$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An LC circuit has $L = 20\\text{ mH}$ and $C = 50\\ \\mu\\text{F}$. The initial charge on the capacitor is $2\\text{ mC}$. The maximum current in amperes is:",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{20 \\times 10^{-3} \\times 50 \\times 10^{-6}}} = \\frac{1}{\\sqrt{10^{-6}}} = 1000\\text{ rad/s}$. Peak current $I_0 = \\omega Q_0 = 1000 \\times 2 \\times 10^{-3} = 2\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A capacitor of $4\\ \\mu\\text{F}$ is charged to $200\\text{ V}$ and connected to an inductor of $100\\ \\mu\\text{H}$. The maximum current in the circuit in amperes is:",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "$\\frac{1}{2} L I_0^2 = \\frac{1}{2} C V_0^2 \\implies I_0 = V_0 \\sqrt{\\frac{C}{L}} = 200 \\times \\sqrt{\\frac{4 \\times 10^{-6}}{100 \\times 10^{-6}}} = 200 \\times 0.2 = 40\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit, the maximum current is $4\\text{ A}$ and the maximum voltage across the capacitor is $200\\text{ V}$. If $C = 5\\ \\mu\\text{F}$, the inductance $L$ in millihenries is:",
    "options": [],
    "correctAnswer": 12.5,
    "numericalAnswer": 12.5,
    "explanation": "$\\frac{1}{2} L I_0^2 = \\frac{1}{2} C V_0^2 \\implies L = C \\left(\\frac{V_0}{I_0}\\right)^2 = 5 \\times 10^{-6} \\times 2500 = 12.5\\text{ mH}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An LC circuit has $L = 0.5\\text{ H}$ and $C = 8\\ \\mu\\text{F}$. The maximum charge on the capacitor is $4\\text{ mC}$. The maximum energy stored in the magnetic field in millijoules is:",
    "options": [],
    "correctAnswer": 1000,
    "numericalAnswer": 1000,
    "explanation": "$U_{max} = \\frac{Q_0^2}{2C} = \\frac{(4 \\times 10^{-3})^2}{2 \\times 8 \\times 10^{-6}} = 1\\text{ J} = 1000\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit oscillating at $500\\text{ Hz}$, the electrostatic energy stored in the capacitor oscillates with a frequency of $\\text{Hz}$:",
    "options": [],
    "correctAnswer": 1000,
    "numericalAnswer": 1000,
    "explanation": "Frequency of energy oscillation $f_{energy} = 2 f_{circuit} = 2 \\times 500 = 1000\\text{ Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An LC circuit consists of an inductor $L = 1\\text{ H}$ and a capacitor $C = 4\\ \\mu\\text{F}$. The angular frequency of oscillation in $\\text{rad/s}$ is:",
    "options": [],
    "correctAnswer": 500,
    "numericalAnswer": 500,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{1 \\times 4 \\times 10^{-6}}} = \\frac{1000}{2} = 500\\text{ rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A $2\\ \\mu\\text{F}$ capacitor is connected across an inductor of $500\\text{ mH}$. The resonant angular frequency $\\omega$ in $\\text{rad/s}$ is:",
    "options": [],
    "correctAnswer": 1000,
    "numericalAnswer": 1000,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{LC}} = \\frac{1}{\\sqrt{0.5 \\times 2 \\times 10^{-6}}} = \\frac{1}{\\sqrt{10^{-6}}} = 1000\\text{ rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit, the capacitor has a capacitance of $25\\ \\mu\\text{F}$ and the inductor has an inductance of $0.16\\text{ H}$. The resonant angular frequency in $\\text{rad/s}$ is:",
    "options": [],
    "correctAnswer": 500,
    "numericalAnswer": 500,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{0.16 \\times 25 \\times 10^{-6}}} = \\frac{1}{\\sqrt{4 \\times 10^{-6}}} = 500\\text{ rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit, $L = 0.64\\text{ H}$ and $C = 25\\ \\mu\\text{F}$. The resonant angular frequency in $\\text{rad/s}$ is:",
    "options": [],
    "correctAnswer": 250,
    "numericalAnswer": 250,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{0.64 \\times 25 \\times 10^{-6}}} = \\frac{1}{\\sqrt{16 \\times 10^{-6}}} = \\frac{1000}{4} = 250\\text{ rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an oscillating LC circuit with $L = 4\\text{ H}$ and $C = 9\\ \\mu\\text{F}$, the resonant angular frequency in $\\text{rad/s}$ is:",
    "options": [],
    "correctAnswer": 167,
    "numericalAnswer": 167,
    "explanation": "$\\omega = \\frac{1}{\\sqrt{4 \\times 9 \\times 10^{-6}}} = \\frac{1}{\\sqrt{36 \\times 10^{-6}}} = \\frac{1000}{6} \\approx 167\\text{ rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A capacitor with capacitance $C = 100\\ \\mu\\text{F}$ is charged to $20\\text{ V}$ and then connected to an inductor with $L = 0.04\\text{ H}$. The peak current during oscillations in amperes is:",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$\\frac{1}{2} L I_0^2 = \\frac{1}{2} C V_0^2 \\implies I_0 = V_0 \\sqrt{\\frac{C}{L}} = 20 \\times \\sqrt{\\frac{100 \\times 10^{-6}}{0.04}} = 20 \\times \\sqrt{0.0025} = 20 \\times 0.05 = 1\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit, the initial energy is $16\\text{ J}$. At a certain instant, the energy stored in the capacitor is $4\\text{ J}$. The energy stored in the inductor at this instant in joules is:",
    "options": [],
    "correctAnswer": 12,
    "numericalAnswer": 12,
    "explanation": "$U_B = U_{total} - U_E = 16 - 4 = 12\\text{ J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A capacitor of $50\\ \\mu\\text{F}$ is charged to $10\\text{ V}$ and connected to an inductor of $2\\text{ mH}$. The maximum magnetic energy stored in the inductor in millijoules is:",
    "options": [],
    "correctAnswer": 2.5,
    "numericalAnswer": 2.5,
    "explanation": "$U_B = \\frac{1}{2} C V_0^2 = \\frac{1}{2} \\times (50 \\times 10^{-6}) \\times 100 = 2.5 \\times 10^{-3}\\text{ J} = 2.5\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit, the maximum charge on the capacitor is $Q_0 = 6\\ \\mu\\text{C}$. The charge on the capacitor when the energy is equally divided between inductor and capacitor in microcoulombs is (rounded to two decimal places, taking $\\sqrt{2} = 1.414$):",
    "options": [],
    "correctAnswer": 4.24,
    "numericalAnswer": 4.24,
    "explanation": "$q = \\frac{Q_0}{\\sqrt{2}} = \\frac{6}{1.414} \\approx 4.24\\ \\mu\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An LC circuit oscillates with a natural frequency of $2000\\text{ Hz}$. If both the inductance and capacitance are increased by a factor of 4, the new natural frequency in $\\text{Hz}$ is:",
    "options": [],
    "correctAnswer": 500,
    "numericalAnswer": 500,
    "explanation": "$f' = \\frac{1}{2\\pi\\sqrt{(4L)(4C)}} = \\frac{1}{4} \\left(\\frac{1}{2\\pi\\sqrt{LC}}\\right) = \\frac{2000}{4} = 500\\text{ Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an LC circuit, the maximum current is $5\\text{ A}$. At an instant when the charge on the capacitor is $\\frac{Q_0}{2}$, the current through the inductor in amperes is (rounded to two decimal places, taking $\\sqrt{3} = 1.732$):",
    "options": [],
    "correctAnswer": 4.33,
    "numericalAnswer": 4.33,
    "explanation": "$I = I_0 \\sqrt{1 - (q/Q_0)^2} = 5 \\times \\sqrt{1 - 0.25} = 5 \\times \\frac{\\sqrt{3}}{2} = 5 \\times 0.866 = 4.33\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "LC oscillations",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
