module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic potential energy of a system of two like charges is strictly positive.\nReason (R): Positive work must be performed by an external agent against the repulsive Coulomb force to bring two like charges from infinite separation to a finite distance $r$: $U = \\frac{k q_1 q_2}{r} > 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the charges repel, moving them together requires positive external work $W_{ext} = \\int_\\infty^r -F_{repulsion}\\, dr = \\frac{k q_1 q_2}{r} > 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic potential energy of a system of two opposite charges is strictly negative.\nReason (R): The attractive electrostatic force between opposite charges performs positive work as they approach each other from infinity, lowering the potential energy below the zero reference at infinity: $U = -\\frac{k |q_1 q_2|}{r} < 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Attractive force pulls charges together spontaneously ($W_{field} > 0$), so the stored electrostatic potential energy decreases below zero ($U < 0$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic self-energy of a thin spherical conducting shell of radius $R$ carrying charge $Q$ is $U = \\frac{k Q^2}{2R}$.\nReason (R): The work required to assemble the charge $Q$ on the sphere by bringing charge elements $dq$ from infinity is $W = \\int_0^Q V(q)\\, dq = \\int_0^Q \\frac{kq}{R}\\, dq = \\frac{k Q^2}{2R}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Integrating the potential $V(q) = \\frac{kq}{R}$ as charge accumulates from $0$ to $Q$ gives $U = \\frac{kQ^2}{2R} = \\frac{Q^2}{8\\pi\\varepsilon_0 R}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic self-energy of a uniformly charged non-conducting solid sphere of radius $R$ and total charge $Q$ is $U = \\frac{3k Q^2}{5R}$.\nReason (R): Assembling concentric shells of charge $dq = \\rho(4\\pi r^2\\, dr)$ onto an accumulating sphere of charge $q(r) = Q\\frac{r^3}{R^3}$ yields $\\int_0^R \\frac{k q(r)\\, dq}{r} = \\frac{3k Q^2}{5R}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Volume integration of electrostatic energy density $\\int \\frac{1}{2}\\varepsilon_0 E^2\\, dV$ both inside and outside the sphere yields $U = \\frac{kQ^2}{10R} + \\frac{kQ^2}{2R} = \\frac{3kQ^2}{5R}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When $N$ identical spherical liquid droplets each charged to potential $V$ and carrying energy $U$ coalesce into a single large droplet, the potential energy of the large droplet is $U' = N^{5/3}U$.\nReason (R): By volume conservation, the radius scales as $R = N^{1/3}r$, and total charge scales as $Q = Nq$, so self-energy $U' = \\frac{k Q^2}{2R} = \\frac{k (Nq)^2}{2(N^{1/3}r)} = N^{5/3}\\left(\\frac{kq^2}{2r}\\right) = N^{5/3}U$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $U \\propto \\frac{Q^2}{R} = \\frac{N^2}{N^{1/3}} = N^{5/3}$, the potential energy increases by $N^{5/3}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When $N$ identical charged droplets coalesce, the electrostatic potential of the resulting large droplet is $V' = N^{2/3}V$.\nReason (R): The potential of a sphere is $V = \\frac{kQ}{R}$, which with $Q = Nq$ and $R = N^{1/3}r$ gives $V' = \\frac{k(Nq)}{N^{1/3}r} = N^{2/3}V$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$V' = \\frac{Q}{4\\pi\\varepsilon_0 R} = \\frac{Nq}{4\\pi\\varepsilon_0 N^{1/3}r} = N^{2/3}\\left(\\frac{q}{4\\pi\\varepsilon_0 r}\\right) = N^{2/3}V$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): For three charges $q_1, q_2, q_3$ placed at the vertices of an equilateral triangle of side $a$, the total electrostatic potential energy is $U = \\frac{k}{a}(q_1 q_2 + q_2 q_3 + q_3 q_1)$.\nReason (R): The total electrostatic potential energy of a system of discrete charges is the algebraic sum of the potential energies of all distinct pairs of interacting charges.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "System energy is $U = \\sum_{i<j} \\frac{k q_i q_j}{r_{ij}} = \\frac{k}{a}(q_1 q_2 + q_2 q_3 + q_3 q_1)$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If four identical positive charges $+q$ are placed at the vertices of a square of side $a$, the total electrostatic potential energy of the system is $\\frac{kq^2}{a}\\left(4 + \\sqrt{2}\\right)$.\nReason (R): There are four adjacent pairs separated by distance $a$ and two diagonal pairs separated by distance $\\sqrt{2}a$, giving $U = 4\\left(\\frac{kq^2}{a}\\right) + 2\\left(\\frac{kq^2}{\\sqrt{2}a}\\right) = \\frac{kq^2}{a}(4 + \\sqrt{2})$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Counting all $\\binom{4}{2} = 6$ pairs: 4 side pairs give $4\\frac{kq^2}{a}$ and 2 diagonal pairs give $2\\frac{kq^2}{\\sqrt{2}a} = \\sqrt{2}\\frac{kq^2}{a}$. Sum is $\\frac{kq^2}{a}(4 + \\sqrt{2})$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The work required to dissociate a system of charges and move them to infinite mutual separation is equal to the negative of the electrostatic potential energy of the system: $W_{dissociation} = -U$.\nReason (R): At infinite separation, the potential energy is zero ($U_\\infty = 0$), so work done by an external agent is $W_{ext} = U_\\infty - U = -U$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By the work-energy relation, disassembling the system to infinity requires $W_{ext} = U_f - U_i = 0 - U = -U$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When an alpha particle of kinetic energy $K$ is directed head-on towards a heavy nucleus of atomic number $Z$, its distance of closest approach is $r_{min} = \\frac{2k Z e^2}{K}$.\nReason (R): At the turning point, the alpha particle momentarily comes to rest, converting all its initial kinetic energy into electrostatic potential energy: $K = \\frac{k(2e)(Ze)}{r_{min}}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Conservation of mechanical energy gives $K = U(r_{min}) = \\frac{k(2e)(Ze)}{r_{min}} = \\frac{2k Z e^2}{r_{min}} \\implies r_{min} = \\frac{2k Z e^2}{K}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): When two like charges are released from rest, they move apart with increasing speed while their electrostatic potential energy decreases.\nReason (R): The repulsive Coulomb force does positive work as the separation increases, converting electrostatic potential energy into kinetic energy: $\\Delta K = -\\Delta U > 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since electrostatic force is conservative, total mechanical energy is conserved: $K + U = \\text{constant}$. As $U \\to 0$, kinetic energy increases to its maximum value. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electrostatic potential energy depends on the choice of the zero-energy reference point.\nReason (R): Only the difference in potential energy between two configurations has physical significance, while the reference value at infinity is chosen as zero purely by convention.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Physical forces and work depend strictly on $\\Delta U$. Choosing $U(\\infty) = 0$ is standard, but shifting $U$ by an arbitrary constant $C$ does not alter any physical observables. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A system of three identical positive charges $+q$ placed at the vertices of an equilateral triangle has minimum potential energy.\nReason (R): All pairwise interactions between like charges are repulsive, making the total electrostatic potential energy strictly positive.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: because all charges repel, the system will fly apart to infinity if released, which reduces $U$ to $0$ (the true minimum). The finite triangle configuration has high potential energy, not a minimum. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic potential energy of an electric dipole of dipole moment $p$ in a uniform electric field $E$ ranges between $-pE$ and $+pE$.\nReason (R): The potential energy function is $U(\\theta) = -pE\\cos\\theta$, and the cosine function takes values strictly in the closed interval $[-1, +1]$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Minimum energy is $U(0^\\circ) = -pE$ and maximum energy is $U(180^\\circ) = +pE$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two protons released from rest from a separation of $10^{-10}\\text{ m}$ acquire a total kinetic energy of $2.3 \\times 10^{-18}\\text{ J}$ at infinite separation.\nReason (R): By conservation of mechanical energy, the initial electrostatic potential energy $U = \\frac{k e^2}{r} \\approx 2.3 \\times 10^{-18}\\text{ J}$ is completely converted into the total kinetic energy of the two particles at infinity.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Total initial potential energy is $U = \\frac{(9 \\times 10^9)(1.6 \\times 10^{-19})^2}{10^{-10}} = 2.304 \\times 10^{-18}\\text{ J}$. At infinite separation, $U_f = 0$, so $K_{total} = U_i = 2.3 \\times 10^{-18}\\text{ J}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If two point charges $+q$ and $-q$ are brought closer together from separation $r_1$ to $r_2$ ($r_2 < r_1$), the potential energy of the system decreases.\nReason (R): The potential energy of opposite charges is $U = -\\frac{kq^2}{r}$, which becomes more negative (smaller) as separation $r$ decreases.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $U = -\\frac{kq^2}{r}$, as $r$ decreases, the magnitude $|U|$ increases while the signed value becomes more negative, meaning $U$ decreases. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If a positive charge is moved against an electric field by an external agent without changing its kinetic energy, the electrostatic potential energy increases.\nReason (R): The work done by the external agent against the conservative electric force is positive and stored as electrostatic potential energy: $\\Delta U = W_{ext} > 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Moving against the electric field requires an external force $\\vec{F}_{ext} = -q\\vec{E}$. The work done is positive, so $\\Delta U > 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic energy of a charged soap bubble increases when its radius expands.\nReason (R): The electrostatic self-energy of a charged spherical shell is $U = \\frac{q^2}{8\\pi\\varepsilon_0 R}$, which is inversely proportional to its radius $R$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: because $U = \\frac{q^2}{8\\pi\\varepsilon_0 R}$, expanding the radius $R$ decreases the electrostatic energy (outward electrostatic pressure does positive work during expansion). Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic potential energy of a continuous charge distribution is equal to the integral of energy density over all space: $U = \\int \\frac{1}{2}\\varepsilon_0 E^2\\, dV$.\nReason (R): Electrostatic energy is physically localized in the electric field created by the charge distribution.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Electrodynamics attributes electrostatic energy directly to the electric field permeating space with local energy density $u = \\frac{1}{2}\\varepsilon_0 E^2$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The energy required to blow up a charged soap bubble from radius $R_1$ to $R_2$ against electrostatic forces is negative.\nReason (R): The mutual repulsion between like charges on the surface of the bubble exerts an outward electrostatic pressure that drives expansion spontaneously.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Electrostatic pressure pushes outwards, doing positive work as the bubble expands. Thus the electrostatic energy decreases: $\\Delta U < 0$. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The potential energy of an electric dipole aligned with an external electric field is minimum.\nReason (R): Potential energy is given by $U = -pE\\cos\\theta$, which attains its minimum value $-pE$ when $\\theta = 0^\\circ$ (dipole aligned parallel to the field).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Alignment parallel to the field minimizes electrostatic potential energy, providing stable mechanical equilibrium. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A negative charge has higher electrostatic potential energy in a region of lower electric potential.\nReason (R): The electrostatic potential energy of a charge $q$ at a point of potential $V$ is given by $U = qV$, so when $q < 0$, a smaller $V$ yields a larger (more positive) potential energy $U$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For negative charge, $U = -|q|V$. Lower potential $V$ makes $-|q|V$ less negative (higher energy). Thus negative charges accelerate spontaneously towards regions of higher potential. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The mutual electrostatic potential energy of two conducting spheres connected by a thin wire is zero.\nReason (R): Connecting two conducting spheres with a wire brings them to a common potential, but both spheres still retain finite charges and mutual electrostatic interaction energy.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: connecting with a wire establishes equal potentials ($V_1 = V_2$), but mutual potential energy $U = \\frac{k Q_1 Q_2}{d} \\ne 0$. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If two point charges are accelerated by their mutual electrostatic repulsion, the total linear momentum of the two-particle system is conserved.\nReason (R): The electrostatic forces $\\vec{F}_{12}$ and $\\vec{F}_{21}$ are internal action-reaction forces obeying Newton's third law, so the net external force on the system is zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{F}_{ext} = 0$, $\\frac{d\\vec{P}_{total}}{dt} = 0$, meaning the total linear momentum remains strictly conserved throughout the motion. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The self-energy of a point charge in classical electrostatics is infinite.\nReason (R): The self-energy of a sphere of radius $R$ is $U = \\frac{k q^2}{2R}$, which diverges to infinity in the point-charge limit as $R \\to 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "As radius $R \\to 0$, $U = \\lim_{R \\to 0} \\frac{kq^2}{2R} = \\infty$, representing the classical electromagnetic mass divergence. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electrostatic potential energy of three identical charges $+q$ placed at the corners of an equilateral triangle of side $a$ increases if the side length is reduced to $a/2$.\nReason (R): The potential energy $U = \\frac{3kq^2}{a}$ is inversely proportional to the side length $a$, so halving $a$ doubles the stored energy to $\\frac{6kq^2}{a}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Compressing the triangle against the mutual repulsion requires positive work by an external agent, increasing stored potential energy. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Three point charges $+q, +q,$ and $+q$ are placed at the vertices of an equilateral triangle of side $a$. The work done by an external agent to increase the side length of the triangle to $2a$ is:",
    "options": [
      "$-\\frac{3kq^2}{2a}$",
      "$\\frac{3kq^2}{2a}$",
      "$-\\frac{3kq^2}{a}$",
      "$\\frac{3kq^2}{a}$"
    ],
    "correctAnswer": 0,
    "explanation": "$U_i = \\frac{3kq^2}{a}$ and $U_f = \\frac{3kq^2}{2a}$. Work done by external agent is $W_{ext} = U_f - U_i = \\frac{3kq^2}{2a} - \\frac{3kq^2}{a} = -\\frac{3kq^2}{2a}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An alpha particle ($q = 2e, m = 6.64 \\times 10^{-27}\\text{ kg}$) is accelerated from rest through a potential difference of $V = 10^6\\text{ V}$ ($1\\text{ MV}$). Its final kinetic energy is:",
    "options": [
      "$2\\text{ MeV}$",
      "$1\\text{ MeV}$",
      "$4\\text{ MeV}$",
      "$0.5\\text{ MeV}$"
    ],
    "correctAnswer": 0,
    "explanation": "$K = qV = (2e)(10^6\\text{ V}) = 2 \\times 10^6\\text{ eV} = 2\\text{ MeV}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two identical conducting spheres of radius $R$ carrying charge $Q$ each are separated by a large distance $d \\gg R$. If they are connected by a thin conducting wire, the work done by the electrostatic forces is:",
    "options": [
      "Zero",
      "$\\frac{kQ^2}{2R}$",
      "$\\frac{kQ^2}{d}$",
      "$\\frac{kQ^2}{4R}$"
    ],
    "correctAnswer": 0,
    "explanation": "Because both spheres are identical and carry identical charges $Q$, they are already at the exact same potential $V = \\frac{kQ}{R}$. Connecting them with a wire causes zero charge redistribution, meaning zero work is done.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "64 identical mercury droplets each charged to a potential of $10\\text{ V}$ coalesce to form a single large drop. The potential of the combined drop is:",
    "options": [
      "$160\\text{ V}$",
      "$640\\text{ V}$",
      "$40\\text{ V}$",
      "$10\\text{ V}$"
    ],
    "correctAnswer": 0,
    "explanation": "Potential scales as $V' = N^{2/3}V$. For $N = 64 = 4^3$, $N^{2/3} = (4^3)^{2/3} = 4^2 = 16$. Thus $V' = 16 \\times 10\\text{ V} = 160\\text{ V}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In the previous question, the ratio of the electrostatic potential energy of the large drop to the total potential energy of the 64 individual droplets is:",
    "options": [
      "$4$",
      "$16$",
      "$64$",
      "$2$"
    ],
    "correctAnswer": 0,
    "explanation": "Single droplet energy is $U_0 = \\frac{1}{2}qV$. Total initial energy is $U_i = N U_0 = 64 U_0$. Energy of large drop is $U' = \\frac{1}{2}QV' = \\frac{1}{2}(64q)(16V) = 64 \\times 16 U_0 = 1024 U_0$. The ratio is $\\frac{U'}{U_i} = \\frac{1024 U_0}{64 U_0} = 16$. Or directly, $\\frac{U'}{N U_0} = \\frac{N^{5/3}U_0}{N U_0} = N^{2/3} = 64^{2/3} = 16$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two point charges $+4\\mu\\text{C}$ and $-2\\mu\\text{C}$ are separated by $1\\text{ m}$ in air. At what point on the line joining them is the electrostatic potential zero (measured from the $+4\\mu\\text{C}$ charge)?",
    "options": [
      "At $2/3\\text{ m}$ between the charges and at $2\\text{ m}$ on the outside",
      "Only at $2/3\\text{ m}$ between the charges",
      "At $1/3\\text{ m}$ between the charges",
      "Only at $2\\text{ m}$ on the outside"
    ],
    "correctAnswer": 0,
    "explanation": "Between charges: $\\frac{k(4)}{x} - \\frac{k(2)}{1 - x} = 0 \\implies \\frac{4}{x} = \\frac{2}{1 - x} \\implies 4 - 4x = 2x \\implies x = \\frac{2}{3}\\text{ m}$. Outside charges (nearer to smaller charge): $\\frac{k(4)}{x} - \\frac{k(2)}{x - 1} = 0 \\implies \\frac{4}{x} = \\frac{2}{x - 1} \\implies 4x - 4 = 2x \\implies x = 2\\text{ m}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electrostatic self-energy of a uniformly charged thin spherical shell of radius $R = 10\\text{ cm}$ carrying charge $Q = 2\\mu\\text{C}$ is (take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$):",
    "options": [
      "$0.18\\text{ J}$",
      "$0.36\\text{ J}$",
      "$0.09\\text{ J}$",
      "$0.72\\text{ J}$"
    ],
    "correctAnswer": 0,
    "explanation": "$U = \\frac{kQ^2}{2R} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})^2}{2(0.1)} = \\frac{9 \\times 10^9 \\times 4 \\times 10^{-12}}{0.2} = \\frac{0.036}{0.2} = 0.18\\text{ J}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two point charges $q_1 = 2\\mu\\text{C}$ and $q_2 = 1\\mu\\text{C}$ are separated by distance $r = 0.3\\text{ m}$ in vacuum. Calculate the electrostatic potential energy $U$ of the two-charge system (in milliJoules, $\\text{mJ}$). (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$U = \\frac{k q_1 q_2}{r} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})(1 \\times 10^{-6})}{0.3} = \\frac{18 \\times 10^{-3}}{0.3} = 60 \\times 10^{-3}\\text{ J} = 60\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two point charges $q_1 = 2\\mu\\text{C}$ and $q_2 = 2\\mu\\text{C}$ are separated by distance $r = 0.3\\text{ m}$ in vacuum. Calculate the electrostatic potential energy $U$ of the two-charge system (in milliJoules, $\\text{mJ}$). (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 120,
    "numericalAnswer": 120,
    "explanation": "$U = \\frac{k q_1 q_2}{r} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})(2 \\times 10^{-6})}{0.3} = \\frac{36 \\times 10^{-3}}{0.3} = 120 \\times 10^{-3}\\text{ J} = 120\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two point charges $q_1 = 2\\mu\\text{C}$ and $q_2 = 3\\mu\\text{C}$ are separated by distance $r = 0.3\\text{ m}$ in vacuum. Calculate the electrostatic potential energy $U$ of the two-charge system (in milliJoules, $\\text{mJ}$). (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 180,
    "numericalAnswer": 180,
    "explanation": "$U = \\frac{k q_1 q_2}{r} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})(3 \\times 10^{-6})}{0.3} = \\frac{54 \\times 10^{-3}}{0.3} = 180 \\times 10^{-3}\\text{ J} = 180\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two point charges $q_1 = 2\\mu\\text{C}$ and $q_2 = 4\\mu\\text{C}$ are separated by distance $r = 0.3\\text{ m}$ in vacuum. Calculate the electrostatic potential energy $U$ of the two-charge system (in milliJoules, $\\text{mJ}$). (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 240,
    "numericalAnswer": 240,
    "explanation": "$U = \\frac{k q_1 q_2}{r} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})(4 \\times 10^{-6})}{0.3} = \\frac{72 \\times 10^{-3}}{0.3} = 240 \\times 10^{-3}\\text{ J} = 240\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two point charges $q_1 = 2\\mu\\text{C}$ and $q_2 = 5\\mu\\text{C}$ are separated by distance $r = 0.3\\text{ m}$ in vacuum. Calculate the electrostatic potential energy $U$ of the two-charge system (in milliJoules, $\\text{mJ}$). (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 300,
    "numericalAnswer": 300,
    "explanation": "$U = \\frac{k q_1 q_2}{r} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})(5 \\times 10^{-6})}{0.3} = \\frac{90 \\times 10^{-3}}{0.3} = 300 \\times 10^{-3}\\text{ J} = 300\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Eight identical small mercury droplets, each charged to an electrostatic potential of $V_0 = 5\\text{ V}$, coalesce together to form a single large spherical drop. Find the potential $V$ (in Volts) of the resulting large drop.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$V = N^{2/3}V_0 = (8)^{2/3}(5\\text{ V}) = 4 \\times 5 = 20\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Eight identical small mercury droplets, each charged to an electrostatic potential of $V_0 = 10\\text{ V}$, coalesce together to form a single large spherical drop. Find the potential $V$ (in Volts) of the resulting large drop.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "$V = N^{2/3}V_0 = (8)^{2/3}(10\\text{ V}) = 4 \\times 10 = 40\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Eight identical small mercury droplets, each charged to an electrostatic potential of $V_0 = 15\\text{ V}$, coalesce together to form a single large spherical drop. Find the potential $V$ (in Volts) of the resulting large drop.",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$V = N^{2/3}V_0 = (8)^{2/3}(15\\text{ V}) = 4 \\times 15 = 60\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Eight identical small mercury droplets, each charged to an electrostatic potential of $V_0 = 20\\text{ V}$, coalesce together to form a single large spherical drop. Find the potential $V$ (in Volts) of the resulting large drop.",
    "options": [],
    "correctAnswer": 80,
    "numericalAnswer": 80,
    "explanation": "$V = N^{2/3}V_0 = (8)^{2/3}(20\\text{ V}) = 4 \\times 20 = 80\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Eight identical small mercury droplets, each charged to an electrostatic potential of $V_0 = 25\\text{ V}$, coalesce together to form a single large spherical drop. Find the potential $V$ (in Volts) of the resulting large drop.",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$V = N^{2/3}V_0 = (8)^{2/3}(25\\text{ V}) = 4 \\times 25 = 100\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Find the work done (in $\\mu\\text{J}$) by an external agent to bring a point charge $q = 1\\mu\\text{C}$ from infinity to a point in an electric field where the electrostatic potential is $V = 50\\text{ V}$.",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "$W = qV = (1\\mu\\text{C})(50\\text{ V}) = 50\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Find the work done (in $\\mu\\text{J}$) by an external agent to bring a point charge $q = 2\\mu\\text{C}$ from infinity to a point in an electric field where the electrostatic potential is $V = 50\\text{ V}$.",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$W = qV = (2\\mu\\text{C})(50\\text{ V}) = 100\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Find the work done (in $\\mu\\text{J}$) by an external agent to bring a point charge $q = 3\\mu\\text{C}$ from infinity to a point in an electric field where the electrostatic potential is $V = 50\\text{ V}$.",
    "options": [],
    "correctAnswer": 150,
    "numericalAnswer": 150,
    "explanation": "$W = qV = (3\\mu\\text{C})(50\\text{ V}) = 150\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Find the work done (in $\\mu\\text{J}$) by an external agent to bring a point charge $q = 4\\mu\\text{C}$ from infinity to a point in an electric field where the electrostatic potential is $V = 50\\text{ V}$.",
    "options": [],
    "correctAnswer": 200,
    "numericalAnswer": 200,
    "explanation": "$W = qV = (4\\mu\\text{C})(50\\text{ V}) = 200\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Find the work done (in $\\mu\\text{J}$) by an external agent to bring a point charge $q = 5\\mu\\text{C}$ from infinity to a point in an electric field where the electrostatic potential is $V = 50\\text{ V}$.",
    "options": [],
    "correctAnswer": 250,
    "numericalAnswer": 250,
    "explanation": "$W = qV = (5\\mu\\text{C})(50\\text{ V}) = 250\\mu\\text{J}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle carrying charge $q = 10\\mu\\text{C}$ is accelerated from rest through an electrostatic potential difference of $V = 100\\text{ V}$. Find the kinetic energy acquired by the particle (in milliJoules, $\\text{mJ}$).",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$K = qV = (10 \\times 10^{-6}\\text{ C})(100\\text{ V}) = 1 \\times 10^{-3}\\text{ J} = 1\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle carrying charge $q = 20\\mu\\text{C}$ is accelerated from rest through an electrostatic potential difference of $V = 100\\text{ V}$. Find the kinetic energy acquired by the particle (in milliJoules, $\\text{mJ}$).",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "$K = qV = (20 \\times 10^{-6}\\text{ C})(100\\text{ V}) = 2 \\times 10^{-3}\\text{ J} = 2\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle carrying charge $q = 30\\mu\\text{C}$ is accelerated from rest through an electrostatic potential difference of $V = 100\\text{ V}$. Find the kinetic energy acquired by the particle (in milliJoules, $\\text{mJ}$).",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "$K = qV = (30 \\times 10^{-6}\\text{ C})(100\\text{ V}) = 3 \\times 10^{-3}\\text{ J} = 3\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle carrying charge $q = 40\\mu\\text{C}$ is accelerated from rest through an electrostatic potential difference of $V = 100\\text{ V}$. Find the kinetic energy acquired by the particle (in milliJoules, $\\text{mJ}$).",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$K = qV = (40 \\times 10^{-6}\\text{ C})(100\\text{ V}) = 4 \\times 10^{-3}\\text{ J} = 4\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle carrying charge $q = 50\\mu\\text{C}$ is accelerated from rest through an electrostatic potential difference of $V = 100\\text{ V}$. Find the kinetic energy acquired by the particle (in milliJoules, $\\text{mJ}$).",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "$K = qV = (50 \\times 10^{-6}\\text{ C})(100\\text{ V}) = 5 \\times 10^{-3}\\text{ J} = 5\\text{ mJ}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Potential energy",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
