module.exports = [
  {
    "question": "Assertion (A): Electrical power is transmitted over long distances at extremely high voltages.\nReason (R): Transmitting power at high voltage reduces the current for a given power level, which drastically reduces Joule heating losses ($I^2 R$) in the transmission cables.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since transmitted power is $P = V I$, higher $V$ allows smaller $I$. The line power loss is $P_{loss} = I^2 R_{line} = \\frac{P^2 R_{line}}{V^2}$, which decreases inversely with $V^2$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A transformer cannot be used to step up or step down a steady DC voltage.\nReason (R): A steady direct current creates a constant magnetic flux through the core, resulting in zero rate of change of flux ($\\,\\frac{d\\Phi}{dt} = 0\\,$) and zero induced EMF in the secondary winding.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Faraday's law requires $\\frac{d\\Phi}{dt} \\neq 0$. With steady DC, the magnetic field is static, so no secondary EMF is induced. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The core of a transformer is laminated rather than made of a solid block of iron.\nReason (R): Laminations separated by thin insulating varnish break up closed conduction paths, significantly reducing eddy current losses.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Eddy currents circulating in planes perpendicular to the flux are broken into thin slices, vastly increasing path resistance and reducing eddy current heating loss. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an ideal step-up transformer, the output electrical power equals the input electrical power.\nReason (R): An ideal transformer has zero winding resistance, zero core losses, and no magnetic flux leakage, strictly conserving electrical energy.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By conservation of energy, in the absence of losses, $P_{out} = V_s I_s = V_p I_p = P_{in}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A step-up transformer increases voltage while simultaneously decreasing the current in the secondary coil.\nReason (R): According to the principle of conservation of energy, the product $V I$ cannot exceed the input power, so an increase in voltage must be accompanied by a proportional decrease in current.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For an ideal transformer, $V_s I_s = V_p I_p$. Therefore, if $V_s > V_p$, it follows that $I_s < I_p$. A step-up transformer steps up voltage, not power. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Soft iron or silicon steel is preferred as the core material for transformers.\nReason (R): Soft iron has a narrow hysteresis loop, resulting in low energy dissipation per magnetization cycle (low hysteresis loss).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Hysteresis loss per cycle equals the area of the B-H loop. Soft iron has high magnetic permeability, low coercivity, and a narrow B-H loop area, minimizing thermal core loss. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a step-down transformer, the secondary winding is made of thicker copper wire than the primary winding.\nReason (R): In a step-down transformer, the secondary current is larger than the primary current, requiring a thicker wire with lower resistance to minimize Joule heating ($I^2 R$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $I_s > I_p$, thicker wire with larger cross-sectional area is used for the secondary coil to handle higher current without overheating. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): An AC generator uses slip rings, whereas a DC generator uses a split-ring commutator.\nReason (R): Slip rings maintain continuous contact with the rotating coil ends to output alternating polarity, whereas a split-ring commutator mechanically reverses connections every half-turn to produce unidirectional current.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Slip rings preserve the sinusoidal alternation generated inside the coil. Split-ring commutators reverse connections at the zero-crossing instants, rectifying AC into pulsating DC. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The EMF induced in the armature coil of an AC generator is zero when the plane of the coil is perpendicular to the magnetic field.\nReason (R): When the plane of the coil is perpendicular to $\\mathbf{B}$, the magnetic flux linked with the coil is maximum, and its rate of change $\\frac{d\\Phi}{dt}$ is zero.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Flux is $\\Phi(t) = B A \\cos(\\omega t)$. When perpendicular, $\\omega t = 0$, so $\\Phi = B A$ (maximum), while $\\mathcal{E} = \\omega B A \\sin(\\omega t) = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The EMF induced in the coil of an AC generator is maximum when the plane of the coil is parallel to the magnetic field lines.\nReason (R): When the coil plane is parallel to $\\mathbf{B}$, the magnetic flux linking the coil is zero, but the rate of change of magnetic flux is at its maximum value.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Parallel coil plane means $\\omega t = \\frac{\\pi}{2}$. Here $\\Phi = B A \\cos(\\pi/2) = 0$, and $\\mathcal{E} = \\omega B A \\sin(\\pi/2) = \\omega B A$ is maximum. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If the rotational speed of the armature coil of an AC generator is doubled, both the frequency and the peak EMF of the generated voltage are doubled.\nReason (R): The frequency of the generated AC is $f = \\frac{\\omega}{2\\pi}$ and the peak EMF is $\\mathcal{E}_0 = N B A \\omega$, both of which are directly proportional to the angular speed $\\omega$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Both $f \\propto \\omega$ and $\\mathcal{E}_0 \\propto \\omega$. Doubling $\\omega$ doubles both output frequency and peak voltage amplitude. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A transformer hums during operation.\nReason (R): The phenomenon of magnetostriction causes the iron core to undergo small periodic changes in dimensions when magnetized by an alternating magnetic field.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The ferromagnetic core physically expands and contracts at twice the AC line frequency due to magnetostriction, vibrating surrounding air and producing an audible 100 Hz/120 Hz hum. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If a DC battery is connected across the primary of a step-up transformer, the primary winding will likely burn out.\nReason (R): A transformer primary winding has very low ohmic resistance, relying on the inductive back EMF to limit alternating current; for steady DC, back EMF is zero and excessive current flows.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In AC, impedance $Z = \\sqrt{R^2 + (\\omega L)^2} \\gg R$ restricts current. For steady DC, $\\omega = 0$, so current is limited only by tiny wire resistance ($I = \\frac{V}{R}$), causing massive $I^2 R$ heating and destruction. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Shell-type transformer cores provide better efficiency and lower flux leakage than core-type transformers.\nReason (R): In a shell-type transformer, the primary and secondary coils are wound concentrically on the central limb, and the magnetic circuit surrounds the windings, providing a closed low-reluctance magnetic path.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Concentric windings on the central limb maximize magnetic coupling between coils ($k \\approx 1$) and minimize leakage flux. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The transformation ratio $K$ of a transformer is given by $K = \\frac{N_s}{N_p} = \\frac{V_s}{V_p}$.\nReason (R): The EMF induced per turn is identical in both primary and secondary windings because the same magnetic flux links each turn: $\\frac{V_s}{N_s} = \\frac{V_p}{N_p} = -\\frac{d\\Phi}{dt}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In an ideal core without flux leakage, each turn experiences the exact same $\\frac{d\\Phi}{dt}$, so $\\frac{V_s}{N_s} = \\frac{V_p}{N_p} \\implies \\frac{V_s}{V_p} = \\frac{N_s}{N_p} = K$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): An AC generator cannot produce direct current directly from its slip rings.\nReason (R): The induced EMF naturally reverses direction every half rotation as the active coil sides switch from moving upwards to downwards across the magnetic field.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the direction of $\\mathbf{v} \\times \\mathbf{B}$ flips relative to each coil side every half cycle, continuous slip rings inevitably convey an alternating voltage. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Carbon brushes are used in AC generators and DC motors to collect current from rotating rings.\nReason (R): Carbon has a negative temperature coefficient of resistance, is self-lubricating, and provides a low-friction electrical sliding contact that does not damage the copper rings.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Graphite/carbon is soft, self-lubricating, and conducts electricity smoothly without excessive wear on the commutators or slip rings. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A step-up transformer does not violate the law of conservation of energy even though it outputs higher voltage.\nReason (R): Although the voltage is increased, the current is simultaneously reduced in the same proportion, so the output power can never exceed the input power.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Energy conservation requires $P_{out} \\le P_{in}$. Increasing $V$ by a factor $K$ reduces $I$ by $K$, preserving $P = V I$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The efficiency of modern commercial transformers is typically very high (95% to 99%).\nReason (R): Transformers are static electromagnetic devices with no moving mechanical parts, completely eliminating mechanical friction and windage losses.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Without rotating friction or bearing losses, energy losses are limited strictly to small core and winding losses, yielding efficiencies exceeding $95\\%$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an open secondary circuit of a transformer, the primary still draws a small current from the AC supply.\nReason (R): The no-load primary current (magnetizing current) is required to establish the alternating magnetic flux in the core and to supply core losses.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Even when secondary current $I_s = 0$, an alternating magnetizing current $I_0$ flows in the primary to set up the magnetic flux in the core. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A load resistance $R_L$ connected to the secondary of a transformer appears as an equivalent resistance $R_p = \\left(\\frac{N_p}{N_s}\\right)^2 R_L$ across the primary terminals.\nReason (R): The primary voltage is $V_p = \\frac{N_p}{N_s} V_s$ and the primary current is $I_p = \\frac{N_s}{N_p} I_s$, so the input impedance is $\\frac{V_p}{I_p} = \\left(\\frac{N_p}{N_s}\\right)^2 \\frac{V_s}{I_s} = \\left(\\frac{N_p}{N_s}\\right)^2 R_L$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Impedance transformation ratio is $\\left(\\frac{N_p}{N_s}\\right)^2$, widely used for impedance matching in audio amplifiers and RF circuits. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an AC generator, the armature coil is often kept stationary while the magnetic field rotates (stator and rotor).\nReason (R): It is much easier and safer to draw large high-voltage currents from stationary stator terminals than from high-speed rotating slip rings.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Modern large power alternators use a stationary stator winding to extract heavy generated currents directly without sparking slip rings, using a low-power DC rotor field. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The output frequency of an AC generator having $P$ pairs of magnetic poles rotating at $n$ revolutions per second is $f = P n$.\nReason (R): The induced EMF undergoes one complete electrical cycle as each pair of north and south poles sweeps past a given coil.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For a machine with $P$ pole pairs (or $2P$ poles), the electrical frequency is $f = P n = \\frac{P N_{rpm}}{60}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Transformer oil is used in high-power substation transformers.\nReason (R): The oil serves both as an excellent electrical insulator and as a liquid coolant that transfers internal heat to radiator fins.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Mineral dielectric oil has high dielectric strength and conducts heat away by convection from the windings and core to the radiator tank. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The instantaneous EMF of an AC generator is proportional to the sine of the angle of rotation.\nReason (R): The magnetic flux linked with the coil is $\\Phi = B A \\cos(\\omega t)$, and Faraday's law states that $\\mathcal{E} = -\\frac{d\\Phi}{dt} = B A \\omega \\sin(\\omega t)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The time derivative of the cosine flux function yields a sinusoidal EMF $\\mathcal{E}_0 \\sin(\\omega t)$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A transformer can amplify electrical power.\nReason (R): A step-up transformer increases the voltage by increasing the turns in the secondary winding.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "(A) is false because a transformer cannot amplify power; $P_{out} \\le P_{in}$ always by the law of conservation of energy. (R) is true because a step-up transformer increases voltage by having $N_s > N_p$.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A step-down transformer transforms $2200\\text{ V}$ to $220\\text{ V}$. The primary coil has 5000 turns. If the efficiency of the transformer is $90\\%$ and the output power is $8.8\\text{ kW}$, the primary current and secondary current are, respectively:",
    "options": [
      "4.44 A, 40 A",
      "4.0 A, 44.4 A",
      "4.44 A, 4.44 A",
      "40 A, 4.0 A"
    ],
    "correctAnswer": 0,
    "explanation": "Output voltage $V_s = 220\\text{ V}$, output power $P_s = 8800\\text{ W}$. Secondary current $I_s = \\frac{P_s}{V_s} = \\frac{8800}{220} = 40\\text{ A}$. Input power $P_p = \\frac{P_s}{\\eta} = \\frac{8800}{0.90} \\approx 9777.8\\text{ W}$. Primary current $I_p = \\frac{P_p}{V_p} = \\frac{9777.8}{2200} \\approx 4.44\\text{ A}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The armature of an AC generator has 100 turns, each of area $0.05\\text{ m}^2$, rotating in a uniform magnetic field of $0.2\\text{ T}$ at an angular speed of $120\\text{ rad/s}$. The maximum EMF induced in the coil is:",
    "options": [
      "120 V",
      "60 V",
      "240 V",
      "12 V"
    ],
    "correctAnswer": 0,
    "explanation": "Peak EMF $\\mathcal{E}_0 = N B A \\omega = 100 \\times 0.2 \\times 0.05 \\times 120 = 100 \\times 0.01 \\times 120 = 120\\text{ V}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An ideal transformer has 100 turns in the primary and 250 turns in the secondary. If the primary is connected to a $200\\text{ V}$, $50\\text{ Hz}$ AC line, the secondary voltage and frequency are, respectively:",
    "options": [
      "500 V, 50 Hz",
      "500 V, 125 Hz",
      "80 V, 50 Hz",
      "80 V, 20 Hz"
    ],
    "correctAnswer": 0,
    "explanation": "Transformation ratio $K = \\frac{N_s}{N_p} = \\frac{250}{100} = 2.5$. Secondary voltage $V_s = K V_p = 2.5 \\times 200 = 500\\text{ V}$. A transformer does not change frequency, so $f = 50\\text{ Hz}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An AC generator coil of 50 turns and area $0.1\\text{ m}^2$ rotates at $3000\\text{ rpm}$ in a magnetic field of $0.2\\text{ T}$. Taking $\\pi = 3.14$, the peak induced EMF is:",
    "options": [
      "314 V",
      "157 V",
      "628 V",
      "100 V"
    ],
    "correctAnswer": 0,
    "explanation": "$\\omega = \\frac{3000 \\times 2\\pi}{60} = 100\\pi\\text{ rad/s}$. $\\mathcal{E}_0 = N B A \\omega = 50 \\times 0.2 \\times 0.1 \\times 100\\pi = 100\\pi = 314\\text{ V}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an ideal transformer, the number of turns in the primary and secondary coils are 200 and 1000 respectively. If a $20\\ \\Omega$ resistor is connected across the secondary, the equivalent resistance seen by the primary source is:",
    "options": [
      "$0.8\\ \\Omega$",
      "$500\\ \\Omega$",
      "$100\\ \\Omega$",
      "$4\\ \\Omega$"
    ],
    "correctAnswer": 0,
    "explanation": "Reflected resistance $R_p = \\left(\\frac{N_p}{N_s}\\right)^2 R_s = \\left(\\frac{200}{1000}\\right)^2 \\times 20 = \\left(\\frac{1}{5}\\right)^2 \\times 20 = \\frac{20}{25} = 0.8\\ \\Omega$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The primary coil of an ideal step-up transformer has 100 turns and the secondary has 2000 turns. If the input power is $4000\\text{ W}$ at $200\\text{ V}$, the secondary current is:",
    "options": [
      "1.0 A",
      "20.0 A",
      "0.5 A",
      "2.0 A"
    ],
    "correctAnswer": 0,
    "explanation": "$V_s = V_p \\left(\\frac{N_s}{N_p}\\right) = 200 \\times 20 = 4000\\text{ V}$. For an ideal transformer, $P_s = P_p = 4000\\text{ W}$. Secondary current $I_s = \\frac{P_s}{V_s} = \\frac{4000}{4000} = 1.0\\text{ A}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Which of the following losses in a practical transformer is minimized by using thin laminated sheets of soft iron rather than a single solid block?",
    "options": [
      "Eddy current loss",
      "Hysteresis loss",
      "Copper loss",
      "Flux leakage loss"
    ],
    "correctAnswer": 0,
    "explanation": "Laminating the core with thin sheets coated with insulating varnish interrupts closed electrical loops within the core material, minimizing eddy current Joule heating loss.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An ideal transformer has 200 primary turns and 800 secondary turns. If the primary voltage is $120\\text{ V}$, the secondary voltage in volts is:",
    "options": [],
    "correctAnswer": 480,
    "numericalAnswer": 480,
    "explanation": "$V_s = V_p \\frac{N_s}{N_p} = 120 \\times \\frac{800}{200} = 120 \\times 4 = 480\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A step-down transformer converts $220\\text{ V}$ to $22\\text{ V}$. If the primary coil has 1000 turns, the number of turns in the secondary coil is:",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$N_s = N_p \\frac{V_s}{V_p} = 1000 \\times \\frac{22}{220} = 100$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An AC generator has a coil of 100 turns, each of area $0.02\\text{ m}^2$, rotating in a magnetic field of $0.5\\text{ T}$ at an angular speed of $50\\text{ rad/s}$. The peak induced EMF in volts is:",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "$\\mathcal{E}_0 = N B A \\omega = 100 \\times 0.5 \\times 0.02 \\times 50 = 50\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A transformer operates on a $220\\text{ V}$ supply and delivers $22\\text{ V}$ to an external load. If the secondary current is $5\\text{ A}$ and the efficiency of the transformer is $100\\%$, the primary current in amperes is:",
    "options": [],
    "correctAnswer": 0.5,
    "numericalAnswer": 0.5,
    "explanation": "$V_p I_p = V_s I_s \\implies I_p = \\frac{V_s I_s}{V_p} = \\frac{22 \\times 5}{220} = 0.5\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A transformer has an efficiency of $80\\%$ and works at $4\\text{ kW}$ output. The electrical power input in kilowatts is:",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "$P_{in} = \\frac{P_{out}}{\\eta} = \\frac{4}{0.8} = 5\\text{ kW}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The primary of a step-up transformer has 50 turns and the secondary has 500 turns. If the secondary current is $2\\text{ A}$ (assuming $100\\%$ efficiency), the primary current in amperes is:",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$I_p = I_s \\frac{N_s}{N_p} = 2 \\times \\frac{500}{50} = 20\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An AC generator armature coil of area $0.05\\text{ m}^2$ with 200 turns rotates at $1800\\text{ rpm}$ in a $0.1\\text{ T}$ magnetic field. Taking $\\pi = 3.14$, the peak voltage in volts is (rounded to nearest integer):",
    "options": [],
    "correctAnswer": 188,
    "numericalAnswer": 188,
    "explanation": "$\\omega = \\frac{1800 \\times 2\\pi}{60} = 60\\pi\\text{ rad/s}$. $\\mathcal{E}_0 = N B A \\omega = 200 \\times 0.1 \\times 0.05 \\times 60\\pi = 60\\pi = 60 \\times 3.1416 \\approx 188.5 \\approx 188\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A transformer with an efficiency of $90\\%$ supplies power to a $220\\text{ V}$, $99\\text{ W}$ bulb from a $110\\text{ V}$ AC line. The primary current drawn in amperes is:",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "Output power $P_{out} = 99\\text{ W}$. Input power $P_{in} = \\frac{99}{0.90} = 110\\text{ W}$. Primary current $I_p = \\frac{P_{in}}{V_p} = \\frac{110}{110} = 1\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An ideal transformer has $N_p = 400$ and $N_s = 100$. A resistance of $10\\ \\Omega$ is connected across the secondary. The equivalent load resistance across the primary in $\\Omega$ is:",
    "options": [],
    "correctAnswer": 160,
    "numericalAnswer": 160,
    "explanation": "$R_p = \\left(\\frac{N_p}{N_s}\\right)^2 R_s = \\left(\\frac{400}{100}\\right)^2 \\times 10 = 16 \\times 10 = 160\\ \\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an AC generator, the armature has 50 turns and cross-sectional area $0.2\\text{ m}^2$. It rotates at $60\\text{ rad/s}$ in a magnetic field of $0.4\\text{ T}$. The peak induced voltage in volts is:",
    "options": [],
    "correctAnswer": 240,
    "numericalAnswer": 240,
    "explanation": "$\\mathcal{E}_0 = N B A \\omega = 50 \\times 0.4 \\times 0.2 \\times 60 = 240\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A step-down transformer has 1200 primary turns and 60 secondary turns. When connected to a $240\\text{ V}$ AC mains, the secondary voltage in volts is:",
    "options": [],
    "correctAnswer": 12,
    "numericalAnswer": 12,
    "explanation": "$V_s = V_p \\frac{N_s}{N_p} = 240 \\times \\frac{60}{1200} = 12\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A transformer with turns ratio $\\frac{N_s}{N_p} = 10$ is connected to a $12\\text{ V}$ AC source. If the secondary is connected to a $1200\\ \\Omega$ resistor, the secondary current in amperes is:",
    "options": [],
    "correctAnswer": 0.1,
    "numericalAnswer": 0.1,
    "explanation": "$V_s = 10 \\times 12 = 120\\text{ V}$. Secondary current $I_s = \\frac{120}{1200} = 0.1\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The power input to a step-up transformer is $2000\\text{ W}$. If the energy dissipated as heat in the core and windings is $200\\text{ W}$, the efficiency percentage of the transformer is:",
    "options": [],
    "correctAnswer": 90,
    "numericalAnswer": 90,
    "explanation": "$\\eta = \\frac{P_{out}}{P_{in}} \\times 100\\% = \\frac{2000 - 200}{2000} \\times 100\\% = \\frac{1800}{2000} \\times 100\\% = 90\\%$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An AC generator produces a maximum voltage of $100\\text{ V}$ at a frequency of $50\\text{ Hz}$. The instantaneous EMF at $t = \\frac{1}{300}\\text{ s}$ after zero in volts is (taking $\\sqrt{3} = 1.732$):",
    "options": [],
    "correctAnswer": 86.6,
    "numericalAnswer": 86.6,
    "explanation": "$\\omega = 2\\pi (50) = 100\\pi\\text{ rad/s}$. At $t = \\frac{1}{300}\\text{ s}$, $\\omega t = \\frac{100\\pi}{300} = \\frac{\\pi}{3}$. $\\mathcal{E} = 100\\sin(\\pi/3) = 100 \\times \\frac{\\sqrt{3}}{2} = 50\\sqrt{3} \\approx 86.6\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A generator has a 10-pole rotor rotating at $600\\text{ rpm}$. The frequency of the generated alternating EMF in $\\text{Hz}$ is:",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "Number of pole pairs $P = \\frac{10}{2} = 5$. Rotational speed $n = \\frac{600}{60} = 10\\text{ rps}$. Frequency $f = P n = 5 \\times 10 = 50\\text{ Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A step-down transformer connected to a $240\\text{ V}$ line supplies a $12\\text{ V}$ door bell. If the door bell draws $2\\text{ A}$ and the transformer is $100\\%$ efficient, the primary current in amperes is:",
    "options": [],
    "correctAnswer": 0.1,
    "numericalAnswer": 0.1,
    "explanation": "$I_p = \\frac{V_s I_s}{V_p} = \\frac{12 \\times 2}{240} = \\frac{24}{240} = 0.1\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An AC generator coil has 100 turns, each of area $0.1\\text{ m}^2$, rotated at $20\\text{ rad/s}$ in a $0.05\\text{ T}$ field. The peak EMF in volts is:",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "$\\mathcal{E}_0 = 100 \\times 0.05 \\times 0.1 \\times 20 = 10\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A $220\\text{ V}$ to $22\\text{ V}$ transformer has an efficiency of $95\\%$. When the output power is $418\\text{ W}$, the input power in watts is:",
    "options": [],
    "correctAnswer": 440,
    "numericalAnswer": 440,
    "explanation": "$P_{in} = \\frac{P_{out}}{\\eta} = \\frac{418}{0.95} = 440\\text{ W}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An ideal transformer has primary and secondary turns in the ratio $1 : 5$. If an alternating voltage of $40\\text{ V}$ RMS is applied to the primary, the secondary RMS voltage in volts is:",
    "options": [],
    "correctAnswer": 200,
    "numericalAnswer": 200,
    "explanation": "$V_s = 5 \\times 40 = 200\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A coil of 80 turns and area $0.025\\text{ m}^2$ rotates at $50\\text{ rad/s}$ in a uniform magnetic field of $0.2\\text{ T}$. The maximum induced EMF in volts is:",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$\\mathcal{E}_0 = N B A \\omega = 80 \\times 0.2 \\times 0.025 \\times 50 = 20\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Transformers and AC generator",
    "chapter": "Electromagnetic Induction and Alternating Currents",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
