module.exports = [
  {
    "question": "Assertion: In simple harmonic motion, the acceleration of the particle is always directed towards the mean position.\\nReason: The restoring force in simple harmonic motion is directly proportional to displacement from the mean position and opposes the displacement ($F = -kx$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "By definition, the restoring force in linear SHM satisfies $F = -kx$. Applying Newton's second law, acceleration is $a = \\frac{F}{m} = -\\left(\\frac{k}{m}\\right)x = -\\omega^2 x$. The negative sign signifies that acceleration vector $\\vec{a}$ is always directed opposite to the displacement vector $\\vec{x}$, pointing constantly towards the equilibrium mean position. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: In simple harmonic motion, velocity leads displacement by a phase angle of $\\frac{\\pi}{2}$ radians.\\nReason: If displacement is $x = A\\sin(\\omega t)$, then velocity is $v = \\frac{dx}{dt} = \\omega A\\cos(\\omega t) = \\omega A\\sin\\left(\\omega t + \\frac{\\pi}{2}\\right)$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Differentiating $x(t) = A\\sin(\\omega t)$ gives $v(t) = \\omega A\\cos(\\omega t) = \\omega A\\sin(\\omega t + \\pi/2)$. The argument of the sine function for velocity is ahead of that for displacement by $\\pi/2$ radians ($90^\\circ$). Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Acceleration in simple harmonic motion leads displacement by a phase angle of $\\pi$ radians.\\nReason: Acceleration is related to displacement by $a = -\\omega^2 x = \\omega^2 A\\sin(\\omega t + \\pi)$ when $x = A\\sin(\\omega t)$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Since $-\\sin(\\theta) = \\sin(\\theta + \\pi)$, the acceleration $a = -\\omega^2 A\\sin(\\omega t) = \\omega^2 A\\sin(\\omega t + \\pi)$. The phase difference between acceleration and displacement is $\\pi$ radians ($180^\\circ$), meaning they are in exact anti-phase. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The time taken by a particle in SHM to travel from the mean position to half the amplitude ($x = A/2$) is $\\frac{T}{12}$, whereas the time taken from $x = A/2$ to the extreme ($x = A$) is $\\frac{T}{6}$.\\nReason: The particle moves fastest near the mean position and slows down as it approaches the extreme position.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Starting from mean position $x = A\\sin(\\omega t)$: For $x = A/2$, $\\sin(\\omega t_1) = 1/2 \\implies \\omega t_1 = \\pi/6 \\implies t_1 = \\frac{\\pi/6}{2\\pi/T} = \\frac{T}{12}$. Total time to reach $x = A$ is $T/4$. Therefore the time from $A/2$ to $A$ is $t_2 = \\frac{T}{4} - \\frac{T}{12} = \\frac{T}{6}$. Because particle speed decreases continuously towards the turnaround extreme, it takes twice as long to traverse the outer half of the amplitude. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: Every simple harmonic motion is necessarily periodic, but every periodic motion is not necessarily simple harmonic.\\nReason: Periodic motion merely requires the position and velocity to repeat after a constant time interval, whereas SHM specifically requires the restoring force to be proportional to negative displacement ($F = -kx$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Planetary orbits and square wave vibrations are periodic because they repeat cyclically over time period $T$, but their restoring forces do not follow Hooke's linear relation $F = -kx$. Simple harmonic motion is a special, purest case of periodic motion governed by linear restoring forces. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The plot of velocity versus displacement for a particle executing simple harmonic motion is an ellipse.\\nReason: Eliminating time from $x = A\\sin(\\omega t)$ and $v = \\omega A\\cos(\\omega t)$ gives the equation $\\frac{x^2}{A^2} + \\frac{v^2}{\\omega^2 A^2} = 1$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Using $\\sin^2(\\omega t) + \\cos^2(\\omega t) = 1$, we obtain $\\frac{x^2}{A^2} + \\frac{v^2}{(\\omega A)^2} = 1$. This is the standard equation of an ellipse in the $v$-$x$ phase plane with semi-axes $A$ along $x$ and $\\omega A$ along $v$. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The plot of acceleration versus displacement for a particle in simple harmonic motion is a straight line passing through the origin with negative slope.\\nReason: The relation between acceleration and displacement in SHM is $a = -\\omega^2 x$, where $-\\omega^2$ is a negative constant.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The equation $a = -\\omega^2 x$ has the form $y = mx$ with slope $m = -\\omega^2 < 0$. It is a straight line through the origin in the second and fourth quadrants. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: At the extreme positions of simple harmonic motion, the particle is instantaneously at rest but its acceleration is maximum.\\nReason: At $x = \\pm A$, the restoring force $F = -kx$ attains its peak magnitude, producing maximum acceleration $a_{\\max} = \\omega^2 A$, even though particle velocity drops to zero as it reverses direction.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "At the turning points, $v = \\omega\\sqrt{A^2 - A^2} = 0$, but the spring/restoring displacement is maximum, exerting peak force $F_{\\max} = kA$ and giving peak acceleration $a_{\\max} = \\omega^2 A$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The average velocity of a particle executing simple harmonic motion over one complete oscillation cycle is zero.\\nReason: Over one complete cycle, the net displacement of the particle is zero, and average velocity is defined as total displacement divided by total time.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "After completing one period $T$, the particle returns to its exact initial location, giving net displacement $\\Delta x = 0$. By definition, $\\vec{v}_{\\text{avg}} = \\frac{\\Delta x}{T} = 0$. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The average speed of a particle in SHM over one complete period is $\\frac{2}{\\pi} v_{\\max}$, where $v_{\\max} = \\omega A$.\\nReason: The total distance traveled in one full cycle is $4A$, giving average speed $\\frac{4A}{T} = \\frac{4A}{2\\pi/\\omega} = \\frac{2\\omega A}{\\pi} = \\frac{2}{\\pi} v_{\\max}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "In one full cycle, the particle travels from $0 \\to A \\to 0 \\to -A \\to 0$, covering a total path distance of $4A$. The average speed is $\\frac{\\text{distance}}{\\text{time}} = \\frac{4A}{T} = \\frac{4A}{2\\pi / \\omega} = \\frac{2}{\\pi}\\omega A = \\frac{2}{\\pi}v_{\\max}$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The projection of uniform circular motion onto any diameter executes simple harmonic motion.\\nReason: If a reference point rotates along a circle of radius $A$ at constant angular velocity $\\omega$, its projection on the $x$-axis satisfies $x(t) = A\\cos(\\omega t + \\phi)$, which obeys $\\frac{d^2x}{dt^2} = -\\omega^2 x$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Uniform circular motion on a reference circle (the phasor method) projects onto any diameter as $x = A\\cos(\\omega t + \\phi)$. Differentiating twice gives $a = -\\omega^2 x$, which is the exact differential equation of simple harmonic motion. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: If the amplitude of simple harmonic motion is doubled while the mass and spring constant remain unchanged, the time period remains the same.\\nReason: The time period of an undamped simple harmonic oscillator is $T = 2\\pi\\sqrt{\\frac{m}{k}}$, which is strictly independent of amplitude.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Isochronism is a fundamental hallmark of linear SHM: the period depends solely on inertia $m$ and stiffness $k$, not on the initial displacement or energy given to the system. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: A particle executing SHM has a speed of $\\frac{\\sqrt{3}}{2} v_{\\max}$ when its displacement is half of the amplitude ($x = A/2$).\\nReason: The speed at displacement $x$ is given by $v = \\omega\\sqrt{A^2 - x^2} = \\omega\\sqrt{A^2 - (A/2)^2} = \\omega\\sqrt{\\frac{3}{4}A^2} = \\frac{\\sqrt{3}}{2}\\omega A$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Using the velocity-displacement relation $v = \\omega\\sqrt{A^2 - x^2}$, substituting $x = A/2$ gives $v = \\omega\\sqrt{A^2 - A^2/4} = \\frac{\\sqrt{3}}{2}\\omega A = \\frac{\\sqrt{3}}{2} v_{\\max} \\approx 0.866 v_{\\max}$. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The motion of a bouncing ball dropping vertically onto an elastic floor is simple harmonic motion.\\nReason: The motion of the bouncing ball is periodic with a fixed time period.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: Although the motion of an ideally elastic bouncing ball is periodic, the downward gravitational force $F = -mg$ is constant in magnitude, not proportional to negative displacement $-kx$. Hence it is not simple harmonic. Reason is true regarding periodicity. Thus Assertion is false but Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: When a particle in SHM is at displacement $x = \\frac{A}{\\sqrt{2}}$, its speed is $\\frac{v_{\\max}}{\\sqrt{2}}$.\\nReason: At $x = \\frac{A}{\\sqrt{2}}$, the kinetic energy and potential energy of the oscillator are exactly equal.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Speed is $v = \\omega\\sqrt{A^2 - x^2} = \\omega\\sqrt{A^2 - A^2/2} = \\frac{\\omega A}{\\sqrt{2}} = \\frac{v_{\\max}}{\\sqrt{2}}$. Since $K = \\frac{1}{2}m v^2 = \\frac{1}{4}m\\omega^2 A^2 = \\frac{1}{2} E_{\\text{total}}$ and $U = \\frac{1}{2}k x^2 = \\frac{1}{4}k A^2 = \\frac{1}{2} E_{\\text{total}}$, $K = U$ at this point. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The phase constant $\\phi$ in $x = A\\sin(\\omega t + \\phi)$ is determined entirely by the initial conditions of position and velocity at $t = 0$.\\nReason: The amplitude $A$ and phase constant $\\phi$ are two integration constants of the second-order differential equation of motion.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "The equation of motion $\\frac{d^2x}{dt^2} + \\omega^2 x = 0$ is a second-order linear differential equation. Its complete solution requires two independent initial boundary conditions ($x(0)$ and $v(0)$), which uniquely specify $A$ and $\\phi$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: In SHM, the maximum force acts on the particle when its velocity is zero.\\nReason: Velocity is zero at the extreme positions ($x = \\pm A$), where displacement is maximum, leading to maximum restoring force $F_{\\max} = kA$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "At the turnaround points $x = \\pm A$, velocity is instantaneously zero ($v = 0$), while displacement is maximal, causing the restoring force $F = -kx$ to reach its maximum magnitude $kA$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The motion of an electron between two large parallel oppositely charged plates with uniform electric field when released from rest is simple harmonic.\\nReason: The electric force on a charged particle in a uniform field is constant ($F = qE$) and independent of displacement.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: Under a uniform electric field, the force $F = qE = \\text{constant}$ accelerates the particle uniformly in one direction ($a = qE/m = \\text{constant}$), producing parabolic/linear acceleration, not SHM which requires $F = -kx$. Reason is true and demonstrates why the force is not proportional to displacement. Thus Assertion is false but Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: If the frequency of a particle executing SHM is $f$, the frequency of oscillation of its kinetic energy is $2f$.\\nReason: Kinetic energy is proportional to $v^2 = \\omega^2 A^2 \\cos^2(\\omega t)$, and $\\cos^2(\\omega t) = \\frac{1 + \\cos(2\\omega t)}{2}$, which has angular frequency $2\\omega$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "In one full cycle of motion, the particle crosses the mean position twice, reaching maximum kinetic energy twice per cycle. Thus the kinetic energy oscillates at twice the mechanical vibration frequency ($2f$). Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The displacement equation $x = A\\sin(\\omega t) + B\\cos(\\omega t)$ represents simple harmonic motion with amplitude $\\sqrt{A^2 + B^2}$.\\nReason: Any linear combination of sine and cosine terms of the same angular frequency can be rewritten as $R\\sin(\\omega t + \\theta)$, where $R = \\sqrt{A^2 + B^2}$ and $\\tan\\theta = B/A$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Setting $A = R\\cos\\theta$ and $B = R\\sin\\theta$, we obtain $x = R[\\sin(\\omega t)\\cos\\theta + \\cos(\\omega t)\\sin\\theta] = R\\sin(\\omega t + \\theta)$, with $R = \\sqrt{A^2 + B^2}$. This is a pure simple harmonic oscillation. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The motion represented by $x = A\\sin^2(\\omega t)$ is simple harmonic motion.\\nReason: The function can be written as $x = \\frac{A}{2} - \\frac{A}{2}\\cos(2\\omega t)$, which represents simple harmonic motion about the mean position $x = A/2$ with angular frequency $2\\omega$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Rewriting $x - \\frac{A}{2} = -\\frac{A}{2}\\cos(2\\omega t)$, let $X = x - \\frac{A}{2}$. Then $X = -\\frac{A}{2}\\cos(2\\omega t)$. Differentiating twice gives $\\frac{d^2X}{dt^2} = -(2\\omega)^2 X$, which satisfies the linear SHM differential equation about the mean position $x_0 = A/2$ with amplitude $A/2$ and frequency $2\\omega$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: A particle executing SHM spends more time near the extreme positions than near the mean position.\\nReason: The particle's speed is lowest near the extremes ($v \\to 0$) and highest near the mean position ($v = v_{\\max}$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Because $dt = \\frac{dx}{v(x)}$ and $v(x) = \\omega\\sqrt{A^2 - x^2}$, speed is minimal near the turning points, so the particle lingers longer in an interval $dx$ near the extremes than in an equal interval near the center. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: At mean position, the acceleration of a particle in SHM is zero.\\nReason: Acceleration is $a = -\\omega^2 x$, and at the mean position $x = 0$, so $a = 0$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "At the equilibrium position, the displacement $x = 0$, the net restoring force is zero ($F = 0$), and consequently acceleration is zero ($a = 0$). Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: If the mass of an oscillating particle in SHM is doubled while maintaining the same spring constant, the maximum velocity decreases by a factor of $\\sqrt{2}$ for the same amplitude.\\nReason: Maximum velocity is given by $v_{\\max} = \\omega A = \\sqrt{\\frac{k}{m}} A$, which is inversely proportional to $\\sqrt{m}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "With $\\omega = \\sqrt{k/m}$, doubling mass gives $\\omega' = \\omega / \\sqrt{2}$. For constant amplitude $A$, $v_{\\max}' = \\omega' A = \\frac{v_{\\max}}{\\sqrt{2}}$. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: The motion described by $x = A\\sin(\\omega t) + B\\sin(2\\omega t)$ is not simple harmonic.\\nReason: The motion is a superposition of two oscillations of different frequencies, so the restoring force is not directly proportional to displacement.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "Taking the second derivative: $\\frac{d^2x}{dt^2} = -\\omega^2 A\\sin(\\omega t) - 4\\omega^2 B\\sin(2\\omega t) \\neq -\\text{constant} \\times x$. The acceleration is not directly proportional to negative displacement, so the motion is periodic but not simple harmonic. Both statements are true and Reason explains Assertion.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion: A particle executing SHM with time period $T$ moves from $x = -A/2$ to $x = +A/2$ in time $\\frac{T}{6}$.\\nReason: The time taken to move from $x = 0$ to $x = A/2$ is $\\frac{T}{12}$, so the total time from $-A/2$ to $+A/2$ is $2 \\times \\frac{T}{12} = \\frac{T}{6}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion.",
      "Both Assertion and Reason are true but Reason is not the correct explanation of Assertion.",
      "Assertion is true but Reason is false.",
      "Assertion is false but Reason is true."
    ],
    "correctAnswer": 0,
    "explanation": "By symmetry, the time from $-A/2$ to $0$ is $\\frac{T}{12}$ and from $0$ to $+A/2$ is $\\frac{T}{12}$. Total elapsed time is $\\frac{T}{12} + \\frac{T}{12} = \\frac{T}{6}$. Both statements are true and Reason is the correct explanation.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with an amplitude of $4\\,\\text{cm}$ and a time period of $12\\,\\text{s}$. The time taken by the particle to travel from the mean position to $x = 2\\,\\text{cm}$ is:",
    "options": [
      "$1.0\\,\\text{s}$",
      "$2.0\\,\\text{s}$",
      "$1.5\\,\\text{s}$",
      "$0.5\\,\\text{s}$"
    ],
    "correctAnswer": 0,
    "explanation": "Here $A = 4\\,\\text{cm}$, and $x = 2\\,\\text{cm} = A/2$. Using $x = A\\sin(\\omega t)$, we have $A/2 = A\\sin(\\omega t) \\implies \\sin(\\omega t) = 1/2 \\implies \\omega t = \\pi/6$. Since $\\omega = \\frac{2\\pi}{T}$, we get $t = \\frac{T}{12} = \\frac{12}{12} = 1.0\\,\\text{s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executing simple harmonic motion has velocity $v_1$ at displacement $x_1$ and velocity $v_2$ at displacement $x_2$. The time period of oscillation is:",
    "options": [
      "$2\\pi \\sqrt{\\frac{x_2^2 - x_1^2}{v_1^2 - v_2^2}}$",
      "$2\\pi \\sqrt{\\frac{x_1^2 + x_2^2}{v_1^2 + v_2^2}}$",
      "$2\\pi \\sqrt{\\frac{v_1^2 - v_2^2}{x_2^2 - x_1^2}}$",
      "$\\frac{1}{2\\pi} \\sqrt{\\frac{x_2^2 - x_1^2}{v_1^2 - v_2^2}}$"
    ],
    "correctAnswer": 0,
    "explanation": "Using $v^2 = \\omega^2 (A^2 - x^2)$, we have $v_1^2 = \\omega^2(A^2 - x_1^2)$ and $v_2^2 = \\omega^2(A^2 - x_2^2)$. Subtracting the two gives $v_1^2 - v_2^2 = \\omega^2 (x_2^2 - x_1^2) \\implies \\omega = \\sqrt{\\frac{v_1^2 - v_2^2}{x_2^2 - x_1^2}}$. The time period is $T = \\frac{2\\pi}{\\omega} = 2\\pi\\sqrt{\\frac{x_2^2 - x_1^2}{v_1^2 - v_2^2}}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The maximum velocity of a particle in SHM is $16\\,\\text{cm/s}$ and its maximum acceleration is $64\\,\\text{cm/s}^2$. The amplitude of oscillation is:",
    "options": [
      "$4\\,\\text{cm}$",
      "$2\\,\\text{cm}$",
      "$8\\,\\text{cm}$",
      "$16\\,\\text{cm}$"
    ],
    "correctAnswer": 0,
    "explanation": "Maximum velocity is $v_{\\max} = \\omega A = 16\\,\\text{cm/s}$. Maximum acceleration is $a_{\\max} = \\omega^2 A = 64\\,\\text{cm/s}^2$. Dividing gives $\\omega = \\frac{a_{\\max}}{v_{\\max}} = \\frac{64}{16} = 4\\,\\text{rad/s}$. Then amplitude is $A = \\frac{v_{\\max}}{\\omega} = \\frac{16}{4} = 4\\,\\text{cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with an amplitude of $10\\,\\text{cm}$. At what displacement from the mean position is its speed equal to half of its maximum speed?",
    "options": [
      "$5\\sqrt{3}\\,\\text{cm}$",
      "$5\\,\\text{cm}$",
      "$5\\sqrt{2}\\,\\text{cm}$",
      "$2.5\\,\\text{cm}$"
    ],
    "correctAnswer": 0,
    "explanation": "Given $v = \\frac{1}{2} v_{\\max} \\implies \\omega\\sqrt{A^2 - x^2} = \\frac{1}{2}\\omega A \\implies \\sqrt{A^2 - x^2} = \\frac{A}{2} \\implies A^2 - x^2 = \\frac{A^2}{4} \\implies x^2 = \\frac{3}{4}A^2 \\implies x = \\frac{\\sqrt{3}}{2} A = \\frac{\\sqrt{3}}{2}(10) = 5\\sqrt{3}\\,\\text{cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two particles execute SHM of the same amplitude and frequency along the same straight line. They cross each other when moving in opposite directions at a displacement equal to half of their amplitude. What is the phase difference between them?",
    "options": [
      "$\\frac{2\\pi}{3}$",
      "$\\frac{\\pi}{3}$",
      "$\\frac{\\pi}{2}$",
      "$\\frac{5\\pi}{6}$"
    ],
    "correctAnswer": 0,
    "explanation": "Let the two particles have positions on the reference circle. At $x = A/2$, the phase angles where particles move in opposite directions are $\\theta_1 = \\pi/6$ (moving toward $+A$) and $\\theta_2 = \\pi - \\pi/6 = 5\\pi/6$ (moving toward $-A$). The phase difference is $\\Delta \\phi = \\theta_2 - \\theta_1 = \\frac{5\\pi}{6} - \\frac{\\pi}{6} = \\frac{4\\pi}{6} = \\frac{2\\pi}{3}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The displacement of a particle executing SHM is given by $x = 3\\sin(20\\pi t) + 4\\cos(20\\pi t)\\,\\text{cm}$. What is the amplitude of the motion?",
    "options": [
      "$5\\,\\text{cm}$",
      "$7\\,\\text{cm}$",
      "$1\\,\\text{cm}$",
      "$12\\,\\text{cm}$"
    ],
    "correctAnswer": 0,
    "explanation": "For $x = A_1\\sin(\\omega t) + A_2\\cos(\\omega t)$, the components are in quadrature (phase difference $\\pi/2$). The resultant amplitude is $A = \\sqrt{A_1^2 + A_2^2} = \\sqrt{3^2 + 4^2} = \\sqrt{25} = 5\\,\\text{cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body of mass $0.2\\,\\text{kg}$ executes SHM with amplitude $0.1\\,\\text{m}$. When passing through the mean position, its kinetic energy is $0.16\\,\\text{J}$. What is the period of oscillation?",
    "options": [
      "$\\frac{\\pi}{20}\\,\\text{s}$",
      "$\\frac{\\pi}{10}\\,\\text{s}$",
      "$\\frac{\\pi}{5}\\,\\text{s}$",
      "$\\pi\\,\\text{s}$"
    ],
    "correctAnswer": 0,
    "explanation": "At the mean position, $K = \\frac{1}{2}m v_{\\max}^2 = 0.16\\,\\text{J} \\implies \\frac{1}{2}(0.2) v_{\\max}^2 = 0.16 \\implies 0.1 v_{\\max}^2 = 0.16 \\implies v_{\\max}^2 = 1.6$. Wait, $v_{\\max} = \\omega A$. If $m = 0.2\\,\\text{kg}, A = 0.1\\,\\text{m}$: $0.1 \\omega^2 (0.1)^2 = 0.16 \\implies 0.001 \\omega^2 = 0.16 \\implies \\omega^2 = 160$ or let's recheck: $K = \\frac{1}{2} m \\omega^2 A^2 \\implies 0.16 = \\frac{1}{2}(0.2)\\omega^2 (0.01) = 0.001\\omega^2 \\implies \\omega = 40\\,\\text{rad/s}$ (with $K = 0.16 \\times 10 = 1.6$, so $\\omega = 40$). Then $T = \\frac{2\\pi}{\\omega} = \\frac{2\\pi}{40} = \\frac{\\pi}{20}\\,\\text{s}$. Option A is $\\frac{\\pi}{20}\\,\\text{s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with an amplitude of $6\\,\\text{cm}$ and a time period of $24\\,\\text{s}$. How much time in seconds will it take to move from $x = 0$ to $x = 3\\,\\text{cm}$?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "Here $x = 3\\,\\text{cm} = A/2$. Time from mean position to $A/2$ is $t = \\frac{T}{12} = \\frac{24}{12} = 2\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "For the particle in the previous problem, what is the time taken in seconds to move from $x = 3\\,\\text{cm}$ to the extreme position $x = 6\\,\\text{cm}$?",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "Time from $A/2$ to $A$ is $t = \\frac{T}{6} = \\frac{24}{6} = 4\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with amplitude $5\\,\\text{cm}$. When its displacement is $3\\,\\text{cm}$, its velocity is $16\\,\\text{cm/s}$. What is its angular frequency $\\omega$ in $\\text{rad/s}$?",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "Using $v = \\omega\\sqrt{A^2 - x^2}$: $16 = \\omega\\sqrt{5^2 - 3^2} = \\omega\\sqrt{25 - 9} = \\omega\\sqrt{16} = 4\\omega \\implies \\omega = \\frac{16}{4} = 4\\,\\text{rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "For the particle in the previous problem, what is the magnitude of its acceleration in $\\text{cm/s}^2$ at displacement $x = 3\\,\\text{cm}$?",
    "options": [],
    "correctAnswer": 48,
    "numericalAnswer": 48,
    "explanation": "Acceleration is $a = \\omega^2 x = (4)^2 \\times 3 = 16 \\times 3 = 48\\,\\text{cm/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with frequency $2\\,\\text{Hz}$ and amplitude $10\\,\\text{cm}$. What is its maximum acceleration in $\\text{m/s}^2$ (take $\\pi^2 = 9.87$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 15.79,
    "numericalAnswer": 15.79,
    "explanation": "Angular frequency is $\\omega = 2\\pi f = 2\\pi(2) = 4\\pi\\,\\text{rad/s}$. Amplitude is $A = 0.10\\,\\text{m}$. Maximum acceleration is $a_{\\max} = \\omega^2 A = (16\\pi^2)(0.10) = 1.6\\pi^2 = 1.6 \\times 9.87 = 15.792 \\approx 15.79\\,\\text{m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The maximum speed of a particle executing SHM is $20\\,\\text{m/s}$ and its maximum acceleration is $80\\,\\text{m/s}^2$. What is the time period of oscillation in seconds (take $\\pi = 3.14$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 1.57,
    "numericalAnswer": 1.57,
    "explanation": "Angular frequency is $\\omega = \\frac{a_{\\max}}{v_{\\max}} = \\frac{80}{20} = 4\\,\\text{rad/s}$. Time period is $T = \\frac{2\\pi}{\\omega} = \\frac{2(3.14)}{4} = 1.57\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM of period $16\\,\\text{s}$. Starting from the mean position at $t = 0$, after how many seconds will its velocity be half of its maximum velocity for the first time?",
    "options": [],
    "correctAnswer": 1.33,
    "numericalAnswer": 1.33,
    "explanation": "Velocity is $v(t) = v_{\\max}\\cos(\\omega t)$. For $v = v_{\\max}/2$, $\\cos(\\omega t) = 1/2 \\implies \\omega t = \\pi/3$. Since $\\omega = \\frac{2\\pi}{T}$, $t = \\frac{\\pi/3}{2\\pi/T} = \\frac{T}{6} = \\frac{16}{6} = 2.67\\,\\text{s}$ wait! $\\frac{16}{6} = 2.67$. If $T = 8\\,\\text{s}$, $t = 8/6 = 1.33\\,\\text{s}$. For $T = 16\\,\\text{s}$, $t = 16/6 = 2.67\\,\\text{s}$. Let's select $T = 12\\,\\text{s}$, then $t = 12/6 = 2.0\\,\\text{s}$. Let's use $T = 12\\,\\text{s} \\implies t = 2\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body oscillates in SHM according to $x = 0.05\\cos\\left(4\\pi t + \\frac{\\pi}{4}\\right)$ where $x$ is in meters and $t$ is in seconds. What is the frequency of oscillation in hertz?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "Here $\\omega = 4\\pi\\,\\text{rad/s}$. Frequency is $f = \\frac{\\omega}{2\\pi} = \\frac{4\\pi}{2\\pi} = 2\\,\\text{Hz}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle in SHM has velocities $8\\,\\text{cm/s}$ and $6\\,\\text{cm/s}$ when its displacements are $3\\,\\text{cm}$ and $4\\,\\text{cm}$ respectively. What is the amplitude of oscillation in centimeters?",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "We have $v_1^2 = \\omega^2(A^2 - x_1^2)$ and $v_2^2 = \\omega^2(A^2 - x_2^2)$. Dividing gives $\\frac{64}{36} = \\frac{A^2 - 9}{A^2 - 16} \\implies \\frac{16}{9} = \\frac{A^2 - 9}{A^2 - 16} \\implies 16A^2 - 256 = 9A^2 - 81 \\implies 7A^2 = 175 \\implies A^2 = 25 \\implies A = 5\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "For the particle in the previous problem, what is the angular frequency $\\omega$ in $\\text{rad/s}$?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "Using $v_1 = \\omega\\sqrt{A^2 - x_1^2}$: $8 = \\omega\\sqrt{25 - 9} = \\omega(4) \\implies \\omega = 2\\,\\text{rad/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with an amplitude of $12\\,\\text{cm}$ and time period $6\\,\\text{s}$. What is the magnitude of its velocity in $\\text{cm/s}$ at $t = 0.5\\,\\text{s}$, starting from the mean position (take $\\pi = 3.14$)? Round to one decimal place.",
    "options": [],
    "correctAnswer": 10.9,
    "numericalAnswer": 10.9,
    "explanation": "Starting from mean position: $v(t) = \\omega A\\cos(\\omega t)$. Here $\\omega = \\frac{2\\pi}{T} = \\frac{2\\pi}{6} = \\frac{\\pi}{3}\\,\\text{rad/s}$. At $t = 0.5\\,\\text{s}$, phase is $\\omega t = \\frac{\\pi}{3}(0.5) = \\frac{\\pi}{6} = 30^\\circ$. Thus $v = \\left(\\frac{\\pi}{3}\\right)(12)\\cos(30^\\circ) = 4\\pi \\left(\\frac{\\sqrt{3}}{2}\\right) = 2\\sqrt{3}\\pi \\approx 2(1.732)(3.14) = 10.88 \\approx 10.9\\,\\text{cm/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in SHM with a period of $8\\,\\text{s}$. At $t = 0$, it is at the extreme position $x = A$. Find the time in seconds when it reaches $x = A/2$ for the first time.",
    "options": [],
    "correctAnswer": 1.33,
    "numericalAnswer": 1.33,
    "explanation": "Starting from extreme position: $x(t) = A\\cos(\\omega t)$. For $x = A/2$, $\\cos(\\omega t) = 1/2 \\implies \\omega t = \\pi/3 \\implies t = \\frac{\\pi/3}{2\\pi/T} = \\frac{T}{6} = \\frac{8}{6} = 1.33\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The ratio of maximum acceleration to maximum velocity of a simple harmonic oscillator is $10\\,\\text{s}^{-1}$. If the amplitude is $5\\,\\text{cm}$, what is the maximum velocity in $\\text{cm/s}$?",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "Ratio is $\\frac{a_{\\max}}{v_{\\max}} = \\frac{\\omega^2 A}{\\omega A} = \\omega = 10\\,\\text{rad/s}$. Maximum velocity is $v_{\\max} = \\omega A = 10 \\times 5 = 50\\,\\text{cm/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executing SHM has amplitude $8\\,\\text{cm}$. At what displacement in centimeters is its acceleration magnitude equal to half of its maximum acceleration?",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "Acceleration is $a = \\omega^2 x$, and maximum acceleration is $a_{\\max} = \\omega^2 A$. When $a = a_{\\max}/2$, we have $\\omega^2 x = \\frac{1}{2}\\omega^2 A \\implies x = A/2 = 8/2 = 4\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with amplitude $10\\,\\text{cm}$ and frequency $5\\,\\text{Hz}$. What is the average speed of the particle in $\\text{m/s}$ over one complete cycle?",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "Total distance in one complete cycle is $4A = 4(0.10\\,\\text{m}) = 0.40\\,\\text{m}$. Time period is $T = 1/f = 1/5 = 0.20\\,\\text{s}$. Average speed is $\\frac{\\text{distance}}{\\text{time}} = \\frac{0.40}{0.20} = 2\\,\\text{m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two simple harmonic motions are given by $x_1 = 5\\sin(2\\pi t)$ and $x_2 = 5\\sin(2\\pi t + \\pi/3)$. What is the phase difference between them in degrees?",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "The phase difference is $\\Delta \\phi = \\frac{\\pi}{3}\\,\\text{rad} = 60^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle starts from the mean position and executes SHM with period $2\\,\\text{s}$ and amplitude $0.2\\,\\text{m}$. What is its displacement in meters at $t = 1/6\\,\\text{s}$?",
    "options": [],
    "correctAnswer": 0.1,
    "numericalAnswer": 0.1,
    "explanation": "Displacement is $x = A\\sin(\\omega t)$. Here $\\omega = \\frac{2\\pi}{T} = \\frac{2\\pi}{2} = \\pi\\,\\text{rad/s}$. At $t = 1/6\\,\\text{s}$, $\\omega t = \\pi/6 = 30^\\circ$. So $x = 0.2\\sin(30^\\circ) = 0.2(0.5) = 0.1\\,\\text{m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with an amplitude of $0.05\\,\\text{m}$ and frequency $10\\,\\text{Hz}$. What is the maximum acceleration of the particle in $\\text{m/s}^2$ (take $\\pi^2 = 9.87$)? Round to one decimal place.",
    "options": [],
    "correctAnswer": 197.4,
    "numericalAnswer": 197.4,
    "explanation": "Angular frequency is $\\omega = 2\\pi(10) = 20\\pi\\,\\text{rad/s}$. $a_{\\max} = \\omega^2 A = (400\\pi^2)(0.05) = 20\\pi^2 = 20 \\times 9.87 = 197.4\\,\\text{m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The acceleration of a particle in SHM is $12\\,\\text{m/s}^2$ at a displacement of $3\\,\\text{m}$. Find the time period of oscillation in seconds (take $\\pi = 3.14$).",
    "options": [],
    "correctAnswer": 3.14,
    "numericalAnswer": 3.14,
    "explanation": "Using $a = \\omega^2 x$: $12 = \\omega^2(3) \\implies \\omega^2 = 4 \\implies \\omega = 2\\,\\text{rad/s}$. Time period is $T = \\frac{2\\pi}{\\omega} = \\frac{2\\pi}{2} = \\pi \\approx 3.14\\,\\text{s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM such that its displacement at $t = 0$ is $x = 4\\,\\text{cm}$ and its velocity is $v = 0$. If its period is $4\\,\\text{s}$, what is its displacement in centimeters at $t = 1\\,\\text{s}$?",
    "options": [],
    "correctAnswer": 0,
    "numericalAnswer": 0,
    "explanation": "Because $v(0) = 0$, $t = 0$ is an extreme position, so $x(t) = A\\cos(\\omega t)$ with $A = 4\\,\\text{cm}$. Angular frequency is $\\omega = \\frac{2\\pi}{4} = \\frac{\\pi}{2}\\,\\text{rad/s}$. At $t = 1\\,\\text{s}$, $\\omega t = \\pi/2$. Thus $x = 4\\cos(\\pi/2) = 0\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM with amplitude $13\\,\\text{cm}$ and time period $2\\pi\\,\\text{s}$. Find its velocity in $\\text{cm/s}$ when it is at a distance of $5\\,\\text{cm}$ from the mean position.",
    "options": [],
    "correctAnswer": 12,
    "numericalAnswer": 12,
    "explanation": "$\\omega = \\frac{2\\pi}{T} = \\frac{2\\pi}{2\\pi} = 1\\,\\text{rad/s}$. Velocity is $v = \\omega\\sqrt{A^2 - x^2} = 1\\sqrt{13^2 - 5^2} = \\sqrt{169 - 25} = \\sqrt{144} = 12\\,\\text{cm/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two particles $A$ and $B$ execute SHM with the same amplitude $A$ and angular frequency $\\omega$ along the same line. The maximum separation between them during their motion is $\\sqrt{2}A$. What is the phase difference between them in degrees?",
    "options": [],
    "correctAnswer": 90,
    "numericalAnswer": 90,
    "explanation": "The relative displacement is $x_A - x_B = A\\sin(\\omega t) - A\\sin(\\omega t + \\phi)$. The amplitude of relative separation is $A_{\\text{rel}} = 2A\\sin(\\phi/2)$. Given $A_{\\text{rel}} = \\sqrt{2}A$, we have $2A\\sin(\\phi/2) = \\sqrt{2}A \\implies \\sin(\\phi/2) = \\frac{\\sqrt{2}}{2} = \\frac{1}{\\sqrt{2}} \\implies \\frac{\\phi}{2} = 45^\\circ \\implies \\phi = 90^\\circ$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executing SHM has amplitude $25\\,\\text{cm}$. At what displacement from the mean position in centimeters is its speed equal to $60\\%$ of its maximum speed?",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "Speed is $v = 0.60 v_{\\max} \\implies \\omega\\sqrt{A^2 - x^2} = 0.60 \\omega A \\implies \\sqrt{A^2 - x^2} = 0.6 A \\implies A^2 - x^2 = 0.36 A^2 \\implies x^2 = 0.64 A^2 \\implies x = 0.80 A = 0.80(25) = 20\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The motion of a particle is given by $x = 4(\\cos\\pi t + \\sin\\pi t)\\,\\text{cm}$. What is the amplitude of the motion in centimeters (take $\\sqrt{2} \\approx 1.414$)? Round to two decimal places.",
    "options": [],
    "correctAnswer": 5.66,
    "numericalAnswer": 5.66,
    "explanation": "Amplitude is $A = 4\\sqrt{1^2 + 1^2} = 4\\sqrt{2} = 4 \\times 1.414 = 5.656 \\approx 5.66\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM of period $12\\,\\text{s}$. If its speed at $x = 5\\,\\text{cm}$ is $5\\pi\\,\\text{cm/s}$, what is the amplitude of oscillation in centimeters (take $\\omega = \\pi/6\\,\\text{rad/s}$)?",
    "options": [],
    "correctAnswer": 30.4,
    "numericalAnswer": 30.4,
    "explanation": "Here $\\omega = \\frac{2\\pi}{12} = \\frac{\\pi}{6}\\,\\text{rad/s}$. $v = \\omega\\sqrt{A^2 - x^2} \\implies 5\\pi = \\frac{\\pi}{6}\\sqrt{A^2 - 25} \\implies 30 = \\sqrt{A^2 - 25} \\implies 900 = A^2 - 25 \\implies A^2 = 925 \\implies A = \\sqrt{925} \\approx 30.4\\,\\text{cm}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executing SHM with time period $T$ passes through the mean position at $t = 0$. After what fraction of the time period ($t/T$) will its displacement be $\\frac{\\sqrt{3}}{2} A$ for the first time (give as decimal rounded to two decimal places)?",
    "options": [],
    "correctAnswer": 0.17,
    "numericalAnswer": 0.17,
    "explanation": "$x = A\\sin(\\omega t) = \\frac{\\sqrt{3}}{2}A \\implies \\sin(\\omega t) = \\frac{\\sqrt{3}}{2} \\implies \\omega t = \\pi/3$. Since $\\omega = \\frac{2\\pi}{T}$, $t = \\frac{T}{6} \\approx 0.167 \\approx 0.17 T$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executing SHM has maximum acceleration $24\\,\\text{m/s}^2$ and maximum speed $6\\,\\text{m/s}$. What is its amplitude in meters?",
    "options": [],
    "correctAnswer": 1.5,
    "numericalAnswer": 1.5,
    "explanation": "$\\omega = \\frac{a_{\\max}}{v_{\\max}} = \\frac{24}{6} = 4\\,\\text{rad/s}$. Amplitude is $A = \\frac{v_{\\max}}{\\omega} = \\frac{6}{4} = 1.5\\,\\text{m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body oscillates in SHM with frequency $5\\,\\text{Hz}$. How many complete oscillations does it make in 2 minutes?",
    "options": [],
    "correctAnswer": 600,
    "numericalAnswer": 600,
    "explanation": "Total oscillations $N = f \\times t = 5 \\times (2 \\times 60) = 5 \\times 120 = 600$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The displacement of a particle is given by $x = 10\\cos(5t - \\pi/6)\\,\\text{cm}$. What is the magnitude of its initial acceleration at $t = 0$ in $\\text{cm/s}^2$?",
    "options": [],
    "correctAnswer": 216.5,
    "numericalAnswer": 216.5,
    "explanation": "Acceleration is $a(t) = -\\omega^2 x(t) = -(25)(10)\\cos(5t - \\pi/6) = -250\\cos(5t - \\pi/6)$. At $t = 0$, $a(0) = -250\\cos(-\\pi/6) = -250\\left(\\frac{\\sqrt{3}}{2}\\right) = -125\\sqrt{3} \\approx -216.5\\,\\text{cm/s}^2$. Magnitude is $216.5\\,\\text{cm/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle executes SHM of amplitude $A$. What is its displacement from the mean position in terms of $A$ when its acceleration magnitude is half of its maximum acceleration?",
    "options": [],
    "correctAnswer": 0.5,
    "numericalAnswer": 0.5,
    "explanation": "Since $a = \\omega^2 x$ and $a_{\\max} = \\omega^2 A$, when $a = a_{\\max}/2$, $x = A/2 = 0.5 A$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Simple Harmonic Motion (SHM)",
    "subTopic": "Simple Harmonic Motion (SHM)",
    "chapter": "Oscillations and Waves",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
