// Subtopic 1: Domain and range of inverse trigonometric functions (30 questions: 10 MCQ, 10 AR, 10 NUM)
module.exports = [
  // --- MCQ 1 to 10 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The domain of the function $f(x) = \\sin^{-1}\\left(\\frac{x-3}{2}\\right) - \\log_{10}(4-x)$ is:",
    options: [
      "$[1, 4)$",
      "$[1, 5]$",
      "$(1, 4)$",
      "$[1, 4]$"
    ],
    correctAnswer: 0,
    explanation: "For $\\sin^{-1}\\left(\\frac{x-3}{2}\\right)$ to be defined, we require: $$-1 \\le \\frac{x-3}{2} \\le 1 \\implies -2 \\le x - 3 \\le 2 \\implies 1 \\le x \\le 5$$. For $\\log_{10}(4-x)$ to be defined, we require: $$4 - x > 0 \\implies x < 4$$. Taking the intersection of $x \\in [1, 5]$ and $x < 4$, we obtain the domain $x \\in [1, 4)$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The domain of the function $f(x) = \\cos^{-1}\\left(2x^2 - 1\\right)$ is:",
    options: [
      "$[-1, 1]$",
      "$[0, 1]$",
      "$[-1, 0]$",
      "$\\left[-\\frac{1}{\\sqrt{2}}, \\frac{1}{\\sqrt{2}}\\right]$"
    ],
    correctAnswer: 0,
    explanation: "For $\\cos^{-1}(y)$ to be defined, $-1 \\le y \\le 1$. Here $y = 2x^2 - 1$, so: $$-1 \\le 2x^2 - 1 \\le 1 \\implies 0 \\le 2x^2 \\le 2 \\implies 0 \\le x^2 \\le 1$$. Taking the square root gives $-1 \\le x \\le 1$. Hence, the domain is $[-1, 1]$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The range of the function $f(x) = \\sin^{-1}(x) + \\cos^{-1}(x) + \\tan^{-1}(x)$ is:",
    options: [
      "$\\left[\\frac{\\pi}{4}, \\frac{3\\pi}{4}\\right]$",
      "$\\left(0, \\pi\\right)$",
      "$\\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]$",
      "$\\left[0, \\frac{3\\pi}{4}\\right]$"
    ],
    correctAnswer: 0,
    explanation: "The domain of $f(x)$ is determined by the intersection of the domains of $\\sin^{-1} x$, $\\cos^{-1} x$, and $\\tan^{-1} x$, which is $[-1, 1]$. For any $x \\in [-1, 1]$, $\\sin^{-1}(x) + \\cos^{-1}(x) = \\frac{\\pi}{2}$. Thus, $f(x) = \\frac{\\pi}{2} + \\tan^{-1}(x)$. Since $x \\in [-1, 1]$, $\\tan^{-1}(x) \\in \\left[-\\frac{\\pi}{4}, \\frac{\\pi}{4}\\right]$. Therefore, $f(x) \\in \\left[\\frac{\\pi}{2} - \\frac{\\pi}{4}, \\frac{\\pi}{2} + \\frac{\\pi}{4}\\right] = \\left[\\frac{\\pi}{4}, \\frac{3\\pi}{4}\\right]$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The domain of $f(x) = \\sqrt{\\cos^{-1}(x) - \\sin^{-1}(x)}$ is:",
    options: [
      "$\\left[-1, \\frac{1}{\\sqrt{2}}\\right]$",
      "$\\left[\\frac{1}{\\sqrt{2}}, 1\\right]$",
      "$[-1, 1]$",
      "$\\left[0, \\frac{1}{\\sqrt{2}}\\right]$"
    ],
    correctAnswer: 0,
    explanation: "First, $x \\in [-1, 1]$. For the square root to be real: $$\\cos^{-1}(x) - \\sin^{-1}(x) \\ge 0 \\implies \\cos^{-1}(x) \\ge \\sin^{-1}(x)$$. Using $\\cos^{-1}(x) = \\frac{\\pi}{2} - \\sin^{-1}(x)$: $$\\frac{\\pi}{2} - \\sin^{-1}(x) \\ge \\sin^{-1}(x) \\implies 2\\sin^{-1}(x) \\le \\frac{\\pi}{2} \\implies \\sin^{-1}(x) \\le \\frac{\\pi}{4}$$. Since $\\sin^{-1}$ is an increasing function on $[-1, 1]$: $$-1 \\le x \\le \\sin\\left(\\frac{\\pi}{4}\\right) = \\frac{1}{\\sqrt{2}}$$. Thus, the domain is $\\left[-1, \\frac{1}{\\sqrt{2}}\\right]$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The range of the function $f(x) = \\left(\\sin^{-1} x\\right)^2 + \\left(\\cos^{-1} x\\right)^2$ is:",
    options: [
      "$\\left[\\frac{\\pi^2}{8}, \\frac{5\\pi^2}{4}\\right]$",
      "$\\left[\\frac{\\pi^2}{4}, \\frac{5\\pi^2}{4}\\right]$",
      "$\\left[\\frac{\\pi^2}{8}, \\pi^2\\right]$",
      "$\\left[0, \\frac{5\\pi^2}{4}\\right]$"
    ],
    correctAnswer: 0,
    explanation: "Let $\\theta = \\sin^{-1} x \\in \\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]$. Then $\\cos^{-1} x = \\frac{\\pi}{2} - \\theta$. Thus: $$f(x) = \\theta^2 + \\left(\\frac{\\pi}{2} - \\theta\\right)^2 = 2\\theta^2 - \\pi\\theta + \\frac{\\pi^2}{4} = 2\\left(\\theta - \\frac{\\pi}{4}\\right)^2 + \\frac{\\pi^2}{8}$$. The minimum occurs at $\\theta = \\frac{\\pi}{4}$, where $f_{\\min} = \\frac{\\pi^2}{8}$. The maximum occurs at the boundary point farthest from $\\frac{\\pi}{4}$, which is $\\theta = -\\frac{\\pi}{2}$: $$f_{\\max} = 2\\left(-\\frac{\\pi}{2} - \\frac{\\pi}{4}\\right)^2 + \\frac{\\pi^2}{8} = 2\\left(-\\frac{3\\pi}{4}\\right)^2 + \\frac{\\pi^2}{8} = 2\\left(\\frac{9\\pi^2}{16}\\right) + \\frac{\\pi^2}{8} = \\frac{9\\pi^2}{8} + \\frac{\\pi^2}{8} = \\frac{10\\pi^2}{8} = \\frac{5\\pi^2}{4}$$. Therefore, the range is $\\left[\\frac{\\pi^2}{8}, \\frac{5\\pi^2}{4}\\right]$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The domain of $f(x) = \\sec^{-1}\\left(\\frac{x}{\\sqrt{x - [x]}}\\right)$, where $[\\cdot]$ denotes the greatest integer function, is:",
    options: [
      "$(1, \\infty) \\setminus \\mathbb{Z}$",
      "$\\mathbb{R} \\setminus \\mathbb{Z}$",
      "$(0, \\infty) \\setminus \\mathbb{Z}$",
      "$[1, \\infty)$"
    ],
    correctAnswer: 0,
    explanation: "Let $\{x\} = x - [x]$ denote the fractional part of $x$. For $\{x\}$ in the denominator under the square root, we must have $\{x\} > 0 \\implies x \\notin \\mathbb{Z}$. Now, for $\\sec^{-1}(u)$ to be defined, $|u| \\ge 1$: $$\\left|\\frac{x}{\\sqrt{\\{x\\}}}\\right| \\ge 1 \\implies \\frac{x^2}{\\{x\\}} \\ge 1 \\implies x^2 \\ge \\{x\\}$$. Since $0 < \\{x\\} < 1$, if $x \\ge 1$, then $x^2 \\ge 1 > \\{x\\}$, which always holds for all non-integers $x > 1$. If $x < 0$, $x / \\sqrt{\\{x\\}} < 0$, so $|u| = -x / \\sqrt{\\{x\\}} \\ge 1 \\implies x^2 \\ge \\{x\\}$, which holds for $x \\le -1$. However, notice $\\sec^{-1}(u)$ is defined for $|u| \\ge 1$. For $x > 1$ with $x \\notin \\mathbb{Z}$, $u = x / \\sqrt{\\{x\\}} > 1$, so $u \\ge 1$. For $x \\in (1, \\infty) \\setminus \\mathbb{Z}$, the condition is completely satisfied.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The domain of the function $f(x) = \\sqrt{\\sin^{-1}(2x) + \\frac{\\pi}{6}}$ is:",
    options: [
      "$\\left[-\\frac{1}{4}, \\frac{1}{2}\\right]$",
      "$\\left[-\\frac{1}{2}, \\frac{1}{2}\\right]$",
      "$\\left[-\\frac{1}{4}, 1\\right]$",
      "$\\left[0, \\frac{1}{2}\\right]$"
    ],
    correctAnswer: 0,
    explanation: "First, the argument of $\\sin^{-1}$ must satisfy $-1 \\le 2x \\le 1 \\implies -\\frac{1}{2} \\le x \\le \\frac{1}{2}$. Second, the quantity under the radical must be non-negative: $$\\sin^{-1}(2x) + \\frac{\\pi}{6} \\ge 0 \\implies \\sin^{-1}(2x) \\ge -\\frac{\\pi}{6}$$. Since $\\sin$ is strictly increasing: $$2x \\ge \\sin\\left(-\\frac{\\pi}{6}\\right) = -\\frac{1}{2} \\implies x \\ge -\\frac{1}{4}$$. Combining with $x \\le \\frac{1}{2}$, we obtain the domain $\\left[-\\frac{1}{4}, \\frac{1}{2}\\right]$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The domain of the function $f(x) = \\sin^{-1}\\left(\\log_2\\left(\\frac{x}{3}\\right)\\right)$ is:",
    options: [
      "$\\left[\\frac{3}{2}, 6\\right]$",
      "$\\left(0, 6\\right]$",
      "$\\left[\\frac{3}{2}, 3\\right]$",
      "$[1, 6]$"
    ],
    correctAnswer: 0,
    explanation: "For the logarithm to be defined, $x/3 > 0 \\implies x > 0$. For the inverse sine to be defined: $$-1 \\le \\log_2\\left(\\frac{x}{3}\\right) \\le 1$$. Since the base $2 > 1$, the inequality is preserved: $$2^{-1} \\le \\frac{x}{3} \\le 2^1 \\implies \\frac{1}{2} \\le \\frac{x}{3} \\le 2 \\implies \\frac{3}{2} \\le x \\le 6$$. Both bounds satisfy $x > 0$. Thus, the domain is $\\left[\\frac{3}{2}, 6\\right]$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The range of the function $f(x) = \\cot^{-1}\\left(2x - x^2\\right)$ is:",
    options: [
      "$\\left[\\frac{\\pi}{4}, \\pi\\right)$",
      "$\\left(0, \\frac{\\pi}{4}\\right]$",
      "$\\left[\\frac{\\pi}{4}, \\frac{\\pi}{2}\\right]$",
      "$(0, \\pi)$"
    ],
    correctAnswer: 0,
    explanation: "Let $u(x) = 2x - x^2 = 1 - (x-1)^2$. Since $(x-1)^2 \\ge 0$, the maximum value of $u(x)$ is $1$, achieved at $x = 1$. Thus, $u \\in (-\\infty, 1]$. The function $\\cot^{-1}(u)$ is strictly decreasing on $(-\\infty, \\infty)$. As $u \\to -\\infty$, $\\cot^{-1}(u) \\to \\pi$. At $u = 1$, $\\cot^{-1}(1) = \\frac{\\pi}{4}$. Therefore, the range of $\\cot^{-1}(u)$ for $u \\le 1$ is $\\left[\\frac{\\pi}{4}, \\pi\\right)$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The domain of the function $f(x) = \\cos^{-1}\\left(\\frac{2-|x|}{4}\\right) + [\\log(3-x)]^{-1}$ is:",
    options: [
      "$[-2, 3) \\setminus \\{2\\}$",
      "$[-6, 3) \\setminus \\{2\\}$",
      "$[-6, 2)$",
      "$[-2, 6]$"
    ],
    correctAnswer: 1,
    explanation: "For $\\cos^{-1}\\left(\\frac{2-|x|}{4}\\right)$ to be defined: $$-1 \\le \\frac{2-|x|}{4} \\le 1 \\implies -4 \\le 2 - |x| \\le 4 \\implies -6 \\le -|x| \\le 2 \\implies |x| \\le 6 \\implies x \\in [-6, 6]$$. For $[\\log(3-x)]^{-1}$ to be defined: $3 - x > 0 \\implies x < 3$, and $\\log(3-x) \\ne 0 \\implies 3 - x \\ne 1 \\implies x \\ne 2$. Intersecting $[-6, 6]$ with $x < 3$ and $x \\ne 2$ yields $[-6, 3) \\setminus \\{2\\}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- AR 11 to 20 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The domain of $f(x) = \\sin^{-1}(x) + \\cos^{-1}(x)$ is $[-1, 1]$.\nReason (R): Both $\\sin^{-1}(x)$ and $\\cos^{-1}(x)$ are defined if and only if $x \\in [-1, 1]$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "The domain of a sum of two functions is the intersection of their individual domains. The domain of $\\sin^{-1} x$ is $[-1, 1]$ and the domain of $\\cos^{-1} x$ is $[-1, 1]$. Their intersection is $[-1, 1]$. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The range of $f(x) = \\sec^{-1}(x)$ is $[0, \\pi] \\setminus \\left\\{\\frac{\\pi}{2}\\right\\}$.\nReason (R): $\\cos\\left(\\frac{\\pi}{2}\\right) = 0$, and secant is undefined at $\\frac{\\pi}{2}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "By definition, $\\sec^{-1}(x) = \\theta \\iff \\sec\\theta = x$ with $\\theta \\in [0, \\pi]$ and $\\theta \\ne \\frac{\\pi}{2}$ because $\\sec\\theta$ is undefined at $\\theta = \\frac{\\pi}{2}$ where $\\cos\\theta = 0$. Thus, both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The maximum value of $f(x) = (\\sin^{-1} x)^3 + (\\cos^{-1} x)^3$ is $\\frac{7\\pi^3}{8}$.\nReason (R): For $x \\in [-1, 1]$, $\\sin^{-1} x + \\cos^{-1} x = \\frac{\\pi}{2}$, and the maximum occurs at the boundary point $x = -1$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Let $\\theta = \\sin^{-1} x$. Then $\\theta \\in [-\\pi/2, \\pi/2]$ and $\\cos^{-1} x = \\pi/2 - \\theta$. $f(x) = \\theta^3 + (\\pi/2 - \\theta)^3 = (\\pi/2)[\\theta^2 - \\theta(\\pi/2 - \\theta) + (\\pi/2 - \\theta)^2] = (\\pi/2)[3\\theta^2 - 3\\theta\\frac{\\pi}{2} + \\frac{\\pi^2}{4}] = \\frac{3\\pi}{2}\\left(\\theta - \\frac{\\pi}{4}\\right)^2 + \\frac{\\pi^3}{32}$. The maximum occurs at the point furthest from $\\pi/4$, which is $\\theta = -\\pi/2$: $f_{\\max} = \\frac{3\\pi}{2}\\left(-\\frac{3\\pi}{4}\\right)^2 + \\frac{\\pi^3}{32} = \\frac{3\\pi}{2}\\frac{9\\pi^2}{16} + \\frac{\\pi^3}{32} = \\frac{27\\pi^3}{32} + \\frac{\\pi^3}{32} = \\frac{28\\pi^3}{32} = \\frac{7\\pi^3}{8}$, which corresponds to $x = -1$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The domain of $f(x) = \\tan^{-1}\\left(\\sqrt{x^2 - 1}\\right)$ is $(-\\infty, -1] \\cup [1, \\infty)$.\nReason (R): For the square root $\\sqrt{x^2-1}$ to be real, we must have $x^2 - 1 \\ge 0$, while the domain of $\\tan^{-1}(u)$ is all real numbers $\\mathbb{R}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Since $\\tan^{-1}(u)$ accepts all real values $u \\in \\mathbb{R}$, the only restriction comes from the radical $\\sqrt{x^2 - 1}$, which requires $x^2 - 1 \\ge 0 \\implies x \\in (-\\infty, -1] \\cup [1, \\infty)$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The range of $f(x) = \\cos^{-1}(x)$ is $[0, \\pi]$.\nReason (R): The function $\\cos(x)$ is bijective when its domain is restricted to $[0, \\pi]$ and its codomain is $[-1, 1]$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "To define the inverse function $\\cos^{-1}(x)$, the cosine function is restricted to its principal domain $[0, \\pi]$, where it is strictly decreasing and one-to-one with range $[-1, 1]$. Thus, the range of the inverse function is the restricted domain $[0, \\pi]$. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The domain of $f(x) = \\sin^{-1}(|x| - 1)$ is $[-2, 2]$.\nReason (R): The inequality $-1 \\le |x| - 1 \\le 1$ implies $0 \\le |x| \\le 2$, which gives $-2 \\le x \\le 2$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "For $\\sin^{-1}(|x|-1)$ to be defined, $-1 \\le |x| - 1 \\le 1$. Adding $1$ across the inequality yields $0 \\le |x| \\le 2$. Since $|x| \\ge 0$ is always true, $|x| \\le 2 \\implies -2 \\le x \\le 2$. Both (A) and (R) are true, and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The function $f(x) = \\tan^{-1}(x)$ is bounded on $\\mathbb{R}$.\nReason (R): For all $x \\in \\mathbb{R}$, $-\\frac{\\pi}{2} < \\tan^{-1}(x) < \\frac{\\pi}{2}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "A function is bounded if there exist real numbers $m$ and $M$ such that $m \\le f(x) \\le M$ for all $x$. Since the range of $\\tan^{-1}(x)$ is $\\left(-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right)$, $|\\tan^{-1}(x)| < \\frac{\\pi}{2}$ for all $x \\in \\mathbb{R}$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The function $f(x) = \\sin^{-1}(x^2 + 1)$ has an empty domain.\nReason (R): For any real $x$, $x^2 + 1 \\ge 1$, so $x^2 + 1 \\in [-1, 1]$ if and only if $x = 0$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 3,
    explanation: "For $\\sin^{-1}(x^2+1)$ to be defined, $-1 \\le x^2 + 1 \\le 1$. Since $x^2 \\ge 0$, $x^2 + 1 \\ge 1$. The only value satisfying $x^2 + 1 \\le 1$ is $x^2 = 0 \\implies x = 0$. Thus, the domain of $f(x)$ is the singleton set $\\{0\\}$, which is NOT empty! Therefore, Assertion (A) is false, but Reason (R) is true.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The domain of $f(x) = \\csc^{-1}(x)$ is $(-\\infty, -1] \\cup [1, \\infty)$.\nReason (R): $\\csc(\\theta) = \\frac{1}{\\sin(\\theta)}$, and since $|\\sin(\\theta)| \\le 1$, we have $|\\csc(\\theta)| \\ge 1$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "The domain of the inverse cosecant function is the range of the cosecant function. Since $|\\sin\\theta| \\le 1$, $|\\csc\\theta| \\ge 1$, meaning $\\csc\\theta \\in (-\\infty, -1] \\cup [1, \\infty)$. Thus, the domain of $\\csc^{-1}(x)$ is $(-\\infty, -1] \\cup [1, \\infty)$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The range of $f(x) = \\cos^{-1}(\\cos x)$ for $x \\in \\mathbb{R}$ is $[0, \\pi]$.\nReason (R): The codomain (principal range) of $\\cos^{-1}(y)$ is $[0, \\pi]$ for all $y \\in [-1, 1]$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "For any $x \\in \\mathbb{R}$, $\\cos x \\in [-1, 1]$. By definition, $\\cos^{-1}(y)$ outputs values exclusively in the principal interval $[0, \\pi]$. As $x$ ranges over $[0, \\pi]$, $\\cos^{-1}(\\cos x) = x$ covers every value in $[0, \\pi]$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- NUM 21 to 30 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the number of integers in the domain of the function $f(x) = \\sin^{-1}\\left(\\frac{x}{2}\\right) + \\log_e(x+1)$.",
    options: [],
    correctAnswer: 3,
    explanation: "For $\\sin^{-1}(x/2)$ to be defined, $-1 \\le x/2 \\le 1 \\implies -2 \\le x \\le 2$. For $\\log_e(x+1)$ to be defined, $x+1 > 0 \\implies x > -1$. The intersection is $x \\in (-1, 2]$. The integers in this interval are $0, 1, 2$. Thus, there are $3$ integers.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the number of integers in the domain of the function $f(x) = \\sin^{-1}\\left(\\frac{x^2 - 5x + 6}{2}\\right)$.",
    options: [],
    correctAnswer: 4,
    explanation: "We require $-1 \\le \\frac{x^2 - 5x + 6}{2} \\le 1 \\implies -2 \\le x^2 - 5x + 6 \\le 2$. The lower inequality $x^2 - 5x + 8 \\ge 0$ has $D = 25 - 32 = -7 < 0$, so it holds for all real $x$. The upper inequality is $x^2 - 5x + 4 \\le 0 \\implies (x-1)(x-4) \\le 0 \\implies 1 \\le x \\le 4$. The integers in this interval are $1, 2, 3, 4$, so there are $4$ integers.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the domain of $f(x) = \\cos^{-1}\\left(\\frac{x^2 - 4}{5}\\right)$ is $[-\\alpha, \\alpha]$, find the value of $\\alpha$.",
    options: [],
    correctAnswer: 3,
    explanation: "We require: $$-1 \\le \\frac{x^2 - 4}{5} \\le 1 \\implies -5 \\le x^2 - 4 \\le 5 \\implies -1 \\le x^2 \\le 9$$. Since $x^2 \\ge 0$ is always true, the condition becomes $x^2 \\le 9 \\implies -3 \\le x \\le 3$. Therefore, $\\alpha = 3$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the maximum value of $f(x) = (\\sin^{-1} x)^2 + (\\cos^{-1} x)^2$ is $k \\pi^2$, find the value of $8k$.",
    options: [],
    correctAnswer: 10,
    explanation: "As established, $f(x) = 2\\left(\\theta - \\frac{\\pi}{4}\\right)^2 + \\frac{\\pi^2}{8}$ where $\\theta = \\sin^{-1} x \\in [-\\frac{\\pi}{2}, \\frac{\\pi}{2}]$. The maximum occurs at $\\theta = -\\frac{\\pi}{2}$: $$f_{\\max} = 2\\left(-\\frac{3\\pi}{4}\\right)^2 + \\frac{\\pi^2}{8} = 2\\left(\\frac{9\\pi^2}{16}\\right) + \\frac{\\pi^2}{8} = \\frac{10\\pi^2}{8} = \\frac{5}{4}\\pi^2$$. Thus, $k = \\frac{10}{8} = \\frac{5}{4}$, so $8k = 8 \\times \\frac{5}{4} = 10$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the number of integers in the domain of $f(x) = \\sin^{-1}\\left(\\frac{x-1}{3}\\right) + \\cos^{-1}\\left(\\frac{x-2}{4}\\right)$.",
    options: [],
    correctAnswer: 7,
    explanation: "For $\\sin^{-1}\\left(\\frac{x-1}{3}\\right)$: $-1 \\le \\frac{x-1}{3} \\le 1 \\implies -3 \\le x - 1 \\le 3 \\implies -2 \\le x \\le 4$. For $\\cos^{-1}\\left(\\frac{x-2}{4}\\right)$: $-1 \\le \\frac{x-2}{4} \\le 1 \\implies -4 \\le x - 2 \\le 4 \\implies -2 \\le x \\le 6$. The intersection of both intervals is $[-2, 4]$. The integers in $[-2, 4]$ are $-2, -1, 0, 1, 2, 3, 4$, which is $4 - (-2) + 1 = 7$ integers.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the domain of $f(x) = \\sqrt{9 - x^2} + \\sin^{-1}\\left(\\frac{2x-1}{3}\\right)$ is $[a, b]$, find the value of $b - a$.",
    options: [],
    correctAnswer: 3,
    explanation: "For $\\sqrt{9-x^2}$: $9 - x^2 \\ge 0 \\implies -3 \\le x \\le 3$. For $\\sin^{-1}\\left(\\frac{2x-1}{3}\\right)$: $-1 \\le \\frac{2x-1}{3} \\le 1 \\implies -3 \\le 2x - 1 \\le 3 \\implies -2 \\le 2x \\le 4 \\implies -1 \\le x \\le 2$. The intersection of $[-3, 3]$ and $[-1, 2]$ is $[-1, 2]$. Thus, $a = -1, b = 2$, so $b - a = 2 - (-1) = 3$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the range of $f(x) = \\sin^{-1}(x) + \\cos^{-1}(x) + \\tan^{-1}(x)$ is $[a, b]$, find the value of $\\frac{b-a}{\\pi/4}$.",
    options: [],
    correctAnswer: 2,
    explanation: "The domain of $f(x)$ is $[-1, 1]$. For $x \\in [-1, 1]$, $\\sin^{-1} x + \\cos^{-1} x = \\frac{\\pi}{2}$. Thus, $f(x) = \\frac{\\pi}{2} + \\tan^{-1}(x)$. Since $x \\in [-1, 1]$, $\\tan^{-1}(x) \\in [-\\frac{\\pi}{4}, \\frac{\\pi}{4}]$. Therefore, the range is $[a, b] = [\\frac{\\pi}{4}, \\frac{3\\pi}{4}]$. Thus, $b - a = \\frac{3\\pi}{4} - \\frac{\\pi}{4} = \\frac{\\pi}{2} = 2 \\times \\frac{\\pi}{4}$. Hence, $\\frac{b-a}{\\pi/4} = 2$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the number of integers in the domain of $f(x) = \\cos^{-1}\\left(\\frac{x}{4}\\right) + \\csc^{-1}(x)$.",
    options: [],
    correctAnswer: 8,
    explanation: "For $\\cos^{-1}(x/4)$: $-1 \\le x/4 \\le 1 \\implies -4 \\le x \\le 4$. For $\\csc^{-1}(x)$: $|x| \\ge 1 \\implies x \\in (-\\infty, -1] \\cup [1, \\infty)$. Taking the intersection gives $x \\in [-4, -1] \\cup [1, 4]$. The integers are $\\{-4, -3, -2, -1\\} \\cup \\{1, 2, 3, 4\\}$. There are $4 + 4 = 8$ integers.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the domain of $f(x) = \\sin^{-1}(2x) + \\cos^{-1}(3x)$ is $[-\\alpha, \\alpha]$, find the value of $6\\alpha$.",
    options: [],
    correctAnswer: 2,
    explanation: "For $\\sin^{-1}(2x)$: $-1/2 \\le x \\le 1/2$. For $\\cos^{-1}(3x)$: $-1/3 \\le x \\le 1/3$. The intersection of $[-1/2, 1/2]$ and $[-1/3, 1/3]$ is $[-1/3, 1/3]$. Thus, $\\alpha = 1/3$, and $6\\alpha = 6 \\times \\frac{1}{3} = 2$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "Inverse Trigonometric Functions",
    subTopic: "Domain and range of inverse trigonometric functions",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If the minimum value of $f(x) = (\\sin^{-1} x)^2 + (\\cos^{-1} x)^2$ is $m \\pi^2$, find the value of $8m$.",
    options: [],
    correctAnswer: 1,
    explanation: "From $f(x) = 2\\left(\\theta - \\frac{\\pi}{4}\\right)^2 + \\frac{\\pi^2}{8}$, the minimum value is $\\frac{\\pi^2}{8}$ at $\\theta = \\frac{\\pi}{4}$. Thus, $m = \\frac{1}{8}$, which implies $8m = 8 \\times \\frac{1}{8} = 1$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  }
];
