// Auto-generated Part 4 for Physics and Measurement - Least count and precision
module.exports = [
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** A screw gauge is generally more precise than a vernier calliper.\n\n**Reason:** The least count of a standard screw gauge is usually $0.001\\text{ cm}$ ($0.01\\text{ mm}$), whereas that of a standard vernier calliper is $0.01\\text{ cm}$ ($0.1\\text{ mm}$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Precision of an instrument depends directly on its least count. Smaller least count means greater precision. Since a typical screw gauge has a least count of $0.01\\text{ mm}$ compared to $0.1\\text{ mm}$ for a vernier calliper, it is more precise. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** Positive zero error of an instrument is always subtracted from the observed reading to get the true reading.\n\n**Reason:** Positive zero error indicates that the instrument indicates a reading greater than zero even when the measured dimension is zero.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "When zero error is positive, the instrument measures more than the actual value. To get the true reading, the positive zero error must be subtracted: $\\text{True Reading} = \\text{Observed Reading} - \\text{Zero Error}$. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** Negative zero error in a vernier calliper means the zero mark of the vernier scale lies to the right of the zero mark of the main scale when jaws are closed.\n\n**Reason:** When the zero of the vernier scale lies to the left of the main scale zero, the reading is less than zero, so the error is negative.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 3,
    "explanation": "When jaws are closed, if the zero mark of the vernier scale lies to the right of the main scale zero, it is positive zero error. If it lies to the left of the main scale zero, it is negative zero error. Therefore, Assertion is false, while Reason is true.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** In a vernier calliper, if $n$ vernier scale divisions (VSD) coincide with $(n - 1)$ main scale divisions (MSD), the least count is $\\frac{1}{n}\\text{ MSD}$.\n\n**Reason:** The least count of a vernier calliper is defined as the difference between one main scale division and one vernier scale division.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{Least count} = 1\\text{ MSD} - 1\\text{ VSD}$. Since $n\\text{ VSD} = (n - 1)\\text{ MSD}$, $1\\text{ VSD} = \\frac{n-1}{n}\\text{ MSD}$. Hence, $\\text{LC} = 1\\text{ MSD} - \\frac{n-1}{n}\\text{ MSD} = \\frac{1}{n}\\text{ MSD}$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** Backlash error in a screw gauge can be avoided by turning the screw always in the same direction while taking a measurement.\n\n**Reason:** Backlash error is caused by looseness or wear and tear of the screw threads in the nut.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Due to wear and tear of the screw threads, there is play or looseness between the screw and the nut. Turning the screw in opposite directions causes the screw to rotate without translational movement (backlash error). It is eliminated by turning the screw in one uniform direction during observation. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** A measurement can be highly precise but not accurate.\n\n**Reason:** Precision depends on the resolution or least count of the measuring instrument, while accuracy depends on the closeness to the true value.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "If an instrument has high resolution (small least count) but possesses a significant zero error or calibration defect, repeated measurements will be very close to each other (precise) but far from the true value (inaccurate). Hence both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** If the pitch of a screw gauge is halved and the number of divisions on its circular scale is doubled, its least count becomes one-fourth of its original value.\n\n**Reason:** Least count of a screw gauge is given by $\\text{LC} = \\frac{\\text{Pitch}}{\\text{Number of circular scale divisions}}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{LC} = \\frac{p}{N}$. If $p' = p/2$ and $N' = 2N$, then $\\text{LC}' = \\frac{p/2}{2N} = \\frac{1}{4}\\frac{p}{N} = \\frac{1}{4}\\text{LC}$. The least count becomes one-fourth. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** The ratchet attached to the head of a screw gauge ensures uniform pressure on the object during measurement.\n\n**Reason:** The ratchet slips with a clicking sound when sufficient pressure is exerted, preventing overtightening and deformation of the measured object.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "The ratchet at the end of the thimble slips and makes a clicking sound when proper pressure is applied. This prevents the user from overtightening the screw, ensuring consistent readings without deforming the object or damaging the threads. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** For a spherometer, the radius of curvature of a spherical surface is calculated using $R = \\frac{l^2}{6h} + \\frac{h}{2}$.\n\n**Reason:** Here $l$ is the average distance between the outer three legs and $h$ is the sagitta or height of the central screw.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "For a spherometer, if $l$ is the mean distance between the outer three legs forming an equilateral triangle and $h$ is the elevation/depression of the central screw, geometry gives $R = \\frac{l^2}{6h} + \\frac{h}{2}$. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** Increasing the number of divisions on the circular scale of a screw gauge indefinitely increases the precision infinitely in practical situations.\n\n**Reason:** Practically, the human eye and mechanical imperfections limit how closely divisions can be resolved.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 3,
    "explanation": "Increasing the circular scale divisions indefinitely does not practically increase precision infinitely because of limits imposed by diffraction, eye resolution, thickness of graduation marks, and mechanical play in the screw threads. Thus Assertion is false, Reason is true.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** In a vernier calliper where $10\\text{ VSD} = 11\\text{ MSD}$, the vernier scale is called a retrograde vernier.\n\n**Reason:** In a retrograde vernier, the divisions on the vernier scale are slightly larger than the divisions on the main scale.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "When $n\\text{ VSD} = (n + 1)\\text{ MSD}$, $1\\text{ VSD} = \\frac{n+1}{n}\\text{ MSD} > 1\\text{ MSD}$. This type of vernier is known as a retrograde vernier, and its divisions run in the direction opposite to the main scale. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** The least count of an instrument sets the lower limit on the absolute error of a single measurement.\n\n**Reason:** An instrument cannot record any fraction of a division smaller than its least count.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Because an instrument cannot resolve any value smaller than its smallest division (least count), the uncertainty in a single direct reading is at least equal to its least count (or half the least count for interpolated scales). Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** If the zero mark of the circular scale of a screw gauge lies below the reference line when the studs are in contact, the zero error is positive.\n\n**Reason:** When the zero mark is below the reference line, the screw has already advanced before the measurement begins, recording a positive initial value.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "When the jaws/studs meet, if the circular scale zero is below the reference line, the reading registered is greater than zero, meaning positive zero error. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** Accuracy of a measurement can be improved by taking a large number of readings with an uncalibrated instrument with significant zero error.\n\n**Reason:** Random errors cancel out when the mean of a large number of readings is taken.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 3,
    "explanation": "Taking the mean of repeated readings eliminates random errors, but systematic errors (like zero error or miscalibration) remain unchanged and affect every reading identically. Thus accuracy cannot be improved without correcting the systematic error. Assertion is false, Reason is true.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** A meter scale with $1\\text{ mm}$ divisions has a least count of $0.001\\text{ m}$.\n\n**Reason:** Least count is the magnitude of the smallest graduation mark on the scale.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "On a standard meter scale, the smallest division is $1\\text{ mm} = 0.001\\text{ m}$, which is its least count. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** In an optical bench experiment, index correction must be applied to the measured distance between the lens and the pin.\n\n**Reason:** Index correction arises because the positions of the pointer tips on the bench uprights may not exactly coincide with the optical centre or needle tip.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Index error occurs when the distance measured between uprights on the optical bench scale differs from the actual distance between the optical centre of the lens and the tip of the needle. Applying index correction (Actual distance = Observed distance + Index correction) eliminates this systematic error. Both are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** A vernier calliper has $1\\text{ MSD} = 1\\text{ mm}$ and $20\\text{ VSD} = 19\\text{ MSD}$. Its least count is $0.05\\text{ mm}$.\n\n**Reason:** The least count is given by $\\text{LC} = \\frac{1\\text{ MSD}}{\\text{number of VSD}} = \\frac{1\\text{ mm}}{20} = 0.05\\text{ mm}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{LC} = 1\\text{ MSD} - 1\\text{ VSD} = 1\\text{ mm} - \\frac{19}{20}\\text{ mm} = \\frac{1}{20}\\text{ mm} = 0.05\\text{ mm}$. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** Parallax error can be avoided by looking at the scale vertically from directly above the graduation mark.\n\n**Reason:** Looking obliquely causes a shift in the position of the pointer relative to the scale due to the gap between them.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Parallax error occurs when the line of sight is inclined to the plane of the scale. Viewing perpendicularly (normally) eliminates the apparent displacement between the pointer/object and the scale marks. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** If the pitch of a micrometer screw gauge is $0.5\\text{ mm}$ and it has 50 circular divisions, its least count is $0.01\\text{ mm}$.\n\n**Reason:** Least count $= \\frac{\\text{Pitch}}{\\text{Total circular divisions}} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{Least count} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm} = 0.001\\text{ cm}$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** A travelling microscope has a higher precision than a common meter scale.\n\n**Reason:** A travelling microscope is equipped with a vernier scale attached to its main scale, giving a least count of typically $0.001\\text{ cm}$ ($0.01\\text{ mm}$).",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "A travelling microscope uses a vernier scale arrangement allowing measurements up to $0.01\\text{ mm}$ ($0.001\\text{ cm}$), whereas a meter scale can only measure down to $1\\text{ mm}$. Hence it is much more precise. Both are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** If a vernier calliper has a zero error of $+0.04\\text{ cm}$, and the observed reading is $3.46\\text{ cm}$, the corrected reading is $3.50\\text{ cm}$.\n\n**Reason:** Zero correction is equal in magnitude to zero error but opposite in sign, so Corrected reading = Observed reading - Zero error.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 3,
    "explanation": "$\\text{Corrected reading} = \\text{Observed reading} - \\text{Zero error} = 3.46 - (+0.04) = 3.42\\text{ cm}$. Adding $0.04$ is wrong. Hence Assertion is false, Reason is true.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** In a screw gauge, if the circular scale zero is 5 divisions above the reference line when closed, the zero error is negative.\n\n**Reason:** When the zero mark is above the reference line, the screw has moved past zero, meaning the initial reading is negative.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "When circular scale zero lies above the reference line, zero error is negative. To get the true reading, this negative error is subtracted (i.e. added in magnitude): $\\text{True reading} = \\text{Observed reading} - (-e) = \\text{Observed reading} + e$. Both are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** The precision of a measurement is determined by the measuring instrument, whereas accuracy also depends on experimental technique.\n\n**Reason:** Precision indicates the degree of reproducibility of measurements, while accuracy indicates how close the measurement is to the standard value.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Precision is fundamentally constrained by the instrument's least count and noise, governing repeatability. Accuracy encompasses systematic errors, proper calibration, environmental factors, and observer skill. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** When measuring the diameter of a thin wire with a screw gauge, one should take readings at several different points along its length and along perpendicular directions.\n\n**Reason:** The cross-section of a practical wire may not be perfectly uniform or circular throughout its length.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Real wires may have non-uniform diameter and non-circular cross-section (ellipticity). Taking readings at multiple positions and orientations gives a representative average diameter and reduces random errors. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** The pitch of a micrometer screw is the linear distance moved by the screw along its axis in one complete rotation of its circular head.\n\n**Reason:** The linear advance per revolution is a fixed characteristic determined by the thread pitch of the screw.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Pitch is precisely defined as the axial displacement of the screw per complete revolution ($360^\\circ$). Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "assertion-reason",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "**Assertion:** A student measures the thickness of a paper using a meter scale and records it as $0.1\\text{ mm}$. This measurement is reliable and precise.\n\n**Reason:** The least count of a standard meter scale is $1\\text{ mm}$, so it cannot reliably measure a thickness of $0.1\\text{ mm}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 3,
    "explanation": "A meter scale has a least count of $1\\text{ mm}$ and cannot resolve $0.1\\text{ mm}$. To measure the thickness of paper, one should use a screw gauge or measure a stack of 100 sheets. Assertion is false, Reason is true.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "multiple-choice",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A vernier callipers has $1\\text{ mm}$ marks on the main scale. It has 20 equal divisions on the Vernier scale which match with 16 main scale divisions. For this Vernier callipers, the least count is:",
    "options": [
      "0.2 mm",
      "0.1 mm",
      "0.05 mm",
      "0.02 mm"
    ],
    "correctOptionIndex": 0,
    "explanation": "Given $1\\text{ MSD} = 1\\text{ mm}$.\n$20\\text{ VSD} = 16\\text{ MSD} \\implies 1\\text{ VSD} = \\frac{16}{20}\\text{ MSD} = 0.8\\text{ mm}$.\nLeast count $\\text{LC} = 1\\text{ MSD} - 1\\text{ VSD} = 1\\text{ mm} - 0.8\\text{ mm} = 0.2\\text{ mm}$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "multiple-choice",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "One pitch of a screw gauge is $0.5\\text{ mm}$ and there are 50 divisions on its circular scale. When there is nothing between the two studs, the 45th division of the circular scale coincides with the reference line and the zero of the main scale is barely visible. When a wire is placed between the studs, the main scale reads $2.5\\text{ mm}$ and the 20th division coincides with the reference line. The diameter of the wire is:",
    "options": [
      "2.75 mm",
      "2.65 mm",
      "2.70 mm",
      "2.25 mm"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{Least count} = \\frac{\\text{Pitch}}{\\text{Divisions}} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm}$.\nSince the 45th division coincides with the reference line, the circular scale zero is 5 divisions above the reference line, so the zero error is negative:\n$$\\text{Zero error} = -(50 - 45) \\times 0.01\\text{ mm} = -5 \\times 0.01 = -0.05\\text{ mm}$$\nObserved reading $= \\text{MSR} + (\\text{CSR} \\times \\text{LC}) = 2.5\\text{ mm} + (20 \\times 0.01\\text{ mm}) = 2.5 + 0.20 = 2.70\\text{ mm}$.\n$$\\text{True diameter} = \\text{Observed reading} - \\text{Zero error} = 2.70 - (-0.05) = 2.75\\text{ mm}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "multiple-choice",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a vernier callipers, one main scale division is $x\\text{ cm}$ and $n$ divisions of the vernier scale coincide with $(n - 1)$ divisions of the main scale. The least count (in cm) of the callipers is:",
    "options": [
      "$\\frac{x}{n}$",
      "$\\frac{x}{n - 1}$",
      "$\\frac{x}{n + 1}$",
      "$\\frac{(n - 1)x}{n}$"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{LC} = 1\\text{ MSD} - 1\\text{ VSD}$.\nGiven $n\\text{ VSD} = (n - 1)\\text{ MSD} \\implies 1\\text{ VSD} = \\frac{n-1}{n}\\text{ MSD}$.\n$$\\text{LC} = \\text{MSD} \\left(1 - \\frac{n-1}{n}\\right) = \\frac{1}{n}\\text{ MSD} = \\frac{x}{n}\\text{ cm}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "multiple-choice",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A screw gauge gives the following reading when used to measure the diameter of a wire:\nMain scale reading : $0\\text{ mm}$\nCircular scale reading : 52 divisions\nGiven that $1\\text{ mm}$ on main scale corresponds to 100 divisions on the circular scale. The diameter of the wire from the above data is:",
    "options": [
      "0.52 mm",
      "0.052 mm",
      "0.026 mm",
      "0.0052 mm"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{Pitch} = 1\\text{ mm}$, number of divisions $= 100$.\n$$\\text{Least count} = \\frac{1\\text{ mm}}{100} = 0.01\\text{ mm}$$\n$$\\text{Diameter} = \\text{MSR} + (\\text{CSR} \\times \\text{LC}) = 0\\text{ mm} + (52 \\times 0.01\\text{ mm}) = 0.52\\text{ mm}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "multiple-choice",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a travelling microscope, the main scale has 1 mm divisions and 50 vernier scale divisions coincide with 49 main scale divisions. The least count of the microscope is:",
    "options": [
      "0.02 mm",
      "0.01 mm",
      "0.05 mm",
      "0.002 mm"
    ],
    "correctOptionIndex": 0,
    "explanation": "$1\\text{ MSD} = 1\\text{ mm}$.\n$50\\text{ VSD} = 49\\text{ MSD} \\implies 1\\text{ VSD} = \\frac{49}{50}\\text{ MSD} = 0.98\\text{ mm}$.\n$$\\text{Least count} = 1\\text{ MSD} - 1\\text{ VSD} = 1\\text{ mm} - 0.98\\text{ mm} = 0.02\\text{ mm}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "multiple-choice",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "Using a screw gauge with pitch $0.5\\text{ mm}$ and 50 circular divisions, a student measures the thickness of a glass slab. If the main scale reading is $6.5\\text{ mm}$ and the 38th division of circular scale coincides with the reference line, and the screw gauge has a positive zero error of $+0.03\\text{ mm}$, the corrected thickness is:",
    "options": [
      "6.85 mm",
      "6.91 mm",
      "6.88 mm",
      "6.82 mm"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\text{LC} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm}$.\nObserved reading $= 6.5\\text{ mm} + (38 \\times 0.01\\text{ mm}) = 6.5 + 0.38 = 6.88\\text{ mm}$.\nCorrected reading $= \\text{Observed reading} - \\text{Zero error} = 6.88 - 0.03 = 6.85\\text{ mm}$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "multiple-choice",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "Which of the following measurements is most precise?",
    "options": [
      "5.000 mm",
      "5.00 mm",
      "5.0 mm",
      "5 mm"
    ],
    "correctOptionIndex": 0,
    "explanation": "Precision is directly related to the least count and the number of decimal places in the measurement. The measurement $5.000\\text{ mm}$ has a least count of $0.001\\text{ mm}$, which is the smallest least count among the options, making it the most precise.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a vernier callipers, 1 main scale division is $1\\text{ mm}$ and 10 divisions of vernier scale coincide with 9 divisions of main scale. What is the least count in mm multiplied by 100? (e.g. if least count is $0.1\\text{ mm}$, answer 10).",
    "correctAnswer": "10",
    "explanation": "$\\text{LC} = 1\\text{ MSD} - 1\\text{ VSD} = 1\\text{ mm} - \\frac{9}{10}(1\\text{ mm}) = 0.1\\text{ mm}$.\nMultiplying by 100 gives $0.1 \\times 100 = 10$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A screw gauge has a pitch of $1.0\\text{ mm}$ and 100 divisions on its circular scale. The least count in microns ($\\mu\\text{m}$) is:",
    "correctAnswer": "10",
    "explanation": "$\\text{Least count} = \\frac{\\text{Pitch}}{\\text{Number of divisions}} = \\frac{1.0\\text{ mm}}{100} = 0.01\\text{ mm} = 10\\,\\mu\\text{m}$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A student finds that for a vernier callipers, $n$ vernier scale divisions coincide with $(n - 2)$ main scale divisions. If $1\\text{ MSD} = 1\\text{ mm}$ and the least count is $0.04\\text{ mm}$, find the value of $n$.",
    "correctAnswer": "50",
    "explanation": "$\\text{LC} = 1\\text{ MSD} - 1\\text{ VSD} = 1\\text{ mm} - \\frac{n-2}{n}(1\\text{ mm}) = \\frac{2}{n}\\text{ mm}$.\nGiven $\\text{LC} = 0.04\\text{ mm} \\implies \\frac{2}{n} = 0.04 \\implies n = \\frac{2}{0.04} = 50$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a screw gauge, 5 complete rotations of the circular scale advance the screw by $2.5\\text{ mm}$. The circular scale has 50 divisions. If the least count is $x\\text{ mm}$, find $1000 \\times x$.",
    "correctAnswer": "10",
    "explanation": "$\\text{Pitch} = \\frac{2.5\\text{ mm}}{5} = 0.5\\text{ mm}$.\n$$\\text{Least count} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm}$$\nHere $x = 0.01$, so $1000 \\times x = 1000 \\times 0.01 = 10$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "When the jaws of a vernier callipers are closed, the zero of the vernier scale lies to the right of the zero of the main scale, and the 4th vernier division coincides with a main scale mark. If $1\\text{ MSD} = 1\\text{ mm}$ and $10\\text{ VSD} = 9\\text{ MSD}$, the zero error in mm is $+e$. Find the value of $10 \\times e$.",
    "correctAnswer": "4",
    "explanation": "$\\text{LC} = 1 - \\frac{9}{10} = 0.1\\text{ mm}$.\nSince the vernier zero is to the right, zero error is positive:\n$$e = +4 \\times \\text{LC} = +4 \\times 0.1 = +0.4\\text{ mm}$$\n$10 \\times e = 10 \\times 0.4 = 4$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "When the jaws of a vernier calliper are closed, the vernier zero lies to the left of the main scale zero, and the 7th division of the 10-division vernier scale coincides with a main scale mark. If least count is $0.1\\text{ mm}$, the magnitude of negative zero error in mm is $e$. Find $10 \\times e$.",
    "correctAnswer": "3",
    "explanation": "Negative zero error $= -(10 - 7) \\times \\text{LC} = -3 \\times 0.1\\text{ mm} = -0.3\\text{ mm}$.\nThe magnitude $e = 0.3\\text{ mm}$, so $10 \\times e = 3$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A screw gauge with a pitch of $0.5\\text{ mm}$ and 100 divisions on circular scale is used to measure the thickness of an aluminium sheet. The main scale reading is $1.5\\text{ mm}$ and 44th division coincides with reference line. If there is no zero error, what is the thickness of the sheet in mm multiplied by 1000? (rounded to integer)",
    "correctAnswer": "1720",
    "explanation": "$\\text{LC} = \\frac{0.5\\text{ mm}}{100} = 0.005\\text{ mm}$.\n$$\\text{Thickness} = \\text{MSR} + (\\text{CSR} \\times \\text{LC}) = 1.5\\text{ mm} + (44 \\times 0.005\\text{ mm}) = 1.5 + 0.22 = 1.72\\text{ mm}$$\n$1000 \\times 1.72 = 1720$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a spherometer, the pitch is $1\\text{ mm}$ and the circular scale has 100 divisions. The distance between each pair of the three outer legs is $l = 6\\text{ cm}$. When placed on a convex spherical surface, the central screw is raised by 2 main scale divisions and 40 circular scale divisions. What is the value of sagitta $h$ in mm multiplied by 10? (Enter integer)",
    "correctAnswer": "24",
    "explanation": "$\\text{Least count} = \\frac{1\\text{ mm}}{100} = 0.01\\text{ mm}$.\n$$h = 2\\text{ mm} + (40 \\times 0.01\\text{ mm}) = 2.4\\text{ mm}$$\n$10 \\times h = 24$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A micrometer has a least count of $0.01\\text{ mm}$. A student measures the diameter of a spherical ball and finds the main scale reading is $5\\text{ mm}$ and circular scale reading is 25 divisions. If the zero error is $+0.02\\text{ mm}$, the true diameter in mm is $d$. Find $100 \\times d$.",
    "correctAnswer": "523",
    "explanation": "Observed reading $= 5\\text{ mm} + (25 \\times 0.01\\text{ mm}) = 5.25\\text{ mm}$.\nTrue diameter $= 5.25 - 0.02 = 5.23\\text{ mm}$.\n$100 \\times d = 523$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "The circular head of a screw gauge has 50 divisions. When it is given 4 complete rotations, the screw moves through $2\\text{ mm}$. If the least count is $x\\text{ mm}$, find the value of $100 \\times x$.",
    "correctAnswer": "1",
    "explanation": "$\\text{Pitch} = \\frac{2\\text{ mm}}{4} = 0.5\\text{ mm}$.\n$$\\text{Least count} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm}$$\n$x = 0.01$, so $100 \\times x = 1$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A vernier scale has 25 divisions which correspond to 24 divisions of the main scale. If $1\\text{ MSD} = 0.5\\text{ mm}$, calculate the least count of the instrument in mm multiplied by 1000.",
    "correctAnswer": "20",
    "explanation": "$\\text{LC} = 1\\text{ MSD} - 1\\text{ VSD} = 0.5\\text{ mm} - \\frac{24}{25}(0.5\\text{ mm}) = \\frac{0.5\\text{ mm}}{25} = 0.02\\text{ mm}$.\n$1000 \\times 0.02 = 20$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A screw gauge with least count $0.01\\text{ mm}$ is used to measure the thickness of a wire. The main scale reading is $1\\text{ mm}$ and circular scale reading is 35. The zero error is $-0.03\\text{ mm}$. The correct diameter of the wire in mm multiplied by 100 is:",
    "correctAnswer": "138",
    "explanation": "Observed reading $= 1 + (35 \\times 0.01) = 1.35\\text{ mm}$.\nCorrect reading $= \\text{Observed} - \\text{Zero error} = 1.35 - (-0.03) = 1.38\\text{ mm}$.\n$100 \\times 1.38 = 138$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a vernier callipers, 1 main scale division is $0.5\\text{ mm}$ and 20 vernier divisions coincide with 19 main scale divisions. Find the least count in mm multiplied by 1000.",
    "correctAnswer": "25",
    "explanation": "$\\text{LC} = \\frac{1\\text{ MSD}}{20} = \\frac{0.5\\text{ mm}}{20} = 0.025\\text{ mm}$.\n$1000 \\times 0.025 = 25$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "The pitch of a screw gauge is $1\\text{ mm}$ and its circular scale has 200 divisions. The least count of the screw gauge in mm is $x$. Find $1000 \\times x$.",
    "correctAnswer": "5",
    "explanation": "$\\text{LC} = \\frac{1\\text{ mm}}{200} = 0.005\\text{ mm}$.\n$1000 \\times x = 1000 \\times 0.005 = 5$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In an experiment with a vernier calliper, the main scale reads $2.8\\text{ cm}$ and the 6th vernier division coincides with a main scale division. If $1\\text{ MSD} = 1\\text{ mm}$ and $10\\text{ VSD} = 9\\text{ MSD}$, calculate the measured length in mm.",
    "correctAnswer": "28.6",
    "explanation": "Main scale reading $= 2.8\\text{ cm} = 28\\text{ mm}$.\n$\\text{LC} = 0.1\\text{ mm}$.\nVernier reading $= 6 \\times 0.1 = 0.6\\text{ mm}$.\nTotal reading $= 28 + 0.6 = 28.6\\text{ mm}$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A student measures the diameter of a small steel ball using a screw gauge of least count $0.001\\text{ cm}$. The main scale reading is $5\\text{ mm}$ and zero of circular scale division coincides with 25 divisions above the reference level. If the screw gauge has a zero error of $-0.004\\text{ cm}$, the correct diameter in mm multiplied by 100 is:",
    "correctAnswer": "529",
    "explanation": "$\\text{LC} = 0.001\\text{ cm} = 0.01\\text{ mm}$.\n$\\text{MSR} = 5\\text{ mm}$.\n$\\text{CSR} = 25 \\times 0.01 = 0.25\\text{ mm}$.\nObserved reading $= 5.25\\text{ mm}$.\nZero error $= -0.004\\text{ cm} = -0.04\\text{ mm}$.\nCorrect reading $= 5.25 - (-0.04) = 5.29\\text{ mm}$.\n$100 \\times 5.29 = 529$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "To measure the diameter of a cylinder with vernier callipers, 50 vernier scale divisions are found to be equal to 49 main scale divisions. If each main scale division is $0.5\\text{ mm}$, find the least count in microns ($\\mu\\text{m}$).",
    "correctAnswer": "10",
    "explanation": "$\\text{LC} = \\frac{1\\text{ MSD}}{50} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm} = 10\\,\\mu\\text{m}$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a micrometer screw gauge, the circular scale rotates through 2 complete turns to advance by $1\\text{ mm}$. If there are 50 divisions on circular scale, what is the least count in mm multiplied by 1000?",
    "correctAnswer": "10",
    "explanation": "$\\text{Pitch} = \\frac{1\\text{ mm}}{2} = 0.5\\text{ mm}$.\n$$\\text{LC} = \\frac{0.5\\text{ mm}}{50} = 0.01\\text{ mm}$$\n$1000 \\times 0.01 = 10$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "A screw gauge has 100 divisions on its circular scale and moves $1\\text{ mm}$ along the axis in 2 rotations. When used to measure the thickness of a coin, the main scale reads $2\\text{ mm}$ and 70th circular division coincides with the reference line. If the zero error is $+0.05\\text{ mm}$, find the actual thickness of the coin in mm multiplied by 100.",
    "correctAnswer": "230",
    "explanation": "$\\text{Pitch} = 1\\text{ mm} / 2 = 0.5\\text{ mm}$.\n$\\text{LC} = 0.5\\text{ mm} / 100 = 0.005\\text{ mm}$.\nObserved reading $= 2\\text{ mm} + (70 \\times 0.005\\text{ mm}) = 2 + 0.35 = 2.35\\text{ mm}$.\nActual thickness $= 2.35 - 0.05 = 2.30\\text{ mm}$.\n$100 \\times 2.30 = 230$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "numerical",
    "subject": "Physics",
    "chapter": "Physics and Measurement",
    "subTopic": "Least count and precision",
    "question": "In a vernier calliper, 1 main scale division is $1\\text{ mm}$. A student finds that 16 vernier divisions coincide with 15 main scale divisions. Find the least count of the vernier calliper in mm multiplied by 16.",
    "correctAnswer": "1",
    "explanation": "$\\text{LC} = 1\\text{ MSD} - 1\\text{ VSD} = 1\\text{ mm} - \\frac{15}{16}\\text{ mm} = \\frac{1}{16}\\text{ mm}$.\nMultiplying by 16 gives $\\frac{1}{16} \\times 16 = 1$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  }
];
