module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A particle executing uniform circular motion has non-zero acceleration despite moving at constant speed.\nReason (R): The direction of the velocity vector changes continuously at every instant along the circular trajectory.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Acceleration is the time rate of change of the velocity vector: $\\vec{a} = \\frac{d\\vec{v}}{dt}$. Even though speed $|\\vec{v}|$ is constant, the changing direction of $\\vec{v}$ gives rise to a non-zero centripetal acceleration $a_c = \\frac{v^2}{R}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In uniform circular motion, the acceleration vector is always directed towards the center of the circular orbit.\nReason (R): The tangential component of acceleration is zero because the speed is constant, leaving only the normal (centripetal) acceleration directed radially inward.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{a} = a_t\\hat{t} + a_n\\hat{n}$. Since speed $v$ is constant, $a_t = \\frac{dv}{dt} = 0$, so $\\vec{a} = \\frac{v^2}{R}\\hat{n}$, which points towards the center. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The kinetic energy of a particle performing uniform circular motion remains constant in time.\nReason (R): The centripetal force is always perpendicular to the instantaneous displacement vector, doing zero work on the particle.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Power is $P = \\vec{F} \\cdot \\vec{v} = 0$ because $\\vec{F} \\perp \\vec{v}$. By the work-energy theorem, $\\frac{dK}{dt} = 0$, so kinetic energy remains strictly constant. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The average velocity of a particle undergoing uniform circular motion over one complete revolution is zero.\nReason (R): Over one full cycle, the particle returns to its starting point, making the net displacement vector $\\Delta\\vec{r} = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Average velocity is $\\vec{v}_{avg} = \\frac{\\Delta\\vec{r}}{\\Delta t}$. For a complete period $T$, $\\Delta\\vec{r} = 0$, so $\\vec{v}_{avg} = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Over a half revolution in uniform circular motion of radius $R$ and speed $v$, the magnitude of the change in velocity is $2v$.\nReason (R): At diametrically opposite points, the velocity vectors are equal in magnitude but opposite in direction: $\\vec{v}_f = -\\vec{v}_i$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$|\\Delta\\vec{v}| = |\\vec{v}_f - \\vec{v}_i| = |(-v\\hat{j}) - (v\\hat{j})| = 2v$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The magnitude of average acceleration over a half revolution in uniform circular motion of speed $v$ and radius $R$ is $\\frac{2v^2}{\\pi R}$.\nReason (R): The time taken for a half revolution is $\\frac{\\pi R}{v}$, and the magnitude of the velocity change is $2v$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$a_{avg} = \\frac{|\\Delta\\vec{v}|}{\\Delta t} = \\frac{2v}{\\pi R / v} = \\frac{2v^2}{\\pi R}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In circular motion, the relation between linear velocity and angular velocity is given by $\\vec{v} = \\vec{\\omega} \\times \\vec{r}$.\nReason (R): The vector cross product ensures that $\\vec{v}$ is perpendicular to both the axis of rotation $\\vec{\\omega}$ and the position vector $\\vec{r}$, with magnitude $v = \\omega r\\sin 90^\\circ = \\omega r$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By definition of rotational kinematics, $\\vec{v} = \\vec{\\omega} \\times \\vec{r}$, which yields both the correct direction (tangent to the circle) and magnitude $v = \\omega r$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The centripetal acceleration of a particle in uniform circular motion can be written as $\\vec{a} = -\\omega^2\\vec{r}$, where $\\vec{r}$ is the radius vector from the center.\nReason (R): The acceleration vector is collinear with and opposite in direction to the radius vector pointing outward from the center.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{a} = -\\frac{v^2}{R}\\hat{r} = -\\omega^2 R \\hat{r} = -\\omega^2\\vec{r}$. The negative sign signifies inward central direction. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A particle moving in a circle with constant angular velocity has zero angular acceleration.\nReason (R): Angular acceleration is defined as $\\alpha = \\frac{d\\omega}{dt}$, which is zero whenever $\\omega = \\text{constant}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\omega$ is constant in magnitude and direction along the axis of rotation, $\\alpha = \\frac{d\\omega}{dt} = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If the radius of a circular path is doubled while maintaining constant speed $v$, the centripetal acceleration is halved.\nReason (R): Centripetal acceleration is inversely proportional to the radius of the path when speed is constant: $a_c = \\frac{v^2}{R}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "From $a_c = \\frac{v^2}{R}$, for constant $v$, $a_c \\propto \\frac{1}{R}$. Doubling $R$ halves $a_c$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If the radius of a circular path is doubled while maintaining constant angular velocity $\\omega$, the centripetal acceleration is doubled.\nReason (R): Centripetal acceleration is directly proportional to radius when angular velocity is held constant: $a_c = \\omega^2 R$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "From $a_c = \\omega^2 R$, for constant $\\omega$, $a_c \\propto R$. Doubling $R$ doubles $a_c$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In non-uniform circular motion, the total acceleration vector makes an angle $\\phi$ with the velocity vector where $\\tan\\phi = \\frac{a_c}{a_t}$.\nReason (R): The tangential component $a_t$ is parallel to the velocity vector and the centripetal component $a_c$ is perpendicular to the velocity vector.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{a}_t \\parallel \\vec{v}$ and $\\vec{a}_c \\perp \\vec{v}$, the vector triangle gives $\\tan\\phi = \\frac{a_c}{a_t} = \\frac{v^2 / R}{dv/dt}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A car moving at constant speed along a circular horizontal track has zero net tangential acceleration.\nReason (R): Tangential acceleration is the rate of change of speed: $a_t = \\frac{dv}{dt}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because speed is constant, $\\frac{dv}{dt} = 0$, hence $a_t = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The average acceleration in uniform circular motion over a quarter of a revolution has magnitude $\\frac{2\\sqrt{2}v^2}{\\pi R}$.\nReason (R): The change in velocity vector over a quarter revolution has magnitude $|\\Delta\\vec{v}| = \\sqrt{2}v$, and the time taken is $\\Delta t = \\frac{\\pi R}{2v}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$a_{avg} = \\frac{|\\Delta\\vec{v}|}{\\Delta t} = \\frac{\\sqrt{2}v}{\\pi R / (2v)} = \\frac{2\\sqrt{2}v^2}{\\pi R}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The acceleration of a particle in uniform circular motion is a constant vector.\nReason (R): In uniform circular motion, the magnitude of the centripetal acceleration is constant ($a_c = \\frac{v^2}{R}$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: while its magnitude is constant, the direction of centripetal acceleration rotates continuously with the particle, so $\\vec{a}$ is NOT a constant vector. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Uniform circular motion is an accelerated motion.\nReason (R): Any motion where the direction of the velocity changes is necessarily accelerated.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Velocity is a vector quantity; a change in its direction requires a non-zero time derivative $\\frac{d\\vec{v}}{dt} \\ne 0$, meaning accelerated motion. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A particle moving in a circle of radius $R$ starting from rest with constant angular acceleration $\\alpha$ has equal tangential and normal accelerations at time $t = \\frac{1}{\\sqrt{\\alpha}}$.\nReason (R): Tangential acceleration is $a_t = \\alpha R$ and centripetal acceleration is $a_c = \\omega^2 R = (\\alpha t)^2 R$, which become equal when $\\alpha = \\alpha^2 t^2 \\implies t = \\frac{1}{\\sqrt{\\alpha}}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Setting $a_t = a_c \\implies \\alpha R = (\\alpha t)^2 R \\implies \\alpha = \\alpha^2 t^2 \\implies t^2 = \\frac{1}{\\alpha} \\implies t = \\frac{1}{\\sqrt{\\alpha}}$. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The angular displacement $\\theta$ of a body rotating with constant angular acceleration $\\alpha$ satisfies $\\omega^2 = \\omega_0^2 + 2\\alpha\\theta$.\nReason (R): This equation is the rotational analogue of the linear kinematic relation $v^2 = u^2 + 2as$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Using $\\alpha = \\omega\\frac{d\\omega}{d\\theta}$, integrating $\\int_{\\omega_0}^\\omega \\omega\\, d\\omega = \\alpha \\int_0^\\theta d\\theta$ gives $\\frac{\\omega^2 - \\omega_0^2}{2} = \\alpha\\theta \\implies \\omega^2 = \\omega_0^2 + 2\\alpha\\theta$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The instantaneous velocity vector of a particle in circular motion is always along the tangent to the circle.\nReason (R): The displacement vector $d\\vec{r}$ over an infinitesimal time interval $dt$ lies along the tangent to the curved path.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\vec{v} = \\lim_{\\Delta t \\to 0} \\frac{\\Delta\\vec{r}}{\\Delta t} = \\frac{d\\vec{r}}{dt}$, which geometrically defines the tangent to the trajectory at that point. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In uniform circular motion, the angle between the velocity vector and the acceleration vector is always $90^\\circ$.\nReason (R): The velocity vector is strictly tangential and the acceleration vector is strictly radial (centripetal), which are mutually orthogonal.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Tangential and radial directions are perpendicular everywhere on a circle, so $\\vec{v} \\cdot \\vec{a} = 0$, meaning the angle is constantly $90^\\circ$. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A body moving along a circular path with increasing speed has an acceleration vector pointing ahead of the normal towards the inside of the curve.\nReason (R): The net acceleration is the resultant of a forward tangential component $\\vec{a}_t$ and an inward normal component $\\vec{a}_n$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because speed is increasing, $a_t > 0$ along $\\vec{v}$. The resultant $\\vec{a} = \\vec{a}_t + \\vec{a}_n$ tilts forward into the interior of the curve. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): In circular motion, the angular velocity vector $\\vec{\\omega}$ points along the plane of the circle.\nReason (R): Angular velocity is an axial vector whose direction is perpendicular to the plane of rotation, given by the right-hand thumb rule.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: $\\vec{\\omega}$ points along the axis of rotation perpendicular to the plane of the circle, not in the plane. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The number of revolutions completed by a wheel in slowing down from angular speed $\\omega_0$ to rest with uniform angular retardation $\\alpha$ is $N = \\frac{\\omega_0^2}{4\\pi\\alpha}$.\nReason (R): From $\\omega^2 = \\omega_0^2 - 2\\alpha\\theta$, setting $\\omega = 0$ gives $\\theta = \\frac{\\omega_0^2}{2\\alpha}$, and $N = \\frac{\\theta}{2\\pi}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\theta = \\frac{\\omega_0^2}{2\\alpha}$. Since each revolution corresponds to $2\\pi\\text{ radians}$, $N = \\frac{\\theta}{2\\pi} = \\frac{\\omega_0^2}{4\\pi\\alpha}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The time period of uniform circular motion is independent of the radius of the circle if the angular speed $\\omega$ is constant.\nReason (R): The period is defined as $T = \\frac{2\\pi}{\\omega}$, which depends solely on the angular speed $\\omega$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $T = \\frac{2\\pi}{\\omega}$, if $\\omega$ is fixed, $T$ is invariant regardless of radius $R$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A particle in circular motion can have zero centripetal acceleration while having non-zero tangential acceleration.\nReason (R): At the exact instant a particle starts from rest along a circular path, its speed is momentarily zero ($v = 0$), so $a_c = \\frac{v^2}{R} = 0$, while $a_t = \\alpha R \\ne 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "At $t = 0$ from rest, $v = 0 \\implies a_c = 0$, but angular acceleration $\\alpha$ produces immediate tangential acceleration $a_t = \\alpha R \\ne 0$. (R) explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The work done by the centripetal force on a particle in uniform circular motion over any displacement is non-zero.\nReason (R): The centripetal force is perpendicular to the instantaneous velocity vector at all times, satisfying $\\vec{F}_c \\cdot d\\vec{r} = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: because $\\vec{F}_c \\perp d\\vec{r}$, $dW = \\vec{F}_c \\cdot d\\vec{r} = 0$, so work done is strictly zero. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in a circle of radius $R = 5\\text{ m}$ with a constant speed $v = 10\\text{ m/s}$. The magnitude of its centripetal acceleration is:",
    "options": [
      "$10\\text{ m/s}^2$",
      "$20\\text{ m/s}^2$",
      "$40\\text{ m/s}^2$",
      "$50\\text{ m/s}^2$"
    ],
    "correctAnswer": 1,
    "explanation": "Centripetal acceleration is $a_c = \\frac{v^2}{R} = \\frac{10^2}{5} = \\frac{100}{5} = 20\\text{ m/s}^2$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A body executes uniform circular motion with time period $T$ and radius $R$. The magnitude of average acceleration during the time interval $\\frac{T}{2}$ is:",
    "options": [
      "$\\frac{2v^2}{\\pi R}$",
      "$\\frac{4v^2}{\\pi R}$",
      "Zero",
      "$\\frac{v^2}{R}$"
    ],
    "correctAnswer": 0,
    "explanation": "In time $t = T/2$, the particle traverses half a circle. Change in velocity is $\\Delta v = v - (-v) = 2v$. The time taken is $\\Delta t = \\frac{\\pi R}{v}$. Hence $a_{avg} = \\frac{2v}{\\pi R / v} = \\frac{2v^2}{\\pi R}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A wheel rotates with a constant angular acceleration of $\\alpha = 4\\text{ rad/s}^2$. If it starts from rest, the number of revolutions made by the wheel in the first $10\\text{ seconds}$ is approximately:",
    "options": [
      "$32$",
      "$64$",
      "$16$",
      "$200$"
    ],
    "correctAnswer": 0,
    "explanation": "$\\theta = \\frac{1}{2}\\alpha t^2 = \\frac{1}{2}(4)(10^2) = 200\\text{ radians}$. Number of revolutions is $N = \\frac{\\theta}{2\\pi} = \\frac{200}{2 \\times 3.1416} \\approx 31.83 \\approx 32\\text{ rev}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle starts from rest and moves in a circle of radius $R = 2\\text{ m}$ with constant tangential acceleration $a_t = 3\\text{ m/s}^2$. At what time $t$ will the magnitude of the centripetal acceleration equal the tangential acceleration?",
    "options": [
      "$\\sqrt{2/3}\\text{ s}$",
      "$\\sqrt{3/2}\\text{ s}$",
      "$2/3\\text{ s}$",
      "$1\\text{ s}$"
    ],
    "correctAnswer": 0,
    "explanation": "Speed at time $t$ is $v = a_t t = 3t$. Centripetal acceleration is $a_c = \\frac{v^2}{R} = \\frac{(3t)^2}{2} = \\frac{9t^2}{2}$. For $a_c = a_t$: $\\frac{9t^2}{2} = 3 \\implies 9t^2 = 6 \\implies t^2 = \\frac{2}{3} \\implies t = \\sqrt{\\frac{2}{3}}\\text{ s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "If the angular speed of a particle performing circular motion is $\\omega = 10\\text{ rad/s}$ and radius is $0.5\\text{ m}$, the linear speed of the particle is:",
    "options": [
      "$5\\text{ m/s}$",
      "$10\\text{ m/s}$",
      "$20\\text{ m/s}$",
      "$2.5\\text{ m/s}$"
    ],
    "correctAnswer": 0,
    "explanation": "$v = \\omega R = 10 \\times 0.5 = 5\\text{ m/s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle is moving along a circular path of radius $R$ with variable speed $v(t) = c t$. What is the angle between the net acceleration vector and the velocity vector at time $t$?",
    "options": [
      "$\\tan^{-1}\\left(\\frac{c t^2}{R}\\right)$",
      "$\\tan^{-1}\\left(\\frac{c^2 t^2}{R}\\right)$",
      "$\\tan^{-1}\\left(\\frac{R}{c t^2}\\right)$",
      "$\\tan^{-1}\\left(\\frac{c t}{R}\\right)$"
    ],
    "correctAnswer": 0,
    "explanation": "Tangential acceleration is $a_t = \\frac{dv}{dt} = c$. Centripetal acceleration is $a_c = \\frac{v^2}{R} = \\frac{(ct)^2}{R} = \\frac{c^2 t^2}{R}$. The angle $\\phi$ with velocity is $\\tan\\phi = \\frac{a_c}{a_t} = \\frac{c^2 t^2 / R}{c} = \\frac{ct^2}{R} \\implies \\phi = \\tan^{-1}\\left(\\frac{ct^2}{R}\\right)$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Two particles $A$ and $B$ are moving in concentric circles of radii $r_A$ and $r_B$ such that they have the same time period $T$. The ratio of their centripetal accelerations $\\frac{a_A}{a_B}$ is:",
    "options": [
      "$\\frac{r_A}{r_B}$",
      "$\\frac{r_B}{r_A}$",
      "$\\frac{r_A^2}{r_B^2}$",
      "$1$"
    ],
    "correctAnswer": 0,
    "explanation": "Since periods are equal, their angular frequencies are identical: $\\omega_A = \\omega_B = \\frac{2\\pi}{T}$. Centripetal acceleration is $a_c = \\omega^2 r$. Therefore $\\frac{a_A}{a_B} = \\frac{\\omega^2 r_A}{\\omega^2 r_B} = \\frac{r_A}{r_B}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in a circle of radius $R = 2\\text{ m}$ with a constant speed $v = 10\\text{ m/s}$. Find its centripetal acceleration $a_c$ (in $\\text{m/s}^2$).",
    "options": [],
    "correctAnswer": 50,
    "numericalAnswer": 50,
    "explanation": "$a_c = \\frac{v^2}{R} = \\frac{(10)^2}{2} = \\frac{100}{2} = 50\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in a circle of radius $R = 4\\text{ m}$ with a constant speed $v = 20\\text{ m/s}$. Find its centripetal acceleration $a_c$ (in $\\text{m/s}^2$).",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$a_c = \\frac{v^2}{R} = \\frac{(20)^2}{4} = \\frac{400}{4} = 100\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in a circle of radius $R = 6\\text{ m}$ with a constant speed $v = 30\\text{ m/s}$. Find its centripetal acceleration $a_c$ (in $\\text{m/s}^2$).",
    "options": [],
    "correctAnswer": 150,
    "numericalAnswer": 150,
    "explanation": "$a_c = \\frac{v^2}{R} = \\frac{(30)^2}{6} = \\frac{900}{6} = 150\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in a circle of radius $R = 8\\text{ m}$ with a constant speed $v = 40\\text{ m/s}$. Find its centripetal acceleration $a_c$ (in $\\text{m/s}^2$).",
    "options": [],
    "correctAnswer": 200,
    "numericalAnswer": 200,
    "explanation": "$a_c = \\frac{v^2}{R} = \\frac{(40)^2}{8} = \\frac{1600}{8} = 200\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle moves in a circle of radius $R = 10\\text{ m}$ with a constant speed $v = 50\\text{ m/s}$. Find its centripetal acceleration $a_c$ (in $\\text{m/s}^2$).",
    "options": [],
    "correctAnswer": 250,
    "numericalAnswer": 250,
    "explanation": "$a_c = \\frac{v^2}{R} = \\frac{(50)^2}{10} = \\frac{2500}{10} = 250\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A disc of radius $R = 5\\text{ m}$ rotates with a constant angular velocity of $\\omega = 4\\text{ rad/s}$. Determine the linear speed $v$ (in $\\text{m/s}$) of a point on the rim of the disc.",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$v = \\omega R = 4 \\times 5 = 20\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A disc of radius $R = 5\\text{ m}$ rotates with a constant angular velocity of $\\omega = 8\\text{ rad/s}$. Determine the linear speed $v$ (in $\\text{m/s}$) of a point on the rim of the disc.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "$v = \\omega R = 8 \\times 5 = 40\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A disc of radius $R = 5\\text{ m}$ rotates with a constant angular velocity of $\\omega = 12\\text{ rad/s}$. Determine the linear speed $v$ (in $\\text{m/s}$) of a point on the rim of the disc.",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$v = \\omega R = 12 \\times 5 = 60\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A disc of radius $R = 5\\text{ m}$ rotates with a constant angular velocity of $\\omega = 16\\text{ rad/s}$. Determine the linear speed $v$ (in $\\text{m/s}$) of a point on the rim of the disc.",
    "options": [],
    "correctAnswer": 80,
    "numericalAnswer": 80,
    "explanation": "$v = \\omega R = 16 \\times 5 = 80\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A disc of radius $R = 5\\text{ m}$ rotates with a constant angular velocity of $\\omega = 20\\text{ rad/s}$. Determine the linear speed $v$ (in $\\text{m/s}$) of a point on the rim of the disc.",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$v = \\omega R = 20 \\times 5 = 100\\text{ m/s}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A flywheel accelerates uniformly from an angular speed of $\\omega_0 = 10\\text{ rad/s}$ to $\\omega = 30\\text{ rad/s}$ in a time of $t = 5\\text{ s}$. Find its angular acceleration $\\alpha$ (in $\\text{rad/s}^2$).",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$\\alpha = \\frac{\\omega - \\omega_0}{t} = \\frac{30 - 10}{5} = 4\\text{ rad/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A flywheel accelerates uniformly from an angular speed of $\\omega_0 = 20\\text{ rad/s}$ to $\\omega = 60\\text{ rad/s}$ in a time of $t = 5\\text{ s}$. Find its angular acceleration $\\alpha$ (in $\\text{rad/s}^2$).",
    "options": [],
    "correctAnswer": 8,
    "numericalAnswer": 8,
    "explanation": "$\\alpha = \\frac{\\omega - \\omega_0}{t} = \\frac{60 - 20}{5} = 8\\text{ rad/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A flywheel accelerates uniformly from an angular speed of $\\omega_0 = 30\\text{ rad/s}$ to $\\omega = 90\\text{ rad/s}$ in a time of $t = 5\\text{ s}$. Find its angular acceleration $\\alpha$ (in $\\text{rad/s}^2$).",
    "options": [],
    "correctAnswer": 12,
    "numericalAnswer": 12,
    "explanation": "$\\alpha = \\frac{\\omega - \\omega_0}{t} = \\frac{90 - 30}{5} = 12\\text{ rad/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A flywheel accelerates uniformly from an angular speed of $\\omega_0 = 40\\text{ rad/s}$ to $\\omega = 120\\text{ rad/s}$ in a time of $t = 5\\text{ s}$. Find its angular acceleration $\\alpha$ (in $\\text{rad/s}^2$).",
    "options": [],
    "correctAnswer": 16,
    "numericalAnswer": 16,
    "explanation": "$\\alpha = \\frac{\\omega - \\omega_0}{t} = \\frac{120 - 40}{5} = 16\\text{ rad/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A flywheel accelerates uniformly from an angular speed of $\\omega_0 = 50\\text{ rad/s}$ to $\\omega = 150\\text{ rad/s}$ in a time of $t = 5\\text{ s}$. Find its angular acceleration $\\alpha$ (in $\\text{rad/s}^2$).",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$\\alpha = \\frac{\\omega - \\omega_0}{t} = \\frac{150 - 50}{5} = 20\\text{ rad/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A circular cylinder of radius $R = 4\\text{ m}$ has an angular acceleration of $\\alpha = 3\\text{ rad/s}^2$. Calculate the tangential acceleration $a_t$ (in $\\text{m/s}^2$) of a point on its outer surface.",
    "options": [],
    "correctAnswer": 12,
    "numericalAnswer": 12,
    "explanation": "$a_t = \\alpha R = 3 \\times 4 = 12\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A circular cylinder of radius $R = 4\\text{ m}$ has an angular acceleration of $\\alpha = 6\\text{ rad/s}^2$. Calculate the tangential acceleration $a_t$ (in $\\text{m/s}^2$) of a point on its outer surface.",
    "options": [],
    "correctAnswer": 24,
    "numericalAnswer": 24,
    "explanation": "$a_t = \\alpha R = 6 \\times 4 = 24\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A circular cylinder of radius $R = 4\\text{ m}$ has an angular acceleration of $\\alpha = 9\\text{ rad/s}^2$. Calculate the tangential acceleration $a_t$ (in $\\text{m/s}^2$) of a point on its outer surface.",
    "options": [],
    "correctAnswer": 36,
    "numericalAnswer": 36,
    "explanation": "$a_t = \\alpha R = 9 \\times 4 = 36\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A circular cylinder of radius $R = 4\\text{ m}$ has an angular acceleration of $\\alpha = 12\\text{ rad/s}^2$. Calculate the tangential acceleration $a_t$ (in $\\text{m/s}^2$) of a point on its outer surface.",
    "options": [],
    "correctAnswer": 48,
    "numericalAnswer": 48,
    "explanation": "$a_t = \\alpha R = 12 \\times 4 = 48\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A circular cylinder of radius $R = 4\\text{ m}$ has an angular acceleration of $\\alpha = 15\\text{ rad/s}^2$. Calculate the tangential acceleration $a_t$ (in $\\text{m/s}^2$) of a point on its outer surface.",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$a_t = \\alpha R = 15 \\times 4 = 60\\text{ m/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Uniform circular motion",
    "chapter": "Kinematics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
