module.exports = [
  {
    "type": "NUMERICAL",
    "question": "When light of wavelength $300\\,\\text{nm}$ falls on a metal, the stopping potential is $1.85\\,\\text{V}$. What is the stopping potential in volts when light of wavelength $400\\,\\text{nm}$ falls on the same metal (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 0.82,
    "explanation": "Energy at $300\\,\\text{nm}$ is $E_1 = \\frac{1240}{300} = 4.133\\,\\text{eV}$. Work function is $\\phi = 4.133 - 1.85 = 2.283\\,\\text{eV}$. Energy at $400\\,\\text{nm}$ is $E_2 = \\frac{1240}{400} = 3.10\\,\\text{eV}$. Stopping potential is $V_0 = 3.10 - 2.283 = 0.817 \\approx 0.82\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "The stopping potential for a certain photosensitive metal is $V_1$ when illuminated by light of frequency $\\nu$, and $V_2$ when illuminated by light of frequency $2\\nu$. If $V_2 = 3V_1$, what is the threshold frequency of the metal in terms of $\\nu$?",
    "correctAnswer": 0.5,
    "explanation": "$eV_1 = h\\nu - h\\nu_0$ and $3eV_1 = 2h\\nu - h\\nu_0$. Multiplying first equation by 3 gives $3eV_1 = 3h\\nu - 3h\\nu_0$. Equating: $3h\\nu - 3h\\nu_0 = 2h\\nu - h\\nu_0 \\implies h\\nu = 2h\\nu_0 \\implies \\nu_0 = 0.5\\nu$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In a graph of stopping potential $V_0$ versus frequency $\\nu$, the intercept on the potential axis is $-2.0\\,\\text{V}$. What is the work function of the metal in $\\text{eV}$?",
    "correctAnswer": 2,
    "explanation": "Intercept on the $V_0$-axis is $-\\frac{\\phi}{e} = -2.0\\,\\text{V} \\implies \\phi = 2.0\\,\\text{eV}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In a graph of stopping potential $V_0$ versus frequency $\\nu$, the intercept on the frequency axis is $6.0 \\times 10^{14}\\,\\text{Hz}$. What is the work function of the metal in $\\text{eV}$ (take $h = 4.14 \\times 10^{-15}\\,\\text{eV}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 2.48,
    "explanation": "Intercept on frequency axis is $\\nu_0 = 6.0 \\times 10^{14}\\,\\text{Hz}$. $\\phi = h\\nu_0 = 4.14 \\times 10^{-15} \\times 6.0 \\times 10^{14} = 2.484 \\approx 2.48\\,\\text{eV}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "Light of wavelength $250\\,\\text{nm}$ falls on a metal surface. If the stopping potential is $1.5\\,\\text{V}$, what is the threshold wavelength of the metal in nanometers (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to one decimal place.",
    "correctAnswer": 358.4,
    "explanation": "Photon energy is $E = \\frac{1240}{250} = 4.96\\,\\text{eV}$. Work function is $\\phi = 4.96 - 1.5 = 3.46\\,\\text{eV}$. Threshold wavelength is $\\lambda_0 = \\frac{1240}{3.46} \\approx 358.38 \\approx 358.4\\,\\text{nm}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "The maximum speed of photoelectrons emitted from a surface is $6.0 \\times 10^5\\,\\text{m/s}$. Taking $m_e = 9.1 \\times 10^{-31}\\,\\text{kg}$ and $e = 1.6 \\times 10^{-19}\\,\\text{C}$, what is the stopping potential in volts? Round to two decimal places.",
    "correctAnswer": 1.02,
    "explanation": "$K_{\\max} = \\frac{1}{2}m v^2 = 0.5(9.1 \\times 10^{-31})(36 \\times 10^{10}) = 1.638 \\times 10^{-19}\\,\\text{J}$. Stopping potential is $V_0 = \\frac{1.638 \\times 10^{-19}}{1.6 \\times 10^{-19}} = 1.02375 \\approx 1.02\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "When a metal surface is irradiated with light of wavelength $\\lambda$, the stopping potential is $4.8\\,\\text{V}$. When irradiated with light of wavelength $2\\lambda$, the stopping potential is $1.6\\,\\text{V}$. What is the threshold wavelength in terms of $\\lambda$?",
    "correctAnswer": 4,
    "explanation": "$4.8 = \\frac{hc}{\\lambda} - \\phi$ and $1.6 = \\frac{hc}{2\\lambda} - \\phi$. Multiplying second by 2 gives $3.2 = \\frac{hc}{\\lambda} - 2\\phi$. Subtracting: $4.8 - 3.2 = \\phi \\implies \\phi = 1.6\\,\\text{eV}$. Then $\\frac{hc}{\\lambda} = 4.8 + 1.6 = 6.4\\,\\text{eV}$. Since $\\phi = \\frac{hc}{\\lambda_0} = 1.6\\,\\text{eV}$, $\\frac{\\lambda_0}{\\lambda} = \\frac{6.4}{1.6} = 4 \\implies \\lambda_0 = 4\\lambda$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In the previous problem, what is the value of $\\frac{hc}{\\lambda}$ in $\\text{eV}$?",
    "correctAnswer": 6.4,
    "explanation": "$\\frac{hc}{\\lambda} = 4.8 + \\phi = 4.8 + 1.6 = 6.4\\,\\text{eV}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photosensitive surface is illuminated with light composed of two wavelengths: $300\\,\\text{nm}$ and $500\\,\\text{nm}$. If the work function is $2.5\\,\\text{eV}$, what is the measured stopping potential in volts (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 1.63,
    "explanation": "Stopping potential is determined by the most energetic photons ($300\\,\\text{nm}$). $E = \\frac{1240}{300} \\approx 4.133\\,\\text{eV}$. $V_0 = 4.133 - 2.5 = 1.633 \\approx 1.63\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "The stopping potential for photoelectrons emitted from a metal with light of frequency $\\nu$ is $V_0$. When the frequency is increased by $25\\%$, the stopping potential becomes $1.5 V_0$. What is the ratio of the work function $\\phi$ to the initial photon energy $h\\nu$?",
    "correctAnswer": 0.5,
    "explanation": "$eV_0 = h\\nu - \\phi$ and $1.5 eV_0 = 1.25 h\\nu - \\phi$. Multiplying first by 1.5: $1.5 eV_0 = 1.5 h\\nu - 1.5 \\phi$. Equating: $1.5 h\\nu - 1.5 \\phi = 1.25 h\\nu - \\phi \\implies 0.25 h\\nu = 0.5 \\phi \\implies \\frac{\\phi}{h\\nu} = \\frac{0.25}{0.5} = 0.5$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "When light of frequency $1.0 \\times 10^{15}\\,\\text{Hz}$ illuminates a metal, the stopping potential is $1.65\\,\\text{V}$. What is the stopping potential in volts for frequency $1.5 \\times 10^{15}\\,\\text{Hz}$ (take $h/e = 4.14 \\times 10^{-15}\\,\\text{V}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 3.72,
    "explanation": "$\\Delta V_0 = \\frac{h}{e}\\Delta \\nu = 4.14 \\times 10^{-15} \\times 0.5 \\times 10^{15} = 2.07\\,\\text{V}$. New stopping potential is $V'_0 = 1.65 + 2.07 = 3.72\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the maximum kinetic energy of photoelectrons from a surface is $4.0\\,\\text{eV}$, what is the stopping potential in volts?",
    "correctAnswer": 4,
    "explanation": "$eV_0 = K_{\\max} = 4.0\\,\\text{eV} \\implies V_0 = 4.0\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "Light of wavelength $200\\,\\text{nm}$ falls on a metal with work function $4.0\\,\\text{eV}$. What is the stopping potential in volts (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)?",
    "correctAnswer": 2.2,
    "explanation": "$E = \\frac{1240}{200} = 6.2\\,\\text{eV}$. $V_0 = 6.2 - 4.0 = 2.2\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A beam of light of wavelength $180\\,\\text{nm}$ ejects photoelectrons with stopping potential $2.88\\,\\text{V}$. What is the work function of the metal in $\\text{eV}$ (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 4.01,
    "explanation": "$E = \\frac{1240}{180} \\approx 6.889\\,\\text{eV}$. $\\phi = 6.889 - 2.88 = 4.009 \\approx 4.01\\,\\text{eV}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the stopping potential is $0.5\\,\\text{V}$ for light of frequency $\\nu_1$ and $1.5\\,\\text{V}$ for frequency $\\nu_2$, what is the difference $\\nu_2 - \\nu_1$ in units of $10^{14}\\,\\text{Hz}$ (take $h/e = 4.14 \\times 10^{-15}\\,\\text{V}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 2.42,
    "explanation": "$\\Delta \\nu = \\frac{e\\Delta V}{h} = \\frac{1.5 - 0.5}{4.14 \\times 10^{-15}} = \\frac{1.0}{4.14 \\times 10^{-15}} \\approx 2.415 \\times 10^{14}\\,\\text{Hz} \\approx 2.42 \\times 10^{14}\\,\\text{Hz}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A metal with work function $2.1\\,\\text{eV}$ is illuminated with monochromatic light. If the stopping potential is $1.9\\,\\text{V}$, what is the wavelength of incident light in nanometers (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)?",
    "correctAnswer": 310,
    "explanation": "Photon energy is $E = \\phi + eV_0 = 2.1 + 1.9 = 4.0\\,\\text{eV}$. Wavelength is $\\lambda = \\frac{1240}{4.0} = 310\\,\\text{nm}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "The stopping potential for a metal surface is plotted against the inverse wavelength $1/\\lambda$ of incident radiation. The slope of the resulting straight line is $k$ in $\\text{V}\\cdot\\text{m}$. What is the value of $k$ in units of $10^{-7}\\,\\text{V}\\cdot\\text{m}$ (take $hc/e = 1.24 \\times 10^{-6}\\,\\text{V}\\cdot\\text{m}$)? Round to one decimal place.",
    "correctAnswer": 12.4,
    "explanation": "From $V_0 = \\left(\\frac{hc}{e}\\right)\\frac{1}{\\lambda} - \\frac{\\phi}{e}$, the slope is $\\frac{hc}{e} = 1.24 \\times 10^{-6}\\,\\text{V}\\cdot\\text{m} = 12.4 \\times 10^{-7}\\,\\text{V}\\cdot\\text{m}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "When light of frequency $\\nu$ is incident on a metal, the stopping potential is $V_0$. When frequency is increased to $3\\nu$, the stopping potential becomes $V'$. If the work function is $\\phi = h\\nu/2$, what is the ratio $V' / V_0$?",
    "correctAnswer": 5,
    "explanation": "$eV_0 = h\\nu - 0.5h\\nu = 0.5h\\nu$. $eV' = 3h\\nu - 0.5h\\nu = 2.5h\\nu$. Ratio is $\\frac{V'}{V_0} = \\frac{2.5}{0.5} = 5$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "What is the maximum speed in $\\text{m/s}$ of photoelectrons stopped by a potential of $2.5\\,\\text{V}$ (take $m_e = 9.1 \\times 10^{-31}\\,\\text{kg}$, $e = 1.6 \\times 10^{-19}\\,\\text{C}$)? Express in units of $10^5\\,\\text{m/s}$ and round to two decimal places.",
    "correctAnswer": 9.38,
    "explanation": "$v_{\\max} = \\sqrt{\\frac{2eV_0}{m}} = \\sqrt{\\frac{2(1.6 \\times 10^{-19})(2.5)}{9.1 \\times 10^{-31}}} = \\sqrt{\\frac{8.0 \\times 10^{-19}}{9.1 \\times 10^{-31}}} = \\sqrt{8.791 \\times 10^{11}} \\approx 9.376 \\times 10^5\\,\\text{m/s} \\approx 9.38 \\times 10^5\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "When light of wavelength $\\lambda_1 = 400\\,\\text{nm}$ is used, stopping potential is $V_1$. When wavelength is $\\lambda_2 = 300\\,\\text{nm}$, stopping potential is $V_2$. What is $V_2 - V_1$ in volts (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 1.03,
    "explanation": "$e(V_2 - V_1) = 1240\\left(\\frac{1}{300} - \\frac{1}{400}\\right) = 1240\\left(\\frac{100}{120000}\\right) = \\frac{1240}{1200} \\approx 1.033\\,\\text{eV} \\implies V_2 - V_1 \\approx 1.03\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "The stopping potential for electrons emitted from a surface illuminated by light of frequency $\\nu$ is $V_0$. If the frequency is doubled, the stopping potential becomes $V'$. Which of the following is the difference $V' - V_0$ in terms of $h, \\nu, e$?",
    "correctAnswer": 1,
    "explanation": "$e(V' - V_0) = h(2\\nu) - \\phi - (h\\nu - \\phi) = h\\nu \\implies V' - V_0 = \\frac{h\\nu}{e}$. The coefficient of $\\frac{h\\nu}{e}$ is 1.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In a photoelectric experiment, stopping potentials for two frequencies $\\nu_1 = 8 \\times 10^{14}\\,\\text{Hz}$ and $\\nu_2 = 12 \\times 10^{14}\\,\\text{Hz}$ are $V_1$ and $V_2$ respectively. What is $V_2 - V_1$ in volts (take $h/e = 4.14 \\times 10^{-15}\\,\\text{V}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 1.66,
    "explanation": "$V_2 - V_1 = \\frac{h}{e}(\\nu_2 - \\nu_1) = 4.14 \\times 10^{-15} \\times 4 \\times 10^{14} = 1.656 \\approx 1.66\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A metal with threshold wavelength $500\\,\\text{nm}$ is illuminated with light of wavelength $250\\,\\text{nm}$. What is the stopping potential in volts (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)?",
    "correctAnswer": 2.48,
    "explanation": "$\\phi = \\frac{1240}{500} = 2.48\\,\\text{eV}$. $E = \\frac{1240}{250} = 4.96\\,\\text{eV}$. $V_0 = 4.96 - 2.48 = 2.48\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the stopping potential is $3.0\\,\\text{V}$, what is the de Broglie wavelength in nanometers of the fastest emitted photoelectrons (take $\\lambda = 1.227/\\sqrt{V}\\,\\text{nm}$)? Round to three decimal places.",
    "correctAnswer": 0.708,
    "explanation": "The kinetic energy of the fastest photoelectrons is $3.0\\,\\text{eV}$, corresponding to an acceleration through $3.0\\,\\text{V}$. Thus $\\lambda = \\frac{1.227}{\\sqrt{3.0}} = \\frac{1.227}{1.732} \\approx 0.7084 \\approx 0.708\\,\\text{nm}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "Light of wavelength $350\\,\\text{nm}$ is incident on a metal with work function $2.2\\,\\text{eV}$. What is the stopping potential in volts (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 1.34,
    "explanation": "$E = \\frac{1240}{350} \\approx 3.543\\,\\text{eV}$. $V_0 = 3.543 - 2.2 = 1.343 \\approx 1.34\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "The stopping potential for a photosensitive metal is $1.2\\,\\text{V}$. What is the maximum kinetic energy of the photoelectrons in electron-volts (eV)?",
    "correctAnswer": 1.2,
    "explanation": "$K_{\\max} = eV_0 = 1.2\\,\\text{eV}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A metal has threshold frequency $\\nu_0 = 4.5 \\times 10^{14}\\,\\text{Hz}$. Light of frequency $9.0 \\times 10^{14}\\,\\text{Hz}$ illuminates the metal. What is the stopping potential in volts (take $h/e = 4.14 \\times 10^{-15}\\,\\text{V}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 1.86,
    "explanation": "$V_0 = \\frac{h}{e}(\\nu - \\nu_0) = 4.14 \\times 10^{-15} \\times 4.5 \\times 10^{14} = 1.863 \\approx 1.86\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A photosensitive surface is illuminated with light of wavelength $\\lambda$ giving stopping potential $V_1$. When light of wavelength $\\lambda/3$ is used, the stopping potential is $V_2 = 4V_1$. What is the ratio of the threshold wavelength to $\\lambda$ (i.e., $\\lambda_0 / \\lambda$)?",
    "correctAnswer": 3,
    "explanation": "$eV_1 = \\frac{hc}{\\lambda} - \\phi$ and $4eV_1 = \\frac{3hc}{\\lambda} - \\phi$. Multiplying the first equation by 4 gives $4eV_1 = \\frac{4hc}{\\lambda} - 4\\phi$. Equating gives $\\frac{4hc}{\\lambda} - 4\\phi = \\frac{3hc}{\\lambda} - \\phi \\implies \\frac{hc}{\\lambda} = 3\\phi \\implies \\phi = \\frac{hc}{3\\lambda}$. Since $\\phi = \\frac{hc}{\\lambda_0}$, we get $\\lambda_0 = 3\\lambda$, so the ratio is 3.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "When a metal surface is irradiated with light of wavelength $\\lambda$, the stopping potential is $V_0$. When irradiated with light of wavelength $\\lambda/2$, the stopping potential is $3V_0$. What is the work function of the metal in terms of $\\frac{hc}{\\lambda}$?",
    "correctAnswer": 0.5,
    "explanation": "$eV_0 = \\frac{hc}{\\lambda} - \\phi$ and $3eV_0 = \\frac{2hc}{\\lambda} - \\phi$. Multiplying first by 3: $3eV_0 = \\frac{3hc}{\\lambda} - 3\\phi$. Equating: $\\frac{3hc}{\\lambda} - 3\\phi = \\frac{2hc}{\\lambda} - \\phi \\implies 2\\phi = \\frac{hc}{\\lambda} \\implies \\phi = 0.5\\frac{hc}{\\lambda}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "For the previous problem, what is the threshold wavelength in terms of $\\lambda$?",
    "correctAnswer": 2,
    "explanation": "$\\phi = \\frac{hc}{\\lambda_0} = \\frac{hc}{2\\lambda} \\implies \\lambda_0 = 2\\lambda$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A beam of light contains two frequencies $\\nu_1 = 10^{15}\\,\\text{Hz}$ and $\\nu_2 = 2 \\times 10^{15}\\,\\text{Hz}$. If the work function is $3.0\\,\\text{eV}$, what is the stopping potential in volts (take $h = 4.14 \\times 10^{-15}\\,\\text{eV}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 5.28,
    "explanation": "Stopping potential is determined by the higher frequency $\\nu_2 = 2 \\times 10^{15}\\,\\text{Hz}$. $E_2 = 4.14 \\times 10^{-15} \\times 2 \\times 10^{15} = 8.28\\,\\text{eV}$. $V_0 = 8.28 - 3.0 = 5.28\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the work function of a metal is $1.8\\,\\text{eV}$, what is the maximum velocity in $\\text{m/s}$ of emitted photoelectrons when illuminated by light of energy $3.4\\,\\text{eV}$ (take $m_e = 9.1 \\times 10^{-31}\\,\\text{kg}$, $1\\,\\text{eV} = 1.6 \\times 10^{-19}\\,\\text{J}$)? Express in units of $10^5\\,\\text{m/s}$ and round to two decimal places.",
    "correctAnswer": 7.5,
    "explanation": "$K_{\\max} = 3.4 - 1.8 = 1.6\\,\\text{eV} = 1.6 \\times 1.6 \\times 10^{-19} = 2.56 \\times 10^{-19}\\,\\text{J}$. $v_{\\max} = \\sqrt{\\frac{2(2.56 \\times 10^{-19})}{9.1 \\times 10^{-31}}} = \\sqrt{5.626 \\times 10^{11}} \\approx 7.5009 \\times 10^5\\,\\text{m/s} \\approx 7.50 \\times 10^5\\,\\text{m/s}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A stopping potential of $0.82\\,\\text{V}$ is required to stop electrons emitted from a metal by light of wavelength $400\\,\\text{nm}$. What is the work function of the metal in $\\text{eV}$ (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 2.28,
    "explanation": "Photon energy is $E = \\frac{1240}{400} = 3.10\\,\\text{eV}$. Work function is $\\phi = 3.10 - 0.82 = 2.28\\,\\text{eV}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "Light of wavelength $280\\,\\text{nm}$ ejects photoelectrons from a metal. If stopping potential is $1.93\\,\\text{V}$, what is the threshold wavelength of the metal in nanometers (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to one decimal place.",
    "correctAnswer": 496.2,
    "explanation": "Photon energy is $E = \\frac{1240}{280} \\approx 4.4286\\,\\text{eV}$. Work function is $\\phi = 4.4286 - 1.93 = 2.4986\\,\\text{eV}$. Threshold wavelength is $\\lambda_0 = \\frac{1240}{2.4986} \\approx 496.28 \\approx 496.2\\,\\text{nm}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "What is the ratio of the stopping potential for light of wavelength $200\\,\\text{nm}$ to that for light of wavelength $300\\,\\text{nm}$ on a metal of work function $2.0\\,\\text{eV}$ (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 1.97,
    "explanation": "For $200\\,\\text{nm}$: $E_1 = \\frac{1240}{200} = 6.2\\,\\text{eV} \\implies V_{0,1} = 6.2 - 2.0 = 4.2\\,\\text{V}$. For $300\\,\\text{nm}$: $E_2 = \\frac{1240}{300} \\approx 4.133\\,\\text{eV} \\implies V_{0,2} = 4.133 - 2.0 = 2.133\\,\\text{V}$. The ratio is $\\frac{4.2}{2.133} \\approx 1.969 \\approx 1.97$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A metal with work function $2.5\\,\\text{eV}$ is illuminated with light of frequency $1.0 \\times 10^{15}\\,\\text{Hz}$. What is the stopping potential in volts (take $h = 4.14 \\times 10^{-15}\\,\\text{eV}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 1.64,
    "explanation": "$E = 4.14 \\times 10^{-15} \\times 10^{15} = 4.14\\,\\text{eV}$. Stopping potential is $V_0 = 4.14 - 2.5 = 1.64\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "When the wavelength of incident radiation is changed from $500\\,\\text{nm}$ to $200\\,\\text{nm}$, by how many volts does the stopping potential increase (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 3.72,
    "explanation": "$\\Delta V_0 = \\frac{\\Delta E}{e} = 1240\\left(\\frac{1}{200} - \\frac{1}{500}\\right) = 1240\\left(\\frac{300}{100000}\\right) = 1240 \\times 0.003 = 3.72\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "A monochromatic light of frequency $\\nu$ produces photoelectrons with stopping potential $V_1$. When the frequency is increased by $\\Delta \\nu = 2.0 \\times 10^{14}\\,\\text{Hz}$, the stopping potential increases by $\\Delta V_0$. What is $\\Delta V_0$ in volts (take $h/e = 4.14 \\times 10^{-15}\\,\\text{V}\\cdot\\text{s}$)? Round to two decimal places.",
    "correctAnswer": 0.83,
    "explanation": "$\\Delta V_0 = \\frac{h}{e}\\Delta \\nu = 4.14 \\times 10^{-15} \\times 2.0 \\times 10^{14} = 0.828 \\approx 0.83\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "If the work function of a metal is $3.2\\,\\text{eV}$, what is the maximum kinetic energy in $\\text{eV}$ of photoelectrons emitted by photons of energy $5.0\\,\\text{eV}$?",
    "correctAnswer": 1.8,
    "explanation": "$K_{\\max} = 5.0 - 3.2 = 1.8\\,\\text{eV}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "What is the threshold wavelength of a metal in nanometers if its work function is $3.1\\,\\text{eV}$ (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)?",
    "correctAnswer": 400,
    "explanation": "$\\lambda_0 = \\frac{1240}{3.1} = 400\\,\\text{nm}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "In a photoelectric experiment, a stopping potential of $2.0\\,\\text{V}$ is observed. If the electron charge is $1.6 \\times 10^{-19}\\,\\text{C}$, what is the maximum kinetic energy of the emitted photoelectrons in units of $10^{-19}\\,\\text{J}$?",
    "correctAnswer": 3.2,
    "explanation": "$K_{\\max} = eV_0 = (1.6 \\times 10^{-19})(2.0) = 3.2 \\times 10^{-19}\\,\\text{J}$. Value is $3.2$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  },
  {
    "type": "NUMERICAL",
    "question": "Light of wavelength $330\\,\\text{nm}$ is incident on a metal with work function $2.25\\,\\text{eV}$. What is the stopping potential in volts (take $hc = 1240\\,\\text{eV}\\cdot\\text{nm}$)? Round to two decimal places.",
    "correctAnswer": 1.51,
    "explanation": "Photon energy is $E = \\frac{1240}{330} \\approx 3.7576\\,\\text{eV}$. $V_0 = 3.7576 - 2.25 = 1.5076 \\approx 1.51\\,\\text{V}$.",
    "marks": 4,
    "negativeMarks": 1,
    "subTopic": "Photoelectric effect",
    "chapter": "Dual Nature of Matter and Radiation",
    "subject": "Physics"
  }
];
