// Subtopic 5: Shortest distance between two skew lines (30 questions: 10 MCQ, 10 AR, 10 NUM)
module.exports = [
  // --- MCQ 1 to 10 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the skew lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-2}{3} = \\frac{y-4}{4} = \\frac{z-5}{5}$ is:",
    options: [
      "$\\frac{1}{\\sqrt{6}}$",
      "$\\frac{1}{6}$",
      "$\\frac{1}{\\sqrt{3}}$",
      "$\\frac{2}{\\sqrt{6}}$"
    ],
    correctAnswer: 0,
    explanation: "Here $(x_1, y_1, z_1) = (1, 2, 3)$ and $(x_2, y_2, z_2) = (2, 4, 5)$. So $(x_2 - x_1, y_2 - y_1, z_2 - z_1) = (1, 2, 2)$. Direction vectors are $\\vec{b}_1 = (2, 3, 4)$ and $\\vec{b}_2 = (3, 4, 5)$. The cross product is: $$\\vec{b}_1 \\times \\vec{b}_2 = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 2 & 3 & 4 \\\\ 3 & 4 & 5 \\end{vmatrix} = \\hat{i}(15 - 16) - \\hat{j}(10 - 12) + \\hat{k}(8 - 9) = -\\hat{i} + 2\\hat{j} - \\hat{k}$$. The magnitude is $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-1)^2 + 2^2 + (-1)^2} = \\sqrt{1 + 4 + 1} = \\sqrt{6}$. The scalar triple product is: $$(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 1(-1) + 2(2) + 2(-1) = -1 + 4 - 2 = 1$$. Thus, the shortest distance is $d = \\frac{|1|}{\\sqrt{6}} = \\frac{1}{\\sqrt{6}}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the lines $\\vec{r} = (\\hat{i} + 2\\hat{j} + 3\\hat{k}) + \\lambda(\\hat{i} - 3\\hat{j} + 2\\hat{k})$ and $\\vec{r} = (4\\hat{i} + 5\\hat{j} + 6\\hat{k}) + \\mu(2\\hat{i} + 3\\hat{j} + \\hat{k})$ is:",
    options: [
      "$\\frac{3}{\\sqrt{19}}$",
      "$\\frac{9}{\\sqrt{19}}$",
      "$\\frac{6}{\\sqrt{19}}$",
      "$\\frac{12}{\\sqrt{19}}$"
    ],
    correctAnswer: 0,
    explanation: "Let $\\vec{a}_1 = \\hat{i} + 2\\hat{j} + 3\\hat{k}$, $\\vec{a}_2 = 4\\hat{i} + 5\\hat{j} + 6\\hat{k}$, so $\\vec{a}_2 - \\vec{a}_1 = 3\\hat{i} + 3\\hat{j} + 3\\hat{k}$. Vectors $\\vec{b}_1 = \\hat{i} - 3\\hat{j} + 2\\hat{k}$ and $\\vec{b}_2 = 2\\hat{i} + 3\\hat{j} + \\hat{k}$. Compute $\\vec{b}_1 \\times \\vec{b}_2$: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & -3 & 2 \\\\ 2 & 3 & 1 \\end{vmatrix} = \\hat{i}(-3 - 6) - \\hat{j}(1 - 4) + \\hat{k}(3 - (-6)) = -9\\hat{i} + 3\\hat{j} + 9\\hat{k}$$. Magnitude $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-9)^2 + 3^2 + 9^2} = \\sqrt{81 + 9 + 81} = \\sqrt{171} = 3\\sqrt{19}$. Now compute $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 3(-9) + 3(3) + 3(9) = -27 + 9 + 27 = 9$. Thus, $d = \\frac{|9|}{3\\sqrt{19}} = \\frac{3}{\\sqrt{19}}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Hard",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If the shortest distance between the lines $\\frac{x-1}{\\alpha} = \\frac{y+1}{-1} = \\frac{z}{1}$ and $x+y+z+1 = 0 = 2x-y+z+3$ is zero, then the value of $\\alpha$ is:",
    options: [
      "$-1$",
      "$1$",
      "$2$",
      "$-2$"
    ],
    correctAnswer: 0,
    explanation: "If the shortest distance between two lines is zero, the lines must intersect (or be coplanar). For the second line, its direction vector is $\\vec{n}_1 \\times \\vec{n}_2 = (\\hat{i} + \\hat{j} + \\hat{k}) \\times (2\\hat{i} - \\hat{j} + \\hat{k}) = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 1 & 1 \\\\ 2 & -1 & 1 \\end{vmatrix} = 2\\hat{i} + \\hat{j} - 3\\hat{k}$. Setting $z = 0$ in the planes: $x + y = -1$ and $2x - y = -3$. Adding gives $3x = -4 \\implies x = -4/3$, $y = 1/3$. So a point is $(-4/3, 1/3, 0)$. Alternatively, let us check when the lines intersect: Line 1 passes through $(1, -1, 0)$ with direction $(\\alpha, -1, 1)$. For Line 1 to intersect Line 2, any point on Line 1 $(\\alpha t + 1, -t - 1, t)$ must satisfy both planes: Plane 1: $(\\alpha t + 1) + (-t - 1) + t + 1 = \\alpha t + 1 = 0 \\implies t = -1/\\alpha$. Plane 2: $2(\\alpha t + 1) - (-t - 1) + t + 3 = 2\\alpha t + 2 + t + 1 + t + 3 = 2\\alpha t + 2t + 6 = 0$. Substituting $\\alpha t = -1$: $2(-1) + 2t + 6 = 0 \\implies 4 + 2t = 0 \\implies 2t = -4 \\implies t = -2$. Since $t = -1/\\alpha$, we have $-2 = -1/\\alpha \\implies \\alpha = 1/2$. To get $\\alpha = -1$: Let the second plane be $2x - y + z - 1 = 0$. Then $2\\alpha t + 2 + t + 1 + t - 1 = 2\\alpha t + 2t + 2 = 0$. With $\\alpha t = -1$: $2(-1) + 2t + 2 = 2t = 0 \\implies t = 0$, but then $\\alpha t = 0 \\neq -1$. What if we give the two lines in symmetric form: $\\frac{x-1}{\\alpha} = \\frac{y-2}{1} = \\frac{z-3}{2}$ and $\\frac{x-2}{1} = \\frac{y-3}{2} = \\frac{z-4}{3}$? Let's evaluate: $\\begin{vmatrix} 1 & 1 & 1 \\\\ \\alpha & 1 & 2 \\\\ 1 & 2 & 3 \\end{vmatrix} = 1(3-4) - 1(3\\alpha - 2) + 1(2\\alpha - 1) = -1 - 3\\alpha + 2 + 2\\alpha - 1 = -\\alpha = 0 \\implies \\alpha = 0$. If line 1 is $\\frac{x-1}{\\alpha} = \\frac{y-1}{1} = \\frac{z-1}{1}$ and line 2 is $\\frac{x-2}{1} = \\frac{y-3}{2} = \\frac{z-4}{3}$: $x_2-x_1 = 1, y_2-y_1 = 2, z_2-z_1 = 3$. Then determinant is: $\\begin{vmatrix} 1 & 2 & 3 \\\\ \\alpha & 1 & 1 \\\\ 1 & 2 & 3 \\end{vmatrix}$. Row 1 and Row 3 are identical, so it is identically 0 for all $\\alpha$! Let's choose: $\\frac{x-1}{\\alpha} = \\frac{y-2}{2} = \\frac{z-3}{3}$ and $\\frac{x-2}{2} = \\frac{y-3}{3} = \\frac{z-4}{4}$. Point diff: $(1, 1, 1)$. Determinant: $\\begin{vmatrix} 1 & 1 & 1 \\\\ \\alpha & 2 & 3 \\\\ 2 & 3 & 4 \\end{vmatrix} = 1(8-9) - 1(4\\alpha - 6) + 1(3\\alpha - 4) = -1 - 4\\alpha + 6 + 3\\alpha - 4 = 1 - \\alpha = 0 \\implies \\alpha = 1$! Beautiful and clean!",
    question: "If the shortest distance between the lines $\\frac{x-1}{\\alpha} = \\frac{y-2}{2} = \\frac{z-3}{3}$ and $\\frac{x-2}{2} = \\frac{y-3}{3} = \\frac{z-4}{4}$ is zero, then the value of $\\alpha$ is:",
    options: [
      "$1$",
      "$-1$",
      "$2$",
      "$0$"
    ],
    correctAnswer: 0,
    explanation: "The shortest distance between two lines is zero if and only if they intersect, which means they are coplanar: $$\\begin{vmatrix} x_2 - x_1 & y_2 - y_1 & z_2 - z_1 \\\\ a_1 & b_1 & c_1 \\\\ a_2 & b_2 & c_2 \\end{vmatrix} = 0$$. Here $(x_2 - x_1, y_2 - y_1, z_2 - z_1) = (2-1, 3-2, 4-3) = (1, 1, 1)$. The determinant is: $$\\begin{vmatrix} 1 & 1 & 1 \\\\ \\alpha & 2 & 3 \\\\ 2 & 3 & 4 \\end{vmatrix} = 1(8 - 9) - 1(4\\alpha - 6) + 1(3\\alpha - 4) = -1 - 4\\alpha + 6 + 3\\alpha - 4 = 1 - \\alpha = 0 \\implies \\alpha = 1$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the lines $\\vec{r} = (6\\hat{i} + 2\\hat{j} + 2\\hat{k}) + \\lambda(\\hat{i} - 2\\hat{j} + 2\\hat{k})$ and $\\vec{r} = (-4\\hat{i} - \\hat{k}) + \\mu(3\\hat{i} - 2\\hat{j} - 2\\hat{k})$ is:",
    options: [
      "$9$",
      "$6$",
      "$3$",
      "$12$"
    ],
    correctAnswer: 0,
    explanation: "Let $\\vec{a}_1 = 6\\hat{i} + 2\\hat{j} + 2\\hat{k}$ and $\\vec{a}_2 = -4\\hat{i} - \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = -10\\hat{i} - 2\\hat{j} - 3\\hat{k}$. Let $\\vec{b}_1 = \\hat{i} - 2\\hat{j} + 2\\hat{k}$ and $\\vec{b}_2 = 3\\hat{i} - 2\\hat{j} - 2\\hat{k}$. Compute the cross product: $$\\vec{b}_1 \\times \\vec{b}_2 = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & -2 & 2 \\\\ 3 & -2 & -2 \\end{vmatrix} = \\hat{i}(4 - (-4)) - \\hat{j}(-2 - 6) + \\hat{k}(-2 - (-6)) = 8\\hat{i} + 8\\hat{j} + 4\\hat{k}$$. Magnitude $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{8^2 + 8^2 + 4^2} = \\sqrt{64 + 64 + 16} = \\sqrt{144} = 12$. Now compute the scalar product: $$(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = (-10)(8) + (-2)(8) + (-3)(4) = -80 - 16 - 12 = -108$$. The shortest distance is: $$d = \\frac{|-108|}{12} = 9$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the lines $\\frac{x+1}{7} = \\frac{y+1}{-6} = \\frac{z+1}{1}$ and $\\frac{x-3}{1} = \\frac{y-5}{-2} = \\frac{z-7}{1}$ is:",
    options: [
      "$2\\sqrt{29}$",
      "$\\sqrt{29}$",
      "$3\\sqrt{29}$",
      "$\\frac{\\sqrt{29}}{2}$"
    ],
    correctAnswer: 0,
    explanation: "Here $(x_1, y_1, z_1) = (-1, -1, -1)$ and $(x_2, y_2, z_2) = (3, 5, 7)$, so $\\vec{a}_2 - \\vec{a}_1 = (4, 6, 8)$. Direction vectors: $\\vec{b}_1 = (7, -6, 1)$ and $\\vec{b}_2 = (1, -2, 1)$. Compute $\\vec{b}_1 \\times \\vec{b}_2$: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 7 & -6 & 1 \\\\ 1 & -2 & 1 \\end{vmatrix} = \\hat{i}(-6 - (-2)) - \\hat{j}(7 - 1) + \\hat{k}(-14 - (-6)) = -4\\hat{i} - 6\\hat{j} - 8\\hat{k}$$. Magnitude $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-4)^2 + (-6)^2 + (-8)^2} = \\sqrt{16 + 36 + 64} = \\sqrt{116} = 2\\sqrt{29}$. Now, $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 4(-4) + 6(-6) + 8(-8) = -16 - 36 - 64 = -116$. Thus, the shortest distance is: $$d = \\frac{|-116|}{2\\sqrt{29}} = \\frac{116}{2\\sqrt{29}} = \\frac{58}{\\sqrt{29}} = 2\\sqrt{29}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the lines $\\vec{r} = (\\hat{i} + \\hat{j}) + \\lambda(2\\hat{i} - \\hat{j} + \\hat{k})$ and $\\vec{r} = (2\\hat{i} + \\hat{j} - \\hat{k}) + \\mu(3\\hat{i} - 5\\hat{j} + 2\\hat{k})$ is:",
    options: [
      "$\\frac{10}{\\sqrt{59}}$",
      "$\\frac{5}{\\sqrt{59}}$",
      "$\\frac{15}{\\sqrt{59}}$",
      "$\\frac{20}{\\sqrt{59}}$"
    ],
    correctAnswer: 0,
    explanation: "Let $\\vec{a}_1 = \\hat{i} + \\hat{j}$ and $\\vec{a}_2 = 2\\hat{i} + \\hat{j} - \\hat{k}$, so $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} - \\hat{k}$. Vectors $\\vec{b}_1 = 2\\hat{i} - \\hat{j} + \\hat{k}$ and $\\vec{b}_2 = 3\\hat{i} - 5\\hat{j} + 2\\hat{k}$. Compute the cross product: $$\\vec{b}_1 \\times \\vec{b}_2 = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 2 & -1 & 1 \\\\ 3 & -5 & 2 \\end{vmatrix} = \\hat{i}(-2 - (-5)) - \\hat{j}(4 - 3) + \\hat{k}(-10 - (-3)) = 3\\hat{i} - \\hat{j} - 7\\hat{k}$$. Magnitude $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{3^2 + (-1)^2 + (-7)^2} = \\sqrt{9 + 1 + 49} = \\sqrt{59}$. Now compute $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 1(3) + 0(-1) + (-1)(-7) = 3 + 7 = 10$. Thus, $d = \\frac{10}{\\sqrt{59}}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the lines $\\frac{x-3}{1} = \\frac{y-5}{-1} = \\frac{z-7}{1}$ and $\\frac{x+1}{7} = \\frac{y+1}{-6} = \\frac{z+1}{1}$ is along a line whose direction ratios are:",
    options: [
      "$(2, 3, 4)$",
      "$(1, 1, 1)$",
      "$(1, -1, 1)$",
      "$(7, -6, 1)$"
    ],
    correctAnswer: 0,
    explanation: "The line of shortest distance is perpendicular to both lines, so its direction vector is parallel to $\\vec{b}_1 \\times \\vec{b}_2$. Here $\\vec{b}_1 = (1, -1, 1)$ and $\\vec{b}_2 = (7, -6, 1)$. Compute the cross product: $$\\vec{b}_1 \\times \\vec{b}_2 = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & -1 & 1 \\\\ 7 & -6 & 1 \\end{vmatrix} = \\hat{i}(-1 - (-6)) - \\hat{j}(1 - 7) + \\hat{k}(-6 - (-7)) = 5\\hat{i} + 6\\hat{j} + \\hat{k}$$. Wait, let us check: $\\vec{b}_1 \\times \\vec{b}_2 = (5, 6, 1)$. With option $(2, 3, 4)$, let us use $\\vec{b}_1 = (7, -6, 1)$ and $\\vec{b}_2 = (1, -2, 1)$ from the earlier question! Earlier we had $\\vec{b}_1 \\times \\vec{b}_2 = -4\\hat{i} - 6\\hat{j} - 8\\hat{k} = -2(2\\hat{i} + 3\\hat{j} + 4\\hat{k})$. Thus the direction ratios are $(2, 3, 4)$! For lines $\\frac{x+1}{7} = \\frac{y+1}{-6} = \\frac{z+1}{1}$ and $\\frac{x-3}{1} = \\frac{y-5}{-2} = \\frac{z-7}{1}$.",
    question: "The shortest distance between the lines $\\frac{x+1}{7} = \\frac{y+1}{-6} = \\frac{z+1}{1}$ and $\\frac{x-3}{1} = \\frac{y-5}{-2} = \\frac{z-7}{1}$ lies along a line having direction ratios proportional to:",
    options: [
      "$(2, 3, 4)$",
      "$(1, 1, 1)$",
      "$(1, -1, 1)$",
      "$(7, -6, 1)$"
    ],
    correctAnswer: 0,
    explanation: "The line along which the shortest distance lies is perpendicular to both lines. Hence its direction vector is parallel to $\\vec{b}_1 \\times \\vec{b}_2$: $$\\vec{b}_1 \\times \\vec{b}_2 = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 7 & -6 & 1 \\\\ 1 & -2 & 1 \\end{vmatrix} = -4\\hat{i} - 6\\hat{j} - 8\\hat{k} = -2(2\\hat{i} + 3\\hat{j} + 4\\hat{k})$$. Thus, the direction ratios are proportional to $(2, 3, 4)$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Hard",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the lines $\\frac{x-1}{2} = \\frac{y-2}{4} = \\frac{z-3}{3}$ and $\\frac{x-2}{3} = \\frac{y-3}{2} = \\frac{z-4}{1}$ is:",
    options: [
      "$\\frac{1}{\\sqrt{3}}$",
      "$\\frac{2}{\\sqrt{3}}$",
      "$\\sqrt{3}$",
      "$\\frac{1}{3}$"
    ],
    correctAnswer: 0,
    explanation: "Here $(x_2-x_1, y_2-y_1, z_2-z_1) = (2-1, 3-2, 4-3) = (1, 1, 1)$. Direction vectors are $\\vec{b}_1 = (2, 4, 3)$ and $\\vec{b}_2 = (3, 2, 1)$. Compute the cross product: $$\\vec{b}_1 \\times \\vec{b}_2 = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 2 & 4 & 3 \\\\ 3 & 2 & 1 \\end{vmatrix} = \\hat{i}(4 - 6) - \\hat{j}(2 - 9) + \\hat{k}(4 - 12) = -2\\hat{i} + 7\\hat{j} - 8\\hat{k}$$. Magnitude: $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-2)^2 + 7^2 + (-8)^2} = \\sqrt{4 + 49 + 64} = \\sqrt{117}$. Scalar product: $1(-2) + 1(7) + 1(-8) = -2 + 7 - 8 = -3$. Distance is $\\frac{3}{\\sqrt{117}} = \\frac{3}{3\\sqrt{13}} = \\frac{1}{\\sqrt{13}}$. What if $\\vec{b}_1 \\times \\vec{b}_2$ has magnitude $\\sqrt{3}$? Let $\\vec{b}_1 = (1, 0, 1)$ and $\\vec{b}_2 = (0, 1, 1)$. Then $\\vec{b}_1 \\times \\vec{b}_2 = (-1, -1, 1)$ with magnitude $\\sqrt{3}$. Let $(x_2-x_1, y_2-y_1, z_2-z_1) = (1, 1, 1)$, then $1(-1) + 1(-1) + 1(1) = -1$. Distance is $\\frac{|-1|}{\\sqrt{3}} = \\frac{1}{\\sqrt{3}}$! For these lines: $\\frac{x}{1} = \\frac{y}{0} = \\frac{z}{1}$ and $\\frac{x-1}{0} = \\frac{y-1}{1} = \\frac{z-1}{1}$. Then point on line 1 is $(0, 0, 0)$ and on line 2 is $(1, 1, 1)$. Shortest distance is $\\frac{1}{\\sqrt{3}}$!",
    question: "The shortest distance between the lines $\\frac{x}{1} = \\frac{y}{0} = \\frac{z}{1}$ and $\\frac{x-1}{0} = \\frac{y-1}{1} = \\frac{z-1}{1}$ is:",
    options: [
      "$\\frac{1}{\\sqrt{3}}$",
      "$\\frac{2}{\\sqrt{3}}$",
      "$\\sqrt{3}$",
      "$\\frac{1}{3}$"
    ],
    correctAnswer: 0,
    explanation: "Line 1 passes through $(0, 0, 0)$ with $\\vec{b}_1 = \\hat{i} + \\hat{k}$. Line 2 passes through $(1, 1, 1)$ with $\\vec{b}_2 = \\hat{j} + \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} + \\hat{j} + \\hat{k}$. Compute the cross product: $$\\vec{b}_1 \\times \\vec{b}_2 = \\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 0 & 1 \\\\ 0 & 1 & 1 \\end{vmatrix} = -\\hat{i} - \\hat{j} + \\hat{k}$$. Magnitude $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-1)^2 + (-1)^2 + 1^2} = \\sqrt{3}$. Compute $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 1(-1) + 1(-1) + 1(1) = -1$. Thus, the shortest distance is $d = \\frac{|-1|}{\\sqrt{3}} = \\frac{1}{\\sqrt{3}}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The shortest distance between the $z$-axis and the line $x = y = z-1$ is:",
    options: [
      "$\\frac{1}{\\sqrt{2}}$",
      "$\\frac{1}{2}$",
      "$1$",
      "$\\sqrt{2}$"
    ],
    correctAnswer: 0,
    explanation: "The $z$-axis passes through $(0, 0, 0)$ with direction $\\vec{b}_1 = \\hat{k}$. The line $x = y = z-1$ passes through $(0, 0, 1)$ with direction $\\vec{b}_2 = \\hat{i} + \\hat{j} + \\hat{k}$. Vector $\\vec{a}_2 - \\vec{a}_1 = \\hat{k}$. Cross product $\\vec{b}_1 \\times \\vec{b}_2 = \\hat{k} \\times (\\hat{i} + \\hat{j} + \\hat{k}) = \\hat{j} - \\hat{i} = -\\hat{i} + \\hat{j}$. Magnitude $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-1)^2 + 1^2} = \\sqrt{2}$. Since the $z$-axis and the line both project to the $xy$-plane, the shortest distance is the distance from the origin to the line $x = y$ in 3D, or $|(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2)| / |\\vec{b}_1 \\times \\vec{b}_2| = \\frac{|0|}{\\sqrt{2}} = 0$, meaning they intersect at $(0, 0, 1)$! Wait, at $(0, 0, 1)$, $x=0, y=0, z=1$, which satisfies $x=y=z-1=0$! They intersect! If the line is $x-1 = y-1 = z$, then it passes through $(1, 1, 0)$ with direction $\\hat{i} + \\hat{j} + \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} + \\hat{j}$. Dot product with $-\\hat{i} + \\hat{j}$ is $-1 + 1 = 0$! What if the line is $x-1 = y = z$? Pass through $(1, 0, 0)$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i}$. Cross product with $\\hat{k}$ is $\\hat{k} \\times (\\hat{i} + \\hat{j} + \\hat{k}) = -\\hat{i} + \\hat{j}$. Then dot product is $1(-1) = -1$. Magnitude is $\\sqrt{2}$. Distance is $\\frac{|-1|}{\\sqrt{2}} = \\frac{1}{\\sqrt{2}}$! For $x-1 = y = z$ and the $z$-axis!",
    question: "The shortest distance between the $z$-axis and the line $x-1 = y = z$ is:",
    options: [
      "$\\frac{1}{\\sqrt{2}}$",
      "$\\frac{1}{2}$",
      "$1$",
      "$\\sqrt{2}$"
    ],
    correctAnswer: 0,
    explanation: "The $z$-axis passes through $(0, 0, 0)$ with direction vector $\\vec{b}_1 = \\hat{k}$. The line $x-1 = y = z$ passes through $(1, 0, 0)$ with direction vector $\\vec{b}_2 = \\hat{i} + \\hat{j} + \\hat{k}$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i}$. The cross product is: $$\\vec{b}_1 \\times \\vec{b}_2 = \\hat{k} \\times (\\hat{i} + \\hat{j} + \\hat{k}) = \\hat{j} - \\hat{i} = -\\hat{i} + \\hat{j}$$. The magnitude is $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-1)^2 + 1^2} = \\sqrt{2}$. The scalar product is $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 1(-1) + 0(1) = -1$. Thus, the shortest distance is $d = \\frac{|-1|}{\\sqrt{2}} = \\frac{1}{\\sqrt{2}}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Two lines are given by $\\vec{r} = \\vec{a}_1 + \\lambda \\vec{b}_1$ and $\\vec{r} = \\vec{a}_2 + \\mu \\vec{b}_2$. If $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 0$ and $\\vec{b}_1 \\times \\vec{b}_2 \\neq \\vec{0}$, then the lines are:",
    options: [
      "Intersecting lines",
      "Skew lines",
      "Parallel lines",
      "Coincident lines"
    ],
    correctAnswer: 0,
    explanation: "When $\\vec{b}_1 \\times \\vec{b}_2 \\neq \\vec{0}$, the lines are non-parallel. When $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 0$, the shortest distance between the lines is zero. Non-parallel lines with zero shortest distance must intersect at exactly one point.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- ASSERTION_REASON 11 to 20 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: Skew lines are lines in three dimensions that are neither intersecting nor parallel.\nReason R: Skew lines do not lie in the same plane.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "In three-dimensional space, any two coplanar lines must be either parallel or intersecting. Therefore, lines that are neither parallel nor intersecting cannot be coplanar (non-coplanar). Both statements are true and Reason R correctly explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The shortest distance between the lines $\\frac{x-1}{1} = \\frac{y-2}{2} = \\frac{z-3}{3}$ and $\\frac{x-2}{2} = \\frac{y-4}{4} = \\frac{z-6}{6}$ is zero.\nReason R: The direction ratios of both lines are $(1, 2, 3)$ and $(2, 4, 6)$, so the lines are parallel, and the point $(1, 2, 3)$ lies on both lines.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "For the second line, setting parameter $t = -0.5$ gives $\\frac{1-2}{2} = \\frac{2-4}{4} = \\frac{3-6}{6} = -0.5$. Thus $(1, 2, 3)$ satisfies the second line equation. Since they have parallel direction vectors and share a point, the lines are coincident, which means the shortest distance between them is $0$. Both statements are true and Reason R explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The shortest distance between two skew lines is measured along a line perpendicular to both given lines.\nReason R: The cross product $\\vec{b}_1 \\times \\vec{b}_2$ of their direction vectors is perpendicular to both lines.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "The shortest distance between two skew lines is along the unique common perpendicular. The direction vector of this common perpendicular is given by $\\vec{b}_1 \\times \\vec{b}_2$, which is perpendicular to both $\\vec{b}_1$ and $\\vec{b}_2$. Both statements are true and Reason R explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Hard",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: If two lines are coplanar, the shortest distance between them is strictly zero.\nReason R: Two distinct parallel lines are coplanar but the shortest distance between them is non-zero.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 3,
    explanation: "Assertion A is false: Coplanar lines can be parallel and distinct, in which case the shortest distance between them is non-zero. Reason R correctly points out this counterexample. Hence Assertion A is false but Reason R is true.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The lines $\\vec{r} = (\\hat{i} + \\hat{j}) + \\lambda(\\hat{i} + 2\\hat{j} - \\hat{k})$ and $\\vec{r} = (\\hat{i} + \\hat{j}) + \\mu(-\\hat{i} - \\hat{j} + 2\\hat{k})$ intersect at the point $(1, 1, 0)$.\nReason R: Both lines pass through the point with position vector $\\hat{i} + \\hat{j}$ when $\\lambda = 0$ and $\\mu = 0$.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "For $\\lambda = 0$, the first line gives $\\hat{i} + \\hat{j}$. For $\\mu = 0$, the second line gives $\\hat{i} + \\hat{j}$. Thus, $(1, 1, 0)$ is a common point to both lines, so they intersect at $(1, 1, 0)$. Both statements are true and Reason R correctly explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The shortest distance formula $d = \\frac{|(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2)|}{|\\vec{b}_1 \\times \\vec{b}_2|}$ gives the length of the projection of $\\vec{a}_2 - \\vec{a}_1$ along $\\vec{b}_1 \\times \\vec{b}_2$.\nReason R: The projection of any vector $\\vec{v}$ along a unit vector $\\hat{n}$ is $|\\vec{v} \\cdot \\hat{n}|$.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "The unit vector along the common perpendicular is $\\hat{n} = \\frac{\\vec{b}_1 \\times \\vec{b}_2}{|\\vec{b}_1 \\times \\vec{b}_2|}$. The shortest distance is the projection of the segment connecting the two lines onto this common normal: $d = |(\\vec{a}_2 - \\vec{a}_1) \\cdot \\hat{n}| = \\frac{|(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2)|}{|\\vec{b}_1 \\times \\vec{b}_2|}$. Both statements are true and Reason R correctly explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The shortest distance between two parallel lines is zero.\nReason R: Two parallel lines in 3D never meet at any finite point unless they are coincident.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 3,
    explanation: "Assertion A is false: The shortest distance between distinct parallel lines is strictly positive ($d > 0$). Reason R is true since distinct parallel lines never meet. Thus Assertion A is false but Reason R is true.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Hard",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: If the lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-k}{1} = \\frac{y-4}{2} = \\frac{z-5}{3}$ intersect, then $k = 2$.\nReason R: The coplanarity condition $\\begin{vmatrix} k-1 & 2 & 2 \\\\ 2 & 3 & 4 \\\\ 1 & 2 & 3 \\end{vmatrix} = 0$ is satisfied when $k = 2$.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "Let us evaluate the determinant: $(x_2-x_1, y_2-y_1, z_2-z_1) = (k-1, 4-2, 5-3) = (k-1, 2, 2)$. The determinant is: $$\\begin{vmatrix} k-1 & 2 & 2 \\\\ 2 & 3 & 4 \\\\ 1 & 2 & 3 \\end{vmatrix} = (k-1)(9 - 8) - 2(6 - 4) + 2(4 - 3) = (k-1)(1) - 2(2) + 2(1) = k - 1 - 4 + 2 = k - 3$$. Wait! The determinant evaluates to $k - 3 = 0 \\implies k = 3$! If $k = 3$, the determinant is zero. For $k = 2$, the determinant is $2 - 3 = -1 \\neq 0$! Let us fix the statements so $k = 3$!",
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: If the lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-k}{1} = \\frac{y-4}{2} = \\frac{z-5}{3}$ intersect, then $k = 3$.\nReason R: The coplanarity condition $\\begin{vmatrix} k-1 & 2 & 2 \\\\ 2 & 3 & 4 \\\\ 1 & 2 & 3 \\end{vmatrix} = 0$ is satisfied when $k = 3$.\nIn the light of the above statements, choose the correct answer from the options given below:",
    correctAnswer: 0,
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The line segment of shortest distance between two skew lines is perpendicular to both lines.\nReason R: If a segment connecting two lines is not perpendicular to both, a shorter connecting segment can always be constructed.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "By variational calculus and Euclidean geometry, the minimum distance between two curves or lines occurs strictly along the common normal. If the segment were not perpendicular, projecting onto the perpendicular yields a strictly smaller length. Both statements are true and Reason R correctly explains Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "ASSERTION_REASON",
    questionType: "Assertion and Reason",
    marks: 4,
    negativeMarks: 1,
    question: "Given below are two statements: one is labelled as Assertion A and the other is labelled as Reason R.\nAssertion A: The distance between the skew lines $\\vec{r} = \\vec{a}_1 + \\lambda \\vec{b}_1$ and $\\vec{r} = \\vec{a}_2 + \\mu \\vec{b}_2$ remains unchanged if $\\vec{a}_1$ is replaced by any other point on the first line.\nReason R: Replacing $\\vec{a}_1$ by $\\vec{a}_1 + k\\vec{b}_1$ does not change $(\\vec{a}_2 - (\\vec{a}_1 + k\\vec{b}_1)) \\cdot (\\vec{b}_1 \\times \\vec{b}_2)$ because $\\vec{b}_1 \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 0$.\nIn the light of the above statements, choose the correct answer from the options given below:",
    options: [
      "Both Assertion A and Reason R are true and Reason R is the correct explanation of Assertion A.",
      "Both Assertion A and Reason R are true but Reason R is NOT the correct explanation of Assertion A.",
      "Assertion A is true but Reason R is false.",
      "Assertion A is false but Reason R is true."
    ],
    correctAnswer: 0,
    explanation: "Since $\\vec{b}_1 \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 0$, the term $k\\vec{b}_1 \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 0$, so the scalar triple product is completely invariant under the choice of point along either line. Both statements are true and Reason R provides the exact proof of Assertion A.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- NUMERICAL 21 to 30 ---
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the shortest distance between the lines $\\frac{x-1}{2} = \\frac{y-2}{3} = \\frac{z-3}{4}$ and $\\frac{x-2}{3} = \\frac{y-4}{4} = \\frac{z-5}{5}$ is $\\frac{1}{\\sqrt{k}}$, then the value of $k$ is:",
    options: [],
    correctAnswer: 6,
    explanation: "From the earlier calculation, $\\vec{a}_2 - \\vec{a}_1 = (1, 2, 2)$, $\\vec{b}_1 \\times \\vec{b}_2 = -\\hat{i} + 2\\hat{j} - \\hat{k}$ with magnitude $\\sqrt{(-1)^2 + 2^2 + (-1)^2} = \\sqrt{6}$. The scalar triple product is $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 1(-1) + 2(2) + 2(-1) = 1$. The shortest distance is $d = \\frac{1}{\\sqrt{6}}$. Comparing with $\\frac{1}{\\sqrt{k}}$, we get $k = 6$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "The shortest distance between the lines $\\vec{r} = (6\\hat{i} + 2\\hat{j} + 2\\hat{k}) + \\lambda(\\hat{i} - 2\\hat{j} + 2\\hat{k})$ and $\\vec{r} = (-4\\hat{i} - \\hat{k}) + \\mu(3\\hat{i} - 2\\hat{j} - 2\\hat{k})$ is equal to:",
    options: [],
    correctAnswer: 9,
    explanation: "As computed earlier: $\\vec{a}_2 - \\vec{a}_1 = -10\\hat{i} - 2\\hat{j} - 3\\hat{k}$, and $\\vec{b}_1 \\times \\vec{b}_2 = 8\\hat{i} + 8\\hat{j} + 4\\hat{k}$. The magnitude is $\\sqrt{64 + 64 + 16} = \\sqrt{144} = 12$. The scalar product is $(-10)(8) + (-2)(8) + (-3)(4) = -80 - 16 - 12 = -108$. Thus $d = \\frac{|-108|}{12} = 9$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Hard",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the shortest distance between the lines $\\frac{x-1}{2} = \\frac{y+1}{3} = \\frac{z-1}{4}$ and $\\frac{x-3}{1} = \\frac{y-k}{2} = \\frac{z}{1}$ is zero, then the value of $2k$ is:",
    options: [],
    correctAnswer: 9,
    explanation: "Two lines have a shortest distance of zero if and only if they intersect: $$\\begin{vmatrix} 3-1 & k+1 & 0-1 \\\\ 2 & 3 & 4 \\\\ 1 & 2 & 1 \\end{vmatrix} = 0 \\implies \\begin{vmatrix} 2 & k+1 & -1 \\\\ 2 & 3 & 4 \\\\ 1 & 2 & 1 \\end{vmatrix} = 0$$. Expanding along row 1: $$2(3 - 8) - (k+1)(2 - 4) - 1(4 - 3) = 0 \\implies 2(-5) + 2(k+1) - 1 = 0 \\implies -10 + 2k + 2 - 1 = 0 \\implies 2k - 9 = 0 \\implies 2k = 9$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the lines $\\vec{r} = (\\hat{i} - \\hat{j}) + \\lambda(2\\hat{i} + k\\hat{j})$ and $\\vec{r} = (2\\hat{i} - \\hat{j}) + \\mu(\\hat{i} + \\hat{j} - \\hat{k})$ intersect, then the value of $k$ is:",
    options: [],
    correctAnswer: -2,
    explanation: "Points are $\\vec{a}_1 = \\hat{i} - \\hat{j}$ and $\\vec{a}_2 = 2\\hat{i} - \\hat{j}$. Then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i}$. Direction vectors are $\\vec{b}_1 = (2, k, 0)$ and $\\vec{b}_2 = (1, 1, -1)$. The lines intersect if the scalar triple product $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 0$: $$\\begin{vmatrix} 1 & 0 & 0 \\\\ 2 & k & 0 \\\\ 1 & 1 & -1 \\end{vmatrix} = 1(-k - 0) = -k = 0 \\implies k = 0$$. If $k = 0$, then $-k = 0$. What if $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} + \\hat{j}$? If $\\vec{a}_2 = 2\\hat{i}$, then $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} + \\hat{j}$. Then determinant is: $\\begin{vmatrix} 1 & 1 & 0 \\\\ 2 & k & 0 \\\\ 1 & 1 & -1 \\end{vmatrix} = 1(-k) - 1(-2) = -k + 2 = 0 \\implies k = 2$! Let $\\vec{a}_2 = 2\\hat{i}$ and $\\vec{a}_1 = \\hat{i} - \\hat{j}$.",
    question: "If the lines $\\vec{r} = (\\hat{i} - \\hat{j}) + \\lambda(2\\hat{i} + k\\hat{j})$ and $\\vec{r} = (2\\hat{i}) + \\mu(\\hat{i} + \\hat{j} - \\hat{k})$ intersect, then the value of $k$ is:",
    correctAnswer: 2,
    explanation: "Here $\\vec{a}_1 = \\hat{i} - \\hat{j}$ and $\\vec{a}_2 = 2\\hat{i}$, so $\\vec{a}_2 - \\vec{a}_1 = \\hat{i} + \\hat{j} = (1, 1, 0)$. Direction vectors are $\\vec{b}_1 = (2, k, 0)$ and $\\vec{b}_2 = (1, 1, -1)$. The lines intersect if and only if: $$\\begin{vmatrix} 1 & 1 & 0 \\\\ 2 & k & 0 \\\\ 1 & 1 & -1 \\end{vmatrix} = 0 \\implies 1(-k - 0) - 1(-2 - 0) + 0 = 0 \\implies -k + 2 = 0 \\implies k = 2$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the shortest distance between the lines $\\frac{x+1}{7} = \\frac{y+1}{-6} = \\frac{z+1}{1}$ and $\\frac{x-3}{1} = \\frac{y-5}{-2} = \\frac{z-7}{1}$ is $d$, then the value of $d^2$ is:",
    options: [],
    correctAnswer: 116,
    explanation: "Earlier we computed that the shortest distance is $d = 2\\sqrt{29}$. Squaring both sides gives $d^2 = (2\\sqrt{29})^2 = 4 \\times 29 = 116$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Hard",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "The shortest distance between the lines $\\frac{x-3}{3} = \\frac{y-8}{-1} = \\frac{z-3}{1}$ and $\\frac{x+3}{-3} = \\frac{y+7}{2} = \\frac{z-6}{4}$ is $3\\sqrt{k}$. The value of $k$ is:",
    options: [],
    correctAnswer: 30,
    explanation: "Here $(x_1, y_1, z_1) = (3, 8, 3)$ and $(x_2, y_2, z_2) = (-3, -7, 6)$, so $\\vec{a}_2 - \\vec{a}_1 = (-6, -15, 3)$. Direction vectors: $\\vec{b}_1 = (3, -1, 1)$ and $\\vec{b}_2 = (-3, 2, 4)$. Compute $\\vec{b}_1 \\times \\vec{b}_2$: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 3 & -1 & 1 \\\\ -3 & 2 & 4 \\end{vmatrix} = \\hat{i}(-4 - 2) - \\hat{j}(12 - (-3)) + \\hat{k}(6 - 3) = -6\\hat{i} - 15\\hat{j} + 3\\hat{k}$$. Notice that $\\vec{a}_2 - \\vec{a}_1 = \\vec{b}_1 \\times \\vec{b}_2$! Thus $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = |\\vec{b}_1 \\times \\vec{b}_2|^2$. Therefore: $$d = \\frac{|\\vec{b}_1 \\times \\vec{b}_2|^2}{|\\vec{b}_1 \\times \\vec{b}_2|} = |\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-6)^2 + (-15)^2 + 3^2} = \\sqrt{36 + 225 + 9} = \\sqrt{270} = \\sqrt{9 \\times 30} = 3\\sqrt{30}$$. Comparing with $3\\sqrt{k}$, we get $k = 30$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the shortest distance between the lines $\\vec{r} = \\lambda(\\hat{i} + 2\\hat{j} + 3\\hat{k})$ and $\\vec{r} = (2\\hat{i} + 3\\hat{j} + 4\\hat{k}) + \\mu(2\\hat{i} + 4\\hat{j} + 5\\hat{k})$ is $\\frac{1}{\\sqrt{k}}$, then the value of $k$ is:",
    options: [],
    correctAnswer: 5,
    explanation: "Line 1 passes through $(0, 0, 0)$ with $\\vec{b}_1 = (1, 2, 3)$. Line 2 passes through $(2, 3, 4)$ with $\\vec{b}_2 = (2, 4, 5)$. Vector $\\vec{a}_2 - \\vec{a}_1 = (2, 3, 4)$. Compute $\\vec{b}_1 \\times \\vec{b}_2$: $$\\begin{vmatrix} \\hat{i} & \\hat{j} & \\hat{k} \\\\ 1 & 2 & 3 \\\\ 2 & 4 & 5 \\end{vmatrix} = \\hat{i}(10 - 12) - \\hat{j}(5 - 6) + \\hat{k}(4 - 4) = -2\\hat{i} + \\hat{j}$$. Magnitude $|\\vec{b}_1 \\times \\vec{b}_2| = \\sqrt{(-2)^2 + 1^2 + 0} = \\sqrt{4 + 1} = \\sqrt{5}$. Scalar product: $(\\vec{a}_2 - \\vec{a}_1) \\cdot (\\vec{b}_1 \\times \\vec{b}_2) = 2(-2) + 3(1) + 4(0) = -4 + 3 = -1$. Thus, $d = \\frac{|-1|}{\\sqrt{5}} = \\frac{1}{\\sqrt{5}}$. Comparing with $\\frac{1}{\\sqrt{k}}$, we have $k = 5$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the shortest distance between the lines $\\frac{x}{1} = \\frac{y}{0} = \\frac{z}{1}$ and $\\frac{x-1}{0} = \\frac{y-1}{1} = \\frac{z-1}{1}$ is $d$, then the value of $3d^2$ is:",
    options: [],
    correctAnswer: 1,
    explanation: "As computed earlier, the shortest distance is $d = \\frac{1}{\\sqrt{3}}$. Squaring both sides: $d^2 = \\frac{1}{3} \\implies 3d^2 = 1$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the lines $\\frac{x-1}{1} = \\frac{y-2}{2} = \\frac{z-3}{3}$ and $\\frac{x-2}{p} = \\frac{y-3}{1} = \\frac{z-4}{2}$ intersect each other, then the value of $p$ is:",
    options: [],
    correctAnswer: 0,
    explanation: "For intersecting lines: $$\\begin{vmatrix} 2-1 & 3-2 & 4-3 \\\\ 1 & 2 & 3 \\\\ p & 1 & 2 \\end{vmatrix} = 0 \\implies \\begin{vmatrix} 1 & 1 & 1 \\\\ 1 & 2 & 3 \\\\ p & 1 & 2 \\end{vmatrix} = 0$$. Expanding along row 3: $$p(3 - 2) - 1(3 - 1) + 2(2 - 1) = 0 \\implies p(1) - 1(2) + 2(1) = 0 \\implies p - 2 + 2 = 0 \\implies p = 0$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 12",
    chapter: "3D Geometry",
    subTopic: "Shortest distance between two skew lines",
    difficulty: "Medium",
    type: "NUMERICAL",
    questionType: "Numerical Value Question",
    marks: 4,
    negativeMarks: 0,
    question: "If the shortest distance between the $z$-axis and the line $x-1 = y = z$ is $d$, then the value of $2d^2$ is:",
    options: [],
    correctAnswer: 1,
    explanation: "As shown in earlier derivation, the shortest distance between the $z$-axis and the line $x-1 = y = z$ is $d = \\frac{1}{\\sqrt{2}}$. Therefore, $d^2 = \\frac{1}{2} \\implies 2d^2 = 1$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  }
];
