// Subtopic 4: Binomial identities (30 questions: 10 MCQ, 10 AR, 10 NUM)
module.exports = [
  // --- MCQ 1 to 10 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\binom{n}{0}^2 + \\binom{n}{1}^2 + \\binom{n}{2}^2 + \\dots + \\binom{n}{n}^2$ is equal to:",
    options: [
      "$\\binom{2n}{n}$",
      "$\\binom{2n}{n-1}$",
      "$2^{2n}$",
      "$2^{2n-1}$"
    ],
    correctAnswer: 0,
    explanation: "Consider the identity $(1+x)^n (x+1)^n = (1+x)^{2n}$. On the left-hand side: $$\\left(\\sum_{r=0}^n \\binom{n}{r} x^r\\right) \\left(\\sum_{s=0}^n \\binom{n}{s} x^{n-s}\\right)$$. The coefficient of $x^n$ is obtained when $r + (n-s) = n \\implies r = s$, which gives $\\sum_{r=0}^n \\binom{n}{r}^2$. On the right-hand side, the coefficient of $x^n$ in $(1+x)^{2n}$ is $\\binom{2n}{n}$. Thus, $\\sum_{r=0}^n \\binom{n}{r}^2 = \\binom{2n}{n}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of the sum $\\sum_{r=0}^{n} r \\binom{n}{r}$ is equal to:",
    options: [
      "$n 2^{n-1}$",
      "$n 2^n$",
      "$(n-1) 2^n$",
      "$(n+1) 2^{n-1}$"
    ],
    correctAnswer: 0,
    explanation: "Using the absorption identity $r \\binom{n}{r} = n \\binom{n-1}{r-1}$: $$\\sum_{r=1}^n r \\binom{n}{r} = \\sum_{r=1}^n n \\binom{n-1}{r-1} = n \\sum_{k=0}^{n-1} \\binom{n-1}{k} = n 2^{n-1}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\binom{n}{0} + \\binom{n+1}{1} + \\binom{n+2}{2} + \\dots + \\binom{n+k}{k}$ is:",
    options: [
      "$\\binom{n+k+1}{k}$",
      "$\\binom{n+k+1}{k+1}$",
      "$\\binom{n+k}{k+1}$",
      "$\\binom{n+k+2}{k}$"
    ],
    correctAnswer: 0,
    explanation: "By the hockey-stick (Chu-Shih-Chieh) identity: $$\\sum_{j=0}^k \\binom{n+j}{j} = \\sum_{j=0}^k \\binom{n+j}{n} = \\binom{n+k+1}{n+1} = \\binom{n+k+1}{k}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The sum $\\sum_{r=0}^{n} \\frac{\\binom{n}{r}}{r+1}$ is equal to:",
    options: [
      "$\\frac{2^{n+1} - 1}{n+1}$",
      "$\\frac{2^n - 1}{n+1}$",
      "$\\frac{2^{n+1}}{n+1}$",
      "$\\frac{2^n}{n+1}$"
    ],
    correctAnswer: 0,
    explanation: "Using the integration identity $\\frac{1}{r+1} \\binom{n}{r} = \\frac{1}{n+1} \\binom{n+1}{r+1}$: $$\\sum_{r=0}^n \\frac{\\binom{n}{r}}{r+1} = \\frac{1}{n+1} \\sum_{r=0}^n \\binom{n+1}{r+1} = \\frac{1}{n+1} \\left[\\sum_{k=0}^{n+1} \\binom{n+1}{k} - \\binom{n+1}{0}\\right] = \\frac{2^{n+1} - 1}{n+1}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\binom{20}{0} - \\binom{20}{1} + \\binom{20}{2} - \\dots + \\binom{20}{10}$ is:",
    options: [
      "$\\frac{1}{2} \\binom{20}{10}$",
      "$\\binom{20}{10}$",
      "$0$",
      "$- \\frac{1}{2} \\binom{20}{10}$"
    ],
    correctAnswer: 0,
    explanation: "We know that $(1 - 1)^{20} = 0 = \\sum_{r=0}^{20} (-1)^r \\binom{20}{r}$. Using symmetry $\\binom{20}{r} = \\binom{20}{20-r}$: $$\\sum_{r=0}^{20} (-1)^r \\binom{20}{r} = 2 \\left[\\binom{20}{0} - \\binom{20}{1} + \\dots - \\binom{20}{9}\\right] + \\binom{20}{10} = 0$$. Thus: $$\\binom{20}{0} - \\binom{20}{1} + \\dots - \\binom{20}{9} = -\\frac{1}{2} \\binom{20}{10}$$. Adding $\\binom{20}{10}$ to both sides: $$\\binom{20}{0} - \\binom{20}{1} + \\dots + \\binom{20}{10} = -\\frac{1}{2} \\binom{20}{10} + \\binom{20}{10} = \\frac{1}{2} \\binom{20}{10}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\sum_{r=1}^{n} r(r-1) \\binom{n}{r}$ is equal to:",
    options: [
      "$n(n-1) 2^{n-2}$",
      "$n(n-1) 2^{n-1}$",
      "$n^2 2^{n-2}$",
      "$n(n+1) 2^{n-2}$"
    ],
    correctAnswer: 0,
    explanation: "Using the identity $r(r-1) \\binom{n}{r} = n(n-1) \\binom{n-2}{r-2}$: $$\\sum_{r=2}^n r(r-1) \\binom{n}{r} = n(n-1) \\sum_{r=2}^n \\binom{n-2}{r-2} = n(n-1) 2^{n-2}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If $C_r = \\binom{n}{r}$, then the value of $C_0 C_1 + C_1 C_2 + C_2 C_3 + \\dots + C_{n-1} C_n$ is:",
    options: [
      "$\\binom{2n}{n-1}$",
      "$\\binom{2n}{n}$",
      "$\\binom{2n}{n+1}$",
      "$\\binom{2n-1}{n}$"
    ],
    correctAnswer: 0,
    explanation: "Consider the product $(1+x)^n (x+1)^n = (1+x)^{2n}$. $(1+x)^n = \\sum_{r=0}^n C_r x^r$ and $(x+1)^n = \\sum_{s=0}^n C_s x^{n-s}$. The coefficient of $x^{n-1}$ on the left-hand side is $\\sum_{s-r=1} C_r C_s = C_0 C_1 + C_1 C_2 + \\dots + C_{n-1} C_n$. On the right-hand side, the coefficient of $x^{n-1}$ in $(1+x)^{2n}$ is $\\binom{2n}{n-1}$. Hence, the sum equals $\\binom{2n}{n-1}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\binom{n}{0} - 2\\binom{n}{1} + 3\\binom{n}{2} - 4\\binom{n}{3} + \\dots + (-1)^n (n+1)\\binom{n}{n}$ for $n > 1$ is:",
    options: [
      "$0$",
      "$1$",
      "$-1$",
      "$(-1)^n$"
    ],
    correctAnswer: 0,
    explanation: "We write $\\sum_{r=0}^n (-1)^r (r+1) \\binom{n}{r} = \\sum_{r=0}^n (-1)^r r \\binom{n}{r} + \\sum_{r=0}^n (-1)^r \\binom{n}{r}$. Since $r \\binom{n}{r} = n \\binom{n-1}{r-1}$, the first sum is: $$-n \\sum_{r=1}^n (-1)^{r-1} \\binom{n-1}{r-1} = -n(1 - 1)^{n-1} = 0 \\quad (\\text{for } n > 1)$$. The second sum is $(1 - 1)^n = 0$. Hence, the total sum is $0 + 0 = 0$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "If $C_r = \\binom{n}{r}$, then the value of $\\frac{C_1}{C_0} + 2\\frac{C_2}{C_1} + 3\\frac{C_3}{C_2} + \\dots + n\\frac{C_n}{C_{n-1}}$ is:",
    options: [
      "$\\frac{n(n+1)}{2}$",
      "$\\frac{n(n-1)}{2}$",
      "$n^2$",
      "$\\frac{(n+1)^2}{2}$"
    ],
    correctAnswer: 0,
    explanation: "Using the ratio of consecutive binomial coefficients: $$\\frac{C_r}{C_{r-1}} = \\frac{n-r+1}{r}$$. Thus: $$r \\frac{C_r}{C_{r-1}} = r \\left(\\frac{n-r+1}{r}\\right) = n - r + 1$$. Summing from $r = 1$ to $n$: $$\\sum_{r=1}^n (n - r + 1) = n + (n-1) + (n-2) + \\dots + 1 = \\frac{n(n+1)}{2}$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "The value of $\\sum_{r=0}^{2n} (-1)^r \\binom{2n}{r}^2$ is equal to:",
    options: [
      "$(-1)^n \\binom{2n}{n}$",
      "$\\binom{2n}{n}$",
      "$0$",
      "$(-1)^n 2^{2n}$"
    ],
    correctAnswer: 0,
    explanation: "Consider $(1-x)^{2n} (1+x)^{2n} = (1-x^2)^{2n}$. Expanding: $$(1-x)^{2n} = \\sum_{r=0}^{2n} \\binom{2n}{r} (-1)^r x^r, \\quad (1+x)^{2n} = \\sum_{s=0}^{2n} \\binom{2n}{s} x^{2n-s}$$. The coefficient of $x^{2n}$ is $\\sum_{r=0}^{2n} (-1)^r \\binom{2n}{r}^2$. On the other hand, in $(1-x^2)^{2n} = \\sum_{k=0}^{2n} \\binom{2n}{k} (-1)^k x^{2k}$, the coefficient of $x^{2n}$ corresponds to $2k = 2n \\implies k = n$, which is $(-1)^n \\binom{2n}{n}$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- AR 11 to 20 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): For any positive integers $n$ and $r$ with $1 \\le r \\le n$, $\\binom{n}{r} + \\binom{n}{r-1} = \\binom{n+1}{r}$.\nReason (R): In Pascal's triangle, each entry is the sum of the two numbers directly above it.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Assertion (A) is Pascal's identity, which can be verified algebraically: $\\frac{n!}{r!(n-r)!} + \\frac{n!}{(r-1)!(n-r+1)!} = \\frac{(n+1)!}{r!(n+1-r)!} = \\binom{n+1}{r}$. Reason (R) describes this geometric rule of Pascal's triangle, which is generated by this exact algebraic relation. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The sum $\\sum_{r=0}^{n} \\binom{n}{r}^2 = \\binom{2n}{n}$.\nReason (R): By Vandermonde's convolution, $\\sum_{k=0}^r \\binom{m}{k}\\binom{n}{r-k} = \\binom{m+n}{r}$, and setting $m = n, r = n$ gives $\\sum_{k=0}^n \\binom{n}{k}^2 = \\binom{2n}{n}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Vandermonde's identity states that $\\sum_{k=0}^r \\binom{m}{k}\\binom{n}{r-k} = \\binom{m+n}{r}$. Taking $m=n$ and $r=n$, we get $\\sum_{k=0}^n \\binom{n}{k}\\binom{n}{n-k} = \\binom{2n}{n}$. Since $\\binom{n}{n-k} = \\binom{n}{k}$, this directly proves $\\sum_{k=0}^n \\binom{n}{k}^2 = \\binom{2n}{n}$. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): $\\sum_{r=1}^{n} r^2 \\binom{n}{r} = n(n+1) 2^{n-2}$.\nReason (R): $r^2 = r(r-1) + r$, and $\\sum_{r=1}^n r(r-1)\\binom{n}{r} = n(n-1)2^{n-2}$ while $\\sum_{r=1}^n r\\binom{n}{r} = n 2^{n-1}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Write $r^2 = r(r-1) + r$. Then: $$\\sum_{r=1}^n r^2 \\binom{n}{r} = \\sum_{r=2}^n r(r-1) \\binom{n}{r} + \\sum_{r=1}^n r \\binom{n}{r} = n(n-1) 2^{n-2} + n 2^{n-1} = n 2^{n-2} [(n-1) + 2] = n(n+1) 2^{n-2}$$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): For any natural number $n$, $\\binom{n}{0} - \\binom{n}{1} + \\binom{n}{2} - \\dots + (-1)^n \\binom{n}{n} = 0$.\nReason (R): Setting $x = -1$ in the expansion of $(1+x)^n = \\sum_{r=0}^n \\binom{n}{r} x^r$ yields $(1-1)^n = 0$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Substituting $x = -1$ into $(1+x)^n = \\sum_{r=0}^n \\binom{n}{r} x^r$ gives $(1 - 1)^n = \\sum_{r=0}^n (-1)^r \\binom{n}{r} = 0$ for all $n \\ge 1$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): If $C_r = \\binom{n}{r}$, then $C_0 + 2C_1 + 3C_2 + \\dots + (n+1)C_n = (n+2) 2^{n-1}$.\nReason (R): $\\sum_{r=0}^n (r+1) C_r = \\sum_{r=0}^n r C_r + \\sum_{r=0}^n C_r = n 2^{n-1} + 2^n = (n+2) 2^{n-1}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "We break the sum into $\\sum_{r=0}^n r C_r + \\sum_{r=0}^n C_r$. Since $\\sum r C_r = n 2^{n-1}$ and $\\sum C_r = 2^n = 2 \\cdot 2^{n-1}$, the total sum is $n 2^{n-1} + 2 \\cdot 2^{n-1} = (n+2) 2^{n-1}$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The value of $\\binom{n}{r} / \\binom{n}{r-1} = \\frac{n-r+1}{r}$.\nReason (R): Binomial coefficients satisfy the absorption formula $\\binom{n}{r} = \\frac{n}{r} \\binom{n-1}{r-1}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 1,
    explanation: "Assertion (A) is the formula for the ratio of consecutive coefficients: $\\frac{n!}{r!(n-r)!} \\times \\frac{(r-1)!(n-r+1)!}{n!} = \\frac{n-r+1}{r}$, which is true. Reason (R) is also a correct standard absorption formula $\\binom{n}{r} = \\frac{n}{r}\\binom{n-1}{r-1}$, but it expresses a reduction in both $n$ and $r$, rather than directly evaluating the ratio $\\binom{n}{r}/\\binom{n}{r-1}$. Both are true, but (R) is not the direct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): For any natural number $n$, $\\sum_{r=0}^{n} (-1)^r \\frac{\\binom{n}{r}}{r+1} = \\frac{1}{n+1}$.\nReason (R): $\\int_0^1 (1-x)^n dx = \\left[-\\frac{(1-x)^{n+1}}{n+1}\\right]_0^1 = \\frac{1}{n+1}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "Expanding $(1-x)^n = \\sum_{r=0}^n \\binom{n}{r} (-1)^r x^r$. Integrating term by term from $0$ to $1$: $$\\int_0^1 (1-x)^n dx = \\sum_{r=0}^n (-1)^r \\binom{n}{r} \\int_0^1 x^r dx = \\sum_{r=0}^n (-1)^r \\frac{\\binom{n}{r}}{r+1}$$. Directly evaluating the integral gives $\\frac{1}{n+1}$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): The sum $\\binom{10}{1} + \\binom{10}{2} + \\dots + \\binom{10}{10} = 1023$.\nReason (R): The total sum of all binomial coefficients for index $n$ is $\\sum_{r=0}^n \\binom{n}{r} = 2^n$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "We know $\\sum_{r=0}^{10} \\binom{10}{r} = 2^{10} = 1024$. Excluding $\\binom{10}{0} = 1$: $\\sum_{r=1}^{10} \\binom{10}{r} = 1024 - 1 = 1023$. Both (A) and (R) are true and (R) is the correct explanation of (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): $\\sum_{r=0}^{n} r \\binom{n}{r}^2 = n \\binom{2n-1}{n-1}$.\nReason (R): Using $r \\binom{n}{r} = n \\binom{n-1}{r-1}$, the sum transforms to $n \\sum_{r=1}^n \\binom{n-1}{r-1} \\binom{n}{n-r} = n \\binom{2n-1}{n-1}$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "We have: $$\\sum_{r=1}^n r \\binom{n}{r}^2 = \\sum_{r=1}^n n \\binom{n-1}{r-1} \\binom{n}{r} = n \\sum_{r=1}^n \\binom{n-1}{r-1} \\binom{n}{n-r}$$. By Vandermonde's convolution, $\\sum_{r=1}^n \\binom{n-1}{r-1} \\binom{n}{n-r} = \\binom{(n-1) + n}{(r-1) + (n-r)} = \\binom{2n-1}{n-1}$. Thus, the sum equals $n \\binom{2n-1}{n-1}$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "MCQ",
    questionType: "MCQ (Multiple Choice Question)",
    marks: 4,
    negativeMarks: 1,
    question: "Assertion (A): In the expansion of $(1+x)^n$, the sum of coefficients at odd positions equals the sum of coefficients at even positions.\nReason (R): Substituting $x = -1$ into $(1+x)^n = \\sum_{r=0}^n \\binom{n}{r} x^r$ gives $(C_0 + C_2 + C_4 + \\dots) - (C_1 + C_3 + C_5 + \\dots) = 0$.",
    options: [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    correctAnswer: 0,
    explanation: "At $x = -1$, $(1-1)^n = 0 \\implies C_0 - C_1 + C_2 - C_3 + \\dots = 0 \\implies C_0 + C_2 + C_4 + \\dots = C_1 + C_3 + C_5 + \\dots = 2^{n-1}$. Both (A) and (R) are true and (R) correctly explains (A).",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },

  // --- NUM 21 to 30 ---
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=0}^{5} \\binom{5}{r}^2 = k$, then find the value of $k$.",
    options: [],
    correctAnswer: 252,
    explanation: "Using the identity $\\sum_{r=0}^n \\binom{n}{r}^2 = \\binom{2n}{n}$ with $n = 5$: $$k = \\binom{10}{5} = \\frac{10 \\times 9 \\times 8 \\times 7 \\times 6}{120} = 252$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Evaluate the sum $\\binom{5}{0} + \\binom{6}{1} + \\binom{7}{2} + \\binom{8}{3} + \\binom{9}{4} + \\binom{10}{5}$.",
    options: [],
    correctAnswer: 462,
    explanation: "By the hockey-stick identity: $$\\sum_{j=0}^5 \\binom{5+j}{j} = \\binom{5+5+1}{5} = \\binom{11}{5}$$. Calculating $\\binom{11}{5} = \\frac{11 \\times 10 \\times 9 \\times 8 \\times 7}{120} = 462$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=1}^{6} r \\binom{6}{r} = M$, find the value of $M$.",
    options: [],
    correctAnswer: 192,
    explanation: "Using the identity $\\sum_{r=1}^n r \\binom{n}{r} = n 2^{n-1}$ with $n = 6$: $$M = 6 \\times 2^{6-1} = 6 \\times 2^5 = 6 \\times 32 = 192$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=0}^{4} \\frac{\\binom{4}{r}}{r+1} = \\frac{p}{q}$ where $\\gcd(p, q) = 1$, find the value of $p - q$.",
    options: [],
    correctAnswer: 26,
    explanation: "Using $\\sum_{r=0}^n \\frac{\\binom{n}{r}}{r+1} = \\frac{2^{n+1} - 1}{n+1}$ with $n = 4$: $$\\frac{2^{4+1} - 1}{4+1} = \\frac{32 - 1}{5} = \\frac{31}{5}$$. Here $p = 31, q = 5$, and $\\gcd(31, 5) = 1$. Thus, $p - q = 31 - 5 = 26$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $C_r = \\binom{n}{r}$ and $C_0 + 2C_1 + 3C_2 + \\dots + (n+1)C_n = 576$, find the value of $n$.",
    options: [],
    correctAnswer: 7,
    explanation: "We know that $\\sum_{r=0}^n (r+1) \\binom{n}{r} = (n+2) 2^{n-1}$. We are given $(n+2) 2^{n-1} = 576$. For $n = 7$: $(7+2) 2^{7-1} = 9 \\times 2^6 = 9 \\times 64 = 576$. Thus, $n = 7$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\sum_{r=1}^{n} r \\binom{n}{r} = 112$, then find the value of $n$.",
    options: [],
    correctAnswer: 7,
    explanation: "We know that $\\sum_{r=1}^n r \\binom{n}{r} = n 2^{n-1}$. Given $n 2^{n-1} = 112$: Since $112 = 7 \\times 16 = 7 \\times 2^4 = 7 \\times 2^{7-1}$, by inspection $n = 7$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Evaluate the sum $\\binom{15}{1} - 2\\binom{15}{2} + 3\\binom{15}{3} - \\dots - 14\\binom{15}{14} + 15\\binom{15}{15}$.",
    options: [],
    correctAnswer: 0,
    explanation: "We evaluate $\\sum_{r=1}^{15} (-1)^{r-1} r \\binom{15}{r}$. Using $r \\binom{15}{r} = 15 \\binom{14}{r-1}$: $$\\sum_{r=1}^{15} (-1)^{r-1} 15 \\binom{14}{r-1} = 15 \\sum_{k=0}^{14} (-1)^k \\binom{14}{k} = 15 (1 - 1)^{14} = 15(0) = 0$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "If $\\frac{\\binom{n}{r}}{\\binom{n}{r-1}} = 3$ and $\\frac{\\binom{n}{r+1}}{\\binom{n}{r}} = 2$, find the value of $n$.",
    options: [],
    correctAnswer: 11,
    explanation: "Using $\\frac{\\binom{n}{k}}{\\binom{n}{k-1}} = \\frac{n-k+1}{k}$: 1) $\\frac{n-r+1}{r} = 3 \\implies n - r + 1 = 3r \\implies n + 1 = 4r$. 2) $\\frac{n-r}{r+1} = 2 \\implies n - r = 2r + 2 \\implies n - 2 = 3r$. Subtracting gives: $(n+1) - (n-2) = 4r - 3r \\implies r = 3$. Then $n + 1 = 4(3) = 12 \\implies n = 11$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Find the value of the sum $\\sum_{r=1}^{5} r^2 \\binom{5}{r}$.",
    options: [],
    correctAnswer: 240,
    explanation: "Using the standard identity $\\sum_{r=1}^n r^2 \\binom{n}{r} = n(n+1) 2^{n-2}$ with $n = 5$: $$5(5+1) 2^{5-2} = 5 \\times 6 \\times 2^3 = 30 \\times 8 = 240$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  },
  {
    subject: "Mathematics",
    class: "Class 11",
    chapter: "Binomial Theorem",
    subTopic: "Binomial identities",
    difficulty: "Medium",
    type: "Numerical",
    questionType: "Numerical",
    marks: 4,
    negativeMarks: 0,
    question: "Evaluate the sum $\\sum_{r=1}^{4} r \\frac{\\binom{4}{r}}{\\binom{4}{r-1}}$.",
    options: [],
    correctAnswer: 10,
    explanation: "Using the identity $r \\frac{\\binom{n}{r}}{\\binom{n}{r-1}} = n - r + 1$: For $n = 4$: $$\\sum_{r=1}^4 (4 - r + 1) = \\sum_{r=1}^4 (5 - r) = 4 + 3 + 2 + 1 = 10$$.",
    source: "JEE Main 10-Year Advanced Pattern Generator"
  }
];
