module.exports = [
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electrostatic field lines can never form closed loops.\nReason (R): The electrostatic force is strictly conservative, which requires the line integral of electric field around any closed path to be zero: $\\oint \\vec{E}\\cdot d\\vec{r} = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "If electric field lines formed closed loops, integrating $\\vec{E}\\cdot d\\vec{r}$ along a loop would yield a non-zero value, violating the conservative nature of electrostatics (Faraday's law with zero time-varying magnetic field: $\\vec{\\nabla}\\times\\vec{E} = 0$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Two electric field lines can never intersect each other.\nReason (R): If two field lines intersected at a point, there would be two different tangents at that point, implying two different directions of the net electric field simultaneously, which is impossible.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the electric field at any spatial coordinate is uniquely defined as a single vector resultant, field lines cannot cross. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field on the axis of a uniformly charged thin ring of radius $R$ and total charge $q$ attains a maximum value at $x = \\frac{R}{\\sqrt{2}}$.\nReason (R): Differentiating the axial field $E(x) = \\frac{kq x}{(x^2 + R^2)^{3/2}}$ with respect to $x$ and setting $\\frac{dE}{dx} = 0$ yields $x^2 + R^2 - 3x^2 = 0 \\implies x = \\frac{R}{\\sqrt{2}}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Setting $\\frac{dE}{dx} = 0$ directly gives $R^2 - 2x^2 = 0 \\implies x = \\frac{R}{\\sqrt{2}}$, where $E_{max} = \\frac{2kq}{3\\sqrt{3}R^2}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field at the exact center of a uniformly charged circular ring is zero.\nReason (R): By circular symmetry, diametrically opposite charge elements $dq$ produce electric fields of equal magnitude and opposing direction that cancel vectorially at the center.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "At $x = 0$, substituting into $E(x) = \\frac{kq x}{(x^2 + R^2)^{3/2}}$ yields $E(0) = 0$. By symmetry, all diametric contributions cancel out. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field due to an infinite uniformly charged thin planar sheet is independent of the distance from the sheet.\nReason (R): Gauss's law applied to a cylindrical pillbox perpendicular to the infinite sheet of surface charge density $\\sigma$ gives $2EA = \\frac{\\sigma A}{\\varepsilon_0} \\implies E = \\frac{\\sigma}{2\\varepsilon_0}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the sheet is infinite in extent, field lines emerge purely normal to the plane without spreading, maintaining constant field strength $E = \\frac{\\sigma}{2\\varepsilon_0}$ at all distances. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field just outside the surface of a charged conductor of arbitrary shape in electrostatic equilibrium is $E = \\frac{\\sigma}{\\varepsilon_0}$ directed normal to the surface.\nReason (R): Inside the conductor, the electric field is zero, so a Gaussian pillbox spanning the conducting surface has non-zero electric flux only through its outer face: $EA = \\frac{\\sigma A}{\\varepsilon_0} \\implies E = \\frac{\\sigma}{\\varepsilon_0}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $E_{inside} = 0$, only the outer surface of the pillbox contributes to flux, yielding $E = \\frac{\\sigma}{\\varepsilon_0}$ (twice the field of a non-conducting sheet). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field due to an infinitely long straight wire carrying uniform linear charge density $\\lambda$ varies inversely as the distance $r$ from the wire: $E = \\frac{\\lambda}{2\\pi\\varepsilon_0 r}$.\nReason (R): Applying Gauss's law to a coaxial cylindrical surface of radius $r$ and length $L$ yields $E(2\\pi r L) = \\frac{\\lambda L}{\\varepsilon_0} \\implies E = \\frac{\\lambda}{2\\pi\\varepsilon_0 r}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By cylindrical symmetry, flux through end caps is zero, leaving curved surface flux $E(2\\pi r L) = \\frac{\\lambda L}{\\varepsilon_0}$, which proves $E \\propto 1/r$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric flux through a planar area $\\vec{A}$ placed in a uniform electric field $\\vec{E}$ is given by $\\Phi_E = \\vec{E} \\cdot \\vec{A} = EA\\cos\\theta$.\nReason (R): Electric flux represents the number of electric field lines crossing an area and is proportional to the component of the electric field perpendicular to the surface.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "By definition, $\\Phi_E = \\iint \\vec{E}\\cdot d\\vec{A} = EA\\cos\\theta$, where $\\theta$ is the angle between $\\vec{E}$ and the surface normal vector $\\vec{A}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If a charged particle is projected perpendicular to a uniform electric field, its trajectory is a parabola.\nReason (R): The particle experiences constant acceleration in the direction of the field while maintaining constant velocity in the perpendicular direction, exactly analogous to projectile motion under gravity.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Horizontal velocity is $v_x = v_0$ (constant) and vertical displacement is $y = \\frac{1}{2}a_y t^2 = \\frac{1}{2}\\left(\\frac{qE}{m}\\right)\\left(\\frac{x}{v_0}\\right)^2 \\propto x^2$, which represents a parabolic path. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A charged oil droplet of mass $m$ carrying charge $q$ can be held stationary in air by an upward electric field of magnitude $E = \\frac{mg}{q}$.\nReason (R): For the droplet to remain stationary, the upward electrostatic force $qE$ must exactly balance the downward gravitational force $mg$: $qE = mg$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Equating upward electric force $qE$ to downward weight $mg$ yields $E = \\frac{mg}{q}$, the operating principle of Millikan's oil drop experiment. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electric field lines are always perpendicular to the surface of a charged conductor in electrostatic equilibrium.\nReason (R): If there were a tangential component of the electric field along the conducting surface, free electrons would experience a force and accelerate, violating the state of electrostatic equilibrium.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "In electrostatic equilibrium, surface currents must be zero ($J_t = 0$), which requires the tangential electric field to vanish identically ($E_t = 0$), so $\\vec{E}$ is purely normal. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electric field lines start on positive charges and end on negative charges.\nReason (R): By Coulomb's law, a positive test charge experiences repulsion away from positive charges and attraction towards negative charges.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Field lines map the trajectory tangent to force on a positive test charge, naturally emanating from positive sources and terminating on negative sinks. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field inside a hollow charged conductor of any arbitrary shape containing no internal charges is identically zero.\nReason (R): Electrostatic shielding occurs because all excess charges reside exclusively on the outer surface of the conductor, and Gauss's law over any interior surface enclosed by the conductor yields $Q_{enc} = 0$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Faraday cage effect: no electric field can penetrate a hollow cavity inside a conductor, shielding interior regions from external electric fields. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The SI unit of electric flux is $\\text{N}\\cdot\\text{m}^2/\\text{C}$ or equivalently $\\text{V}\\cdot\\text{m}$.\nReason (R): Electric flux is defined as $\\Phi_E = \\int \\vec{E}\\cdot d\\vec{A}$, where electric field has units of $\\text{N/C}$ or $\\text{V/m}$, giving units $[E][A] = (\\text{V/m})(\\text{m}^2) = \\text{V}\\cdot\\text{m}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Both dimensional forms are identical: $\\frac{\\text{N}\\cdot\\text{m}^2}{\\text{C}} = \\frac{\\text{J}\\cdot\\text{m}}{\\text{C}} = \\text{V}\\cdot\\text{m}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The density of electric field lines in a region is directly proportional to the magnitude of the electric field in that region.\nReason (R): By geometric construction, the number of field lines crossing unit cross-sectional area perpendicular to the lines represents the field intensity $E$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Crowded field lines indicate strong electric field; sparse field lines indicate weak electric field. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric flux through a closed surface containing a net charge of $1\\text{ C}$ in vacuum is $\\frac{1}{\\varepsilon_0} \\approx 1.13 \\times 10^{11}\\text{ N}\\cdot\\text{m}^2/\\text{C}$.\nReason (R): Gauss's law states that $\\Phi_E = \\frac{Q_{enclosed}}{\\varepsilon_0} = \\frac{1}{8.854 \\times 10^{-12}} \\approx 1.13 \\times 10^{11}\\text{ V}\\cdot\\text{m}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Evaluating $\\frac{1}{8.854 \\times 10^{-12}}$ gives $1.129 \\times 10^{11}\\text{ V}\\cdot\\text{m}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): An electron and a proton released from rest in the same uniform electric field experience equal acceleration.\nReason (R): The force on a charge in an electric field depends solely on its charge: $F = qE$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: while both experience the same force magnitude ($eE$), the electron has a much smaller mass than the proton ($m_p \\approx 1836 m_e$), so the electron's acceleration $a_e = eE/m_e$ is $\\approx 1836$ times greater than the proton's acceleration. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electric field is a vector quantity while electric flux is a scalar quantity.\nReason (R): Electric field has both magnitude and direction, whereas electric flux is defined by the dot product of electric field and area vector: $\\Phi_E = \\vec{E}\\cdot\\vec{A}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The scalar dot product of two vectors yields a scalar quantity (flux). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): A charged particle placed in an electric field always moves along the electric field line.\nReason (R): The electric field line gives the direction of the acceleration of the charged particle, not necessarily its velocity.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: a particle moves along field lines only if it starts from rest in straight field lines; in curved field lines or with initial transverse velocity, inertia causes velocity to diverge from the field lines. Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field of a dipole at large distance falls off faster than the electric field of a point charge.\nReason (R): A point charge field falls off as $\\frac{1}{r^2}$, whereas a dipole field falls off as $\\frac{1}{r^3}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because opposite charges partially cancel in the far field, the dipole field decreases as $1/r^3$, which decays more rapidly than the monopole $1/r^2$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The total electric flux passing through a closed surface is independent of the size and shape of the surface.\nReason (R): By Gauss's law, the total electric flux depends only on the total net charge enclosed inside the surface: $\\Phi_E = \\frac{Q_{enclosed}}{\\varepsilon_0}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Regardless of geometry or surface area, enclosing the same net charge $Q$ yields the same total flux $\\frac{Q}{\\varepsilon_0}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): If the electric flux through a closed Gaussian surface is zero, the electric field must be zero everywhere on the surface.\nReason (R): Electric flux through a closed surface is given by $\\oint \\vec{E}\\cdot d\\vec{A}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Assertion is false: net flux is zero if net enclosed charge is zero (for example, a uniform field entering one side and leaving the other has $\\Phi_E = 0$ while $E \\ne 0$). Reason is true.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Near a sharp conducting point, the electric field is extremely intense.\nReason (R): The surface charge density on a charged conductor is inversely proportional to its local radius of curvature: $\\sigma \\propto \\frac{1}{R}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $V = \\text{constant}$ across a conductor, local charge density $\\sigma \\propto 1/R$. Sharp points have very small $R$, leading to very large $\\sigma$ and electric field $E = \\frac{\\sigma}{\\varepsilon_0}$, causing corona discharge. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric field intensity between two infinitely large parallel conducting plates carrying equal and opposite surface charge densities $+\\sigma$ and $-\\sigma$ is $\\frac{\\sigma}{\\varepsilon_0}$.\nReason (R): The fields produced by the two plates point in the same direction between the plates, adding constructively: $E = \\frac{\\sigma}{2\\varepsilon_0} + \\frac{\\sigma}{2\\varepsilon_0} = \\frac{\\sigma}{\\varepsilon_0}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Between the plates, positive sheet pushes right and negative sheet pulls right, adding up to $E = \\frac{\\sigma}{\\varepsilon_0}$. Outside, they cancel to zero. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): Electric field lines never cross a conductor in electrostatic equilibrium.\nReason (R): Inside a conductor in electrostatic equilibrium, mobile charges cancel all internal fields, making $\\vec{E} = 0$ everywhere within the conducting material.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\vec{E} = 0$ inside a conductor, no electric field lines exist within the bulk of the conducting material. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Given below are two statements: one is labelled as Assertion (A) and the other is labelled as Reason (R).\nAssertion (A): The electric flux through a flat circular loop of radius $R$ oriented perpendicular to a uniform electric field $E$ is $\\pi R^2 E$.\nReason (R): When the surface is perpendicular to $\\vec{E}$, the normal vector is parallel to $\\vec{E}$ ($\\theta = 0^\\circ$), so $\\Phi_E = EA\\cos 0^\\circ = E(\\pi R^2)$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$\\Phi_E = \\vec{E}\\cdot\\vec{A} = EA = E(\\pi R^2)$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion–Reasoning",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $m = 10^{-6}\\text{ kg}$ and charge $q = 2\\mu\\text{C}$ is released from rest in a uniform electric field $E = 500\\text{ V/m}$. The velocity of the particle after travelling a distance of $0.002\\text{ m}$ is:",
    "options": [
      "$2\\text{ m/s}$",
      "$1\\text{ m/s}$",
      "$4\\text{ m/s}$",
      "$0.5\\text{ m/s}$"
    ],
    "correctAnswer": 0,
    "explanation": "Acceleration is $a = \\frac{qE}{m} = \\frac{(2 \\times 10^{-6}\\text{ C})(500\\text{ V/m})}{10^{-6}\\text{ kg}} = 1000\\text{ m/s}^2$. Using $v^2 = u^2 + 2as = 0 + 2(1000)(0.002) = 4 \\implies v = 2\\text{ m/s}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A circular ring of radius $R = 10\\text{ cm}$ carries a uniform positive charge $Q$. At what distance $x$ from the center of the ring along its axis does the electric field have its maximum value?",
    "options": [
      "$\\frac{10}{\\sqrt{2}}\\text{ cm}$",
      "$10\\sqrt{2}\\text{ cm}$",
      "$5\\text{ cm}$",
      "$10\\text{ cm}$"
    ],
    "correctAnswer": 0,
    "explanation": "The axial field of a ring is $E(x) = \\frac{kQx}{(x^2 + R^2)^{3/2}}$. Maximum field occurs at $x = \\frac{R}{\\sqrt{2}} = \\frac{10}{\\sqrt{2}}\\text{ cm}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An infinite line charge produces an electric field of $9 \\times 10^4\\text{ N/C}$ at a radial distance of $2\\text{ cm}$. The linear charge density $\\lambda$ is (take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$):",
    "options": [
      "$0.1\\mu\\text{C/m}$",
      "$1\\mu\\text{C/m}$",
      "$0.01\\mu\\text{C/m}$",
      "$0.2\\mu\\text{C/m}$"
    ],
    "correctAnswer": 0,
    "explanation": "$E = \\frac{2k\\lambda}{r} \\implies \\lambda = \\frac{E r}{2k} = \\frac{(9 \\times 10^4)(0.02)}{2(9 \\times 10^9)} = \\frac{1.8 \\times 10^3}{18 \\times 10^9} = 10^{-7}\\text{ C/m} = 0.1\\mu\\text{C/m}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A uniform electric field $\\vec{E} = 3 \\times 10^3\\hat{i}\\text{ N/C}$ passes through a square of side $10\\text{ cm}$ whose plane is parallel to the $yz$-plane. The electric flux through the square is:",
    "options": [
      "$30\\text{ N}\\cdot\\text{m}^2/\\text{C}$",
      "$300\\text{ N}\\cdot\\text{m}^2/\\text{C}$",
      "$3\\text{ N}\\cdot\\text{m}^2/\\text{C}$",
      "$0$"
    ],
    "correctAnswer": 0,
    "explanation": "The area vector is normal to the $yz$-plane, so $\\vec{A} = (0.1)^2\\hat{i} = 0.01\\hat{i}\\text{ m}^2$. Flux is $\\Phi_E = \\vec{E}\\cdot\\vec{A} = (3 \\times 10^3)(0.01) = 30\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In the previous question, if the normal to the plane of the square makes an angle of $60^\\circ$ with the $x$-axis, the electric flux through the square is:",
    "options": [
      "$15\\text{ N}\\cdot\\text{m}^2/\\text{C}$",
      "$30\\text{ N}\\cdot\\text{m}^2/\\text{C}$",
      "$15\\sqrt{3}\\text{ N}\\cdot\\text{m}^2/\\text{C}$",
      "$0$"
    ],
    "correctAnswer": 0,
    "explanation": "$\\Phi_E = EA\\cos 60^\\circ = 30 \\times 0.5 = 15\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A charged water drop of radius $0.1\\text{ mm}$ is suspended stationary in air in a downward electric field of $400\\text{ V/m}$. If density of water is $1000\\text{ kg/m}^3$ and $g = 10\\text{ m/s}^2$, the charge on the drop must be:",
    "options": [
      "Negative",
      "Positive",
      "Zero",
      "Cannot be determined"
    ],
    "correctAnswer": 0,
    "explanation": "Gravity pulls the droplet downwards. To balance gravity, the electrostatic force $\\vec{F} = q\\vec{E}$ must point upwards. Since the electric field $\\vec{E}$ is directed downwards, the charge $q$ must be negative so that $\\vec{F} = q\\vec{E}$ is directed opposite to the field (upward).",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The electric field intensity near a large conducting plate carrying surface charge density $\\sigma$ is:",
    "options": [
      "$\\frac{\\sigma}{\\varepsilon_0}$",
      "$\\frac{\\sigma}{2\\varepsilon_0}$",
      "$\\frac{2\\sigma}{\\varepsilon_0}$",
      "$\\frac{\\sigma}{4\\varepsilon_0}$"
    ],
    "correctAnswer": 0,
    "explanation": "For a conducting surface, the electric field inside the conductor is zero, so by Gauss's law, the electric field just outside is $E = \\frac{\\sigma}{\\varepsilon_0}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A uniform electric field of $\\vec{E} = (1000\\hat{i})\\text{ N/C}$ passes through a square surface of area $A = 0.04\\text{ m}^2$ whose normal is aligned along the $+x$-axis. Find the electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) through the square.",
    "options": [],
    "correctAnswer": 40,
    "numericalAnswer": 40,
    "explanation": "$\\Phi_E = \\vec{E}\\cdot\\vec{A} = (1000\\text{ N/C})(0.04\\text{ m}^2) = 40\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A uniform electric field of $\\vec{E} = (2000\\hat{i})\\text{ N/C}$ passes through a square surface of area $A = 0.04\\text{ m}^2$ whose normal is aligned along the $+x$-axis. Find the electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) through the square.",
    "options": [],
    "correctAnswer": 80,
    "numericalAnswer": 80,
    "explanation": "$\\Phi_E = \\vec{E}\\cdot\\vec{A} = (2000\\text{ N/C})(0.04\\text{ m}^2) = 80\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A uniform electric field of $\\vec{E} = (3000\\hat{i})\\text{ N/C}$ passes through a square surface of area $A = 0.04\\text{ m}^2$ whose normal is aligned along the $+x$-axis. Find the electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) through the square.",
    "options": [],
    "correctAnswer": 120,
    "numericalAnswer": 120,
    "explanation": "$\\Phi_E = \\vec{E}\\cdot\\vec{A} = (3000\\text{ N/C})(0.04\\text{ m}^2) = 120\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A uniform electric field of $\\vec{E} = (4000\\hat{i})\\text{ N/C}$ passes through a square surface of area $A = 0.04\\text{ m}^2$ whose normal is aligned along the $+x$-axis. Find the electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) through the square.",
    "options": [],
    "correctAnswer": 160,
    "numericalAnswer": 160,
    "explanation": "$\\Phi_E = \\vec{E}\\cdot\\vec{A} = (4000\\text{ N/C})(0.04\\text{ m}^2) = 160\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A uniform electric field of $\\vec{E} = (5000\\hat{i})\\text{ N/C}$ passes through a square surface of area $A = 0.04\\text{ m}^2$ whose normal is aligned along the $+x$-axis. Find the electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) through the square.",
    "options": [],
    "correctAnswer": 200,
    "numericalAnswer": 200,
    "explanation": "$\\Phi_E = \\vec{E}\\cdot\\vec{A} = (5000\\text{ N/C})(0.04\\text{ m}^2) = 200\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Calculate the electric field magnitude $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from a point charge $q = 1\\mu\\text{C}$ in vacuum. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$E = \\frac{kq}{r^2} = \\frac{(9 \\times 10^9)(1 \\times 10^{-6})}{(0.3)^2} = \\frac{9000}{0.09} = 100000\\text{ V/m} = 100\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Calculate the electric field magnitude $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from a point charge $q = 2\\mu\\text{C}$ in vacuum. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 200,
    "numericalAnswer": 200,
    "explanation": "$E = \\frac{kq}{r^2} = \\frac{(9 \\times 10^9)(2 \\times 10^{-6})}{(0.3)^2} = \\frac{18000}{0.09} = 200000\\text{ V/m} = 200\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Calculate the electric field magnitude $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from a point charge $q = 3\\mu\\text{C}$ in vacuum. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 300,
    "numericalAnswer": 300,
    "explanation": "$E = \\frac{kq}{r^2} = \\frac{(9 \\times 10^9)(3 \\times 10^{-6})}{(0.3)^2} = \\frac{27000}{0.09} = 300000\\text{ V/m} = 300\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Calculate the electric field magnitude $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from a point charge $q = 4\\mu\\text{C}$ in vacuum. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 400,
    "numericalAnswer": 400,
    "explanation": "$E = \\frac{kq}{r^2} = \\frac{(9 \\times 10^9)(4 \\times 10^{-6})}{(0.3)^2} = \\frac{36000}{0.09} = 400000\\text{ V/m} = 400\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Calculate the electric field magnitude $E$ (in $\\text{kV/m}$) at a distance of $r = 0.3\\text{ m}$ from a point charge $q = 5\\mu\\text{C}$ in vacuum. (Take $k = 9 \\times 10^9\\text{ N}\\cdot\\text{m}^2/\\text{C}^2$).",
    "options": [],
    "correctAnswer": 500,
    "numericalAnswer": 500,
    "explanation": "$E = \\frac{kq}{r^2} = \\frac{(9 \\times 10^9)(5 \\times 10^{-6})}{(0.3)^2} = \\frac{45000}{0.09} = 500000\\text{ V/m} = 500\\text{ kV/m}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $m = 2\\text{ mg}$ carries a charge of $q = 2\\mu\\text{C}$. It is placed in a uniform electric field of $E = 1000\\text{ V/m}$. Calculate the acceleration of the particle (in $\\text{km/s}^2$).",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$a = \\frac{qE}{m} = \\frac{(2 \\times 10^{-6}\\text{ C})(1000\\text{ V/m})}{2 \\times 10^{-6}\\text{ kg}} = 1000\\text{ m/s}^2 = 1\\text{ km/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $m = 2\\text{ mg}$ carries a charge of $q = 4\\mu\\text{C}$. It is placed in a uniform electric field of $E = 1000\\text{ V/m}$. Calculate the acceleration of the particle (in $\\text{km/s}^2$).",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "$a = \\frac{qE}{m} = \\frac{(4 \\times 10^{-6}\\text{ C})(1000\\text{ V/m})}{2 \\times 10^{-6}\\text{ kg}} = 2000\\text{ m/s}^2 = 2\\text{ km/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $m = 2\\text{ mg}$ carries a charge of $q = 6\\mu\\text{C}$. It is placed in a uniform electric field of $E = 1000\\text{ V/m}$. Calculate the acceleration of the particle (in $\\text{km/s}^2$).",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "$a = \\frac{qE}{m} = \\frac{(6 \\times 10^{-6}\\text{ C})(1000\\text{ V/m})}{2 \\times 10^{-6}\\text{ kg}} = 3000\\text{ m/s}^2 = 3\\text{ km/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $m = 2\\text{ mg}$ carries a charge of $q = 8\\mu\\text{C}$. It is placed in a uniform electric field of $E = 1000\\text{ V/m}$. Calculate the acceleration of the particle (in $\\text{km/s}^2$).",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "$a = \\frac{qE}{m} = \\frac{(8 \\times 10^{-6}\\text{ C})(1000\\text{ V/m})}{2 \\times 10^{-6}\\text{ kg}} = 4000\\text{ m/s}^2 = 4\\text{ km/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A particle of mass $m = 2\\text{ mg}$ carries a charge of $q = 10\\mu\\text{C}$. It is placed in a uniform electric field of $E = 1000\\text{ V/m}$. Calculate the acceleration of the particle (in $\\text{km/s}^2$).",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "$a = \\frac{qE}{m} = \\frac{(10 \\times 10^{-6}\\text{ C})(1000\\text{ V/m})}{2 \\times 10^{-6}\\text{ kg}} = 5000\\text{ m/s}^2 = 5\\text{ km/s}^2$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An open hemispherical surface of radius $R$ is placed in a uniform electric field $E = 100\\text{ V/m}$ parallel to its axis of symmetry. If the circular base area of the hemisphere is $\\pi R^2 = 1\\text{ m}^2$, calculate the total electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) entering through the curved surface.",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "By Gauss's law, all field lines passing through the circular cross-section must enter the curved surface: $\\Phi_E = E(\\pi R^2) = (100\\text{ V/m})(1\\text{ m}^2) = 100\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An open hemispherical surface of radius $R$ is placed in a uniform electric field $E = 200\\text{ V/m}$ parallel to its axis of symmetry. If the circular base area of the hemisphere is $\\pi R^2 = 1\\text{ m}^2$, calculate the total electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) entering through the curved surface.",
    "options": [],
    "correctAnswer": 200,
    "numericalAnswer": 200,
    "explanation": "By Gauss's law, all field lines passing through the circular cross-section must enter the curved surface: $\\Phi_E = E(\\pi R^2) = (200\\text{ V/m})(1\\text{ m}^2) = 200\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An open hemispherical surface of radius $R$ is placed in a uniform electric field $E = 300\\text{ V/m}$ parallel to its axis of symmetry. If the circular base area of the hemisphere is $\\pi R^2 = 1\\text{ m}^2$, calculate the total electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) entering through the curved surface.",
    "options": [],
    "correctAnswer": 300,
    "numericalAnswer": 300,
    "explanation": "By Gauss's law, all field lines passing through the circular cross-section must enter the curved surface: $\\Phi_E = E(\\pi R^2) = (300\\text{ V/m})(1\\text{ m}^2) = 300\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An open hemispherical surface of radius $R$ is placed in a uniform electric field $E = 400\\text{ V/m}$ parallel to its axis of symmetry. If the circular base area of the hemisphere is $\\pi R^2 = 1\\text{ m}^2$, calculate the total electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) entering through the curved surface.",
    "options": [],
    "correctAnswer": 400,
    "numericalAnswer": 400,
    "explanation": "By Gauss's law, all field lines passing through the circular cross-section must enter the curved surface: $\\Phi_E = E(\\pi R^2) = (400\\text{ V/m})(1\\text{ m}^2) = 400\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "An open hemispherical surface of radius $R$ is placed in a uniform electric field $E = 500\\text{ V/m}$ parallel to its axis of symmetry. If the circular base area of the hemisphere is $\\pi R^2 = 1\\text{ m}^2$, calculate the total electric flux $\\Phi_E$ (in $\\text{N}\\cdot\\text{m}^2/\\text{C}$) entering through the curved surface.",
    "options": [],
    "correctAnswer": 500,
    "numericalAnswer": 500,
    "explanation": "By Gauss's law, all field lines passing through the circular cross-section must enter the curved surface: $\\Phi_E = E(\\pi R^2) = (500\\text{ V/m})(1\\text{ m}^2) = 500\\text{ N}\\cdot\\text{m}^2/\\text{C}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subTopic": "Electric field/flux",
    "chapter": "Electrostatics",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
