module.exports = [
  {
    "question": "Assertion (A): In a balanced Wheatstone bridge, no current flows through the galvanometer branch.\nReason (R): Under the balance condition $\\frac{P}{Q} = \\frac{R}{S}$, the two junction points across the galvanometer are at the exact same electric potential ($V_B = V_D$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because the voltage dividers along both parallel branches produce identical potentials ($V_B = V_D$), the potential difference across the galvanometer is zero, giving $I_g = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): Interchanging the positions of the galvanometer and the battery in a balanced Wheatstone bridge does not disturb the balance condition.\nReason (R): The galvanometer branch and the battery branch in a Wheatstone bridge form conjugate arms.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "If $\\frac{P}{Q} = \\frac{R}{S}$, swapping the battery and galvanometer results in $\\frac{P}{R} = \\frac{Q}{S}$, which is algebraically equivalent. Hence the null deflection persists. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A Wheatstone bridge is most sensitive when the resistances in all four arms are approximately equal.\nReason (R): When the four arm resistances are of the same order of magnitude, any small fractional change in the unknown resistance produces the maximum possible potential difference across the detector.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Bridge sensitivity $\\frac{d(\\Delta V)}{dR}$ is mathematically maximized when $P \\approx Q \\approx R \\approx S$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A Wheatstone bridge is unsuitable for measuring very low resistances (less than $1\\,\\Omega$).\nReason (R): For very small resistances, the contact resistance of connecting wires and binding terminals becomes comparable to the resistance being measured, introducing significant systematic errors.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Lead and contact resistances (typically $10^{-3} - 10^{-2}\\,\\Omega$) introduce severe errors in standard Wheatstone bridges; specialized Kelvin double bridges are used instead. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A Wheatstone bridge is not used for measuring very high resistances (mega-ohms).\nReason (R): When arm resistances are very high, the bridge current becomes extremely small, making galvanometer deflection too sluggish and insensitive to detect null points accurately.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Large resistance limits current to micro-amperes or nano-amperes, below the detection threshold of ordinary galvanometers; leakage currents also corrupt balance. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a balanced Wheatstone bridge, the equivalent resistance between the battery terminals is independent of the resistance of the galvanometer.\nReason (R): Since no current flows through the galvanometer arm, removing it or replacing it with an open or short circuit does not affect the currents in the remaining four arms.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "With $I_g = 0$, the circuit simplifies to two parallel branches of resistances $(P+Q)$ and $(R+S)$, giving $R_{\\text{eq}} = \\frac{(P+Q)(R+S)}{P+Q+R+S}$, completely independent of $G$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A Wheatstone bridge operates as a null method measurement tool.\nReason (R): Null measurement methods do not depend on the accuracy of calibration of the detector galvanometer.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The galvanometer is used merely as a zero-current detector (null indicator); whether its scale is calibrated or linear has no effect on the measurement accuracy. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If the temperature of all four identical resistors in a balanced Wheatstone bridge increases uniformly, the bridge remains balanced.\nReason (R): All four resistors have the same temperature coefficient of resistance ($\\alpha$), so their resistance values change by the same fractional amount.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $R'(T) = R(1 + \\alpha \\Delta T)$, all four arms scale by the identical factor $(1 + \\alpha \\Delta T)$, keeping the ratio $\\frac{P'}{Q'} = \\frac{R'}{S'}$ unchanged. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In an unbalanced Wheatstone bridge, the current through the galvanometer depends on its internal resistance $G$.\nReason (R): When $V_B \\ne V_D$, current flows through the galvanometer, and applying Thévenin's theorem gives $I_g = \\frac{V_{\\text{Th}}}{R_{\\text{Th}} + G}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "An unbalanced bridge delivers current through branch $BD$ determined by the Thévenin equivalent voltage and impedance across the detector terminals. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A Wheatstone bridge cannot be used with alternating current (AC) sources.\nReason (R): Galvanometers can only detect direct current (DC) and give zero average deflection for alternating current.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 1,
    "explanation": "Both statements are true. A DC galvanometer does not respond to AC. However, replacing the battery with an AC source and the galvanometer with a headphone or AC null detector yields AC bridges (e.g. Maxwell, Wien, Schering bridges). Reason is true for DC galvanometers, but (B) is appropriate. (B).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a balanced Wheatstone bridge network with five resistors $P, Q, R, S$ and $G$, the power dissipated in the central resistor $G$ is zero.\nReason (R): The potential difference across resistor $G$ is zero under the balanced condition ($V_B - V_D = 0$).",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $\\Delta V = 0$ across resistor $G$, power dissipated is $P = \\frac{(\\Delta V)^2}{G} = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): The balance condition of a Wheatstone bridge does not depend on the electromotive force (EMF) of the driving battery.\nReason (R): The balance condition $\\frac{P}{Q} = \\frac{R}{S}$ is purely a geometric and constitutive relation between the four resistances forming the bridge.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The voltage across the bridge divides purely according to resistance ratios, so the condition $V_B = V_D$ is completely independent of the driving EMF $E$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If three resistances of a Wheatstone bridge are known with high precision, the unknown fourth resistance can be determined with equal precision.\nReason (R): From $S = \\frac{Q}{P} R$, the fractional uncertainty is $\\frac{\\Delta S}{S} = \\frac{\\Delta P}{P} + \\frac{\\Delta Q}{Q} + \\frac{\\Delta R}{R}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The accuracy of determination is directly bounded by the precision of the three reference resistors and the detector sensitivity. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a Wheatstone bridge, if $P = 10\\,\\Omega, Q = 20\\,\\Omega, R = 15\\,\\Omega$, the value of $S$ for balance is $30\\,\\Omega$.\nReason (R): The balance condition requires $P S = Q R \\implies S = \\frac{Q R}{P}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "$S = \\frac{20 \\times 15}{10} = 30\\,\\Omega$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If the ratio arms $P$ and $Q$ of a Wheatstone bridge are unequal, the bridge can still be balanced.\nReason (R): Balance requires $\\frac{P}{Q} = \\frac{R}{S}$; as long as the ratio $R/S$ equals $P/Q$, a null point is achieved.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Ratio arms need not be equal to each other; they simply determine the multiplying factor ($S = \\frac{Q}{P} R$). (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A post office box is a practical compact form of the Wheatstone bridge.\nReason (R): A post office box contains ratio arms and a resistance arm made of non-inductively wound resistance coils.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "The P.O. Box is a laboratory apparatus historically used by the postal telegraph department to locate faults in telegraph lines using the Wheatstone bridge principle. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): When a Wheatstone bridge is balanced, closing or opening the key in the galvanometer branch produces no deflection in the galvanometer.\nReason (R): The potential difference between the galvanometer terminals is zero, so no transient or steady current flows upon opening or closing the key.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $V_B = V_D$, the state of the galvanometer key (open or closed) produces zero current perturbation. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If the battery and galvanometer are connected to the same pair of opposite nodes in a Wheatstone bridge, the bridge is balanced.\nReason (R): Current will flow through all resistors symmetrically.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "If the battery and galvanometer are connected across the same two nodes, the galvanometer simply measures the battery voltage directly and does not act as a bridge detector. Assertion is false.",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a delta-connected network of three resistors $R$, the equivalent star network has resistors of value $R/3$.\nReason (R): Delta-star transformation converts a loop into a node with branch resistances $R_Y = \\frac{R_1 R_2}{R_1 + R_2 + R_3}$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "For symmetric delta resistors of value $R$: $R_Y = \\frac{R \\cdot R}{3R} = \\frac{R}{3}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a balanced bridge with $P = Q = R = S = 10\\,\\Omega$, the equivalent resistance across the battery terminals is $10\\,\\Omega$.\nReason (R): Two parallel branches, each having resistance $P + Q = 20\\,\\Omega$ and $R + S = 20\\,\\Omega$, yield $R_{\\text{eq}} = \\frac{20}{2} = 10\\,\\Omega$.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Equivalent resistance of two identical $20\\,\\Omega$ branches in parallel is $10\\,\\Omega$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A Wheatstone bridge can be balanced even if the internal resistance of the battery is non-zero.\nReason (R): Internal resistance of the battery affects only the total current drawn from the battery, not the voltage dividing ratio between the arms.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Internal resistance lowers terminal voltage across the bridge from $E$ to $V = E - I r$, but both parallel branches still share the identical terminal voltage $V$, preserving the balance ratio. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a Wheatstone bridge, reversing the polarity of the battery reverses the direction of current in all branches.\nReason (R): By linear circuit superposition, reversing the source voltage negates all branch currents.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since all resistors are linear ohmic elements, reversing the driving EMF negates the sign of every node potential and branch current. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A strain gauge uses the Wheatstone bridge circuit to measure mechanical deformation.\nReason (R): Mechanical strain alters the electrical resistance of the gauge foil slightly, unbalancing a pre-balanced bridge and generating a proportional output voltage.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Piezoresistive foil resistance changes as $\\frac{\\Delta R}{R} = G_F \\epsilon$. Even microscopic changes $\\Delta R \\sim 10^{-3}\\,\\Omega$ produce detectable millivolt signals from an initially balanced bridge. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): In a balanced Wheatstone bridge, the ratio of power dissipated in arm $P$ to that in arm $Q$ is equal to the ratio of their resistances.\nReason (R): Arms $P$ and $Q$ are connected in series in the upper branch and carry the exact same current.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Since $I_g = 0$, the same current $I_1$ flows through both $P$ and $Q$. Power dissipated is $P_P = I_1^2 P$ and $P_Q = I_1^2 Q$, giving $\\frac{P_P}{P_Q} = \\frac{P}{Q}$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): If the galvanometer in a Wheatstone bridge is replaced by a capacitor, the charge on the capacitor is zero at balance.\nReason (R): The potential difference across the capacitor terminals is zero when the bridge is balanced.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 0,
    "explanation": "Because $V_B = V_D$, voltage across the capacitor is $\\Delta V = 0$, giving stored charge $Q = C \\Delta V = 0$. (R) correctly explains (A).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Assertion (A): A Wheatstone bridge cannot be used to measure temperature.\nReason (R): Resistors do not change their resistance when temperature changes.",
    "options": [
      "Both (A) and (R) are true and (R) is the correct explanation of (A)",
      "Both (A) and (R) are true but (R) is not the correct explanation of (A)",
      "(A) is true but (R) is false",
      "(A) is false but (R) is true"
    ],
    "correctAnswer": 3,
    "explanation": "Platinum resistance thermometers (PRTs) and thermistors operate precisely via Wheatstone bridges to detect temperature variations through resistance changes. Both statements are false; Assertion is false. (D).",
    "type": "ASSERTION_REASON",
    "questionType": "Assertion-Reason",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge circuit, the four arms have resistances $P = 2\\,\\Omega, Q = 4\\,\\Omega, R = 3\\,\\Omega$, and $S = 6\\,\\Omega$. A galvanometer of resistance $10\\,\\Omega$ is connected across the bridge. The equivalent resistance across the battery terminals is:",
    "options": [
      "$3.6\\,\\Omega$",
      "$4.5\\,\\Omega$",
      "$5.0\\,\\Omega$",
      "$6.0\\,\\Omega$"
    ],
    "correctAnswer": 0,
    "explanation": "Since $\\frac{P}{Q} = \\frac{2}{4} = \\frac{1}{2}$ and $\\frac{R}{S} = \\frac{3}{6} = \\frac{1}{2}$, the bridge is balanced and no current flows through the galvanometer. The upper branch resistance is $P + Q = 2 + 4 = 6\\,\\Omega$, and the lower branch resistance is $R + S = 3 + 6 = 9\\,\\Omega$. In parallel: $R_{\\text{eq}} = \\frac{6 \\times 9}{6 + 9} = \\frac{54}{15} = 3.6\\,\\Omega$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In an unbalanced Wheatstone bridge, $P = 1\\,\\Omega, Q = 2\\,\\Omega, R = 2\\,\\Omega, S = 1\\,\\Omega$, and a battery of $6\\text{ V}$ is connected across the input terminals. If the galvanometer branch has resistance $G$, the potential difference across the galvanometer $V_B - V_D$ is:",
    "options": [
      "$1\\text{ V}$",
      "$2\\text{ V}$",
      "$-2\\text{ V}$",
      "$0\\text{ V}$"
    ],
    "correctAnswer": 1,
    "explanation": "Let the battery terminals be at $6\\text{ V}$ and $0\\text{ V}$. Potential at node $B$ is $V_B = 6 \\times \\frac{Q}{P + Q} = 6 \\times \\frac{2}{1 + 2} = 4\\text{ V}$. Potential at node $D$ is $V_D = 6 \\times \\frac{S}{R + S} = 6 \\times \\frac{1}{2 + 1} = 2\\text{ V}$. The potential difference is $V_B - V_D = 4 - 2 = 2\\text{ V}$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "The condition for maximum sensitivity of a Wheatstone bridge is:",
    "options": [
      "$P \\gg Q$ and $R \\gg S$",
      "$P \\ll Q$ and $R \\ll S$",
      "$P \\approx Q \\approx R \\approx S$",
      "Galvanometer resistance $G \\to \\infty$"
    ],
    "correctAnswer": 2,
    "explanation": "A Wheatstone bridge achieves maximum sensitivity to small changes in unknown resistance when all four arms have roughly equal resistance ($P \\approx Q \\approx R \\approx S$) and the galvanometer resistance is of the same order.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge, three resistors have values $P = 10\\,\\Omega, Q = 20\\,\\Omega, R = 30\\,\\Omega$. What resistance $S'$ must be connected in parallel with a resistor $S = 100\\,\\Omega$ in the fourth arm to balance the bridge?",
    "options": [
      "$150\\,\\Omega$",
      "$100\\,\\Omega$",
      "$75\\,\\Omega$",
      "$60\\,\\Omega$"
    ],
    "correctAnswer": 0,
    "explanation": "Required resistance for balance is $S_{\\text{eq}} = \\frac{Q R}{P} = \\frac{20 \\times 30}{10} = 60\\,\\Omega$. Connecting $S'$ in parallel with $S = 100\\,\\Omega$ gives $\\frac{100 S'}{100 + S'} = 60 \\implies 100 S' = 6000 + 60 S' \\implies 40 S' = 6000 \\implies S' = 150\\,\\Omega$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A network of five identical resistors each of value $R$ forms a bridge. The equivalent resistance between the two input nodes is:",
    "options": [
      "$R$",
      "$2R$",
      "$\\frac{R}{2}$",
      "$\\frac{5R}{2}$"
    ],
    "correctAnswer": 0,
    "explanation": "Since all four arms are identical ($P = Q = R = S = R$), the bridge is balanced ($\\frac{R}{R} = \\frac{R}{R}$). No current flows through the central resistor. The circuit reduces to two parallel branches of $2R$ each: $R_{\\text{eq}} = \\frac{2R}{2} = R$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge, if the positions of the battery and the galvanometer are interchanged, the condition for null deflection:",
    "options": [
      "Becomes $\\frac{P}{S} = \\frac{Q}{R}$",
      "Remains unchanged",
      "Requires doubling the value of $P$",
      "Can never be achieved"
    ],
    "correctAnswer": 1,
    "explanation": "The galvanometer and battery arms are conjugate arms. Interchanging them transforms $\\frac{P}{Q} = \\frac{R}{S}$ into $\\frac{P}{R} = \\frac{Q}{S}$, which is algebraically identical ($P S = Q R$). Hence the balance condition remains unchanged.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge, $P = 9\\,\\Omega, Q = 11\\,\\Omega, R = 4\\,\\Omega$, and $S = 6\\,\\Omega$. To balance the bridge, a resistor $x$ should be connected in:",
    "options": [
      "Parallel with $P$",
      "Series with $R$",
      "Series with $P$",
      "Parallel with $S$"
    ],
    "correctAnswer": 1,
    "explanation": "Currently $\\frac{P}{Q} = \\frac{9}{11}$ and $\\frac{R}{S} = \\frac{4}{6} = \\frac{2}{3} = \\frac{4}{6} < \\frac{9}{11}$. To balance the bridge, we need $\\frac{R'}{S} = \\frac{9}{11} \\implies R' = \\frac{54}{11} \\approx 4.91\\,\\Omega > 4\\,\\Omega$. Since the required resistance $R'$ is greater than $4\\,\\Omega$, a resistor must be connected in series with $R$.",
    "type": "MCQ",
    "questionType": "MCQ (Multiple Choice Question)",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, $P = 10\\,\\Omega, Q = 20\\,\\Omega$, and $R = 15\\,\\Omega$. The value of unknown resistance $S$ in Ohms is:",
    "options": [],
    "correctAnswer": 30,
    "numericalAnswer": 30,
    "explanation": "$S = \\frac{Q R}{P} = \\frac{20 \\times 15}{10} = 30\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "Five identical resistors of $10\\,\\Omega$ each are arranged to form a bridge circuit. The equivalent resistance between the two diagonal input terminals in Ohms is:",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "Because all four arms are equal to $10\\,\\Omega$, the bridge is balanced. The central resistor draws zero current. The two parallel branches each have $10 + 10 = 20\\,\\Omega$, yielding $R_{\\text{eq}} = 10\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge, $P = 4\\,\\Omega, Q = 12\\,\\Omega$, and $R = 5\\,\\Omega$. The value of $S$ in Ohms required for the galvanometer to show null deflection is:",
    "options": [],
    "correctAnswer": 15,
    "numericalAnswer": 15,
    "explanation": "$\\frac{P}{Q} = \\frac{R}{S} \\implies \\frac{4}{12} = \\frac{5}{S} \\implies \\frac{1}{3} = \\frac{5}{S} \\implies S = 15\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, the four arm resistances are $P = 2\\,\\Omega, Q = 4\\,\\Omega, R = 4\\,\\Omega$, and $S = 8\\,\\Omega$. The equivalent resistance of the network across the battery terminals in Ohms is:",
    "options": [],
    "correctAnswer": 4,
    "numericalAnswer": 4,
    "explanation": "The bridge is balanced since $\\frac{2}{4} = \\frac{4}{8} = \\frac{1}{2}$. Upper branch resistance is $P + Q = 2 + 4 = 6\\,\\Omega$. Lower branch resistance is $R + S = 4 + 8 = 12\\,\\Omega$. In parallel: $R_{\\text{eq}} = \\frac{6 \\times 12}{6 + 12} = \\frac{72}{18} = 4\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge, $P = 2\\,\\Omega, Q = 2\\,\\Omega, R = 2\\,\\Omega$, and $S = 3\\,\\Omega$. The resistance in Ohms that must be connected in parallel with $S$ to balance the bridge is:",
    "options": [],
    "correctAnswer": 6,
    "numericalAnswer": 6,
    "explanation": "For balance, we need $S_{\\text{eq}} = 2\\,\\Omega$. Connecting $x$ in parallel with $3\\,\\Omega$: $\\frac{3x}{3+x} = 2 \\implies 3x = 6 + 2x \\implies x = 6\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, $P = 6\\,\\Omega, Q = 6\\,\\Omega, R = 12\\,\\Omega$, and $S = 12\\,\\Omega$. If a $24\\text{ V}$ battery is connected across the input terminals, the total current drawn from the battery in Amperes is:",
    "options": [],
    "correctAnswer": 3,
    "numericalAnswer": 3,
    "explanation": "Upper branch resistance is $6 + 6 = 12\\,\\Omega$. Lower branch resistance is $12 + 12 = 24\\,\\Omega$. Equivalent resistance is $R_{\\text{eq}} = \\frac{12 \\times 24}{12 + 24} = \\frac{288}{36} = 8\\,\\Omega$. Current drawn is $I = \\frac{V}{R_{\\text{eq}}} = \\frac{24}{8} = 3\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, $P = 100\\,\\Omega, Q = 1000\\,\\Omega$, and $R = 40\\,\\Omega$. The value of $S$ in Ohms is:",
    "options": [],
    "correctAnswer": 400,
    "numericalAnswer": 400,
    "explanation": "$S = \\frac{Q R}{P} = \\frac{1000 \\times 40}{100} = 400\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A Wheatstone bridge has arms $P = 1\\,\\Omega, Q = 3\\,\\Omega, R = 2\\,\\Omega$, and $S = 6\\,\\Omega$. If a current of $2\\text{ A}$ flows through arm $P$, the current flowing through arm $Q$ in Amperes is:",
    "options": [],
    "correctAnswer": 2,
    "numericalAnswer": 2,
    "explanation": "Because the bridge is balanced ($\\frac{1}{3} = \\frac{2}{6}$), zero current enters or leaves through the galvanometer branch. Hence the entire current passing through arm $P$ continues directly into arm $Q$, so $I_Q = 2\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a bridge circuit, the resistances in cyclic order are $10\\,\\Omega, 20\\,\\Omega, 30\\,\\Omega$, and $40\\,\\Omega$. To make the bridge balanced, a resistor of value $X$ Ohms is added in series with the $10\\,\\Omega$ resistor. The value of $X$ is:",
    "options": [],
    "correctAnswer": 5,
    "numericalAnswer": 5,
    "explanation": "For balance, $\\frac{10 + X}{20} = \\frac{30}{40} = \\frac{3}{4} \\implies 4(10 + X) = 60 \\implies 40 + 4X = 60 \\implies 4X = 20 \\implies X = 5\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, the resistances are $P = 8\\,\\Omega, Q = 12\\,\\Omega, R = 16\\,\\Omega$, and $S = 24\\,\\Omega$. The potential difference across the galvanometer in Volts is:",
    "options": [],
    "correctAnswer": 0,
    "numericalAnswer": 0,
    "explanation": "In any balanced Wheatstone bridge, the two nodes connected to the galvanometer are at equal potentials, so the potential difference across the galvanometer is identically zero.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A balanced Wheatstone bridge is powered by a $10\\text{ V}$ battery. The resistances are $P = 1\\,\\Omega, Q = 4\\,\\Omega, R = 2\\,\\Omega$, and $S = 8\\,\\Omega$. The potential of the junction between $P$ and $Q$ relative to the negative battery terminal in Volts is:",
    "options": [],
    "correctAnswer": 8,
    "numericalAnswer": 8,
    "explanation": "The voltage across the upper branch is $10\\text{ V}$. Current is $I_1 = \\frac{10}{1 + 4} = 2\\text{ A}$. Voltage drop across $P$ is $2 \\times 1 = 2\\text{ V}$. The potential at the junction relative to the negative terminal is $10 - 2 = 8\\text{ V}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge, $P = 10\\,\\Omega, Q = 10\\,\\Omega, R = 10\\,\\Omega$, and $S = 10\\,\\Omega$. If the galvanometer resistance is $50\\,\\Omega$, the equivalent resistance across the battery terminals in Ohms is:",
    "options": [],
    "correctAnswer": 10,
    "numericalAnswer": 10,
    "explanation": "The bridge is balanced, so galvanometer branch carries no current. Two parallel branches of $20\\,\\Omega$ each yield $R_{\\text{eq}} = 10\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A resistor of $20\\,\\Omega$ is placed in arm $P$, $40\\,\\Omega$ in arm $Q$, and $30\\,\\Omega$ in arm $R$. The resistance in Ohms required in arm $S$ to balance the bridge is:",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$S = \\frac{Q R}{P} = \\frac{40 \\times 30}{20} = 60\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, $P = 50\\,\\Omega, Q = 150\\,\\Omega$, and $R = 20\\,\\Omega$. The value of $S$ in Ohms is:",
    "options": [],
    "correctAnswer": 60,
    "numericalAnswer": 60,
    "explanation": "$S = \\frac{150 \\times 20}{50} = 3 \\times 20 = 60\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a bridge with $P = 3\\,\\Omega, Q = 9\\,\\Omega, R = 4\\,\\Omega$, and $S = 12\\,\\Omega$, the current through the galvanometer of resistance $20\\,\\Omega$ in Amperes is:",
    "options": [],
    "correctAnswer": 0,
    "numericalAnswer": 0,
    "explanation": "Since $\\frac{P}{Q} = \\frac{3}{9} = \\frac{1}{3}$ and $\\frac{R}{S} = \\frac{4}{12} = \\frac{1}{3}$, the bridge is balanced and current through the galvanometer is $0\\text{ A}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a Wheatstone bridge, $P = 2\\,\\Omega, Q = 4\\,\\Omega, R = 1\\,\\Omega$, and $S = 2\\,\\Omega$. If the battery has an EMF of $6\\text{ V}$ and zero internal resistance, the power dissipated by the bridge in Watts is:",
    "options": [],
    "correctAnswer": 18,
    "numericalAnswer": 18,
    "explanation": "Upper branch resistance is $2 + 4 = 6\\,\\Omega$. Lower branch resistance is $1 + 2 = 3\\,\\Omega$. In parallel, $R_{\\text{eq}} = \\frac{6 \\times 3}{6 + 3} = 2\\,\\Omega$. Power is $P = \\frac{V^2}{R_{\\text{eq}}} = \\frac{6^2}{2} = \\frac{36}{2} = 18\\text{ W}$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, the ratio $\\frac{P}{Q}$ is equal to $\\frac{1}{4}$. If $R = 25\\,\\Omega$, the value of $S$ in Ohms is:",
    "options": [],
    "correctAnswer": 100,
    "numericalAnswer": 100,
    "explanation": "$\\frac{P}{Q} = \\frac{R}{S} \\implies \\frac{1}{4} = \\frac{25}{S} \\implies S = 100\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a bridge network, the four arms have resistances $10\\,\\Omega, 20\\,\\Omega, 20\\,\\Omega$, and $40\\,\\Omega$. The ratio $\\frac{P S}{Q R}$ is:",
    "options": [],
    "correctAnswer": 1,
    "numericalAnswer": 1,
    "explanation": "$\\frac{P S}{Q R} = \\frac{10 \\times 40}{20 \\times 20} = \\frac{400}{400} = 1$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "A Wheatstone bridge has arms $P = 7\\,\\Omega, Q = 21\\,\\Omega, R = 5\\,\\Omega$, and $S = 15\\,\\Omega$. The equivalent resistance between the two detector terminals when the battery is removed in Ohms is:",
    "options": [],
    "correctAnswer": 9,
    "numericalAnswer": 9,
    "explanation": "Looking into the detector terminals with the battery terminals open, the branches are $(P + R) = 12\\,\\Omega$ and $(Q + S) = 36\\,\\Omega$ in parallel. $R_{\\text{Th}} = \\frac{12 \\times 36}{12 + 36} = \\frac{432}{48} = 9\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  },
  {
    "question": "In a balanced Wheatstone bridge, $P = 15\\,\\Omega, Q = 45\\,\\Omega$, and $S = 60\\,\\Omega$. The value of $R$ in Ohms is:",
    "options": [],
    "correctAnswer": 20,
    "numericalAnswer": 20,
    "explanation": "$R = \\frac{P S}{Q} = \\frac{15 \\times 60}{45} = \\frac{900}{45} = 20\\,\\Omega$.",
    "type": "NUMERICAL",
    "questionType": "Numerical",
    "subtopic": "Wheatstone bridge",
    "subTopic": "Wheatstone bridge",
    "chapter": "Current Electricity",
    "subject": "Physics",
    "marks": 4,
    "negativeMarks": 1,
    "source": "JEE Main Question Bank"
  }
];
