// Auto-generated Part 5 for Gravitation - Acceleration due to gravity
module.exports = [
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The value of acceleration due to gravity is maximum at the poles and minimum at the equator.\n\n**Reason:** Both the centrifugal force due to Earth's axial rotation and the ellipsoidal shape of the Earth (polar radius being less than equatorial radius) reduce $g$ at the equator relative to the poles.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At the poles, latitude $\\lambda = 90^\\circ$, so centrifugal acceleration $R\\omega^2\\cos^2(90^\\circ) = 0$. At the equator, $\\lambda = 0^\\circ$, so $g_e = g - R\\omega^2$. Additionally, Earth is flattened at the poles ($R_p < R_e$), so $g = GM/R^2$ is inherently larger at the poles. Both effects make $g$ maximum at the poles and minimum at the equator. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** For small distances near Earth's surface ($h \\ll R$), the decrease in $g$ at an altitude $h$ is twice the decrease in $g$ at a depth $d = h$.\n\n**Reason:** The fractional decrease in $g$ with height is $\\frac{\\Delta g_h}{g} = \\frac{2h}{R}$, whereas with depth it is $\\frac{\\Delta g_d}{g} = \\frac{d}{R}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "For $h \\ll R$, $g_h \\approx g(1 - 2h/R) \\implies \\Delta g_h = \\frac{2h}{R}g$. At depth $d$, $g_d = g(1 - d/R) \\implies \\Delta g_d = \\frac{d}{R}g$. When $d = h$, $\\Delta g_h = 2 \\Delta g_d$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** At the centre of the Earth, the acceleration due to gravity is zero.\n\n**Reason:** At the centre of Earth ($d = R$), by $g_d = g\\left(1 - \\frac{d}{R}\\right)$, $g_{\\text{centre}} = g(1 - 1) = 0$, and the symmetrical mass distribution exerts equal outward gravitational pulls in all directions.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At the Earth's centre, distance from centre is $r = 0$, so the enclosed mass is zero ($M(0) = 0$). By symmetry, gravitational forces from all directions cancel, resulting in $g = 0$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** If the Earth suddenly stops rotating about its axis, the value of $g$ increases everywhere on Earth except at the poles.\n\n**Reason:** Centrifugal force due to rotation acts at all latitudes except the poles, reducing the effective acceleration due to gravity by $R\\omega^2\\cos^2\\lambda$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Effective gravity is $g' = g - R\\omega^2\\cos^2\\lambda$. If rotation stops ($\\omega = 0$), $g'$ increases by $R\\omega^2\\cos^2\\lambda$. At the poles ($\\lambda = 90^\\circ$), $\\cos\\lambda = 0$, so $g$ was already unaffected by rotation and remains unchanged. At all other latitudes, $g$ increases. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** If the Earth rotates 17 times faster than its present angular speed, bodies at the equator would experience weightlessness.\n\n**Reason:** Weightlessness occurs at the equator when the centrifugal acceleration equals the gravitational acceleration: $R\\omega^2 = g \\implies \\omega = \\sqrt{\\frac{g}{R}}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Effective weight at the equator is $W' = m(g - R\\omega^2)$. Setting $W' = 0$ yields $\\omega = \\sqrt{g/R} \\approx \\sqrt{9.8 / (6.4 \\times 10^6)} \\approx 1.24 \\times 10^{-3}\\text{ rad/s}$. The current angular velocity is $\\omega_0 = \\frac{2\\pi}{86400} \\approx 7.27 \\times 10^{-5}\\text{ rad/s}$. Thus $\\frac{\\omega}{\\omega_0} \\approx 17$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The formula $g_h = g\\left(1 - \\frac{2h}{R}\\right)$ cannot be used when $h = R$.\n\n**Reason:** The binomial approximation $(1 + h/R)^{-2} \\approx 1 - 2h/R$ is valid only when $h \\ll R$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "When $h = R$, the exact formula gives $g_h = \\frac{g}{(1 + 1)^2} = \\frac{g}{4}$. Using the approximation would give $g(1 - 2) = -g$, which is physically nonsensical. The approximation requires $h/R \\ll 1$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** As a person goes from the equator to the North Pole, their apparent weight increases.\n\n**Reason:** The centrifugal force due to Earth's rotation decreases from maximum at the equator to zero at the pole.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At latitude $\\lambda$, $W = m(g - R\\omega^2\\cos^2\\lambda)$. As $\\lambda$ increases from $0^\\circ$ (equator) to $90^\\circ$ (North Pole), $\\cos\\lambda$ decreases to 0, so the centrifugal reduction diminishes, increasing apparent weight. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** A body weighs more in a mine of depth $d$ than it does on the surface of the Earth.\n\n**Reason:** Inside the Earth, acceleration due to gravity decreases linearly with depth as $g_d = g(1 - d/R)$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 3,
    "explanation": "Because $g_d = g(1 - d/R) < g$ for any depth $d > 0$, the weight in a mine is strictly less than that on the surface. Assertion is false, Reason is true.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** If both the mass and radius of the Earth decrease by $1\\%$, the value of $g$ increases by approximately $1\\%$.\n\n**Reason:** Acceleration due to gravity is $g = \\frac{GM}{R^2}$, so $\\frac{\\Delta g}{g} = \\frac{\\Delta M}{M} - 2\\frac{\\Delta R}{R}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "From $g = G M R^{-2}$, differentiating gives $\\frac{\\Delta g}{g} = \\frac{\\Delta M}{M} - 2\\frac{\\Delta R}{R} = (-1\\%) - 2(-1\\%) = -1\\% + 2\\% = +1\\%$. Hence $g$ increases by $1\\%$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The difference in the acceleration due to gravity between the poles and the equator due to Earth's rotation is $R\\omega^2$.\n\n**Reason:** At the poles $g_p = g$ and at the equator $g_e = g - R\\omega^2$, giving $g_p - g_e = R\\omega^2$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At latitude $\\lambda$, $g_\\lambda = g - R\\omega^2\\cos^2\\lambda$. At poles ($\\lambda = 90^\\circ$), $g_p = g$. At equator ($\\lambda = 0^\\circ$), $g_e = g - R\\omega^2$. Thus $g_p - g_e = R\\omega^2 \\approx 0.034\\text{ m/s}^2$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** A simple pendulum of length $L$ oscillates faster at the poles than at the equator.\n\n**Reason:** The time period of a simple pendulum is $T = 2\\pi\\sqrt{\\frac{L}{g}}$, and $g_{\\text{pole}} > g_{\\text{equator}}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Since frequency $f = \\frac{1}{T} = \\frac{1}{2\\pi}\\sqrt{\\frac{g}{L}}$, frequency is proportional to $\\sqrt{g}$. Because $g_{\\text{pole}} > g_{\\text{equator}}$, the frequency is higher and the pendulum oscillates faster at the poles. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** At an altitude $h = R(\\sqrt{2} - 1) \\approx 0.414 R$, the value of $g$ becomes half of its surface value.\n\n**Reason:** From $g_h = \\frac{g}{(1 + h/R)^2} = \\frac{g}{2}$, taking reciprocal and square root gives $1 + \\frac{h}{R} = \\sqrt{2} \\implies h = R(\\sqrt{2} - 1)$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "$$\\frac{g}{(1 + h/R)^2} = \\frac{g}{2} \\implies (1 + h/R)^2 = 2 \\implies 1 + h/R = \\sqrt{2} \\implies h = R(\\sqrt{2} - 1) \\approx 0.414 R$$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The acceleration due to gravity at depth $d = R/2$ is equal to half of the value on the Earth's surface.\n\n**Reason:** Inside the Earth, $g_d = g\\left(1 - \\frac{d}{R}\\right)$, so substituting $d = R/2$ yields $g_d = g(1 - 1/2) = g/2$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At $d = R/2$, $g_d = g(1 - 0.5) = 0.5 g$. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** If a hole is bored to the centre of the Earth, a body dropped into the hole accelerates continuously until it reaches the centre.\n\n**Reason:** Throughout the fall towards the centre, the gravitational force is always directed towards the centre.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Inside the Earth, restoring force $F = -\\left(\\frac{mg}{R}\\right)r$ is directed towards the centre at all points. Although the acceleration $a = g(r/R)$ decreases in magnitude as $r \\to 0$, it remains positive in the direction of motion, so the body continuously speeds up, reaching maximum velocity at the centre. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The value of $g$ on a planet of the same mean density as Earth but twice the radius is twice that of Earth.\n\n**Reason:** Acceleration due to gravity on the surface is given by $g = \\frac{4}{3}\\pi G\\rho R$, which is directly proportional to radius $R$ for a constant density $\\rho$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Since $g = \\frac{4}{3}\\pi G\\rho R$, if $\\rho$ is constant and $R' = 2R$, then $g' = 2g$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** A spring balance reading decreases when moved from the poles to the equator.\n\n**Reason:** A spring balance measures the true weight $mg$ without being affected by centrifugal force.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 2,
    "explanation": "A spring balance measures apparent weight $W' = m(g - R\\omega^2\\cos^2\\lambda)$. At the equator, apparent weight is smaller due to centrifugal force and Earth's bulge, so the spring balance reading decreases. Reason is false because spring balance DOES measure apparent weight (centrifugal force affects it). Assertion is true, Reason is false.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** A beam balance with standard masses gives the same reading at the equator and at the poles.\n\n**Reason:** A beam balance compares the gravitational force on the unknown mass with that on standard masses, and $g$ affects both pans equally.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "In a beam balance, equilibrium requires $m_1 g' = m_2 g' \\implies m_1 = m_2$. Because local gravity $g'$ acts equally on both pans, the measurement of true mass is invariant with location. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The fractional decrease in $g$ at height $h$ is independent of the mass of the planet.\n\n**Reason:** The fractional change in $g$ for $h \\ll R$ is given by $\\frac{\\Delta g}{g} = -\\frac{2h}{R}$, which depends only on height $h$ and planetary radius $R$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "$\\frac{\\Delta g}{g} = \\frac{g_h - g}{g} \\approx -\\frac{2h}{R}$. The planetary mass $M$ cancels out when dividing by $g = GM/R^2$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** If the Earth were to expand to twice its radius without any change in its mass, a person's weight on its surface would become one-fourth.\n\n**Reason:** Acceleration due to gravity is inversely proportional to the square of the planet's radius: $g \\propto \\frac{1}{R^2}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "From $g = \\frac{GM}{R^2}$, if $R' = 2R$, $g' = \\frac{GM}{(2R)^2} = \\frac{g}{4}$. Weight $W' = mg' = W/4$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** At latitude $\\lambda = 60^\\circ$, the reduction in acceleration due to gravity due to Earth's rotation is $\\frac{1}{4}R\\omega^2$.\n\n**Reason:** The reduction in $g$ due to rotation is $R\\omega^2\\cos^2\\lambda$, and $\\cos 60^\\circ = \\frac{1}{2}$, so $\\cos^2 60^\\circ = \\frac{1}{4}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Reduction $\\Delta g = R\\omega^2\\cos^2(60^\\circ) = R\\omega^2(1/2)^2 = \\frac{1}{4}R\\omega^2$. Both Assertion and Reason are true and Reason is the correct explanation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** An object weighs less at the top of Mount Everest than at sea level.\n\n**Reason:** Mount Everest is at an altitude $h \\approx 8.85\\text{ km}$, and $g_h = g\\left(1 - \\frac{2h}{R}\\right) < g$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At an altitude of $8.85\\text{ km}$, distance from Earth's centre increases, decreasing $g$ by approximately $\\frac{2(8.85)}{6400} \\approx 0.28\\%$, so weight is lower. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The rate of decrease of $g$ with height is greater than the rate of decrease of $g$ with depth near the surface of Earth.\n\n**Reason:** $\\left|\\frac{dg}{dh}\\right| = \\frac{2g}{R}$, while $\\left|\\frac{dg}{dd}\\right| = \\frac{g}{R}$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Differentiating $g_h = g(1 - 2h/R)$ gives $\\left|\\frac{dg}{dh}\\right| = \\frac{2g}{R}$. Differentiating $g_d = g(1 - d/R)$ gives $\\left|\\frac{dg}{dd}\\right| = \\frac{g}{R}$. The rate of decrease with height is twice that with depth. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The acceleration due to gravity $g$ is a constant vector at all points on the Earth's surface.\n\n**Reason:** The magnitude of $g$ varies with latitude and topography, and its direction points toward the centre of Earth, which differs from point to point.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 3,
    "explanation": "The acceleration due to gravity is NOT a constant vector: its magnitude varies with latitude (due to rotation and oblateness), and its direction points radially inward (varying from point to point over the sphere). Hence Assertion is false, Reason is true.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** If a clock regulated by a simple pendulum is taken from the equator to the pole, it gains time.\n\n**Reason:** The time period of a simple pendulum decreases as $g$ increases, so the pendulum completes more oscillations per day.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "Since $T = 2\\pi\\sqrt{L/g}$, as $g$ increases from equator to pole, $T$ decreases. A shorter period means the pendulum swings faster, completing more oscillations in 24 hours, so the clock gains time. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** At a depth equal to the radius of Earth ($d = R$), a body becomes completely weightless.\n\n**Reason:** At the centre of Earth, the gravitational field is zero.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At $d = R$, the body is at the centre of Earth where $g = 0$, so weight $W = mg = 0$ (weightlessness). Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "ASSERTION_REASON",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "**Assertion:** The centrifugal force acting on a body of mass $m$ at the equator due to Earth's rotation is $m R\\omega^2$.\n\n**Reason:** At the equator, the radius of the circular path of rotation is equal to the radius of the Earth $R$.",
    "options": [
      "Both Assertion and Reason are true and Reason is the correct explanation of Assertion",
      "Both Assertion and Reason are true but Reason is NOT the correct explanation of Assertion",
      "Assertion is true but Reason is false",
      "Assertion is false but Reason is true"
    ],
    "correctOptionIndex": 0,
    "explanation": "At latitude $\\lambda$, the radius of rotation about the polar axis is $r = R\\cos\\lambda$. At the equator ($\\lambda = 0^\\circ$), $r = R$. Thus the centrifugal force in the rotating frame is $F_c = m r \\omega^2 = m R\\omega^2$. Both Assertion and Reason are true and Reason explains Assertion.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what height $h$ above the Earth's surface will the acceleration due to gravity become $1\\%$ of its value on the surface of the Earth? ($R$ is the radius of Earth)",
    "options": [
      "$9R$",
      "$10R$",
      "$99R$",
      "$\\frac{R}{9}$"
    ],
    "correctOptionIndex": 0,
    "explanation": "Given $g_h = \\frac{1}{100}g$.\n$$g_h = \\frac{g}{(1 + h/R)^2} = \\frac{1}{100}g \\implies (1 + h/R)^2 = 100 \\implies 1 + \\frac{h}{R} = 10 \\implies h = 9R$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what depth $d$ below the Earth's surface is the acceleration due to gravity equal to $\\frac{g}{4}$, where $g$ is the acceleration due to gravity on the surface?",
    "options": [
      "$\\frac{3}{4}R$",
      "$\\frac{1}{4}R$",
      "$\\frac{1}{2}R$",
      "$\\frac{2}{3}R$"
    ],
    "correctOptionIndex": 0,
    "explanation": "Inside the Earth, $g_d = g\\left(1 - \\frac{d}{R}\\right)$.\n$$\\frac{g}{4} = g\\left(1 - \\frac{d}{R}\\right) \\implies 1 - \\frac{d}{R} = \\frac{1}{4} \\implies \\frac{d}{R} = \\frac{3}{4} \\implies d = \\frac{3}{4}R$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "The acceleration due to gravity at a height $h$ above the surface of Earth is the same as that at a depth $d$ below the surface. If $h \\ll R$, the relation between $h$ and $d$ is:",
    "options": [
      "$d = 2h$",
      "$d = h$",
      "$d = h/2$",
      "$d = 4h$"
    ],
    "correctOptionIndex": 0,
    "explanation": "For $h \\ll R$, $g_h = g\\left(1 - \\frac{2h}{R}\\right)$.\nAt depth $d$, $g_d = g\\left(1 - \\frac{d}{R}\\right)$.\nEquating $g_h = g_d$:\n$$1 - \\frac{2h}{R} = 1 - \\frac{d}{R} \\implies d = 2h$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "Assuming Earth to be a uniform sphere of radius $R$, at what latitude $\\lambda$ will the acceleration due to gravity be $g - \\frac{1}{4}R\\omega^2$?",
    "options": [
      "$60^\\circ$",
      "$30^\\circ$",
      "$45^\\circ$",
      "$0^\\circ$"
    ],
    "correctOptionIndex": 0,
    "explanation": "Effective gravity at latitude $\\lambda$ is $g' = g - R\\omega^2\\cos^2\\lambda$.\nGiven $g' = g - \\frac{1}{4}R\\omega^2$:\n$$R\\omega^2\\cos^2\\lambda = \\frac{1}{4}R\\omega^2 \\implies \\cos^2\\lambda = \\frac{1}{4} \\implies \\cos\\lambda = \\frac{1}{2} \\implies \\lambda = 60^\\circ$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "If the radius of the Earth contracts by $2\\%$ while its mass remains constant, the acceleration due to gravity on its surface will:",
    "options": [
      "Increase by 4%",
      "Decrease by 4%",
      "Increase by 2%",
      "Decrease by 2%"
    ],
    "correctOptionIndex": 0,
    "explanation": "From $g = G M R^{-2}$, differentiating gives:\n$$\\frac{\\Delta g}{g} = -2\\frac{\\Delta R}{R}$$\nSince $R$ contracts by $2\\%$ ($\\frac{\\Delta R}{R} = -2\\%$):\n$$\\frac{\\Delta g}{g} = -2(-2\\%) = +4\\%$$\nThus $g$ increases by $4\\%$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "The weight of a body on the surface of Earth is $250\\text{ N}$. How much will it weigh at a depth equal to half the radius of the Earth?",
    "options": [
      "125 N",
      "62.5 N",
      "187.5 N",
      "200 N"
    ],
    "correctOptionIndex": 0,
    "explanation": "At depth $d = R/2$:\n$$g_d = g\\left(1 - \\frac{d}{R}\\right) = g\\left(1 - \\frac{1}{2}\\right) = \\frac{g}{2}$$\n$$W_d = m g_d = m \\frac{g}{2} = \\frac{W}{2} = \\frac{250}{2} = 125\\text{ N}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "MCQ",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what height $h$ above Earth's surface does the value of $g$ decrease by $36\\%$ of its value on the surface?",
    "options": [
      "$R/4$",
      "$R/2$",
      "$R/3$",
      "$2R/3$"
    ],
    "correctOptionIndex": 0,
    "explanation": "If $g$ decreases by $36\\%$, the new value is $g_h = (1 - 0.36)g = 0.64 g$.\n$$\\frac{g}{(1 + h/R)^2} = 0.64 g \\implies (1 + h/R)^2 = \\frac{1}{0.64} = \\frac{100}{64}$$\nTaking the square root:\n$$1 + \\frac{h}{R} = \\frac{10}{8} = 1.25 \\implies \\frac{h}{R} = 0.25 = \\frac{1}{4} \\implies h = \\frac{R}{4}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 1,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what height $h$ (in kilometres) above the Earth's surface is the acceleration due to gravity $g/4$? Take the radius of Earth as $R = 6400\\text{ km}$.",
    "correctAnswer": "6400",
    "explanation": "$$g_h = \\frac{g}{(1 + h/R)^2} = \\frac{g}{4} \\implies 1 + h/R = 2 \\implies h = R = 6400\\text{ km}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what depth $d$ (in kilometres) below the surface of Earth is the acceleration due to gravity half of its surface value? Take $R = 6400\\text{ km}$.",
    "correctAnswer": "3200",
    "explanation": "$$g_d = g(1 - d/R) = g/2 \\implies 1 - d/R = 1/2 \\implies d = R/2 = 3200\\text{ km}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "The percentage decrease in the acceleration due to gravity at an altitude $h = 32\\text{ km}$ above the Earth's surface ($R = 6400\\text{ km}$) is $x\\%$. Find $x$.",
    "correctAnswer": "1",
    "explanation": "Since $h = 32\\text{ km} \\ll R = 6400\\text{ km}$:\n$$\\%\\text{ decrease} = \\frac{2h}{R} \\times 100 = \\frac{2 \\times 32}{6400} \\times 100 = \\frac{64}{64} = 1\\%$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "A body weighs $72\\text{ N}$ on the surface of the Earth. What is its weight in Newtons at an altitude $h = R/2$ above the surface?",
    "correctAnswer": "32",
    "explanation": "$$g_h = \\frac{g}{(1 + h/R)^2} = \\frac{g}{(1 + 1/2)^2} = \\frac{g}{(3/2)^2} = \\frac{4}{9}g$$\n$$W_h = \\frac{4}{9} W = \\frac{4}{9} \\times 72 = 32\\text{ N}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what latitude $\\lambda$ (in degrees) is the effective acceleration due to gravity equal to $g - \\frac{3}{4}R\\omega^2$?",
    "correctAnswer": "30",
    "explanation": "$$g' = g - R\\omega^2\\cos^2\\lambda = g - \\frac{3}{4}R\\omega^2 \\implies \\cos^2\\lambda = \\frac{3}{4} \\implies \\cos\\lambda = \\frac{\\sqrt{3}}{2} \\implies \\lambda = 30^\\circ$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "If the acceleration due to gravity at depth $d$ is equal to that at height $h = 10\\text{ km}$ above the surface (where $h \\ll R$), find the depth $d$ in kilometres.",
    "correctAnswer": "20",
    "explanation": "For $h \\ll R$, $d = 2h = 2(10) = 20\\text{ km}$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "A body weighs $200\\text{ N}$ on the surface of Earth. At what depth (in terms of $R$) will its weight become $50\\text{ N}$? (Enter $d/R$ as a decimal fraction, e.g. 0.75)",
    "correctAnswer": "0.75",
    "explanation": "$$W_d = W\\left(1 - \\frac{d}{R}\\right) \\implies 50 = 200\\left(1 - \\frac{d}{R}\\right) \\implies 1 - \\frac{d}{R} = \\frac{1}{4} \\implies \\frac{d}{R} = \\frac{3}{4} = 0.75$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "The acceleration due to gravity on the surface of the Moon is $1.67\\text{ m/s}^2$. If the radius of the Moon is $1.74 \\times 10^6\\text{ m}$, what is the mass of the Moon in units of $10^{22}\\text{ kg}$ rounded to one decimal place? (Take $G = 6.67 \\times 10^{-11}\\,\\text{N}\\cdot\\text{m}^2/\\text{kg}^2$)",
    "correctAnswer": "7.6",
    "explanation": "$$M = \\frac{g R^2}{G} = \\frac{1.67 \\times (1.74 \\times 10^6)^2}{6.67 \\times 10^{-11}} = \\frac{1.67 \\times 3.0276 \\times 10^{12}}{6.67 \\times 10^{-11}} = \\frac{5.056 \\times 10^{12}}{6.67 \\times 10^{-11}} \\approx 7.58 \\times 10^{22}\\text{ kg} \\approx 7.6 \\times 10^{22}\\text{ kg}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "If the angular speed of rotation of the Earth is increased so that bodies on the equator fly off (weightlessness), what would be the duration of the day in minutes rounded to the nearest integer? (Take $R = 6400\\text{ km}, g = 10\\text{ m/s}^2$)",
    "correctAnswer": "84",
    "explanation": "$$T = 2\\pi\\sqrt{\\frac{R}{g}} = 2\\pi\\sqrt{\\frac{6.4 \\times 10^6}{10}} = 2\\pi \\times 800 = 1600\\pi\\text{ s} = \\frac{5026.5}{60} \\approx 83.78 \\approx 84\\text{ minutes}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "A planet has twice the density of Earth and half the radius of Earth. If $g$ on Earth is $9.8\\text{ m/s}^2$, what is the acceleration due to gravity on the planet in $\\text{m/s}^2$?",
    "correctAnswer": "9.8",
    "explanation": "$$g = \\frac{4}{3}\\pi G\\rho R \\propto \\rho R$$\n$$g' = g \\left(\\frac{2\\rho}{\\rho}\\right)\\left(\\frac{R/2}{R}\\right) = g(2)(1/2) = g = 9.8\\text{ m/s}^2$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what height $h$ in terms of $R$ is the acceleration due to gravity reduced by $75\\%$? (i.e. $g_h = 0.25 g$; enter $h/R$ as an integer)",
    "correctAnswer": "1",
    "explanation": "$$g_h = \\frac{g}{(1 + h/R)^2} = 0.25 g = \\frac{1}{4}g \\implies 1 + h/R = 2 \\implies h = R$$\nThus $h/R = 1$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "A body weighs $90\\text{ N}$ on the surface of Earth. How much does it weigh in Newtons at a height $h = 2R$ above the surface?",
    "correctAnswer": "10",
    "explanation": "$$W_h = \\frac{W}{(1 + h/R)^2} = \\frac{90}{(1 + 2)^2} = \\frac{90}{9} = 10\\text{ N}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "The percentage change in $g$ when moving from the surface of Earth to an altitude of $64\\text{ km}$ ($R = 6400\\text{ km}$) is $x\\%$. Find the magnitude of $x$.",
    "correctAnswer": "2",
    "explanation": "$$\\frac{\\Delta g}{g} \\times 100 = \\frac{2h}{R} \\times 100 = \\frac{2 \\times 64}{6400} \\times 100 = 2\\%$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At what depth $d$ below the Earth's surface does the acceleration due to gravity decrease by $20\\%$? (Take $R = 6400\\text{ km}$; answer in km)",
    "correctAnswer": "1280",
    "explanation": "$$\\frac{d}{R} = 0.20 \\implies d = 0.20 \\times 6400 = 1280\\text{ km}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "If a body is taken to an altitude equal to $3R$, the ratio of the acceleration due to gravity at that altitude to that on the surface is $1/n$. Find the integer $n$.",
    "correctAnswer": "16",
    "explanation": "$$g_h = \\frac{g}{(1 + 3)^2} = \\frac{g}{16} \\implies n = 16$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "The acceleration due to gravity on the surface of a planet is $4.9\\text{ m/s}^2$. If its mass is equal to Earth's mass, the radius of the planet in terms of Earth's radius $R_E$ is $\\sqrt{k} R_E$. Find the integer $k$.",
    "correctAnswer": "2",
    "explanation": "$$g = \\frac{GM}{R^2} \\implies \\frac{g'}{g} = \\frac{R_E^2}{R'^2} = \\frac{4.9}{9.8} = \\frac{1}{2} \\implies R'^2 = 2 R_E^2 \\implies R' = \\sqrt{2} R_E$$\nThus $k = 2$.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "If the speed of Earth's rotation increases such that the acceleration due to gravity at the equator becomes zero, what would be the value of $g$ at the poles in $\\text{m/s}^2$? (Assuming original $g = 9.8\\text{ m/s}^2$)",
    "correctAnswer": "9.8",
    "explanation": "At the poles, latitude $\\lambda = 90^\\circ$, so centrifugal force is zero ($R\\omega^2\\cos^2(90^\\circ) = 0$). Hence $g_{\\text{pole}} = g = 9.8\\text{ m/s}^2$, completely unaffected by rotation.",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "A pendulum clock beats seconds on the surface of Earth ($T = 2\\text{ s}$). If it is taken to a height $h = R$, what will be its new time period in seconds?",
    "correctAnswer": "4",
    "explanation": "At $h = R$, $g' = g/4$.\n$$T' = 2\\pi \\sqrt{\\frac{L}{g'}} = 2\\pi \\sqrt{\\frac{L}{g/4}} = 2 \\times 2\\pi\\sqrt{\\frac{L}{g}} = 2 T = 2 \\times 2 = 4\\text{ s}$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "If the mass of the Earth is increased by $2\\%$ without changing its size, by what percentage does the acceleration due to gravity on its surface increase?",
    "correctAnswer": "2",
    "explanation": "$$g = \\frac{GM}{R^2} \\propto M \\implies \\frac{\\Delta g}{g} = \\frac{\\Delta M}{M} = 2\\%$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  },
  {
    "type": "NUMERICAL",
    "subject": "Physics",
    "chapter": "Gravitation",
    "subTopic": "Acceleration due to gravity (variation with height, depth, latitude)",
    "question": "At a certain height $h$ above the Earth's surface, the acceleration due to gravity is $64\\%$ of its value on the surface. What is $h$ in terms of Earth's radius $R$? (Enter $h/R$ as a decimal fraction)",
    "correctAnswer": "0.25",
    "explanation": "$$\\frac{g}{(1 + h/R)^2} = 0.64 g \\implies 1 + h/R = \\frac{1}{\\sqrt{0.64}} = \\frac{1}{0.8} = 1.25 \\implies h/R = 0.25$$",
    "difficulty": "medium",
    "marks": 4,
    "negativeMarks": 0,
    "examType": "JEE Mains"
  }
];
